import type { BrowserChildInterventionPageModel } from './browser-child-intervention-page';

const BrowserChildInterventionPageDefaults = {
  BlockMarker: 'OCENTRA_MANAGED_BROWSER_BLOCKED',
  DefaultBridge: 'browser-child-intervention-template',
} as const;

export const BrowserChildInterventionPageSamples: readonly BrowserChildInterventionPageModel[] = [
  {
    action: 'block',
    blockMarker: BrowserChildInterventionPageDefaults.BlockMarker,
    bridge: BrowserChildInterventionPageDefaults.DefaultBridge,
    deliveryState: 'block-page-rendered',
    outcome: 'blocked',
    parentRequestEnabled: true,
    reason: 'Your family rule blocks this exact video URL.',
    requestedUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ruleId: 'blocked-youtube-video-url',
    ruleLabel: 'Disallowed YouTube video URL',
    ruleMarker: BrowserChildInterventionPageDefaults.BlockMarker,
    targetType: 'video',
  },
  {
    action: 'approval-hold',
    blockMarker: BrowserChildInterventionPageDefaults.BlockMarker,
    bridge: BrowserChildInterventionPageDefaults.DefaultBridge,
    deliveryState: 'approval-hold-rendered',
    outcome: 'approval-required',
    parentRequestEnabled: true,
    reason: 'Creating a social account needs parent approval first.',
    requestedUrl: 'https://www.instagram.com/accounts/emailsignup/',
    ruleId: 'social-signup-approval-hold',
    ruleLabel: 'Social account creation approval hold',
    ruleMarker: 'OCENTRA_MANAGED_BROWSER_APPROVAL_HOLD',
    targetType: 'social-account-creation',
  },
  {
    action: 'warn',
    blockMarker: BrowserChildInterventionPageDefaults.BlockMarker,
    bridge: BrowserChildInterventionPageDefaults.DefaultBridge,
    deliveryState: 'warn-page-rendered',
    outcome: 'warned',
    parentRequestEnabled: true,
    reason: 'Short-video feeds are set to warning mode for this device.',
    requestedUrl: 'https://www.tiktok.com/@ocentra/video/1',
    ruleId: 'social-short-video-warning',
    ruleLabel: 'Social short-video route warning',
    ruleMarker: 'OCENTRA_MANAGED_BROWSER_WARNED',
    targetType: 'social-short-video-feed',
  },
  {
    action: 'checking-hold',
    blockMarker: BrowserChildInterventionPageDefaults.BlockMarker,
    bridge: BrowserChildInterventionPageDefaults.DefaultBridge,
    deliveryState: 'checking-hold-rendered',
    outcome: 'held',
    parentRequestEnabled: false,
    reason: 'Ocentra is checking the game page against the latest family rules.',
    requestedUrl: 'https://poki.com/en/g/example-game',
    ruleId: 'browser-game-checking-hold',
    ruleLabel: 'Browser game checking hold',
    ruleMarker: 'OCENTRA_MANAGED_BROWSER_CHECKING_HOLD',
    targetType: 'browser-game',
  },
  {
    action: 'time-limit',
    blockMarker: BrowserChildInterventionPageDefaults.BlockMarker,
    bridge: BrowserChildInterventionPageDefaults.DefaultBridge,
    deliveryState: 'block-page-rendered',
    outcome: 'blocked',
    parentRequestEnabled: true,
    reason: 'The daily browser-game quota for this device has been used.',
    requestedUrl: 'https://www.xbox.com/en-US/play',
    ruleId: 'cloud-gaming-quota-reached',
    ruleLabel: 'Cloud gaming quota reached',
    ruleMarker: 'OCENTRA_MANAGED_BROWSER_TIME_LIMIT',
    targetType: 'cloud-gaming',
  },
  {
    action: 'parent-review',
    blockMarker: BrowserChildInterventionPageDefaults.BlockMarker,
    bridge: BrowserChildInterventionPageDefaults.DefaultBridge,
    deliveryState: 'manual-required',
    outcome: 'manual-required',
    parentRequestEnabled: true,
    reason: 'This browser needs parent setup before Ocentra can unblock it automatically.',
    requestedUrl: 'https://example.com/manual-review',
    ruleId: 'manual-parent-review',
    ruleLabel: 'Manual parent review',
    ruleMarker: 'OCENTRA_MANAGED_BROWSER_MANUAL_REVIEW',
    targetType: 'browser-session',
  },
] as const;
