import { decodeDisplayText } from './display-text';
import {
  PortalAgentCommand,
  type PortalAgentCommandName,
  PortalAgentLanHouseholdActionDeviceKindField,
  PortalAgentLanHouseholdActionKind,
  PortalAgentLanHouseholdDeviceKindValues,
  PortalAgentLanIntentKind,
  PortalAgentLanParentAuthority,
  PortalAgentPeerDefaults,
  PortalAgentProtocolField,
  PortalAgentTargetDefaults,
  PortalConnectionState,
  PortalRoute,
  PortalRouteHashPrefix,
  PortalRouteHashQuerySeparator,
  PortalRouteLiteral,
  PortalRouteSchema,
} from './portal-contract-adapter';
import {
  decodePortalClipboardText,
  decodePortalDetailValue,
  decodeTrackingStatusProofArtifact,
  type PortalDetailValue,
  type TrackingStatusProofArtifact,
} from './portal-contract-text-contracts';
import { PortalFormatting } from './formatting';
import { PortalBrowserInventoryFields, PortalDetails, PortalReadableValues } from './details';
import { PortalDiagnostics } from './diagnostics';
import { GeneratedPortalTrackingContracts } from './generated-portal-contracts';
import {
  createLocalAiRuntimePanelIntent,
  type LocalAiRuntimePanelCard,
  type LocalAiRuntimePanelDetail,
  type LocalAiRuntimePanelIntent,
} from './local-ai-runtime-panel';
import {
  PortalFrameChromeNumberFields,
  PortalCarouselContentNumberFields,
  PortalCarouselFrameNumberFields,
  PortalCarouselRailNumberFields,
  PortalFrameContentBooleanFields,
  PortalFrameContentNumberFields,
  PortalFrameGeometryNumberFields,
  PortalGoldenCardBooleanFields,
  PortalGoldenCardContentNumberFields,
  PortalGoldenCardFrameNumberFields,
  PortalFrameInnerEdgeNumberFields,
  PortalFrameInnerGapNumberFields,
  PortalFrameInnerSegmentNumberFields,
  PortalFrameInnerShapeNumberFields,
  PortalFrameOuterEdgeNumberFields,
  PortalFrameOuterGapNumberFields,
  PortalFrameOuterSegmentNumberFields,
  PortalFrameOuterShapeNumberFields,
  PortalFrameShellNumberFields,
  PortalFrameSlotNumberFields,
  PortalFrameTuner,
  portalFrameCssNumber,
  portalFrameCssOpacity,
  portalFrameCssPercent,
  portalFrameCssPixel,
  type PortalFrameCssStyle,
  type PortalFrameCssValue,
  type PortalFrameBooleanField,
  type PortalFrameColorField,
  type PortalFrameNumberField,
  type PortalFrameTargetValue,
  type PortalFrameTunerFrameSectionValue,
} from './frame-tuner';
import { PortalFrameColorFields, PortalFrameTunerFrameSections } from './frame-tuner-lists';
import { PortalAssets, PortalExternalLinks, PortalUnifiedChrome } from './unified-chrome';
import {
  createPortalAppLayoutButtonDraft,
  createPortalAppLayoutFoldoutDraft,
  defaultPortalAppLayoutContentDraft,
  defaultPortalAppLayoutSurfaceContent,
  normalizePortalAppLayoutContentDraft,
  normalizePortalAppLayoutSurfaceContentDraft,
  type PortalAppLayoutButtonDraft,
  type PortalAppLayoutContentAreaKey,
  type PortalAppLayoutContentDraft,
  type PortalAppLayoutFoldoutDraft,
  type PortalAppLayoutSurfaceContentDraft,
  type PortalAppLayoutSurfaceKey,
  type PortalAppLayoutTone,
} from './app-layout';
import {
  PARENT_ASSISTANT_PORTAL_NEW_CHAT_ACTION,
  PARENT_ASSISTANT_PORTAL_QUICK_ACTIONS,
  type ParentAssistantPortalQuickAction,
  type ParentAssistantPortalQuickActionId,
} from './parent-assistant-chat';
import {
  PARENT_PORTAL_CONTENT,
  PARENT_PORTAL_ROUTE,
  PARENT_PORTAL_ROUTE_CONTEXT,
  parentPortalRouteContext,
  type ParentPortalContent,
  type ParentPortalIconName,
  type ParentPortalPageMode,
  type ParentPortalRow,
  type ParentPortalRowSource,
  type ParentPortalRouteContext,
  type ParentPortalTabId,
  type ParentPortalTone,
} from './parent-portal-data';
import {
  PARENT_PORTAL_SERVICE_STATE,
  resolveParentPortalServiceState,
  type ParentPortalServiceState,
} from './parent-portal-service-state';
import { TrackingStatusProofArtifacts } from './tracking-status-proof-artifacts';
import {
  trackingFamilyDashboardHostedRollupProof,
  trackingStatusLiveSummary,
  trackingStatusProofRows,
  trackingStatusServiceDataCoverage,
  trackingUnsupportedManualPlatformProof,
} from './tracking-status-panel';
import type {
  TrackingFamilyDashboardHostedRollupProof,
  TrackingFamilyDashboardHostedRollupRow,
  TrackingStatusLiveCitation,
  TrackingStatusLiveProjectionInput,
  TrackingStatusLiveSummary,
  TrackingStatusProofRow,
  TrackingStatusServiceDataCoverage,
  TrackingUnsupportedManualPlatformProof,
  TrackingUnsupportedManualPlatformRow,
} from './tracking-status-panel';
import {
  TrackingEvidenceDrawerHostedUiProofDetails,
  trackingEvidenceDrawerHostedUiProof,
  type TrackingEvidenceDrawerHostedUiProof,
  type TrackingEvidenceDrawerSourceCitation,
} from './tracking-evidence-drawer-hosted-ui-proof';
import {
  trackingRetentionSettingsHostedUiProof,
  type TrackingRetentionSettingsHostedUiProof,
  type TrackingRetentionSettingsHostedUiRow,
  type TrackingRetentionSettingsWritePreflight,
} from './tracking-retention-settings-hosted-ui-proof';
import {
  PARENT_PORTAL_NAV_LABELS,
  type ParentPortalHashRoutePath,
  type ParentPortalNavGroup,
  type ParentPortalNavGroupId,
  type ParentPortalNavItem,
  type ParentPortalNavLabel,
  type ParentPortalNavSectionLabel,
} from './parent-portal-nav';
import {
  parseActivityMemoryGraphReadModel,
  type PortalActivityMemoryGraphEdge,
  type PortalActivityMemoryGraphNode,
  type PortalActivityMemoryGraphNodeId,
  type PortalActivityMemoryGraphReadModel,
} from './activity-memory-graph';
import {
  PortalDevToolWindow,
  PortalAiRuntimeRoutes,
  PortalRouteDescriptors,
  PortalAppGameParentSurfaceRoutes,
  PortalBrowserParentSurfaceRoutes,
  PortalNetworkEvidenceDrawerRoutes,
  PortalRouteGroup,
  PortalRoutes,
  PortalScreenSettingsRoutes,
  PortalScreenSummaryRoutes,
  PortalSidebarRouteDescriptors,
  PortalTrackingStatusRoutes,
  isPortalAiRuntimeRoute,
  isPortalAppGameParentSurfaceRoute,
  isPortalBrowserParentSurfaceRoute,
  isPortalNetworkEvidenceDrawerRoute,
  isPortalScreenSettingsRoute,
  isPortalScreenSummaryRoute,
  isPortalTrackingStatusRoute,
  portalDevToolUrl,
  portalRouteHashPath,
  portalRouteHashPathWithQuery,
  type PortalRouteHashPath,
  type PortalRouteHashQueryPath,
  type PortalRouteDescriptor,
  type PortalRouteGroupValue,
} from './routes';
import {
  DEFAULT_PORTAL_BACKGROUND_CONFIG,
  DEFAULT_PORTAL_BACKGROUND_DARK_COLORS,
  DEFAULT_PORTAL_BACKGROUND_LIGHT_COLORS,
  PortalBackgroundRuntime,
  normalizePortalBackgroundConfig,
  portalBackgroundAppRenderConfig,
  portalBackgroundRenderConfig,
  type PortalBackgroundConfig,
  type PortalBackgroundRenderConfig,
  type PortalBackgroundThemeColors,
} from './portal-background';
import {
  PORTAL_BACKGROUND_SVG_HEIGHT,
  PORTAL_BACKGROUND_SVG_WIDTH,
  portalBackgroundSvgContent,
  portalBackgroundSvgMarkup,
} from './portal-background-svg-markup';
import {
  BrowserChildInterventionPageDefaults,
  BrowserChildInterventionPageSamples,
  renderBrowserChildInterventionPage,
  type BrowserChildInterventionPageAction,
  type BrowserChildInterventionPageBackdrop,
  type BrowserChildInterventionPageModel,
  type BrowserChildInterventionPageTheme,
} from './browser-child-intervention-page';
import {
  createSocialChildInterventionPageModels,
  type SocialChildInterventionPageModelOptions,
  type SocialChildInterventionPageModelResult,
  type SocialChildInterventionRequestedUrlResolver,
} from './social-child-intervention-page-model';

const PortalDom = {
  RootSelector: '#app',
  HashPrefix: PortalRouteHashPrefix,
  HashQuerySeparator: PortalRouteHashQuerySeparator,
  BackgroundDevToolHashFlag: 'bg-only=1',
  EmptyHashRoute: '',
  Ids: {
    AppLoading: 'app-loading',
  },
  Runtime: {
    HideAppLoading: '__hideAppLoading',
    Undefined: 'undefined',
  },
  Tags: {
    Aside: 'aside',
    Anchor: 'a',
    Button: 'button',
    Code: 'code',
    DefinitionDescription: 'dd',
    DefinitionList: 'dl',
    DefinitionTerm: 'dt',
    Details: 'details',
    Division: 'div',
    Header: 'header',
    HeadingOne: 'h1',
    HeadingTwo: 'h2',
    ListItem: 'li',
    Main: 'main',
    Navigation: 'nav',
    OrderedList: 'ol',
    Paragraph: 'p',
    Section: 'section',
    Strong: 'strong',
    SummaryTag: 'summary',
    Span: 'span',
    Image: 'img',
    TextArea: 'textarea',
    UnorderedList: 'ul',
  },
  Classes: {
    AppChrome: 'app-chrome',
    AppContent: 'app-content',
    AppFrame: 'app-frame',
    AppHeader: 'app-header',
    AppMain: 'app-main',
    AppRightRail: 'app-right-rail',
    AppSidebar: 'app-sidebar',
    AppStatus: 'app-status',
    AppStatusBar: 'app-status-bar',
    AppToolbar: 'app-toolbar',
    AppLoadingHidden: 'hidden',
    AppLoadingHide: 'hide',
    CapabilityGrid: 'capability-grid',
    CapabilityItem: 'capability-item',
    ClipboardBuffer: 'clipboard-buffer',
    ClassNameSeparator: ' ',
    CommandGrid: 'command-grid',
    ControlCard: 'control-card',
    ControlCardAccentPrimary: 'control-card-accent-primary',
    ControlCardAccentPrivacy: 'control-card-accent-privacy',
    ControlCardAccentWarn: 'control-card-accent-warn',
    ControlCardBody: 'control-card-body',
    ControlCardContent: 'control-card-content',
    ControlCardGlyph: 'control-card-glyph',
    ControlCardGoldenArt: 'control-card-golden-art',
    ControlCardHeader: 'control-card-header',
    ControlCardStatus: 'control-card-status',
    ControlCardTip: 'control-card-tip',
    ControlCardTipBody: 'control-card-tip-body',
    ControlCardTipTitle: 'control-card-tip-title',
    ControlCarouselCount: 'control-carousel-count',
    ControlCarouselFrame: 'control-carousel-frame',
    ControlCarouselHandle: 'control-carousel-handle',
    ControlCarouselHandleLeft: 'control-carousel-handle-left',
    ControlCarouselHandleRight: 'control-carousel-handle-right',
    ControlCarouselIntro: 'control-carousel-intro',
    ControlCarouselLabel: 'control-carousel-label',
    ControlCarouselPager: 'control-carousel-pager',
    ControlCarouselPill: 'control-carousel-pill',
    ControlCarouselPillActive: 'control-carousel-pill-active',
    ControlCarouselRail: 'control-carousel-rail',
    ControlCarouselStage: 'control-carousel-stage',
    ControlCarouselTitle: 'control-carousel-title',
    ControlDeck: 'control-deck',
    ControlDeckHeader: 'control-deck-header',
    ControlDeckIntro: 'control-deck-intro',
    DeviceRuleScopePanel: 'device-rule-scope-panel',
    CommandResultEmpty: 'command-result-empty',
    CommandResultHeader: 'command-result-header',
    CommandResultPanel: 'command-result-panel',
    CommandResultTab: 'command-result-tab',
    CommandResultTabActive: 'command-result-tab-active',
    CopyResultButton: 'copy-result-button',
    DeveloperRouteContent: 'portal-dev-route-content',
    DeveloperRoutePanel: 'portal-dev-route-panel',
    DeveloperRouteToolbar: 'portal-dev-route-toolbar',
    Header: 'header',
    Log: 'log',
    LogLevelPrefix: 'log-',
    LogList: 'log-list',
    PageDescription: 'page-description',
    PageHeader: 'page-header',
    PageTitle: 'page-title',
    PanelGrid: 'panel-grid',
    PanelGridWide: 'panel-grid-wide',
    ProductDashboard: 'product-dashboard',
    ProductHeroCopy: 'product-hero-copy',
    ProductMetric: 'product-metric',
    ProductMetricLabel: 'product-metric-label',
    ProductMetricMeta: 'product-metric-meta',
    ProductMetricValue: 'product-metric-value',
    ProductStatusCard: 'product-status-card',
    ProductStatusCardBadge: 'product-status-card-badge',
    ProductStatusCardBody: 'product-status-card-body',
    ProductStatusCardEvidence: 'product-status-card-evidence',
    ProductStatusCardManaged: 'product-status-card-managed',
    ProductStatusCardMedia: 'product-status-card-media',
    ProductStatusCardMeta: 'product-status-card-meta',
    ProductStatusCardMetaItem: 'product-status-card-meta-item',
    ProductStatusCardMetaLabel: 'product-status-card-meta-label',
    ProductStatusCardMetaValue: 'product-status-card-meta-value',
    ProductStatusCardProtection: 'product-status-card-protection',
    ProductBadge: 'product-badge',
    ProductBrand: 'product-brand',
    ProductBrandMark: 'product-brand-mark',
    ProductEyebrow: 'product-eyebrow',
    ProductPanelNote: 'product-panel-note',
    ProductShellHero: 'product-shell-hero',
    ProductSidebarPanel: 'product-sidebar-panel',
    RightRailCard: 'right-rail-card',
    RightRailStrip: 'right-rail-strip',
    RightRailTitle: 'right-rail-title',
    RouteTabs: 'route-tabs',
    RouteGroup: 'route-group',
    RouteGroupLabel: 'route-group-label',
    RouteLink: 'route-link',
    RouteLinkArrow: 'route-link-arrow',
    RouteLinkCopy: 'route-link-copy',
    RouteLinkDescription: 'route-link-description',
    RouteLinkFrame: 'route-link-frame',
    RouteLinkIcon: 'route-link-icon',
    RouteLinkLabel: 'route-link-label',
    Routes: 'routes',
    Shell: 'shell',
    SettingsThemePanel: 'settings-theme-panel',
    SidebarActions: 'sidebar-actions',
    SidebarDeviceFrame: 'sidebar-device-frame',
    SidebarNavFrame: 'sidebar-nav-frame',
    SidebarReconnectButton: 'sidebar-reconnect-button',
    SidebarStatusButton: 'sidebar-status-button',
    State: 'state',
    Summary: 'summary',
    ThemeToggle: 'theme-toggle',
    ThemeToggleButton: 'theme-toggle-button',
    ThemeToggleButtonActive: 'theme-toggle-button-active',
    TrackingStatusOverlay: 'tracking-status-overlay',
    TrackingStatusOverlayContent: 'tracking-status-overlay-content',
    TrackingStatusOverlayGrid: 'tracking-status-overlay-grid',
    TrackingStatusOverlayHeader: 'tracking-status-overlay-header',
    TrackingStatusOverlayMeta: 'tracking-status-overlay-meta',
  },
  Attributes: {
    AriaCurrent: 'aria-current',
    AriaHidden: 'aria-hidden',
    AriaSelected: 'aria-selected',
    DataRouteId: 'data-ocentra-parent-route-id',
    DataTrackingProof: 'data-ocentra-tracking-proof',
    DataTheme: 'data-theme',
    Page: 'page',
    True: 'true',
    False: 'false',
    ReadOnly: 'readonly',
    Role: 'role',
    Tab: 'tab',
    TabList: 'tablist',
    TrackingProofCitationDetail: 'service-backed-citation-detail',
    TrackingProofChildCheckIn: 'child-check-in',
    TrackingProofChildRuntimeUi: 'child-runtime-ui',
    TrackingProofEvidenceDrawer: 'service-backed-evidence-drawer',
    TrackingProofFamilyDashboard: 'family-dashboard-rollup',
    TrackingProofNotificationParentSurfaceHistory: 'notification-parent-surface-history-ui',
    TrackingProofParentActionReadiness: 'parent-action-readiness-ui',
    TrackingProofMissingDevice: 'missing-device-ui',
    TrackingProofReportPolicyConsumer: 'report-policy-consumer-ui',
    TrackingProofReportExport: 'report-export-ui',
    TrackingProofRetentionSettings: 'retention-settings-ui',
  },
  Events: {
    Click: 'click',
    Close: 'close',
    Error: 'error',
    HashChange: 'hashchange',
    Message: 'message',
    Open: 'open',
    Storage: 'storage',
    TransitionEnd: 'transitionend',
  },
  ButtonType: {
    Button: 'button',
    Submit: 'submit',
  },
} as const;

const PortalTheme = {
  Dark: 'dark',
  Light: 'light',
  LocalStorageKey: 'ocentra-parent-theme',
  MediaDark: '(prefers-color-scheme: dark)',
} as const;
type PortalThemeValue = (typeof PortalTheme)[keyof Pick<typeof PortalTheme, 'Dark' | 'Light'>];

const PortalClipboard = {
  CommandCopy: 'copy',
} as const;

const PortalLanPairingScan = {
  PendingIndicatorMs: 8000,
  Text: {
    HeaderTitle: decodeDisplayText('Local Area Network'),
    Scan: decodeDisplayText('SCAN'),
    Scanning: decodeDisplayText('SCANNING'),
    ScanLocalAreaNetwork: decodeDisplayText('Scan Local Area Network'),
    OpenLocalAreaNetworkGuide: decodeDisplayText('Open Local Area Network guide'),
  },
} as const;

const PortalTiming = {
  CopyFeedbackMs: 1200,
} as const;

const PortalTrackingRetentionSettingsWriteDefaults = GeneratedPortalTrackingContracts.RetentionSettingsWrite.Defaults;

const PortalEnvironment = {
  AgentWebSocketUrl: 'VITE_AGENT_WS_URL',
  ParentDevBridgeUrl: 'VITE_PARENT_DEV_BRIDGE_URL',
  BrowserParentExplanationProofBundle: 'VITE_BROWSER_PARENT_EXPLANATION_PROOF_BUNDLE',
  SocialAuditExplanationProofBundle: 'VITE_SOCIAL_AUDIT_EXPLANATION_PROOF_BUNDLE',
} as const;

export {
  PortalFormatting,
  PortalBrowserInventoryFields,
  PortalDetails,
  PortalReadableValues,
  PortalDiagnostics,
  createLocalAiRuntimePanelIntent,
  PortalFrameChromeNumberFields,
  PortalCarouselContentNumberFields,
  PortalCarouselFrameNumberFields,
  PortalCarouselRailNumberFields,
  PortalFrameContentBooleanFields,
  PortalFrameContentNumberFields,
  PortalFrameGeometryNumberFields,
  PortalGoldenCardBooleanFields,
  PortalGoldenCardContentNumberFields,
  PortalGoldenCardFrameNumberFields,
  PortalFrameInnerEdgeNumberFields,
  PortalFrameInnerGapNumberFields,
  PortalFrameInnerSegmentNumberFields,
  PortalFrameInnerShapeNumberFields,
  PortalFrameOuterEdgeNumberFields,
  PortalFrameOuterGapNumberFields,
  PortalFrameOuterSegmentNumberFields,
  PortalFrameOuterShapeNumberFields,
  PortalFrameShellNumberFields,
  PortalFrameSlotNumberFields,
  PortalFrameTuner,
  portalFrameCssNumber,
  portalFrameCssOpacity,
  portalFrameCssPercent,
  portalFrameCssPixel,
  PortalFrameColorFields,
  PortalFrameTunerFrameSections,
  PortalAssets,
  PortalExternalLinks,
  PortalUnifiedChrome,
  createPortalAppLayoutButtonDraft,
  createPortalAppLayoutFoldoutDraft,
  defaultPortalAppLayoutContentDraft,
  defaultPortalAppLayoutSurfaceContent,
  normalizePortalAppLayoutContentDraft,
  normalizePortalAppLayoutSurfaceContentDraft,
  PARENT_ASSISTANT_PORTAL_NEW_CHAT_ACTION,
  PARENT_ASSISTANT_PORTAL_QUICK_ACTIONS,
  PARENT_PORTAL_CONTENT,
  PARENT_PORTAL_ROUTE,
  PARENT_PORTAL_ROUTE_CONTEXT,
  parentPortalRouteContext,
  PARENT_PORTAL_SERVICE_STATE,
  resolveParentPortalServiceState,
  TrackingStatusProofArtifacts,
  trackingFamilyDashboardHostedRollupProof,
  trackingStatusLiveSummary,
  trackingStatusProofRows,
  trackingStatusServiceDataCoverage,
  trackingUnsupportedManualPlatformProof,
  PortalTrackingRetentionSettingsWriteDefaults,
  TrackingEvidenceDrawerHostedUiProofDetails,
  trackingEvidenceDrawerHostedUiProof,
  trackingRetentionSettingsHostedUiProof,
  PARENT_PORTAL_NAV_LABELS,
  parseActivityMemoryGraphReadModel,
  PortalClipboard,
  PortalAgentCommand,
  PortalAgentLanHouseholdActionDeviceKindField,
  PortalAgentLanHouseholdActionKind,
  PortalAgentLanHouseholdDeviceKindValues,
  PortalAgentLanIntentKind,
  PortalAgentLanParentAuthority,
  PortalAgentPeerDefaults,
  PortalAgentProtocolField,
  PortalAgentTargetDefaults,
  PortalConnectionState,
  PortalDevToolWindow,
  PortalAiRuntimeRoutes,
  PortalRouteDescriptors,
  PortalAppGameParentSurfaceRoutes,
  PortalBrowserParentSurfaceRoutes,
  PortalNetworkEvidenceDrawerRoutes,
  PortalRoute,
  PortalRouteGroup,
  PortalRouteLiteral,
  PortalRouteSchema,
  PortalRoutes,
  PortalScreenSettingsRoutes,
  PortalScreenSummaryRoutes,
  PortalSidebarRouteDescriptors,
  PortalTrackingStatusRoutes,
  decodePortalClipboardText,
  decodePortalDetailValue,
  decodeTrackingStatusProofArtifact,
  isPortalAiRuntimeRoute,
  isPortalAppGameParentSurfaceRoute,
  isPortalBrowserParentSurfaceRoute,
  isPortalNetworkEvidenceDrawerRoute,
  isPortalScreenSettingsRoute,
  isPortalScreenSummaryRoute,
  isPortalTrackingStatusRoute,
  portalDevToolUrl,
  portalRouteHashPath,
  portalRouteHashPathWithQuery,
  DEFAULT_PORTAL_BACKGROUND_CONFIG,
  DEFAULT_PORTAL_BACKGROUND_DARK_COLORS,
  DEFAULT_PORTAL_BACKGROUND_LIGHT_COLORS,
  PortalBackgroundRuntime,
  normalizePortalBackgroundConfig,
  portalBackgroundAppRenderConfig,
  portalBackgroundRenderConfig,
  PORTAL_BACKGROUND_SVG_HEIGHT,
  PORTAL_BACKGROUND_SVG_WIDTH,
  portalBackgroundSvgContent,
  portalBackgroundSvgMarkup,
  BrowserChildInterventionPageDefaults,
  BrowserChildInterventionPageSamples,
  renderBrowserChildInterventionPage,
  createSocialChildInterventionPageModels,
  PortalDom,
  PortalEnvironment,
  PortalLanPairingScan,
  PortalTheme,
  PortalTiming,
  type LocalAiRuntimePanelCard,
  type LocalAiRuntimePanelDetail,
  type LocalAiRuntimePanelIntent,
  type PortalFrameCssStyle,
  type PortalFrameCssValue,
  type PortalFrameBooleanField,
  type PortalFrameColorField,
  type PortalFrameNumberField,
  type PortalFrameTargetValue,
  type PortalFrameTunerFrameSectionValue,
  type PortalAppLayoutButtonDraft,
  type PortalAppLayoutContentAreaKey,
  type PortalAppLayoutContentDraft,
  type PortalAppLayoutFoldoutDraft,
  type PortalAppLayoutSurfaceContentDraft,
  type PortalAppLayoutSurfaceKey,
  type PortalAppLayoutTone,
  type ParentAssistantPortalQuickAction,
  type ParentAssistantPortalQuickActionId,
  type ParentPortalContent,
  type ParentPortalIconName,
  type ParentPortalPageMode,
  type ParentPortalRow,
  type ParentPortalRowSource,
  type ParentPortalRouteContext,
  type ParentPortalTabId,
  type ParentPortalTone,
  type ParentPortalServiceState,
  type TrackingFamilyDashboardHostedRollupProof,
  type TrackingFamilyDashboardHostedRollupRow,
  type TrackingStatusLiveCitation,
  type TrackingStatusLiveProjectionInput,
  type TrackingStatusLiveSummary,
  type TrackingStatusProofRow,
  type TrackingStatusServiceDataCoverage,
  type TrackingUnsupportedManualPlatformProof,
  type TrackingUnsupportedManualPlatformRow,
  type TrackingEvidenceDrawerHostedUiProof,
  type TrackingEvidenceDrawerSourceCitation,
  type TrackingRetentionSettingsHostedUiProof,
  type TrackingRetentionSettingsHostedUiRow,
  type TrackingRetentionSettingsWritePreflight,
  type ParentPortalHashRoutePath,
  type ParentPortalNavGroup,
  type ParentPortalNavGroupId,
  type ParentPortalNavItem,
  type ParentPortalNavLabel,
  type ParentPortalNavSectionLabel,
  type PortalActivityMemoryGraphEdge,
  type PortalActivityMemoryGraphNode,
  type PortalActivityMemoryGraphNodeId,
  type PortalActivityMemoryGraphReadModel,
  type PortalDetailValue,
  type PortalAgentCommandName,
  type PortalRouteHashPath,
  type PortalRouteHashQueryPath,
  type PortalRouteDescriptor,
  type PortalRouteGroupValue,
  type PortalBackgroundConfig,
  type PortalBackgroundRenderConfig,
  type PortalBackgroundThemeColors,
  type BrowserChildInterventionPageAction,
  type BrowserChildInterventionPageBackdrop,
  type BrowserChildInterventionPageModel,
  type BrowserChildInterventionPageTheme,
  type SocialChildInterventionPageModelOptions,
  type SocialChildInterventionPageModelResult,
  type SocialChildInterventionRequestedUrlResolver,
  type TrackingStatusProofArtifact,
  type PortalThemeValue,
};
