import { decodeDisplayText, type DisplayText } from './display-text';

export const PortalBrowserInventoryFields = {
  ActiveTabCapability: 'activeTabCapability',
  BrowserInventoryRowId: 'browserInventoryRowId',
  ExactUrlCapability: 'exactUrlCapability',
  ExecutablePathRef: 'executablePathRef',
  FileHashRef: 'fileHashRef',
  InstallState: 'installState',
  ManagedProfileState: 'managedProfileState',
  ManagementTier: 'managementTier',
  ProductName: 'productName',
  PublisherSignatureRef: 'publisherSignatureRef',
  RunningState: 'runningState',
  ScannedAt: 'scannedAt',
  SupportTier: 'supportTier',
  UnmanagedFallbackCapability: 'unmanagedFallbackCapability',
} as const;

export const PortalDetails = {
  Transport: decodeDisplayText('Transport'),
  State: decodeDisplayText('State'),
  Events: decodeDisplayText('Events'),
  AgentUrl: decodeDisplayText('Agent URL'),
  ActiveState: decodeDisplayText('Active state'),
  ActivityKind: decodeDisplayText('Activity kind'),
  BrowserEvidence: decodeDisplayText('Browser evidence'),
  BrowserInventory: decodeDisplayText('Browser inventory'),
  BrowserInventoryUnavailable: decodeDisplayText('Browser inventory has not been reported yet.'),
  BrowserIntervention: decodeDisplayText('Browser intervention'),
  BrowserBoundary: decodeDisplayText('Browser boundary'),
  BrowserChannel: decodeDisplayText('Browser channel'),
  BrowserFamily: decodeDisplayText('Browser family'),
  BrowserVersion: decodeDisplayText('Browser version'),
  Bridge: decodeDisplayText('Bridge'),
  BytesReceived: decodeDisplayText('Bytes received'),
  BytesSent: decodeDisplayText('Bytes sent'),
  Capability: decodeDisplayText('Capability'),
  ChildCallParentAction: decodeDisplayText('Call parent action'),
  ChildCopy: decodeDisplayText('Child copy'),
  ChildDelivery: decodeDisplayText('Child delivery'),
  ChildHelpAction: decodeDisplayText('Help action'),
  ChildSafeAction: decodeDisplayText('Safe action'),
  ChildShareLocationAction: decodeDisplayText('Share location action'),
  Connections: decodeDisplayText('Connections'),
  Custody: decodeDisplayText('Custody'),
  Database: decodeDisplayText('Database'),
  Destination: decodeDisplayText('Destination'),
  Device: decodeDisplayText('Device'),
  Domain: decodeDisplayText('Domain'),
  DomainAttribution: decodeDisplayText('Domain attribution'),
  DuplicateEvents: decodeDisplayText('Duplicate events'),
  Entries: decodeDisplayText('Entries'),
  EntryId: decodeDisplayText('Entry ID'),
  EventId: decodeDisplayText('Event ID'),
  EventsIngested: decodeDisplayText('Events ingested'),
  EventsStored: decodeDisplayText('Events stored'),
  ExactUrlCapability: decodeDisplayText('Exact URL capability'),
  ExactUrlClaim: decodeDisplayText('Exact URL claim'),
  FirstObserved: decodeDisplayText('First observed'),
  GeneratedAt: decodeDisplayText('Generated at'),
  GraphEdges: decodeDisplayText('Graph edges'),
  GraphNodes: decodeDisplayText('Graph nodes'),
  GraphOmittedEdges: decodeDisplayText('Omitted graph edges'),
  GraphNavigation: decodeDisplayText('Graph navigation'),
  Host: decodeDisplayText('Host'),
  HostCapabilityEvidence: decodeDisplayText('Host capability evidence'),
  HostCapabilityProbe: decodeDisplayText('Host capability probe'),
  HostCapabilityState: decodeDisplayText('Host capability state'),
  HistoryVisibility: decodeDisplayText('History visibility'),
  LastEvent: decodeDisplayText('Last event'),
  LastObserved: decodeDisplayText('Last observed'),
  LastChecked: decodeDisplayText('Last checked'),
  PrivacyMode: decodeDisplayText('Privacy mode'),
  AdapterBoundary: decodeDisplayText('Adapter boundary'),
  ExecutionState: decodeDisplayText('Execution state'),
  ProviderSource: decodeDisplayText('Provider source'),
  Level: decodeDisplayText('Level'),
  DecisionAction: decodeDisplayText('Decision action'),
  DecisionSource: decodeDisplayText('Decision source'),
  DecisionId: decodeDisplayText('Decision ID'),
  DegradedState: decodeDisplayText('Degraded state'),
  DeletedEvidence: decodeDisplayText('Deleted evidence'),
  DeletedEvidenceReferences: decodeDisplayText('Deleted evidence refs'),
  DryRun: decodeDisplayText('Mode'),
  SentAt: decodeDisplayText('Sent at'),
  Severity: decodeDisplayText('Severity'),
  Enforcement: decodeDisplayText('Enforcement'),
  EnforcementHandoff: decodeDisplayText('Enforcement handoff'),
  EvidenceReferences: decodeDisplayText('Evidence references'),
  Observer: decodeDisplayText('Observer'),
  OcrSnippets: decodeDisplayText('OCR snippets'),
  LocalAiResult: decodeDisplayText('Local AI result'),
  ManagedSession: decodeDisplayText('Managed session'),
  ManagedSessionIntervention: decodeDisplayText('Managed session intervention'),
  ManagedState: decodeDisplayText('Managed state'),
  Model: decodeDisplayText('Model'),
  NetworkFlow: decodeDisplayText('Network flow'),
  NetworkEvidenceGrade: decodeDisplayText('Network evidence grade'),
  NetworkMappedPolicyAction: decodeDisplayText('Network mapped action'),
  NetworkPolicyMappingMode: decodeDisplayText('Network mapping mode'),
  NetworkProtocol: decodeDisplayText('Network protocol'),
  NetworkRequestedPolicyAction: decodeDisplayText('Network requested action'),
  NetworkAdapterAuthorization: decodeDisplayText('Network adapter authorization'),
  NetworkEnforcementAuthorization: decodeDisplayText('Network enforcement authorization'),
  Platform: decodeDisplayText('Platform'),
  PlatformState: decodeDisplayText('Platform state'),
  ParentExplanationReferences: decodeDisplayText('Parent explanation refs'),
  ParentRuleContextReferences: decodeDisplayText('Parent rule context references'),
  ParentRuleContextRefIds: decodeDisplayText('Parent rule context ref IDs'),
  PolicyPreview: decodeDisplayText('Policy check'),
  PolicyReadiness: decodeDisplayText('Policy readiness'),
  PolicyEvaluation: decodeDisplayText('Policy evaluation'),
  CategoryRouting: decodeDisplayText('Category routing'),
  ManualReview: decodeDisplayText('Manual review'),
  UnknownReview: decodeDisplayText('Unknown review'),
  AdapterDispatch: decodeDisplayText('Adapter dispatch'),
  EvidenceClaimRows: decodeDisplayText('Evidence claim rows'),
  IdentityRows: decodeDisplayText('Identity rows'),
  ApprovalAuthorityRows: decodeDisplayText('Approval authority rows'),
  ApprovalActionResultRows: decodeDisplayText('Approval action result rows'),
  PlatformAuthorityRows: decodeDisplayText('Platform authority rows'),
  AiClassifierRows: decodeDisplayText('AI classifier rows'),
  CategoryCandidateRows: decodeDisplayText('Category candidate rows'),
  UnknownReviewRows: decodeDisplayText('Unknown review rows'),
  ReadinessKind: decodeDisplayText('Readiness kind'),
  RowCount: decodeDisplayText('Row count'),
  ReadModelRows: decodeDisplayText('Read-model rows'),
  RequestId: decodeDisplayText('Request ID'),
  PerformanceState: decodeDisplayText('Performance state'),
  PreviewStatus: decodeDisplayText('Decision status'),
  Profile: decodeDisplayText('Profile'),
  Process: decodeDisplayText('Process'),
  ProcessAttribution: decodeDisplayText('Process attribution'),
  ProcessId: decodeDisplayText('Process ID'),
  ProductClaim: decodeDisplayText('Product claim'),
  ProofTier: decodeDisplayText('Proof tier'),
  Provider: decodeDisplayText('Provider'),
  Reason: decodeDisplayText('Reason'),
  ReasonCodes: decodeDisplayText('Reason codes'),
  RedactionNotes: decodeDisplayText('Redaction notes'),
  MissingProof: decodeDisplayText('Missing proof'),
  ResourceClass: decodeDisplayText('Resource class'),
  RowsReturned: decodeDisplayText('Rows returned'),
  RuleIds: decodeDisplayText('Rule IDs'),
  RuntimeReference: decodeDisplayText('Runtime reference'),
  LoadState: decodeDisplayText('Load state'),
  Version: decodeDisplayText('Version'),
  Schema: decodeDisplayText('Schema'),
  Status: decodeDisplayText('Status'),
  Subject: decodeDisplayText('Subject'),
  SubjectId: decodeDisplayText('Subject ID'),
  SubjectKind: decodeDisplayText('Subject kind'),
  Source: decodeDisplayText('Source'),
  TargetId: decodeDisplayText('Target ID'),
  InterventionAction: decodeDisplayText('Intervention action'),
  InterventionActionId: decodeDisplayText('Intervention action ID'),
  InterventionAuditId: decodeDisplayText('Intervention audit ID'),
  InterventionChildDelivery: decodeDisplayText('Child delivery'),
  InterventionMechanism: decodeDisplayText('Intervention mechanism'),
  InterventionOutcome: decodeDisplayText('Intervention outcome'),
  InterventionTarget: decodeDisplayText('Intervention target'),
  InterventionTargetType: decodeDisplayText('Intervention target type'),
  UnmanagedBrowserEnforcement: decodeDisplayText('Unmanaged browser enforcement'),
  UnmanagedDetection: decodeDisplayText('Unmanaged detection'),
  UnmanagedFallback: decodeDisplayText('Unmanaged fallback'),
  UnmanagedFallbackAction: decodeDisplayText('Unmanaged fallback action'),
  ActiveTabCapability: decodeDisplayText('Active tab proof'),
  ManagedProfileState: decodeDisplayText('Managed profile state'),
  ManagementTier: decodeDisplayText('Management tier'),
  RunningState: decodeDisplayText('Running state'),
  SupportTier: decodeDisplayText('Support tier'),
  TargetType: decodeDisplayText('Target type'),
  TargetValue: decodeDisplayText('Target value'),
  TcpState: decodeDisplayText('TCP state'),
  Title: decodeDisplayText('Title'),
  UnknownState: decodeDisplayText('Unknown state'),
  Url: decodeDisplayText('URL'),
} as const;

export const PortalReadableValues: Readonly<Record<string, DisplayText>> = {
  available: decodeDisplayText('Available'),
  blocked: decodeDisplayText('Blocked'),
  disabled: decodeDisplayText('Off'),
  empty: decodeDisplayText('No activity'),
  error: decodeDisplayText('Needs attention'),
  false: decodeDisplayText('Off'),
  info: decodeDisplayText('Available'),
  ready: decodeDisplayText('Ready'),
  true: decodeDisplayText('Ready'),
  unavailable: decodeDisplayText('Unavailable'),
  unknown: decodeDisplayText('Unknown'),
  warn: decodeDisplayText('Review'),
  'bridge-connected': decodeDisplayText('Connected'),
  'candidate-running': decodeDisplayText('Candidate running'),
  'child-device-local': decodeDisplayText('Child device'),
  'child-device-query-store': decodeDisplayText('Child device'),
  'approval-hold-rendered': decodeDisplayText('Approval hold rendered'),
  'block-page-rendered': decodeDisplayText('Block page rendered'),
  'checking-hold-rendered': decodeDisplayText('Checking hold rendered'),
  'disabled-preview-only': decodeDisplayText('Advisory'),
  'domain-observed': decodeDisplayText('Domain observed'),
  'exact-url-proven': decodeDisplayText('Exact URL proven'),
  'installed-supported': decodeDisplayText('Installed'),
  installed: decodeDisplayText('Installed'),
  'live-local': decodeDisplayText('Live local'),
  'local-adapter-unavailable': decodeDisplayText('Local adapter not connected'),
  'local-only': decodeDisplayText('Local only'),
  managed: decodeDisplayText('Managed'),
  'managed-browser-unmanaged-process': decodeDisplayText('Open outside managed web profile'),
  'managed-exact-url-available': decodeDisplayText('Exact URL available'),
  'managed-profile-extension': decodeDisplayText('Managed profile extension'),
  'managed-session': decodeDisplayText('Managed session'),
  'managed-target-list': decodeDisplayText('Managed target list'),
  'managed-target-list-only': decodeDisplayText('Target list only'),
  'manual-required': decodeDisplayText('Manual required'),
  'no-network-observations': decodeDisplayText('No network activity'),
  'not-claimed': decodeDisplayText('Not claimed'),
  notClaimed: decodeDisplayText('Not claimed'),
  'not-delivered': decodeDisplayText('Not delivered'),
  'not-installed': decodeDisplayText('Not installed'),
  'not-running': decodeDisplayText('Not running'),
  none: decodeDisplayText('None'),
  'portal-row-only': decodeDisplayText('Portal row only'),
  'process-attributed': decodeDisplayText('Matched to app'),
  'report-only': decodeDisplayText('Report only'),
  'requires-os-app-control': decodeDisplayText('Requires OS app control'),
  'warn-child': decodeDisplayText('Warn child'),
  'parent-review': decodeDisplayText('Ask parent'),
  'terminate-process': decodeDisplayText('Terminate process'),
  'relaunch-managed': decodeDisplayText('Relaunch managed browser'),
  'relaunch-managed-browser': decodeDisplayText('Relaunch managed browser'),
  'os-block-configured': decodeDisplayText('OS block configured'),
  'os-block-manual-required': decodeDisplayText('OS block manual required'),
  'allowed-unmanaged-exception': decodeDisplayText('Allowed unmanaged exception'),
  degraded: decodeDisplayText('Degraded'),
  'running-managed': decodeDisplayText('Running managed'),
  'running-unmanaged': decodeDisplayText('Running unmanaged'),
  'running-unknown': decodeDisplayText('Running state unknown'),
  'tab-list-only': decodeDisplayText('Tab visibility'),
  'unmanaged-browser': decodeDisplayText('Unmanaged web session'),
  'warn-page-rendered': decodeDisplayText('Warning page rendered'),
  unmanaged: decodeDisplayText('Unmanaged'),
} as const;
