import { decodeDisplayText } from '@ocentra-parent/text-domain/contracts';

export const PortalDetails = {
  Transport: decodeDisplayText('Transport'),
  State: decodeDisplayText('State'),
  Events: decodeDisplayText('Events'),
  AgentUrl: decodeDisplayText('Agent URL'),
  ActiveState: decodeDisplayText('Active state'),
  ActivityKind: decodeDisplayText('Activity kind'),
  ActivityDigest: decodeDisplayText('Activity digest'),
  BrowserEvidence: decodeDisplayText('Browser evidence'),
  BrowserFamily: decodeDisplayText('Browser family'),
  Capability: decodeDisplayText('Capability'),
  Custody: decodeDisplayText('Custody'),
  Database: decodeDisplayText('Database'),
  Device: decodeDisplayText('Device'),
  Domain: decodeDisplayText('Domain'),
  DuplicateEvents: decodeDisplayText('Duplicate events'),
  Entries: decodeDisplayText('Entries'),
  EntryId: decodeDisplayText('Entry ID'),
  EventId: decodeDisplayText('Event ID'),
  EventsIngested: decodeDisplayText('Events ingested'),
  EventsStored: decodeDisplayText('Events stored'),
  FirstObserved: decodeDisplayText('First observed'),
  Host: decodeDisplayText('Host'),
  Connections: decodeDisplayText('Connections'),
  LastEvent: decodeDisplayText('Last event'),
  LastObserved: decodeDisplayText('Last observed'),
  Level: decodeDisplayText('Level'),
  SentAt: decodeDisplayText('Sent at'),
  Severity: decodeDisplayText('Severity'),
  Observer: decodeDisplayText('Observer'),
  ManagedSession: decodeDisplayText('Managed session'),
  Platform: decodeDisplayText('Platform'),
  Reason: decodeDisplayText('Reason'),
  RowsReturned: decodeDisplayText('Rows returned'),
  BytesReceived: decodeDisplayText('Bytes received'),
  BytesSent: decodeDisplayText('Bytes sent'),
  Indicators: decodeDisplayText('Indicators'),
  ObservedAt: decodeDisplayText('Observed at'),
  Version: decodeDisplayText('Version'),
  Schema: decodeDisplayText('Schema'),
  Status: decodeDisplayText('Status'),
  Subject: decodeDisplayText('Subject'),
  SubjectId: decodeDisplayText('Subject ID'),
  SubjectKind: decodeDisplayText('Subject kind'),
  Source: decodeDisplayText('Source'),
  TopDestinations: decodeDisplayText('Top destinations'),
  TopProcesses: decodeDisplayText('Top processes'),
  Title: decodeDisplayText('Title'),
  Url: decodeDisplayText('URL'),
} as const;
