import { decodeDisplayText, type DisplayText } from '@ocentra-parent/text-domain/contracts';

export const PortalDetails = {
  Transport: decodeDisplayText('Transport'),
  State: decodeDisplayText('State'),
  Events: decodeDisplayText('Events'),
  AgentUrl: decodeDisplayText('Agent URL'),
  ActiveState: decodeDisplayText('Active state'),
  ActivityKind: decodeDisplayText('Activity kind'),
  BrowserEvidence: decodeDisplayText('Browser evidence'),
  BrowserIntervention: decodeDisplayText('Browser intervention'),
  BrowserChannel: decodeDisplayText('Browser channel'),
  BrowserFamily: decodeDisplayText('Browser family'),
  BrowserVersion: decodeDisplayText('Browser version'),
  Bridge: decodeDisplayText('Bridge'),
  BytesReceived: decodeDisplayText('Bytes received'),
  BytesSent: decodeDisplayText('Bytes sent'),
  Capability: decodeDisplayText('Capability'),
  Connections: decodeDisplayText('Connections'),
  Custody: decodeDisplayText('Custody'),
  Database: decodeDisplayText('Database'),
  Destination: decodeDisplayText('Destination'),
  Device: decodeDisplayText('Device'),
  Domain: decodeDisplayText('Domain'),
  DomainAttribution: decodeDisplayText('Domain attribution'),
  DuplicateEvents: decodeDisplayText('Duplicate events'),
  Entries: decodeDisplayText('Entries'),
  EntryId: decodeDisplayText('Entry ID'),
  EventId: decodeDisplayText('Event ID'),
  EventsIngested: decodeDisplayText('Events ingested'),
  EventsStored: decodeDisplayText('Events stored'),
  FirstObserved: decodeDisplayText('First observed'),
  GeneratedAt: decodeDisplayText('Generated at'),
  GraphEdges: decodeDisplayText('Graph edges'),
  GraphNodes: decodeDisplayText('Graph nodes'),
  GraphOmittedEdges: decodeDisplayText('Omitted graph edges'),
  GraphNavigation: decodeDisplayText('Graph navigation'),
  Host: decodeDisplayText('Host'),
  HistoryVisibility: decodeDisplayText('History visibility'),
  LastEvent: decodeDisplayText('Last event'),
  LastObserved: decodeDisplayText('Last observed'),
  LastChecked: decodeDisplayText('Last checked'),
  PrivacyMode: decodeDisplayText('Privacy mode'),
  AdapterBoundary: decodeDisplayText('Adapter boundary'),
  ExecutionState: decodeDisplayText('Execution state'),
  ProviderSource: decodeDisplayText('Provider source'),
  Level: decodeDisplayText('Level'),
  DecisionAction: decodeDisplayText('Decision action'),
  DecisionSource: decodeDisplayText('Decision source'),
  DecisionId: decodeDisplayText('Decision ID'),
  DegradedState: decodeDisplayText('Degraded state'),
  DeletedEvidence: decodeDisplayText('Deleted evidence'),
  DryRun: decodeDisplayText('Mode'),
  SentAt: decodeDisplayText('Sent at'),
  Severity: decodeDisplayText('Severity'),
  Enforcement: decodeDisplayText('Enforcement'),
  EnforcementHandoff: decodeDisplayText('Enforcement handoff'),
  EvidenceReferences: decodeDisplayText('Evidence references'),
  Observer: decodeDisplayText('Observer'),
  LocalAiResult: decodeDisplayText('Local AI result'),
  ManagedSession: decodeDisplayText('Managed session'),
  ManagedSessionIntervention: decodeDisplayText('Managed session intervention'),
  ManagedState: decodeDisplayText('Managed state'),
  Model: decodeDisplayText('Model'),
  NetworkFlow: decodeDisplayText('Network flow'),
  NetworkProtocol: decodeDisplayText('Network protocol'),
  Platform: decodeDisplayText('Platform'),
  ParentRuleContextReferences: decodeDisplayText('Parent rule context references'),
  ParentRuleContextRefIds: decodeDisplayText('Parent rule context ref IDs'),
  PolicyPreview: decodeDisplayText('Policy check'),
  PreviewStatus: decodeDisplayText('Decision status'),
  Profile: decodeDisplayText('Profile'),
  Process: decodeDisplayText('Process'),
  ProcessAttribution: decodeDisplayText('Process attribution'),
  ProcessId: decodeDisplayText('Process ID'),
  ProductClaim: decodeDisplayText('Product claim'),
  ProofTier: decodeDisplayText('Proof tier'),
  Provider: decodeDisplayText('Provider'),
  Reason: decodeDisplayText('Reason'),
  ReasonCodes: decodeDisplayText('Reason codes'),
  MissingProof: decodeDisplayText('Missing proof'),
  ResourceClass: decodeDisplayText('Resource class'),
  RowsReturned: decodeDisplayText('Rows returned'),
  RuleIds: decodeDisplayText('Rule IDs'),
  RuntimeReference: decodeDisplayText('Runtime reference'),
  LoadState: decodeDisplayText('Load state'),
  Version: decodeDisplayText('Version'),
  Schema: decodeDisplayText('Schema'),
  Status: decodeDisplayText('Status'),
  Subject: decodeDisplayText('Subject'),
  SubjectId: decodeDisplayText('Subject ID'),
  SubjectKind: decodeDisplayText('Subject kind'),
  Source: decodeDisplayText('Source'),
  TargetId: decodeDisplayText('Target ID'),
  InterventionAction: decodeDisplayText('Intervention action'),
  InterventionMechanism: decodeDisplayText('Intervention mechanism'),
  InterventionOutcome: decodeDisplayText('Intervention outcome'),
  InterventionTarget: decodeDisplayText('Intervention target'),
  InterventionTargetType: decodeDisplayText('Intervention target type'),
  UnmanagedBrowserEnforcement: decodeDisplayText('Unmanaged browser enforcement'),
  TargetType: decodeDisplayText('Target type'),
  TargetValue: decodeDisplayText('Target value'),
  TcpState: decodeDisplayText('TCP state'),
  Title: decodeDisplayText('Title'),
  UnknownState: decodeDisplayText('Unknown state'),
  Url: decodeDisplayText('URL'),
} as const;

export const PortalReadableValues: Readonly<Record<string, DisplayText>> = {
  available: decodeDisplayText('Available'),
  blocked: decodeDisplayText('Blocked'),
  disabled: decodeDisplayText('Off'),
  empty: decodeDisplayText('No activity'),
  error: decodeDisplayText('Needs attention'),
  false: decodeDisplayText('Off'),
  info: decodeDisplayText('Available'),
  ready: decodeDisplayText('Ready'),
  true: decodeDisplayText('Ready'),
  unavailable: decodeDisplayText('Unavailable'),
  unknown: decodeDisplayText('Unknown'),
  warn: decodeDisplayText('Review'),
  'bridge-connected': decodeDisplayText('Connected'),
  'child-device-local': decodeDisplayText('Child device'),
  'child-device-query-store': decodeDisplayText('Child device'),
  'disabled-preview-only': decodeDisplayText('Advisory'),
  'domain-observed': decodeDisplayText('Domain observed'),
  'installed-supported': decodeDisplayText('Installed'),
  'live-local': decodeDisplayText('Live local'),
  'local-adapter-unavailable': decodeDisplayText('Local adapter not connected'),
  'local-only': decodeDisplayText('Local only'),
  'managed-browser-unmanaged-process': decodeDisplayText('Open outside managed web profile'),
  'no-network-observations': decodeDisplayText('No network activity'),
  'process-attributed': decodeDisplayText('Matched to app'),
  'requires-os-app-control': decodeDisplayText('Requires OS app control'),
  'tab-list-only': decodeDisplayText('Tab visibility'),
  'unmanaged-browser': decodeDisplayText('Unmanaged web session'),
} as const;
