import { decodeDisplayText } from './display-text';
import {
  PortalFrameTunerLayoutKey as PortalFrameTunerLayoutKeyImpl,
  PortalFrameShellNumberFields as PortalFrameShellNumberFieldsImpl,
  PortalFrameContentBooleanFields as PortalFrameContentBooleanFieldsImpl,
  PortalGoldenCardBooleanFields as PortalGoldenCardBooleanFieldsImpl,
  PortalFrameContentNumberFields as PortalFrameContentNumberFieldsImpl,
  PortalGoldenCardFrameNumberFields as PortalGoldenCardFrameNumberFieldsImpl,
  PortalGoldenCardContentNumberFields as PortalGoldenCardContentNumberFieldsImpl,
  PortalCarouselFrameNumberFields as PortalCarouselFrameNumberFieldsImpl,
  PortalCarouselContentNumberFields as PortalCarouselContentNumberFieldsImpl,
  PortalCarouselRailNumberFields as PortalCarouselRailNumberFieldsImpl,
  PortalFrameSlotNumberFields as PortalFrameSlotNumberFieldsImpl,
  PortalFrameGeometryNumberFields as PortalFrameGeometryNumberFieldsImpl,
  PortalFrameChromeNumberFields as PortalFrameChromeNumberFieldsImpl,
  PortalFrameOuterShapeNumberFields as PortalFrameOuterShapeNumberFieldsImpl,
  PortalFrameInnerShapeNumberFields as PortalFrameInnerShapeNumberFieldsImpl,
  PortalFrameOuterEdgeNumberFields as PortalFrameOuterEdgeNumberFieldsImpl,
  PortalFrameInnerEdgeNumberFields as PortalFrameInnerEdgeNumberFieldsImpl,
  PortalFrameOuterGapNumberFields as PortalFrameOuterGapNumberFieldsImpl,
  PortalFrameInnerGapNumberFields as PortalFrameInnerGapNumberFieldsImpl,
  PortalFrameOuterSegmentNumberFields as PortalFrameOuterSegmentNumberFieldsImpl,
  PortalFrameInnerSegmentNumberFields as PortalFrameInnerSegmentNumberFieldsImpl,
} from './frame-tuner-fields';

export const PortalFrameTuner = {
  Api: {
    StaticLayoutAsset: '/portal-frame-layout.json',
    LayoutEndpoint: '/__ocentra-parent/frame-layout',
    SavedLayoutEndpoint: '/__ocentra-parent/frame-layout-saved',
  },
  HttpMethod: {
    Put: 'PUT',
  },
  HttpHeader: {
    ContentType: 'Content-Type',
  },
  ContentType: {
    Json: 'application/json',
  },
  FetchCache: {
    NoStore: 'no-store',
  },
  Timing: {
    LayoutPollMs: 120,
    AutoSaveMs: 80,
  },
  Classes: {
    FrameBackdrop: 'portal-frame-backdrop',
    FrameBackdropSvg: 'portal-frame-backdrop-svg',
    FrameContentBoundsLabel: 'portal-frame-content-bounds-label',
    FrameContentBoundsOverlay: 'portal-frame-content-bounds-overlay',
    FrameContent: 'portal-frame-content',
    FrameContentHidden: 'portal-frame-content-hidden',
    FrameDebugHost: 'portal-frame-debug-host',
    FrameOuterBoundsLabel: 'portal-frame-outer-bounds-label',
    FrameOuterBoundsOverlay: 'portal-frame-outer-bounds-overlay',
    Tuner: 'portal-frame-tuner',
    TunerToolbar: 'portal-frame-tuner-toolbar',
    TunerActions: 'portal-frame-tuner-actions',
    TunerButton: 'portal-frame-tuner-button',
    TunerButtonActive: 'portal-frame-tuner-button-active',
    TunerBoolean: 'portal-frame-tuner-boolean',
    TunerControlGrid: 'portal-frame-tuner-control-grid',
    TunerControlPanel: 'portal-frame-tuner-control-panel',
    TunerControlSection: 'portal-frame-tuner-control-section',
    TunerField: 'portal-frame-tuner-field',
    TunerFieldReset: 'portal-frame-tuner-field-reset',
    TunerFieldValue: 'portal-frame-tuner-field-value',
    TunerPreview: 'portal-frame-tuner-preview',
    TunerPreviewStage: 'portal-frame-tuner-preview-stage',
    TunerPreviewSidebar: 'portal-frame-tuner-preview-sidebar',
    TunerPreviewMain: 'portal-frame-tuner-preview-main',
    TunerPreviewContent: 'portal-frame-tuner-preview-content',
    TunerPreviewHidden: 'portal-frame-tuner-preview-hidden',
    TunerJson: 'portal-frame-tuner-json',
    TunerStatus: 'portal-frame-tuner-status',
    TunerStandalone: 'portal-frame-tuner-standalone',
    TunerWorkspace: 'portal-frame-tuner-workspace',
    TunerTabs: 'portal-frame-tuner-tabs',
    TunerSurfaceTabs: 'portal-frame-tuner-surface-tabs',
    TunerPanelTabs: 'portal-frame-tuner-panel-tabs',
    TunerTab: 'portal-frame-tuner-tab',
    TunerTabActive: 'portal-frame-tuner-tab-active',
    TunerSectionTabs: 'portal-frame-tuner-section-tabs',
    TunerInspector: 'portal-frame-tuner-inspector',
    TunerGoldenCardOriginalControls: 'portal-frame-tuner-golden-card-original-controls',
    TunerPreviewPanel: 'portal-frame-tuner-preview-panel',
    TunerColor: 'portal-frame-tuner-color',
    TunerAppLayoutSurface: 'portal-frame-tuner-app-layout-surface',
    TunerAppLayoutHeader: 'portal-frame-tuner-app-layout-header',
    TunerHierarchy: 'portal-frame-tuner-hierarchy',
    TunerAppLayoutPane: 'portal-frame-tuner-app-layout-pane',
    TunerContentEditor: 'portal-frame-tuner-content-editor',
    TunerContentList: 'portal-frame-tuner-content-list',
    TunerContentItem: 'portal-frame-tuner-content-item',
    TunerContentFields: 'portal-frame-tuner-content-fields',
    TunerContentButtons: 'portal-frame-tuner-content-buttons',
    TunerContentInput: 'portal-frame-tuner-content-input',
    TunerContentSummary: 'portal-frame-tuner-content-summary',
  },
  CssVar: {
    ContentGap: '--portal-frame-content-gap',
    ContentInsetX: '--portal-frame-content-inset-x',
    ContentInsetY: '--portal-frame-content-inset-y',
    ContentOffsetX: '--portal-frame-content-offset-x',
    ContentOffsetY: '--portal-frame-content-offset-y',
    ContentClipX: '--portal-frame-content-clip-x',
    ContentClipY: '--portal-frame-content-clip-y',
    SlotHeightAdjust: '--portal-frame-slot-height-adjust',
    SlotWidthAdjust: '--portal-frame-slot-width-adjust',
    SideBottomHeight: '--portal-sidebar-bottom-height',
    SideStackGap: '--portal-sidebar-stack-gap',
    GoldenCardContentBoundsOpacity: '--portal-golden-card-content-bounds-opacity',
    GoldenCardContentInsetX: '--portal-golden-card-content-inset-x',
    GoldenCardContentInsetY: '--portal-golden-card-content-inset-y',
    GoldenCardContentOffsetX: '--portal-golden-card-content-offset-x',
    GoldenCardContentOffsetY: '--portal-golden-card-content-offset-y',
    GoldenCardContentOpacity: '--portal-golden-card-content-opacity',
    GoldenCardFrameBoundsOpacity: '--portal-golden-card-frame-bounds-opacity',
    GoldenCardFrameGlowBlur: '--portal-golden-card-frame-glow-blur',
    GoldenCardFrameGlowOpacity: '--portal-golden-card-frame-glow-opacity',
    GoldenCardFrameHeightAdjust: '--portal-golden-card-frame-height-adjust',
    GoldenCardFrameInset: '--portal-golden-card-frame-inset',
    GoldenCardFrameOffsetX: '--portal-golden-card-frame-offset-x',
    GoldenCardFrameOffsetY: '--portal-golden-card-frame-offset-y',
    GoldenCardFrameOpacity: '--portal-golden-card-frame-opacity',
    GoldenCardFrameWidthAdjust: '--portal-golden-card-frame-width-adjust',
    GoldenCardGlyphSize: '--portal-golden-card-glyph-size',
    GoldenCardHeight: '--portal-golden-card-height',
    GoldenCardPaddingX: '--portal-golden-card-padding-x',
    GoldenCardPaddingY: '--portal-golden-card-padding-y',
    GoldenCardTitleOffsetX: '--portal-golden-card-title-offset-x',
    GoldenCardTitleOffsetY: '--portal-golden-card-title-offset-y',
    CarouselCardMinWidth: '--portal-carousel-card-min-width',
    CarouselCardWidthPercent: '--portal-carousel-card-width-percent',
    CarouselFrameHeightAdjust: '--portal-carousel-frame-height-adjust',
    CarouselFrameInsetX: '--portal-carousel-frame-inset-x',
    CarouselFrameInsetY: '--portal-carousel-frame-inset-y',
    CarouselFrameOffsetX: '--portal-carousel-frame-offset-x',
    CarouselFrameOffsetY: '--portal-carousel-frame-offset-y',
    CarouselFrameOpacity: '--portal-carousel-frame-opacity',
    CarouselFrameWidthAdjust: '--portal-carousel-frame-width-adjust',
    CarouselMinHeight: '--portal-carousel-min-height',
    CarouselPaddingBottom: '--portal-carousel-padding-bottom',
    CarouselPaddingLeft: '--portal-carousel-padding-left',
    CarouselPaddingRight: '--portal-carousel-padding-right',
    CarouselPaddingTop: '--portal-carousel-padding-top',
    CarouselRailGap: '--portal-carousel-rail-gap',
    CarouselRailPaddingBottom: '--portal-carousel-rail-padding-bottom',
    CarouselRailPaddingLeft: '--portal-carousel-rail-padding-left',
    CarouselRailPaddingRight: '--portal-carousel-rail-padding-right',
    CarouselRailPaddingTop: '--portal-carousel-rail-padding-top',
    CarouselTitleLeft: '--portal-carousel-title-left',
    CarouselTitleRight: '--portal-carousel-title-right',
    CarouselTitleTop: '--portal-carousel-title-top',
  },
  InputType: {
    Checkbox: 'checkbox',
    Color: 'color',
    Number: 'number',
    Range: 'range',
    Text: 'text',
  },
  FrameTarget: {
    Side: 'side',
    SideTop: 'sideTop',
    SideBottom: 'sideBottom',
    Main: 'main',
  },
  Panel: {
    MainApp: 'mainApp',
    ChatInterface: 'chatInterface',
    Shell: 'shell',
    SideAnchors: 'sideAnchors',
    SideChrome: 'sideChrome',
    SidePanel: 'sidePanel',
    MainAnchors: 'mainAnchors',
    MainChrome: 'mainChrome',
    MainPanel: 'mainPanel',
    Carousel: 'carousel',
    GoldenCard: 'goldenCard',
    Preview: 'preview',
  },
  FrameSection: {
    Viewport: 'viewport',
    Placement: 'placement',
    OuterAnchors: 'outerAnchors',
    InnerAnchors: 'innerAnchors',
    OuterFrame: 'outerFrame',
    OuterGaps: 'outerGaps',
    OuterEdges: 'outerEdges',
    OuterSegments: 'outerSegments',
    InnerFrame: 'innerFrame',
    InnerGaps: 'innerGaps',
    InnerEdges: 'innerEdges',
    InnerSegments: 'innerSegments',
    Colors: 'colors',
    Content: 'content',
  },
  LayoutKey: PortalFrameTunerLayoutKeyImpl,
  Segment: {
    TopLeftRunStart: 'topLeftRunStart',
    TopLeftRunMid: 'topLeftRunMid',
    TopLeftRunEnd: 'topLeftRunEnd',
    TopLeftConnector: 'topLeftConnector',
    TopCenterRun: 'topCenterRun',
    TopRightConnector: 'topRightConnector',
    TopRightRunStart: 'topRightRunStart',
    TopRightRunMid: 'topRightRunMid',
    TopRightRunEnd: 'topRightRunEnd',
    RightTopCorner: 'rightTopCorner',
    RightSideRunStart: 'rightSideRunStart',
    RightSideRunMid: 'rightSideRunMid',
    RightSideRunEnd: 'rightSideRunEnd',
    RightBottomCorner: 'rightBottomCorner',
    BottomRightRunStart: 'bottomRightRunStart',
    BottomRightRunMid: 'bottomRightRunMid',
    BottomRightRunEnd: 'bottomRightRunEnd',
    BottomRightConnector: 'bottomRightConnector',
    BottomCenterRun: 'bottomCenterRun',
    BottomLeftConnector: 'bottomLeftConnector',
    BottomLeftRunStart: 'bottomLeftRunStart',
    BottomLeftRunMid: 'bottomLeftRunMid',
    BottomLeftRunEnd: 'bottomLeftRunEnd',
    LeftBottomCorner: 'leftBottomCorner',
    LeftSideRunStart: 'leftSideRunStart',
    LeftSideRunMid: 'leftSideRunMid',
    LeftSideRunEnd: 'leftSideRunEnd',
    LeftTopCorner: 'leftTopCorner',
  },
  Orientation: {
    Portrait: 'portrait',
    Landscape: 'landscape',
  },
  Color: {
    Cyan: '#42e8ff',
    DeepBlue: '#06111f',
    Gold: '#f6c34a',
  },
  AppSurface: {
    MainApp: 'mainApp',
    ChatInterface: 'chatInterface',
  },
  AppContentArea: {
    SidePanelFoldouts: 'sidePanelFoldouts',
    MainPanelTop: 'mainPanelTop',
    MainPanelBottom: 'mainPanelBottom',
  },
  AppLayoutTone: {
    Cyan: 'cyan',
    Gold: 'gold',
    Purple: 'purple',
    Red: 'red',
    Muted: 'muted',
  },
  AppLayoutRegion: {
    SidePanel: 'sidePanel',
    MainPanel: 'mainPanel',
  },
  AppLayoutSection: {
    Top: 'top',
    Bottom: 'bottom',
    Chrome: 'chrome',
    Colors: 'colors',
    Content: 'content',
  },
  AppLayoutFieldKey: {
    CanvasWidth: 'canvas.width',
    CanvasHeight: 'canvas.height',
    LayoutOuterPad: 'layout.outerPad',
    LayoutGap: 'layout.gap',
    LayoutLeftW: 'layout.leftW',
    LayoutRightW: 'layout.rightW',
    LayoutTopY: 'layout.topY',
    LayoutHeaderH: 'layout.headerH',
    LayoutTabsY: 'layout.tabsY',
    LayoutTabsH: 'layout.tabsH',
    LayoutMainY: 'layout.mainY',
    LayoutBottomY: 'layout.bottomY',
    LayoutBottomH: 'layout.bottomH',
    ChromePanelCut: 'chrome.panelCut',
    ChromePanelStrokeWidth: 'chrome.panelStrokeWidth',
    ChromePanelInnerInset: 'chrome.panelInnerInset',
    ChromeHoverPad: 'chrome.hoverPad',
    ChromeGlowOpacity: 'chrome.glowOpacity',
    ChromeButtonArrowWidth: 'chrome.buttonArrowWidth',
    ChromeRowHeight: 'chrome.rowHeight',
    ChromeRowGap: 'chrome.rowGap',
    ChromeAvatarRadius: 'chrome.avatarRadius',
  },
  AppLayoutFieldSeparator: '.',
  ValueType: {
    String: 'string',
  },
  ParentPortalControlGroup: {
    Canvas: 'canvas',
    Layout: 'layout',
    Colors: 'colors',
    Chrome: 'chrome',
  },
  GoldenFrame: {
    StorageKey: 'ocentra-foreign-frame-config',
    Channel: 'ocentra-foreign-frame-channel',
    ToneGold: 'gold',
    ToneSilver: 'silver',
    ToneBronze: 'bronze',
    ToneBlue: 'blue',
    ValueType: {
      Object: 'object',
      Undefined: 'undefined',
    },
    ConfigKey: {
      OuterFrame: 'outerFrame',
      InnerFrame: 'innerFrame',
      SideHexBadge: 'sideHexBadge',
      WinnerName: 'winnerName',
      RightStats: 'rightStats',
    },
  },
  Text: {
    RouteTitle: decodeDisplayText('App layout'),
    RouteDescription: decodeDisplayText('Layout and content authoring for parent portal app surfaces.'),
    TargetSide: decodeDisplayText('Side panel'),
    TargetSideTop: decodeDisplayText('Side navigation frame'),
    TargetSideBottom: decodeDisplayText('Side device frame'),
    TargetMain: decodeDisplayText('Main body'),
    ShellSection: decodeDisplayText('Shell fit'),
    FrameSection: decodeDisplayText('Frame geometry'),
    AnchorSection: decodeDisplayText('Anchors'),
    ChromeSection: decodeDisplayText('Stroke and glow'),
    HideInnerContent: decodeDisplayText('Show inner content'),
    Save: decodeDisplayText('Save JSON'),
    Reset: decodeDisplayText('Reset'),
    Saved: decodeDisplayText('Saved layout JSON.'),
    ResetLoaded: decodeDisplayText('Loaded saved layout JSON.'),
    SaveFailed: decodeDisplayText('Save failed. Check the Vite dev server.'),
    Loading: decodeDisplayText('Loading frame layout.'),
    Ready: decodeDisplayText('Frame layout ready.'),
    PreviewSidebar: decodeDisplayText('Navigation frame preview'),
    PreviewMain: decodeDisplayText('Main panel frame preview'),
    JsonTitle: decodeDisplayText('Saved JSON preview'),
    PanelMainApp: decodeDisplayText('Main App'),
    PanelChatInterface: decodeDisplayText('Chat Interface'),
    PanelShell: decodeDisplayText('Shell'),
    PanelSidePanel: decodeDisplayText('Side panel'),
    PanelMainPanel: decodeDisplayText('Main panel'),
    PanelCarousel: decodeDisplayText('Carousel'),
    PanelGoldenCard: decodeDisplayText('Golden card'),
    PanelPreview: decodeDisplayText('Save and JSON'),
    SideTopTab: decodeDisplayText('Top'),
    SideBottomTab: decodeDisplayText('Bottom'),
    ResetShell: decodeDisplayText('Reset shell'),
    ResetSideTop: decodeDisplayText('Reset top'),
    ResetSideBottom: decodeDisplayText('Reset bottom'),
    ResetMain: decodeDisplayText('Reset main'),
    ResetSurface: decodeDisplayText('Reset surface'),
    ResetContentDraft: decodeDisplayText('Reset content draft'),
    ResetCarousel: decodeDisplayText('Reset carousel'),
    ResetGoldenCard: decodeDisplayText('Reset golden card'),
    ToggleContent: decodeDisplayText('Content'),
    ToggleFrameBounds: decodeDisplayText('Purple frame bounds'),
    ToggleContentBounds: decodeDisplayText('Yellow content bounds'),
    SideTopAnchors: decodeDisplayText('Side navigation anchors'),
    SideTopChrome: decodeDisplayText('Side navigation stroke'),
    SideTopColors: decodeDisplayText('Side navigation colors'),
    SideBottomAnchors: decodeDisplayText('Side device anchors'),
    SideBottomChrome: decodeDisplayText('Side device stroke'),
    SideBottomColors: decodeDisplayText('Side device colors'),
    MainAnchors: decodeDisplayText('Main anchors'),
    MainChrome: decodeDisplayText('Main stroke'),
    MainColors: decodeDisplayText('Main colors'),
    GoldenCardFit: decodeDisplayText('Golden card frame'),
    GoldenCardContent: decodeDisplayText('Golden card content'),
    CarouselFrameFit: decodeDisplayText('Carousel frame'),
    CarouselContentFit: decodeDisplayText('Carousel content'),
    CarouselRailFit: decodeDisplayText('Carousel rail'),
    ViewportGroup: decodeDisplayText('Advanced SVG camera'),
    FrameGroup: decodeDisplayText('Frame move'),
    OuterAnchorGroup: decodeDisplayText('Fit frame'),
    InnerAnchorGroup: decodeDisplayText('Inner frame fit'),
    OuterFrameGroup: decodeDisplayText('Outer frame'),
    OuterEdgeGroup: decodeDisplayText('Outer edge widths'),
    OuterGapGroup: decodeDisplayText('Outer segment gaps'),
    InnerFrameGroup: decodeDisplayText('Inner frame'),
    InnerEdgeGroup: decodeDisplayText('Inner edge widths'),
    InnerGapGroup: decodeDisplayText('Inner segment gaps'),
    OuterSegmentGroup: decodeDisplayText('Outer segment widths'),
    InnerSegmentGroup: decodeDisplayText('Inner segment widths'),
    ColorsGroup: decodeDisplayText('Colors'),
    ContentGroup: decodeDisplayText('Content'),
    FrameSlotGroup: decodeDisplayText('Frame box size'),
    FrameSpaceGroup: decodeDisplayText('Frame path size'),
    OrientationGroup: decodeDisplayText('SVG orientation'),
    Portrait: decodeDisplayText('Portrait'),
    Landscape: decodeDisplayText('Landscape'),
    BoundsGroup: decodeDisplayText('Bounds and visibility'),
    ContentFitGroup: decodeDisplayText('Content fit'),
    AppLayoutSurfaceFit: decodeDisplayText('Surface fit'),
    AppLayoutSidePanel: decodeDisplayText('Side panel'),
    AppLayoutMainPanel: decodeDisplayText('Main panel'),
    AppLayoutTop: decodeDisplayText('Top'),
    AppLayoutBottom: decodeDisplayText('Bottom'),
    AppLayoutSideTop: decodeDisplayText('Side panel top'),
    AppLayoutSideBottom: decodeDisplayText('Side panel bottom'),
    AppLayoutTopCards: decodeDisplayText('Top cards'),
    AppLayoutTopChoices: decodeDisplayText('Top choices'),
    AppLayoutMainBottom: decodeDisplayText('Main bottom'),
    AppLayoutChrome: decodeDisplayText('Chrome'),
    AppLayoutColors: decodeDisplayText('Colors'),
    AppLayoutContent: decodeDisplayText('Content'),
    SidePanelFoldouts: decodeDisplayText('Sidepanel foldouts'),
    MainPanelTopContent: decodeDisplayText('Main top content'),
    MainPanelBottomContent: decodeDisplayText('Main bottom content'),
    AddFoldout: decodeDisplayText('Add foldout'),
    AddButton: decodeDisplayText('Add button'),
    Remove: decodeDisplayText('Remove'),
    FoldoutName: decodeDisplayText('Foldout name'),
    ButtonLabel: decodeDisplayText('Button label'),
    ButtonDetail: decodeDisplayText('Button detail'),
    ButtonRoute: decodeDisplayText('Button route'),
    ButtonIcon: decodeDisplayText('Button icon'),
    Theme: decodeDisplayText('Theme'),
    ContentAuthoringSummary: decodeDisplayText(
      'Author layout content here, then wire it into the runtime surface when ready.'
    ),
    ResetGlyph: decodeDisplayText('↺'),
    ShowFrameBounds: decodeDisplayText('Show frame bounds'),
    ShowContentBounds: decodeDisplayText('Show content bounds'),
    ShowFrameContent: decodeDisplayText('Show content'),
    ContentInsetX: decodeDisplayText('Inset X'),
    ContentInsetY: decodeDisplayText('Inset Y'),
    ContentOffsetX: decodeDisplayText('Offset X'),
    ContentOffsetY: decodeDisplayText('Offset Y'),
    ContentGap: decodeDisplayText('Gap'),
    SlotWidthAdjust: decodeDisplayText('Frame box width +/-'),
    SlotHeightAdjust: decodeDisplayText('Frame box height +/-'),
    GoldenCardHeight: decodeDisplayText('Card height'),
    GoldenCardPaddingX: decodeDisplayText('Padding X'),
    GoldenCardPaddingY: decodeDisplayText('Padding Y'),
    GoldenCardFrameInset: decodeDisplayText('Frame inset'),
    GoldenCardFrameWidthAdjust: decodeDisplayText('Frame width +/-'),
    GoldenCardFrameHeightAdjust: decodeDisplayText('Frame height +/-'),
    GoldenCardFrameOffsetX: decodeDisplayText('Frame offset X'),
    GoldenCardFrameOffsetY: decodeDisplayText('Frame offset Y'),
    GoldenCardFrameOpacity: decodeDisplayText('Frame opacity'),
    GoldenCardFrameGlowBlur: decodeDisplayText('Frame glow blur'),
    GoldenCardFrameGlowOpacity: decodeDisplayText('Frame glow opacity'),
    GoldenCardGlyphSize: decodeDisplayText('Glyph size'),
    GoldenCardTitleOffsetX: decodeDisplayText('Title offset X'),
    GoldenCardTitleOffsetY: decodeDisplayText('Title offset Y'),
    CarouselMinHeight: decodeDisplayText('Carousel height'),
    CarouselFrameInsetX: decodeDisplayText('Frame inset X'),
    CarouselFrameInsetY: decodeDisplayText('Frame inset Y'),
    CarouselFrameOffsetX: decodeDisplayText('Frame offset X'),
    CarouselFrameOffsetY: decodeDisplayText('Frame offset Y'),
    CarouselFrameWidthAdjust: decodeDisplayText('Frame width +/-'),
    CarouselFrameHeightAdjust: decodeDisplayText('Frame height +/-'),
    CarouselFrameOpacity: decodeDisplayText('Frame opacity'),
    CarouselPaddingTop: decodeDisplayText('Padding top'),
    CarouselPaddingRight: decodeDisplayText('Padding right'),
    CarouselPaddingBottom: decodeDisplayText('Padding bottom'),
    CarouselPaddingLeft: decodeDisplayText('Padding left'),
    CarouselTitleLeft: decodeDisplayText('Title left'),
    CarouselTitleRight: decodeDisplayText('Title right'),
    CarouselTitleTop: decodeDisplayText('Title top'),
    CarouselRailGap: decodeDisplayText('Rail gap'),
    CarouselRailPaddingTop: decodeDisplayText('Rail padding top'),
    CarouselRailPaddingRight: decodeDisplayText('Rail padding right'),
    CarouselRailPaddingBottom: decodeDisplayText('Rail padding bottom'),
    CarouselRailPaddingLeft: decodeDisplayText('Rail padding left'),
    CarouselCardMinWidth: decodeDisplayText('Card min width'),
    CarouselCardWidthPercent: decodeDisplayText('Card width %'),
    OuterColor: decodeDisplayText('Outer color'),
    OuterGlowColor: decodeDisplayText('Outer glow color'),
    InnerColor: decodeDisplayText('Inner color'),
    InnerGlowColor: decodeDisplayText('Inner glow color'),
  },
} as const;

export type PortalFrameTargetValue = (typeof PortalFrameTuner.FrameTarget)[keyof typeof PortalFrameTuner.FrameTarget];
export type PortalFrameTunerFrameSectionValue =
  (typeof PortalFrameTuner.FrameSection)[keyof typeof PortalFrameTuner.FrameSection];
export type PortalFrameCssStyle = Record<string, string>;
export type PortalFrameCssValue = string;

export type PortalFrameBooleanField = {
  readonly path: readonly string[];
  readonly label: ReturnType<typeof decodeDisplayText>;
};

export type PortalFrameNumberField = {
  readonly path: readonly string[];
  readonly label: ReturnType<typeof decodeDisplayText>;
  readonly min: number;
  readonly max: number;
  readonly step: number;
};

export type PortalFrameColorField = {
  readonly path: readonly string[];
  readonly label: ReturnType<typeof decodeDisplayText>;
};

export const PortalFrameShellNumberFields = PortalFrameShellNumberFieldsImpl;
export const PortalFrameContentBooleanFields = PortalFrameContentBooleanFieldsImpl;
export const PortalGoldenCardBooleanFields = PortalGoldenCardBooleanFieldsImpl;
export const PortalFrameContentNumberFields = PortalFrameContentNumberFieldsImpl;
export const PortalGoldenCardFrameNumberFields = PortalGoldenCardFrameNumberFieldsImpl;
export const PortalGoldenCardContentNumberFields = PortalGoldenCardContentNumberFieldsImpl;
export const PortalCarouselFrameNumberFields = PortalCarouselFrameNumberFieldsImpl;
export const PortalCarouselContentNumberFields = PortalCarouselContentNumberFieldsImpl;
export const PortalCarouselRailNumberFields = PortalCarouselRailNumberFieldsImpl;
export const PortalFrameSlotNumberFields = PortalFrameSlotNumberFieldsImpl;
export const PortalFrameGeometryNumberFields = PortalFrameGeometryNumberFieldsImpl;
export const PortalFrameChromeNumberFields = PortalFrameChromeNumberFieldsImpl;
export const PortalFrameOuterShapeNumberFields = PortalFrameOuterShapeNumberFieldsImpl;
export const PortalFrameInnerShapeNumberFields = PortalFrameInnerShapeNumberFieldsImpl;
export const PortalFrameOuterEdgeNumberFields = PortalFrameOuterEdgeNumberFieldsImpl;
export const PortalFrameInnerEdgeNumberFields = PortalFrameInnerEdgeNumberFieldsImpl;
export const PortalFrameOuterGapNumberFields = PortalFrameOuterGapNumberFieldsImpl;
export const PortalFrameInnerGapNumberFields = PortalFrameInnerGapNumberFieldsImpl;
export const PortalFrameOuterSegmentNumberFields = PortalFrameOuterSegmentNumberFieldsImpl;
export const PortalFrameInnerSegmentNumberFields = PortalFrameInnerSegmentNumberFieldsImpl;

export function portalFrameCssPixel(value: number): PortalFrameCssValue {
  return `${value}px`;
}

export function portalFrameCssPercent(value: number): PortalFrameCssValue {
  return `${value}%`;
}

export function portalFrameCssNumber(value: number): PortalFrameCssValue {
  return String(value);
}

export function portalFrameCssOpacity(value: boolean): PortalFrameCssValue {
  return value ? '1' : '0';
}
