import { decodeDisplayText } from '@ocentra-parent/text-domain/contracts';

export const PortalFrameTuner = {
  Api: {
    StaticLayoutAsset: '/portal-frame-layout.json',
    LayoutEndpoint: '/__ocentra-parent/frame-layout',
    SavedLayoutEndpoint: '/__ocentra-parent/frame-layout-saved',
  },
  HttpMethod: {
    Put: 'PUT',
  },
  HttpHeader: {
    ContentType: 'Content-Type',
  },
  ContentType: {
    Json: 'application/json',
  },
  FetchCache: {
    NoStore: 'no-store',
  },
  Timing: {
    LayoutPollMs: 120,
    AutoSaveMs: 80,
  },
  Classes: {
    FrameBackdrop: 'portal-frame-backdrop',
    FrameBackdropSvg: 'portal-frame-backdrop-svg',
    FrameContentBoundsLabel: 'portal-frame-content-bounds-label',
    FrameContentBoundsOverlay: 'portal-frame-content-bounds-overlay',
    FrameContent: 'portal-frame-content',
    FrameContentHidden: 'portal-frame-content-hidden',
    FrameDebugHost: 'portal-frame-debug-host',
    FrameOuterBoundsLabel: 'portal-frame-outer-bounds-label',
    FrameOuterBoundsOverlay: 'portal-frame-outer-bounds-overlay',
    Tuner: 'portal-frame-tuner',
    TunerToolbar: 'portal-frame-tuner-toolbar',
    TunerActions: 'portal-frame-tuner-actions',
    TunerButton: 'portal-frame-tuner-button',
    TunerButtonActive: 'portal-frame-tuner-button-active',
    TunerBoolean: 'portal-frame-tuner-boolean',
    TunerControlGrid: 'portal-frame-tuner-control-grid',
    TunerControlPanel: 'portal-frame-tuner-control-panel',
    TunerControlSection: 'portal-frame-tuner-control-section',
    TunerField: 'portal-frame-tuner-field',
    TunerFieldReset: 'portal-frame-tuner-field-reset',
    TunerFieldValue: 'portal-frame-tuner-field-value',
    TunerPreview: 'portal-frame-tuner-preview',
    TunerPreviewStage: 'portal-frame-tuner-preview-stage',
    TunerPreviewSidebar: 'portal-frame-tuner-preview-sidebar',
    TunerPreviewMain: 'portal-frame-tuner-preview-main',
    TunerPreviewContent: 'portal-frame-tuner-preview-content',
    TunerPreviewHidden: 'portal-frame-tuner-preview-hidden',
    TunerJson: 'portal-frame-tuner-json',
    TunerStatus: 'portal-frame-tuner-status',
    TunerStandalone: 'portal-frame-tuner-standalone',
    TunerWorkspace: 'portal-frame-tuner-workspace',
    TunerTabs: 'portal-frame-tuner-tabs',
    TunerSurfaceTabs: 'portal-frame-tuner-surface-tabs',
    TunerPanelTabs: 'portal-frame-tuner-panel-tabs',
    TunerTab: 'portal-frame-tuner-tab',
    TunerTabActive: 'portal-frame-tuner-tab-active',
    TunerSectionTabs: 'portal-frame-tuner-section-tabs',
    TunerInspector: 'portal-frame-tuner-inspector',
    TunerGoldenCardOriginalControls: 'portal-frame-tuner-golden-card-original-controls',
    TunerPreviewPanel: 'portal-frame-tuner-preview-panel',
    TunerColor: 'portal-frame-tuner-color',
    TunerAppLayoutSurface: 'portal-frame-tuner-app-layout-surface',
    TunerAppLayoutHeader: 'portal-frame-tuner-app-layout-header',
    TunerHierarchy: 'portal-frame-tuner-hierarchy',
    TunerAppLayoutPane: 'portal-frame-tuner-app-layout-pane',
    TunerContentEditor: 'portal-frame-tuner-content-editor',
    TunerContentList: 'portal-frame-tuner-content-list',
    TunerContentItem: 'portal-frame-tuner-content-item',
    TunerContentFields: 'portal-frame-tuner-content-fields',
    TunerContentButtons: 'portal-frame-tuner-content-buttons',
    TunerContentInput: 'portal-frame-tuner-content-input',
    TunerContentSummary: 'portal-frame-tuner-content-summary',
  },
  CssVar: {
    ContentGap: '--portal-frame-content-gap',
    ContentInsetX: '--portal-frame-content-inset-x',
    ContentInsetY: '--portal-frame-content-inset-y',
    ContentOffsetX: '--portal-frame-content-offset-x',
    ContentOffsetY: '--portal-frame-content-offset-y',
    ContentClipX: '--portal-frame-content-clip-x',
    ContentClipY: '--portal-frame-content-clip-y',
    SlotHeightAdjust: '--portal-frame-slot-height-adjust',
    SlotWidthAdjust: '--portal-frame-slot-width-adjust',
    SideBottomHeight: '--portal-sidebar-bottom-height',
    SideStackGap: '--portal-sidebar-stack-gap',
    GoldenCardContentBoundsOpacity: '--portal-golden-card-content-bounds-opacity',
    GoldenCardContentInsetX: '--portal-golden-card-content-inset-x',
    GoldenCardContentInsetY: '--portal-golden-card-content-inset-y',
    GoldenCardContentOffsetX: '--portal-golden-card-content-offset-x',
    GoldenCardContentOffsetY: '--portal-golden-card-content-offset-y',
    GoldenCardContentOpacity: '--portal-golden-card-content-opacity',
    GoldenCardFrameBoundsOpacity: '--portal-golden-card-frame-bounds-opacity',
    GoldenCardFrameGlowBlur: '--portal-golden-card-frame-glow-blur',
    GoldenCardFrameGlowOpacity: '--portal-golden-card-frame-glow-opacity',
    GoldenCardFrameHeightAdjust: '--portal-golden-card-frame-height-adjust',
    GoldenCardFrameInset: '--portal-golden-card-frame-inset',
    GoldenCardFrameOffsetX: '--portal-golden-card-frame-offset-x',
    GoldenCardFrameOffsetY: '--portal-golden-card-frame-offset-y',
    GoldenCardFrameOpacity: '--portal-golden-card-frame-opacity',
    GoldenCardFrameWidthAdjust: '--portal-golden-card-frame-width-adjust',
    GoldenCardGlyphSize: '--portal-golden-card-glyph-size',
    GoldenCardHeight: '--portal-golden-card-height',
    GoldenCardPaddingX: '--portal-golden-card-padding-x',
    GoldenCardPaddingY: '--portal-golden-card-padding-y',
    GoldenCardTitleOffsetX: '--portal-golden-card-title-offset-x',
    GoldenCardTitleOffsetY: '--portal-golden-card-title-offset-y',
    CarouselCardMinWidth: '--portal-carousel-card-min-width',
    CarouselCardWidthPercent: '--portal-carousel-card-width-percent',
    CarouselFrameHeightAdjust: '--portal-carousel-frame-height-adjust',
    CarouselFrameInsetX: '--portal-carousel-frame-inset-x',
    CarouselFrameInsetY: '--portal-carousel-frame-inset-y',
    CarouselFrameOffsetX: '--portal-carousel-frame-offset-x',
    CarouselFrameOffsetY: '--portal-carousel-frame-offset-y',
    CarouselFrameOpacity: '--portal-carousel-frame-opacity',
    CarouselFrameWidthAdjust: '--portal-carousel-frame-width-adjust',
    CarouselMinHeight: '--portal-carousel-min-height',
    CarouselPaddingBottom: '--portal-carousel-padding-bottom',
    CarouselPaddingLeft: '--portal-carousel-padding-left',
    CarouselPaddingRight: '--portal-carousel-padding-right',
    CarouselPaddingTop: '--portal-carousel-padding-top',
    CarouselRailGap: '--portal-carousel-rail-gap',
    CarouselRailPaddingBottom: '--portal-carousel-rail-padding-bottom',
    CarouselRailPaddingLeft: '--portal-carousel-rail-padding-left',
    CarouselRailPaddingRight: '--portal-carousel-rail-padding-right',
    CarouselRailPaddingTop: '--portal-carousel-rail-padding-top',
    CarouselTitleLeft: '--portal-carousel-title-left',
    CarouselTitleRight: '--portal-carousel-title-right',
    CarouselTitleTop: '--portal-carousel-title-top',
  },
  InputType: {
    Checkbox: 'checkbox',
    Color: 'color',
    Number: 'number',
    Range: 'range',
    Text: 'text',
  },
  FrameTarget: {
    Side: 'side',
    SideTop: 'sideTop',
    SideBottom: 'sideBottom',
    Main: 'main',
  },
  Panel: {
    MainApp: 'mainApp',
    ChatInterface: 'chatInterface',
    Shell: 'shell',
    SideAnchors: 'sideAnchors',
    SideChrome: 'sideChrome',
    SidePanel: 'sidePanel',
    MainAnchors: 'mainAnchors',
    MainChrome: 'mainChrome',
    MainPanel: 'mainPanel',
    Carousel: 'carousel',
    GoldenCard: 'goldenCard',
    Preview: 'preview',
  },
  FrameSection: {
    Viewport: 'viewport',
    Placement: 'placement',
    OuterAnchors: 'outerAnchors',
    InnerAnchors: 'innerAnchors',
    OuterFrame: 'outerFrame',
    OuterGaps: 'outerGaps',
    OuterEdges: 'outerEdges',
    OuterSegments: 'outerSegments',
    InnerFrame: 'innerFrame',
    InnerGaps: 'innerGaps',
    InnerEdges: 'innerEdges',
    InnerSegments: 'innerSegments',
    Colors: 'colors',
    Content: 'content',
  },
  LayoutKey: {
    ParentPortal: 'parentPortal',
    ContentDraft: 'contentDraft',
    SidePanelFoldouts: 'sidePanelFoldouts',
    MainPanelTop: 'mainPanelTop',
    MainPanelBottom: 'mainPanelBottom',
    Id: 'id',
    Label: 'label',
    Detail: 'detail',
    RoutePath: 'routePath',
    Icon: 'icon',
    Tone: 'tone',
    Buttons: 'buttons',
    Orientation: 'orientation',
    Content: 'content',
    Shell: 'shell',
    Preview: 'preview',
    Carousel: 'carousel',
    GoldenCard: 'goldenCard',
    ShowContent: 'showContent',
    MinHeight: 'minHeight',
    SidebarWidth: 'sidebarWidth',
    ShellEdge: 'shellEdge',
    BodyInset: 'bodyInset',
    FrameGap: 'frameGap',
    SideBottomHeight: 'sideBottomHeight',
    SideStackGap: 'sideStackGap',
    ShowBounds: 'showBounds',
    ShowContentBounds: 'showContentBounds',
    ContentInsetX: 'insetX',
    ContentInsetY: 'insetY',
    ContentOffsetX: 'offsetX',
    ContentOffsetY: 'offsetY',
    ContentGap: 'gap',
    ShowFrameBounds: 'showFrameBounds',
    ViewBox: 'viewBox',
    FrameSpace: 'frameSpace',
    FrameGroup: 'frameGroup',
    SlotHeightAdjust: 'slotHeightAdjust',
    SlotWidthAdjust: 'slotWidthAdjust',
    OuterAnchor: 'outerAnchor',
    InnerAnchor: 'innerAnchor',
    OuterFrame: 'outerFrame',
    InnerFrame: 'innerFrame',
    SegmentThicknesses: 'segmentThicknesses',
    Width: 'w',
    Height: 'h',
    Inset: 'inset',
    OffsetX: 'offsetX',
    OffsetY: 'offsetY',
    PaddingTop: 'paddingTop',
    PaddingRight: 'paddingRight',
    PaddingBottom: 'paddingBottom',
    PaddingLeft: 'paddingLeft',
    SideInset: 'sideInset',
    TopInset: 'topInset',
    BottomInset: 'bottomInset',
    CornerCut: 'cornerCut',
    TopRise: 'topRise',
    TopStepWidth: 'topStepWidth',
    TopStepInset: 'topStepInset',
    BottomTabWidth: 'bottomTabWidth',
    BottomTabDepth: 'bottomTabDepth',
    BottomTabInset: 'bottomTabInset',
    TopLeftThickness: 'topLeftThickness',
    TopCenterThickness: 'topCenterThickness',
    TopRightThickness: 'topRightThickness',
    LeftSideThickness: 'leftSideThickness',
    RightSideThickness: 'rightSideThickness',
    BottomLeftThickness: 'bottomLeftThickness',
    BottomCenterThickness: 'bottomCenterThickness',
    BottomRightThickness: 'bottomRightThickness',
    TopGroupThickness: 'topGroupThickness',
    BottomGroupThickness: 'bottomGroupThickness',
    CornerGroupThickness: 'cornerGroupThickness',
    ThinLineGroupThickness: 'thinLineGroupThickness',
    TopLeftStartGap: 'topLeftStartGap',
    TopLeftEndGap: 'topLeftEndGap',
    TopRightStartGap: 'topRightStartGap',
    TopRightEndGap: 'topRightEndGap',
    BottomLeftStartGap: 'bottomLeftStartGap',
    BottomLeftEndGap: 'bottomLeftEndGap',
    BottomRightStartGap: 'bottomRightStartGap',
    BottomRightEndGap: 'bottomRightEndGap',
    LeftSideStartGap: 'leftSideStartGap',
    LeftSideEndGap: 'leftSideEndGap',
    RightSideStartGap: 'rightSideStartGap',
    RightSideEndGap: 'rightSideEndGap',
    GlowOpacity: 'glowOpacity',
    GlowBlur: 'glowBlur',
    GlowWidthBoost: 'glowWidthBoost',
    OutlineOpacity: 'outlineOpacity',
    OutlineWidthBoost: 'outlineWidthBoost',
    Opacity: 'opacity',
    Color: 'color',
    GlowColor: 'glowColor',
    FrameInset: 'frameInset',
    FrameInsetX: 'frameInsetX',
    FrameInsetY: 'frameInsetY',
    CardHeight: 'height',
    CardMinWidth: 'cardMinWidth',
    CardWidthPercent: 'cardWidthPercent',
    FrameWidthAdjust: 'frameWidthAdjust',
    FrameHeightAdjust: 'frameHeightAdjust',
    FrameOpacity: 'frameOpacity',
    FrameGlowBlur: 'frameGlowBlur',
    FrameGlowOpacity: 'frameGlowOpacity',
    PaddingX: 'paddingX',
    PaddingY: 'paddingY',
    GlyphSize: 'glyphSize',
    TitleOffsetX: 'titleOffsetX',
    TitleOffsetY: 'titleOffsetY',
    TitleLeft: 'titleLeft',
    TitleRight: 'titleRight',
    TitleTop: 'titleTop',
    RailGap: 'railGap',
    RailPaddingTop: 'railPadTop',
    RailPaddingRight: 'railPadRight',
    RailPaddingBottom: 'railPadBottom',
    RailPaddingLeft: 'railPadLeft',
  },
  Segment: {
    TopLeftRunStart: 'topLeftRunStart',
    TopLeftRunMid: 'topLeftRunMid',
    TopLeftRunEnd: 'topLeftRunEnd',
    TopLeftConnector: 'topLeftConnector',
    TopCenterRun: 'topCenterRun',
    TopRightConnector: 'topRightConnector',
    TopRightRunStart: 'topRightRunStart',
    TopRightRunMid: 'topRightRunMid',
    TopRightRunEnd: 'topRightRunEnd',
    RightTopCorner: 'rightTopCorner',
    RightSideRunStart: 'rightSideRunStart',
    RightSideRunMid: 'rightSideRunMid',
    RightSideRunEnd: 'rightSideRunEnd',
    RightBottomCorner: 'rightBottomCorner',
    BottomRightRunStart: 'bottomRightRunStart',
    BottomRightRunMid: 'bottomRightRunMid',
    BottomRightRunEnd: 'bottomRightRunEnd',
    BottomRightConnector: 'bottomRightConnector',
    BottomCenterRun: 'bottomCenterRun',
    BottomLeftConnector: 'bottomLeftConnector',
    BottomLeftRunStart: 'bottomLeftRunStart',
    BottomLeftRunMid: 'bottomLeftRunMid',
    BottomLeftRunEnd: 'bottomLeftRunEnd',
    LeftBottomCorner: 'leftBottomCorner',
    LeftSideRunStart: 'leftSideRunStart',
    LeftSideRunMid: 'leftSideRunMid',
    LeftSideRunEnd: 'leftSideRunEnd',
    LeftTopCorner: 'leftTopCorner',
  },
  Orientation: {
    Portrait: 'portrait',
    Landscape: 'landscape',
  },
  Color: {
    Cyan: '#42e8ff',
    DeepBlue: '#06111f',
    Gold: '#f6c34a',
  },
  AppSurface: {
    MainApp: 'mainApp',
    ChatInterface: 'chatInterface',
  },
  AppContentArea: {
    SidePanelFoldouts: 'sidePanelFoldouts',
    MainPanelTop: 'mainPanelTop',
    MainPanelBottom: 'mainPanelBottom',
  },
  AppLayoutTone: {
    Cyan: 'cyan',
    Gold: 'gold',
    Purple: 'purple',
    Red: 'red',
    Muted: 'muted',
  },
  AppLayoutRegion: {
    SidePanel: 'sidePanel',
    MainPanel: 'mainPanel',
  },
  AppLayoutSection: {
    Top: 'top',
    Bottom: 'bottom',
    Chrome: 'chrome',
    Colors: 'colors',
    Content: 'content',
  },
  AppLayoutFieldKey: {
    CanvasWidth: 'canvas.width',
    CanvasHeight: 'canvas.height',
    LayoutOuterPad: 'layout.outerPad',
    LayoutGap: 'layout.gap',
    LayoutLeftW: 'layout.leftW',
    LayoutRightW: 'layout.rightW',
    LayoutTopY: 'layout.topY',
    LayoutHeaderH: 'layout.headerH',
    LayoutTabsY: 'layout.tabsY',
    LayoutTabsH: 'layout.tabsH',
    LayoutMainY: 'layout.mainY',
    LayoutBottomY: 'layout.bottomY',
    LayoutBottomH: 'layout.bottomH',
    ChromePanelCut: 'chrome.panelCut',
    ChromePanelStrokeWidth: 'chrome.panelStrokeWidth',
    ChromePanelInnerInset: 'chrome.panelInnerInset',
    ChromeHoverPad: 'chrome.hoverPad',
    ChromeGlowOpacity: 'chrome.glowOpacity',
    ChromeButtonArrowWidth: 'chrome.buttonArrowWidth',
    ChromeRowHeight: 'chrome.rowHeight',
    ChromeRowGap: 'chrome.rowGap',
    ChromeAvatarRadius: 'chrome.avatarRadius',
  },
  AppLayoutFieldSeparator: '.',
  ValueType: {
    String: 'string',
  },
  ParentPortalControlGroup: {
    Canvas: 'canvas',
    Layout: 'layout',
    Colors: 'colors',
    Chrome: 'chrome',
  },
  GoldenFrame: {
    StorageKey: 'ocentra-foreign-frame-config',
    Channel: 'ocentra-foreign-frame-channel',
    ToneGold: 'gold',
    ToneSilver: 'silver',
    ToneBronze: 'bronze',
    ToneBlue: 'blue',
    ValueType: {
      Object: 'object',
      Undefined: 'undefined',
    },
    ConfigKey: {
      OuterFrame: 'outerFrame',
      InnerFrame: 'innerFrame',
      SideHexBadge: 'sideHexBadge',
      WinnerName: 'winnerName',
      RightStats: 'rightStats',
    },
  },
  Text: {
    RouteTitle: decodeDisplayText('App layout'),
    RouteDescription: decodeDisplayText('Layout and content authoring for parent portal app surfaces.'),
    TargetSide: decodeDisplayText('Side panel'),
    TargetSideTop: decodeDisplayText('Side navigation frame'),
    TargetSideBottom: decodeDisplayText('Side device frame'),
    TargetMain: decodeDisplayText('Main body'),
    ShellSection: decodeDisplayText('Shell fit'),
    FrameSection: decodeDisplayText('Frame geometry'),
    AnchorSection: decodeDisplayText('Anchors'),
    ChromeSection: decodeDisplayText('Stroke and glow'),
    HideInnerContent: decodeDisplayText('Show inner content'),
    Save: decodeDisplayText('Save JSON'),
    Reset: decodeDisplayText('Reset'),
    Saved: decodeDisplayText('Saved layout JSON.'),
    ResetLoaded: decodeDisplayText('Loaded saved layout JSON.'),
    SaveFailed: decodeDisplayText('Save failed. Check the Vite dev server.'),
    Loading: decodeDisplayText('Loading frame layout.'),
    Ready: decodeDisplayText('Frame layout ready.'),
    PreviewSidebar: decodeDisplayText('Navigation frame preview'),
    PreviewMain: decodeDisplayText('Main panel frame preview'),
    JsonTitle: decodeDisplayText('Saved JSON preview'),
    PanelMainApp: decodeDisplayText('Main App'),
    PanelChatInterface: decodeDisplayText('Chat Interface'),
    PanelShell: decodeDisplayText('Shell'),
    PanelSidePanel: decodeDisplayText('Side panel'),
    PanelMainPanel: decodeDisplayText('Main panel'),
    PanelCarousel: decodeDisplayText('Carousel'),
    PanelGoldenCard: decodeDisplayText('Golden card'),
    PanelPreview: decodeDisplayText('Save and JSON'),
    SideTopTab: decodeDisplayText('Top'),
    SideBottomTab: decodeDisplayText('Bottom'),
    ResetShell: decodeDisplayText('Reset shell'),
    ResetSideTop: decodeDisplayText('Reset top'),
    ResetSideBottom: decodeDisplayText('Reset bottom'),
    ResetMain: decodeDisplayText('Reset main'),
    ResetSurface: decodeDisplayText('Reset surface'),
    ResetContentDraft: decodeDisplayText('Reset content draft'),
    ResetCarousel: decodeDisplayText('Reset carousel'),
    ResetGoldenCard: decodeDisplayText('Reset golden card'),
    ToggleContent: decodeDisplayText('Content'),
    ToggleFrameBounds: decodeDisplayText('Purple frame bounds'),
    ToggleContentBounds: decodeDisplayText('Yellow content bounds'),
    SideTopAnchors: decodeDisplayText('Side navigation anchors'),
    SideTopChrome: decodeDisplayText('Side navigation stroke'),
    SideTopColors: decodeDisplayText('Side navigation colors'),
    SideBottomAnchors: decodeDisplayText('Side device anchors'),
    SideBottomChrome: decodeDisplayText('Side device stroke'),
    SideBottomColors: decodeDisplayText('Side device colors'),
    MainAnchors: decodeDisplayText('Main anchors'),
    MainChrome: decodeDisplayText('Main stroke'),
    MainColors: decodeDisplayText('Main colors'),
    GoldenCardFit: decodeDisplayText('Golden card frame'),
    GoldenCardContent: decodeDisplayText('Golden card content'),
    CarouselFrameFit: decodeDisplayText('Carousel frame'),
    CarouselContentFit: decodeDisplayText('Carousel content'),
    CarouselRailFit: decodeDisplayText('Carousel rail'),
    ViewportGroup: decodeDisplayText('Advanced SVG camera'),
    FrameGroup: decodeDisplayText('Frame move'),
    OuterAnchorGroup: decodeDisplayText('Fit frame'),
    InnerAnchorGroup: decodeDisplayText('Inner frame fit'),
    OuterFrameGroup: decodeDisplayText('Outer frame'),
    OuterEdgeGroup: decodeDisplayText('Outer edge widths'),
    OuterGapGroup: decodeDisplayText('Outer segment gaps'),
    InnerFrameGroup: decodeDisplayText('Inner frame'),
    InnerEdgeGroup: decodeDisplayText('Inner edge widths'),
    InnerGapGroup: decodeDisplayText('Inner segment gaps'),
    OuterSegmentGroup: decodeDisplayText('Outer segment widths'),
    InnerSegmentGroup: decodeDisplayText('Inner segment widths'),
    ColorsGroup: decodeDisplayText('Colors'),
    ContentGroup: decodeDisplayText('Content'),
    FrameSlotGroup: decodeDisplayText('Frame box size'),
    FrameSpaceGroup: decodeDisplayText('Frame path size'),
    OrientationGroup: decodeDisplayText('SVG orientation'),
    Portrait: decodeDisplayText('Portrait'),
    Landscape: decodeDisplayText('Landscape'),
    BoundsGroup: decodeDisplayText('Bounds and visibility'),
    ContentFitGroup: decodeDisplayText('Content fit'),
    AppLayoutSurfaceFit: decodeDisplayText('Surface fit'),
    AppLayoutSidePanel: decodeDisplayText('Side panel'),
    AppLayoutMainPanel: decodeDisplayText('Main panel'),
    AppLayoutTop: decodeDisplayText('Top'),
    AppLayoutBottom: decodeDisplayText('Bottom'),
    AppLayoutSideTop: decodeDisplayText('Sidepanel top'),
    AppLayoutSideBottom: decodeDisplayText('Sidepanel bottom'),
    AppLayoutTopCards: decodeDisplayText('Top cards'),
    AppLayoutTopChoices: decodeDisplayText('Top choices'),
    AppLayoutMainBottom: decodeDisplayText('Main bottom'),
    AppLayoutChrome: decodeDisplayText('Chrome'),
    AppLayoutColors: decodeDisplayText('Colors'),
    AppLayoutContent: decodeDisplayText('Content'),
    SidePanelFoldouts: decodeDisplayText('Sidepanel foldouts'),
    MainPanelTopContent: decodeDisplayText('Main top content'),
    MainPanelBottomContent: decodeDisplayText('Main bottom content'),
    AddFoldout: decodeDisplayText('Add foldout'),
    AddButton: decodeDisplayText('Add button'),
    Remove: decodeDisplayText('Remove'),
    FoldoutName: decodeDisplayText('Foldout name'),
    ButtonLabel: decodeDisplayText('Button label'),
    ButtonDetail: decodeDisplayText('Button detail'),
    ButtonRoute: decodeDisplayText('Button route'),
    ButtonIcon: decodeDisplayText('Button icon'),
    Theme: decodeDisplayText('Theme'),
    ContentAuthoringSummary: decodeDisplayText(
      'Author layout content here, then wire it into the runtime surface when ready.'
    ),
    ResetGlyph: decodeDisplayText('↺'),
    ShowFrameBounds: decodeDisplayText('Show frame bounds'),
    ShowContentBounds: decodeDisplayText('Show content bounds'),
    ShowFrameContent: decodeDisplayText('Show content'),
    ContentInsetX: decodeDisplayText('Inset X'),
    ContentInsetY: decodeDisplayText('Inset Y'),
    ContentOffsetX: decodeDisplayText('Offset X'),
    ContentOffsetY: decodeDisplayText('Offset Y'),
    ContentGap: decodeDisplayText('Gap'),
    SlotWidthAdjust: decodeDisplayText('Frame box width +/-'),
    SlotHeightAdjust: decodeDisplayText('Frame box height +/-'),
    GoldenCardHeight: decodeDisplayText('Card height'),
    GoldenCardPaddingX: decodeDisplayText('Padding X'),
    GoldenCardPaddingY: decodeDisplayText('Padding Y'),
    GoldenCardFrameInset: decodeDisplayText('Frame inset'),
    GoldenCardFrameWidthAdjust: decodeDisplayText('Frame width +/-'),
    GoldenCardFrameHeightAdjust: decodeDisplayText('Frame height +/-'),
    GoldenCardFrameOffsetX: decodeDisplayText('Frame offset X'),
    GoldenCardFrameOffsetY: decodeDisplayText('Frame offset Y'),
    GoldenCardFrameOpacity: decodeDisplayText('Frame opacity'),
    GoldenCardFrameGlowBlur: decodeDisplayText('Frame glow blur'),
    GoldenCardFrameGlowOpacity: decodeDisplayText('Frame glow opacity'),
    GoldenCardGlyphSize: decodeDisplayText('Glyph size'),
    GoldenCardTitleOffsetX: decodeDisplayText('Title offset X'),
    GoldenCardTitleOffsetY: decodeDisplayText('Title offset Y'),
    CarouselMinHeight: decodeDisplayText('Carousel height'),
    CarouselFrameInsetX: decodeDisplayText('Frame inset X'),
    CarouselFrameInsetY: decodeDisplayText('Frame inset Y'),
    CarouselFrameOffsetX: decodeDisplayText('Frame offset X'),
    CarouselFrameOffsetY: decodeDisplayText('Frame offset Y'),
    CarouselFrameWidthAdjust: decodeDisplayText('Frame width +/-'),
    CarouselFrameHeightAdjust: decodeDisplayText('Frame height +/-'),
    CarouselFrameOpacity: decodeDisplayText('Frame opacity'),
    CarouselPaddingTop: decodeDisplayText('Padding top'),
    CarouselPaddingRight: decodeDisplayText('Padding right'),
    CarouselPaddingBottom: decodeDisplayText('Padding bottom'),
    CarouselPaddingLeft: decodeDisplayText('Padding left'),
    CarouselTitleLeft: decodeDisplayText('Title left'),
    CarouselTitleRight: decodeDisplayText('Title right'),
    CarouselTitleTop: decodeDisplayText('Title top'),
    CarouselRailGap: decodeDisplayText('Rail gap'),
    CarouselRailPaddingTop: decodeDisplayText('Rail padding top'),
    CarouselRailPaddingRight: decodeDisplayText('Rail padding right'),
    CarouselRailPaddingBottom: decodeDisplayText('Rail padding bottom'),
    CarouselRailPaddingLeft: decodeDisplayText('Rail padding left'),
    CarouselCardMinWidth: decodeDisplayText('Card min width'),
    CarouselCardWidthPercent: decodeDisplayText('Card width %'),
    OuterColor: decodeDisplayText('Outer color'),
    OuterGlowColor: decodeDisplayText('Outer glow color'),
    InnerColor: decodeDisplayText('Inner color'),
    InnerGlowColor: decodeDisplayText('Inner glow color'),
  },
} as const;

export type PortalFrameTargetValue = (typeof PortalFrameTuner.FrameTarget)[keyof typeof PortalFrameTuner.FrameTarget];
export type PortalFrameTunerFrameSectionValue =
  (typeof PortalFrameTuner.FrameSection)[keyof typeof PortalFrameTuner.FrameSection];
export type PortalFrameCssStyle = Record<string, string>;
export type PortalFrameCssValue = string;

export type PortalFrameBooleanField = {
  readonly path: readonly string[];
  readonly label: ReturnType<typeof decodeDisplayText>;
};

export type PortalFrameNumberField = {
  readonly path: readonly string[];
  readonly label: ReturnType<typeof decodeDisplayText>;
  readonly min: number;
  readonly max: number;
  readonly step: number;
};

export type PortalFrameColorField = {
  readonly path: readonly string[];
  readonly label: ReturnType<typeof decodeDisplayText>;
};

const key = PortalFrameTuner.LayoutKey;

export const PortalFrameShellNumberFields: readonly PortalFrameNumberField[] = [
  field([key.SidebarWidth], 'Sidebar width', 220, 340, 1),
  field([key.SideBottomHeight], 'Bottom frame height', 96, 180, 1),
  field([key.SideStackGap], 'Side frame gap', 0, 24, 1),
  field([key.ShellEdge], 'Shell edge', 0, 20, 1),
  field([key.BodyInset], 'Body inset', 10, 40, 1),
  field([key.FrameGap], 'Frame gap', -10, 20, 1),
] as const;

export const PortalFrameContentBooleanFields: readonly PortalFrameBooleanField[] = [
  booleanField([key.ShowFrameBounds], PortalFrameTuner.Text.ShowFrameBounds),
  booleanField([key.ShowContentBounds], PortalFrameTuner.Text.ShowContentBounds),
  booleanField([key.ShowContent], PortalFrameTuner.Text.ShowFrameContent),
] as const;

export const PortalGoldenCardBooleanFields: readonly PortalFrameBooleanField[] = [
  booleanField([key.ShowFrameBounds], PortalFrameTuner.Text.ShowFrameBounds),
  booleanField([key.ShowContentBounds], PortalFrameTuner.Text.ShowContentBounds),
  booleanField([key.ShowContent], PortalFrameTuner.Text.ShowFrameContent),
] as const;

export const PortalFrameContentNumberFields: readonly PortalFrameNumberField[] = [
  field([key.ContentInsetX], 'Inset X', 0, 80, 1),
  field([key.ContentInsetY], 'Inset Y', 0, 80, 1),
  field([key.ContentOffsetX], 'Offset X', -80, 80, 1),
  field([key.ContentOffsetY], 'Offset Y', -80, 80, 1),
  field([key.ContentGap], 'Gap', 0, 40, 1),
] as const;

export const PortalGoldenCardFrameNumberFields: readonly PortalFrameNumberField[] = [
  field([key.CardHeight], 'Card height', 130, 260, 1),
  field([key.FrameInset], 'Frame inset', -24, 24, 1),
  field([key.FrameWidthAdjust], 'Frame width +/-', -80, 120, 1),
  field([key.FrameHeightAdjust], 'Frame height +/-', -80, 120, 1),
  field([key.FrameGroup, key.OffsetX], 'Frame offset X', -80, 80, 1),
  field([key.FrameGroup, key.OffsetY], 'Frame offset Y', -80, 80, 1),
  field([key.FrameOpacity], 'Frame opacity', 0, 1, 0.01),
  field([key.FrameGlowBlur], 'Frame glow blur', 0, 24, 1),
  field([key.FrameGlowOpacity], 'Frame glow opacity', 0, 0.6, 0.01),
] as const;

export const PortalGoldenCardContentNumberFields: readonly PortalFrameNumberField[] = [
  field([key.PaddingX], 'Padding X', 0, 60, 1),
  field([key.PaddingY], 'Padding Y', 0, 70, 1),
  field([key.ContentInsetX], 'Content bounds X', 0, 80, 1),
  field([key.ContentInsetY], 'Content bounds Y', 0, 80, 1),
  field([key.ContentOffsetX], 'Content offset X', -80, 80, 1),
  field([key.ContentOffsetY], 'Content offset Y', -80, 80, 1),
  field([key.GlyphSize], 'Glyph size', 24, 64, 1),
  field([key.TitleOffsetX], 'Title offset X', -80, 80, 1),
  field([key.TitleOffsetY], 'Title offset Y', -40, 40, 1),
] as const;

export const PortalCarouselFrameNumberFields: readonly PortalFrameNumberField[] = [
  field([key.MinHeight], 'Carousel height', 190, 420, 1),
  field([key.FrameInsetX], 'Frame inset X', -80, 80, 1),
  field([key.FrameInsetY], 'Frame inset Y', -80, 80, 1),
  field([key.FrameWidthAdjust], 'Frame width +/-', -160, 200, 1),
  field([key.FrameHeightAdjust], 'Frame height +/-', -120, 160, 1),
  field([key.FrameGroup, key.OffsetX], 'Frame offset X', -120, 120, 1),
  field([key.FrameGroup, key.OffsetY], 'Frame offset Y', -120, 120, 1),
  field([key.FrameOpacity], 'Frame opacity', 0, 1, 0.01),
] as const;

export const PortalCarouselContentNumberFields: readonly PortalFrameNumberField[] = [
  field([key.PaddingTop], 'Padding top', 0, 100, 1),
  field([key.PaddingRight], 'Padding right', 0, 120, 1),
  field([key.PaddingBottom], 'Padding bottom', 0, 100, 1),
  field([key.PaddingLeft], 'Padding left', 0, 120, 1),
  field([key.TitleLeft], 'Title left', 0, 180, 1),
  field([key.TitleRight], 'Title right', 0, 180, 1),
  field([key.TitleTop], 'Title top', -20, 80, 1),
] as const;

export const PortalCarouselRailNumberFields: readonly PortalFrameNumberField[] = [
  field([key.RailGap], 'Rail gap', 0, 48, 1),
  field([key.RailPaddingTop], 'Rail padding top', 0, 80, 1),
  field([key.RailPaddingRight], 'Rail padding right', 0, 80, 1),
  field([key.RailPaddingBottom], 'Rail padding bottom', 0, 80, 1),
  field([key.RailPaddingLeft], 'Rail padding left', 0, 80, 1),
  field([key.CardMinWidth], 'Card min width', 220, 520, 1),
  field([key.CardWidthPercent], 'Card width %', 28, 96, 1),
] as const;

export const PortalFrameSlotNumberFields: readonly PortalFrameNumberField[] = [
  field([key.SlotWidthAdjust], 'Frame box width +/-', -180, 240, 1),
  field([key.SlotHeightAdjust], 'Frame box height +/-', -180, 240, 1),
] as const;

export const PortalFrameGeometryNumberFields: readonly PortalFrameNumberField[] = [
  field([key.ViewBox, key.Width], 'Camera width', 700, 2200, 1),
  field([key.ViewBox, key.Height], 'Camera height', 700, 2400, 1),
  field([key.FrameSpace, key.Width], 'Path width', 300, 2600, 1),
  field([key.FrameSpace, key.Height], 'Path height', 180, 2400, 1),
  field([key.FrameGroup, key.Inset], 'Uniform margin', 0, 60, 1),
  field([key.FrameGroup, key.OffsetX], 'Move frame X', -120, 120, 1),
  field([key.FrameGroup, key.OffsetY], 'Move frame Y', -120, 120, 1),
  field([key.OuterAnchor, key.SideInset], 'Left/right padding', 0, 120, 1),
  field([key.OuterAnchor, key.TopInset], 'Top padding', 0, 140, 1),
  field([key.OuterAnchor, key.BottomInset], 'Bottom padding', 0, 140, 1),
  field([key.InnerAnchor, key.SideInset], 'Inner left/right padding', 0, 160, 1),
  field([key.InnerAnchor, key.TopInset], 'Inner top padding', 0, 180, 1),
  field([key.InnerAnchor, key.BottomInset], 'Inner bottom padding', 0, 180, 1),
] as const;

export const PortalFrameChromeNumberFields: readonly PortalFrameNumberField[] = [
  field([key.OuterFrame, key.CornerCut], 'Outer corner cut', 20, 140, 1),
  field([key.OuterFrame, key.TopRise], 'Outer top rise', 0, 120, 1),
  field([key.OuterFrame, key.TopStepWidth], 'Outer top step', 120, 920, 1),
  field([key.OuterFrame, key.BottomTabWidth], 'Outer bottom tab', 120, 920, 1),
  field([key.OuterFrame, key.GlowOpacity], 'Outer glow opacity', 0, 0.8, 0.01),
  field([key.OuterFrame, key.GlowBlur], 'Outer glow blur', 0, 40, 1),
  field([key.OuterFrame, key.GlowWidthBoost], 'Outer glow width', 0, 16, 1),
  field([key.InnerFrame, key.CornerCut], 'Inner corner cut', 10, 120, 1),
  field([key.InnerFrame, key.TopStepWidth], 'Inner top step', 120, 820, 1),
  field([key.InnerFrame, key.BottomTabWidth], 'Inner bottom tab', 120, 820, 1),
  field([key.InnerFrame, key.OutlineOpacity], 'Inner outline opacity', 0, 1, 0.01),
  field([key.InnerFrame, key.Opacity], 'Inner opacity', 0, 1, 0.01),
] as const;

export const PortalFrameOuterShapeNumberFields: readonly PortalFrameNumberField[] = [
  field([key.OuterFrame, key.SideInset], 'Side inset', 0, 160, 1),
  field([key.OuterFrame, key.CornerCut], 'Corner cut', 0, 160, 1),
  field([key.OuterFrame, key.TopRise], 'Top rise', 0, 140, 1),
  field([key.OuterFrame, key.TopStepWidth], 'Top step width', 40, 1000, 1),
  field([key.OuterFrame, key.TopStepInset], 'Top step inset', 0, 140, 1),
  field([key.OuterFrame, key.BottomTabWidth], 'Bottom tab width', 40, 1000, 1),
  field([key.OuterFrame, key.BottomTabDepth], 'Bottom tab depth', 0, 160, 1),
  field([key.OuterFrame, key.BottomTabInset], 'Bottom tab inset', 0, 140, 1),
  field([key.OuterFrame, key.GlowOpacity], 'Glow opacity', 0, 0.8, 0.01),
  field([key.OuterFrame, key.GlowBlur], 'Glow blur', 0, 40, 1),
  field([key.OuterFrame, key.GlowWidthBoost], 'Glow width', 0, 16, 1),
  field([key.OuterFrame, key.OutlineOpacity], 'Outline opacity', 0, 1, 0.01),
  field([key.OuterFrame, key.OutlineWidthBoost], 'Outline width', 0, 12, 1),
  field([key.OuterFrame, key.Opacity], 'Opacity', 0, 1, 0.01),
] as const;

export const PortalFrameInnerShapeNumberFields: readonly PortalFrameNumberField[] = [
  field([key.InnerFrame, key.SideInset], 'Side inset', 0, 160, 1),
  field([key.InnerFrame, key.CornerCut], 'Corner cut', 0, 160, 1),
  field([key.InnerFrame, key.TopRise], 'Top rise', 0, 140, 1),
  field([key.InnerFrame, key.TopStepWidth], 'Top step width', 40, 1000, 1),
  field([key.InnerFrame, key.TopStepInset], 'Top step inset', 0, 140, 1),
  field([key.InnerFrame, key.BottomTabWidth], 'Bottom tab width', 40, 1000, 1),
  field([key.InnerFrame, key.BottomTabDepth], 'Bottom tab depth', 0, 160, 1),
  field([key.InnerFrame, key.BottomTabInset], 'Bottom tab inset', 0, 140, 1),
  field([key.InnerFrame, key.GlowOpacity], 'Glow opacity', 0, 0.8, 0.01),
  field([key.InnerFrame, key.GlowBlur], 'Glow blur', 0, 40, 1),
  field([key.InnerFrame, key.GlowWidthBoost], 'Glow width', 0, 16, 1),
  field([key.InnerFrame, key.OutlineOpacity], 'Outline opacity', 0, 1, 0.01),
  field([key.InnerFrame, key.OutlineWidthBoost], 'Outline width', 0, 12, 1),
  field([key.InnerFrame, key.Opacity], 'Opacity', 0, 1, 0.01),
] as const;

export const PortalFrameOuterEdgeNumberFields: readonly PortalFrameNumberField[] = [
  field([key.OuterFrame, key.TopGroupThickness], 'Top group', 0, 40, 1),
  field([key.OuterFrame, key.BottomGroupThickness], 'Bottom group', 0, 40, 1),
  field([key.OuterFrame, key.CornerGroupThickness], 'Corner group', 0, 40, 1),
  field([key.OuterFrame, key.ThinLineGroupThickness], 'Thin line group', 0, 20, 1),
  field([key.OuterFrame, key.TopLeftThickness], 'Top left', 0, 40, 1),
  field([key.OuterFrame, key.TopCenterThickness], 'Top center', 0, 40, 1),
  field([key.OuterFrame, key.TopRightThickness], 'Top right', 0, 40, 1),
  field([key.OuterFrame, key.LeftSideThickness], 'Left side', 0, 40, 1),
  field([key.OuterFrame, key.RightSideThickness], 'Right side', 0, 40, 1),
  field([key.OuterFrame, key.BottomLeftThickness], 'Bottom left', 0, 40, 1),
  field([key.OuterFrame, key.BottomCenterThickness], 'Bottom center', 0, 40, 1),
  field([key.OuterFrame, key.BottomRightThickness], 'Bottom right', 0, 40, 1),
] as const;

export const PortalFrameInnerEdgeNumberFields: readonly PortalFrameNumberField[] = [
  field([key.InnerFrame, key.TopGroupThickness], 'Top group', 0, 40, 1),
  field([key.InnerFrame, key.BottomGroupThickness], 'Bottom group', 0, 40, 1),
  field([key.InnerFrame, key.CornerGroupThickness], 'Corner group', 0, 40, 1),
  field([key.InnerFrame, key.ThinLineGroupThickness], 'Thin line group', 0, 20, 1),
  field([key.InnerFrame, key.TopLeftThickness], 'Top left', 0, 40, 1),
  field([key.InnerFrame, key.TopCenterThickness], 'Top center', 0, 40, 1),
  field([key.InnerFrame, key.TopRightThickness], 'Top right', 0, 40, 1),
  field([key.InnerFrame, key.LeftSideThickness], 'Left side', 0, 40, 1),
  field([key.InnerFrame, key.RightSideThickness], 'Right side', 0, 40, 1),
  field([key.InnerFrame, key.BottomLeftThickness], 'Bottom left', 0, 40, 1),
  field([key.InnerFrame, key.BottomCenterThickness], 'Bottom center', 0, 40, 1),
  field([key.InnerFrame, key.BottomRightThickness], 'Bottom right', 0, 40, 1),
] as const;

export const PortalFrameOuterGapNumberFields: readonly PortalFrameNumberField[] = [
  field([key.OuterFrame, key.TopLeftStartGap], 'Top left start', 0, 200, 1),
  field([key.OuterFrame, key.TopLeftEndGap], 'Top left end', 0, 200, 1),
  field([key.OuterFrame, key.TopRightStartGap], 'Top right start', 0, 200, 1),
  field([key.OuterFrame, key.TopRightEndGap], 'Top right end', 0, 200, 1),
  field([key.OuterFrame, key.BottomLeftStartGap], 'Bottom left start', 0, 200, 1),
  field([key.OuterFrame, key.BottomLeftEndGap], 'Bottom left end', 0, 200, 1),
  field([key.OuterFrame, key.BottomRightStartGap], 'Bottom right start', 0, 200, 1),
  field([key.OuterFrame, key.BottomRightEndGap], 'Bottom right end', 0, 200, 1),
  field([key.OuterFrame, key.LeftSideStartGap], 'Left side start', 0, 200, 1),
  field([key.OuterFrame, key.LeftSideEndGap], 'Left side end', 0, 200, 1),
  field([key.OuterFrame, key.RightSideStartGap], 'Right side start', 0, 200, 1),
  field([key.OuterFrame, key.RightSideEndGap], 'Right side end', 0, 200, 1),
] as const;

export const PortalFrameInnerGapNumberFields: readonly PortalFrameNumberField[] = [
  field([key.InnerFrame, key.TopLeftStartGap], 'Top left start', 0, 200, 1),
  field([key.InnerFrame, key.TopLeftEndGap], 'Top left end', 0, 200, 1),
  field([key.InnerFrame, key.TopRightStartGap], 'Top right start', 0, 200, 1),
  field([key.InnerFrame, key.TopRightEndGap], 'Top right end', 0, 200, 1),
  field([key.InnerFrame, key.BottomLeftStartGap], 'Bottom left start', 0, 200, 1),
  field([key.InnerFrame, key.BottomLeftEndGap], 'Bottom left end', 0, 200, 1),
  field([key.InnerFrame, key.BottomRightStartGap], 'Bottom right start', 0, 200, 1),
  field([key.InnerFrame, key.BottomRightEndGap], 'Bottom right end', 0, 200, 1),
  field([key.InnerFrame, key.LeftSideStartGap], 'Left side start', 0, 200, 1),
  field([key.InnerFrame, key.LeftSideEndGap], 'Left side end', 0, 200, 1),
  field([key.InnerFrame, key.RightSideStartGap], 'Right side start', 0, 200, 1),
  field([key.InnerFrame, key.RightSideEndGap], 'Right side end', 0, 200, 1),
] as const;

export const PortalFrameOuterSegmentNumberFields: readonly PortalFrameNumberField[] = [
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.TopLeftRunStart], 'Top left start', 0, 40, 1),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.TopLeftRunMid], 'Top left mid', 0, 40, 1),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.TopLeftRunEnd], 'Top left end', 0, 40, 1),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.TopLeftConnector],
    'Top left connector',
    0,
    40,
    1
  ),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.TopCenterRun], 'Top center run', 0, 40, 1),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.TopRightConnector],
    'Top right connector',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.TopRightRunStart],
    'Top right start',
    0,
    40,
    1
  ),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.TopRightRunMid], 'Top right mid', 0, 40, 1),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.TopRightRunEnd], 'Top right end', 0, 40, 1),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.RightTopCorner],
    'Right top corner',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.RightSideRunStart],
    'Right side start',
    0,
    40,
    1
  ),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.RightSideRunMid], 'Right side mid', 0, 40, 1),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.RightSideRunEnd], 'Right side end', 0, 40, 1),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.RightBottomCorner],
    'Right bottom corner',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.BottomRightRunStart],
    'Bottom right start',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.BottomRightRunMid],
    'Bottom right mid',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.BottomRightRunEnd],
    'Bottom right end',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.BottomRightConnector],
    'Bottom right connector',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.BottomCenterRun],
    'Bottom center run',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.BottomLeftConnector],
    'Bottom left connector',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.BottomLeftRunStart],
    'Bottom left start',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.BottomLeftRunMid],
    'Bottom left mid',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.BottomLeftRunEnd],
    'Bottom left end',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.LeftBottomCorner],
    'Left bottom corner',
    0,
    40,
    1
  ),
  field(
    [key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.LeftSideRunStart],
    'Left side start',
    0,
    40,
    1
  ),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.LeftSideRunMid], 'Left side mid', 0, 40, 1),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.LeftSideRunEnd], 'Left side end', 0, 40, 1),
  field([key.OuterFrame, key.SegmentThicknesses, PortalFrameTuner.Segment.LeftTopCorner], 'Left top corner', 0, 40, 1),
] as const;

export const PortalFrameInnerSegmentNumberFields: readonly PortalFrameNumberField[] =
  PortalFrameOuterSegmentNumberFields.map((fieldValue) => ({
    ...fieldValue,
    path: [key.InnerFrame, ...fieldValue.path.slice(1)],
  }));

export function portalFrameCssPixel(value: number): PortalFrameCssValue {
  return `${value}px`;
}

export function portalFrameCssPercent(value: number): PortalFrameCssValue {
  return `${value}%`;
}

export function portalFrameCssNumber(value: number): PortalFrameCssValue {
  return String(value);
}

export function portalFrameCssOpacity(value: boolean): PortalFrameCssValue {
  return value ? '1' : '0';
}

function booleanField(path: readonly string[], label: ReturnType<typeof decodeDisplayText>): PortalFrameBooleanField {
  return {
    path,
    label,
  };
}

function field(path: readonly string[], label: string, min: number, max: number, step: number): PortalFrameNumberField {
  return {
    path,
    label: decodeDisplayText(label),
    min,
    max,
    step,
  };
}
