import type {
  ParentLeaderboardCopyIconName,
  ParentLeaderboardCopyTabId,
  ParentLeaderboardCopyTone,
} from './parent-leaderboard-copy-data';

export type ParentLeaderboardCopyNavGroupId = 'quickGlance' | 'guide' | 'manage';

export type ParentLeaderboardCopyNavGroup = {
  readonly id: ParentLeaderboardCopyNavGroupId;
  readonly label: string;
  readonly detail: string;
};

export type ParentLeaderboardCopyNavItem = {
  readonly label: string;
  readonly detail: string;
  readonly icon: ParentLeaderboardCopyIconName;
  readonly tabId: ParentLeaderboardCopyTabId;
  readonly groupId: ParentLeaderboardCopyNavGroupId;
  readonly tone?: ParentLeaderboardCopyTone;
  readonly routePath?: string;
};

export const PARENT_LEADERBOARD_COPY_NAV_GROUPS: readonly ParentLeaderboardCopyNavGroup[] = [
  { id: 'quickGlance', label: 'QUICK GLANCE', detail: 'Current child-device state' },
  { id: 'guide', label: 'GUIDE', detail: 'Policy, privacy, and local AI' },
  { id: 'manage', label: 'MANAGE', detail: 'Devices, alerts, drives, support' },
] as const;

export const PARENT_LEADERBOARD_COPY_NAV_ITEMS: readonly ParentLeaderboardCopyNavItem[] = [
  {
    label: 'START HERE',
    detail: 'Setup and controls map',
    icon: 'home',
    tabId: 'overall',
    groupId: 'guide',
    tone: 'cyan',
    routePath: '#/leaderboard-copy',
  },
  {
    label: 'OVERVIEW',
    detail: 'Recent child-device state',
    icon: 'activity',
    tabId: 'overall',
    groupId: 'quickGlance',
    tone: 'cyan',
    routePath: '#/overview',
  },
  {
    label: 'ACTIVITY',
    detail: 'Stored activity timeline',
    icon: 'activity',
    tabId: 'overall',
    groupId: 'quickGlance',
    tone: 'purple',
    routePath: '#/activity',
  },
  {
    label: 'WEB',
    detail: 'Supported and unsupported',
    icon: 'shield',
    tabId: 'perGame',
    groupId: 'quickGlance',
    tone: 'cyan',
    routePath: '#/browser',
  },
  {
    label: 'RULES',
    detail: 'Allow, ask, explain, block',
    icon: 'grid',
    tabId: 'perGame',
    groupId: 'guide',
    tone: 'gold',
    routePath: '#/policy',
  },
  {
    label: 'MEMORY',
    detail: 'Cited local knowledge',
    icon: 'circle',
    tabId: 'aiBenchmarks',
    groupId: 'guide',
    tone: 'purple',
    routePath: '#/memory',
  },
  {
    label: 'AI',
    detail: 'Local and API AI',
    icon: 'bot',
    tabId: 'aiBenchmarks',
    groupId: 'guide',
    tone: 'cyan',
    routePath: '#/ai-runtime',
  },
  {
    label: 'REPORTS',
    detail: 'Daily weekly monthly',
    icon: 'grid',
    tabId: 'aiBenchmarks',
    groupId: 'guide',
    tone: 'purple',
    routePath: '#/report-settings',
  },
  {
    label: 'PRIVATE',
    detail: 'Data stays local',
    icon: 'shield',
    tabId: 'aiBenchmarks',
    groupId: 'guide',
    tone: 'gold',
    routePath: '#/privacy-design',
  },
  {
    label: 'BROWSER SETUP',
    detail: 'Managed and unmanaged',
    icon: 'shield',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'gold',
    routePath: '#/browser-settings',
  },
  {
    label: 'RULE SETUP',
    detail: 'Rules and policies',
    icon: 'grid',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'gold',
    routePath: '#/rule-management',
  },
  {
    label: 'SCHEDULES',
    detail: 'School sleep budgets',
    icon: 'calendar',
    tabId: 'tournaments',
    groupId: 'manage',
    tone: 'purple',
    routePath: '#/schedules',
  },
  {
    label: 'APPROVALS',
    detail: 'Ask parent flow',
    icon: 'gift',
    tabId: 'tournaments',
    groupId: 'manage',
    tone: 'cyan',
    routePath: '#/approvals',
  },
  {
    label: 'ENFORCE',
    detail: 'Dry run then apply',
    icon: 'swords',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'red',
    routePath: '#/enforcement',
  },
  {
    label: 'REPORT SETUP',
    detail: 'Daily weekly monthly',
    icon: 'grid',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'purple',
    routePath: '#/report-settings',
  },
  {
    label: 'DEVICES',
    detail: 'Child device pairing',
    icon: 'gamepad',
    tabId: 'tournaments',
    groupId: 'manage',
    tone: 'cyan',
    routePath: '#/devices',
  },
  {
    label: 'SCREEN',
    detail: 'Local summaries',
    icon: 'activity',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'cyan',
    routePath: '#/screen-analysis',
  },
  {
    label: 'APPS/GAMES',
    detail: 'Known app sessions',
    icon: 'gamepad',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'purple',
    routePath: '#/app-game-sessions',
  },
  {
    label: 'NETWORK',
    detail: 'Domains and flows',
    icon: 'activity',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'cyan',
    routePath: '#/network-activity',
  },
  {
    label: 'ALERTS',
    detail: 'Parent notifications',
    icon: 'gift',
    tabId: 'tournaments',
    groupId: 'manage',
    tone: 'red',
    routePath: '#/notifications',
  },
  {
    label: 'DRIVES',
    detail: 'Connect your drives',
    icon: 'trophy',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'gold',
    routePath: '#/drive-connections',
  },
  {
    label: 'AI SETUP',
    detail: 'Models and API providers',
    icon: 'bot',
    tabId: 'aiBenchmarks',
    groupId: 'manage',
    tone: 'purple',
    routePath: '#/ai-runtime',
  },
  {
    label: 'API KEYS',
    detail: 'External AI providers',
    icon: 'bot',
    tabId: 'aiBenchmarks',
    groupId: 'manage',
    tone: 'purple',
    routePath: '#/api-providers',
  },
  {
    label: 'MEMORY SETUP',
    detail: 'Review revoke export',
    icon: 'circle',
    tabId: 'aiBenchmarks',
    groupId: 'manage',
    tone: 'purple',
    routePath: '#/memory-settings',
  },
  {
    label: 'REMOTE',
    detail: 'Away from home',
    icon: 'users',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'cyan',
    routePath: '#/remote-access',
  },
  {
    label: 'SUBSCRIPTION',
    detail: 'Plans and device limits',
    icon: 'coins',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'gold',
    routePath: '#/subscription',
  },
  {
    label: 'PLATFORMS',
    detail: 'Desktop mobile install',
    icon: 'home',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'cyan',
    routePath: '#/platforms-install',
  },
  {
    label: 'SUPPORT',
    detail: 'Diagnostics and help',
    icon: 'users',
    tabId: 'perGame',
    groupId: 'manage',
    tone: 'cyan',
    routePath: '#/diagnostics',
  },
  {
    label: 'SETTINGS',
    detail: 'Family defaults',
    icon: 'crown',
    tabId: 'tournaments',
    groupId: 'manage',
    tone: 'cyan',
    routePath: '#/settings-rules',
  },
] as const;
