import type { ParentPortalContent, ParentPortalRow } from './parent-portal-data';

export const PARENT_PORTAL_MANAGE_ROWS: ParentPortalRow[] = [
  {
    label: 'Browser Setup',
    order: 11,
    signalScore: 2320,
    readyCount: 4,
    gapCount: 0,
    primaryArea: 'BROWSER SETUP',
    trend: 'Per device',
    tone: 'gold',
  },
  {
    label: 'Rules',
    order: 12,
    signalScore: 2300,
    readyCount: 4,
    gapCount: 0,
    primaryArea: 'RULES',
    trend: 'Draft',
    tone: 'gold',
  },
  {
    label: 'Schedules And Budgets',
    order: 13,
    signalScore: 2280,
    readyCount: 4,
    gapCount: 0,
    primaryArea: 'SCHEDULES',
    trend: 'Planned',
    tone: 'purple',
  },
  {
    label: 'Approvals',
    order: 14,
    signalScore: 2240,
    readyCount: 4,
    gapCount: 0,
    primaryArea: 'APPROVALS',
    trend: 'Queued',
    tone: 'cyan',
  },
  {
    label: 'Enforcement Readiness',
    order: 15,
    signalScore: 2200,
    readyCount: 3,
    gapCount: 0,
    primaryArea: 'ENFORCEMENT',
    trend: 'Gated',
    tone: 'red',
  },
  {
    label: 'Reports',
    order: 16,
    signalScore: 2160,
    readyCount: 3,
    gapCount: 0,
    primaryArea: 'REPORTS',
    trend: 'Local',
    tone: 'purple',
  },
  {
    label: 'API Providers',
    order: 17,
    signalScore: 2120,
    readyCount: 3,
    gapCount: 0,
    primaryArea: 'External AI',
    trend: 'Opt in',
    tone: 'purple',
  },
  {
    label: 'Memory Settings',
    order: 18,
    signalScore: 2080,
    readyCount: 3,
    gapCount: 0,
    primaryArea: 'MEMORY SETUP',
    trend: 'Local',
    tone: 'purple',
  },
  {
    label: 'Network Activity',
    order: 19,
    signalScore: 2040,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'NETWORK ACTIVITY',
    trend: 'Metadata',
    tone: 'cyan',
  },
  {
    label: 'Remote Access',
    order: 20,
    signalScore: 2000,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'REMOTE ACCESS',
    trend: 'Future',
    tone: 'cyan',
  },
  {
    label: 'Subscription',
    order: 21,
    signalScore: 1960,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'SUBSCRIPTION',
    trend: 'Planned',
    tone: 'gold',
  },
  {
    label: 'Platforms',
    order: 22,
    signalScore: 1920,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'PLATFORMS',
    trend: 'Roadmap',
    tone: 'cyan',
  },
  {
    label: 'Drive Exports',
    order: 23,
    signalScore: 1880,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'Drive Exports',
    trend: 'Opt in',
    tone: 'gold',
  },
  {
    label: 'Support And Diagnostics',
    order: 24,
    signalScore: 1840,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'SUPPORT AND API STATUS',
    trend: 'Parent owned',
    tone: 'cyan',
  },
  {
    label: 'Device Pairing',
    order: 25,
    signalScore: 1800,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'Device Pairing',
    trend: 'Trusted',
    tone: 'cyan',
  },
  {
    label: 'Notifications',
    order: 26,
    signalScore: 1760,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'Notifications',
    trend: 'Parent only',
    tone: 'red',
  },
  {
    label: 'Family Settings',
    order: 27,
    signalScore: 1720,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'Family Settings',
    trend: 'Defaults',
    tone: 'cyan',
  },
  {
    label: 'LAN Pairing',
    order: 28,
    signalScore: 1700,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'LAN PAIRING',
    trend: 'Explicit',
    tone: 'cyan',
  },
  {
    label: 'Capability Status',
    order: 29,
    signalScore: 1680,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'CAPABILITY STATUS',
    trend: 'Per device',
    tone: 'cyan',
  },
  {
    label: 'Notification Channels',
    order: 30,
    signalScore: 1660,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'NOTIFICATION CHANNELS',
    trend: 'Minimal',
    tone: 'red',
  },
  {
    label: 'Export Retention',
    order: 31,
    signalScore: 1640,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'EXPORT DELETE RETENTION',
    trend: 'Parent owned',
    tone: 'gold',
  },
  {
    label: 'Report Compiler',
    order: 32,
    signalScore: 1620,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'REPORT COMPILER',
    trend: 'Stateless',
    tone: 'purple',
  },
  {
    label: 'Audit History',
    order: 33,
    signalScore: 1600,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'AUDIT HISTORY',
    trend: 'Required',
    tone: 'purple',
  },
  {
    label: 'Entitlements',
    order: 34,
    signalScore: 1580,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'ENTITLEMENTS',
    trend: 'Grace',
    tone: 'gold',
  },
  {
    label: 'Install Updates',
    order: 35,
    signalScore: 1560,
    readyCount: 2,
    gapCount: 0,
    primaryArea: 'INSTALL UPDATES',
    trend: 'Rollback',
    tone: 'cyan',
  },
];

export const PARENT_PORTAL_MANAGE_QUICK_CONTROLS: ParentPortalContent['quickControls'] = [
  {
    id: 'browser-settings',
    name: 'BROWSER SETUP',
    detail: 'Managed, unmanaged, unsupported',
    icon: 'browser',
    tone: 'gold',
    category: 'Browser',
    subcategory: 'Per-device browser choices',
    controlCode: 1,
    routePath: '#/browser-settings',
  },
  {
    id: 'rules-management',
    name: 'RULES',
    detail: 'House rules and policy preview',
    icon: 'rules',
    tone: 'gold',
    category: 'Policy',
    subcategory: 'Family and device rules',
    controlCode: 3,
    routePath: '#/rule-management',
  },
  {
    id: 'schedules-budgets',
    name: 'SCHEDULES',
    detail: 'School sleep homework windows',
    icon: 'schedule',
    tone: 'purple',
    category: 'Routine',
    subcategory: 'Time budgets',
    controlCode: 3,
    routePath: '#/schedules',
  },
  {
    id: 'approvals',
    name: 'APPROVALS',
    detail: 'Ask parent requests',
    icon: 'schedule',
    tone: 'cyan',
    category: 'Routine',
    subcategory: 'Approve deny explain',
    controlCode: 3,
    routePath: '#/approvals',
  },
  {
    id: 'enforcement-readiness',
    name: 'ENFORCEMENT',
    detail: 'Dry-run, timers, rollback',
    icon: 'enforcement',
    tone: 'red',
    category: 'Policy',
    subcategory: 'Adapter readiness',
    controlCode: 3,
    routePath: '#/enforcement',
  },
  {
    id: 'reports-settings',
    name: 'REPORTS',
    detail: 'Daily weekly monthly summaries',
    icon: 'report',
    tone: 'purple',
    category: 'Reports',
    subcategory: 'Report schedule and custody',
    controlCode: 4,
    routePath: '#/report-settings',
  },
  {
    id: 'screen-analysis',
    name: 'SCREEN ANALYSIS',
    detail: 'Local summary queue',
    icon: 'screen',
    tone: 'cyan',
    category: 'Activity',
    subcategory: 'Optional local summaries',
    controlCode: 4,
    routePath: '#/screen-analysis',
  },
  {
    id: 'app-game-sessions',
    name: 'APP AND GAME SESSIONS',
    detail: 'Known app time and focus',
    icon: 'activity',
    tone: 'purple',
    category: 'Activity',
    subcategory: 'Apps, games, focus time',
    controlCode: 4,
    routePath: '#/app-game-sessions',
  },
  {
    id: 'network-activity',
    name: 'NETWORK ACTIVITY',
    detail: 'Domains and flow metadata',
    icon: 'activity',
    tone: 'cyan',
    category: 'Activity',
    subcategory: 'Network metadata',
    controlCode: 4,
    routePath: '#/network-activity',
  },
  {
    id: 'memory-settings',
    name: 'MEMORY SETUP',
    detail: 'Review, revoke, export',
    icon: 'ai-memory-set',
    tone: 'purple',
    category: 'Memory',
    subcategory: 'Parent editable context',
    controlCode: 7,
    routePath: '#/memory-settings',
  },
  {
    id: 'ai-runtime',
    name: 'AI SETUP',
    detail: 'Local models and child device AI',
    icon: 'ai-setup',
    tone: 'purple',
    category: 'AI',
    subcategory: 'Per-device model runtime',
    controlCode: 7,
    routePath: '#/ai-runtime',
  },
  {
    id: 'api-providers',
    name: 'API KEYS',
    detail: 'External AI providers',
    icon: 'api',
    tone: 'purple',
    category: 'Parent Portal',
    subcategory: 'Provider keys and limits',
    controlCode: 8,
    routePath: '#/api-providers',
  },
  {
    id: 'remote-access',
    name: 'REMOTE ACCESS',
    detail: 'Relay, cache, or drive source',
    icon: 'remote',
    tone: 'cyan',
    category: 'Privacy',
    subcategory: 'Away from home',
    controlCode: 8,
    routePath: '#/remote-access',
  },
  {
    id: 'subscription-plans',
    name: 'SUBSCRIPTION',
    detail: 'Plan, trial, device limits',
    icon: 'account',
    tone: 'gold',
    category: 'Support',
    subcategory: 'Billing and entitlements',
    controlCode: 8,
    routePath: '#/subscription',
  },
  {
    id: 'platforms-install',
    name: 'PLATFORMS',
    detail: 'Desktop, mobile, install',
    icon: 'devices',
    tone: 'cyan',
    category: 'Support',
    subcategory: 'Packaging and support',
    controlCode: 8,
    routePath: '#/platforms-install',
  },
  {
    id: 'device-pairing',
    name: 'DEVICE',
    detail: 'Child device pairing',
    icon: 'devices',
    tone: 'cyan',
    category: 'Devices',
    subcategory: 'Selected child device',
    controlCode: 7,
    routePath: '#/devices',
  },
  {
    id: 'lan-pairing',
    name: 'LAN PAIRING',
    detail: 'Paired local devices only',
    icon: 'lan',
    tone: 'cyan',
    category: 'Devices',
    subcategory: 'Explicit LAN trust',
    controlCode: 7,
    routePath: '#/lan-pairing',
  },
  {
    id: 'capability-status',
    name: 'CAPABILITY STATUS',
    detail: 'Supported degraded unavailable',
    icon: 'policy',
    tone: 'cyan',
    category: 'Devices',
    subcategory: 'Per-device readiness',
    controlCode: 7,
    routePath: '#/capability-status',
  },
  {
    id: 'notifications',
    name: 'ALERTS',
    detail: 'Portal alerts and quiet hours',
    icon: 'alerts',
    tone: 'red',
    category: 'Parent Portal',
    subcategory: 'Parent alert policy',
    controlCode: 8,
    routePath: '#/notifications',
  },
  {
    id: 'notification-channels',
    name: 'NOTIFICATION CHANNELS',
    detail: 'Push email SMS WhatsApp',
    icon: 'alerts',
    tone: 'red',
    category: 'Alerts',
    subcategory: 'Delivery and quiet hours',
    controlCode: 8,
    routePath: '#/notification-channels',
  },
  {
    id: 'drive-exports',
    name: 'DRIVES',
    detail: 'Connect parent-owned storage',
    icon: 'drives',
    tone: 'gold',
    category: 'Data',
    subcategory: 'Drive connections',
    controlCode: 8,
    routePath: '#/drive-connections',
  },
  {
    id: 'export-retention',
    name: 'EXPORT DELETE RETENTION',
    detail: 'Data classes and custody',
    icon: 'export',
    tone: 'gold',
    category: 'Privacy',
    subcategory: 'Export sync delete',
    controlCode: 8,
    routePath: '#/export-retention',
  },
  {
    id: 'report-compiler',
    name: 'REPORT COMPILER',
    detail: 'Daily weekly monthly compile',
    icon: 'report',
    tone: 'purple',
    category: 'Reports',
    subcategory: 'Stateless report build',
    controlCode: 4,
    routePath: '#/report-compiler',
  },
  {
    id: 'audit-history',
    name: 'AUDIT HISTORY',
    detail: 'Rules approvals exports',
    icon: 'audit',
    tone: 'purple',
    category: 'Support',
    subcategory: 'Parent-visible audit',
    controlCode: 8,
    routePath: '#/audit-history',
  },
  {
    id: 'support-api-status',
    name: 'SUPPORT',
    detail: 'Diagnostics and support bundle',
    icon: 'portal',
    tone: 'cyan',
    category: 'Support',
    subcategory: 'Diagnostics and help',
    controlCode: 8,
    routePath: '#/diagnostics',
  },
  {
    id: 'entitlements',
    name: 'ENTITLEMENTS',
    detail: 'Plan gates and grace',
    icon: 'account',
    tone: 'gold',
    category: 'Support',
    subcategory: 'Paid feature state',
    controlCode: 8,
    routePath: '#/entitlements',
  },
  {
    id: 'install-updates',
    name: 'INSTALL UPDATES',
    detail: 'Install health rollback',
    icon: 'updates',
    tone: 'cyan',
    category: 'Support',
    subcategory: 'Installer lifecycle',
    controlCode: 8,
    routePath: '#/install-updates',
  },
  {
    id: 'family-settings',
    name: 'SETTINGS',
    detail: 'Family defaults',
    icon: 'account',
    tone: 'cyan',
    category: 'Parent Portal',
    subcategory: 'Family defaults',
    controlCode: 8,
    routePath: '#/settings-rules',
  },
];
