import { PortalRoute } from './portal-contract-adapter';
import type { ParentPortalContent } from './parent-portal-data';
import { PARENT_PORTAL_NAV_LABELS } from './parent-portal-nav';
import { portalRouteHashPath } from './routes';

export const PARENT_PORTAL_MANAGE_QUICK_CONTROLS: ParentPortalContent['quickControls'] = [
  {
    id: 'browser-settings',
    name: 'BROWSER SETUP',
    detail: 'Managed, unmanaged, unsupported',
    icon: 'browser',
    tone: 'gold',
    category: 'Browser',
    subcategory: 'Per-device browser choices',
    controlCode: 1,
    routePath: portalRouteHashPath(PortalRoute.BrowserSettings),
  },
  {
    id: 'policy-apps',
    name: 'APP POLICY',
    detail: 'App rules, budgets, approvals',
    icon: 'app',
    tone: 'gold',
    category: 'Policy',
    subcategory: 'Installed apps',
    controlCode: 3,
    routePath: portalRouteHashPath(PortalRoute.PolicyApps),
  },
  {
    id: 'policy-games',
    name: 'GAME POLICY',
    detail: 'Game limits and sessions',
    icon: 'games',
    tone: 'purple',
    category: 'Policy',
    subcategory: 'Games and entertainment',
    controlCode: 3,
    routePath: portalRouteHashPath(PortalRoute.PolicyGames),
  },
  {
    id: 'policy-tracking',
    name: 'TRACKING POLICY',
    detail: 'Device location rules',
    icon: 'devices',
    tone: 'cyan',
    category: 'Policy',
    subcategory: 'Device location',
    controlCode: 3,
    routePath: portalRouteHashPath(PortalRoute.PolicyTracking),
  },
  {
    id: 'policy-remote-screen',
    name: 'REMOTE SCREEN POLICY',
    detail: 'Live view backend not implemented yet',
    icon: 'remote',
    tone: 'purple',
    category: 'Policy',
    subcategory: 'Live screen view',
    controlCode: 3,
    routePath: portalRouteHashPath(PortalRoute.PolicyRemoteScreen),
  },
  {
    id: 'rules-management',
    name: 'RULES',
    detail: 'House rules and policy preview',
    icon: 'rules',
    tone: 'gold',
    category: 'Policy',
    subcategory: 'Family and device rules',
    controlCode: 3,
    routePath: portalRouteHashPath(PortalRoute.RuleManagement),
  },
  {
    id: 'schedules-budgets',
    name: 'SCHEDULES',
    detail: 'Manual-required schedule and budget state',
    icon: 'schedule',
    tone: 'purple',
    category: 'Routine',
    subcategory: 'Service-owned time budgets',
    controlCode: 3,
    routePath: portalRouteHashPath(PortalRoute.Schedules),
  },
  {
    id: 'approvals',
    name: 'APPROVALS',
    detail: 'Ask parent requests',
    icon: 'schedule',
    tone: 'cyan',
    category: 'Routine',
    subcategory: 'Approve deny explain',
    controlCode: 3,
    routePath: portalRouteHashPath(PortalRoute.Approvals),
  },
  {
    id: 'enforcement-readiness',
    name: 'ENFORCEMENT',
    detail: 'Dry-run, timers, rollback',
    icon: 'enforcement',
    tone: 'red',
    category: 'Policy',
    subcategory: 'Adapter readiness',
    controlCode: 3,
    routePath: portalRouteHashPath(PortalRoute.Enforcement),
  },
  {
    id: 'reports-settings',
    name: 'REPORTS',
    detail: 'Daily weekly monthly summaries',
    icon: 'report',
    tone: 'purple',
    category: 'Reports',
    subcategory: 'Report schedule and custody',
    controlCode: 4,
    routePath: portalRouteHashPath(PortalRoute.Activity),
  },
  {
    id: 'screen-analysis',
    name: 'SCREEN ANALYSIS',
    detail: 'Local summary queue',
    icon: 'screen',
    tone: 'cyan',
    category: 'Activity',
    subcategory: 'Optional local summaries',
    controlCode: 4,
    routePath: portalRouteHashPath(PortalRoute.ScreenAnalysis),
  },
  {
    id: 'app-game-sessions',
    name: 'APP AND GAME SESSIONS',
    detail: 'Known app time and focus',
    icon: 'app',
    tone: 'purple',
    category: 'Activity',
    subcategory: 'Apps, games, focus time',
    controlCode: 4,
    routePath: portalRouteHashPath(PortalRoute.AppGameSessions),
  },
  {
    id: 'network-activity',
    name: 'NETWORK ACTIVITY',
    detail: 'Domains and flow metadata',
    icon: 'activity',
    tone: 'cyan',
    category: 'Activity',
    subcategory: 'Network metadata',
    controlCode: 4,
    routePath: portalRouteHashPath(PortalRoute.NetworkActivity),
  },
  {
    id: 'memory-settings',
    name: 'MEMORY SETUP',
    detail: 'Review, revoke, export',
    icon: 'ai-memory-set',
    tone: 'purple',
    category: 'Memory',
    subcategory: 'Parent editable context',
    controlCode: 7,
    routePath: portalRouteHashPath(PortalRoute.MemorySettings),
  },
  {
    id: 'ai-runtime',
    name: 'AI SETUP',
    detail: 'Local models and child device AI',
    icon: 'ai-setup',
    tone: 'purple',
    category: 'AI',
    subcategory: 'Per-device model runtime',
    controlCode: 7,
    routePath: portalRouteHashPath(PortalRoute.AiRuntime),
  },
  {
    id: 'api-providers',
    name: 'API KEYS',
    detail: 'External AI providers',
    icon: 'api',
    tone: 'purple',
    category: 'Parent Portal',
    subcategory: 'Provider keys and limits',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.ApiProviders),
  },
  {
    id: 'remote-access',
    name: 'REMOTE ACCESS',
    detail: 'Relay, cache, or drive source',
    icon: 'remote',
    tone: 'cyan',
    category: 'Privacy',
    subcategory: 'Away from home',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.RemoteAccess),
  },
  {
    id: 'subscription-plans',
    name: 'SUBSCRIPTION',
    detail: 'Plan, trial, device limits',
    icon: 'account',
    tone: 'gold',
    category: 'Support',
    subcategory: 'Billing and entitlements',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.Subscription),
  },
  {
    id: 'platforms-install',
    name: 'PLATFORMS',
    detail: 'Desktop, mobile, install',
    icon: 'devices',
    tone: 'cyan',
    category: 'Support',
    subcategory: 'Packaging and support',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.PlatformsInstall),
  },
  {
    id: 'lan-pairing',
    name: 'LAN PAIRING',
    detail: 'Paired local devices only',
    icon: 'lan',
    tone: 'cyan',
    category: 'Devices',
    subcategory: 'Explicit LAN trust',
    controlCode: 7,
    routePath: portalRouteHashPath(PortalRoute.LanPairing),
  },
  {
    id: 'capability-status',
    name: 'CAPABILITY STATUS',
    detail: 'Supported degraded unavailable',
    icon: 'policy',
    tone: 'cyan',
    category: 'Devices',
    subcategory: 'Per-device readiness',
    controlCode: 7,
    routePath: portalRouteHashPath(PortalRoute.CapabilityStatus),
  },
  {
    id: 'notifications',
    name: 'ALERTS',
    detail: 'Portal alerts and quiet hours',
    icon: 'alerts',
    tone: 'red',
    category: 'Parent Portal',
    subcategory: 'Parent alert policy',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.Notifications),
  },
  {
    id: 'notification-channels',
    name: 'NOTIFICATION CHANNELS',
    detail: 'Push email SMS WhatsApp',
    icon: 'alerts',
    tone: 'red',
    category: 'Alerts',
    subcategory: 'Delivery and quiet hours',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.NotificationChannels),
  },
  {
    id: 'drive-exports',
    name: 'DRIVES',
    detail: 'Connect parent-owned storage',
    icon: 'drives',
    tone: 'gold',
    category: 'Data',
    subcategory: 'Drive connections',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.DriveConnections),
  },
  {
    id: 'export-retention',
    name: 'EXPORT DELETE RETENTION',
    detail: 'Data classes and custody',
    icon: 'export',
    tone: 'gold',
    category: 'Privacy',
    subcategory: 'Export sync delete',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.ExportRetention),
  },
  {
    id: 'report-compiler',
    name: 'REPORT COMPILER',
    detail: 'Daily weekly monthly compile',
    icon: 'report',
    tone: 'purple',
    category: 'Reports',
    subcategory: 'Stateless report build',
    controlCode: 4,
    routePath: portalRouteHashPath(PortalRoute.ReportCompiler),
  },
  {
    id: 'audit-history',
    name: 'AUDIT HISTORY',
    detail: 'Rules approvals exports',
    icon: 'audit',
    tone: 'purple',
    category: 'Support',
    subcategory: 'Parent-visible audit',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.AuditHistory),
  },
  {
    id: 'support-api-status',
    name: 'SUPPORT',
    detail: 'Contact support message',
    icon: 'portal',
    tone: 'cyan',
    category: 'Support',
    subcategory: 'Contact and help',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.Diagnostics),
  },
  {
    id: 'entitlements',
    name: 'ENTITLEMENTS',
    detail: 'Plan gates and grace',
    icon: 'account',
    tone: 'gold',
    category: 'Support',
    subcategory: 'Paid feature state',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.Entitlements),
  },
  {
    id: 'install-updates',
    name: 'INSTALL UPDATES',
    detail: 'Install health rollback',
    icon: 'updates',
    tone: 'cyan',
    category: 'Support',
    subcategory: 'Installer lifecycle',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.InstallUpdates),
  },
  {
    id: 'family-settings',
    name: 'SETTINGS',
    detail: 'Family defaults',
    icon: 'account',
    tone: 'cyan',
    category: 'Parent Portal',
    subcategory: 'Family defaults',
    controlCode: 8,
    routePath: portalRouteHashPath(PortalRoute.SettingsRules),
  },
  {
    id: 'dev-proof-panels',
    name: PARENT_PORTAL_NAV_LABELS.ProofPanels,
    detail: 'Tracking, network, and policy proof panels',
    icon: 'audit',
    tone: 'purple',
    category: 'Dev tools',
    subcategory: 'Route proof panels',
    controlCode: 9,
    routePath: portalRouteHashPath(PortalRoute.ProofPanels),
  },
  {
    id: 'dev-commands',
    name: PARENT_PORTAL_NAV_LABELS.Commands,
    detail: 'Send typed runtime commands',
    icon: 'portal',
    tone: 'cyan',
    category: 'Dev tools',
    subcategory: 'Command lane',
    controlCode: 9,
    routePath: portalRouteHashPath(PortalRoute.Commands),
  },
  {
    id: 'dev-events',
    name: PARENT_PORTAL_NAV_LABELS.Events,
    detail: 'Inspect runtime events',
    icon: 'activity',
    tone: 'purple',
    category: 'Dev tools',
    subcategory: 'Event stream',
    controlCode: 9,
    routePath: portalRouteHashPath(PortalRoute.Events),
  },
  {
    id: 'dev-logs',
    name: PARENT_PORTAL_NAV_LABELS.Logs,
    detail: 'Inspect service logs',
    icon: 'audit',
    tone: 'gold',
    category: 'Dev tools',
    subcategory: 'Runtime logs',
    controlCode: 9,
    routePath: portalRouteHashPath(PortalRoute.Logs),
  },
  {
    id: 'app-layout',
    name: PARENT_PORTAL_NAV_LABELS.AppLayout,
    detail: 'Tune app layout surfaces',
    icon: 'overview',
    tone: 'cyan',
    category: 'Dev tools',
    subcategory: 'Layout surface',
    controlCode: 9,
    routePath: portalRouteHashPath(PortalRoute.FrameTuner),
  },
];
