const PARENT_PORTAL_SERVICE_STATE = {
  Empty: '',
  RowSource: {
    Api: 'api',
  },
  Connection: {
    Connected: 'connected',
    Connecting: 'connecting',
    Error: 'error',
  },
  Label: {
    LocalAgent: 'Local agent',
    LanDiscovery: 'LAN discovery',
    DevicePairing: 'Device pairing',
    BrowserActivity: 'Browser activity',
    BrowserInventory: 'Browser inventory',
    ExactUrlCapability: 'Exact URL capability',
    ActiveTabProof: 'Active tab proof',
    UnmanagedFallback: 'Unmanaged fallback',
    ActivityReports: 'Activity reports',
    NetworkTracking: 'Network tracking',
    HouseholdSetup: 'Household setup',
    ManagedWeb: 'Managed web path',
    BrowserSetup: 'Browser setup',
    ActivityStore: 'Activity store',
    AppGameSessions: 'App and game sessions',
    AppPolicy: 'App policy',
    GamePolicy: 'Game policy',
    ScreenAnalysis: 'Screen analysis',
    NetworkActivity: 'Network activity',
    TrackingPolicy: 'Tracking policy',
    RemoteScreenPolicy: 'Remote screen policy',
    SchedulePlan: 'Schedule plan',
    ApprovalQueue: 'Approval queue',
    EnforcementReadiness: 'Enforcement readiness',
    ReportsSurface: 'Reports surface',
    AssistantEntry: 'Assistant entry',
    DataCustody: 'Data custody',
    Alerts: 'Alerts',
    NotificationChannels: 'Notification channels',
    RemoteAccess: 'Remote access',
    ExportRetention: 'Export retention',
    AuditHistory: 'Audit history',
    Support: 'Support',
    Subscription: 'Subscription',
    Entitlements: 'Entitlements',
    MemorySetup: 'Memory setup',
    ApiProviders: 'API providers',
  },
  Area: {
    Service: 'Service',
    Runtime: 'Runtime',
    Lan: 'LAN',
    CurrentDevice: 'Current device',
    Browser: 'Browser',
    BrowserInventory: 'BROWSER INVENTORY',
    ExactUrlCapability: 'BROWSER EXACT URL CAPABILITY',
    ActiveTabProof: 'BROWSER ACTIVE TAB PROOF',
    UnmanagedFallback: 'BROWSER UNMANAGED FALLBACK',
    Activity: 'Activity',
    Network: 'Network',
    FamilySettings: 'Family Settings',
    Settings: 'SETTINGS',
    ManagedWeb: 'Managed Web',
    BrowserSetup: 'BROWSER SETUP',
    ActivityStore: 'Activity Store',
    AppGameSessions: 'APP AND GAME SESSIONS',
    AppPolicy: 'APP POLICY',
    GamePolicy: 'GAME POLICY',
    ScreenAnalysis: 'SCREEN ANALYSIS',
    NetworkActivity: 'NETWORK ACTIVITY',
    TrackingPolicy: 'TRACKING POLICY',
    RemoteScreenPolicy: 'REMOTE SCREEN POLICY',
    Schedules: 'SCHEDULES',
    Approvals: 'APPROVALS',
    Enforcement: 'ENFORCEMENT',
    Reports: 'REPORTS',
    AiSetup: 'AI SETUP',
    ApiProviders: 'API Providers',
    ApiKeys: 'API KEYS',
    MemorySetup: 'MEMORY SETUP',
    DriveExports: 'Drive Exports',
    Drives: 'DRIVES',
    Alerts: 'ALERTS',
    NotificationChannels: 'NOTIFICATION CHANNELS',
    RemoteAccess: 'REMOTE ACCESS',
    ExportRetention: 'EXPORT DELETE RETENTION',
    AuditHistory: 'AUDIT HISTORY',
    Support: 'SUPPORT',
    Subscription: 'SUBSCRIPTION',
    Entitlements: 'ENTITLEMENTS',
    Device: 'DEVICE',
    LanPairing: 'LAN PAIRING',
    CapabilityStatus: 'CAPABILITY STATUS',
  },
  Trend: {
    NotReported: 'not-reported',
    Offline: 'offline',
    Reported: 'reported',
    Unavailable: 'unavailable',
    NotClaimed: 'not-claimed',
    ManualRequired: 'manual-required',
    PermissionRequired: 'permission-required',
    ScaffoldOnly: 'scaffold-only',
    BackendNotConnected: 'backend-not-connected',
  },
  Field: {
    LanScanSummary: 'scanSummary',
    ScannedDeviceCount: 'scannedDeviceCount',
  },
} as const;

const PORTAL_HOST_BRIDGE_RUNTIME = {
  AbortErrorName: 'AbortError',
  UnavailableState: 'unavailable',
  TransportUnavailableReason: 'transport-unavailable',
  DirectEnforcementCommandBoundaryErrorText:
    'Portal cannot dispatch enforcement mutation commands directly; use the enforcement authority boundary.',
} as const;

export { PARENT_PORTAL_SERVICE_STATE, PORTAL_HOST_BRIDGE_RUNTIME };
export default PARENT_PORTAL_SERVICE_STATE;
