import type { ParentPortalIconName, ParentPortalTabId, ParentPortalTone } from './parent-portal-data';
import { PortalRoute } from './portal-contract-adapter';
import {
  portalRouteHashPath,
  portalRouteHashPathWithQuery,
  type PortalRouteHashPath,
  type PortalRouteHashQueryPath,
} from './routes';

export type ParentPortalNavGroupId = 'quickGlance' | 'guide' | 'manage' | 'devTools';

export const PARENT_PORTAL_NAV_LABELS = {
  QuickGlance: 'QUICK GLANCE',
  Guide: 'GUIDE',
  Manage: 'MANAGE',
  DevTools: 'DEV TOOLS',
  Policies: 'POLICY',
  Activity: 'ACTIVITY',
  Devices: 'DEVICES',
  Portal: 'PORTAL',
  DataPrivacy: 'DATA',
  AiMemory: 'AI',
  Account: 'ACCOUNT',
  StartHere: 'START HERE',
  Overview: 'OVERVIEW',
  Web: 'WEB',
  RulesGuide: 'RULES',
  MemoryGuide: 'MEMORY',
  Ai: 'AI',
  ReportsGuide: 'REPORTS',
  Private: 'PRIVATE',
  Browser: 'BROWSER',
  Apps: 'APPS',
  Games: 'GAMES',
  RuleSet: 'RULES',
  Schedules: 'SCHEDULES',
  Approvals: 'APPROVALS',
  Enforce: 'ENFORCE',
  ReportSet: 'REPORTS',
  Lan: 'LAN',
  Capability: 'CAPABILITY',
  Screen: 'SCREEN',
  RemoteScreen: 'REMOTE SCREEN',
  AppsGames: 'APP USE',
  Network: 'NETWORK',
  Tracking: 'TRACKING',
  Alerts: 'ALERTS',
  Channels: 'CHANNELS',
  Drives: 'DRIVES',
  Export: 'EXPORT',
  AiSetup: 'AI SETUP',
  ApiKeys: 'API KEYS',
  MemorySet: 'MEMORY SET',
  Remote: 'REMOTE',
  Builder: 'BUILDER',
  Audit: 'AUDIT',
  Plan: 'PLAN',
  Access: 'ACCESS',
  Platforms: 'PLATFORMS',
  Updates: 'UPDATES',
  Support: 'SUPPORT',
  Diagnostics: 'DIAGNOSTICS',
  ProofPanels: 'PROOF PANELS',
  Settings: 'SETTINGS',
  Commands: 'COMMANDS',
  Events: 'EVENTS',
  Logs: 'LOGS',
  AppLayout: 'APP LAYOUT',
  Background: 'BG',
} as const;

export type ParentPortalHashRoutePath = PortalRouteHashPath | PortalRouteHashQueryPath;
export type ParentPortalNavLabel = (typeof PARENT_PORTAL_NAV_LABELS)[keyof typeof PARENT_PORTAL_NAV_LABELS];
export type ParentPortalNavSectionLabel =
  | typeof PARENT_PORTAL_NAV_LABELS.Portal
  | typeof PARENT_PORTAL_NAV_LABELS.Devices
  | typeof PARENT_PORTAL_NAV_LABELS.Activity
  | typeof PARENT_PORTAL_NAV_LABELS.Policies
  | typeof PARENT_PORTAL_NAV_LABELS.DataPrivacy
  | typeof PARENT_PORTAL_NAV_LABELS.AiMemory
  | typeof PARENT_PORTAL_NAV_LABELS.Account;

export type ParentPortalNavGroup = {
  readonly id: ParentPortalNavGroupId;
  readonly label: ParentPortalNavLabel;
  readonly detail: string;
};

export type ParentPortalNavItem = {
  readonly label: ParentPortalNavLabel;
  readonly detail: string;
  readonly icon: ParentPortalIconName;
  readonly tabId: ParentPortalTabId;
  readonly groupId: ParentPortalNavGroupId;
  readonly sectionLabel?: ParentPortalNavSectionLabel;
  readonly tone?: ParentPortalTone;
  readonly routePath?: ParentPortalHashRoutePath;
};

export const PARENT_PORTAL_NAV_GROUPS: readonly ParentPortalNavGroup[] = [
  { id: 'quickGlance', label: PARENT_PORTAL_NAV_LABELS.QuickGlance, detail: 'Current child-device state' },
  { id: 'guide', label: PARENT_PORTAL_NAV_LABELS.Guide, detail: 'Policy, privacy, and local AI' },
  {
    id: 'manage',
    label: PARENT_PORTAL_NAV_LABELS.Manage,
    detail: 'Portal, device, activity, policy, data, AI, account',
  },
  {
    id: 'devTools',
    label: PARENT_PORTAL_NAV_LABELS.DevTools,
    detail: 'Diagnostics, proof panels, commands, events, logs, app layout, background',
  },
] as const;

export const PARENT_PORTAL_NAV_ITEMS: readonly ParentPortalNavItem[] = [
  {
    label: PARENT_PORTAL_NAV_LABELS.StartHere,
    detail: 'Setup and controls map',
    icon: 'start',
    tabId: 'overall',
    groupId: 'guide',
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.Start),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Overview,
    detail: 'Recent child-device state',
    icon: 'overview',
    tabId: 'overall',
    groupId: 'quickGlance',
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.Overview),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Web,
    detail: 'Supported and unsupported',
    icon: 'web',
    tabId: 'controls',
    groupId: 'quickGlance',
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.Browser),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.RulesGuide,
    detail: 'Allow, ask, explain, block',
    icon: 'rules',
    tabId: 'controls',
    groupId: 'guide',
    tone: 'gold',
    routePath: portalRouteHashPath(PortalRoute.Policy),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.MemoryGuide,
    detail: 'Cited local knowledge',
    icon: 'ai-memory',
    tabId: 'aiStatus',
    groupId: 'guide',
    tone: 'purple',
    routePath: portalRouteHashPath(PortalRoute.Memory),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Ai,
    detail: 'Local and API AI',
    icon: 'ai-setup',
    tabId: 'aiStatus',
    groupId: 'guide',
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.AiGuide),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.ReportsGuide,
    detail: 'Daily weekly monthly',
    icon: 'report',
    tabId: 'aiStatus',
    groupId: 'guide',
    tone: 'purple',
    routePath: portalRouteHashPath(PortalRoute.ReportsGuide),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Private,
    detail: 'Data stays local',
    icon: 'privacy',
    tabId: 'aiStatus',
    groupId: 'guide',
    tone: 'gold',
    routePath: portalRouteHashPath(PortalRoute.PrivacyDesign),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Portal,
    detail: 'Portal settings alerts channels',
    icon: 'portal',
    tabId: 'routines',
    groupId: 'manage',
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.SettingsRules),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Devices,
    detail: 'LAN discovery and device management',
    icon: 'lan',
    tabId: 'routines',
    groupId: 'manage',
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.Devices),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Activity,
    detail: 'Reports and activity management',
    icon: 'activity',
    tabId: 'controls',
    groupId: 'manage',
    tone: 'purple',
    routePath: portalRouteHashPath(PortalRoute.Activity),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Browser,
    detail: 'Managed and unmanaged',
    icon: 'browser',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'gold',
    routePath: portalRouteHashPath(PortalRoute.BrowserSettings),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.RuleSet,
    detail: 'Family and device rules',
    icon: 'rules',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'gold',
    routePath: portalRouteHashPath(PortalRoute.RuleManagement),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Schedules,
    detail: 'Schedules and time budgets',
    icon: 'schedule',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'purple',
    routePath: portalRouteHashPath(PortalRoute.Schedules),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Approvals,
    detail: 'Ask-parent requests and overrides',
    icon: 'alerts',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.Approvals),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Enforce,
    detail: 'Enforcement readiness and rollback',
    icon: 'enforcement',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'red',
    routePath: portalRouteHashPath(PortalRoute.Enforcement),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Apps,
    detail: 'App rules and budgets',
    icon: 'app',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'gold',
    routePath: portalRouteHashPath(PortalRoute.PolicyApps),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Games,
    detail: 'Game limits and sessions',
    icon: 'games',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'purple',
    routePath: portalRouteHashPath(PortalRoute.PolicyGames),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Screen,
    detail: 'Screen capture policy',
    icon: 'screen',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.PolicyScreen),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Network,
    detail: 'Network metadata policy',
    icon: 'web',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.PolicyNetwork),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Tracking,
    detail: 'Device location policy',
    icon: 'devices',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.PolicyTracking),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.RemoteScreen,
    detail: 'Live screen policy',
    icon: 'remote',
    tabId: 'controls',
    groupId: 'manage',
    sectionLabel: PARENT_PORTAL_NAV_LABELS.Policies,
    tone: 'purple',
    routePath: portalRouteHashPath(PortalRoute.PolicyRemoteScreen),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.DataPrivacy,
    detail: 'Storage export retention audit',
    icon: 'drives',
    tabId: 'controls',
    groupId: 'manage',
    tone: 'gold',
    routePath: portalRouteHashPath(PortalRoute.DriveConnections),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.AiMemory,
    detail: 'Models providers memory',
    icon: 'ai-setup',
    tabId: 'aiStatus',
    groupId: 'manage',
    tone: 'purple',
    routePath: portalRouteHashPath(PortalRoute.AiRuntime),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Account,
    detail: 'Plan access support',
    icon: 'account',
    tabId: 'controls',
    groupId: 'manage',
    tone: 'gold',
    routePath: portalRouteHashPath(PortalRoute.Subscription),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Diagnostics,
    detail: 'Copy redacted support diagnostics',
    icon: 'audit',
    tabId: 'support',
    groupId: 'devTools',
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.Diagnostics),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.ProofPanels,
    detail: 'Inspect tracking, network, and policy proof panels',
    icon: 'audit',
    tabId: 'support',
    groupId: 'devTools',
    tone: 'purple',
    routePath: portalRouteHashPath(PortalRoute.ProofPanels),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Commands,
    detail: 'Send real service commands',
    icon: 'portal',
    tabId: 'support',
    groupId: 'devTools',
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.Commands),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Events,
    detail: 'Inspect agent event stream',
    icon: 'audit',
    tabId: 'support',
    groupId: 'devTools',
    tone: 'purple',
    routePath: portalRouteHashPath(PortalRoute.Events),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Logs,
    detail: 'Inspect service logs',
    icon: 'audit',
    tabId: 'support',
    groupId: 'devTools',
    tone: 'gold',
    routePath: portalRouteHashPath(PortalRoute.Logs),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.AppLayout,
    detail: 'Tune portal layout',
    icon: 'manage',
    tabId: 'support',
    groupId: 'devTools',
    tone: 'cyan',
    routePath: portalRouteHashPath(PortalRoute.FrameTuner),
  },
  {
    label: PARENT_PORTAL_NAV_LABELS.Background,
    detail: 'Tune SVG background',
    icon: 'overview',
    tabId: 'support',
    groupId: 'devTools',
    tone: 'cyan',
    routePath: portalRouteHashPathWithQuery(PortalRoute.FrameTuner, 'bg-only=1'),
  },
] as const;
