import {
  PARENT_ASSISTANT_PORTAL_NEW_CHAT_ACTION as PARENT_ASSISTANT_PORTAL_NEW_CHAT_ACTION_IMPL,
  PARENT_ASSISTANT_PORTAL_QUICK_ACTIONS as PARENT_ASSISTANT_PORTAL_QUICK_ACTIONS_IMPL,
  ParentAssistantPortalQuickActionId as ParentAssistantPortalQuickActionIdImpl,
} from './parent-assistant-chat-impl';
import type {
  ParentAssistantPortalChoice as ParentAssistantPortalChoiceImpl,
  ParentAssistantPortalQuickAction as ParentAssistantPortalQuickActionImpl,
  ParentAssistantPortalQuickActionId as ParentAssistantPortalQuickActionIdTypeImpl,
} from './parent-assistant-chat-impl';

export type ParentAssistantPortalChoice = ParentAssistantPortalChoiceImpl;
export type ParentAssistantPortalQuickAction = ParentAssistantPortalQuickActionImpl;
export type ParentAssistantPortalQuickActionId = ParentAssistantPortalQuickActionIdTypeImpl;
export const ParentAssistantPortalQuickActionId = ParentAssistantPortalQuickActionIdImpl;
export const PARENT_ASSISTANT_PORTAL_QUICK_ACTIONS = PARENT_ASSISTANT_PORTAL_QUICK_ACTIONS_IMPL;
export const PARENT_ASSISTANT_PORTAL_NEW_CHAT_ACTION = PARENT_ASSISTANT_PORTAL_NEW_CHAT_ACTION_IMPL;
