import type { ParentLeaderboardCopyContent, ParentLeaderboardCopyRow } from './parent-leaderboard-copy-data';

export const PARENT_LEADERBOARD_COPY_MANAGE_ROWS: ParentLeaderboardCopyRow[] = [
  {
    user_id: 'Browser Setup',
    rank: 11,
    score: 2320,
    wins: 4,
    losses: 0,
    bestGame: 'BROWSER SETUP',
    trend: 'Per device',
    tone: 'gold',
  },
  {
    user_id: 'Rule Setup',
    rank: 12,
    score: 2300,
    wins: 4,
    losses: 0,
    bestGame: 'RULE SETUP',
    trend: 'Draft',
    tone: 'gold',
  },
  {
    user_id: 'Schedules And Budgets',
    rank: 13,
    score: 2280,
    wins: 4,
    losses: 0,
    bestGame: 'SCHEDULES',
    trend: 'Planned',
    tone: 'purple',
  },
  {
    user_id: 'Approvals',
    rank: 14,
    score: 2240,
    wins: 4,
    losses: 0,
    bestGame: 'APPROVALS',
    trend: 'Queued',
    tone: 'cyan',
  },
  {
    user_id: 'Enforcement Readiness',
    rank: 15,
    score: 2200,
    wins: 3,
    losses: 0,
    bestGame: 'ENFORCEMENT',
    trend: 'Gated',
    tone: 'red',
  },
  {
    user_id: 'Reports',
    rank: 16,
    score: 2160,
    wins: 3,
    losses: 0,
    bestGame: 'REPORT SETUP',
    trend: 'Local',
    tone: 'purple',
  },
  {
    user_id: 'API Providers',
    rank: 17,
    score: 2120,
    wins: 3,
    losses: 0,
    bestGame: 'External AI',
    trend: 'Opt in',
    tone: 'purple',
  },
  {
    user_id: 'Memory Settings',
    rank: 18,
    score: 2080,
    wins: 3,
    losses: 0,
    bestGame: 'MEMORY SETUP',
    trend: 'Local',
    tone: 'purple',
  },
  {
    user_id: 'Network Activity',
    rank: 19,
    score: 2040,
    wins: 2,
    losses: 0,
    bestGame: 'NETWORK ACTIVITY',
    trend: 'Metadata',
    tone: 'cyan',
  },
  {
    user_id: 'Remote Access',
    rank: 20,
    score: 2000,
    wins: 2,
    losses: 0,
    bestGame: 'REMOTE ACCESS',
    trend: 'Future',
    tone: 'cyan',
  },
  {
    user_id: 'Subscription',
    rank: 21,
    score: 1960,
    wins: 2,
    losses: 0,
    bestGame: 'SUBSCRIPTION',
    trend: 'Planned',
    tone: 'gold',
  },
  {
    user_id: 'Platforms',
    rank: 22,
    score: 1920,
    wins: 2,
    losses: 0,
    bestGame: 'PLATFORMS',
    trend: 'Roadmap',
    tone: 'cyan',
  },
  {
    user_id: 'Drive Exports',
    rank: 23,
    score: 1880,
    wins: 2,
    losses: 0,
    bestGame: 'Drive Exports',
    trend: 'Opt in',
    tone: 'gold',
  },
  {
    user_id: 'Support And Diagnostics',
    rank: 24,
    score: 1840,
    wins: 2,
    losses: 0,
    bestGame: 'SUPPORT AND API STATUS',
    trend: 'Parent owned',
    tone: 'cyan',
  },
  {
    user_id: 'Device Pairing',
    rank: 25,
    score: 1800,
    wins: 2,
    losses: 0,
    bestGame: 'Device Pairing',
    trend: 'Trusted',
    tone: 'cyan',
  },
  {
    user_id: 'Notifications',
    rank: 26,
    score: 1760,
    wins: 2,
    losses: 0,
    bestGame: 'Notifications',
    trend: 'Parent only',
    tone: 'red',
  },
  {
    user_id: 'Family Settings',
    rank: 27,
    score: 1720,
    wins: 2,
    losses: 0,
    bestGame: 'Family Settings',
    trend: 'Defaults',
    tone: 'cyan',
  },
];

export const PARENT_LEADERBOARD_COPY_MANAGE_QUICK_GAMES: ParentLeaderboardCopyContent['quickGames'] = [
  {
    id: 'browser-settings',
    name: 'BROWSER SETUP',
    detail: 'Managed, unmanaged, unsupported',
    icon: 'shield',
    tone: 'gold',
    category: 'Browser',
    subcategory: 'Per-device browser choices',
    gameType: 1,
    routePath: '#/browser-settings',
  },
  {
    id: 'rules-management',
    name: 'RULE SETUP',
    detail: 'House rules and policy preview',
    icon: 'grid',
    tone: 'gold',
    category: 'Policy',
    subcategory: 'Family and device rules',
    gameType: 3,
    routePath: '#/rule-management',
  },
  {
    id: 'schedules-budgets',
    name: 'SCHEDULES',
    detail: 'School sleep homework windows',
    icon: 'calendar',
    tone: 'purple',
    category: 'Routine',
    subcategory: 'Time budgets',
    gameType: 3,
    routePath: '#/schedules',
  },
  {
    id: 'approvals',
    name: 'APPROVALS',
    detail: 'Ask parent requests',
    icon: 'gift',
    tone: 'cyan',
    category: 'Routine',
    subcategory: 'Approve deny explain',
    gameType: 3,
    routePath: '#/approvals',
  },
  {
    id: 'enforcement-readiness',
    name: 'ENFORCEMENT',
    detail: 'Dry-run, timers, rollback',
    icon: 'swords',
    tone: 'red',
    category: 'Policy',
    subcategory: 'Adapter readiness',
    gameType: 3,
    routePath: '#/enforcement',
  },
  {
    id: 'reports-settings',
    name: 'REPORT SETUP',
    detail: 'Daily weekly monthly summaries',
    icon: 'grid',
    tone: 'purple',
    category: 'Reports',
    subcategory: 'Report schedule and custody',
    gameType: 4,
    routePath: '#/report-settings',
  },
  {
    id: 'screen-analysis',
    name: 'SCREEN ANALYSIS',
    detail: 'Local summary queue',
    icon: 'activity',
    tone: 'cyan',
    category: 'Activity',
    subcategory: 'Optional local summaries',
    gameType: 4,
    routePath: '#/screen-analysis',
  },
  {
    id: 'app-game-sessions',
    name: 'APP AND GAME SESSIONS',
    detail: 'Known app time and focus',
    icon: 'gamepad',
    tone: 'purple',
    category: 'Activity',
    subcategory: 'Apps, games, focus time',
    gameType: 4,
    routePath: '#/app-game-sessions',
  },
  {
    id: 'network-activity',
    name: 'NETWORK ACTIVITY',
    detail: 'Domains and flow metadata',
    icon: 'activity',
    tone: 'cyan',
    category: 'Activity',
    subcategory: 'Network metadata',
    gameType: 4,
    routePath: '#/network-activity',
  },
  {
    id: 'memory-settings',
    name: 'MEMORY SETUP',
    detail: 'Review, revoke, export',
    icon: 'circle',
    tone: 'purple',
    category: 'Memory',
    subcategory: 'Parent editable context',
    gameType: 7,
    routePath: '#/memory-settings',
  },
  {
    id: 'remote-access',
    name: 'REMOTE ACCESS',
    detail: 'Relay, cache, or drive source',
    icon: 'users',
    tone: 'cyan',
    category: 'Privacy',
    subcategory: 'Away from home',
    gameType: 8,
    routePath: '#/remote-access',
  },
  {
    id: 'subscription-plans',
    name: 'SUBSCRIPTION',
    detail: 'Plan, trial, device limits',
    icon: 'coins',
    tone: 'gold',
    category: 'Support',
    subcategory: 'Billing and entitlements',
    gameType: 8,
    routePath: '#/subscription',
  },
  {
    id: 'platforms-install',
    name: 'PLATFORMS',
    detail: 'Desktop, mobile, install',
    icon: 'home',
    tone: 'cyan',
    category: 'Support',
    subcategory: 'Packaging and support',
    gameType: 8,
    routePath: '#/platforms-install',
  },
];
