import {
  trackingChildCheckInProof as trackingChildCheckInProofImpl,
  trackingChildRuntimeUiProof as trackingChildRuntimeUiProofImpl,
  type TrackingChildCheckInProof as TrackingChildCheckInProofImpl,
  type TrackingChildRuntimeUiProof as TrackingChildRuntimeUiProofImpl,
} from './tracking-child-check-in-proof';
import {
  TrackingMissingDeviceHostedUiDetails as TrackingMissingDeviceHostedUiDetailsImpl,
  trackingMissingDeviceHostedUiProof as trackingMissingDeviceHostedUiProofImpl,
  type TrackingMissingDeviceHostedUiProof as TrackingMissingDeviceHostedUiProofImpl,
  type TrackingMissingDeviceHostedUiRow as TrackingMissingDeviceHostedUiRowImpl,
} from './tracking-missing-device-hosted-ui-proof';
import {
  TrackingNotificationParentSurfaceHostedUiDetails as TrackingNotificationParentSurfaceHostedUiDetailsImpl,
  trackingNotificationParentSurfaceHostedUiProof as trackingNotificationParentSurfaceHostedUiProofImpl,
  type TrackingNotificationParentSurfaceHostedUiProof as TrackingNotificationParentSurfaceHostedUiProofImpl,
  type TrackingNotificationParentSurfaceHostedUiRow as TrackingNotificationParentSurfaceHostedUiRowImpl,
} from './tracking-notification-parent-surface-hosted-ui-proof';
import {
  TrackingParentActionReadinessHostedUiDetails as TrackingParentActionReadinessHostedUiDetailsImpl,
  trackingParentActionReadinessHostedUiProof as trackingParentActionReadinessHostedUiProofImpl,
  type TrackingParentActionReadinessHostedUiProof as TrackingParentActionReadinessHostedUiProofImpl,
  type TrackingParentActionReadinessHostedUiRow as TrackingParentActionReadinessHostedUiRowImpl,
} from './tracking-parent-action-readiness-hosted-ui-proof';
import {
  trackingReportExportHostedUiProof as trackingReportExportHostedUiProofImpl,
  type TrackingReportExportHostedUiProof as TrackingReportExportHostedUiProofImpl,
  type TrackingReportExportHostedUiRow as TrackingReportExportHostedUiRowImpl,
} from './tracking-report-export-hosted-ui-proof';
import {
  trackingReportPolicyConsumerHostedUiProof as trackingReportPolicyConsumerHostedUiProofImpl,
  type TrackingReportPolicyConsumerHostedUiProof as TrackingReportPolicyConsumerHostedUiProofImpl,
  type TrackingReportPolicyConsumerHostedUiRow as TrackingReportPolicyConsumerHostedUiRowImpl,
} from './tracking-report-policy-consumer-hosted-ui-proof';

export const trackingChildCheckInProof = trackingChildCheckInProofImpl;
export const trackingChildRuntimeUiProof = trackingChildRuntimeUiProofImpl;
export type TrackingChildCheckInProof = TrackingChildCheckInProofImpl;
export type TrackingChildRuntimeUiProof = TrackingChildRuntimeUiProofImpl;

export const TrackingMissingDeviceHostedUiDetails = TrackingMissingDeviceHostedUiDetailsImpl;
export const trackingMissingDeviceHostedUiProof = trackingMissingDeviceHostedUiProofImpl;
export type TrackingMissingDeviceHostedUiProof = TrackingMissingDeviceHostedUiProofImpl;
export type TrackingMissingDeviceHostedUiRow = TrackingMissingDeviceHostedUiRowImpl;

export const TrackingNotificationParentSurfaceHostedUiDetails =
  TrackingNotificationParentSurfaceHostedUiDetailsImpl;
export const trackingNotificationParentSurfaceHostedUiProof =
  trackingNotificationParentSurfaceHostedUiProofImpl;
export type TrackingNotificationParentSurfaceHostedUiProof =
  TrackingNotificationParentSurfaceHostedUiProofImpl;
export type TrackingNotificationParentSurfaceHostedUiRow =
  TrackingNotificationParentSurfaceHostedUiRowImpl;

export const TrackingParentActionReadinessHostedUiDetails =
  TrackingParentActionReadinessHostedUiDetailsImpl;
export const trackingParentActionReadinessHostedUiProof =
  trackingParentActionReadinessHostedUiProofImpl;
export type TrackingParentActionReadinessHostedUiProof =
  TrackingParentActionReadinessHostedUiProofImpl;
export type TrackingParentActionReadinessHostedUiRow =
  TrackingParentActionReadinessHostedUiRowImpl;

export const trackingReportExportHostedUiProof = trackingReportExportHostedUiProofImpl;
export type TrackingReportExportHostedUiProof = TrackingReportExportHostedUiProofImpl;
export type TrackingReportExportHostedUiRow = TrackingReportExportHostedUiRowImpl;

export const trackingReportPolicyConsumerHostedUiProof =
  trackingReportPolicyConsumerHostedUiProofImpl;
export type TrackingReportPolicyConsumerHostedUiProof =
  TrackingReportPolicyConsumerHostedUiProofImpl;
export type TrackingReportPolicyConsumerHostedUiRow =
  TrackingReportPolicyConsumerHostedUiRowImpl;
