const PortalUnifiedChromeCssVars = {
  AppBackground: '--portal-app-background',
  FrameGlassColor: '--portal-frame-glass-color',
  FrameGlassOpacity: '--portal-frame-glass-opacity',
  FrameBodyFill: '--portal-frame-body-fill',
  FrameBodyStrokeOpacity: '--portal-frame-body-stroke-opacity',
  FrameFooterLineOpacity: '--portal-frame-footer-line-opacity',
  FrameHeaderLineOpacity: '--portal-frame-header-line-opacity',
  FrameScrimFill: '--portal-frame-scrim-fill',
  FrameSurfaceColor: '--portal-frame-surface-color',
  FrameSurfaceDisabledFillOpacity: '--portal-frame-surface-disabled-fill-opacity',
  FrameSurfaceFill: '--portal-frame-surface-fill',
  FrameSurfaceFillOpacity: '--portal-frame-surface-fill-opacity',
  FrameSurfaceOpacity: '--portal-frame-surface-opacity',
  FrameTransparentFill: '--portal-frame-transparent-fill',
  HeaderActionContentHoverFilter: '--portal-outline-header-action-content-hover-filter',
  HeaderActionContentHoverScale: '--portal-outline-header-action-content-hover-scale',
  HeaderBrandLogoBackground: '--portal-outline-header-brand-logo-bg',
  HeaderBrandLogoBorder: '--portal-outline-header-brand-logo-border',
  HeaderBrandLogoShadow: '--portal-outline-header-brand-logo-shadow',
  HeaderBrandText: '--portal-outline-header-brand-text',
  HeaderBrandTextShadow: '--portal-outline-header-brand-text-shadow',
  HeaderBrandTextStroke: '--portal-outline-header-brand-text-stroke',
  HeaderConnectorFill: '--portal-outline-header-connector-fill',
  HeaderConnectorFilter: '--portal-outline-header-connector-filter',
  HeaderConnectorStroke: '--portal-outline-header-connector-stroke',
  HeaderFrameFill: '--portal-outline-header-frame-fill',
  HeaderFrameFillBlur: '--portal-outline-header-frame-fill-blur',
  HeaderFrameLineFilter: '--portal-outline-header-frame-line-filter',
  HeaderFrameLineStroke: '--portal-outline-header-frame-line-stroke',
  HeaderFrameOuterStroke: '--portal-outline-header-frame-outer-stroke',
  HeaderIconFilter: '--portal-outline-header-icon-filter',
  HeaderLabelShadow: '--portal-outline-header-label-shadow',
  HeaderText: '--portal-outline-header-text',
  HeaderThemeHoverFilter: '--portal-outline-header-theme-hover-filter',
} as const;

const portalCssVarRef = <Value extends string>(value: Value): `var(${Value})` => `var(${value})`;

const PortalUnifiedChromeCssVarRefs = {
  AppBackground: portalCssVarRef(PortalUnifiedChromeCssVars.AppBackground),
  FrameGlassColor: portalCssVarRef(PortalUnifiedChromeCssVars.FrameGlassColor),
  FrameGlassOpacity: portalCssVarRef(PortalUnifiedChromeCssVars.FrameGlassOpacity),
  FrameBodyFill: portalCssVarRef(PortalUnifiedChromeCssVars.FrameBodyFill),
  FrameBodyStrokeOpacity: portalCssVarRef(PortalUnifiedChromeCssVars.FrameBodyStrokeOpacity),
  FrameFooterLineOpacity: portalCssVarRef(PortalUnifiedChromeCssVars.FrameFooterLineOpacity),
  FrameHeaderLineOpacity: portalCssVarRef(PortalUnifiedChromeCssVars.FrameHeaderLineOpacity),
  FrameScrimFill: portalCssVarRef(PortalUnifiedChromeCssVars.FrameScrimFill),
  FrameSurfaceColor: portalCssVarRef(PortalUnifiedChromeCssVars.FrameSurfaceColor),
  FrameSurfaceDisabledFillOpacity: portalCssVarRef(PortalUnifiedChromeCssVars.FrameSurfaceDisabledFillOpacity),
  FrameSurfaceFill: portalCssVarRef(PortalUnifiedChromeCssVars.FrameSurfaceFill),
  FrameSurfaceFillOpacity: portalCssVarRef(PortalUnifiedChromeCssVars.FrameSurfaceFillOpacity),
  FrameSurfaceOpacity: portalCssVarRef(PortalUnifiedChromeCssVars.FrameSurfaceOpacity),
  FrameTransparentFill: portalCssVarRef(PortalUnifiedChromeCssVars.FrameTransparentFill),
  HeaderActionContentHoverFilter: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderActionContentHoverFilter),
  HeaderActionContentHoverScale: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderActionContentHoverScale),
  HeaderBrandLogoBackground: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderBrandLogoBackground),
  HeaderBrandLogoBorder: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderBrandLogoBorder),
  HeaderBrandLogoShadow: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderBrandLogoShadow),
  HeaderBrandText: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderBrandText),
  HeaderBrandTextShadow: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderBrandTextShadow),
  HeaderBrandTextStroke: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderBrandTextStroke),
  HeaderConnectorFill: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderConnectorFill),
  HeaderConnectorFilter: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderConnectorFilter),
  HeaderConnectorStroke: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderConnectorStroke),
  HeaderFrameFill: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderFrameFill),
  HeaderFrameFillBlur: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderFrameFillBlur),
  HeaderFrameLineFilter: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderFrameLineFilter),
  HeaderFrameLineStroke: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderFrameLineStroke),
  HeaderFrameOuterStroke: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderFrameOuterStroke),
  HeaderIconFilter: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderIconFilter),
  HeaderLabelShadow: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderLabelShadow),
  HeaderText: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderText),
  HeaderThemeHoverFilter: portalCssVarRef(PortalUnifiedChromeCssVars.HeaderThemeHoverFilter),
} as const;

export const PortalUnifiedChrome = {
  Tags: {
    Footer: 'footer',
    Image: 'img',
  },
  Classes: {
    Shell: 'portal-unified-shell',
    ShellWork: 'portal-shell-work',
    OutlineHeader: 'portal-outline-header',
    OutlineHeaderAction: 'portal-outline-header__action',
    OutlineHeaderActionContent: 'portal-outline-header__action-content',
    OutlineHeaderActionIcon: 'portal-outline-header__action-icon',
    OutlineHeaderActionIconImage: 'portal-outline-header__action-icon-image',
    OutlineHeaderActionLabel: 'portal-outline-header__action-label',
    OutlineHeaderBrand: 'portal-outline-header__brand',
    OutlineHeaderBrandLogo: 'portal-outline-header__brand-logo',
    OutlineHeaderBrandLogoMount: 'portal-outline-header__brand-logo-mount',
    OutlineHeaderBrandLogoSpinner: 'portal-outline-header__brand-logo-spinner',
    OutlineHeaderConnector: 'portal-outline-header__connector',
    OutlineHeaderConnectorBox: 'portal-outline-header__connector-box',
    OutlineHeaderConnectorInteractive: 'portal-outline-header__connector-interactive',
    OutlineHeaderConnectorSvg: 'portal-outline-header__connector-svg',
    OutlineHeaderTheme: 'portal-outline-header__theme',
    OutlineHeaderThemeButton: 'portal-outline-header__theme-button',
    OutlineHeaderThemeButtonLeft: 'portal-outline-header__theme-button-left',
    OutlineHeaderThemeButtonRight: 'portal-outline-header__theme-button-right',
    OutlineHeaderThemeVisual: 'portal-outline-header__theme-visual',
    OutlineHeaderFrame: 'portal-outline-header__frame',
    OutlineHeaderFrameBlur: 'portal-outline-header__frame-blur',
    OutlineHeaderFrameContent: 'portal-outline-header__frame-content',
    OutlineHeaderFrameFill: 'portal-outline-header__frame-fill',
    OutlineHeaderFrameForeignObject: 'portal-outline-header__frame-foreign-object',
    OutlineHeaderFrameLine: 'portal-outline-header__frame-line',
    OutlineHeaderFrameOuter: 'portal-outline-header__frame-outer',
    OutlineHeaderFrameSegmentGroup: 'portal-outline-header__frame-segment-group',
    OutlineHeaderFrameSvg: 'portal-outline-header__frame-svg',
    OutlineHeaderBrandPart: 'portal-outline-header__brand-part',
    OutlineHeaderBrandPartMuted: 'portal-outline-header__brand-part-muted',
    Footer: 'oc-unified-footer',
    FooterBar: 'oc-unified-footer__bar',
    FooterContent: 'oc-unified-footer__content',
    FooterText: 'oc-unified-footer__text',
    FooterHeart: 'oc-unified-footer__heart',
    FooterLink: 'oc-unified-footer__link',
    FooterVersion: 'oc-unified-footer__version',
  },
  Attributes: {
    HeaderLogoLoading: 'data-oc-header-logo-loading',
    ShellHeaderExtension: 'data-oc-shell-header-extension',
  },
  Alt: {
    DecorativeImage: '',
  },
  CssVars: PortalUnifiedChromeCssVars,
  CssVarRefs: PortalUnifiedChromeCssVarRefs,
  Svg: {
    AnchorKeyInner: 'innerAnchor',
    AnchorKeyOuter: 'outerAnchor',
    BottomTabDown: 'down',
    FillNone: 'none',
    FrameColorCyan: '#2fddff',
    FrameKeyOuter: 'outerFrame',
    FrameLineVariant: {
      Line: 'line',
      Outline: 'outline',
    },
    FrameOrientationLandscape: 'landscape',
    HeaderConnectorViewBox: '0 0 100 44',
    PointerEventsNone: 'none',
    PreserveAspectRatioNone: 'none',
    StrokeLinejoinRound: 'round',
    VectorEffectNonScalingStroke: 'non-scaling-stroke',
  },
  Version: {
    App: '0.1.1',
  },
} as const;

export const PortalAssets = {
  AnonymousProfile: '/header-login.svg',
  HeaderHomeIcon: '/images/home.png',
  HeaderLoginIcon: '/images/login.png',
  HeaderLogo: '/ocentra-logo.svg',
  LanPairingScanIcon: '/images/scan.png',
} as const;

export const PortalExternalLinks = {
  Ocentra: 'https://ocentra.ca',
  BlankTarget: '_blank',
  ExternalRel: 'noopener noreferrer',
} as const;
