import { PortalDom } from '@ocentra-parent/portal-domain/contracts';
import styles from './portal-background-tuner-controls-panels.module.css';

const {
  actions,
  button,
  buttonActive,
  colorInput,
  colorLabel,
  column,
  columnTitle,
  editor,
  grid,
  header,
  headerTitle,
  json,
  jsonActions,
  jsonError,
  jsonStatus,
  jsonSummary,
  jsonTextarea,
  rangeInput,
  rangeLabel,
  rangeValue,
  status,
} = styles;

export const PortalBackgroundTunerPanelClasses = {
  actions,
  button,
  buttonActive: [button, buttonActive].join(PortalDom.Classes.ClassNameSeparator),
  colorInput,
  colorLabel,
  column,
  columnTitle,
  editor,
  grid,
  header,
  headerTitle,
  json,
  jsonActions,
  jsonError,
  jsonStatus,
  jsonSummary,
  jsonTextarea,
  rangeInput,
  rangeLabel,
  rangeValue,
  status,
} as const;
