import { decodeDisplayText, type PortalDisplayText } from './portal-display-text';

export const PortalDevTextToken = {
  Activity: decodeDisplayText('Activity'),
  ActivityDescription: decodeDisplayText('Stored activity'),
  AgentCommands: decodeDisplayText('Device controls'),
  AgentEvents: decodeDisplayText('Device audit'),
  AiRuntime: decodeDisplayText('Local AI'),
  AiRuntimeBody: decodeDisplayText(
    'Local AI should explain and summarize when available, while safety decisions remain typed and auditable.'
  ),
  AiRuntimeDescription: decodeDisplayText('Local model privacy'),
  AppGamePolicyReadiness: decodeDisplayText('App/game policy readiness'),
  AppGameSessions: decodeDisplayText('App and game sessions'),
  AppGameTimerParentSurface: decodeDisplayText('App/game timer parent surface'),
  AppTitle: decodeDisplayText('Ocentra Parent'),
  Approvals: decodeDisplayText('Approvals'),
  ApprovalsBody: decodeDisplayText('Route ask-parent moments into a clear approve, deny, or explain outcome.'),
  AuthBody: decodeDisplayText('Use a parent session before changing rules, approvals, drives, or child-device trust.'),
  AuthClose: decodeDisplayText('Close parent sign in'),
  AuthEyebrow: decodeDisplayText('Parent access'),
  AuthTitle: decodeDisplayText('Protect the family console'),
  AuthUnavailable: decodeDisplayText('Parent identity is not connected on this device yet.'),
  BillingEntitlements: decodeDisplayText('Billing and entitlements'),
  Browser: decodeDisplayText('Web'),
  BrowserBlockBody: decodeDisplayText(
    'Turn a supported browser rule into allow, ask-parent, explain-first, schedule-limit, or block behavior.'
  ),
  BrowserControls: decodeDisplayText('Browser controls'),
  BrowserDescription: decodeDisplayText('Browser evidence'),
  BrowserIntervention: decodeDisplayText('Browser protection'),
  BrowserManagedStatus: decodeDisplayText('Managed browser'),
  CommandResult: decodeDisplayText('Command result'),
  Commands: decodeDisplayText('Controls'),
  CommandsDescription: decodeDisplayText('Safe device refresh actions that use the real child-device connection.'),
  Connected: decodeDisplayText('Child device connected'),
  CopiedDiagnostics: decodeDisplayText('Diagnostics copied'),
  CopiedResult: decodeDisplayText('Copied'),
  CopyDiagnostics: decodeDisplayText('Copy diagnostics'),
  CopyDiagnosticsFailed: decodeDisplayText('Diagnostics copy failed'),
  CopyResult: decodeDisplayText('Copy result'),
  CopyResultFailed: decodeDisplayText('Copy failed'),
  DataCustodyBody: decodeDisplayText(
    'The child device keeps evidence locally. You decide whether diagnostics or exports leave the device.'
  ),
  DataCustodyTitle: decodeDisplayText('Private by design'),
  DesktopApp: decodeDisplayText('Desktop app'),
  DesktopAppBody: decodeDisplayText(
    'The desktop app hosts the child-device service and native capabilities for Windows, macOS, and Linux.'
  ),
  DevLog: decodeDisplayText('Service log'),
  DeviceDiagnostics: decodeDisplayText('Device diagnostics'),
  DeviceInventory: decodeDisplayText('Device inventory'),
  Devices: decodeDisplayText('Devices'),
  DevicesDescription: decodeDisplayText('Device control'),
  Diagnostics: decodeDisplayText('Support'),
  DiagnosticsDescription: decodeDisplayText('Exports and logs'),
  DisplayTheme: decodeDisplayText('Display theme'),
  DriveConnectionsBody: decodeDisplayText(
    'Prepare backups for a parent-owned drive, school archive, or support bundle when you choose.'
  ),
  DriveConnectionsTitle: decodeDisplayText('Connect your drives'),
  Events: decodeDisplayText('Audit'),
  EventsDescription: decodeDisplayText('Validated child-device audit entries from the local service.'),
  ExecuteActivityAppGameAdapterDispatch: decodeDisplayText('Execute scoped adapter dispatch'),
  ExportSync: decodeDisplayText('Export and sync'),
  FrameTuner: decodeDisplayText('App layout'),
  FrameTunerDescription: decodeDisplayText('Layout and content editor for parent portal app surfaces.'),
  GetActivityAppGameAdapterDispatchPreflightReadModel: decodeDisplayText('Refresh adapter dispatch preflight'),
  GetActivityAppGameAdapterDispatchResultReadModel: decodeDisplayText('Refresh adapter dispatch result'),
  GetActivityAppGameChildRuntimeTransportReceiptReadModel: decodeDisplayText('Refresh child runtime receipts'),
  GetActivityAppGamePlatformProofStatusReadModel: decodeDisplayText('Refresh platform proof status'),
  GetActivityAppGamePolicyReadinessReadModel: decodeDisplayText('Refresh policy readiness'),
  GetActivityAppGameTimerParentSurfaceReadModel: decodeDisplayText('Refresh timer parent surface'),
  GetActivityTrackingReadModel: decodeDisplayText('Refresh tracking status'),
  GetLocalAiRuntimeStatus: decodeDisplayText('Refresh local AI'),
  GetPolicyPreviewReadModel: decodeDisplayText('Refresh policy decision'),
  HeaderBrandLeft: decodeDisplayText("O'centra"),
  HeaderBrandRight: decodeDisplayText('Parent'),
  HeaderHome: decodeDisplayText('Home'),
  HeaderLogin: decodeDisplayText('Login'),
  Logs: decodeDisplayText('Logs'),
  LogsDescription: decodeDisplayText('Local portal and agent service log snapshots.'),
  Memory: decodeDisplayText('Memory'),
  MemoryBody: decodeDisplayText('Derived memory links must cite stored evidence, selected policy versions, or parent actions.'),
  MemoryDescription: decodeDisplayText('Cited local memory'),
  NavGroupDevTools: decodeDisplayText('Dev tools'),
  NavGroupGuide: decodeDisplayText('Guide'),
  NavGroupMonitor: decodeDisplayText('Today'),
  NavGroupOperate: decodeDisplayText('Manage'),
  NetworkFlow: decodeDisplayText('Network activity'),
  NoBrowserIntervention: decodeDisplayText('No browser protection decision is available yet.'),
  NoBrowserManagedStatus: decodeDisplayText('Managed browser status has not been reported yet.'),
  NoCommandResult: decodeDisplayText('Choose a device control to see the latest response.'),
  NoDevLog: decodeDisplayText('No service log snapshot has been reported yet.'),
  NoNetworkFlow: decodeDisplayText('No network activity is available yet.'),
  NotReported: decodeDisplayText('Not reported'),
  Notifications: decodeDisplayText('Notifications'),
  NotificationsBody: decodeDisplayText('Choose which events deserve a parent alert and which should stay in the daily audit.'),
  Overview: decodeDisplayText('Overview'),
  OverviewDescription: decodeDisplayText('Daily command'),
  Pairing: decodeDisplayText('Pairing'),
  PairingBody: decodeDisplayText(
    'Pair desktop and mobile apps with a parent-owned local trust step before controls are enabled.'
  ),
  ParentPortal: decodeDisplayText('Start here'),
  ParentPortalDescription: decodeDisplayText('Setup and controls map'),
  PendingServiceReadModel: decodeDisplayText('Not connected'),
  PendingTypedIntent: decodeDisplayText('Setup'),
  Policy: decodeDisplayText('Policy'),
  PolicyDescription: decodeDisplayText('Rules and approvals'),
  PolicyModeActive: decodeDisplayText('Active'),
  PolicyPreview: decodeDisplayText('Policy decision'),
  PolicyPreviewNoEnforcement: decodeDisplayText('Protection mode: advisory.'),
  ProductSurfacePending: decodeDisplayText('No family setting is configured for this area yet.'),
  ProofPanels: decodeDisplayText('Proof panels'),
  ProofPanelsDescription: decodeDisplayText('Tracking, network, and policy proof panels.'),
  Reconnect: decodeDisplayText('Reconnect'),
  RemoteScreen: decodeDisplayText('Remote screen'),
  RootMissing: decodeDisplayText('Portal root element is missing.'),
  RuleBuilder: decodeDisplayText('Rule builder'),
  RuleBuilderBody: decodeDisplayText(
    'Create family rules for web, apps, games, schedules, local AI explanations, and exception requests.'
  ),
  SchedulesBudgets: decodeDisplayText('Schedules and budgets'),
  SchedulesBudgetsBody: decodeDisplayText(
    'Set school, sleep, homework, and weekend windows without hiding what happened outside the window.'
  ),
  ScreenAnalysis: decodeDisplayText('Screen analysis'),
  SettingsRules: decodeDisplayText('Settings'),
  SettingsRulesDescription: decodeDisplayText('Schedules and budgets'),
  ThemeDark: decodeDisplayText('Dark'),
  ThemeLight: decodeDisplayText('Light'),
  TrackingStatusSurface: decodeDisplayText('Tracking status proof'),
  Unavailable: decodeDisplayText('Child device not connected'),
} as const;

export type PortalDevTextTokenValue = (typeof PortalDevTextToken)[keyof typeof PortalDevTextToken];

export function resolvePortalDevText(token: PortalDevTextTokenValue): PortalDisplayText {
  return token;
}
