import type { AgentEventEnvelope } from '@ocentra-parent/schema-domain/agent-command-event-contracts';
import {
  parseAgentSocialAlertReportParentSurfaceReadModelEvent as parsePortalDomainSocialAlertReportParentSurfaceReadModelEvent,
  parseAgentSocialAlertReportReadModelEvent as parsePortalDomainSocialAlertReportReadModelEvent,
  parseAgentSocialDashboardReadModelEvent as parsePortalDomainSocialDashboardReadModelEvent,
  parseAgentSocialParentNotificationDeliveryReadModelEvent as parsePortalDomainSocialParentNotificationDeliveryReadModelEvent,
  type AgentSocialAlertReportParentSurfaceReadModelFailureReason as PortalDomainAgentSocialAlertReportParentSurfaceReadModelFailureReason,
  type AgentSocialAlertReportParentSurfaceReadModelResult as PortalDomainAgentSocialAlertReportParentSurfaceReadModelResult,
  type AgentSocialAlertReportReadModelFailureReason as PortalDomainAgentSocialAlertReportReadModelFailureReason,
  type AgentSocialAlertReportReadModelResult as PortalDomainAgentSocialAlertReportReadModelResult,
  type AgentSocialDashboardReadModelFailureReason as PortalDomainAgentSocialDashboardReadModelFailureReason,
  type AgentSocialDashboardReadModelResult as PortalDomainAgentSocialDashboardReadModelResult,
  type AgentSocialParentNotificationDeliveryReadModelFailureReason as PortalDomainAgentSocialParentNotificationDeliveryReadModelFailureReason,
  type AgentSocialParentNotificationDeliveryReadModelResult as PortalDomainAgentSocialParentNotificationDeliveryReadModelResult,
  type SocialParentNotificationDeliveryReadModelSnapshot as PortalDomainSocialParentNotificationDeliveryReadModelSnapshot,
} from '@ocentra-parent/portal-domain/social-read-model-events';

export type AgentSocialAlertReportReadModelFailureReason = PortalDomainAgentSocialAlertReportReadModelFailureReason;
export type AgentSocialAlertReportReadModelResult = PortalDomainAgentSocialAlertReportReadModelResult;

export type AgentSocialAlertReportParentSurfaceReadModelFailureReason =
  PortalDomainAgentSocialAlertReportParentSurfaceReadModelFailureReason;
export type AgentSocialAlertReportParentSurfaceReadModelResult =
  PortalDomainAgentSocialAlertReportParentSurfaceReadModelResult;

export type SocialParentNotificationDeliveryReadModelSnapshot =
  PortalDomainSocialParentNotificationDeliveryReadModelSnapshot;
export type AgentSocialParentNotificationDeliveryReadModelFailureReason =
  PortalDomainAgentSocialParentNotificationDeliveryReadModelFailureReason;
export type AgentSocialParentNotificationDeliveryReadModelResult =
  PortalDomainAgentSocialParentNotificationDeliveryReadModelResult;

export type AgentSocialDashboardReadModelFailureReason = PortalDomainAgentSocialDashboardReadModelFailureReason;
export type AgentSocialDashboardReadModelResult = PortalDomainAgentSocialDashboardReadModelResult;

export function parseAgentSocialAlertReportReadModelEvent(
  event: AgentEventEnvelope
): AgentSocialAlertReportReadModelResult {
  return parsePortalDomainSocialAlertReportReadModelEvent(event);
}

export function parseAgentSocialAlertReportParentSurfaceReadModelEvent(
  event: AgentEventEnvelope
): AgentSocialAlertReportParentSurfaceReadModelResult {
  return parsePortalDomainSocialAlertReportParentSurfaceReadModelEvent(event);
}

export function parseAgentSocialParentNotificationDeliveryReadModelEvent(
  event: AgentEventEnvelope
): AgentSocialParentNotificationDeliveryReadModelResult {
  return parsePortalDomainSocialParentNotificationDeliveryReadModelEvent(event);
}

export function parseAgentSocialDashboardReadModelEvent(
  event: AgentEventEnvelope
): AgentSocialDashboardReadModelResult {
  return parsePortalDomainSocialDashboardReadModelEvent(event);
}
