ios_string_enums!(ChildIosEntitlementRuntimeOwner {
            IosXcodeProject => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_IOS_XCODE_PROJECT,
            IosInfoPlist => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_IOS_INFO_PLIST,
            IosSwiftScaffold => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_IOS_SWIFT_SCAFFOLD,
            IosSimulatorBuildScript => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_IOS_SIMULATOR_BUILD_SCRIPT,
            AppleSimulatorHost => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APPLE_SIMULATOR_HOST,
            AppleEntitlement => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APPLE_ENTITLEMENT,
            AppleDeviceFramework => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APPLE_DEVICE_FRAMEWORK,
            AppleNetworkExtension => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APPLE_NETWORK_EXTENSION,
            AppleNotificationPermission => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APPLE_NOTIFICATION_PERMISSION,
            AppleBackgroundMode => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APPLE_BACKGROUND_MODE,
            AppleSigning => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APPLE_SIGNING,
            AppleTestflight => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APPLE_TESTFLIGHT,
            AppleDeviceProof => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APPLE_DEVICE_PROOF,
            AppStoreConnect => CHILD_IOS_ENTITLEMENT_RUNTIME_OWNER_APP_STORE_CONNECT,
        });
        
        ios_string_enums!(ChildIosEntitlementDeclarationState {
            DeclaredInProject => CHILD_IOS_ENTITLEMENT_DECLARATION_STATE_DECLARED_IN_PROJECT,
            DeclaredInPlist => CHILD_IOS_ENTITLEMENT_DECLARATION_STATE_DECLARED_IN_PLIST,
            ScaffoldStatusLabel => CHILD_IOS_ENTITLEMENT_DECLARATION_STATE_SCAFFOLD_STATUS_LABEL,
            NotDeclared => CHILD_IOS_ENTITLEMENT_DECLARATION_STATE_NOT_DECLARED,
            NotApplicable => CHILD_IOS_ENTITLEMENT_DECLARATION_STATE_NOT_APPLICABLE,
        });
        
        ios_string_enums!(ChildIosEntitlementPackagePhase {
            XcodeProjectTarget => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_XCODE_PROJECT_TARGET,
            BundleIdentifier => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_BUNDLE_IDENTIFIER,
            SimulatorBuildScript => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_SIMULATOR_BUILD_SCRIPT,
            StatusView => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_STATUS_VIEW,
            InfoPlist => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_INFO_PLIST,
            SimulatorBuild => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_SIMULATOR_BUILD,
            SimulatorLaunch => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_SIMULATOR_LAUNCH,
            DeviceInstall => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_DEVICE_INSTALL,
            DeviceLaunch => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_DEVICE_LAUNCH,
            TestflightInstall => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_TESTFLIGHT_INSTALL,
            SigningProfile => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_SIGNING_PROFILE,
            EntitlementReview => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_ENTITLEMENT_REVIEW,
            RecoveryBehavior => CHILD_IOS_ENTITLEMENT_PACKAGE_PHASE_RECOVERY_BEHAVIOR,
        });
        
        ios_string_enums!(ChildIosEntitlementProtocolCommand {
            CapabilitySnapshotGet => CHILD_IOS_ENTITLEMENT_PROTOCOL_COMMAND_CAPABILITY_SNAPSHOT_GET,
            PackageProofGet => CHILD_IOS_ENTITLEMENT_PROTOCOL_COMMAND_PACKAGE_PROOF_GET,
            ManualProofGet => CHILD_IOS_ENTITLEMENT_PROTOCOL_COMMAND_MANUAL_PROOF_GET,
        });
        
        ios_string_enums!(ChildIosEntitlementProtocolEvent {
            CapabilitySnapshotReported => CHILD_IOS_ENTITLEMENT_PROTOCOL_EVENT_CAPABILITY_SNAPSHOT_REPORTED,
            PackageProofReported => CHILD_IOS_ENTITLEMENT_PROTOCOL_EVENT_PACKAGE_PROOF_REPORTED,
            ManualProofReported => CHILD_IOS_ENTITLEMENT_PROTOCOL_EVENT_MANUAL_PROOF_REPORTED,
        });
        
        ios_string_enums!(ChildIosEntitlementBridgeState {
            SimulatorScaffold => CHILD_IOS_ENTITLEMENT_BRIDGE_STATE_SIMULATOR_SCAFFOLD,
            NotImplemented => CHILD_IOS_ENTITLEMENT_BRIDGE_STATE_NOT_IMPLEMENTED,
        });
