use crate::ios_string_enums;

ios_string_enums!(ChildIosEntitlementParentCapability {
            PackageLifecycle => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_PACKAGE_LIFECYCLE,
            TypedProtocolBridge => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_TYPED_PROTOCOL_BRIDGE,
            FamilyControlsEntitlement => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_FAMILY_CONTROLS_ENTITLEMENT,
            DeviceActivity => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_DEVICE_ACTIVITY,
            ScreenTimeApi => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_SCREEN_TIME_API,
            NetworkExtension => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_NETWORK_EXTENSION,
            Notifications => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_NOTIFICATIONS,
            BackgroundExecution => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_BACKGROUND_EXECUTION,
            SigningEntitlements => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_SIGNING_ENTITLEMENTS,
            TestflightDistribution => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_TESTFLIGHT_DISTRIBUTION,
            StoreDistribution => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_STORE_DISTRIBUTION,
        });
        
        ios_string_enums!(ChildIosEntitlementParentCapabilityStatus {
            ManualRequired => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_STATUS_MANUAL_REQUIRED,
            Scaffold => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_STATUS_SCAFFOLD,
            Planned => CHILD_IOS_ENTITLEMENT_PARENT_CAPABILITY_STATUS_PLANNED,
        });
        
        ios_string_enums!(ChildIosEntitlementSurfaceName {
            SimulatorAppTarget => CHILD_IOS_ENTITLEMENT_SURFACE_SIMULATOR_APP_TARGET,
            BundleIdentifier => CHILD_IOS_ENTITLEMENT_SURFACE_BUNDLE_IDENTIFIER,
            StatusSurface => CHILD_IOS_ENTITLEMENT_SURFACE_STATUS_SURFACE,
            FamilyControlsEntitlement => CHILD_IOS_ENTITLEMENT_SURFACE_FAMILY_CONTROLS_ENTITLEMENT,
            DeviceActivityFramework => CHILD_IOS_ENTITLEMENT_SURFACE_DEVICE_ACTIVITY_FRAMEWORK,
            ScreenTimeApi => CHILD_IOS_ENTITLEMENT_SURFACE_SCREEN_TIME_API,
            NetworkExtension => CHILD_IOS_ENTITLEMENT_SURFACE_NETWORK_EXTENSION,
            NotificationsPermission => CHILD_IOS_ENTITLEMENT_SURFACE_NOTIFICATIONS_PERMISSION,
            BackgroundExecution => CHILD_IOS_ENTITLEMENT_SURFACE_BACKGROUND_EXECUTION,
            ProvisioningProfile => CHILD_IOS_ENTITLEMENT_SURFACE_PROVISIONING_PROFILE,
            SupervisionState => CHILD_IOS_ENTITLEMENT_SURFACE_SUPERVISION_STATE,
            SigningEntitlements => CHILD_IOS_ENTITLEMENT_SURFACE_SIGNING_ENTITLEMENTS,
            TestflightDistribution => CHILD_IOS_ENTITLEMENT_SURFACE_TESTFLIGHT_DISTRIBUTION,
            PhysicalDeviceProof => CHILD_IOS_ENTITLEMENT_SURFACE_PHYSICAL_DEVICE_PROOF,
            AppStoreDistribution => CHILD_IOS_ENTITLEMENT_SURFACE_APP_STORE_DISTRIBUTION,
        });
        
        ios_string_enums!(ChildIosEntitlementProofState {
            CiMechanicalProof => CHILD_IOS_ENTITLEMENT_PROOF_STATE_CI_MECHANICAL_PROOF,
            SimulatorScaffold => CHILD_IOS_ENTITLEMENT_PROOF_STATE_SIMULATOR_SCAFFOLD,
            ManualRequired => CHILD_IOS_ENTITLEMENT_PROOF_STATE_MANUAL_REQUIRED,
            EntitlementRequired => CHILD_IOS_ENTITLEMENT_PROOF_STATE_ENTITLEMENT_REQUIRED,
            SigningRequired => CHILD_IOS_ENTITLEMENT_PROOF_STATE_SIGNING_REQUIRED,
            DeviceProofRequired => CHILD_IOS_ENTITLEMENT_PROOF_STATE_DEVICE_PROOF_REQUIRED,
            NotDeclared => CHILD_IOS_ENTITLEMENT_PROOF_STATE_NOT_DECLARED,
            NotImplemented => CHILD_IOS_ENTITLEMENT_PROOF_STATE_NOT_IMPLEMENTED,
            Planned => CHILD_IOS_ENTITLEMENT_PROOF_STATE_PLANNED,
        });
