[workspace]
resolver = "2"
members = [
  "crates/agent-core",
  "crates/agent-protocol",
  "crates/agent-service",
  "crates/agent-updater",
  "crates/screen-capture-adapter"
]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "UNLICENSED"

[workspace.lints.rust]
unsafe_code = "forbid"
