const APP_GAME_TIMER_SERVICE_READINESS_GENERATED_MARKER_VALUE: &str =
    "app-game-timer-service-readiness";

pub const APP_GAME_TIMER_SERVICE_READINESS_GENERATED_MARKER: &str =
    APP_GAME_TIMER_SERVICE_READINESS_GENERATED_MARKER_VALUE;
