const APP_GAME_SOURCE_FRESHNESS_POLICY_CONSUMPTION_MATRIX_ID_VALUE: &str =
    "app-game-source-freshness-policy-consumption";

pub const APP_GAME_SOURCE_FRESHNESS_POLICY_CONSUMPTION_MATRIX_ID: &str =
    APP_GAME_SOURCE_FRESHNESS_POLICY_CONSUMPTION_MATRIX_ID_VALUE;
