use super::*;

pub(super) fn event_descriptors() -> Vec<ProtocolLiteralDescriptor<AgentEventName>> {
    let mut descriptors = Vec::new();
    descriptors.extend(event_descriptors_activity());
    descriptors.extend(event_descriptors_app_game());
    descriptors.extend(event_descriptors_browser_network());
    descriptors.extend(event_descriptors_local_policy_lan());
    descriptors
}

fn event_descriptors_activity() -> Vec<ProtocolLiteralDescriptor<AgentEventName>> {
    vec![
        event("ConnectionReady", AgentEventName::AgentConnectionReady),
        event("CommandRejected", AgentEventName::AgentCommandRejected),
        event("HealthReported", AgentEventName::AgentHealthReported),
        event(
            "LogSnapshotReported",
            AgentEventName::AgentLogSnapshotReported,
        ),
        event("DevEchoed", AgentEventName::AgentDevEchoed),
        event(
            "WatchStatusReported",
            AgentEventName::AgentWatchStatusReported,
        ),
        event(
            "ActivityIngestStatusReported",
            AgentEventName::AgentActivityIngestStatusReported,
        ),
        event(
            "ActivityRecentSummaryReported",
            AgentEventName::AgentActivityRecentSummaryReported,
        ),
        event(
            "ActivityMemoryGraphReported",
            AgentEventName::AgentActivityMemoryGraphReported,
        ),
        event(
            "ActivityReportGenerated",
            AgentEventName::AgentActivityReportGenerated,
        ),
        event(
            "ActivityReportSaved",
            AgentEventName::AgentActivityReportSaved,
        ),
        event(
            "ActivityReportHistoryReported",
            AgentEventName::AgentActivityReportHistoryReported,
        ),
        event(
            "ActivityScreenReadModelReported",
            AgentEventName::AgentActivityScreenReadModelReported,
        ),
        event(
            "ActivityAppUseReadModelReported",
            AgentEventName::AgentActivityAppUseReadModelReported,
        ),
        event(
            "ActivityBrowserReadModelReported",
            AgentEventName::AgentActivityBrowserReadModelReported,
        ),
        event(
            "ActivityGamesReadModelReported",
            AgentEventName::AgentActivityGamesReadModelReported,
        ),
        event(
            "ActivityAppGameBoundaryReadModelReported",
            AgentEventName::AgentActivityAppGameBoundaryReadModelReported,
        ),
    ]
}

fn event_descriptors_app_game() -> Vec<ProtocolLiteralDescriptor<AgentEventName>> {
    vec![
        event(
            "ActivityAppGameNotificationReadinessReadModelReported",
            AgentEventName::AgentActivityAppGameNotificationReadinessReadModelReported,
        ),
        event(
            "ActivityAppGameAdapterExecutionReadinessReadModelReported",
            AgentEventName::AgentActivityAppGameAdapterExecutionReadinessReadModelReported,
        ),
        event(
            "ActivityAppGamePlatformProofStatusReadModelReported",
            AgentEventName::AgentActivityAppGamePlatformProofStatusReadModelReported,
        ),
        event(
            "ActivityAppGameChildRuntimeTransportReceiptReadModelReported",
            AgentEventName::AgentActivityAppGameChildRuntimeTransportReceiptReadModelReported,
        ),
        event(
            "ActivityAppGameAdapterDispatchPreflightReadModelReported",
            AgentEventName::AgentActivityAppGameAdapterDispatchPreflightReadModelReported,
        ),
        event(
            "ActivityAppGameAdapterDispatchResultReadModelReported",
            AgentEventName::AgentActivityAppGameAdapterDispatchResultReadModelReported,
        ),
        event(
            "ActivityAppGameAdapterDispatchExecuted",
            AgentEventName::AgentActivityAppGameAdapterDispatchExecuted,
        ),
        event(
            "ActivityAppGameTimerParentSurfaceReadModelReported",
            AgentEventName::AgentActivityAppGameTimerParentSurfaceReadModelReported,
        ),
        event(
            "ActivityAppGameTimerParentPreferenceSetupRequested",
            AgentEventName::AgentActivityAppGameTimerParentPreferenceSetupRequested,
        ),
    ]
}

fn event_descriptors_browser_network() -> Vec<ProtocolLiteralDescriptor<AgentEventName>> {
    vec![
        event(
            "BrowserSocialDashboardReadModelReported",
            AgentEventName::AgentBrowserSocialDashboardReadModelReported,
        ),
        event(
            "BrowserSocialAuditExplanationReadModelReported",
            AgentEventName::AgentBrowserSocialAuditExplanationReadModelReported,
        ),
        event(
            "BrowserSocialAlertReportReadModelReported",
            AgentEventName::AgentBrowserSocialAlertReportReadModelReported,
        ),
        event(
            "BrowserSocialAlertReportParentSurfaceReadModelReported",
            AgentEventName::AgentBrowserSocialAlertReportParentSurfaceReadModelReported,
        ),
        event(
            "BrowserSocialParentNotificationDeliveryReadModelReported",
            AgentEventName::AgentBrowserSocialParentNotificationDeliveryReadModelReported,
        ),
        event(
            "BrowserSocialSourceCustodyMutationApplied",
            AgentEventName::AgentBrowserSocialSourceCustodyMutationApplied,
        ),
        event(
            "ActivityNetworkReadModelReported",
            AgentEventName::AgentActivityNetworkReadModelReported,
        ),
        event(
            "BrowserEvidenceRecentReported",
            AgentEventName::AgentBrowserEvidenceRecentReported,
        ),
        event(
            "BrowserManagedStatusReported",
            AgentEventName::AgentBrowserManagedStatusReported,
        ),
        event(
            "BrowserInventoryReadModelReported",
            AgentEventName::AgentBrowserInventoryReadModelReported,
        ),
        event(
            "BrowserInterventionReadModelReported",
            AgentEventName::AgentBrowserInterventionReadModelReported,
        ),
        event(
            "BrowserRuntimeEventChainStreamReported",
            AgentEventName::AgentBrowserRuntimeEventChainStreamReported,
        ),
        event(
            "NetworkFlowReadModelReported",
            AgentEventName::AgentNetworkFlowReadModelReported,
        ),
        event(
            "NetworkRuntimeEventChainStreamReported",
            AgentEventName::AgentNetworkRuntimeEventChainStreamReported,
        ),
        event(
            "LanRuntimeEventChainStreamReported",
            AgentEventName::AgentLanRuntimeEventChainStreamReported,
        ),
        event(
            "NetworkRemoteDeliveryStatusReported",
            AgentEventName::AgentNetworkRemoteDeliveryStatusReported,
        ),
        event(
            "NetworkLiveCaptureStatusReported",
            AgentEventName::AgentNetworkLiveCaptureStatusReported,
        ),
    ]
}

pub(super) fn event_descriptors_local_policy_lan() -> Vec<ProtocolLiteralDescriptor<AgentEventName>>
{
    let mut descriptors = Vec::new();
    descriptors.extend(event_descriptors_local_policy_lan_network());
    descriptors.extend(event_descriptors_local_policy_lan_policy());
    descriptors.extend(event_descriptors_local_policy_lan_enforcement());
    descriptors.extend(event_descriptors_local_policy_lan_pairing());
    descriptors
}

fn event_descriptors_local_policy_lan_network() -> Vec<ProtocolLiteralDescriptor<AgentEventName>> {
    vec![
        event(
            "NetworkLinuxNftablesLabStatusReported",
            AgentEventName::AgentNetworkLinuxNftablesLabStatusReported,
        ),
        event(
            "NetworkWindowsFirewallLabStatusReported",
            AgentEventName::AgentNetworkWindowsFirewallLabStatusReported,
        ),
        event(
            "NetworkWindowsWfpGateStatusReported",
            AgentEventName::AgentNetworkWindowsWfpGateStatusReported,
        ),
        event(
            "NetworkAndroidVpnServiceGateStatusReported",
            AgentEventName::AgentNetworkAndroidVpnServiceGateStatusReported,
        ),
        event(
            "NetworkAppleNetworkExtensionGateStatusReported",
            AgentEventName::AgentNetworkAppleNetworkExtensionGateStatusReported,
        ),
        event(
            "ActivityTrackingReadModelReported",
            AgentEventName::AgentActivityTrackingReadModelReported,
        ),
        event(
            "ActivityTrackingRetentionSettingsWriteReported",
            AgentEventName::AgentActivityTrackingRetentionSettingsWriteReported,
        ),
        event(
            "ParentRuntimeIntentIngressReported",
            AgentEventName::AgentParentRuntimeIntentIngressReported,
        ),
        event(
            "LocalAiRuntimeStatusReported",
            AgentEventName::AgentLocalAiRuntimeStatusReported,
        ),
        event(
            "LocalAiChatGenerationReported",
            AgentEventName::AgentLocalAiChatGenerationReported,
        ),
        event(
            "PolicyPreviewReadModelReported",
            AgentEventName::AgentPolicyPreviewReadModelReported,
        ),
        event(
            "PolicyRequestAssistantPreviewConfirmReported",
            AgentEventName::AgentPolicyRequestAssistantPreviewConfirmReported,
        ),
        event(
            "PolicyRequestParentResolutionResolved",
            AgentEventName::AgentPolicyRequestParentResolutionResolved,
        ),
    ]
}

fn event_descriptors_local_policy_lan_policy() -> Vec<ProtocolLiteralDescriptor<AgentEventName>> {
    vec![
        event(
            "BrowserPolicyReported",
            AgentEventName::AgentBrowserPolicyReported,
        ),
        event(
            "BrowserPolicyPreviewed",
            AgentEventName::AgentBrowserPolicyPreviewed,
        ),
        event(
            "BrowserPolicyPatchAccepted",
            AgentEventName::AgentBrowserPolicyPatchAccepted,
        ),
        event(
            "BrowserPolicyPatchRejected",
            AgentEventName::AgentBrowserPolicyPatchRejected,
        ),
        event(
            "BrowserPolicyReplaceAccepted",
            AgentEventName::AgentBrowserPolicyReplaceAccepted,
        ),
        event(
            "BrowserPolicyReplaceRejected",
            AgentEventName::AgentBrowserPolicyReplaceRejected,
        ),
        event(
            "BrowserPolicyRollbackAccepted",
            AgentEventName::AgentBrowserPolicyRollbackAccepted,
        ),
        event(
            "BrowserPolicyRollbackRejected",
            AgentEventName::AgentBrowserPolicyRollbackRejected,
        ),
        event(
            "ScreenSettingsReported",
            AgentEventName::AgentScreenSettingsReported,
        ),
        event(
            "ScreenSettingsReplaceAccepted",
            AgentEventName::AgentScreenSettingsReplaceAccepted,
        ),
        event(
            "ScreenSettingsReplaceRejected",
            AgentEventName::AgentScreenSettingsReplaceRejected,
        ),
    ]
}

fn event_descriptors_local_policy_lan_enforcement() -> Vec<ProtocolLiteralDescriptor<AgentEventName>>
{
    vec![
        event(
            "EnforcementAuditReported",
            AgentEventName::AgentEnforcementAuditReported,
        ),
        event(
            "EnforcementTimerReported",
            AgentEventName::AgentEnforcementTimerReported,
        ),
        event(
            "EnforcementProductControlSpineReported",
            AgentEventName::AgentEnforcementProductControlSpineReported,
        ),
        event(
            "EnforcementPolicyDispatchReported",
            AgentEventName::AgentEnforcementPolicyDispatchReported,
        ),
        event(
            "EnforcementBroadAdapterProofReported",
            AgentEventName::AgentEnforcementBroadAdapterProofReported,
        ),
        event(
            "EnforcementSupportedAdapterRuntimeProofReported",
            AgentEventName::AgentEnforcementSupportedAdapterRuntimeProofReported,
        ),
        event(
            "ActivityAppGamePolicyReadinessReadModelReported",
            AgentEventName::AgentActivityAppGamePolicyReadinessReadModelReported,
        ),
        event(
            "ParentAssistantAnswerReported",
            AgentEventName::AgentParentAssistantAnswerReported,
        ),
        event(
            "ParentAssistantThreadUpdated",
            AgentEventName::AgentParentAssistantThreadUpdated,
        ),
        event(
            "ParentAssistantMessageAccepted",
            AgentEventName::AgentParentAssistantMessageAccepted,
        ),
        event(
            "ParentAssistantRunStarted",
            AgentEventName::AgentParentAssistantRunStarted,
        ),
        event(
            "ParentAssistantMessageDelta",
            AgentEventName::AgentParentAssistantMessageDelta,
        ),
        event(
            "ParentAssistantMessageCompleted",
            AgentEventName::AgentParentAssistantMessageCompleted,
        ),
        event(
            "ParentAssistantActionPreviewed",
            AgentEventName::AgentParentAssistantActionPreviewed,
        ),
        event(
            "ParentAssistantActionConfirmed",
            AgentEventName::AgentParentAssistantActionConfirmed,
        ),
        event(
            "ParentAssistantProviderDegraded",
            AgentEventName::AgentParentAssistantProviderDegraded,
        ),
        event(
            "ParentAssistantErrorReported",
            AgentEventName::AgentParentAssistantErrorReported,
        ),
    ]
}

fn event_descriptors_local_policy_lan_pairing() -> Vec<ProtocolLiteralDescriptor<AgentEventName>> {
    vec![
        event(
            "LanPairingStatusReported",
            AgentEventName::AgentLanPairingStatusReported,
        ),
        event(
            "LanPairingBrowserDiscoveryReported",
            AgentEventName::AgentLanPairingBrowserDiscoveryReported,
        ),
        event(
            "LanPairingAddDeviceReported",
            AgentEventName::AgentLanPairingAddDeviceReported,
        ),
        event(
            "LanPairingSignedChildAgentReported",
            AgentEventName::AgentLanPairingSignedChildAgentReported,
        ),
        event(
            "LanPairingAuditReported",
            AgentEventName::AgentLanPairingAuditReported,
        ),
        event("LanAiJobReported", AgentEventName::AgentLanAiJobReported),
    ]
}
