pub(super) const ACTIVITY_SURFACE_DECODER_TYPESCRIPT_TEMPLATE_A: &str = r#"
export const __READ_MODEL_KIND_NAME_CONST__ = { Screen: __SECTION_KIND_CONST__.Screen, AppUse: __SECTION_KIND_CONST__.AppUse, Browser: __SECTION_KIND_CONST__.Browser, Games: __SECTION_KIND_CONST__.Games, Network: __SECTION_KIND_CONST__.Network } as const;
export type __READ_MODEL_KIND_TYPE__ = (typeof __READ_MODEL_KIND_NAME_CONST__)[keyof typeof __READ_MODEL_KIND_NAME_CONST__];
export type __PARSER_TYPE__<T> = { readonly parse: (input: unknown) => T; readonly safeParse: (input: unknown) => { readonly success: true; readonly data: T } | { readonly success: false } };
export type __EVIDENCE_REF_TYPE__ = { readonly evidenceId: string; readonly kind: __EVIDENCE_KIND_TYPE__; readonly digest: string | null; readonly uri: string | null };
export type __SCOPE_TYPE__ = { readonly scopeKind: __SCOPE_KIND_TYPE__; readonly familyId: string | null; readonly deviceId: string | null };
export type __REQUEST_TYPE__ = { readonly schemaVersion: typeof __SCHEMA_VERSION_CONST__; readonly scope: __SCOPE_TYPE__; readonly requestedAt: string; readonly rangeStart: string; readonly rangeEnd: string };
export type __SOURCE_STATE_TYPE__ = { readonly deviceId: string; readonly reachabilityState: __SOURCE_REACHABILITY_TYPE__; readonly state: __READ_MODEL_STATE_TYPE__; readonly reason: string | null; readonly lastUpdatedAt: string | null; readonly custodyLabel: __CUSTODY_LABEL_TYPE__; readonly sourceLabel: __SOURCE_LABEL_TYPE__; readonly rawChildEvidenceIncluded: boolean };
export type __SECTION_TYPE__ = { readonly sectionKind: __SECTION_KIND_TYPE__; readonly title: string; readonly state: __READ_MODEL_STATE_TYPE__; readonly summary: string; readonly itemCount: number; readonly evidence: readonly __EVIDENCE_REF_TYPE__[] };
export type __SAVED_METADATA_TYPE__ = { readonly reportId: string; readonly fileName: string; readonly savedState: __SAVED_REPORT_STATE_TYPE__; readonly savedAt: string | null; readonly storageReason: string | null; readonly custodyLabel: __CUSTODY_LABEL_TYPE__; readonly sourceLabel: __SOURCE_LABEL_TYPE__; readonly rawChildEvidenceIncluded: boolean };
export type __SOURCE_STATE_SUMMARY_TYPE__ = { readonly totalSources: number; readonly readySources: number; readonly offlineSources: number; readonly staleSources: number; readonly unavailableSources: number; readonly unreachableSources: number; readonly errorSources: number };
export type __REPORT_DOCUMENT_TYPE__ = { readonly schemaVersion: typeof __SCHEMA_VERSION_CONST__; readonly reportId: string; readonly frequency: __REPORT_FREQUENCY_TYPE__; readonly scope: __SCOPE_TYPE__; readonly requestedAt: string; readonly rangeStart: string; readonly rangeEnd: string; readonly generatedAt: string; readonly savedMetadata: __SAVED_METADATA_TYPE__ | null; readonly sourceStates: readonly __SOURCE_STATE_TYPE__[]; readonly sections: readonly __SECTION_TYPE__[] };
export type __HISTORY_ITEM_TYPE__ = { readonly schemaVersion: typeof __SCHEMA_VERSION_CONST__; readonly reportId: string; readonly fileName: string; readonly reportDate: string; readonly rangeStart: string; readonly rangeEnd: string; readonly summary: string; readonly savedState: __SAVED_REPORT_STATE_TYPE__; readonly savedAt: string | null; readonly sourceStateSummary: __SOURCE_STATE_SUMMARY_TYPE__; readonly parsedReport: __REPORT_DOCUMENT_TYPE__; readonly custodyLabel: __CUSTODY_LABEL_TYPE__; readonly sourceLabel: __SOURCE_LABEL_TYPE__; readonly rawChildEvidenceIncluded: boolean };
export type __HISTORY_LIST_TYPE__ = { readonly schemaVersion: typeof __SCHEMA_VERSION_CONST__; readonly request: __REQUEST_TYPE__; readonly state: __READ_MODEL_STATE_TYPE__; readonly storageState: __SAVED_REPORT_STATE_TYPE__; readonly storageReason: string | null; readonly reports: readonly __HISTORY_ITEM_TYPE__[] };
export type __SOURCE_STATUS_ROW_TYPE__ = { readonly sourceKind: string; readonly state: __READ_MODEL_STATE_TYPE__; readonly rowCount: number; readonly lastObservedAt: string | null; readonly capabilityStatus: string; readonly evidence: readonly __EVIDENCE_REF_TYPE__[] };
export type __TAB_READ_MODEL_TYPE__<Row> = { readonly schemaVersion: typeof __SCHEMA_VERSION_CONST__; readonly request: __REQUEST_TYPE__; readonly state: __READ_MODEL_STATE_TYPE__; readonly generatedAt: string; readonly summary: string; readonly rows: readonly Row[] };
export type __SCREEN_ROW_TYPE__ = { readonly rowId: string; readonly label: string; readonly deviceId: string; readonly state: __READ_MODEL_STATE_TYPE__; readonly totalMs: number; readonly foregroundMs: number; readonly backgroundMs: number; readonly captureReason: string; readonly captureScope: string; readonly capabilityStatus: string; readonly queueJobId: string; readonly modelRuntimeRef: string; readonly modelId: string; readonly providerKind: string; readonly promptOrTemplateVersion: string; readonly primaryCategory: string | null; readonly confidence: number; readonly imageDeletionState: string; readonly rawImageRetained: boolean; readonly policyEligible: boolean; readonly imageDigest: string; readonly custodyState: string; readonly evidence: readonly __EVIDENCE_REF_TYPE__[]; readonly policyDecisionRef: string | null; readonly policyAction: string | null; readonly policyReasonCodes: readonly string[]; readonly parentRuleRefs: readonly string[]; readonly localModelRuntimeRefs: readonly string[]; readonly parentExplanationRefs: readonly string[]; readonly explanationReasons: readonly string[]; readonly deletionReasons: readonly string[]; readonly ocrTextSnippets: readonly string[]; readonly redactionNotes: readonly string[] };
export type __APP_USE_ROW_TYPE__ = { readonly rowId: string; readonly appName: string; readonly deviceId: string; readonly state: __READ_MODEL_STATE_TYPE__; readonly productKind: string; readonly classificationState: string; readonly inventoryState: string; readonly runtimeState: string; readonly foregroundState: string; readonly capabilityStatus: string; readonly lastObservedAt: string | null; readonly totalMs: number; readonly launchCount: number; readonly inventoryRowCount: number; readonly runningRowCount: number; readonly foregroundRowCount: number; readonly dailyRollupCount: number; readonly evidenceClaimRowCount: number; readonly identityRowCount: number; readonly approvalAuthorityRowCount: number; readonly approvalActionResultRowCount: number; readonly platformAuthorityMatrixCount: number; readonly platformAuthorityRowCount: number; readonly aiClassifierResultRowCount: number; readonly sourceStatusRows: readonly __SOURCE_STATUS_ROW_TYPE__[]; readonly evidence: readonly __EVIDENCE_REF_TYPE__[] };
export type __BROWSER_ROW_TYPE__ = { readonly rowId: string; readonly domainLabel: string; readonly deviceId: string; readonly state: __READ_MODEL_STATE_TYPE__; readonly visitCount: number; readonly totalMs: number; readonly evidenceDigest: string | null };
export type __GAMES_ROW_TYPE__ = { readonly rowId: string; readonly displayName: string; readonly deviceId: string; readonly state: __READ_MODEL_STATE_TYPE__; readonly productKind: string; readonly classificationState: string; readonly inventoryState: string; readonly runtimeState: string; readonly foregroundState: string; readonly capabilityStatus: string; readonly lastObservedAt: string | null; readonly totalMs: number; readonly sessionCount: number; readonly launcherRowCount: number; readonly runningRowCount: number; readonly foregroundRowCount: number; readonly dailyRollupCount: number; readonly evidenceClaimRowCount: number; readonly identityRowCount: number; readonly approvalAuthorityRowCount: number; readonly approvalActionResultRowCount: number; readonly platformAuthorityMatrixCount: number; readonly platformAuthorityRowCount: number; readonly aiClassifierResultRowCount: number; readonly sourceStatusRows: readonly __SOURCE_STATUS_ROW_TYPE__[]; readonly evidence: readonly __EVIDENCE_REF_TYPE__[] };
export type __NETWORK_ROW_TYPE__ = { readonly rowId: string; readonly destinationLabel: string; readonly deviceId: string; readonly state: __READ_MODEL_STATE_TYPE__; readonly connectionCount: number; readonly totalBytes: number; readonly evidenceDigest: string | null };
export type __SCREEN_READ_MODEL_TYPE__ = __TAB_READ_MODEL_TYPE__<__SCREEN_ROW_TYPE__>;
export type __APP_USE_READ_MODEL_TYPE__ = __TAB_READ_MODEL_TYPE__<__APP_USE_ROW_TYPE__>;
export type __BROWSER_READ_MODEL_TYPE__ = __TAB_READ_MODEL_TYPE__<__BROWSER_ROW_TYPE__>;
export type __GAMES_READ_MODEL_TYPE__ = __TAB_READ_MODEL_TYPE__<__GAMES_ROW_TYPE__>;
export type __NETWORK_READ_MODEL_TYPE__ = __TAB_READ_MODEL_TYPE__<__NETWORK_ROW_TYPE__>;
export type __SURFACE_READ_MODEL_TYPE__ = __SCREEN_READ_MODEL_TYPE__ | __APP_USE_READ_MODEL_TYPE__ | __BROWSER_READ_MODEL_TYPE__ | __GAMES_READ_MODEL_TYPE__ | __NETWORK_READ_MODEL_TYPE__;
function __HELPER_PREFIX__Schema<T>(decoder: (value: unknown) => T): __PARSER_TYPE__<T> {
  const parse = decoder;
  const safeParse = (
    value: unknown
  ): { readonly success: true; readonly data: T } | { readonly success: false } => {
    try {
      return { success: true, data: decoder(value) };
    } catch {
      return { success: false };
    }
  };
  return { parse, safeParse } as const;
}
function __HELPER_PREFIX__IsRecord(value: unknown): value is Readonly<Record<string, unknown>> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
function __HELPER_PREFIX__ReadRecord(value: unknown, label: string): Readonly<Record<string, unknown>> { if (!__HELPER_PREFIX__IsRecord(value)) { throw new TypeError(`${label} must be an activity surface object`); } return value; }
function __HELPER_PREFIX__ReadString(record: Readonly<Record<string, unknown>>, field: string): string { const value = record[field]; if (typeof value !== 'string' || value.length === 0) { throw new TypeError(`${field} must be a non-empty activity surface string`); } return value; }
function __HELPER_PREFIX__ReadNullableString(record: Readonly<Record<string, unknown>>, field: string): string | null { const value = record[field]; if (value === null) { return null; } if (typeof value !== 'string' || value.length === 0) { throw new TypeError(`${field} must be a non-empty activity surface string or null`); } return value; }
function __HELPER_PREFIX__ReadOptionalNullableString(record: Readonly<Record<string, unknown>>, field: string): string | null { const value = record[field]; if (value === undefined || value === null) { return null; } if (typeof value !== 'string' || value.length === 0) { throw new TypeError(`${field} must be a non-empty activity surface string or null`); } return value; }
function __HELPER_PREFIX__ReadBoolean(record: Readonly<Record<string, unknown>>, field: string): boolean { const value = record[field]; if (typeof value !== 'boolean') { throw new TypeError(`${field} must be an activity surface boolean`); } return value; }
function __HELPER_PREFIX__ReadOptionalFalse(record: Readonly<Record<string, unknown>>, field: string): boolean { const value = record[field]; if (value === undefined) { return false; } if (value !== false) { throw new TypeError(`${field} must be false for activity surface redaction/custody boundary`); } return false; }
function __HELPER_PREFIX__ReadNonNegativeInteger(record: Readonly<Record<string, unknown>>, field: string): number { const value = record[field]; if (typeof value !== 'number' || !Number.isInteger(value) || value < 0) { throw new TypeError(`${field} must be a non-negative activity surface integer`); } return value; }
function __HELPER_PREFIX__ReadConfidence(record: Readonly<Record<string, unknown>>, field: string): number { const value = record[field]; if (typeof value !== 'number' || !Number.isFinite(value) || value < 0 || value > 1) { throw new TypeError(`${field} must be an activity surface confidence from 0 to 1`); } return value; }
"#;
