pub(super) const ACTIVITY_SURFACE_DECODER_TYPESCRIPT_TEMPLATE_B: &str = r#"
function __HELPER_PREFIX__ReadSchemaVersion(record: Readonly<Record<string, unknown>>): typeof __SCHEMA_VERSION_CONST__ { if (record['schemaVersion'] !== __SCHEMA_VERSION_CONST__) { throw new TypeError('schemaVersion is not the Rust-owned activity surface schema version'); } return __SCHEMA_VERSION_CONST__; }
function __HELPER_PREFIX__ReadLiteral<T extends string>(record: Readonly<Record<string, unknown>>, field: string, allowed: readonly T[]): T { const value = __HELPER_PREFIX__ReadString(record, field); if (!allowed.includes(value as T)) { throw new TypeError(`${field} is not a Rust-owned activity surface literal`); } return value as T; }
function __HELPER_PREFIX__ReadOptionalLiteral<T extends string>(record: Readonly<Record<string, unknown>>, field: string, allowed: readonly T[], fallback: T): T { const value = record[field]; if (value === undefined) { return fallback; } if (typeof value !== 'string' || !allowed.includes(value as T)) { throw new TypeError(`${field} is not a Rust-owned activity surface literal`); } return value as T; }
function __HELPER_PREFIX__ReadArray<T>(record: Readonly<Record<string, unknown>>, field: string, decoder: (value: unknown) => T): readonly T[] { const value = record[field]; if (!Array.isArray(value)) { throw new TypeError(`${field} must be an activity surface array`); } return value.map(decoder); }
function __HELPER_PREFIX__ReadStringArrayValue(value: unknown, field: string): readonly string[] { if (!Array.isArray(value) || value.some((entry) => typeof entry !== 'string' || entry.length === 0)) { throw new TypeError(`${field} must be an activity surface string array`); } return value as readonly string[]; }
function __HELPER_PREFIX__ReadOptionalStringArray(record: Readonly<Record<string, unknown>>, field: string): readonly string[] { const value = record[field]; if (value === undefined) { return []; } return __HELPER_PREFIX__ReadStringArrayValue(value, field); }
function __HELPER_PREFIX__DecodeEvidenceRef(value: unknown): __EVIDENCE_REF_TYPE__ { const record = __HELPER_PREFIX__ReadRecord(value, 'activity evidence ref'); return { evidenceId: __HELPER_PREFIX__ReadString(record, 'evidenceId'), kind: __HELPER_PREFIX__ReadLiteral(record, 'kind', Object.values(__EVIDENCE_KIND_CONST__)), digest: __HELPER_PREFIX__ReadNullableString(record, 'digest'), uri: __HELPER_PREFIX__ReadNullableString(record, 'uri') }; }
function __HELPER_PREFIX__ReadEvidenceArray(record: Readonly<Record<string, unknown>>, field: string): readonly __EVIDENCE_REF_TYPE__[] { return __HELPER_PREFIX__ReadArray(record, field, __HELPER_PREFIX__DecodeEvidenceRef); }
function __HELPER_PREFIX__DecodeScope(value: unknown): __SCOPE_TYPE__ { const record = __HELPER_PREFIX__ReadRecord(value, 'activity surface scope'); const scope = { scopeKind: __HELPER_PREFIX__ReadLiteral(record, 'scopeKind', Object.values(__SCOPE_KIND_CONST__)), familyId: __HELPER_PREFIX__ReadNullableString(record, 'familyId'), deviceId: __HELPER_PREFIX__ReadNullableString(record, 'deviceId') }; if (scope.scopeKind === __SCOPE_KIND_CONST__.Family && (scope.familyId === null || scope.deviceId !== null)) { throw new TypeError('family activity scope must include familyId only'); } if (scope.scopeKind === __SCOPE_KIND_CONST__.Device && (scope.familyId !== null || scope.deviceId === null)) { throw new TypeError('device activity scope must include deviceId only'); } return scope; }
"#;
