import {
  BrowserParentExplanationText as SchemaDomainBrowserParentExplanationText,
  BrowserParentExplanationTextToken as SchemaDomainBrowserParentExplanationTextToken,
  resolveBrowserParentExplanationText as resolveSchemaDomainBrowserParentExplanationText,
  type BrowserParentExplanationTextTokenValue as SchemaDomainBrowserParentExplanationTextTokenValue,
} from '@ocentra-parent/schema-domain/text-browser-ux';

export const BrowserParentExplanationTextToken = SchemaDomainBrowserParentExplanationTextToken;
export type BrowserParentExplanationTextTokenValue = SchemaDomainBrowserParentExplanationTextTokenValue;
export const BrowserParentExplanationText = SchemaDomainBrowserParentExplanationText;
export const resolveBrowserParentExplanationText = resolveSchemaDomainBrowserParentExplanationText;
