import { decodeDisplayText, decodeTextTokenId, type DisplayText } from './contracts';

export const PortalDevTextToken = {
  AppTitle: decodeTextTokenId('portal.dev.appTitle'),
  Subtitle: decodeTextTokenId('portal.dev.subtitle'),
  Reconnect: decodeTextTokenId('portal.dev.reconnect'),
  Overview: decodeTextTokenId('portal.dev.route.overview'),
  Commands: decodeTextTokenId('portal.dev.route.commands'),
  Events: decodeTextTokenId('portal.dev.route.events'),
  Connected: decodeTextTokenId('portal.dev.connected'),
  Unavailable: decodeTextTokenId('portal.dev.unavailable'),
  AgentCommands: decodeTextTokenId('portal.dev.agentCommands'),
  AgentEvents: decodeTextTokenId('portal.dev.agentEvents'),
  ActivityTimeline: decodeTextTokenId('portal.dev.activityTimeline'),
  DeviceDiagnostics: decodeTextTokenId('portal.dev.deviceDiagnostics'),
  DevLog: decodeTextTokenId('portal.dev.devLog'),
  EvidenceStore: decodeTextTokenId('portal.dev.evidenceStore'),
  BrowserEvidence: decodeTextTokenId('portal.dev.browserEvidence'),
  BrowserManagedStatus: decodeTextTokenId('portal.dev.browserManagedStatus'),
  NetworkFlow: decodeTextTokenId('portal.dev.networkFlow'),
  LiveActivity: decodeTextTokenId('portal.dev.liveActivity'),
  NoActivityStatus: decodeTextTokenId('portal.dev.noActivityStatus'),
  NoBrowserEvidence: decodeTextTokenId('portal.dev.noBrowserEvidence'),
  NoBrowserManagedStatus: decodeTextTokenId('portal.dev.noBrowserManagedStatus'),
  NoDevLog: decodeTextTokenId('portal.dev.noDevLog'),
  NoEvents: decodeTextTokenId('portal.dev.noEvents'),
  NoNetworkFlow: decodeTextTokenId('portal.dev.noNetworkFlow'),
  NoRecentActivity: decodeTextTokenId('portal.dev.noRecentActivity'),
  NotReported: decodeTextTokenId('portal.dev.notReported'),
  RecentActivity: decodeTextTokenId('portal.dev.recentActivity'),
  CommandResult: decodeTextTokenId('portal.dev.commandResult'),
  CopyDiagnostics: decodeTextTokenId('portal.dev.copyDiagnostics'),
  CopiedDiagnostics: decodeTextTokenId('portal.dev.copiedDiagnostics'),
  CopyDiagnosticsFailed: decodeTextTokenId('portal.dev.copyDiagnosticsFailed'),
  CopyResult: decodeTextTokenId('portal.dev.copyResult'),
  CopiedResult: decodeTextTokenId('portal.dev.copiedResult'),
  CopyResultFailed: decodeTextTokenId('portal.dev.copyResultFailed'),
  NoCommandResult: decodeTextTokenId('portal.dev.noCommandResult'),
  LatestSnapshot: decodeTextTokenId('portal.dev.latestSnapshot'),
  CheckHealth: decodeTextTokenId('portal.dev.command.checkHealth'),
  GetLogSnapshot: decodeTextTokenId('portal.dev.command.getLogSnapshot'),
  EchoPortalPing: decodeTextTokenId('portal.dev.command.echoPortalPing'),
  GetWatcherStatus: decodeTextTokenId('portal.dev.command.getWatcherStatus'),
  GetActivityIngestStatus: decodeTextTokenId('portal.dev.command.getActivityIngestStatus'),
  GetRecentActivitySummary: decodeTextTokenId('portal.dev.command.getRecentActivitySummary'),
  GetBrowserEvidenceRecent: decodeTextTokenId('portal.dev.command.getBrowserEvidenceRecent'),
  PollManagedBrowserBridge: decodeTextTokenId('portal.dev.command.pollManagedBrowserBridge'),
  GetNetworkFlowReadModel: decodeTextTokenId('portal.dev.command.getNetworkFlowReadModel'),
  GetLocalAiRuntimeStatus: decodeTextTokenId('portal.dev.command.getLocalAiRuntimeStatus'),
  RootMissing: decodeTextTokenId('portal.dev.rootMissing'),
} as const;

export type PortalDevTextTokenValue = (typeof PortalDevTextToken)[keyof typeof PortalDevTextToken];

export const PortalDevText: Record<PortalDevTextTokenValue, DisplayText> = {
  [PortalDevTextToken.AppTitle]: decodeDisplayText('Ocentra Parent'),
  [PortalDevTextToken.Subtitle]: decodeDisplayText('Local agent WebSocket command and event scaffold'),
  [PortalDevTextToken.Reconnect]: decodeDisplayText('Reconnect'),
  [PortalDevTextToken.Overview]: decodeDisplayText('overview'),
  [PortalDevTextToken.Commands]: decodeDisplayText('commands'),
  [PortalDevTextToken.Events]: decodeDisplayText('events'),
  [PortalDevTextToken.Connected]: decodeDisplayText('Agent WebSocket connected'),
  [PortalDevTextToken.Unavailable]: decodeDisplayText('Agent WebSocket unavailable'),
  [PortalDevTextToken.AgentCommands]: decodeDisplayText('Agent commands'),
  [PortalDevTextToken.AgentEvents]: decodeDisplayText('Agent events'),
  [PortalDevTextToken.ActivityTimeline]: decodeDisplayText('Activity timeline'),
  [PortalDevTextToken.DeviceDiagnostics]: decodeDisplayText('Device diagnostics'),
  [PortalDevTextToken.DevLog]: decodeDisplayText('Service dev log'),
  [PortalDevTextToken.EvidenceStore]: decodeDisplayText('Evidence store'),
  [PortalDevTextToken.BrowserEvidence]: decodeDisplayText('Browser evidence'),
  [PortalDevTextToken.BrowserManagedStatus]: decodeDisplayText('Managed browser'),
  [PortalDevTextToken.NetworkFlow]: decodeDisplayText('Network flow'),
  [PortalDevTextToken.LiveActivity]: decodeDisplayText('Live activity'),
  [PortalDevTextToken.NoActivityStatus]: decodeDisplayText('Activity status has not been reported yet.'),
  [PortalDevTextToken.NoBrowserEvidence]: decodeDisplayText('No browser evidence rows returned yet.'),
  [PortalDevTextToken.NoBrowserManagedStatus]: decodeDisplayText('Managed browser status has not been reported yet.'),
  [PortalDevTextToken.NoDevLog]: decodeDisplayText('No service log snapshot has been reported yet.'),
  [PortalDevTextToken.NoEvents]: decodeDisplayText('No service events have been reported yet.'),
  [PortalDevTextToken.NoNetworkFlow]: decodeDisplayText('No network flow rows returned yet.'),
  [PortalDevTextToken.NoRecentActivity]: decodeDisplayText('No recent activity rows returned yet.'),
  [PortalDevTextToken.NotReported]: decodeDisplayText('Not reported'),
  [PortalDevTextToken.RecentActivity]: decodeDisplayText('Recent activity'),
  [PortalDevTextToken.CommandResult]: decodeDisplayText('Command result'),
  [PortalDevTextToken.CopyDiagnostics]: decodeDisplayText('Copy diagnostics'),
  [PortalDevTextToken.CopiedDiagnostics]: decodeDisplayText('Diagnostics copied'),
  [PortalDevTextToken.CopyDiagnosticsFailed]: decodeDisplayText('Diagnostics copy failed'),
  [PortalDevTextToken.CopyResult]: decodeDisplayText('Copy result'),
  [PortalDevTextToken.CopiedResult]: decodeDisplayText('Copied'),
  [PortalDevTextToken.CopyResultFailed]: decodeDisplayText('Copy failed'),
  [PortalDevTextToken.NoCommandResult]: decodeDisplayText('Run a command to see the latest response.'),
  [PortalDevTextToken.LatestSnapshot]: decodeDisplayText('Latest agent snapshot'),
  [PortalDevTextToken.CheckHealth]: decodeDisplayText('Check health'),
  [PortalDevTextToken.GetLogSnapshot]: decodeDisplayText('Get log snapshot'),
  [PortalDevTextToken.EchoPortalPing]: decodeDisplayText('Echo portal ping'),
  [PortalDevTextToken.GetWatcherStatus]: decodeDisplayText('Get watcher status'),
  [PortalDevTextToken.GetActivityIngestStatus]: decodeDisplayText('Get activity ingest status'),
  [PortalDevTextToken.GetRecentActivitySummary]: decodeDisplayText('Get recent activity summary'),
  [PortalDevTextToken.GetBrowserEvidenceRecent]: decodeDisplayText('Get browser evidence'),
  [PortalDevTextToken.PollManagedBrowserBridge]: decodeDisplayText('Poll managed browser bridge'),
  [PortalDevTextToken.GetNetworkFlowReadModel]: decodeDisplayText('Get network flow'),
  [PortalDevTextToken.GetLocalAiRuntimeStatus]: decodeDisplayText('Get local AI runtime'),
  [PortalDevTextToken.RootMissing]: decodeDisplayText('Portal root element is missing.'),
};

const MissingPortalDevTextTokenMessage = decodeDisplayText('Missing portal dev text token.');

export function resolvePortalDevText(token: PortalDevTextTokenValue): DisplayText {
  const text = PortalDevText[token];
  if (text === undefined) {
    throw new Error(MissingPortalDevTextTokenMessage);
  }
  return text;
}
