import { decodeDisplayText, decodeTextTokenId, type DisplayText } from './contracts';
import { PortalProductText, PortalProductTextToken } from './portal-product-text';

export const PortalDevTextToken = {
  AppTitle: decodeTextTokenId('portal.dev.appTitle'),
  Subtitle: decodeTextTokenId('portal.dev.subtitle'),
  Reconnect: decodeTextTokenId('portal.dev.reconnect'),
  ...PortalProductTextToken,
  AgentCommands: decodeTextTokenId('portal.dev.agentCommands'),
  AgentEvents: decodeTextTokenId('portal.dev.agentEvents'),
  ActivityTimeline: decodeTextTokenId('portal.dev.activityTimeline'),
  DeviceDiagnostics: decodeTextTokenId('portal.dev.deviceDiagnostics'),
  DevLog: decodeTextTokenId('portal.dev.devLog'),
  EvidenceStore: decodeTextTokenId('portal.dev.evidenceStore'),
  BrowserEvidence: decodeTextTokenId('portal.dev.browserEvidence'),
  BrowserIntervention: decodeTextTokenId('portal.dev.browserIntervention'),
  BrowserManagedStatus: decodeTextTokenId('portal.dev.browserManagedStatus'),
  ActivityMemoryGraph: decodeTextTokenId('portal.dev.activityMemoryGraph'),
  NetworkFlow: decodeTextTokenId('portal.dev.networkFlow'),
  PolicyPreview: decodeTextTokenId('portal.dev.policyPreview'),
  TrackingStatusSurface: decodeTextTokenId('portal.dev.trackingStatusSurface'),
  TrackingStatusSurfaceBody: decodeTextTokenId('portal.dev.trackingStatusSurfaceBody'),
  TrackingServiceReadModel: decodeTextTokenId('portal.dev.trackingServiceReadModel'),
  TrackingServiceDataCoverage: decodeTextTokenId('portal.dev.trackingServiceDataCoverage'),
  TrackingFirstTarget: decodeTextTokenId('portal.dev.trackingFirstTarget'),
  TrackingProofFixture: decodeTextTokenId('portal.dev.trackingProofFixture'),
  TrackingProofService: decodeTextTokenId('portal.dev.trackingProofService'),
  TrackingManualRequired: decodeTextTokenId('portal.dev.trackingManualRequired'),
  TrackingPhysicalDeviceRequired: decodeTextTokenId('portal.dev.trackingPhysicalDeviceRequired'),
  TrackingNoProductClaim: decodeTextTokenId('portal.dev.trackingNoProductClaim'),
  TrackingStateDisabled: decodeTextTokenId('portal.dev.trackingStateDisabled'),
  TrackingStatePermissionRequired: decodeTextTokenId('portal.dev.trackingStatePermissionRequired'),
  TrackingStateStale: decodeTextTokenId('portal.dev.trackingStateStale'),
  TrackingStateOffline: decodeTextTokenId('portal.dev.trackingStateOffline'),
  TrackingStateLowAccuracy: decodeTextTokenId('portal.dev.trackingStateLowAccuracy'),
  TrackingStateAmbiguousNearby: decodeTextTokenId('portal.dev.trackingStateAmbiguousNearby'),
  TrackingStateAlert: decodeTextTokenId('portal.dev.trackingStateAlert'),
  TrackingStateAcknowledged: decodeTextTokenId('portal.dev.trackingStateAcknowledged'),
  TrackingStateException: decodeTextTokenId('portal.dev.trackingStateException'),
  TrackingStateChildCheckIn: decodeTextTokenId('portal.dev.trackingStateChildCheckIn'),
  TrackingChildCheckInProofTitle: decodeTextTokenId('portal.dev.trackingChildCheckInProofTitle'),
  TrackingChildCheckInProofBody: decodeTextTokenId('portal.dev.trackingChildCheckInProofBody'),
  TrackingChildCheckInSafeAction: decodeTextTokenId('portal.dev.trackingChildCheckInSafeAction'),
  TrackingChildCheckInHelpAction: decodeTextTokenId('portal.dev.trackingChildCheckInHelpAction'),
  TrackingChildCheckInShareLocationAction: decodeTextTokenId('portal.dev.trackingChildCheckInShareLocationAction'),
  TrackingChildCheckInCallParentAction: decodeTextTokenId('portal.dev.trackingChildCheckInCallParentAction'),
  TrackingChildCheckInDeliveryBoundary: decodeTextTokenId('portal.dev.trackingChildCheckInDeliveryBoundary'),
  TrackingChildCheckInCopyBoundary: decodeTextTokenId('portal.dev.trackingChildCheckInCopyBoundary'),
  TrackingChildRuntimeUiProofTitle: decodeTextTokenId('portal.dev.trackingChildRuntimeUiProofTitle'),
  TrackingChildRuntimeUiProofBody: decodeTextTokenId('portal.dev.trackingChildRuntimeUiProofBody'),
  TrackingChildRuntimeDisclosure: decodeTextTokenId('portal.dev.trackingChildRuntimeDisclosure'),
  TrackingChildRuntimeSafeResponse: decodeTextTokenId('portal.dev.trackingChildRuntimeSafeResponse'),
  TrackingChildRuntimeHelpResponse: decodeTextTokenId('portal.dev.trackingChildRuntimeHelpResponse'),
  TrackingChildRuntimeLocationConsent: decodeTextTokenId('portal.dev.trackingChildRuntimeLocationConsent'),
  TrackingChildRuntimeBoundary: decodeTextTokenId('portal.dev.trackingChildRuntimeBoundary'),
  TrackingStateTemporaryLive: decodeTextTokenId('portal.dev.trackingStateTemporaryLive'),
  TrackingStateMissingDevice: decodeTextTokenId('portal.dev.trackingStateMissingDevice'),
  TrackingStateRetentionDeleted: decodeTextTokenId('portal.dev.trackingStateRetentionDeleted'),
  TrackingRetentionHistoryHidden: decodeTextTokenId('portal.dev.trackingRetentionHistoryHidden'),
  TrackingDeletedEvidenceNotRendered: decodeTextTokenId('portal.dev.trackingDeletedEvidenceNotRendered'),
  TrackingEvidenceContracts: decodeTextTokenId('portal.dev.trackingEvidenceContracts'),
  TrackingEvidenceUiFixture: decodeTextTokenId('portal.dev.trackingEvidenceUiFixture'),
  TrackingEvidencePhysicalMissing: decodeTextTokenId('portal.dev.trackingEvidencePhysicalMissing'),
  LiveActivity: decodeTextTokenId('portal.dev.liveActivity'),
  NoActivityStatus: decodeTextTokenId('portal.dev.noActivityStatus'),
  NoBrowserEvidence: decodeTextTokenId('portal.dev.noBrowserEvidence'),
  NoBrowserIntervention: decodeTextTokenId('portal.dev.noBrowserIntervention'),
  NoBrowserManagedStatus: decodeTextTokenId('portal.dev.noBrowserManagedStatus'),
  NoActivityMemoryGraph: decodeTextTokenId('portal.dev.noActivityMemoryGraph'),
  NoDevLog: decodeTextTokenId('portal.dev.noDevLog'),
  NoEvents: decodeTextTokenId('portal.dev.noEvents'),
  NoLocalAiRuntimeStatus: decodeTextTokenId('portal.dev.noLocalAiRuntimeStatus'),
  NoNetworkFlow: decodeTextTokenId('portal.dev.noNetworkFlow'),
  NoPolicyPreview: decodeTextTokenId('portal.dev.noPolicyPreview'),
  PolicyPreviewNoEnforcement: decodeTextTokenId('portal.dev.policyPreviewNoEnforcement'),
  NoRecentActivity: decodeTextTokenId('portal.dev.noRecentActivity'),
  NotReported: decodeTextTokenId('portal.dev.notReported'),
  RecentActivity: decodeTextTokenId('portal.dev.recentActivity'),
  CommandResult: decodeTextTokenId('portal.dev.commandResult'),
  CopyDiagnostics: decodeTextTokenId('portal.dev.copyDiagnostics'),
  CopiedDiagnostics: decodeTextTokenId('portal.dev.copiedDiagnostics'),
  CopyDiagnosticsFailed: decodeTextTokenId('portal.dev.copyDiagnosticsFailed'),
  CopyResult: decodeTextTokenId('portal.dev.copyResult'),
  CopiedResult: decodeTextTokenId('portal.dev.copiedResult'),
  CopyResultFailed: decodeTextTokenId('portal.dev.copyResultFailed'),
  NoCommandResult: decodeTextTokenId('portal.dev.noCommandResult'),
  LatestSnapshot: decodeTextTokenId('portal.dev.latestSnapshot'),
  CheckHealth: decodeTextTokenId('portal.dev.command.checkHealth'),
  GetLogSnapshot: decodeTextTokenId('portal.dev.command.getLogSnapshot'),
  EchoPortalPing: decodeTextTokenId('portal.dev.command.echoPortalPing'),
  GetWatcherStatus: decodeTextTokenId('portal.dev.command.getWatcherStatus'),
  GetActivityIngestStatus: decodeTextTokenId('portal.dev.command.getActivityIngestStatus'),
  GetRecentActivitySummary: decodeTextTokenId('portal.dev.command.getRecentActivitySummary'),
  GetBrowserEvidenceRecent: decodeTextTokenId('portal.dev.command.getBrowserEvidenceRecent'),
  GetActivityMemoryGraph: decodeTextTokenId('portal.dev.command.getActivityMemoryGraph'),
  GetActivityReportDaily: decodeTextTokenId('portal.dev.command.getActivityReportDaily'),
  GetActivityReportHistory: decodeTextTokenId('portal.dev.command.getActivityReportHistory'),
  GetActivityScreenReadModel: decodeTextTokenId('portal.dev.command.getActivityScreenReadModel'),
  GetActivityAppUseReadModel: decodeTextTokenId('portal.dev.command.getActivityAppUseReadModel'),
  GetActivityBrowserReadModel: decodeTextTokenId('portal.dev.command.getActivityBrowserReadModel'),
  GetActivityGamesReadModel: decodeTextTokenId('portal.dev.command.getActivityGamesReadModel'),
  GetActivityNetworkReadModel: decodeTextTokenId('portal.dev.command.getActivityNetworkReadModel'),
  GetBrowserInterventionReadModel: decodeTextTokenId('portal.dev.command.getBrowserInterventionReadModel'),
  PollManagedBrowserBridge: decodeTextTokenId('portal.dev.command.pollManagedBrowserBridge'),
  GetNetworkFlowReadModel: decodeTextTokenId('portal.dev.command.getNetworkFlowReadModel'),
  GetActivityTrackingReadModel: decodeTextTokenId('portal.dev.command.getActivityTrackingReadModel'),
  GetLocalAiRuntimeStatus: decodeTextTokenId('portal.dev.command.getLocalAiRuntimeStatus'),
  GetPolicyPreviewReadModel: decodeTextTokenId('portal.dev.command.getPolicyPreviewReadModel'),
  RootMissing: decodeTextTokenId('portal.dev.rootMissing'),
} as const;

export type PortalDevTextTokenValue = (typeof PortalDevTextToken)[keyof typeof PortalDevTextToken];

export const PortalDevText: Record<PortalDevTextTokenValue, DisplayText> = {
  [PortalDevTextToken.AppTitle]: decodeDisplayText('Ocentra Parent'),
  [PortalDevTextToken.Subtitle]: decodeDisplayText('Family safety for local child devices'),
  [PortalDevTextToken.Reconnect]: decodeDisplayText('Reconnect'),
  ...PortalProductText,
  [PortalDevTextToken.AgentCommands]: decodeDisplayText('Device controls'),
  [PortalDevTextToken.AgentEvents]: decodeDisplayText('Device audit'),
  [PortalDevTextToken.ActivityTimeline]: decodeDisplayText('Activity timeline'),
  [PortalDevTextToken.DeviceDiagnostics]: decodeDisplayText('Device diagnostics'),
  [PortalDevTextToken.DevLog]: decodeDisplayText('Service log'),
  [PortalDevTextToken.EvidenceStore]: decodeDisplayText('Evidence store'),
  [PortalDevTextToken.BrowserEvidence]: decodeDisplayText('Browser evidence'),
  [PortalDevTextToken.BrowserIntervention]: decodeDisplayText('Browser protection'),
  [PortalDevTextToken.BrowserManagedStatus]: decodeDisplayText('Managed browser'),
  [PortalDevTextToken.ActivityMemoryGraph]: decodeDisplayText('Memory links'),
  [PortalDevTextToken.NetworkFlow]: decodeDisplayText('Network activity'),
  [PortalDevTextToken.PolicyPreview]: decodeDisplayText('Policy decision'),
  [PortalDevTextToken.TrackingStatusSurface]: decodeDisplayText('Tracking status proof'),
  [PortalDevTextToken.TrackingStatusSurfaceBody]: decodeDisplayText('Location states are fixture proof only.'),
  [PortalDevTextToken.TrackingServiceReadModel]: decodeDisplayText('Service read model'),
  [PortalDevTextToken.TrackingServiceDataCoverage]: decodeDisplayText('Service data coverage'),
  [PortalDevTextToken.TrackingFirstTarget]: decodeDisplayText('First target'),
  [PortalDevTextToken.TrackingProofFixture]: decodeDisplayText('P1 fixture proof'),
  [PortalDevTextToken.TrackingProofService]: decodeDisplayText('P2 service proof'),
  [PortalDevTextToken.TrackingManualRequired]: decodeDisplayText('Manual proof required'),
  [PortalDevTextToken.TrackingPhysicalDeviceRequired]: decodeDisplayText('Physical device proof required'),
  [PortalDevTextToken.TrackingNoProductClaim]: decodeDisplayText('No product claim'),
  [PortalDevTextToken.TrackingStateDisabled]: decodeDisplayText('Tracking off'),
  [PortalDevTextToken.TrackingStatePermissionRequired]: decodeDisplayText('Permission required'),
  [PortalDevTextToken.TrackingStateStale]: decodeDisplayText('Stale last known'),
  [PortalDevTextToken.TrackingStateOffline]: decodeDisplayText('Offline last known'),
  [PortalDevTextToken.TrackingStateLowAccuracy]: decodeDisplayText('Low accuracy'),
  [PortalDevTextToken.TrackingStateAmbiguousNearby]: decodeDisplayText('Nearby place ambiguous'),
  [PortalDevTextToken.TrackingStateAlert]: decodeDisplayText('Policy alert'),
  [PortalDevTextToken.TrackingStateAcknowledged]: decodeDisplayText('Parent acknowledged'),
  [PortalDevTextToken.TrackingStateException]: decodeDisplayText('Exception active'),
  [PortalDevTextToken.TrackingStateChildCheckIn]: decodeDisplayText('Child check-in'),
  [PortalDevTextToken.TrackingChildCheckInProofTitle]: decodeDisplayText('Child check-in request'),
  [PortalDevTextToken.TrackingChildCheckInProofBody]: decodeDisplayText(
    'Your parent is asking you to check in. Are you safe?'
  ),
  [PortalDevTextToken.TrackingChildCheckInSafeAction]: decodeDisplayText("I'm safe"),
  [PortalDevTextToken.TrackingChildCheckInHelpAction]: decodeDisplayText('Need help'),
  [PortalDevTextToken.TrackingChildCheckInShareLocationAction]: decodeDisplayText('Share current location'),
  [PortalDevTextToken.TrackingChildCheckInCallParentAction]: decodeDisplayText('Call parent'),
  [PortalDevTextToken.TrackingChildCheckInDeliveryBoundary]: decodeDisplayText('Child-device delivery not proved'),
  [PortalDevTextToken.TrackingChildCheckInCopyBoundary]: decodeDisplayText('Calm copy, no accusation'),
  [PortalDevTextToken.TrackingChildRuntimeUiProofTitle]: decodeDisplayText('Child runtime UI proof'),
  [PortalDevTextToken.TrackingChildRuntimeUiProofBody]: decodeDisplayText(
    'Child sees a clear tracking request, safe response, help response, and location-share consent copy.'
  ),
  [PortalDevTextToken.TrackingChildRuntimeDisclosure]: decodeDisplayText('Tracking request disclosed'),
  [PortalDevTextToken.TrackingChildRuntimeSafeResponse]: decodeDisplayText('Safe response visible'),
  [PortalDevTextToken.TrackingChildRuntimeHelpResponse]: decodeDisplayText('Help response visible'),
  [PortalDevTextToken.TrackingChildRuntimeLocationConsent]: decodeDisplayText('Location share asks consent'),
  [PortalDevTextToken.TrackingChildRuntimeBoundary]: decodeDisplayText('Hosted proof only, not child-agent delivery'),
  [PortalDevTextToken.TrackingStateTemporaryLive]: decodeDisplayText('Temporary live'),
  [PortalDevTextToken.TrackingStateMissingDevice]: decodeDisplayText('Missing device'),
  [PortalDevTextToken.TrackingStateRetentionDeleted]: decodeDisplayText('Retention deleted'),
  [PortalDevTextToken.TrackingRetentionHistoryHidden]: decodeDisplayText('Deleted history hidden'),
  [PortalDevTextToken.TrackingDeletedEvidenceNotRendered]: decodeDisplayText('Deleted evidence not rendered'),
  [PortalDevTextToken.TrackingEvidenceContracts]: decodeDisplayText('Contract/runtime proof'),
  [PortalDevTextToken.TrackingEvidenceUiFixture]: decodeDisplayText('UI fixture proof'),
  [PortalDevTextToken.TrackingEvidencePhysicalMissing]: decodeDisplayText('Physical artifact missing'),
  [PortalDevTextToken.LiveActivity]: decodeDisplayText('Live activity'),
  [PortalDevTextToken.NoActivityStatus]: decodeDisplayText('Activity status has not been reported yet.'),
  [PortalDevTextToken.NoBrowserEvidence]: decodeDisplayText('No web evidence is available yet.'),
  [PortalDevTextToken.NoBrowserIntervention]: decodeDisplayText('No browser protection decision is available yet.'),
  [PortalDevTextToken.NoBrowserManagedStatus]: decodeDisplayText('Managed browser status has not been reported yet.'),
  [PortalDevTextToken.NoActivityMemoryGraph]: decodeDisplayText('No evidence-cited memory links are available yet.'),
  [PortalDevTextToken.NoDevLog]: decodeDisplayText('No service log snapshot has been reported yet.'),
  [PortalDevTextToken.NoEvents]: decodeDisplayText('No audit entries are available yet.'),
  [PortalDevTextToken.NoLocalAiRuntimeStatus]: decodeDisplayText('Local AI status has not been reported yet.'),
  [PortalDevTextToken.NoNetworkFlow]: decodeDisplayText('No network activity is available yet.'),
  [PortalDevTextToken.NoPolicyPreview]: decodeDisplayText('No policy decision has been reported yet.'),
  [PortalDevTextToken.PolicyPreviewNoEnforcement]: decodeDisplayText('Protection mode: advisory.'),
  [PortalDevTextToken.NoRecentActivity]: decodeDisplayText('No recent activity is available yet.'),
  [PortalDevTextToken.NotReported]: decodeDisplayText('Not reported'),
  [PortalDevTextToken.RecentActivity]: decodeDisplayText('Recent activity'),
  [PortalDevTextToken.CommandResult]: decodeDisplayText('Command result'),
  [PortalDevTextToken.CopyDiagnostics]: decodeDisplayText('Copy diagnostics'),
  [PortalDevTextToken.CopiedDiagnostics]: decodeDisplayText('Diagnostics copied'),
  [PortalDevTextToken.CopyDiagnosticsFailed]: decodeDisplayText('Diagnostics copy failed'),
  [PortalDevTextToken.CopyResult]: decodeDisplayText('Copy result'),
  [PortalDevTextToken.CopiedResult]: decodeDisplayText('Copied'),
  [PortalDevTextToken.CopyResultFailed]: decodeDisplayText('Copy failed'),
  [PortalDevTextToken.NoCommandResult]: decodeDisplayText('Choose a device control to see the latest response.'),
  [PortalDevTextToken.LatestSnapshot]: decodeDisplayText('Latest device snapshot'),
  [PortalDevTextToken.CheckHealth]: decodeDisplayText('Check health'),
  [PortalDevTextToken.GetLogSnapshot]: decodeDisplayText('Get log snapshot'),
  [PortalDevTextToken.EchoPortalPing]: decodeDisplayText('Send connectivity check'),
  [PortalDevTextToken.GetWatcherStatus]: decodeDisplayText('Refresh browser watcher'),
  [PortalDevTextToken.GetActivityIngestStatus]: decodeDisplayText('Refresh activity ingest'),
  [PortalDevTextToken.GetRecentActivitySummary]: decodeDisplayText('Refresh recent activity'),
  [PortalDevTextToken.GetBrowserEvidenceRecent]: decodeDisplayText('Refresh web evidence'),
  [PortalDevTextToken.GetActivityMemoryGraph]: decodeDisplayText('Refresh memory links'),
  [PortalDevTextToken.GetActivityReportDaily]: decodeDisplayText('Build daily activity report'),
  [PortalDevTextToken.GetActivityReportHistory]: decodeDisplayText('Refresh activity report history'),
  [PortalDevTextToken.GetActivityScreenReadModel]: decodeDisplayText('Refresh activity screen'),
  [PortalDevTextToken.GetActivityAppUseReadModel]: decodeDisplayText('Refresh activity app use'),
  [PortalDevTextToken.GetActivityBrowserReadModel]: decodeDisplayText('Refresh activity browser'),
  [PortalDevTextToken.GetActivityGamesReadModel]: decodeDisplayText('Refresh activity games'),
  [PortalDevTextToken.GetActivityNetworkReadModel]: decodeDisplayText('Refresh activity network'),
  [PortalDevTextToken.GetBrowserInterventionReadModel]: decodeDisplayText('Refresh browser protection'),
  [PortalDevTextToken.PollManagedBrowserBridge]: decodeDisplayText('Refresh managed browser'),
  [PortalDevTextToken.GetNetworkFlowReadModel]: decodeDisplayText('Refresh network activity'),
  [PortalDevTextToken.GetActivityTrackingReadModel]: decodeDisplayText('Refresh tracking status'),
  [PortalDevTextToken.GetLocalAiRuntimeStatus]: decodeDisplayText('Refresh local AI'),
  [PortalDevTextToken.GetPolicyPreviewReadModel]: decodeDisplayText('Refresh policy decision'),
  [PortalDevTextToken.RootMissing]: decodeDisplayText('Portal root element is missing.'),
};

const MissingPortalDevTextTokenMessage = decodeDisplayText('Missing portal dev text token.');

export function resolvePortalDevText(token: PortalDevTextTokenValue): DisplayText {
  const text = PortalDevText[token];
  if (text === undefined) {
    throw new Error(MissingPortalDevTextTokenMessage);
  }
  return text;
}
