import {
  SocialChildApprovalBlockUxText as SchemaDomainSocialChildApprovalBlockUxText,
  SocialChildApprovalBlockUxTextToken as SchemaDomainSocialChildApprovalBlockUxTextToken,
  resolveSocialChildApprovalBlockUxText as resolveSchemaDomainSocialChildApprovalBlockUxText,
  type SocialChildApprovalBlockUxTextTokenValue as SchemaDomainSocialChildApprovalBlockUxTextTokenValue,
} from '@ocentra-parent/schema-domain/text-social-ux';

export const SocialChildApprovalBlockUxTextToken = SchemaDomainSocialChildApprovalBlockUxTextToken;
export type SocialChildApprovalBlockUxTextTokenValue = SchemaDomainSocialChildApprovalBlockUxTextTokenValue;
export const SocialChildApprovalBlockUxText = SchemaDomainSocialChildApprovalBlockUxText;
export const resolveSocialChildApprovalBlockUxText = resolveSchemaDomainSocialChildApprovalBlockUxText;
