/* thin adapter over Rust-owned generated account identity authority contracts */

import * as Generated from './generated-account-identity-authority';

export const AccountIdentityProviderSchema = Generated.AccountIdentityProviderSchema;
export const AccountIdentityAuthoritySchemaVersionSchema = Generated.AccountIdentityAuthoritySchemaVersionSchema;
export const AccountIdentityMappingStatusSchema = Generated.AccountIdentityMappingStatusSchema;
export const AccountIdentityAccountStateSchema = Generated.AccountIdentityAccountStateSchema;
export const AccountIdentityMembershipStateSchema = Generated.AccountIdentityMembershipStateSchema;
export const AccountIdentityRoleSchema = Generated.AccountIdentityRoleSchema;
export const AccountIdentityDeviceTrustStateSchema = Generated.AccountIdentityDeviceTrustStateSchema;
export const AccountIdentitySessionFreshnessStateSchema = Generated.AccountIdentitySessionFreshnessStateSchema;
export const AccountIdentityPairingStateSchema = Generated.AccountIdentityPairingStateSchema;
export const AccountIdentityInstallStateSchema = Generated.AccountIdentityInstallStateSchema;
export const AccountIdentitySelectedRouteSchema = Generated.AccountIdentitySelectedRouteSchema;
export const AccountIdentityBindingLifecycleStateSchema = Generated.AccountIdentityBindingLifecycleStateSchema;
export const AccountIdentityBindingRevocationStateSchema = Generated.AccountIdentityBindingRevocationStateSchema;
export const AccountIdentityProviderSubjectSchema = Generated.AccountIdentityProviderSubjectSchema;
export const AccountIdentityMemberIdSchema = Generated.AccountIdentityMemberIdSchema;
export const AccountIdentitySessionIdSchema = Generated.AccountIdentitySessionIdSchema;
export const AccountIdentityChildDeviceIdSchema = Generated.AccountIdentityChildDeviceIdSchema;
export const AccountIdentityPairingIdSchema = Generated.AccountIdentityPairingIdSchema;
export const AccountIdentityInstallationIdSchema = Generated.AccountIdentityInstallationIdSchema;
export const AccountIdentityRouteIdSchema = Generated.AccountIdentityRouteIdSchema;
export const AccountIdentityProviderSubjectMappingSchema = Generated.AccountIdentityProviderSubjectMappingSchema;
export const AccountIdentityHouseholdChildDeviceBindingSchema =
  Generated.AccountIdentityHouseholdChildDeviceBindingSchema;
export const AccountIdentityAuthorityHandoffSchema = Generated.AccountIdentityAuthorityHandoffSchema;

export type AccountIdentityProvider = Generated.AccountIdentityProvider;
export type AccountIdentityAuthoritySchemaVersion = Generated.AccountIdentityAuthoritySchemaVersion;
export type AccountIdentityMappingStatus = Generated.AccountIdentityMappingStatus;
export type AccountIdentityAccountState = Generated.AccountIdentityAccountState;
export type AccountIdentityMembershipState = Generated.AccountIdentityMembershipState;
export type AccountIdentityRole = Generated.AccountIdentityRole;
export type AccountIdentityDeviceTrustState = Generated.AccountIdentityDeviceTrustState;
export type AccountIdentitySessionFreshnessState = Generated.AccountIdentitySessionFreshnessState;
export type AccountIdentityPairingState = Generated.AccountIdentityPairingState;
export type AccountIdentityInstallState = Generated.AccountIdentityInstallState;
export type AccountIdentitySelectedRouteKind = Generated.AccountIdentitySelectedRouteKind;
export type AccountIdentityBindingLifecycleState = Generated.AccountIdentityBindingLifecycleState;
export type AccountIdentityBindingRevocationState = Generated.AccountIdentityBindingRevocationState;
export type AccountIdentityProviderSubject = Generated.AccountIdentityProviderSubject;
export type AccountIdentityMemberId = Generated.AccountIdentityMemberId;
export type AccountIdentitySessionId = Generated.AccountIdentitySessionId;
export type AccountIdentityChildDeviceId = Generated.AccountIdentityChildDeviceId;
export type AccountIdentityPairingId = Generated.AccountIdentityPairingId;
export type AccountIdentityInstallationId = Generated.AccountIdentityInstallationId;
export type AccountIdentityRouteId = Generated.AccountIdentityRouteId;
export type AccountIdentityProviderSubjectMapping = Generated.AccountIdentityProviderSubjectMapping;
export type AccountIdentityHouseholdChildDeviceBinding = Generated.AccountIdentityHouseholdChildDeviceBinding;
export type AccountIdentityAuthorityHandoff = Generated.AccountIdentityAuthorityHandoff;
