import type { AppControlGuideCatalogSettingSeed } from './app-control-catalog-data';

// Generated from docs/app-control-capability-guide.md. Tests parse the source doc and prove parity.
export const AppControlGuideCatalogData0: readonly AppControlGuideCatalogSettingSeed[] = [
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-native-app',
    'Native App',
    1,
    'app-guide-core-terms-native-app-001',
    1,
    33,
    'Windows Win32 desktop app.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-native-app',
    'Native App',
    1,
    'app-guide-core-terms-native-app-002',
    2,
    34,
    'Windows packaged app or Microsoft Store app.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-native-app',
    'Native App',
    1,
    'app-guide-core-terms-native-app-003',
    3,
    35,
    'macOS app bundle.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-native-app',
    'Native App',
    1,
    'app-guide-core-terms-native-app-004',
    4,
    36,
    'Linux desktop app, package app, Flatpak, Snap, AppImage, or command-backed desktop entry.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-native-app',
    'Native App',
    1,
    'app-guide-core-terms-native-app-005',
    5,
    38,
    'Android package.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-native-app',
    'Native App',
    1,
    'app-guide-core-terms-native-app-006',
    6,
    39,
    'iOS or iPadOS application selected through Apple-approved controls.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-managed-app',
    'Managed App',
    2,
    'app-guide-core-terms-managed-app-001',
    7,
    52,
    'App installed by a supervised or managed device flow.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-managed-app',
    'Managed App',
    2,
    'app-guide-core-terms-managed-app-002',
    8,
    53,
    'App allowlisted or denylisted by an OS application-control policy.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-managed-app',
    'Managed App',
    2,
    'app-guide-core-terms-managed-app-003',
    9,
    54,
    'App represented by an opaque mobile platform token selected by a guardian.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-managed-app',
    'Managed App',
    2,
    'app-guide-core-terms-managed-app-004',
    10,
    55,
    'App launched through an Ocentra-controlled shortcut, launcher, or policy adapter.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-managed-app',
    'Managed App',
    2,
    'app-guide-core-terms-managed-app-005',
    11,
    57,
    'App process started by Ocentra and tracked with an owned process/session id.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-unmanaged-app',
    'Unmanaged App',
    3,
    'app-guide-core-terms-unmanaged-app-001',
    12,
    69,
    'A normal user-installed desktop app without Ocentra policy.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-unmanaged-app',
    'Unmanaged App',
    3,
    'app-guide-core-terms-unmanaged-app-002',
    13,
    70,
    'A portable executable.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-unmanaged-app',
    'Unmanaged App',
    3,
    'app-guide-core-terms-unmanaged-app-003',
    14,
    71,
    'A copied or renamed executable.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-unmanaged-app',
    'Unmanaged App',
    3,
    'app-guide-core-terms-unmanaged-app-004',
    15,
    72,
    'A helper process launched by a known app but not mapped to a supported app identity.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-unmanaged-app',
    'Unmanaged App',
    3,
    'app-guide-core-terms-unmanaged-app-005',
    16,
    74,
    'A mobile app that the platform does not expose through the approved parental, enterprise, or device-owner APIs.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-unmanaged-app',
    'Unmanaged App',
    3,
    'app-guide-core-terms-unmanaged-app-006',
    17,
    76,
    'An app running on an unsupported platform adapter.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-identity',
    'App Identity',
    5,
    'app-guide-core-terms-app-identity-001',
    18,
    96,
    'Package id, bundle id, AppUserModelID, package family name, desktop entry id, or application token.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-identity',
    'App Identity',
    5,
    'app-guide-core-terms-app-identity-002',
    19,
    98,
    'Executable path, file hash, publisher/signature, product name, or version.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-identity',
    'App Identity',
    5,
    'app-guide-core-terms-app-identity-003',
    20,
    99,
    'Process id and parent process id for a running observation.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-identity',
    'App Identity',
    5,
    'app-guide-core-terms-app-identity-004',
    21,
    100,
    'Window id and foreground state for active-use evidence.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-identity',
    'App Identity',
    5,
    'app-guide-core-terms-app-identity-005',
    22,
    101,
    'Installer/source reference and install state for inventory evidence.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-session-evidence',
    'App Session Evidence',
    6,
    'app-guide-core-terms-app-session-evidence-001',
    23,
    112,
    'App was observed.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-session-evidence',
    'App Session Evidence',
    6,
    'app-guide-core-terms-app-session-evidence-002',
    24,
    113,
    'App was running.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-session-evidence',
    'App Session Evidence',
    6,
    'app-guide-core-terms-app-session-evidence-003',
    25,
    114,
    'App was foreground-active where foreground proof exists.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-session-evidence',
    'App Session Evidence',
    6,
    'app-guide-core-terms-app-session-evidence-004',
    26,
    115,
    'App had a running or foreground duration inside a time window.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-session-evidence',
    'App Session Evidence',
    6,
    'app-guide-core-terms-app-session-evidence-005',
    27,
    116,
    'App identity, category, or unknown state was derived from specific evidence ids.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-control-action',
    'App Control Action',
    7,
    'app-guide-core-terms-app-control-action-001',
    28,
    128,
    'Launch.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-control-action',
    'App Control Action',
    7,
    'app-guide-core-terms-app-control-action-002',
    29,
    129,
    'Warn.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-control-action',
    'App Control Action',
    7,
    'app-guide-core-terms-app-control-action-003',
    30,
    130,
    'Ask parent.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-control-action',
    'App Control Action',
    7,
    'app-guide-core-terms-app-control-action-004',
    31,
    131,
    'Terminate owned or target process.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-control-action',
    'App Control Action',
    7,
    'app-guide-core-terms-app-control-action-005',
    32,
    132,
    'Suspend, hide, shield, or block app where the platform supports it.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-control-action',
    'App Control Action',
    7,
    'app-guide-core-terms-app-control-action-006',
    33,
    133,
    'Start, extend, expire, or roll back a time limit.',
  ],
  [
    'app-guide-core-terms',
    'Core Terms',
    1,
    'app-guide-core-terms-app-control-action',
    'App Control Action',
    7,
    'app-guide-core-terms-app-control-action-007',
    34,
    134,
    'Install or uninstall a managed app where the platform and custody model allow it.',
  ],
  [
    'app-guide-the-main-capability-truth',
    'The Main Capability Truth',
    2,
    'app-guide-the-main-capability-truth-the-main-capability-truth',
    'The Main Capability Truth',
    1,
    'app-guide-the-main-capability-truth-the-main-capability-truth-001',
    35,
    153,
    'Inventory layer: app appears installed, launchable, removable, managed, or unknown.',
  ],
  [
    'app-guide-the-main-capability-truth',
    'The Main Capability Truth',
    2,
    'app-guide-the-main-capability-truth-the-main-capability-truth',
    'The Main Capability Truth',
    1,
    'app-guide-the-main-capability-truth-the-main-capability-truth-002',
    36,
    155,
    'Runtime layer: process/package/app session is running, foreground, background, stale, or unavailable.',
  ],
  [
    'app-guide-the-main-capability-truth',
    'The Main Capability Truth',
    2,
    'app-guide-the-main-capability-truth-the-main-capability-truth',
    'The Main Capability Truth',
    1,
    'app-guide-the-main-capability-truth-the-main-capability-truth-003',
    37,
    157,
    'Duration layer: running and foreground time are derived from stored evidence, not portal refresh.',
  ],
  [
    'app-guide-the-main-capability-truth',
    'The Main Capability Truth',
    2,
    'app-guide-the-main-capability-truth-the-main-capability-truth',
    'The Main Capability Truth',
    1,
    'app-guide-the-main-capability-truth-the-main-capability-truth-004',
    38,
    159,
    'Policy layer: parent rule matches app identity, category, unknown state, schedule, budget, or approval state.',
  ],
  [
    'app-guide-the-main-capability-truth',
    'The Main Capability Truth',
    2,
    'app-guide-the-main-capability-truth-the-main-capability-truth',
    'The Main Capability Truth',
    1,
    'app-guide-the-main-capability-truth-the-main-capability-truth-005',
    39,
    161,
    'Enforcement layer: child-device adapter executes terminate, block, shield, suspend, hide, launch, install, uninstall, or time-limit actions.',
  ],
  [
    'app-guide-the-main-capability-truth',
    'The Main Capability Truth',
    2,
    'app-guide-the-main-capability-truth-the-main-capability-truth',
    'The Main Capability Truth',
    1,
    'app-guide-the-main-capability-truth-the-main-capability-truth-006',
    40,
    163,
    'Audit layer: every parent-visible claim carries evidence source, custody, policy decision, adapter result, and capability status.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-001',
    41,
    174,
    'Capability matrix row | Capability=Installed app inventory | Windows=Yes, partial by source | macOS=Yes, partial by source | Linux=Yes, partial by distro/desktop | Android=Yes, visibility-limited | iOS/iPadOS=Limited, token/MDM-managed paths | Required proof=Inventory adapter and source ids | Important limit=Inventory is not proof of current use.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-002',
    42,
    175,
    'Capability matrix row | Capability=Package/process identity | Windows=Strong for observed processes/packages | macOS=Strong for bundles/processes | Linux=Varies by package and desktop entry | Android=Strong package id when visible | iOS/iPadOS=Opaque tokens or managed app metadata | Required proof=Identity fields plus confidence | Important limit=Renames, helpers, and wrappers reduce confidence.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-003',
    43,
    176,
    'Capability matrix row | Capability=Running app observation | Windows=Yes | macOS=Yes | Linux=Yes | Android=Limited; usage/accessibility/DO paths | iOS/iPadOS=Limited through Screen Time/MDM signals | Required proof=Runtime observation evidence | Important limit=Background services may not equal user-facing app use.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-004',
    44,
    177,
    'Capability matrix row | Capability=Foreground app evidence | Windows=Yes | macOS=Permission-dependent | Linux=Desktop-environment-dependent | Android=Usage stats/accessibility-dependent | iOS/iPadOS=Device Activity thresholds, not raw focus | Required proof=Fresh foreground or activity evidence | Important limit=Foreground does not prove in-app content.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-005',
    45,
    178,
    'Capability matrix row | Capability=Running duration | Windows=Yes | macOS=Yes | Linux=Yes | Android=Usage-stat/session-dependent | iOS/iPadOS=Device Activity threshold-based | Required proof=Ordered observations/session model | Important limit=Gaps and restarts need stale handling.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-006',
    46,
    179,
    'Capability matrix row | Capability=Foreground duration | Windows=Yes | macOS=Permission-dependent | Linux=Desktop-environment-dependent | Android=Usage-stat/accessibility-dependent | iOS/iPadOS=Threshold/event-based | Required proof=Foreground observations or platform events | Important limit=Portal polling must not count time.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-007',
    47,
    180,
    'Capability matrix row | Capability=App categories | Windows=Derived from catalog/package/source | macOS=Derived from catalog/package/source | Linux=Derived from desktop/package metadata | Android=Package/category where exposed | iOS/iPadOS=Opaque category tokens through Screen Time | Required proof=Category source and confidence | Important limit=Category labels are policy inputs, not hidden blocks.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-008',
    48,
    181,
    'Capability matrix row | Capability=Launch app | Windows=Yes | macOS=Yes | Linux=Yes | Android=Yes, with package intents where allowed | iOS/iPadOS=Limited; open intents/managed flows | Required proof=Launch adapter result | Important limit=Launch does not imply ongoing control.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-009',
    49,
    182,
    'Capability matrix row | Capability=Terminate app | Windows=Yes, where permission permits | macOS=Yes, where permission permits | Linux=Yes, where permission permits | Android=Limited; device-owner/admin paths | iOS/iPadOS=No general third-party terminate | Required proof=Target identity and adapter result | Important limit=Unsaved data and race conditions need UX/audit.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-010',
    50,
    183,
    'Capability matrix row | Capability=Suspend/hide/shield app | Windows=App control policy dependent | macOS=MDM/profile dependent | Linux=Desktop/policy dependent | Android=Device owner/profile owner capable | iOS/iPadOS=Screen Time/Managed Settings capable | Required proof=Platform management proof | Important limit=Mobile support depends on entitlements/setup.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-011',
    51,
    184,
    'Capability matrix row | Capability=Block launch | Windows=AppLocker/WDAC or similar proof required | macOS=MDM/system policy proof required | Linux=Policy/permission proof required | Android=Device owner/profile owner capable | iOS/iPadOS=Screen Time shield or MDM restriction | Required proof=Pre-launch enforcement proof | Important limit=Current repo must not claim broad blocking without proof.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-012',
    52,
    185,
    'Capability matrix row | Capability=Time-limit app use | Windows=Yes for app sessions and owned terminate | macOS=Possible with platform proof | Linux=Possible with platform proof | Android=Usage/DevicePolicy/Accessibility proof | iOS/iPadOS=Device Activity threshold/shield path | Required proof=Timer plus action/result audit | Important limit=Needs fallback when action cannot enforce.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-013',
    53,
    186,
    'Capability matrix row | Capability=Install app | Windows=Installer/package manager path | macOS=Installer/MDM/package path | Linux=Package manager path | Android=Package installer/device owner/MDM | iOS/iPadOS=MDM/App Store managed distribution | Required proof=Install adapter/custody proof | Important limit=User consent, store policy, and signing matter.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-014',
    54,
    187,
    'Capability matrix row | Capability=Uninstall app | Windows=Installer/package manager path | macOS=Installer/MDM/package path | Linux=Package manager path | Android=Device owner/MDM/package path | iOS/iPadOS=MDM-managed app removal only | Required proof=Removal adapter/custody proof | Important limit=Personal app removal is often not available.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-015',
    55,
    188,
    'Capability matrix row | Capability=Child-facing message | Windows=Yes | macOS=Yes | Linux=Yes | Android=Yes | iOS/iPadOS=Shield UI where supported | Required proof=Local UI/notification/shield result | Important limit=Do not show parent diagnostics to child.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-016',
    56,
    189,
    'Capability matrix row | Capability=Parent report | Windows=Yes | macOS=Yes | Linux=Yes | Android=Yes, if evidence exists | iOS/iPadOS=Yes, token/capability-limited | Required proof=Stored evidence and custody labels | Important limit=Reports must distinguish raw vs redacted fields.',
  ],
  [
    'app-guide-capability-matrix',
    'Capability Matrix',
    3,
    'app-guide-capability-matrix-capability-matrix',
    'Capability Matrix',
    1,
    'app-guide-capability-matrix-capability-matrix-017',
    57,
    190,
    'Capability matrix row | Capability=Audit/retention | Windows=Yes | macOS=Yes | Linux=Yes | Android=Yes | iOS/iPadOS=Yes | Required proof=Journal/query retention policy | Important limit=Local-first custody remains default.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-001',
    58,
    201,
    'App display name where safe.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-002',
    59,
    202,
    'Package id, bundle id, package family name, desktop entry id, AppUserModelID, or app token.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-003',
    60,
    204,
    'Install source: installer, store package, app bundle, desktop entry, package manager, managed app distribution, or unknown.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-004',
    61,
    206,
    'Version, publisher, signature, hash, install path, and executable path where available and policy permits.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-005',
    62,
    208,
    'Category metadata from platform, catalog, desktop entry, app store metadata, or parent-maintained catalog.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-006',
    63,
    210,
    'Install, update, uninstall, hidden, suspended, shielded, managed, unmanaged, unsupported, or permission-limited state where the platform exposes it.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-007',
    64,
    215,
    'It is partial on every platform.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-008',
    65,
    216,
    'It can miss portable apps, per-user installs, wrapped apps, web apps, and apps hidden by platform privacy.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-009',
    66,
    218,
    'It can report apps that are installed but never used.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-010',
    67,
    219,
    'Mobile app lists can be package-visibility-limited, tokenized, supervised-only, or MDM-only.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-011',
    68,
    221,
    'Inventory should never be used as proof of activity without runtime evidence.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-001',
    69,
    227,
    'Process id, parent process id, executable path, process name, command-line handling status, user/session reference, and launch time where available.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-002',
    70,
    229,
    'Publisher/signature/hash metadata where safe.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-003',
    71,
    230,
    'Window id, title, active/foreground state, minimized/background state, and last foreground timestamp where available.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-004',
    72,
    232,
    'Sessionization into running and foreground durations.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-005',
    73,
    233,
    'Unknown, permission-limited, stale, unsupported, and adapter-error states.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-006',
    74,
    237,
    'Process names can be renamed.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-007',
    75,
    238,
    'Helper processes may not represent user-facing apps.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-008',
    76,
    239,
    'Foreground window title may contain sensitive text and may be stale or misleading.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-009',
    77,
    241,
    'Foreground proof does not reveal what happened inside the app.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-010',
    78,
    242,
    'Background process duration is not the same as child attention.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-011',
    79,
    243,
    'Elevated, protected, sandboxed, or cross-user processes can be unreadable or uncontrollable.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration',
    'Foreground Use And Duration',
    3,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration-001',
    80,
    250,
    'Which app is active now?',
  ],
];
