import type { AppControlGuideCatalogSettingSeed } from './app-control-catalog-data';

// Generated from docs/app-control-capability-guide.md. Tests parse the source doc and prove parity.
export const AppControlGuideCatalogData2: readonly AppControlGuideCatalogSettingSeed[] = [
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-002',
    161,
    451,
    'Show time remaining.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-003',
    162,
    452,
    'Show that parent approval is needed.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-004',
    163,
    453,
    'Show whether an app is paused, shielded, blocked, or closed by parent policy.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-005',
    164,
    454,
    'Offer ask-parent, request more time, or use allowed alternative where policy supports it.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-006',
    165,
    456,
    'Hide parent diagnostics, evidence ids, adapter errors, hashes, and internal policy fields from the child surface.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-001',
    166,
    475,
    'Installed/detectable app inventory.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-002',
    167,
    476,
    'Running now.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-003',
    168,
    477,
    'Foreground now.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-004',
    169,
    478,
    'Recent sessions.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-005',
    170,
    479,
    'Daily app/category rollups.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-006',
    171,
    480,
    'Time budgets and remaining time.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-007',
    172,
    481,
    'Unknown and permission-limited apps.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-008',
    173,
    482,
    'Policy decisions.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-009',
    174,
    483,
    'Enforcement actions and failures.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-010',
    175,
    484,
    'Approval requests and parent responses.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-011',
    176,
    488,
    'Evidence ids.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-012',
    177,
    489,
    'Source adapter.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-013',
    178,
    490,
    'Capability state.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-014',
    179,
    491,
    'Custody label.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-015',
    180,
    492,
    'Collection scope.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-016',
    181,
    493,
    'Retention policy.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-017',
    182,
    494,
    'Redaction status.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-018',
    183,
    495,
    'Policy version and decision id when policy contributed.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-019',
    184,
    496,
    'Adapter result id when enforcement contributed.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-020',
    185,
    500,
    'Raw process/window evidence should be retained for the shortest useful local audit window.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-021',
    186,
    502,
    'Daily rollups can be retained longer than raw observations if they are redacted.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-022',
    187,
    504,
    'Exact executable paths and window titles may be sensitive and should have narrower retention and reveal controls.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-023',
    188,
    506,
    'Ocentra-hosted storage is not the default child-activity store.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-024',
    189,
    507,
    'Parent export and deletion must preserve audit integrity while respecting retention settings.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-001',
    190,
    519,
    'Installed-app inventory from uninstall records, Start Menu shortcuts, Microsoft Store packages, known install paths, package query APIs, and executable metadata.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-002',
    191,
    522,
    'Process enumeration and process metadata.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-003',
    192,
    523,
    'Foreground-window observation.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-004',
    193,
    524,
    'Running and foreground sessionization.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-005',
    194,
    525,
    'Owned-process launch and termination.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-006',
    195,
    526,
    'Narrow target process termination after typed policy decisions.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-007',
    196,
    527,
    'Broad app control through AppLocker, WDAC/App Control for Business, managed installer policy, or equivalent only after explicit host proof.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-008',
    197,
    529,
    'Package lifecycle actions through installer/package mechanisms where product setup owns the package.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-009',
    198,
    534,
    'AppLocker/WDAC behavior depends on Windows edition, policy deployment, signing, administrator rights, audit/enforce mode, and reboot or refresh behavior.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-010',
    199,
    536,
    'Microsoft Store package identity and Win32 executable identity are different evidence families.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-011',
    200,
    538,
    'Blocking by path alone can be bypassed by copy/rename unless hash, signer, or managed installer proof is used.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-012',
    201,
    540,
    'The current roadmap distinguishes owned-process terminate and app time-limit proof from broad app blocking. Do not claim broad blocking until the adapter is proven.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-001',
    202,
    551,
    'Application bundle inventory.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-002',
    203,
    552,
    'Running process and window/frontmost app observation with the required permissions.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-003',
    204,
    554,
    'Launch Services, bundle identifiers, code signing, and app metadata.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-004',
    205,
    555,
    'MDM managed app distribution and restrictions where enrolled.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-005',
    206,
    556,
    'System Extensions, Endpoint Security, or Network Extension paths where entitled and deployed.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-006',
    207,
    558,
    'Managed browser/app controls through configuration profiles where supported.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-007',
    208,
    562,
    'Accessibility, Screen Recording, Full Disk Access, Endpoint Security, Network Extension, and MDM posture change what is possible.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-008',
    209,
    564,
    'Some controls require supervised or managed devices.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-009',
    210,
    565,
    'Do not assume Windows process control maps directly to macOS.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-001',
    211,
    575,
    'Desktop entries and menu categories.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-002',
    212,
    576,
    'Package manager inventory.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-003',
    213,
    577,
    'Flatpak, Snap, AppImage, or custom install metadata.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-004',
    214,
    578,
    'Process observation through OS process tables.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-005',
    215,
    579,
    'Foreground-window observation through X11, Wayland compositor protocols, or desktop-specific APIs where available.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-006',
    216,
    581,
    'Process termination where permission permits.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-007',
    217,
    582,
    'Policy controls through service, user session, package, desktop, firewall, or container mechanisms where proven.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-008',
    218,
    587,
    'Wayland commonly restricts global window inspection compared with X11.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-009',
    219,
    588,
    'Desktop entry category metadata is useful but not a complete app ontology.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-010',
    220,
    589,
    'Package managers differ by distro.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-011',
    221,
    590,
    'Broad app blocking should be treated as manual-required until a concrete adapter is proven on the target distro and desktop.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-001',
    222,
    600,
    'Package inventory through PackageManager subject to package visibility rules.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-002',
    223,
    601,
    'Usage events/statistics when the user grants Usage Access or the app has the required privileged context.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-003',
    224,
    603,
    'Foreground visibility through UsageStatsManager or Accessibility where approved and enabled.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-004',
    225,
    605,
    'DevicePolicyManager package hiding, suspension, permission policy, managed configuration, and package lifecycle control for device owner/profile owner contexts.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-005',
    226,
    608,
    'Managed Play or MDM package installation/removal where deployed.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-006',
    227,
    609,
    'Always-on VPN with lockdown for network mediation, separate from app foreground proof.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-007',
    228,
    614,
    'A normal Android app cannot generally control all other apps.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-008',
    229,
    615,
    'Package visibility rules can hide installed apps from inventory queries.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-009',
    230,
    616,
    'Usage access is permission-gated and can be revoked.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-010',
    231,
    617,
    'Accessibility is sensitive and must not be used as a stealth content capture path.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-011',
    232,
    619,
    'Device owner/profile owner changes the capability class and setup burden.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-012',
    233,
    620,
    'The roadmap currently treats Android package lifecycle proof as manual-required until real device artifacts exist.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-001',
    234,
    629,
    'Screen Time frameworks: Family Controls, Managed Settings, Device Activity.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-002',
    235,
    630,
    'Opaque selections for applications, categories, and web domains.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-003',
    236,
    631,
    'App/category shielding through Managed Settings.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-004',
    237,
    632,
    'Threshold/event monitoring through Device Activity.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-005',
    238,
    633,
    'MDM managed app install/removal and restrictions for enrolled devices.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-006',
    239,
    634,
    'Supervised-device restrictions where applicable.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-007',
    240,
    638,
    'Third-party apps do not get a general raw list of every installed app for parental control.',
  ],
];
