/* thin adapter over Rust-generated app-game preview/source-freshness rules */

import {
  AppGameSourceGatedPolicyPreviewReadModelNoClaimFlagsGenerated,
  AppGameSourceGatedPolicyPreviewReadModelProjectionStateGenerated,
  AppGameSourceGatedPolicyPreviewReadModelSensitiveBoundaryGenerated,
  RequiredAppGameSourceGatedPolicyPreviewReadModelNonClaimsGenerated,
} from './generated-app-game-preview-source-freshness-values';
import {
  appGameSourceGatedPolicyPreviewReadModelCountsMatchRowsGenerated,
  appGameSourceGatedPolicyPreviewReadModelHasNoRuntimeClaimsGenerated,
  appGameSourceGatedPolicyPreviewReadModelRowHasNoRuntimeClaimsGenerated,
  appGameSourceGatedPolicyPreviewReadModelRowMatchesGateStateGenerated,
  countAppGameSourceGatedPolicyPreviewProjectionStatesGenerated,
  countAppGameSourceGatedPolicyPreviewReadModelRowsGenerated,
  countAppGameSourceGatedPolicyPreviewRowsGenerated,
} from './generated-app-game-preview-source-freshness-rules';

export const AppGameSourceGatedPolicyPreviewReadModelProjectionState =
  AppGameSourceGatedPolicyPreviewReadModelProjectionStateGenerated;
export const AppGameSourceGatedPolicyPreviewReadModelSensitiveBoundary =
  AppGameSourceGatedPolicyPreviewReadModelSensitiveBoundaryGenerated;
export const RequiredAppGameSourceGatedPolicyPreviewReadModelNonClaims =
  RequiredAppGameSourceGatedPolicyPreviewReadModelNonClaimsGenerated;
export const AppGameSourceGatedPolicyPreviewReadModelNoClaimFlags =
  AppGameSourceGatedPolicyPreviewReadModelNoClaimFlagsGenerated;

export const appGameSourceGatedPolicyPreviewReadModelRowHasNoRuntimeClaims =
  appGameSourceGatedPolicyPreviewReadModelRowHasNoRuntimeClaimsGenerated;
export const appGameSourceGatedPolicyPreviewReadModelRowMatchesGateState =
  appGameSourceGatedPolicyPreviewReadModelRowMatchesGateStateGenerated;
export const countAppGameSourceGatedPolicyPreviewRows = countAppGameSourceGatedPolicyPreviewRowsGenerated;
export const countAppGameSourceGatedPolicyPreviewProjectionStates =
  countAppGameSourceGatedPolicyPreviewProjectionStatesGenerated;
export const countAppGameSourceGatedPolicyPreviewReadModelRows =
  countAppGameSourceGatedPolicyPreviewReadModelRowsGenerated;
export const appGameSourceGatedPolicyPreviewReadModelCountsMatchRows =
  appGameSourceGatedPolicyPreviewReadModelCountsMatchRowsGenerated;
export const appGameSourceGatedPolicyPreviewReadModelHasNoRuntimeClaims =
  appGameSourceGatedPolicyPreviewReadModelHasNoRuntimeClaimsGenerated;
