/* thin adapter over Rust-generated app-game timer/service-readiness rules */

import {
  AppGameSourceGatedPolicyPreviewTimerHandoffNoClaimFlagsGenerated,
  AppGameSourceGatedPolicyPreviewTimerHandoffStateGenerated,
  RequiredAppGameSourceGatedPolicyPreviewTimerHandoffNonClaimsGenerated,
} from './generated/app-game-timer-service-readiness-values';
import {
  appGameSourceGatedPolicyPreviewTimerHandoffCountsMatchGenerated,
  appGameSourceGatedPolicyPreviewTimerHandoffHasNoRuntimeClaimsGenerated,
  appGameSourceGatedPolicyPreviewTimerHandoffStateForProjectionGenerated,
  appGameSourceGatedPolicyPreviewTimerStateMatchesProjectionGenerated,
  countAppGameSourceGatedPolicyPreviewTimerHandoffRowsGenerated,
} from './generated/app-game-timer-service-readiness-rules';

export const AppGameSourceGatedPolicyPreviewTimerHandoffState =
  AppGameSourceGatedPolicyPreviewTimerHandoffStateGenerated;
export const RequiredAppGameSourceGatedPolicyPreviewTimerHandoffNonClaims =
  RequiredAppGameSourceGatedPolicyPreviewTimerHandoffNonClaimsGenerated;
export const AppGameSourceGatedPolicyPreviewTimerHandoffNoClaimFlags =
  AppGameSourceGatedPolicyPreviewTimerHandoffNoClaimFlagsGenerated;
export const appGameSourceGatedPolicyPreviewTimerStateMatchesProjection =
  appGameSourceGatedPolicyPreviewTimerStateMatchesProjectionGenerated;
export const appGameSourceGatedPolicyPreviewTimerHandoffStateForProjection =
  appGameSourceGatedPolicyPreviewTimerHandoffStateForProjectionGenerated;
export const countAppGameSourceGatedPolicyPreviewTimerHandoffRows =
  countAppGameSourceGatedPolicyPreviewTimerHandoffRowsGenerated;
export const appGameSourceGatedPolicyPreviewTimerHandoffCountsMatch =
  appGameSourceGatedPolicyPreviewTimerHandoffCountsMatchGenerated;
export const appGameSourceGatedPolicyPreviewTimerHandoffHasNoRuntimeClaims =
  appGameSourceGatedPolicyPreviewTimerHandoffHasNoRuntimeClaimsGenerated;
