/* thin adapter over Rust-generated app-game timer/service-readiness rules */

import {
  AppGameSourceGatedPolicyPreviewTimerRuntimeReadinessNoClaimFlagsGenerated,
  AppGameSourceGatedPolicyPreviewTimerRuntimeReadinessStateGenerated,
  RequiredAppGameSourceGatedPolicyPreviewTimerRuntimeReadinessNonClaimsGenerated,
} from './generated-app-game-timer-service-readiness-values';
import {
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessCountsMatchGenerated,
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessHasNoRuntimeClaimsGenerated,
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessMatchesStatusGenerated,
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessRequiredProofRefsGenerated,
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessStateForStatusGenerated,
  countAppGameSourceGatedPolicyPreviewTimerRuntimeReadinessRowsGenerated,
} from './generated-app-game-timer-service-readiness-rules';

export const AppGameSourceGatedPolicyPreviewTimerRuntimeReadinessState =
  AppGameSourceGatedPolicyPreviewTimerRuntimeReadinessStateGenerated;
export const RequiredAppGameSourceGatedPolicyPreviewTimerRuntimeReadinessNonClaims =
  RequiredAppGameSourceGatedPolicyPreviewTimerRuntimeReadinessNonClaimsGenerated;
export const AppGameSourceGatedPolicyPreviewTimerRuntimeReadinessNoClaimFlags =
  AppGameSourceGatedPolicyPreviewTimerRuntimeReadinessNoClaimFlagsGenerated;
export const appGameSourceGatedPolicyPreviewTimerRuntimeReadinessMatchesStatus =
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessMatchesStatusGenerated;
export const appGameSourceGatedPolicyPreviewTimerRuntimeReadinessStateForStatus =
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessStateForStatusGenerated;
export const countAppGameSourceGatedPolicyPreviewTimerRuntimeReadinessRows =
  countAppGameSourceGatedPolicyPreviewTimerRuntimeReadinessRowsGenerated;
export const appGameSourceGatedPolicyPreviewTimerRuntimeReadinessRequiredProofRefs =
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessRequiredProofRefsGenerated;
export const appGameSourceGatedPolicyPreviewTimerRuntimeReadinessCountsMatch =
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessCountsMatchGenerated;
export const appGameSourceGatedPolicyPreviewTimerRuntimeReadinessHasNoRuntimeClaims =
  appGameSourceGatedPolicyPreviewTimerRuntimeReadinessHasNoRuntimeClaimsGenerated;
