import {
  AppGamePolicyAuditRefSchema as GeneratedAppGamePolicyAuditRefSchema,
  AppGamePolicyAuthorityRefSchema as GeneratedAppGamePolicyAuthorityRefSchema,
  AppGamePolicyCapabilityRefSchema as GeneratedAppGamePolicyCapabilityRefSchema,
  AppGamePolicyCompileRequestIdSchema as GeneratedAppGamePolicyCompileRequestIdSchema,
  AppGamePolicyCompileRequestSchema as GeneratedAppGamePolicyCompileRequestSchema,
  AppGamePolicyCompiledDecisionIdSchema as GeneratedAppGamePolicyCompiledDecisionIdSchema,
  AppGamePolicyCompiledDecisionSchema as GeneratedAppGamePolicyCompiledDecisionSchema,
  AppGamePolicyCompilerAuthorityRefSchema as GeneratedAppGamePolicyCompilerAuthorityRefSchema,
  AppGamePolicyCompilerAuthorityStateSchema as GeneratedAppGamePolicyCompilerAuthorityStateSchema,
  AppGamePolicyCompilerCapabilityRefSchema as GeneratedAppGamePolicyCompilerCapabilityRefSchema,
  AppGamePolicyCompilerCapabilityStateSchema as GeneratedAppGamePolicyCompilerCapabilityStateSchema,
  AppGamePolicyCompilerEvidenceSchema as GeneratedAppGamePolicyCompilerEvidenceSchema,
  AppGamePolicyCompilerEvidenceStateSchema as GeneratedAppGamePolicyCompilerEvidenceStateSchema,
  AppGamePolicyCompilerOutcomeStateSchema as GeneratedAppGamePolicyCompilerOutcomeStateSchema,
  AppGamePolicyCompilerProofKindSchema as GeneratedAppGamePolicyCompilerProofKindSchema,
  AppGamePolicyCompilerRejectionReasonSchema as GeneratedAppGamePolicyCompilerRejectionReasonSchema,
  AppGamePolicyCompilerRequestedActionSchema as GeneratedAppGamePolicyCompilerRequestedActionSchema,
  AppGamePolicyCompilerTargetSchema as GeneratedAppGamePolicyCompilerTargetSchema,
  AppGamePolicyLocalUserRefSchema as GeneratedAppGamePolicyLocalUserRefSchema,
  AppGamePolicyTargetKindSchema as GeneratedAppGamePolicyTargetKindSchema,
  AppGamePolicyTargetRefSchema as GeneratedAppGamePolicyTargetRefSchema,
  type AppGamePolicyCompileRequest as GeneratedAppGamePolicyCompileRequest,
  type AppGamePolicyCompiledDecision as GeneratedAppGamePolicyCompiledDecision,
  type AppGamePolicyCompilerEvidence as GeneratedAppGamePolicyCompilerEvidence,
  type AppGamePolicyCompilerTarget as GeneratedAppGamePolicyCompilerTarget,
  type AppGamePolicyTargetKind as GeneratedAppGamePolicyTargetKind,
} from './generated-app-game-policy-target-compiler';

export const AppGamePolicyCompileRequestIdSchema = GeneratedAppGamePolicyCompileRequestIdSchema;
export const AppGamePolicyCompiledDecisionIdSchema = GeneratedAppGamePolicyCompiledDecisionIdSchema;
export const AppGamePolicyTargetRefSchema = GeneratedAppGamePolicyTargetRefSchema;
export const AppGamePolicyLocalUserRefSchema = GeneratedAppGamePolicyLocalUserRefSchema;
export const AppGamePolicyCapabilityRefSchema = GeneratedAppGamePolicyCapabilityRefSchema;
export const AppGamePolicyAuthorityRefSchema = GeneratedAppGamePolicyAuthorityRefSchema;
export const AppGamePolicyAuditRefSchema = GeneratedAppGamePolicyAuditRefSchema;

export const AppGamePolicyTargetKindSchema = GeneratedAppGamePolicyTargetKindSchema;
export const AppGamePolicyCompilerProofKindSchema = GeneratedAppGamePolicyCompilerProofKindSchema;
export const AppGamePolicyCompilerEvidenceStateSchema = GeneratedAppGamePolicyCompilerEvidenceStateSchema;
export const AppGamePolicyCompilerCapabilityStateSchema = GeneratedAppGamePolicyCompilerCapabilityStateSchema;
export const AppGamePolicyCompilerAuthorityStateSchema = GeneratedAppGamePolicyCompilerAuthorityStateSchema;
export const AppGamePolicyCompilerRequestedActionSchema = GeneratedAppGamePolicyCompilerRequestedActionSchema;
export const AppGamePolicyCompilerOutcomeStateSchema = GeneratedAppGamePolicyCompilerOutcomeStateSchema;
export const AppGamePolicyCompilerRejectionReasonSchema = GeneratedAppGamePolicyCompilerRejectionReasonSchema;

export const AppGamePolicyCompilerTargetSchema = GeneratedAppGamePolicyCompilerTargetSchema;
export const AppGamePolicyCompilerEvidenceSchema = GeneratedAppGamePolicyCompilerEvidenceSchema;
export const AppGamePolicyCompilerCapabilityRefSchema = GeneratedAppGamePolicyCompilerCapabilityRefSchema;
export const AppGamePolicyCompilerAuthorityRefSchema = GeneratedAppGamePolicyCompilerAuthorityRefSchema;
export const AppGamePolicyCompileRequestSchema = GeneratedAppGamePolicyCompileRequestSchema;
export const AppGamePolicyCompiledDecisionSchema = GeneratedAppGamePolicyCompiledDecisionSchema;

export type AppGamePolicyTargetKind = GeneratedAppGamePolicyTargetKind;
export type AppGamePolicyCompilerTarget = GeneratedAppGamePolicyCompilerTarget;
export type AppGamePolicyCompilerEvidence = GeneratedAppGamePolicyCompilerEvidence;
export type AppGamePolicyCompileRequest = GeneratedAppGamePolicyCompileRequest;
export type AppGamePolicyCompiledDecision = GeneratedAppGamePolicyCompiledDecision;
