export const AppControlCatalogSettingSeedsB = [
  [
    'runtime-evidence',
    'Runtime evidence',
    'audit',
    'data-minimization',
    'Data minimization',
    'evidence.neverCollect',
    'multi-choice',
    'What must app controls never collect?',
    '/appPolicy/evidence/neverCollect',
    'already-represented',
    'rust-parent-runtime',
    'protected',
    'privacy and redaction boundary',
    'App evidence does not prove content, keystrokes, screenshots, or chat text.',
    'Exclude raw sensitive fields and keep reports evidence-reference based.',
    [
      'screen-contents',
      'screenshots',
      'keystrokes',
      'chat-content',
      'voice-content',
      'app-internal-documents',
      'launcher-credentials',
      'decrypted-network-payload',
      'raw-command-line-with-secrets',
    ],
    [
      'screen-contents',
      'screenshots',
      'keystrokes',
      'chat-content',
      'voice-content',
      'app-internal-documents',
      'launcher-credentials',
      'decrypted-network-payload',
    ],
  ],
  [
    'app-rules',
    'App rules',
    'rules',
    'rule-targets',
    'Rule targets',
    'rules.allowedTargetTypes',
    'multi-choice',
    'What app targets should rules match?',
    '/appPolicy/rules/allowedTargetTypes',
    'proof-required',
    'child-agent',
    'protected',
    'typed app identity and category match strategy',
    'Unknown, helper, wrapper, and renamed apps require honest confidence state.',
    'Keep exact app control disabled when targets cannot be matched deterministically.',
    [
      'app-ref',
      'app-category',
      'package-id',
      'bundle-id',
      'application-token',
      'executable-identity',
      'publisher-signature',
      'unknown-app',
      'managed-app-state',
      'app-session',
      'capability-state',
    ],
    ['app-ref', 'app-category', 'executable-identity', 'unknown-app', 'app-session', 'capability-state'],
  ],
  [
    'app-rules',
    'App rules',
    'rules',
    'unknown-apps',
    'Unknown apps',
    'rules.defaultUnknownRule',
    'single-choice',
    'Default rule for unknown apps?',
    '/appPolicy/rules/defaultUnknownRule',
    'proof-required',
    'child-agent',
    'protected',
    'unknown app fallback policy',
    'Unknown remains unknown until adapter evidence maps it confidently.',
    'Use ask, warn, or limit fallback before unsupported broad blocking.',
    ['allow', 'observe', 'warn', 'ask-first-run', 'limit', 'block-if-supported'],
    'ask-first-run',
  ],
  [
    'app-rules',
    'App rules',
    'rules',
    'rule-targets',
    'Rule targets',
    'rules.matchConfidenceRequired',
    'single-choice',
    'How strong must an app match be before strict action?',
    '/appPolicy/rules/matchConfidenceRequired',
    'already-represented',
    'rust-parent-runtime',
    'available',
    'app identity confidence threshold',
    'Strict action requires deterministic or approved app identity proof.',
    'Fall back to parent approval when confidence is below threshold.',
    ['any-candidate', 'catalog-confidence-high', 'deterministic-or-parent-approved', 'managed-device-proof'],
    'deterministic-or-parent-approved',
  ],
  [
    'budgets',
    'App time limits',
    'schedule',
    'time-budgets',
    'Time budgets',
    'budgets.enabled',
    'toggle',
    'Enable app time budgets?',
    '/appPolicy/budgets/enabled',
    'already-represented',
    'child-agent',
    'available',
    'local timer state and app-session evidence',
    'Budgets need child-agent timer state, not portal-rendered time.',
    'Disable app budgets when no runtime evidence source is available.',
    [],
    true,
  ],
  [
    'budgets',
    'App time limits',
    'schedule',
    'time-budgets',
    'Time budgets',
    'budgets.defaultDailyMinutes',
    'number',
    'Default daily app time limit in minutes?',
    '/appPolicy/budgets/defaultDailyMinutes',
    'needs-effect-wiring',
    'child-agent',
    'available',
    'daily app budget policy value',
    'Timer recovery and audit are child-agent responsibilities.',
    'Reject non-positive or non-finite budget values.',
    [],
    60,
  ],
  [
    'budgets',
    'App time limits',
    'schedule',
    'time-budgets',
    'Time budgets',
    'budgets.whenExhausted',
    'single-choice',
    'What happens when app time runs out?',
    '/appPolicy/budgets/whenExhausted',
    'proof-required',
    'child-agent',
    'protected',
    'time-limit action adapter result',
    'Terminate, shield, or block after budget requires platform proof.',
    'Use ask or warn fallback when the strict action is unsupported.',
    ['observe', 'warn', 'ask', 'terminate-if-supported', 'shield-if-supported', 'block-if-supported'],
    'ask',
  ],
  [
    'enforcement',
    'App enforcement',
    'enforcement',
    'strict-actions',
    'Strict actions',
    'enforcement.allowedActions',
    'multi-choice',
    'Which app enforcement actions may run?',
    '/appPolicy/enforcement/allowedActions',
    'manual-required',
    'os-adapter',
    'manual-required',
    'per-platform enforcement adapter capability',
    'Broad app blocking remains manual-required until a real adapter proves it.',
    'Allow only warn, ask, owned-process terminate, and time-limit paths until stricter proof exists.',
    [
      'warn',
      'ask-parent',
      'owned-process-terminate',
      'target-process-terminate',
      'block-launch',
      'shield-app',
      'suspend-package',
      'hide-package',
      'time-limit',
      'managed-install',
      'managed-uninstall',
    ],
    ['warn', 'ask-parent', 'owned-process-terminate', 'time-limit'],
  ],
  [
    'enforcement',
    'App enforcement',
    'enforcement',
    'strict-actions',
    'Strict actions',
    'enforcement.strictActionFallback',
    'single-choice',
    'What if a strict app action is unsupported?',
    '/appPolicy/enforcement/strictActionFallback',
    'already-represented',
    'rust-parent-runtime',
    'available',
    'strict action fallback policy',
    'Unsupported strict actions must surface as unavailable or parent-visible fallback.',
    'Never silently claim enforcement when adapter proof is missing.',
    [
      'allow-and-report-unavailable',
      'observe-and-report-unavailable',
      'warn-and-report-unavailable',
      'parent-request-report-unavailable',
      'block-until-ready',
    ],
    'parent-request-report-unavailable',
  ],
] as const;
