export const AppControlCatalogSettingSeedsA = [
  [
    'app-management',
    'App management',
    'rules',
    'app-management-defaults',
    'Default posture',
    'app.enabled',
    'toggle',
    'Enable app management?',
    '/appPolicy/enabled',
    'already-represented',
    'rust-parent-runtime',
    'available',
    null,
    null,
    'Native app controls stay disabled until a parent enables this policy document.',
    [],
    false,
  ],
  [
    'app-management',
    'App management',
    'rules',
    'app-management-defaults',
    'Default posture',
    'app.defaultPosture',
    'single-choice',
    'What should happen to app activity?',
    '/appPolicy/defaultPosture',
    'proof-required',
    'child-agent',
    'protected',
    'runtime app evidence plus strict-action capability proof',
    'Blocking is product-true only when the target platform adapter proves it.',
    'Degrade block posture to ask, warn, or unavailable reporting when broad app blocking is not proven.',
    [
      { value: 'allow', label: 'Allow', meaning: 'App activity is allowed unless a more specific rule changes it.' },
      {
        value: 'observe',
        label: 'Observe',
        meaning: 'App activity is allowed and decisions are report-only.',
      },
      { value: 'warn', label: 'Warn', meaning: 'Matching app activity warns the child and records events.' },
      { value: 'ask', label: 'Ask', meaning: 'Matching app activity needs parent approval.' },
      { value: 'limit', label: 'Limit', meaning: 'App activity is allowed inside configured schedules and budgets.' },
      {
        value: 'block',
        label: 'Block',
        meaning: 'Blocking applies only when platform capability proof exists.',
      },
    ],
    'observe',
  ],
  [
    'app-management',
    'App management',
    'rules',
    'app-management-defaults',
    'Default posture',
    'app.managementMode',
    'single-choice',
    'How should app management run on this device?',
    '/appPolicy/managementMode',
    'already-represented',
    'child-agent',
    'available',
    'local child-agent or LAN service route',
    'Portal authoring alone must not claim runtime enforcement.',
    'Show authoring-only or unavailable when no child-agent route exists.',
    ['local-child-agent', 'lan-live', 'authoring-only', 'unavailable'],
    'local-child-agent',
  ],
  [
    'inventory',
    'Installed apps',
    'evidence',
    'inventory-sources',
    'Inventory sources',
    'inventory.mode',
    'single-choice',
    'How should installed app inventory be used?',
    '/appPolicy/inventory/mode',
    'needs-effect-wiring',
    'child-agent',
    'permission-limited',
    'installed app inventory adapter',
    'Inventory is not proof of current use.',
    'Keep app activity unknown when inventory is missing or stale.',
    ['disabled', 'reports-only', 'use-for-matching-and-reports', 'required-for-strict-rules'],
    'use-for-matching-and-reports',
  ],
  [
    'inventory',
    'Installed apps',
    'evidence',
    'inventory-sources',
    'Inventory sources',
    'inventory.sources',
    'multi-choice',
    'Which app inventory sources are allowed?',
    '/appPolicy/inventory/sources',
    'permission-limited',
    'os-adapter',
    'permission-limited',
    'platform inventory source visibility',
    'Portable, privacy-hidden, and mobile-tokenized apps may be absent.',
    'Do not infer unlisted apps are absent or safe.',
    [
      'os-installed-apps',
      'desktop-shortcuts',
      'store-packages',
      'package-manager',
      'managed-device-apps',
      'screen-time-tokens',
      'executable-metadata',
      'parent-catalog',
    ],
    ['os-installed-apps', 'desktop-shortcuts', 'store-packages', 'executable-metadata', 'parent-catalog'],
  ],
  [
    'inventory',
    'Installed apps',
    'evidence',
    'inventory-identity',
    'Identity strategy',
    'inventory.identityFields',
    'multi-choice',
    'Which identity fields may app rules use?',
    '/appPolicy/inventory/identityFields',
    'proof-required',
    'child-agent',
    'protected',
    'typed app identity evidence',
    'No single identity field proves an app on every platform.',
    'Keep unknown identity state when deterministic proof is unavailable.',
    [
      'package-id',
      'bundle-id',
      'app-user-model-id',
      'desktop-entry-id',
      'application-token',
      'executable-path',
      'publisher-signature',
      'file-hash',
      'display-name',
      'parent-label',
    ],
    ['package-id', 'bundle-id', 'app-user-model-id', 'executable-path', 'publisher-signature', 'file-hash'],
  ],
  [
    'inventory',
    'Installed apps',
    'rules',
    'inventory-identity',
    'Identity strategy',
    'inventory.unknownHandling',
    'single-choice',
    'What should happen when an app cannot be identified?',
    '/appPolicy/inventory/unknownHandling',
    'already-represented',
    'rust-parent-runtime',
    'available',
    'unknown app policy state',
    'Unknown apps must remain labeled unknown.',
    'Never promote unknown apps to known, risky, blocked, or game without proof.',
    ['allow', 'observe', 'warn', 'ask', 'count-under-unknown-budget', 'block-if-supported'],
    'observe',
  ],
  [
    'runtime-evidence',
    'Runtime evidence',
    'evidence',
    'runtime-sources',
    'Runtime sources',
    'evidence.runtimeSources',
    'multi-choice',
    'Which runtime evidence sources may be used?',
    '/appPolicy/evidence/runtimeSources',
    'permission-required',
    'os-adapter',
    'permission-required',
    'process, foreground, usage, or managed-device adapter permissions',
    'Foreground evidence and mobile usage visibility are platform-permission dependent.',
    'Report unavailable instead of counting portal polling as child activity.',
    [
      'process-snapshot',
      'process-start-exit',
      'foreground-window',
      'usage-stats',
      'device-activity',
      'managed-device-state',
      'accessibility-approved-state',
      'app-session-summary',
    ],
    ['process-snapshot', 'process-start-exit', 'foreground-window', 'app-session-summary'],
  ],
  [
    'runtime-evidence',
    'Runtime evidence',
    'evidence',
    'runtime-proof',
    'Runtime proof',
    'evidence.requiredProof',
    'single-choice',
    'What proof is enough for app rules?',
    '/appPolicy/evidence/requiredProof',
    'proof-required',
    'child-agent',
    'protected',
    'fresh app evidence reference',
    'Inventory-only proof cannot justify strict runtime action.',
    'Degrade strict actions until fresh runtime or managed-device proof exists.',
    [
      'inventory-only',
      'process-running',
      'foreground-window',
      'fresh-app-session',
      'platform-usage-event',
      'managed-device-state',
    ],
    'fresh-app-session',
  ],
  [
    'runtime-evidence',
    'Runtime evidence',
    'schedule',
    'duration-proof',
    'Duration proof',
    'evidence.durationMode',
    'single-choice',
    'Which duration should time budgets count?',
    '/appPolicy/evidence/durationMode',
    'proof-required',
    'child-agent',
    'protected',
    'ordered runtime or foreground app-session evidence',
    'Portal refresh cadence must not count as child activity.',
    'Treat observation gaps and restarts as gaps unless replay or platform events prove continuity.',
    ['running-time', 'foreground-time', 'platform-usage-time', 'manual-review-only'],
    'foreground-time',
  ],
  [
    'runtime-evidence',
    'Runtime evidence',
    'evidence',
    'runtime-proof',
    'Runtime proof',
    'evidence.whenProofUnavailable',
    'single-choice',
    'What if app proof is unavailable?',
    '/appPolicy/evidence/whenProofUnavailable',
    'already-represented',
    'rust-parent-runtime',
    'available',
    'fallback policy state',
    'Unavailable proof is a parent-visible state, not a hidden allow or block.',
    'Mark unavailable when proof cannot support the selected strict action.',
    ['allow', 'observe', 'warn', 'ask', 'block-until-ready', 'mark-unavailable'],
    'mark-unavailable',
  ],
] as const;
