/* thin adapter over Rust-generated app-game timer/service-readiness rules */

import {
  AppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceNoClaimFlagsGenerated,
  AppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceStateGenerated,
  RequiredAppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceNonClaimsGenerated,
} from './generated-app-game-timer-service-readiness-values';
import {
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceCountsMatchGenerated,
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceHasNoRuntimeClaimsGenerated,
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceMatchesRuntimeReadinessGenerated,
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceRequiredProofRefsGenerated,
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceStateForRuntimeReadinessGenerated,
  countAppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceRowsGenerated,
} from './generated-app-game-timer-service-readiness-rules';

export const AppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceState =
  AppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceStateGenerated;
export const RequiredAppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceNonClaims =
  RequiredAppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceNonClaimsGenerated;
export const AppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceNoClaimFlags =
  AppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceNoClaimFlagsGenerated;
export const appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceMatchesRuntimeReadiness =
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceMatchesRuntimeReadinessGenerated;
export const appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceStateForRuntimeReadiness =
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceStateForRuntimeReadinessGenerated;
export const countAppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceRows =
  countAppGameSourceGatedPolicyPreviewTimerSchedulerPersistenceRowsGenerated;
export const appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceRequiredProofRefs =
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceRequiredProofRefsGenerated;
export const appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceCountsMatch =
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceCountsMatchGenerated;
export const appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceHasNoRuntimeClaims =
  appGameSourceGatedPolicyPreviewTimerSchedulerPersistenceHasNoRuntimeClaimsGenerated;
