import {
  approvalRequestCandidateRefsAreConsistent as approvalRequestCandidateRefsAreConsistentImpl,
  authorityGrantStateIsConsistent as authorityGrantStateIsConsistentImpl,
  requestSettingRefsMatchPolicyKind as requestSettingRefsMatchPolicyKindImpl,
} from './app-game-control-authority-rules-authority';
import {
  approvalDecisionPersistenceIsConsistent as approvalDecisionPersistenceIsConsistentImpl,
  approvalDecisionResponseScopeIsConsistent as approvalDecisionResponseScopeIsConsistentImpl,
  decisionParentActionPresenceIsConsistent as decisionParentActionPresenceIsConsistentImpl,
  decisionPolicyVersionMatchesParentAction as decisionPolicyVersionMatchesParentActionImpl,
} from './app-game-control-authority-rules-decision';
import {
  actionResultApprovalStateIsConsistent as actionResultApprovalStateIsConsistentImpl,
  actionResultCapabilityIsConsistent as actionResultCapabilityIsConsistentImpl,
  actionResultEvidenceProofIsConsistent as actionResultEvidenceProofIsConsistentImpl,
} from './app-game-control-authority-rules-action-result';

export const authorityGrantStateIsConsistent = authorityGrantStateIsConsistentImpl;
export const requestSettingRefsMatchPolicyKind = requestSettingRefsMatchPolicyKindImpl;
export const approvalRequestCandidateRefsAreConsistent = approvalRequestCandidateRefsAreConsistentImpl;
export const decisionPolicyVersionMatchesParentAction = decisionPolicyVersionMatchesParentActionImpl;
export const decisionParentActionPresenceIsConsistent = decisionParentActionPresenceIsConsistentImpl;
export const approvalDecisionResponseScopeIsConsistent = approvalDecisionResponseScopeIsConsistentImpl;
export const approvalDecisionPersistenceIsConsistent = approvalDecisionPersistenceIsConsistentImpl;
export const actionResultApprovalStateIsConsistent = actionResultApprovalStateIsConsistentImpl;
export const actionResultCapabilityIsConsistent = actionResultCapabilityIsConsistentImpl;
export const actionResultEvidenceProofIsConsistent = actionResultEvidenceProofIsConsistentImpl;
