/* thin adapter over Rust-generated app-game timer/service-readiness rules */

import {
  AppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelNoClaimFlagsGenerated,
  AppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelStateGenerated,
  RequiredAppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelNonClaimsGenerated,
} from './generated-app-game-timer-service-readiness-values';
import {
  appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelCountsMatchGenerated,
  appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelHasNoRuntimeClaimsGenerated,
  appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelMatchesHandoffGenerated,
  appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelStateForHandoffGenerated,
  countAppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelRowsGenerated,
} from './generated-app-game-timer-service-readiness-rules';

export const AppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelState =
  AppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelStateGenerated;
export type AppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelStateValue =
  (typeof AppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelState)[keyof typeof AppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelState];
export const RequiredAppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelNonClaims =
  RequiredAppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelNonClaimsGenerated;
export const AppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelNoClaimFlags =
  AppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelNoClaimFlagsGenerated;
export const appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelMatchesHandoff =
  appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelMatchesHandoffGenerated;
export const appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelStateForHandoff =
  appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelStateForHandoffGenerated;
export const countAppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelRows =
  countAppGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelRowsGenerated;
export const appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelCountsMatch =
  appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelCountsMatchGenerated;
export const appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelHasNoRuntimeClaims =
  appGameSourceGatedPolicyPreviewTimerServiceReadinessReadModelHasNoRuntimeClaimsGenerated;
