export const AppControlCatalogSettingSeedsC = [
  [
    'enforcement',
    'App enforcement',
    'enforcement',
    'strict-actions',
    'Strict actions',
    'enforcement.graceSeconds',
    'number',
    'How long should the child get before strict action applies?',
    '/appPolicy/enforcement/graceSeconds',
    'needs-effect-wiring',
    'child-agent',
    'available',
    'child-agent strict action timer',
    'Grace timers need local runtime and audit state.',
    'Reject negative grace periods and record unavailable when timers cannot run.',
    [],
    15,
  ],
  [
    'enforcement',
    'App enforcement',
    'enforcement',
    'strict-actions',
    'Strict actions',
    'enforcement.requireRollbackPlan',
    'toggle',
    'Require rollback state for strict actions?',
    '/appPolicy/enforcement/requireRollbackPlan',
    'already-represented',
    'rust-service',
    'available',
    'adapter rollback or unavailable state',
    'Strict actions need rollback or explicit unavailable outcome.',
    'Reject strict action plans without audit and rollback/unavailable state.',
    [],
    true,
  ],
  [
    'app-lifecycle',
    'Managed app lifecycle',
    'setup',
    'managed-lifecycle',
    'Managed lifecycle',
    'lifecycle.mode',
    'single-choice',
    'How should app install and uninstall controls be handled?',
    '/appPolicy/lifecycle/mode',
    'manual-required',
    'os-adapter',
    'manual-required',
    'managed device, device-owner, MDM, or approved package lifecycle proof',
    'Personal app install or removal often is not available.',
    'Keep lifecycle controls disabled unless managed-device proof exists.',
    ['disabled', 'report-managed-state', 'managed-apps-only', 'device-owner-or-mdm-only'],
    'disabled',
  ],
  [
    'app-lifecycle',
    'Managed app lifecycle',
    'setup',
    'managed-lifecycle',
    'Managed lifecycle',
    'lifecycle.allowedOperations',
    'multi-choice',
    'Which managed app lifecycle operations are allowed?',
    '/appPolicy/lifecycle/allowedOperations',
    'manual-required',
    'os-adapter',
    'manual-required',
    'managed package lifecycle adapter',
    'Install, uninstall, hide, and suspend depend on platform custody and policy.',
    'Report managed lifecycle as unavailable when the device is not supervised or managed.',
    [
      'install-managed-app',
      'uninstall-managed-app',
      'hide-managed-app',
      'suspend-managed-app',
      'remove-user-installed-app-if-platform-approved',
      'prevent-uninstall-if-platform-approved',
    ],
    [],
  ],
  [
    'approvals',
    'Approvals',
    'approvals',
    'approval-events',
    'Approval events',
    'approvals.requiredFor',
    'multi-choice',
    'Which app events require parent approval?',
    '/appPolicy/approvals/requiredFor',
    'needs-effect-wiring',
    'child-agent',
    'available',
    'parent approval request and audit flow',
    'Approval state is policy data; child-agent still owns local action results.',
    'Queue or deny according to unanswered-default when parent is unavailable.',
    [
      'unknown-app',
      'new-app',
      'blocked-app',
      'time-extension',
      'managed-install',
      'managed-uninstall',
      'strict-action-unavailable',
      'category-override',
    ],
    ['unknown-app', 'time-extension', 'strict-action-unavailable'],
  ],
  [
    'approvals',
    'Approvals',
    'approvals',
    'approval-events',
    'Approval events',
    'approvals.unansweredDefault',
    'single-choice',
    'What happens if the parent does not answer?',
    '/appPolicy/approvals/unansweredDefault',
    'already-represented',
    'rust-parent-runtime',
    'available',
    'approval fallback policy',
    'Unanswered approvals must be deterministic and auditable.',
    'Use the configured fallback rather than silently allowing strict action.',
    ['allow', 'deny', 'keep-pending', 'use-rule-fallback'],
    'deny',
  ],
  [
    'reports',
    'Reports',
    'reports',
    'report-fields',
    'Report fields',
    'reports.visibleFields',
    'multi-choice',
    'Which app report fields should be visible?',
    '/appPolicy/reports/visibleFields',
    'already-represented',
    'parent-owned-storage',
    'available',
    'stored evidence references and report read models',
    'Reports must distinguish raw evidence from redacted rollups.',
    'Hide fields whose source capability is unavailable.',
    [
      'installed-apps',
      'running-now',
      'foreground-now',
      'session-rollups',
      'unknown-apps',
      'category-rollups',
      'time-budget',
      'policy-decisions',
      'enforcement-results',
      'approval-events',
      'managed-lifecycle-events',
      'source-capability',
    ],
    [
      'installed-apps',
      'running-now',
      'foreground-now',
      'session-rollups',
      'policy-decisions',
      'enforcement-results',
      'source-capability',
    ],
  ],
  [
    'reports',
    'Reports',
    'audit',
    'retention',
    'Retention',
    'retention.rawObservation',
    'retention',
    'How long should raw app observations be kept?',
    '/appPolicy/retention/rawObservation',
    'already-represented',
    'parent-owned-storage',
    'available',
    'local-first evidence retention policy',
    'Raw app observations should be short-lived and redacted where possible.',
    'Default to local retention and do not upload raw app observations to Ocentra-hosted storage.',
    [],
    '7-days',
  ],
  [
    'reports',
    'Reports',
    'audit',
    'retention',
    'Retention',
    'retention.rollups',
    'retention',
    'How long should app rollups be kept?',
    '/appPolicy/retention/rollups',
    'already-represented',
    'parent-owned-storage',
    'available',
    'local-first report rollup retention policy',
    'Rollups must preserve custody and evidence-reference boundaries.',
    'Delete or export according to parent-owned retention settings.',
    [],
    '30-days',
  ],
] as const;
