import type { AppControlGuideCatalogSettingSeed } from './app-control-catalog-data';

// Generated from docs/app-control-capability-guide.md. Tests parse the source doc and prove parity.
export const AppControlGuideCatalogData1: readonly AppControlGuideCatalogSettingSeed[] = [
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration',
    'Foreground Use And Duration',
    3,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration-002',
    81,
    251,
    'How long was this app in foreground today?',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration',
    'Foreground Use And Duration',
    3,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration-003',
    82,
    252,
    'Did the time budget run out?',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration',
    'Foreground Use And Duration',
    3,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration-004',
    83,
    253,
    'Which evidence ids prove the count?',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-001',
    84,
    269,
    'Education.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-002',
    85,
    270,
    'Productivity.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-003',
    86,
    271,
    'Communication.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-004',
    87,
    272,
    'Entertainment.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-005',
    88,
    273,
    'Social.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-006',
    89,
    274,
    'Browser.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-007',
    90,
    275,
    'Game.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-008',
    91,
    276,
    'Creative.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-009',
    92,
    277,
    'System.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-010',
    93,
    278,
    'Unknown.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-011',
    94,
    285,
    'Category is not content.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-012',
    95,
    286,
    'Category confidence must be recorded.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-013',
    96,
    287,
    'Parent rules decide actions. Category labels alone should not block.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-014',
    97,
    288,
    'Some platforms expose categories as opaque tokens rather than raw identifiers.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-015',
    98,
    289,
    'Unknown or ambiguous categories should degrade to observe, ask, or parent review according to explicit policy.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-001',
    99,
    301,
    'Open an approved app.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-002',
    100,
    302,
    'Relaunch a blocked/closed app later after a time budget resets.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-003',
    101,
    303,
    'Open an app as part of an ask-parent approval.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-004',
    102,
    304,
    'Prefer a managed app path or managed browser path for certain tasks.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-005',
    103,
    308,
    'Launching an app does not guarantee it stays foreground.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-006',
    104,
    309,
    'Launching an unmanaged app can move outside Ocentra control.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-007',
    105,
    310,
    'Mobile launch behavior depends on platform foreground and intent rules.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-001',
    106,
    316,
    'Stop an app after a block or time-limit decision.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-002',
    107,
    317,
    'Stop an owned child process.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-003',
    108,
    318,
    'Stop a target process when identity still matches the policy target.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-004',
    109,
    319,
    'Record already-exited, target-changed, permission-limited, failed, or succeeded results.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-005',
    110,
    324,
    'Termination can lose unsaved work.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-006',
    111,
    325,
    'Target processes can exit and relaunch between detection and action.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-007',
    112,
    326,
    'Parent/child UX should support grace periods, warnings, and ask-parent flows.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-008',
    113,
    327,
    'Some platforms do not allow third-party apps to kill other apps.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-009',
    114,
    328,
    'Protected, elevated, system, or different-user processes may be unavailable.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-001',
    115,
    337,
    'Windows application control policy, AppLocker, WDAC/App Control for Business, or a narrower service adapter where proven.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-002',
    116,
    339,
    'macOS MDM profile, system extension, endpoint/security tooling, or managed app restriction where entitled and deployed.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-003',
    117,
    341,
    'Linux policy, desktop/session integration, package-manager restriction, or service-level control where proven.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-004',
    118,
    343,
    'Android DevicePolicyManager package hide/suspend, device owner/profile owner, managed configuration, or accessibility/VPN-adjacent UX where approved.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-005',
    119,
    345,
    'iOS/iPadOS Screen Time Family Controls, Managed Settings shields, Device Activity thresholds, or MDM restrictions where entitled/supervised.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-006',
    120,
    350,
    'Broad app blocking is a privileged OS capability, not a normal UI toggle.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-007',
    121,
    351,
    'Policy setup can require admin rights, device-owner enrollment, MDM, supervision, entitlements, app review, signing, or store distribution.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-008',
    122,
    353,
    'Some systems support shielding/visibility restrictions rather than process termination.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-009',
    123,
    355,
    'Platform APIs may expose opaque identifiers for privacy.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-010',
    124,
    356,
    'Rollback and uninstall paths must be documented before strict policies ship.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-001',
    125,
    364,
    'App/session identity.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-002',
    126,
    365,
    'Running or foreground duration proof.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-003',
    127,
    366,
    'Schedule and budget state.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-004',
    128,
    367,
    'Warning threshold and grace state.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-005',
    129,
    368,
    'Parent approval or extension state.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-006',
    130,
    369,
    'Enforcement fallback for unsupported action.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-007',
    131,
    370,
    'Audit event for warning, timeout, action, failure, extension, and rollback.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-008',
    132,
    374,
    'A timer without action is report-only.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-009',
    133,
    375,
    'Foreground time and running time should be separate settings.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-010',
    134,
    376,
    'Cross-device time budgets need sync/custody rules.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-011',
    135,
    377,
    'Mobile time-limit enforcement depends on platform-specific APIs.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-001',
    136,
    386,
    'Windows MSI/MSIX/package manager or managed installer.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-002',
    137,
    387,
    'macOS installer/package/MDM managed app or declarative package management.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-003',
    138,
    388,
    'Linux package manager, Flatpak, Snap, AppImage-managed wrapper, or desktop entry.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-004',
    139,
    390,
    'Android package installer, device owner/profile owner, managed Play, or MDM.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-005',
    140,
    391,
    'iOS/iPadOS MDM managed app distribution and managed app removal.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-006',
    141,
    395,
    'Ocentra must not remove personal apps unless a platform-approved managed path and parent/child custody model explicitly allow it.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-007',
    142,
    397,
    'Store policies, signing, entitlements, user consent, device enrollment, and uninstall rights vary sharply.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-008',
    143,
    399,
    'Install/uninstall actions must be audited separately from normal app observation.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-001',
    144,
    408,
    'Known identity from package/bundle/app token.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-002',
    145,
    409,
    'Known policy source.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-003',
    146,
    410,
    'Install or update provenance.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-004',
    147,
    411,
    'Known allowed/blocked/shielded state.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-005',
    148,
    412,
    'Stronger app lifecycle action where the platform supports it.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-001',
    149,
    421,
    'Running and foreground observation.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-002',
    150,
    422,
    'Session duration.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-003',
    151,
    423,
    'Category candidate.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-004',
    152,
    424,
    'Ask-parent or warning events.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-005',
    153,
    425,
    'Terminate where allowed.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-006',
    154,
    426,
    'Report-only unknown or bypass state.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-001',
    155,
    435,
    'Observe only.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-002',
    156,
    436,
    'Ask parent on first run.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-003',
    157,
    437,
    'Warn child.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-004',
    158,
    438,
    'Count time under unknown-app budget.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-005',
    159,
    439,
    'Block or terminate only when the parent selected that posture and the platform adapter can prove the action.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-001',
    160,
    450,
    'Warn before time limit.',
  ],
];
