/* thin adapter over Rust-generated app-game timer/service-readiness rules */

import {
  AppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelNoClaimFlagsGenerated,
  AppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelStateGenerated,
  RequiredAppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelNonClaimsGenerated,
} from './generated-app-game-timer-service-readiness-values';
import {
  appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelCountsMatchGenerated,
  appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelHasNoRuntimeClaimsGenerated,
  appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelMatchesHandoffGenerated,
  appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelStateForHandoffGenerated,
  countAppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelRowsGenerated,
} from './generated-app-game-timer-service-readiness-rules';

export const AppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelState =
  AppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelStateGenerated;
export type AppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelStateValue =
  (typeof AppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelState)[keyof typeof AppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelState];
export const RequiredAppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelNonClaims =
  RequiredAppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelNonClaimsGenerated;
export const AppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelNoClaimFlags =
  AppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelNoClaimFlagsGenerated;
export const appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelMatchesHandoff =
  appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelMatchesHandoffGenerated;
export const appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelStateForHandoff =
  appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelStateForHandoffGenerated;
export const countAppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelRows =
  countAppGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelRowsGenerated;
export const appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelCountsMatch =
  appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelCountsMatchGenerated;
export const appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelHasNoRuntimeClaims =
  appGameSourceGatedPolicyPreviewTimerServiceReadinessProtocolReadModelHasNoRuntimeClaimsGenerated;
