/* thin adapter over Rust-generated app-game timer/service-readiness rules */

import {
  AppGameSourceGatedPolicyPreviewTimerStatusNoClaimFlagsGenerated,
  AppGameSourceGatedPolicyPreviewTimerStatusStateGenerated,
  RequiredAppGameSourceGatedPolicyPreviewTimerStatusNonClaimsGenerated,
} from './generated/app-game-timer-service-readiness-values';
import {
  appGameSourceGatedPolicyPreviewTimerStatusCountsMatchGenerated,
  appGameSourceGatedPolicyPreviewTimerStatusHasNoRuntimeClaimsGenerated,
  appGameSourceGatedPolicyPreviewTimerStatusMatchesHandoffGenerated,
  appGameSourceGatedPolicyPreviewTimerStatusRequiredProofRefsGenerated,
  appGameSourceGatedPolicyPreviewTimerStatusStateForHandoffGenerated,
  countAppGameSourceGatedPolicyPreviewTimerStatusRowsGenerated,
} from './generated/app-game-timer-service-readiness-rules';

export const AppGameSourceGatedPolicyPreviewTimerStatusState =
  AppGameSourceGatedPolicyPreviewTimerStatusStateGenerated;
export const RequiredAppGameSourceGatedPolicyPreviewTimerStatusNonClaims =
  RequiredAppGameSourceGatedPolicyPreviewTimerStatusNonClaimsGenerated;
export const AppGameSourceGatedPolicyPreviewTimerStatusNoClaimFlags =
  AppGameSourceGatedPolicyPreviewTimerStatusNoClaimFlagsGenerated;
export const appGameSourceGatedPolicyPreviewTimerStatusMatchesHandoff =
  appGameSourceGatedPolicyPreviewTimerStatusMatchesHandoffGenerated;
export const appGameSourceGatedPolicyPreviewTimerStatusStateForHandoff =
  appGameSourceGatedPolicyPreviewTimerStatusStateForHandoffGenerated;
export const countAppGameSourceGatedPolicyPreviewTimerStatusRows =
  countAppGameSourceGatedPolicyPreviewTimerStatusRowsGenerated;
export const appGameSourceGatedPolicyPreviewTimerStatusRequiredProofRefs =
  appGameSourceGatedPolicyPreviewTimerStatusRequiredProofRefsGenerated;
export const appGameSourceGatedPolicyPreviewTimerStatusCountsMatch =
  appGameSourceGatedPolicyPreviewTimerStatusCountsMatchGenerated;
export const appGameSourceGatedPolicyPreviewTimerStatusHasNoRuntimeClaims =
  appGameSourceGatedPolicyPreviewTimerStatusHasNoRuntimeClaimsGenerated;
