import { ParentPlatform as ParentPlatformValue } from '@ocentra-parent/schema-domain/family-reference-primitives';
import { route } from './app-game-platform-extension-routing-data-support';

export const AndroidPlatformExtensionRows = [
  route({
    rowId: 'ANDROID-01',
    platform: ParentPlatformValue.Android,
    title: 'Package inventory and visibility contract',
    actionScope: 'inventory',
    authorityTier: 'observe-only',
    setupState: 'permission-required',
    proofGate: 'Package visibility and permission proof',
    parentVisibleLabel: 'Android package visibility needs permission proof and stays inventory-only.',
    appGameDifference: 'Game packages need category proof before policy treats them as games.',
  }),
  route({
    rowId: 'ANDROID-02',
    platform: ParentPlatformValue.Android,
    title: 'UsageStats permission and usage summary adapter',
    actionScope: 'runtime',
    authorityTier: 'user-approved-helper',
    setupState: 'permission-required',
    proofGate: 'Usage access proof',
    parentVisibleLabel: 'Android usage summaries require user-granted Usage Access proof.',
    appGameDifference: 'Usage summaries are not foreground content or direct enforcement authority.',
    manualTags: ['@requires-usage-stats'],
    requiredProofKinds: ['permission-setup-proof', 'runtime-evidence-proof'],
  }),
  route({
    rowId: 'ANDROID-03',
    platform: ParentPlatformValue.Android,
    title: 'UsageEvents foreground/session adapter',
    actionScope: 'foreground',
    authorityTier: 'user-approved-helper',
    setupState: 'permission-required',
    proofGate: 'UsageEvents replay proof',
    parentVisibleLabel: 'Android UsageEvents foreground/session rows need replay proof.',
    appGameDifference: 'Game session proof needs event replay and cannot infer gameplay content.',
    manualTags: ['@requires-usage-stats'],
    requiredProofKinds: ['permission-setup-proof', 'runtime-evidence-proof'],
  }),
  route({
    rowId: 'ANDROID-04',
    platform: ParentPlatformValue.Android,
    title: 'Accessibility-assisted foreground/overlay adapter',
    actionScope: 'foreground',
    authorityTier: 'accessibility-assisted',
    setupState: 'permission-required',
    proofGate: 'Transparent opt-in proof',
    parentVisibleLabel: 'Android Accessibility-assisted foreground proof requires transparent opt-in evidence.',
    appGameDifference: 'Accessibility overlay proof cannot become package suspend proof.',
    manualTags: ['@requires-accessibility'],
    requiredProofKinds: ['permission-setup-proof', 'runtime-evidence-proof'],
  }),
  route({
    rowId: 'ANDROID-05',
    platform: ParentPlatformValue.Android,
    title: 'VpnService/DNS relation handoff to network plan',
    actionScope: 'cross-plan-handoff',
    authorityTier: 'not-claimed',
    setupState: 'not-claimed',
    proofGate: 'Network-plan no-claim proof',
    parentVisibleLabel: 'Android VPN or DNS control routes to the network plan and is not claimed by app/game scope.',
    appGameDifference: 'Cloud-game/network traffic gating belongs to browser/network plans, not native app proof.',
    productScope: 'platform-handoff',
    promotionState: 'not-claimed',
    requiredProofKinds: ['cross-plan-handoff-proof', 'security-negative-proof'],
    crossPlanHandoff: 'Route Android VPN/DNS behavior to network-domain-control or browser-plan proof before claims.',
  }),
  route({
    rowId: 'ANDROID-06',
    platform: ParentPlatformValue.Android,
    title: 'Device Owner provisioning flow',
    actionScope: 'policy-handoff',
    authorityTier: 'device-owner',
    setupState: 'device-owner-required',
    proofGate: 'Real device-owner proof',
    parentVisibleLabel: 'Android Device Owner claims need real provisioning proof before controls move up.',
    appGameDifference: 'Game package hide/suspend claims also need Device Owner proof and rollback.',
    manualTags: ['@requires-device-owner'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof'],
  }),
  route({
    rowId: 'ANDROID-07',
    platform: ParentPlatformValue.Android,
    title: 'Profile Owner / managed profile flow',
    actionScope: 'policy-handoff',
    authorityTier: 'managed-profile',
    setupState: 'managed-profile-required',
    proofGate: 'Managed profile proof',
    parentVisibleLabel: 'Android Profile Owner support is scoped to managed profile proof.',
    appGameDifference: 'Managed-profile game controls must show profile scope and rollback limits.',
    manualTags: ['@requires-profile-owner'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof'],
  }),
  route({
    rowId: 'ANDROID-08',
    platform: ParentPlatformValue.Android,
    title: 'setApplicationHidden adapter proof',
    actionScope: 'hide-app',
    authorityTier: 'device-owner',
    setupState: 'device-owner-required',
    proofGate: 'DPM hidden-package proof',
    parentVisibleLabel: 'Android hide-app requires Device Owner or Profile Owner DPM proof and rollback.',
    appGameDifference: 'Game hide-app proof needs package identity, parent policy, and unhide rollback proof.',
    manualTags: ['@requires-device-owner'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'ANDROID-09',
    platform: ParentPlatformValue.Android,
    title: 'setPackagesSuspended adapter proof',
    actionScope: 'suspend-app',
    authorityTier: 'device-owner',
    setupState: 'device-owner-required',
    proofGate: 'DPM suspension proof',
    parentVisibleLabel: 'Android suspend-app requires Device Owner or Profile Owner DPM proof and unsuspend rollback.',
    appGameDifference: 'Game suspension proof needs package identity, budget decision, and child-visible state.',
    manualTags: ['@requires-device-owner'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'ANDROID-10',
    platform: ParentPlatformValue.Android,
    title: 'setUninstallBlocked proof',
    actionScope: 'uninstall-block',
    authorityTier: 'device-owner',
    setupState: 'device-owner-required',
    proofGate: 'DPM uninstall-block proof',
    parentVisibleLabel: 'Android uninstall blocking requires Device Owner proof and rollback before app/game claims.',
    appGameDifference: 'Install/uninstall custody routes to the app install approval workpack before product claims.',
    manualTags: ['@requires-device-owner'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'ANDROID-11',
    platform: ParentPlatformValue.Android,
    title: 'Lock Task / allowlist mode proof',
    actionScope: 'single-app-mode',
    authorityTier: 'kiosk-or-single-app',
    setupState: 'kiosk-required',
    proofGate: 'Dedicated-device proof',
    parentVisibleLabel: 'Android Lock Task or allowlist mode requires dedicated-device setup and rollback proof.',
    appGameDifference: 'Game kiosk claims need dedicated-device proof and cannot masquerade as normal-mode blocking.',
    manualTags: ['@requires-kiosk', '@requires-device-owner'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'ANDROID-12',
    platform: ParentPlatformValue.Android,
    title: 'Managed configurations for app restrictions',
    actionScope: 'managed-configuration',
    authorityTier: 'managed-profile',
    setupState: 'managed-profile-required',
    proofGate: 'Managed configuration proof',
    parentVisibleLabel: 'Android managed configurations require managed-profile scope and app-specific proof.',
    appGameDifference: 'Game restrictions through managed config must name target app support and rollback state.',
    manualTags: ['@requires-profile-owner'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'ANDROID-13',
    platform: ParentPlatformValue.Android,
    title: 'Play policy/signing/store compliance proof',
    actionScope: 'store-signing',
    authorityTier: 'manual-required',
    setupState: 'manual-required',
    proofGate: 'Store/signing proof',
    parentVisibleLabel:
      'Android Play policy, signing, and store compliance proof is required before distribution claims.',
    appGameDifference: 'Game app controls must keep store policy constraints visible before runtime claims.',
    manualTags: ['@requires-store-signing'],
    requiredProofKinds: ['store-signing-entitlement-proof', 'manual-platform-proof'],
    storeSigningEntitlementRequired: true,
  }),
  route({
    rowId: 'ANDROID-14',
    platform: ParentPlatformValue.Android,
    title: 'Android child request/approval UX',
    actionScope: 'warn-ask',
    authorityTier: 'device-owner',
    setupState: 'device-owner-required',
    proofGate: 'Device screenshot and audit proof',
    parentVisibleLabel: 'Android child request UX needs device screenshot, approval expiry, and audit proof.',
    appGameDifference: 'Game approval UX must cite game/package evidence and avoid content claims.',
    manualTags: ['@requires-device-owner'],
    requiredProofKinds: ['ui-proof', 'policy-action-proof', 'manual-platform-proof'],
  }),
] as const;
