/* thin adapter over Rust-generated app-game preview/source-freshness rules */

import {
  AppGameSourceFreshnessPreviewGateNoRuntimeClaimFlagsGenerated,
  AppGameSourceFreshnessPreviewGateStateGenerated,
  AppGameSourceFreshnessPreviewGateStatusGenerated,
} from './generated-app-game-preview-source-freshness-values';
import {
  appGameSourceFreshnessPreviewGateReadModelCountsMatchRowsGenerated,
  appGameSourceFreshnessPreviewGateReadModelHasNoRuntimeClaimsGenerated,
  appGameSourceFreshnessPreviewGateRowHasNoRuntimeClaimsGenerated,
  appGameSourceFreshnessPreviewGateRowMatchesPreviewStateGenerated,
  appGameSourceFreshnessPreviewGateRowMatchesSourceStateGenerated,
  countAppGameSourceFreshnessPreviewGateReadModelRowsGenerated,
  countAppGameSourceFreshnessPreviewGateRowsGenerated,
  countAppGameSourceFreshnessPreviewGateStatesGenerated,
  countAppGameSourceFreshnessPreviewGateStatusesGenerated,
} from './generated-app-game-preview-source-freshness-rules';

export const AppGameSourceFreshnessPreviewGateStatus = AppGameSourceFreshnessPreviewGateStatusGenerated;
export const AppGameSourceFreshnessPreviewGateState = AppGameSourceFreshnessPreviewGateStateGenerated;
export const AppGameSourceFreshnessPreviewGateNoRuntimeClaimFlags =
  AppGameSourceFreshnessPreviewGateNoRuntimeClaimFlagsGenerated;

export const appGameSourceFreshnessPreviewGateRowHasNoRuntimeClaims =
  appGameSourceFreshnessPreviewGateRowHasNoRuntimeClaimsGenerated;
export const appGameSourceFreshnessPreviewGateRowMatchesSourceState =
  appGameSourceFreshnessPreviewGateRowMatchesSourceStateGenerated;
export const appGameSourceFreshnessPreviewGateRowMatchesPreviewState =
  appGameSourceFreshnessPreviewGateRowMatchesPreviewStateGenerated;
export const countAppGameSourceFreshnessPreviewGateRows = countAppGameSourceFreshnessPreviewGateRowsGenerated;
export const countAppGameSourceFreshnessPreviewGateStatuses = countAppGameSourceFreshnessPreviewGateStatusesGenerated;
export const countAppGameSourceFreshnessPreviewGateStates = countAppGameSourceFreshnessPreviewGateStatesGenerated;
export const countAppGameSourceFreshnessPreviewGateReadModelRows =
  countAppGameSourceFreshnessPreviewGateReadModelRowsGenerated;
export const appGameSourceFreshnessPreviewGateReadModelCountsMatchRows =
  appGameSourceFreshnessPreviewGateReadModelCountsMatchRowsGenerated;
export const appGameSourceFreshnessPreviewGateReadModelHasNoRuntimeClaims =
  appGameSourceFreshnessPreviewGateReadModelHasNoRuntimeClaimsGenerated;
