import type { Infer } from './effect';
import {
  AppGamePolicyPreviewHandoffAdapterDispatchStateSchema as GeneratedAppGamePolicyPreviewHandoffAdapterDispatchStateSchema,
  AppGamePolicyPreviewHandoffIdSchema as GeneratedAppGamePolicyPreviewHandoffIdSchema,
  AppGamePolicyPreviewHandoffOptionsSchema as GeneratedAppGamePolicyPreviewHandoffOptionsSchema,
  AppGamePolicyPreviewHandoffReadModelSchema as GeneratedAppGamePolicyPreviewHandoffReadModelSchema,
  AppGamePolicyPreviewHandoffRuntimeClaimStateSchema as GeneratedAppGamePolicyPreviewHandoffRuntimeClaimStateSchema,
  AppGamePolicyPreviewHandoffRowIdSchema as GeneratedAppGamePolicyPreviewHandoffRowIdSchema,
  AppGamePolicyPreviewHandoffRowSchema as GeneratedAppGamePolicyPreviewHandoffRowSchema,
  AppGamePolicyPreviewHandoffSourceContractRefSchema as GeneratedAppGamePolicyPreviewHandoffSourceContractRefSchema,
  AppGamePolicyPreviewStatus as GeneratedAppGamePolicyPreviewStatus,
  AppGamePolicyPreviewStatusSchema as GeneratedAppGamePolicyPreviewStatusSchema,
  AppGamePolicyPreviewTargetDomain as GeneratedAppGamePolicyPreviewTargetDomain,
  AppGamePolicyPreviewTargetDomainSchema as GeneratedAppGamePolicyPreviewTargetDomainSchema,
  decodeAppGamePolicyPreviewHandoffReadModel as GeneratedDecodeAppGamePolicyPreviewHandoffReadModel,
} from './generated-app-game-policy-preview-handoff';

export const AppGamePolicyPreviewHandoffIdSchema = GeneratedAppGamePolicyPreviewHandoffIdSchema;
export const AppGamePolicyPreviewHandoffRowIdSchema = GeneratedAppGamePolicyPreviewHandoffRowIdSchema;
export const AppGamePolicyPreviewHandoffSourceContractRefSchema =
  GeneratedAppGamePolicyPreviewHandoffSourceContractRefSchema;
export const AppGamePolicyPreviewHandoffRuntimeClaimStateSchema =
  GeneratedAppGamePolicyPreviewHandoffRuntimeClaimStateSchema;
export const AppGamePolicyPreviewHandoffAdapterDispatchStateSchema =
  GeneratedAppGamePolicyPreviewHandoffAdapterDispatchStateSchema;
export const AppGamePolicyPreviewTargetDomainSchema = GeneratedAppGamePolicyPreviewTargetDomainSchema;
export const AppGamePolicyPreviewStatusSchema = GeneratedAppGamePolicyPreviewStatusSchema;
export const AppGamePolicyPreviewHandoffOptionsSchema = GeneratedAppGamePolicyPreviewHandoffOptionsSchema;
export const AppGamePolicyPreviewHandoffRowSchema = GeneratedAppGamePolicyPreviewHandoffRowSchema;
export const AppGamePolicyPreviewHandoffReadModelSchema = GeneratedAppGamePolicyPreviewHandoffReadModelSchema;

export type AppGamePolicyPreviewHandoffOptions = Infer<typeof GeneratedAppGamePolicyPreviewHandoffOptionsSchema>;
export type AppGamePolicyPreviewHandoffRow = Infer<typeof GeneratedAppGamePolicyPreviewHandoffRowSchema>;
export type AppGamePolicyPreviewHandoffReadModel = Infer<typeof GeneratedAppGamePolicyPreviewHandoffReadModelSchema>;
export type AppGamePolicyPreviewTargetDomain = Infer<typeof GeneratedAppGamePolicyPreviewTargetDomainSchema>;
export type AppGamePolicyPreviewStatus = Infer<typeof GeneratedAppGamePolicyPreviewStatusSchema>;

export const decodeAppGamePolicyPreviewHandoffReadModel = GeneratedDecodeAppGamePolicyPreviewHandoffReadModel;

export const AppGamePolicyPreviewStatus = GeneratedAppGamePolicyPreviewStatus;
export const AppGamePolicyPreviewTargetDomain = GeneratedAppGamePolicyPreviewTargetDomain;
