import * as Generated from './generated-app-game-source-freshness-policy-consumption';
import type * as GeneratedTypes from './generated-app-game-source-freshness-policy-consumption';

export const AppGameSourceFreshnessPolicyRequestIdSchema = Generated.AppGameSourceFreshnessPolicyRequestIdSchema;
export const AppGameSourceFreshnessPolicyReadinessIdSchema = Generated.AppGameSourceFreshnessPolicyReadinessIdSchema;
export const AppGameSourceFreshnessTargetRefSchema = Generated.AppGameSourceFreshnessTargetRefSchema;
export const AppGameSourceFreshnessEvidenceRefSchema = Generated.AppGameSourceFreshnessEvidenceRefSchema;
export const AppGameSourceFreshnessMatrixIdSchema = Generated.AppGameSourceFreshnessMatrixIdSchema;
export const AppGameSourceFreshnessPolicyTargetKindSchema = Generated.AppGameSourceFreshnessPolicyTargetKindSchema;
export const AppGameSourceFreshnessRequirementKindSchema = Generated.AppGameSourceFreshnessRequirementKindSchema;
export const AppGameSourceFreshnessSourceKindSchema = Generated.AppGameSourceFreshnessSourceKindSchema;
export const AppGameSourceFreshnessReadModelStateSchema = Generated.AppGameSourceFreshnessReadModelStateSchema;
export const AppGameSourceFreshnessCapabilityStatusSchema = Generated.AppGameSourceFreshnessCapabilityStatusSchema;
export const AppGameSourceFreshnessRequirementStateSchema = Generated.AppGameSourceFreshnessRequirementStateSchema;
export const AppGameSourceFreshnessPolicyReadinessStateSchema =
  Generated.AppGameSourceFreshnessPolicyReadinessStateSchema;
export const AppGameSourceFreshnessAdapterDispatchStateSchema =
  Generated.AppGameSourceFreshnessAdapterDispatchStateSchema;
export const AppGameSourceFreshnessReasonCodeSchema = Generated.AppGameSourceFreshnessReasonCodeSchema;
export const AppGameSourceFreshnessStatusRowSchema = Generated.AppGameSourceFreshnessStatusRowSchema;
export const AppGameSourceFreshnessPolicyTargetSchema = Generated.AppGameSourceFreshnessPolicyTargetSchema;
export const AppGameSourceFreshnessPolicyRequestSchema = Generated.AppGameSourceFreshnessPolicyRequestSchema;
export const AppGameSourceFreshnessRequirementResultSchema = Generated.AppGameSourceFreshnessRequirementResultSchema;
export const AppGameSourceFreshnessPolicyReadinessSchema = Generated.AppGameSourceFreshnessPolicyReadinessSchema;
export const AppGameSourceFreshnessPolicyConsumptionMatrixSchema =
  Generated.AppGameSourceFreshnessPolicyConsumptionMatrixSchema;
export const evaluateAppGameSourceFreshnessPolicyReadiness = Generated.evaluateAppGameSourceFreshnessPolicyReadiness;
export const decodeAppGameSourceFreshnessPolicyReadiness = Generated.decodeAppGameSourceFreshnessPolicyReadiness;
export const decodeAppGameSourceFreshnessPolicyConsumptionMatrix =
  Generated.decodeAppGameSourceFreshnessPolicyConsumptionMatrix;

export type AppGameSourceFreshnessStatusRow = GeneratedTypes.AppGameSourceFreshnessStatusRow;
export type AppGameSourceFreshnessPolicyTarget = GeneratedTypes.AppGameSourceFreshnessPolicyTarget;
export type AppGameSourceFreshnessPolicyRequest = GeneratedTypes.AppGameSourceFreshnessPolicyRequest;
export type AppGameSourceFreshnessRequirementResult = GeneratedTypes.AppGameSourceFreshnessRequirementResult;
export type AppGameSourceFreshnessPolicyReadiness = GeneratedTypes.AppGameSourceFreshnessPolicyReadiness;
export type AppGameSourceFreshnessPolicyConsumptionMatrix =
  GeneratedTypes.AppGameSourceFreshnessPolicyConsumptionMatrix;
