import {
  BillingEntitlementRuntimeAuditReferenceSchema as GeneratedBillingEntitlementRuntimeAuditReferenceSchema,
  BillingEntitlementRuntimeBoundaryIdSchema as GeneratedBillingEntitlementRuntimeBoundaryIdSchema,
  BillingEntitlementRuntimeChildCustodyClaimSchema as GeneratedBillingEntitlementRuntimeChildCustodyClaimSchema,
  BillingEntitlementRuntimeConsumptionStateSchema as GeneratedBillingEntitlementRuntimeConsumptionStateSchema,
  BillingEntitlementRuntimeNonClaimSchema as GeneratedBillingEntitlementRuntimeNonClaimSchema,
  BillingEntitlementRuntimeOperationSchema as GeneratedBillingEntitlementRuntimeOperationSchema,
  BillingEntitlementRuntimePortalUiClaimSchema as GeneratedBillingEntitlementRuntimePortalUiClaimSchema,
  BillingEntitlementRuntimeProductionBillingClaimSchema as GeneratedBillingEntitlementRuntimeProductionBillingClaimSchema,
  BillingEntitlementRuntimeProviderContactClaimSchema as GeneratedBillingEntitlementRuntimeProviderContactClaimSchema,
  BillingEntitlementRuntimeProviderExecutionClaimSchema as GeneratedBillingEntitlementRuntimeProviderExecutionClaimSchema,
  BillingEntitlementRuntimeRefundCreditClaimSchema as GeneratedBillingEntitlementRuntimeRefundCreditClaimSchema,
  BillingEntitlementRuntimeSchemaVersionSchema as GeneratedBillingEntitlementRuntimeSchemaVersionSchema,
  BillingEntitlementRuntimeSnapshotStateSchema as GeneratedBillingEntitlementRuntimeSnapshotStateSchema,
  BillingEntitlementRuntimeSourceSchema as GeneratedBillingEntitlementRuntimeSourceSchema,
  BillingEntitlementRuntimeProofReadModel as GeneratedBillingEntitlementRuntimeProofReadModel,
  BillingEntitlementRuntimeProofSchema as GeneratedBillingEntitlementRuntimeProofSchema,
  BillingEntitlementRuntimeSnapshotConsumptionSchema as GeneratedBillingEntitlementRuntimeSnapshotConsumptionSchema,
  BillingEntitlementRuntimeDeviceLimitConsumptionSchema as GeneratedBillingEntitlementRuntimeDeviceLimitConsumptionSchema,
  BillingEntitlementRuntimeFailureConsumptionSchema as GeneratedBillingEntitlementRuntimeFailureConsumptionSchema,
  type BillingEntitlementRuntimeConsumptionState as GeneratedBillingEntitlementRuntimeConsumptionState,
  type BillingEntitlementRuntimeNonClaim as GeneratedBillingEntitlementRuntimeNonClaim,
  type BillingEntitlementRuntimeOperation as GeneratedBillingEntitlementRuntimeOperation,
  type BillingEntitlementRuntimeSnapshotState as GeneratedBillingEntitlementRuntimeSnapshotState,
  type BillingEntitlementRuntimeProof as GeneratedBillingEntitlementRuntimeProof,
  type BillingEntitlementRuntimeSnapshotConsumption as GeneratedBillingEntitlementRuntimeSnapshotConsumption,
  type BillingEntitlementRuntimeDeviceLimitConsumption as GeneratedBillingEntitlementRuntimeDeviceLimitConsumption,
  type BillingEntitlementRuntimeFailureConsumption as GeneratedBillingEntitlementRuntimeFailureConsumption,
} from './generated-billing-entitlement-runtime-proof-schema';

export const BillingEntitlementRuntimeSnapshotConsumptionSchema =
  GeneratedBillingEntitlementRuntimeSnapshotConsumptionSchema;
export const BillingEntitlementRuntimeDeviceLimitConsumptionSchema =
  GeneratedBillingEntitlementRuntimeDeviceLimitConsumptionSchema;
export const BillingEntitlementRuntimeFailureConsumptionSchema =
  GeneratedBillingEntitlementRuntimeFailureConsumptionSchema;
export const BillingEntitlementRuntimeProofSchema = GeneratedBillingEntitlementRuntimeProofSchema;
export const BillingEntitlementRuntimeProofReadModel = GeneratedBillingEntitlementRuntimeProofReadModel;

export type BillingEntitlementRuntimeSnapshotConsumption = GeneratedBillingEntitlementRuntimeSnapshotConsumption;
export type BillingEntitlementRuntimeDeviceLimitConsumption = GeneratedBillingEntitlementRuntimeDeviceLimitConsumption;
export type BillingEntitlementRuntimeFailureConsumption = GeneratedBillingEntitlementRuntimeFailureConsumption;
export type BillingEntitlementRuntimeProof = GeneratedBillingEntitlementRuntimeProof;

export const BillingEntitlementRuntimeAuditReferenceSchema = GeneratedBillingEntitlementRuntimeAuditReferenceSchema;
export const BillingEntitlementRuntimeBoundaryIdSchema = GeneratedBillingEntitlementRuntimeBoundaryIdSchema;
export const BillingEntitlementRuntimeChildCustodyClaimSchema =
  GeneratedBillingEntitlementRuntimeChildCustodyClaimSchema;
export const BillingEntitlementRuntimeConsumptionStateSchema = GeneratedBillingEntitlementRuntimeConsumptionStateSchema;
export const BillingEntitlementRuntimeNonClaimSchema = GeneratedBillingEntitlementRuntimeNonClaimSchema;
export const BillingEntitlementRuntimeOperationSchema = GeneratedBillingEntitlementRuntimeOperationSchema;
export const BillingEntitlementRuntimePortalUiClaimSchema = GeneratedBillingEntitlementRuntimePortalUiClaimSchema;
export const BillingEntitlementRuntimeProductionBillingClaimSchema =
  GeneratedBillingEntitlementRuntimeProductionBillingClaimSchema;
export const BillingEntitlementRuntimeProviderContactClaimSchema =
  GeneratedBillingEntitlementRuntimeProviderContactClaimSchema;
export const BillingEntitlementRuntimeProviderExecutionClaimSchema =
  GeneratedBillingEntitlementRuntimeProviderExecutionClaimSchema;
export const BillingEntitlementRuntimeRefundCreditClaimSchema =
  GeneratedBillingEntitlementRuntimeRefundCreditClaimSchema;
export const BillingEntitlementRuntimeSchemaVersionSchema = GeneratedBillingEntitlementRuntimeSchemaVersionSchema;
export const BillingEntitlementRuntimeSnapshotStateSchema = GeneratedBillingEntitlementRuntimeSnapshotStateSchema;
export const BillingEntitlementRuntimeSourceSchema = GeneratedBillingEntitlementRuntimeSourceSchema;

export type BillingEntitlementRuntimeConsumptionState = GeneratedBillingEntitlementRuntimeConsumptionState;
export type BillingEntitlementRuntimeNonClaim = GeneratedBillingEntitlementRuntimeNonClaim;
export type BillingEntitlementRuntimeOperation = GeneratedBillingEntitlementRuntimeOperation;
export type BillingEntitlementRuntimeSnapshotState = GeneratedBillingEntitlementRuntimeSnapshotState;
