import type { BrowserControlFullCatalogSettingSeed } from './browser-control-full-catalog-schema';
export const BrowserControlFullCatalogData3: readonly BrowserControlFullCatalogSettingSeed[] = [
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-006',
    637,
    859,
    'Allow approved executable paths only.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-007',
    638,
    860,
    'Allow signed browser executables only.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-008',
    639,
    861,
    'Block unsigned browser-like processes.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-009',
    640,
    862,
    'Block portable browser folders.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-010',
    641,
    863,
    'Block browser installation.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-011',
    642,
    864,
    'Detect browser installation.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-012',
    643,
    865,
    'Notify parent on browser installation.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-013',
    644,
    866,
    'Require approval for browser installation.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-014',
    645,
    867,
    'Block browser updater if it breaks managed support.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-015',
    646,
    868,
    'Allow browser updater.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-016',
    647,
    869,
    'Allow only specific browser versions.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-017',
    648,
    870,
    'Block unsupported browser versions.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-018',
    649,
    871,
    'Block browser command-line flags that disable controls.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-019',
    650,
    872,
    'Block remote debugging unless Ocentra owns the session.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-020',
    651,
    873,
    'Block child-launched CDP bridge.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-021',
    652,
    874,
    'Kill orphaned managed browser process.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-022',
    653,
    875,
    'Roll back failed process block.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-023',
    654,
    876,
    'Audit process block result.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-001',
    655,
    882,
    'Show warning text.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-002',
    656,
    883,
    'Show block reason.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-003',
    657,
    884,
    'Show ask-parent state.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-004',
    658,
    885,
    'Show time left.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-005',
    659,
    886,
    'Show daily budget left.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-006',
    660,
    887,
    'Show session budget left.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-007',
    661,
    888,
    'Show managed browser required message.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-008',
    662,
    889,
    'Show unmanaged browser closed message.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-009',
    663,
    890,
    'Show download blocked message.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-010',
    664,
    891,
    'Show approval pending message.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-011',
    665,
    892,
    'Show approval approved message.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-012',
    666,
    893,
    'Show approval denied message.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-013',
    667,
    894,
    'Show parent note.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-014',
    668,
    895,
    'Show safe page after block.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-015',
    669,
    896,
    'Show open managed browser action.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-016',
    670,
    897,
    'Show request access action.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-017',
    671,
    898,
    'Show request more time action.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-018',
    672,
    899,
    'Hide sensitive rule details.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-019',
    673,
    900,
    'Hide parent-only diagnostics.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-020',
    674,
    901,
    'Use age-appropriate text preset.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-021',
    675,
    902,
    'Use silent enforcement.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-022',
    676,
    903,
    'Use visible enforcement.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-023',
    677,
    904,
    'Allow child to retry after parent action.',
  ],
  [
    'browser-catalog-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    22,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings',
    'Child-Facing Experience Settings',
    27,
    'browser-catalog-child-facing-experience-settings-child-facing-experience-settings-024',
    678,
    905,
    'Allow child to view allowed alternatives.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-001',
    679,
    911,
    'Show managed browser status.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-002',
    680,
    912,
    'Show managed setup health.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-003',
    681,
    913,
    'Show recent exact URL.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-004',
    682,
    914,
    'Show recent domain/title.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-005',
    683,
    915,
    'Show recent active tab.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-006',
    684,
    916,
    'Show tab-list-only evidence.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-007',
    685,
    917,
    'Show unmanaged browser use.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-008',
    686,
    918,
    'Show unsupported browser use.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-009',
    687,
    919,
    'Show browser app time.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-010',
    688,
    920,
    'Show site/domain time.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-011',
    689,
    921,
    'Show category time.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-012',
    690,
    922,
    'Show download events.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-013',
    691,
    923,
    'Show blocked downloads.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-014',
    692,
    924,
    'Show policy decisions.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-015',
    693,
    925,
    'Show block results.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-016',
    694,
    926,
    'Show ask-parent results.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-017',
    695,
    927,
    'Show time budget state.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-018',
    696,
    928,
    'Show source/capability state.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-019',
    697,
    929,
    'Show evidence freshness.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-020',
    698,
    930,
    'Show stale/degraded state.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-021',
    699,
    931,
    'Show adapter errors.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-022',
    700,
    932,
    'Show platform unavailable controls.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-023',
    701,
    933,
    'Show local-only custody label.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-024',
    702,
    934,
    'Show LAN live source.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-025',
    703,
    935,
    'Show parent cache source.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-026',
    704,
    936,
    'Show parent export/report source.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-027',
    705,
    937,
    'Hide exact URL by default.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-028',
    706,
    938,
    'Require reveal for exact URL.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-029',
    707,
    939,
    'Summarize by category.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-030',
    708,
    940,
    'Summarize by domain.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-031',
    709,
    941,
    'Summarize by browser.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-032',
    710,
    942,
    'Summarize by child.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-033',
    711,
    943,
    'Summarize by device.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-034',
    712,
    944,
    'Summarize unmanaged bypass attempts.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-035',
    713,
    945,
    'Export browser report.',
  ],
  [
    'browser-catalog-parent-report-settings',
    'Parent Report Settings',
    23,
    'browser-catalog-parent-report-settings-parent-report-settings',
    'Parent Report Settings',
    28,
    'browser-catalog-parent-report-settings-parent-report-settings-036',
    714,
    946,
    'Redact exact details in report.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-001',
    715,
    952,
    'Portal may display managed status.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-002',
    716,
    953,
    'Portal may display exact URL.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-003',
    717,
    954,
    'Portal may display domain/title.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-004',
    718,
    955,
    'Portal may display unmanaged use.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-005',
    719,
    956,
    'Portal may display policy decisions.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-006',
    720,
    957,
    'Portal may display block results.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-007',
    721,
    958,
    'Portal may display time budget.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-008',
    722,
    959,
    'Portal may display source/capability.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-009',
    723,
    960,
    'Portal may display downloads.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-010',
    724,
    961,
    'Portal may display platform support matrix.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-011',
    725,
    962,
    'Portal may display setup guide.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-012',
    726,
    963,
    'Portal may display unavailable controls.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-013',
    727,
    964,
    'Portal may display local agent offline state.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-014',
    728,
    965,
    'Portal may display LAN source.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-015',
    729,
    966,
    'Portal may display parent cache source.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-016',
    730,
    967,
    'Portal may display parent export source.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-017',
    731,
    968,
    'Portal may display report-only summaries.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-018',
    732,
    969,
    'Portal must not run capture code.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-019',
    733,
    970,
    'Portal must not read browser profiles.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-020',
    734,
    971,
    'Portal must not connect directly to browser bridge.',
  ],
  [
    'browser-catalog-portal-display-settings',
    'Portal Display Settings',
    24,
    'browser-catalog-portal-display-settings-portal-display-settings',
    'Portal Display Settings',
    29,
    'browser-catalog-portal-display-settings-portal-display-settings-021',
    735,
    972,
    'Portal must not read SQLite or journal files directly.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-001',
    736,
    978,
    'View browser status.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-002',
    737,
    979,
    'Refresh browser status.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-003',
    738,
    980,
    'Preview policy.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-004',
    739,
    981,
    'Answer ask-parent request.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-005',
    740,
    982,
    'Approve once.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-006',
    741,
    983,
    'Deny once.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-007',
    742,
    984,
    'Extend time.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-008',
    743,
    985,
    'Cancel block.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-009',
    744,
    986,
    'Launch managed browser through agent where allowed.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-010',
    745,
    987,
    'Open setup guide.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-011',
    746,
    988,
    'Request managed setup repair.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-012',
    747,
    989,
    'Export browser report.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-013',
    748,
    990,
    'Delete browser evidence.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-014',
    749,
    991,
    'Change retention.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-015',
    750,
    992,
    'Show unavailable reason.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-016',
    751,
    993,
    'Show capability diagnostics.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-017',
    752,
    994,
    'Show bridge diagnostics.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-018',
    753,
    995,
    'Show policy audit.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-019',
    754,
    996,
    'Never send raw OS commands from portal.',
  ],
  [
    'browser-catalog-portal-action-settings',
    'Portal Action Settings',
    25,
    'browser-catalog-portal-action-settings-portal-action-settings',
    'Portal Action Settings',
    30,
    'browser-catalog-portal-action-settings-portal-action-settings-020',
    755,
    997,
    'Never connect to DevTools from portal.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-001',
    756,
    1003,
    'Allow Portal AI to summarize browser report.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-002',
    757,
    1004,
    'Allow Portal AI to explain policy decision.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-003',
    758,
    1005,
    'Allow Portal AI to draft parent note.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-004',
    759,
    1006,
    'Allow Portal AI to suggest rule changes.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-005',
    760,
    1007,
    'Allow Portal AI to cite evidence refs.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-006',
    761,
    1008,
    'Allow Portal AI to use URL metadata.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-007',
    762,
    1009,
    'Allow Portal AI to use domain/title metadata.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-008',
    763,
    1010,
    'Allow Portal AI to use source/custody labels.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-009',
    764,
    1011,
    'Allow Portal AI to use degraded state.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-010',
    765,
    1012,
    'Disallow raw page content.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-011',
    766,
    1013,
    'Disallow chat content.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-012',
    767,
    1014,
    'Disallow screenshots.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-013',
    768,
    1015,
    'Disallow raw protocol payloads.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-014',
    769,
    1016,
    'Require manual review before applying AI suggestion.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-015',
    770,
    1017,
    'Use local AI only.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-016',
    771,
    1018,
    'Use parent-authorized API AI only.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-017',
    772,
    1019,
    'Fall back to manual report if AI unavailable.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-018',
    773,
    1020,
    'Show AI unavailable state.',
  ],
  [
    'browser-catalog-portal-ai-settings',
    'Portal AI Settings',
    26,
    'browser-catalog-portal-ai-settings-portal-ai-settings',
    'Portal AI Settings',
    31,
    'browser-catalog-portal-ai-settings-portal-ai-settings-019',
    774,
    1021,
    'Show AI confidence/reason where available.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-001',
    775,
    1027,
    'Use child local live data.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-002',
    776,
    1028,
    'Use LAN live data.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-003',
    777,
    1029,
    'Use parent cache.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-004',
    778,
    1030,
    'Use parent-owned export.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-005',
    779,
    1031,
    'Use parent report.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-006',
    780,
    1032,
    'Mark unavailable.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-007',
    781,
    1033,
    'Do not use Ocentra-hosted storage for browser evidence by default.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-008',
    782,
    1034,
    'Allow parent-owned storage sync.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-009',
    783,
    1035,
    'Disable browser evidence cloud sync.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-010',
    784,
    1036,
    'Allow report compilation from redacted evidence refs.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-011',
    785,
    1037,
    'Use source/custody label in every browser row.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-012',
    786,
    1038,
    'Require custody label before Portal display.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-013',
    787,
    1039,
    'Require custody label before AI summary.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-014',
    788,
    1040,
    'Require custody label before export.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-015',
    789,
    1041,
    'Show stale parent cache separately from live child data.',
  ],
  [
    'browser-catalog-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    27,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings',
    'Data Source And Custody Settings',
    32,
    'browser-catalog-data-source-and-custody-settings-data-source-and-custody-settings-016',
    790,
    1042,
    'Show offline child device separately from no activity.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-001',
    791,
    1048,
    'Keep fresh-only browser state.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-002',
    792,
    1049,
    'Keep until device reset.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-003',
    793,
    1050,
    'Keep 24 hours.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-004',
    794,
    1051,
    'Keep 7 days.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-005',
    795,
    1052,
    'Keep 30 days.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-006',
    796,
    1053,
    'Keep custom duration.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-007',
    797,
    1054,
    'Delete expired exact URLs.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-008',
    798,
    1055,
    'Delete expired titles.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-009',
    799,
    1056,
    'Keep redacted domain summary.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-010',
    800,
    1057,
    'Keep policy audit longer than raw evidence.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-011',
    801,
    1058,
    'Keep parent override audit.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-012',
    802,
    1059,
    'Keep block audit.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-013',
    803,
    1060,
    'Keep unmanaged bypass audit.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-014',
    804,
    1061,
    'Keep download audit.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-015',
    805,
    1062,
    'Delete browser evidence on parent request.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-016',
    806,
    1063,
    'Delete browser evidence when child profile removed.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-017',
    807,
    1064,
    'Delete managed browser profile data on schedule.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-018',
    808,
    1065,
    'Export before delete.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-019',
    809,
    1066,
    'Redact before export.',
  ],
  [
    'browser-catalog-retention-settings',
    'Retention Settings',
    28,
    'browser-catalog-retention-settings-retention-settings',
    'Retention Settings',
    33,
    'browser-catalog-retention-settings-retention-settings-020',
    810,
    1067,
    'Show retention status to parent.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-001',
    811,
    1073,
    'Audit policy decision.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-002',
    812,
    1074,
    'Audit rule id.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-003',
    813,
    1075,
    'Audit policy version.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-004',
    814,
    1076,
    'Audit child profile.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-005',
    815,
    1077,
    'Audit device id.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-006',
    816,
    1078,
    'Audit browser family/version.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-007',
    817,
    1079,
    'Audit managed/unmanaged state.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-008',
    818,
    1080,
    'Audit capability status.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-009',
    819,
    1081,
    'Audit evidence ref.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-010',
    820,
    1082,
    'Audit AI ref.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-011',
    821,
    1083,
    'Audit adapter result.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-012',
    822,
    1084,
    'Audit enforcement mechanism.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-013',
    823,
    1085,
    'Audit enforcement outcome.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-014',
    824,
    1086,
    'Audit timer state.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-015',
    825,
    1087,
    'Audit parent override.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-016',
    826,
    1088,
    'Audit child request.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-017',
    827,
    1089,
    'Audit rollback.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-018',
    828,
    1090,
    'Audit failed block.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-019',
    829,
    1091,
    'Audit failed termination.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-020',
    830,
    1092,
    'Audit degraded/unavailable state.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-021',
    831,
    1093,
    'Audit custody/source label.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-022',
    832,
    1094,
    'Audit download action.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-023',
    833,
    1095,
    'Audit network/domain fallback.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-024',
    834,
    1096,
    'Audit conflict resolution rule.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-025',
    835,
    1097,
    'Audit manual parent change.',
  ],
  [
    'browser-catalog-audit-settings',
    'Audit Settings',
    29,
    'browser-catalog-audit-settings-audit-settings',
    'Audit Settings',
    34,
    'browser-catalog-audit-settings-audit-settings-026',
    836,
    1098,
    'Audit setup/provisioning change.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-001',
    837,
    1104,
    'If managed profile missing: observe.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-002',
    838,
    1105,
    'If managed profile missing: ask.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-003',
    839,
    1106,
    'If managed profile missing: block until setup.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-004',
    840,
    1107,
    'If bridge missing: observe.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-005',
    841,
    1108,
    'If bridge missing: warn.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-006',
    842,
    1109,
    'If bridge missing: ask.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-007',
    843,
    1110,
    'If bridge missing: block exact web rules.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-008',
    844,
    1111,
    'If extension disabled: observe.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-009',
    845,
    1112,
    'If extension disabled: warn.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-010',
    846,
    1113,
    'If extension disabled: block.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-011',
    847,
    1114,
    'If native host missing: repair prompt.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-012',
    848,
    1115,
    'If browser unsupported: monitor only.',
  ],
];
