import {
  OptionalSocialFeedVideoRouteGateTextSchema as GeneratedOptionalSocialFeedVideoRouteGateTextSchema,
  SocialFeedVideoRouteGateSourceEvidenceIdsSchema as GeneratedSocialFeedVideoRouteGateSourceEvidenceIdsSchema,
  BrowserSocialFeedVideoRouteGateSchemaVersion as GeneratedBrowserSocialFeedVideoRouteGateSchemaVersion,
  BrowserSocialFeedVideoRouteGatePlanIdSchema as GeneratedBrowserSocialFeedVideoRouteGatePlanIdSchema,
  BrowserSocialFeedVideoRouteGateTargetKindSchema as GeneratedBrowserSocialFeedVideoRouteGateTargetKindSchema,
  BrowserSocialFeedVideoRouteGateActionSchema as GeneratedBrowserSocialFeedVideoRouteGateActionSchema,
  BrowserSocialFeedVideoRouteGateStateSchema as GeneratedBrowserSocialFeedVideoRouteGateStateSchema,
  BrowserSocialFeedVideoRouteGateReasonSchema as GeneratedBrowserSocialFeedVideoRouteGateReasonSchema,
  BrowserSocialFeedVideoRouteGateReasonsSchema as GeneratedBrowserSocialFeedVideoRouteGateReasonsSchema,
} from './generated-browser-social-feed-video-route-gate-values';
import type {
  BrowserSocialFeedVideoRouteGateAction as GeneratedBrowserSocialFeedVideoRouteGateAction,
  BrowserSocialFeedVideoRouteGateReason as GeneratedBrowserSocialFeedVideoRouteGateReason,
  BrowserSocialFeedVideoRouteGateState as GeneratedBrowserSocialFeedVideoRouteGateState,
  BrowserSocialFeedVideoRouteGateTargetKind as GeneratedBrowserSocialFeedVideoRouteGateTargetKind,
} from './generated-browser-social-feed-video-route-gate-values';

export const OptionalSocialFeedVideoRouteGateTextSchema = GeneratedOptionalSocialFeedVideoRouteGateTextSchema;
export const SocialFeedVideoRouteGateSourceEvidenceIdsSchema = GeneratedSocialFeedVideoRouteGateSourceEvidenceIdsSchema;
export const BrowserSocialFeedVideoRouteGateSchemaVersion = GeneratedBrowserSocialFeedVideoRouteGateSchemaVersion;
export const BrowserSocialFeedVideoRouteGatePlanIdSchema = GeneratedBrowserSocialFeedVideoRouteGatePlanIdSchema;
export const BrowserSocialFeedVideoRouteGateTargetKindSchema = GeneratedBrowserSocialFeedVideoRouteGateTargetKindSchema;
export const BrowserSocialFeedVideoRouteGateActionSchema = GeneratedBrowserSocialFeedVideoRouteGateActionSchema;
export const BrowserSocialFeedVideoRouteGateStateSchema = GeneratedBrowserSocialFeedVideoRouteGateStateSchema;
export const BrowserSocialFeedVideoRouteGateReasonSchema = GeneratedBrowserSocialFeedVideoRouteGateReasonSchema;
export const BrowserSocialFeedVideoRouteGateReasonsSchema = GeneratedBrowserSocialFeedVideoRouteGateReasonsSchema;
export type BrowserSocialFeedVideoRouteGateAction = GeneratedBrowserSocialFeedVideoRouteGateAction;
export type BrowserSocialFeedVideoRouteGateReason = GeneratedBrowserSocialFeedVideoRouteGateReason;
export type BrowserSocialFeedVideoRouteGateState = GeneratedBrowserSocialFeedVideoRouteGateState;
export type BrowserSocialFeedVideoRouteGateTargetKind = GeneratedBrowserSocialFeedVideoRouteGateTargetKind;
