import type { BrowserControlFullCatalogSettingSeed } from './browser-control-full-catalog-schema';
export const BrowserControlFullCatalogData4: readonly BrowserControlFullCatalogSettingSeed[] = [
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-013',
    849,
    1116,
    'If browser unsupported: ask.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-014',
    850,
    1117,
    'If browser unsupported: block.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-015',
    851,
    1118,
    'If evidence stale: do not enforce exact URL rule.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-016',
    852,
    1119,
    'If evidence stale: allow but report.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-017',
    853,
    1120,
    'If evidence stale: ask.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-018',
    854,
    1121,
    'If network adapter unavailable: continue managed browser controls.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-019',
    855,
    1122,
    'If process control unavailable: fall back to warn/ask.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-020',
    856,
    1123,
    'If enforcement fails: rollback and audit.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-021',
    857,
    1124,
    'If rollback fails: notify parent.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-022',
    858,
    1125,
    'If child device offline: use last known report only.',
  ],
  [
    'browser-catalog-capability-failure-settings',
    'Capability Failure Settings',
    30,
    'browser-catalog-capability-failure-settings-capability-failure-settings',
    'Capability Failure Settings',
    35,
    'browser-catalog-capability-failure-settings-capability-failure-settings-023',
    859,
    1126,
    'If platform unsupported: show unavailable.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-001',
    860,
    1132,
    'Specific URL beats domain.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-002',
    861,
    1133,
    'Domain beats category.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-003',
    862,
    1134,
    'Child-specific rule beats family default.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-004',
    863,
    1135,
    'Device-specific rule beats child default.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-005',
    864,
    1136,
    'Temporary override beats static rule.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-006',
    865,
    1137,
    'Block beats allow.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-007',
    866,
    1138,
    'Allow beats block for parent-approved exception.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-008',
    867,
    1139,
    'Ask beats block when parent approval is pending.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-009',
    868,
    1140,
    'Time limit beats allow.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-010',
    869,
    1141,
    'Bedtime rule beats daily quota.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-011',
    870,
    1142,
    'School mode allowlist beats entertainment block.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-012',
    871,
    1143,
    'Download block beats site allow.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-013',
    872,
    1144,
    'Managed exact evidence beats network evidence.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-014',
    873,
    1145,
    'Fresh evidence beats stale evidence.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-015',
    874,
    1146,
    'Higher confidence AI decision beats lower confidence only in dry-run.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-016',
    875,
    1147,
    'Local deterministic policy beats AI suggestion.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-017',
    876,
    1148,
    'Parent manual override beats AI suggestion.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-018',
    877,
    1149,
    'Emergency allow beats normal policy.',
  ],
  [
    'browser-catalog-conflict-resolution-settings',
    'Conflict Resolution Settings',
    31,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings',
    'Conflict Resolution Settings',
    36,
    'browser-catalog-conflict-resolution-settings-conflict-resolution-settings-019',
    878,
    1150,
    'Emergency block beats normal policy.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-001',
    879,
    1157,
    'Allow AI to reference browser evidence ids.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-002',
    880,
    1158,
    'Allow AI to reference URL metadata.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-003',
    881,
    1159,
    'Allow AI to reference domain/origin.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-004',
    882,
    1160,
    'Allow AI to reference page title.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-005',
    883,
    1161,
    'Allow AI to reference active certainty.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-006',
    884,
    1162,
    'Allow AI to reference recent local context.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-007',
    885,
    1163,
    'Allow AI to reference parent rule context.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-008',
    886,
    1164,
    'Allow AI to reference source/custody label.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-009',
    887,
    1165,
    'Allow AI to reference degraded state.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-010',
    888,
    1166,
    'Allow AI to reference browser app/session time.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-011',
    889,
    1167,
    'Allow AI to reference network/domain evidence.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-012',
    890,
    1168,
    'Allow AI to reference download metadata.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-013',
    891,
    1169,
    'Require AI output to cite evidence refs.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-014',
    892,
    1170,
    'Require deterministic policy after AI.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-015',
    893,
    1171,
    'Use AI only for classification.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-016',
    894,
    1172,
    'Use AI only for report explanation.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-017',
    895,
    1173,
    'Use AI only in dry-run.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-018',
    896,
    1174,
    'Do not send raw page content to AI.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-019',
    897,
    1175,
    'Do not send screenshots to AI.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-020',
    898,
    1176,
    'Do not send chat content to AI.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-021',
    899,
    1177,
    'Do not send raw protocol payloads to AI.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-022',
    900,
    1178,
    'Treat AI unavailable as unknown.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-023',
    901,
    1179,
    'Treat AI unavailable as ask parent.',
  ],
  [
    'browser-catalog-local-ai-browser-settings',
    'Local AI Browser Settings',
    32,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings',
    'Local AI Browser Settings',
    37,
    'browser-catalog-local-ai-browser-settings-local-ai-browser-settings-024',
    902,
    1180,
    'Treat AI unavailable as deterministic rules only.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-001',
    903,
    1187,
    'Do not collect page body text.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-002',
    904,
    1188,
    'Do not collect chat message content.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-003',
    905,
    1189,
    'Do not collect screenshots for browser rules.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-004',
    906,
    1190,
    'Do not collect keystrokes.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-005',
    907,
    1191,
    'Do not collect form values.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-006',
    908,
    1192,
    'Do not collect passwords.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-007',
    909,
    1193,
    'Do not collect cookies.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-008',
    910,
    1194,
    'Do not collect tokens.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-009',
    911,
    1195,
    'Do not collect browser local storage.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-010',
    912,
    1196,
    'Do not collect browser session storage.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-011',
    913,
    1197,
    'Do not collect browser secrets.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-012',
    914,
    1198,
    'Do not collect decrypted HTTPS payloads.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-013',
    915,
    1199,
    'Do not store raw DevTools protocol dumps.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-014',
    916,
    1200,
    'Do not infer exact URL from window title.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-015',
    917,
    1201,
    'Do not infer exact URL from network destination.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-016',
    918,
    1202,
    'Do not attach to default personal profile bridge.',
  ],
  [
    'browser-catalog-never-collect-settings',
    'Never-Collect Settings',
    33,
    'browser-catalog-never-collect-settings-never-collect-settings',
    'Never-Collect Settings',
    38,
    'browser-catalog-never-collect-settings-never-collect-settings-017',
    919,
    1203,
    'Do not connect Portal directly to browser bridge.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-001',
    920,
    1211,
    'Enable Windows managed Edge.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-002',
    921,
    1212,
    'Enable Windows managed Chrome.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-003',
    922,
    1213,
    'Enable Windows Chrome for Testing.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-004',
    923,
    1214,
    'Enable Windows process observation.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-005',
    924,
    1215,
    'Enable Windows foreground window observation.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-006',
    925,
    1216,
    'Enable Windows process termination.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-007',
    926,
    1217,
    'Enable Windows app-control blocking.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-008',
    927,
    1218,
    'Enable Windows browser executable allowlist.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-009',
    928,
    1219,
    'Enable Windows network filtering.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-010',
    929,
    1220,
    'Enable Windows DNS/domain filtering.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-011',
    930,
    1221,
    'Enable Windows managed extension native host.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-012',
    931,
    1222,
    'Enable Windows CDP managed bridge.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-013',
    932,
    1223,
    'Enable Windows browser policy provisioning.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-014',
    933,
    1224,
    'Mark Windows AppLocker/WDAC controls as manual-required until proven.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-windows',
    'Windows',
    39,
    'browser-catalog-platform-settings-windows-015',
    934,
    1225,
    'Mark Windows WFP/domain controls as manual-required until proven.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-macos',
    'macOS',
    40,
    'browser-catalog-platform-settings-macos-001',
    935,
    1229,
    'Enable macOS managed browser profile.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-macos',
    'macOS',
    40,
    'browser-catalog-platform-settings-macos-002',
    936,
    1230,
    'Enable macOS browser extension/native host.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-macos',
    'macOS',
    40,
    'browser-catalog-platform-settings-macos-003',
    937,
    1231,
    'Enable macOS process observation.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-macos',
    'macOS',
    40,
    'browser-catalog-platform-settings-macos-004',
    938,
    1232,
    'Enable macOS process control.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-macos',
    'macOS',
    40,
    'browser-catalog-platform-settings-macos-005',
    939,
    1233,
    'Enable macOS browser policy profile where supported.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-macos',
    'macOS',
    40,
    'browser-catalog-platform-settings-macos-006',
    940,
    1234,
    'Enable macOS network/content filter where entitled.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-macos',
    'macOS',
    40,
    'browser-catalog-platform-settings-macos-007',
    941,
    1235,
    'Mark macOS controls unavailable until platform proof exists.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-linux',
    'Linux',
    41,
    'browser-catalog-platform-settings-linux-001',
    942,
    1239,
    'Enable Linux managed browser profile.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-linux',
    'Linux',
    41,
    'browser-catalog-platform-settings-linux-002',
    943,
    1240,
    'Enable Linux extension/native host.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-linux',
    'Linux',
    41,
    'browser-catalog-platform-settings-linux-003',
    944,
    1241,
    'Enable Linux process observation.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-linux',
    'Linux',
    41,
    'browser-catalog-platform-settings-linux-004',
    945,
    1242,
    'Enable Linux process control.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-linux',
    'Linux',
    41,
    'browser-catalog-platform-settings-linux-005',
    946,
    1243,
    'Enable Linux firewall/domain filtering.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-linux',
    'Linux',
    41,
    'browser-catalog-platform-settings-linux-006',
    947,
    1244,
    'Mark distro-specific controls manual-required.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-android',
    'Android',
    42,
    'browser-catalog-platform-settings-android-001',
    948,
    1248,
    'Enable Android browser app observation.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-android',
    'Android',
    42,
    'browser-catalog-platform-settings-android-002',
    949,
    1249,
    'Enable Android app suspension.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-android',
    'Android',
    42,
    'browser-catalog-platform-settings-android-003',
    950,
    1250,
    'Enable Android package hiding.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-android',
    'Android',
    42,
    'browser-catalog-platform-settings-android-004',
    951,
    1251,
    'Enable Android device-owner browser controls.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-android',
    'Android',
    42,
    'browser-catalog-platform-settings-android-005',
    952,
    1252,
    'Enable Android managed Chrome config where available.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-android',
    'Android',
    42,
    'browser-catalog-platform-settings-android-006',
    953,
    1253,
    'Enable Android always-on VPN/domain filtering.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-android',
    'Android',
    42,
    'browser-catalog-platform-settings-android-007',
    954,
    1254,
    'Enable Android accessibility-assisted foreground evidence where explicitly approved.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-android',
    'Android',
    42,
    'browser-catalog-platform-settings-android-008',
    955,
    1256,
    'Enable Android owned browser/WebView path.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-android',
    'Android',
    42,
    'browser-catalog-platform-settings-android-009',
    956,
    1257,
    'Mark exact arbitrary mobile browser URL unavailable unless adapter proof exists.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-ios-and-ipados',
    'iOS And iPadOS',
    43,
    'browser-catalog-platform-settings-ios-and-ipados-001',
    957,
    1262,
    'Enable iOS Screen Time app/category/domain controls.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-ios-and-ipados',
    'iOS And iPadOS',
    43,
    'browser-catalog-platform-settings-ios-and-ipados-002',
    958,
    1263,
    'Enable iOS Managed Settings shielding.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-ios-and-ipados',
    'iOS And iPadOS',
    43,
    'browser-catalog-platform-settings-ios-and-ipados-003',
    959,
    1264,
    'Enable iOS web domain shields.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-ios-and-ipados',
    'iOS And iPadOS',
    43,
    'browser-catalog-platform-settings-ios-and-ipados-004',
    960,
    1265,
    'Enable iOS MDM web content filtering.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-ios-and-ipados',
    'iOS And iPadOS',
    43,
    'browser-catalog-platform-settings-ios-and-ipados-005',
    961,
    1266,
    'Enable iOS Network Extension filtering where entitled.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-ios-and-ipados',
    'iOS And iPadOS',
    43,
    'browser-catalog-platform-settings-ios-and-ipados-006',
    962,
    1267,
    'Enable iOS Safari/domain-level rules where approved.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-ios-and-ipados',
    'iOS And iPadOS',
    43,
    'browser-catalog-platform-settings-ios-and-ipados-007',
    963,
    1268,
    'Mark exact arbitrary browser URL capture unavailable unless Apple-approved proof exists.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-ios-and-ipados',
    'iOS And iPadOS',
    43,
    'browser-catalog-platform-settings-ios-and-ipados-008',
    964,
    1270,
    'Mark non-entitled controls unavailable.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-web-parent-portal',
    'Web Parent Portal',
    44,
    'browser-catalog-platform-settings-web-parent-portal-001',
    965,
    1274,
    'Enable browser policy authoring.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-web-parent-portal',
    'Web Parent Portal',
    44,
    'browser-catalog-platform-settings-web-parent-portal-002',
    966,
    1275,
    'Enable browser report viewing.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-web-parent-portal',
    'Web Parent Portal',
    44,
    'browser-catalog-platform-settings-web-parent-portal-003',
    967,
    1276,
    'Enable policy preview.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-web-parent-portal',
    'Web Parent Portal',
    44,
    'browser-catalog-platform-settings-web-parent-portal-004',
    968,
    1277,
    'Disable child-device capture in web portal.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-web-parent-portal',
    'Web Parent Portal',
    44,
    'browser-catalog-platform-settings-web-parent-portal-005',
    969,
    1278,
    'Disable direct local file reads in web portal.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-web-parent-portal',
    'Web Parent Portal',
    44,
    'browser-catalog-platform-settings-web-parent-portal-006',
    970,
    1279,
    'Disable direct browser bridge access in web portal.',
  ],
  [
    'browser-catalog-platform-settings',
    'Platform Settings',
    34,
    'browser-catalog-platform-settings-web-parent-portal',
    'Web Parent Portal',
    44,
    'browser-catalog-platform-settings-web-parent-portal-007',
    971,
    1280,
    'Show web authoring as control surface only.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-001',
    972,
    1286,
    'Install managed browser support.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-002',
    973,
    1287,
    'Repair managed browser support.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-003',
    974,
    1288,
    'Provision managed profile.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-004',
    975,
    1289,
    'Provision browser policy.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-005',
    976,
    1290,
    'Provision native messaging host.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-006',
    977,
    1291,
    'Provision managed extension.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-007',
    978,
    1292,
    'Verify extension heartbeat.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-008',
    979,
    1293,
    'Verify CDP bridge.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-009',
    980,
    1294,
    'Verify localhost bridge only.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-010',
    981,
    1295,
    'Verify profile is Ocentra-owned.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-011',
    982,
    1296,
    'Verify default browser route.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-012',
    983,
    1297,
    'Verify HTTP protocol route.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-013',
    984,
    1298,
    'Verify HTTPS protocol route.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-014',
    985,
    1299,
    'Verify unmanaged browser detection.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-015',
    986,
    1300,
    'Verify process termination permission.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-016',
    987,
    1301,
    'Verify network/domain filtering permission.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-017',
    988,
    1302,
    'Verify download monitoring permission.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-018',
    989,
    1303,
    'Verify platform capability matrix.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-019',
    990,
    1304,
    'Show setup incomplete state.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-020',
    991,
    1305,
    'Show setup ready state.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-021',
    992,
    1306,
    'Show setup degraded state.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-022',
    993,
    1307,
    'Allow parent to run setup check.',
  ],
  [
    'browser-catalog-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    35,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings',
    'Setup And Provisioning Settings',
    45,
    'browser-catalog-setup-and-provisioning-settings-setup-and-provisioning-settings-023',
    994,
    1308,
    'Allow parent to export setup diagnostics.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-001',
    995,
    1314,
    'Notify parent on blocked site.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-002',
    996,
    1315,
    'Notify parent on ask-parent request.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-003',
    997,
    1316,
    'Notify parent on unmanaged browser.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-004',
    998,
    1317,
    'Notify parent on repeated bypass attempts.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-005',
    999,
    1318,
    'Notify parent on managed bridge failure.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-006',
    1000,
    1319,
    'Notify parent on browser policy removal.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-007',
    1001,
    1320,
    'Notify parent on extension disabled.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-008',
    1002,
    1321,
    'Notify parent on new browser found.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-009',
    1003,
    1322,
    'Notify parent on risky download.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-010',
    1004,
    1323,
    'Notify parent on time budget warning.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-011',
    1005,
    1324,
    'Notify parent on time budget exhausted.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-012',
    1006,
    1325,
    'Notify child on warning.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-013',
    1007,
    1326,
    'Notify child on block.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-014',
    1008,
    1327,
    'Notify child on parent approval.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-015',
    1009,
    1328,
    'Notify child on parent denial.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-016',
    1010,
    1329,
    'Quiet hours for parent notifications.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-017',
    1011,
    1330,
    'Escalate after N unmanaged attempts.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-018',
    1012,
    1331,
    'Escalate after N blocked downloads.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-019',
    1013,
    1332,
    'Escalate after N failed setup checks.',
  ],
  [
    'browser-catalog-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    36,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings',
    'Notifications And Escalation Settings',
    46,
    'browser-catalog-notifications-and-escalation-settings-notifications-and-escalation-settings-020',
    1014,
    1333,
    'Escalate to local-only report if notification provider unavailable.',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-001',
    1015,
    1340,
    'Do browser settings live in `parent-domain`, `activity-domain`, `agent-protocol-domain`, or a new policy-domain package?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-002',
    1016,
    1342,
    'Which settings are actual parent-editable controls versus internal capability state?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-003',
    1017,
    1344,
    'Which settings are per-family defaults versus per-child overrides?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-004',
    1018,
    1345,
    'Which settings are per-device only because capability differs by OS?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-005',
    1019,
    1346,
    'Which settings need Effect Schema brands and decode helpers first?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-006',
    1020,
    1347,
    'What is the minimal MVP set for Windows?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-007',
    1021,
    1348,
    'Should exact URL policy require managed browser for MVP?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-008',
    1022,
    1349,
    'Should unmanaged browser handling default to monitor, warn, ask, relaunch, or block?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-009',
    1023,
    1351,
    'Should strict unmanaged blocking require a setup checklist first?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-010',
    1024,
    1352,
    'Should parent be allowed to block all unknown browser-like processes?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-011',
    1025,
    1353,
    'What is the first download policy surface: report only, ask, or block?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-012',
    1026,
    1354,
    'Should search terms ever be stored, or should search rules use redacted URL metadata only?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-013',
    1027,
    1356,
    'Should page title be stored by default or only when rule matches?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-014',
    1028,
    1357,
    'What is the default retention for exact URLs?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-015',
    1029,
    1358,
    'What is the default retention for domain summaries?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-016',
    1030,
    1359,
    'What is the default retention for policy audit?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-017',
    1031,
    1360,
    'What is the first conflict-resolution rule set?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-018',
    1032,
    1361,
    'What is the first child-facing block/warn/request flow?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-019',
    1033,
    1362,
    'What is the first parent override flow?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-020',
    1034,
    1363,
    'What settings must be hidden until platform proof exists?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-021',
    1035,
    1364,
    'What settings must be visible but unavailable so parents understand limits?',
  ],
  [
    'browser-catalog-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    37,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts',
    'Gaps To Decide Before UI Contracts',
    47,
    'browser-catalog-gaps-to-decide-before-ui-contracts-gaps-to-decide-before-ui-contracts-022',
    1036,
    1365,
    'What settings belong in guide text instead of controls?',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-001',
    1037,
    1371,
    'Enable browser controls.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-002',
    1038,
    1372,
    'Mode: observe, dry-run, warn/ask, enforce.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-003',
    1039,
    1373,
    'Require managed browser for exact web rules.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-004',
    1040,
    1374,
    'Scan installed browsers.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-005',
    1041,
    1375,
    'Scan running browsers.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-006',
    1042,
    1376,
    'Detect unmanaged browsers.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-007',
    1043,
    1377,
    'Allow managed browser.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-008',
    1044,
    1378,
    'Launch or repair managed browser setup.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-009',
    1045,
    1379,
    'Allow URL/domain/title evidence from managed browser.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-010',
    1046,
    1380,
    'Redact query strings.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-011',
    1047,
    1381,
    'Keep exact URL evidence for selected retention.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-012',
    1048,
    1382,
    'Allow unmanaged browser: monitor, warn, ask, relaunch, block.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-013',
    1049,
    1383,
    'Choose covered browsers: Edge, Chrome, Chrome for Testing, unsupported as unmanaged.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-014',
    1050,
    1385,
    'Rule targets: exact URL, domain/origin, category, browser process, browser session, capability state.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-015',
    1051,
    1387,
    'Rule actions: allow, warn, ask, limit, block.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-016',
    1052,
    1388,
    'Time budgets: daily, session, site/domain, grace, blackout.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-017',
    1053,
    1389,
    'Parent approvals: new domain, blocked site, unmanaged browser, downloads, time extension.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-018',
    1054,
    1391,
    'Reports: managed status, recent URL/domain/title, unmanaged use, decisions, block results, time budget, source/capability.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-019',
    1055,
    1393,
    'Proof requirement: process, foreground, managed tab list, proven active tab, fresh only, stale/degraded.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-020',
    1056,
    1395,
    'Data custody: child local, LAN live, parent cache, parent export/report, unavailable.',
  ],
  [
    'browser-catalog-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    38,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set',
    'Candidate MVP Setting Set',
    48,
    'browser-catalog-candidate-mvp-setting-set-candidate-mvp-setting-set-021',
    1057,
    1397,
    'Audit: policy decision, evidence ref, adapter result, timer state, parent override, rollback, policy version.',
  ],
];
