import type { BrowserControlFullCatalogSettingSeed } from './browser-control-full-catalog-schema';
export const BrowserControlFullCatalogData0B: readonly BrowserControlFullCatalogSettingSeed[] = [
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-006',
    72,
    192,
    'Most specific target wins.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-007',
    73,
    193,
    'Child override wins family default.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-008',
    74,
    194,
    'Device override wins child default.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-009',
    75,
    195,
    'Temporary parent override wins.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-010',
    76,
    196,
    'Emergency/school mode wins.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-011',
    77,
    197,
    'Latest rule wins.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-012',
    78,
    198,
    'Highest severity wins.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-013',
    79,
    199,
    'Safer evidence wins weaker evidence.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-014',
    80,
    200,
    'Managed exact URL wins network/domain guess.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-001',
    81,
    206,
    'Enable browser controls.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-002',
    82,
    207,
    'Disable browser controls.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-003',
    83,
    208,
    'Enable observe-only browser mode.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-004',
    84,
    209,
    'Enable browser dry-run decisions.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-005',
    85,
    210,
    'Enable enforcement for browser rules.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-006',
    86,
    211,
    'Require managed browser for exact web rules.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-007',
    87,
    212,
    'Allow browser controls while local agent is offline.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-008',
    88,
    213,
    'Require child device to be online before browser enforcement.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-009',
    89,
    214,
    'Enable browser rules for this family.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-010',
    90,
    215,
    'Enable browser rules for this child.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-011',
    91,
    216,
    'Enable browser rules for this device.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-012',
    92,
    217,
    'Enable browser rules for this platform.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-013',
    93,
    218,
    'Pause all browser rules until a chosen time.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-014',
    94,
    219,
    'Emergency allow all browser activity.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-015',
    95,
    220,
    'Emergency block all browser activity.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-016',
    96,
    221,
    'School mode browser preset.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-017',
    97,
    222,
    'Bedtime mode browser preset.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-018',
    98,
    223,
    'Travel mode browser preset.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-019',
    99,
    224,
    'Guest device browser preset.',
  ],
  [
    'browser-catalog-master-browser-control-settings',
    'Master Browser Control Settings',
    2,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings',
    'Master Browser Control Settings',
    7,
    'browser-catalog-master-browser-control-settings-master-browser-control-settings-020',
    100,
    225,
    'New device default browser preset.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-001',
    101,
    231,
    'Scan installed browsers.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-002',
    102,
    232,
    'Scan running browsers.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-003',
    103,
    233,
    'Scan default browser setting.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-004',
    104,
    234,
    'Scan browser versions.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-005',
    105,
    235,
    'Scan browser channels.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-006',
    106,
    236,
    'Scan browser executable signatures.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-007',
    107,
    237,
    'Scan browser executable hashes.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-008',
    108,
    238,
    'Scan browser install paths.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-009',
    109,
    239,
    'Scan browser profile readiness.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-010',
    110,
    240,
    'Scan browser extension install state.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-011',
    111,
    241,
    'Scan browser policy state.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-012',
    112,
    242,
    'Scan browser-like processes.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-013',
    113,
    243,
    'Scan portable browser locations.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-014',
    114,
    244,
    'Scan renamed browser executables.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-015',
    115,
    245,
    'Scan embedded WebView shells.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-016',
    116,
    246,
    'Scan Tor/private browsers.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-017',
    117,
    247,
    'Scan unknown Chromium forks.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-018',
    118,
    248,
    'Scan child-accessible browser shortcuts.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-019',
    119,
    249,
    'Scan protocol handlers such as HTTP and HTTPS.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-020',
    120,
    250,
    'Scan browser command lines for launch URLs when available.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-021',
    121,
    251,
    'Scan for unsupported browser state.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-022',
    122,
    252,
    'Scan for unmanaged browser state.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-023',
    123,
    253,
    'Notify parent when a new browser is found.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-024',
    124,
    254,
    'Ask parent before allowing a newly found browser.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-025',
    125,
    255,
    'Auto-classify new browser as unmanaged.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-026',
    126,
    256,
    'Auto-classify unknown browser as blocked.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-027',
    127,
    257,
    'Auto-classify unknown browser as monitor only.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-028',
    128,
    258,
    'Re-scan browser inventory on schedule.',
  ],
  [
    'browser-catalog-browser-discovery-settings',
    'Browser Discovery Settings',
    3,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings',
    'Browser Discovery Settings',
    8,
    'browser-catalog-browser-discovery-settings-browser-discovery-settings-029',
    129,
    259,
    'Re-scan browser inventory after install events.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-001',
    130,
    266,
    'Cover Microsoft Edge stable.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-002',
    131,
    267,
    'Cover Microsoft Edge beta/dev/canary.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-003',
    132,
    268,
    'Cover Chrome stable.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-004',
    133,
    269,
    'Cover Chrome beta/dev/canary.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-005',
    134,
    270,
    'Cover Chrome for Testing.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-006',
    135,
    271,
    'Cover Brave.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-007',
    136,
    272,
    'Cover Opera.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-008',
    137,
    273,
    'Cover Vivaldi.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-009',
    138,
    274,
    'Cover Firefox.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-010',
    139,
    275,
    'Cover Safari/WebKit.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-011',
    140,
    276,
    'Cover Android Chrome.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-012',
    141,
    277,
    'Cover Android browser apps.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-013',
    142,
    278,
    'Cover iOS Safari.',
  ],
];
