import {
  BrowserSocialVideoMetadataSchemaVersion as GeneratedBrowserSocialVideoMetadataSchemaVersion,
  BrowserSocialVideoMetadataEvidenceIdSchema as GeneratedBrowserSocialVideoMetadataEvidenceIdSchema,
  BrowserSocialVideoMetadataSourceKindSchema as GeneratedBrowserSocialVideoMetadataSourceKindSchema,
  BrowserSocialVideoMetadataStateSchema as GeneratedBrowserSocialVideoMetadataStateSchema,
  BrowserSocialVideoMetadataEvidenceSchema as GeneratedBrowserSocialVideoMetadataEvidenceSchema,
  decodeBrowserSocialVideoMetadataEvidence as GenerateddecodeBrowserSocialVideoMetadataEvidence,
  extractBrowserSocialVideoMetadata as GeneratedextractBrowserSocialVideoMetadata,
} from './generated-browser-social-video-metadata';
import type {
  BrowserSocialVideoMetadataEvidence as GeneratedBrowserSocialVideoMetadataEvidence,
  BrowserSocialVideoMetadataEvidenceId as GeneratedBrowserSocialVideoMetadataEvidenceId,
  BrowserSocialVideoMetadataExtractorInput as GeneratedBrowserSocialVideoMetadataExtractorInput,
  BrowserSocialVideoMetadataSourceKind as GeneratedBrowserSocialVideoMetadataSourceKind,
  BrowserSocialVideoMetadataState as GeneratedBrowserSocialVideoMetadataState,
} from './generated-browser-social-video-metadata';

export const BrowserSocialVideoMetadataSchemaVersion = GeneratedBrowserSocialVideoMetadataSchemaVersion;
export const BrowserSocialVideoMetadataEvidenceIdSchema = GeneratedBrowserSocialVideoMetadataEvidenceIdSchema;
export const BrowserSocialVideoMetadataSourceKindSchema = GeneratedBrowserSocialVideoMetadataSourceKindSchema;
export const BrowserSocialVideoMetadataStateSchema = GeneratedBrowserSocialVideoMetadataStateSchema;
export const BrowserSocialVideoMetadataEvidenceSchema = GeneratedBrowserSocialVideoMetadataEvidenceSchema;
export const decodeBrowserSocialVideoMetadataEvidence = GenerateddecodeBrowserSocialVideoMetadataEvidence;
export const extractBrowserSocialVideoMetadata = GeneratedextractBrowserSocialVideoMetadata;
export type BrowserSocialVideoMetadataEvidence = GeneratedBrowserSocialVideoMetadataEvidence;
export type BrowserSocialVideoMetadataEvidenceId = GeneratedBrowserSocialVideoMetadataEvidenceId;
export type BrowserSocialVideoMetadataExtractorInput = GeneratedBrowserSocialVideoMetadataExtractorInput;
export type BrowserSocialVideoMetadataSourceKind = GeneratedBrowserSocialVideoMetadataSourceKind;
export type BrowserSocialVideoMetadataState = GeneratedBrowserSocialVideoMetadataState;
