import type { BrowserControlFullCatalogSettingSeed } from './browser-control-full-catalog-schema';
export const BrowserControlFullCatalogData0C: readonly BrowserControlFullCatalogSettingSeed[] = [
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-014',
    143,
    279,
    'Cover iOS third-party browsers.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-015',
    144,
    280,
    'Cover embedded WebViews.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-016',
    145,
    281,
    'Cover Electron shells.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-017',
    146,
    282,
    'Cover game launchers with embedded web content.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-018',
    147,
    283,
    'Cover Tor Browser.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-019',
    148,
    284,
    'Cover private/incognito browser windows.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-020',
    149,
    285,
    'Cover unknown Chromium browsers.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-021',
    150,
    286,
    'Cover portable browsers.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-022',
    151,
    287,
    'Cover renamed browsers.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-023',
    152,
    288,
    'Allow unsupported browser as monitor only.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-024',
    153,
    289,
    'Treat unsupported browser as unmanaged.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-025',
    154,
    290,
    'Treat unsupported browser as blocked.',
  ],
  [
    'browser-catalog-browser-coverage-settings',
    'Browser Coverage Settings',
    4,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings',
    'Browser Coverage Settings',
    9,
    'browser-catalog-browser-coverage-settings-browser-coverage-settings-026',
    155,
    291,
    'Require adapter proof before exact rules apply.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-001',
    156,
    297,
    'Allow managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-002',
    157,
    298,
    'Require managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-003',
    158,
    299,
    'Disable managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-004',
    159,
    300,
    'Auto-create managed browser profile.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-005',
    160,
    301,
    'Keep managed profile persistent.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-006',
    161,
    302,
    'Clear managed profile on schedule.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-007',
    162,
    303,
    'Clear managed cookies/cache on schedule.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-008',
    163,
    304,
    'Clear managed downloads on schedule.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-009',
    164,
    305,
    'Allow bookmarks in managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-010',
    165,
    306,
    'Provision school bookmarks.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-011',
    166,
    307,
    'Provision allowed-start-page bookmarks.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-012',
    167,
    308,
    'Set managed browser as default browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-013',
    168,
    309,
    'Restore previous default browser on uninstall.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-014',
    169,
    310,
    'Open HTTP links in managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-015',
    170,
    311,
    'Open HTTPS links in managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-016',
    171,
    312,
    'Open school app links in managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-017',
    172,
    313,
    'Open unknown web links in managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-018',
    173,
    314,
    'Use Ocentra launcher for browser start.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-019',
    174,
    315,
    'Use managed shell/owned WebView.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-020',
    175,
    316,
    'Use installed Edge as managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-021',
    176,
    317,
    'Use installed Chrome as managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-022',
    177,
    318,
    'Use Chrome for Testing as managed browser.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-023',
    178,
    319,
    'Allow parent/admin to choose browser executable.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-024',
    179,
    320,
    'Require signed approved browser executable.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-025',
    180,
    321,
    'Require browser version minimum.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-026',
    181,
    322,
    'Block managed launch if browser version is unsupported.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-027',
    182,
    323,
    'Notify parent when managed browser needs update.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-028',
    183,
    324,
    'Allow managed browser without extension.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-029',
    184,
    325,
    'Require managed extension.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-030',
    185,
    326,
    'Allow managed extension optional mode.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-031',
    186,
    327,
    'Force-install managed extension where supported.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-032',
    187,
    328,
    'Enable native messaging host.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-033',
    188,
    329,
    'Require native messaging host heartbeat.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-034',
    189,
    330,
    'Enable browser policy provisioning.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-035',
    190,
    331,
    'Enable CDP bridge.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-036',
    191,
    332,
    'Enable WebDriver BiDi bridge.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-037',
    192,
    333,
    'Enable extension bridge.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-038',
    193,
    334,
    'Enable owned WebView bridge.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-039',
    194,
    335,
    'Enable loopback-only browser bridge.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-040',
    195,
    336,
    'Use random bridge port per session.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-041',
    196,
    337,
    'Store bridge endpoint only as redacted reference.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-042',
    197,
    338,
    'Reject default profile bridge.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-043',
    198,
    339,
    'Reject unmanaged profile bridge.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-044',
    199,
    340,
    'Reject stale managed session bridge.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-045',
    200,
    341,
    'Close bridge when managed session ends.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-046',
    201,
    342,
    'Degrade safely when bridge is unavailable.',
  ],
  [
    'browser-catalog-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    5,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings',
    'Managed Browser Setup Settings',
    10,
    'browser-catalog-managed-browser-setup-settings-managed-browser-setup-settings-047',
    202,
    343,
    'Block exact web rules until managed setup is ready.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-001',
    203,
    349,
    'Auto-launch managed browser at sign-in.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-002',
    204,
    350,
    'Auto-launch managed browser when child opens a web link.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-003',
    205,
    351,
    'Keep managed browser running in background.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-004',
    206,
    352,
    'Close managed browser at bedtime.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-005',
    207,
    353,
    'Close managed browser after inactivity.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-006',
    208,
    354,
    'Restore managed session after restart.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-007',
    209,
    355,
    'Restore previous tabs in managed session.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-008',
    210,
    356,
    'Start with approved home page.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-009',
    211,
    357,
    'Start with blank page.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-010',
    212,
    358,
    'Start with school dashboard.',
  ],
];
