import {
  BrowserSocialFeedRouteSchemaVersion as GeneratedBrowserSocialFeedRouteSchemaVersion,
  BrowserSocialFeedRouteClassificationIdSchema as GeneratedBrowserSocialFeedRouteClassificationIdSchema,
  BrowserSocialFeedSurfaceHintSchema as GeneratedBrowserSocialFeedSurfaceHintSchema,
  BrowserSocialFeedSurfaceKindSchema as GeneratedBrowserSocialFeedSurfaceKindSchema,
  BrowserSocialFeedRouteClassificationSchema as GeneratedBrowserSocialFeedRouteClassificationSchema,
  decodeBrowserSocialFeedRouteClassification as GenerateddecodeBrowserSocialFeedRouteClassification,
  classifyBrowserSocialFeedRoute as GeneratedclassifyBrowserSocialFeedRoute,
} from './generated-browser-social-feed-route-classification';
import type {
  BrowserSocialFeedRouteClassification as GeneratedBrowserSocialFeedRouteClassification,
  BrowserSocialFeedRouteClassificationId as GeneratedBrowserSocialFeedRouteClassificationId,
  BrowserSocialFeedRouteClassifierInput as GeneratedBrowserSocialFeedRouteClassifierInput,
  BrowserSocialFeedSurfaceHint as GeneratedBrowserSocialFeedSurfaceHint,
  BrowserSocialFeedSurfaceKind as GeneratedBrowserSocialFeedSurfaceKind,
} from './generated-browser-social-feed-route-classification';

export const BrowserSocialFeedRouteSchemaVersion = GeneratedBrowserSocialFeedRouteSchemaVersion;
export const BrowserSocialFeedRouteClassificationIdSchema = GeneratedBrowserSocialFeedRouteClassificationIdSchema;
export const BrowserSocialFeedSurfaceHintSchema = GeneratedBrowserSocialFeedSurfaceHintSchema;
export const BrowserSocialFeedSurfaceKindSchema = GeneratedBrowserSocialFeedSurfaceKindSchema;
export const BrowserSocialFeedRouteClassificationSchema = GeneratedBrowserSocialFeedRouteClassificationSchema;
export const decodeBrowserSocialFeedRouteClassification = GenerateddecodeBrowserSocialFeedRouteClassification;
export const classifyBrowserSocialFeedRoute = GeneratedclassifyBrowserSocialFeedRoute;
export type BrowserSocialFeedRouteClassification = GeneratedBrowserSocialFeedRouteClassification;
export type BrowserSocialFeedRouteClassificationId = GeneratedBrowserSocialFeedRouteClassificationId;
export type BrowserSocialFeedRouteClassifierInput = GeneratedBrowserSocialFeedRouteClassifierInput;
export type BrowserSocialFeedSurfaceHint = GeneratedBrowserSocialFeedSurfaceHint;
export type BrowserSocialFeedSurfaceKind = GeneratedBrowserSocialFeedSurfaceKind;
