import type { BrowserControlFullCatalogSettingSeed } from './browser-control-full-catalog-schema';
export const BrowserControlFullCatalogData1C: readonly BrowserControlFullCatalogSettingSeed[] = [
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-015',
    355,
    521,
    'Close browser.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-016',
    356,
    522,
    'Redirect to allowed page.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-017',
    357,
    523,
    'Redirect to managed browser.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-018',
    358,
    524,
    'Pause browser access.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-019',
    359,
    525,
    'Lock browser access until approval.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-020',
    360,
    526,
    'Block unmanaged browser process.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-021',
    361,
    527,
    'Terminate unmanaged browser process.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-022',
    362,
    528,
    'Block network/domain.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-023',
    363,
    529,
    'Cancel download.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-024',
    364,
    530,
    'Quarantine download.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-025',
    365,
    531,
    'Delete download.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-026',
    366,
    532,
    'Mark for parent review.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-027',
    367,
    533,
    'Require child explanation.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-028',
    368,
    534,
    'Require parent PIN.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-029',
    369,
    535,
    'No-op because unsupported.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-030',
    370,
    536,
    'No-op because degraded.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-031',
    371,
    537,
    'Roll back enforcement.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-001',
    372,
    543,
    'Observe installed browsers only.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-002',
    373,
    544,
    'Observe running browsers only.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-003',
    374,
    545,
    'Observe managed browser readiness only.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-004',
    375,
    546,
    'Observe exact URL without enforcing.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-005',
    376,
    547,
    'Observe unmanaged browser without action.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-006',
    377,
    548,
    'Observe downloads without action.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-007',
    378,
    549,
    'Observe network domains without action.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-008',
    379,
    550,
    'Dry-run page block.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-009',
    380,
    551,
    'Dry-run domain block.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-010',
    381,
    552,
    'Dry-run unmanaged browser block.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-011',
    382,
    553,
    'Dry-run download block.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-012',
    383,
    554,
    'Dry-run time budget.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-013',
    384,
    555,
    'Warn instead of block when proof is weak.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-014',
    385,
    556,
    'Ask instead of block when proof is weak.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-015',
    386,
    557,
    'Enforce only when proof is fresh.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-016',
    387,
    558,
    'Enforce only from managed active tab.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-017',
    388,
    559,
    'Enforce from managed tab list.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-018',
    389,
    560,
    'Enforce from network/domain evidence.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-019',
    390,
    561,
    'Enforce from process evidence.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-020',
    391,
    562,
    'Enforce from local AI classification.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-021',
    392,
    563,
    'Never enforce from stale/degraded evidence.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-022',
    393,
    564,
    'Never enforce from network-only evidence for exact URL rules.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-023',
    394,
    565,
    'Fallback from enforce to ask.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-024',
    395,
    566,
    'Fallback from enforce to warn.',
  ],
  [
    'browser-catalog-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    11,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings',
    'Observe Versus Enforce Settings',
    16,
    'browser-catalog-observe-versus-enforce-settings-observe-versus-enforce-settings-025',
    396,
    567,
    'Fallback from enforce to observe.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-001',
    397,
    573,
    'Always.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-002',
    398,
    574,
    'School hours.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-003',
    399,
    575,
    'Homework hours.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-004',
    400,
    576,
    'Bedtime.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-005',
    401,
    577,
    'Morning routine.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-006',
    402,
    578,
    'Weekend.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-007',
    403,
    579,
    'Custom schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-008',
    404,
    580,
    'One-time schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-009',
    405,
    581,
    'Holiday schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-010',
    406,
    582,
    'Travel schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-011',
    407,
    583,
    'Per-child schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-012',
    408,
    584,
    'Per-device schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-013',
    409,
    585,
    'Per-browser schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-014',
    410,
    586,
    'Per-site schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-015',
    411,
    587,
    'Per-category schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-016',
    412,
    588,
    'Per-download schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-017',
    413,
    589,
    'Schedule timezone.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-018',
    414,
    590,
    'Schedule source from parent device.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-019',
    415,
    591,
    'Schedule source from child device.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-020',
    416,
    592,
    'Allow grace before schedule starts.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-021',
    417,
    593,
    'Allow grace after schedule ends.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-022',
    418,
    594,
    'Lock browser during blackout window.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-023',
    419,
    595,
    'Allow only school domains during school schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-024',
    420,
    596,
    'Allow only managed browser during school schedule.',
  ],
  [
    'browser-catalog-schedule-settings',
    'Schedule Settings',
    12,
    'browser-catalog-schedule-settings-schedule-settings',
    'Schedule Settings',
    17,
    'browser-catalog-schedule-settings-schedule-settings-025',
    421,
    597,
    'Allow unmanaged browser only outside school/bedtime.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-001',
    422,
    603,
    'Enable browser daily quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-002',
    423,
    604,
    'Enable browser weekly quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-003',
    424,
    605,
    'Enable browser session limit.',
  ],
];
