import type { BrowserControlFullCatalogSettingSeed } from './browser-control-full-catalog-schema';
export const BrowserControlFullCatalogData0A: readonly BrowserControlFullCatalogSettingSeed[] = [
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-001',
    1,
    106,
    'Family default.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-002',
    2,
    107,
    'Child profile.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-003',
    3,
    108,
    'Child age band.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-004',
    4,
    109,
    'Device.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-005',
    5,
    110,
    'Platform.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-006',
    6,
    111,
    'Browser family.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-007',
    7,
    112,
    'Managed browser profile.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-008',
    8,
    113,
    'Unmanaged browser group.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-009',
    9,
    114,
    'Browser session.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-010',
    10,
    115,
    'Site/domain/category target.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-011',
    11,
    116,
    'Download target.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-012',
    12,
    117,
    'Temporary parent override.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope',
    'Ownership Scope',
    1,
    'browser-catalog-global-rule-dimensions-ownership-scope-013',
    13,
    118,
    'Emergency/school/admin preset.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-001',
    14,
    122,
    'Off.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-002',
    15,
    123,
    'Observe only.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-003',
    16,
    124,
    'Dry run only.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-004',
    17,
    125,
    'Warn child.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-005',
    18,
    126,
    'Notify parent.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-006',
    19,
    127,
    'Ask parent.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-007',
    20,
    128,
    'Limit.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-008',
    21,
    129,
    'Block.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-009',
    22,
    130,
    'Relaunch managed browser.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-010',
    23,
    131,
    'Enforce with rollback.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-policy-mode',
    'Policy Mode',
    2,
    'browser-catalog-global-rule-dimensions-policy-mode-011',
    24,
    132,
    'Unavailable on this platform.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-001',
    25,
    136,
    'Before browser launch.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-002',
    26,
    137,
    'At process launch.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-003',
    27,
    138,
    'At managed browser startup.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-004',
    28,
    139,
    'At navigation start.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-005',
    29,
    140,
    'Before request is sent.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-006',
    30,
    141,
    'After response/download starts.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-007',
    31,
    142,
    'At active tab change.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-008',
    32,
    143,
    'At foreground window change.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-009',
    33,
    144,
    'During session timer.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-010',
    34,
    145,
    'At download start.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-011',
    35,
    146,
    'At download completion.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-012',
    36,
    147,
    'After unmanaged browser detection.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-013',
    37,
    148,
    'At network/domain observation.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-enforcement-phase',
    'Enforcement Phase',
    3,
    'browser-catalog-global-rule-dimensions-enforcement-phase-014',
    38,
    149,
    'At report generation only.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-001',
    39,
    153,
    'No evidence required.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-002',
    40,
    154,
    'Parent-authored rule only.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-003',
    41,
    155,
    'Installed browser inventory.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-004',
    42,
    156,
    'Running process.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-005',
    43,
    157,
    'Foreground browser window.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-006',
    44,
    158,
    'Browser command-line URL.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-007',
    45,
    159,
    'Network/domain observation.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-008',
    46,
    160,
    'DNS observation.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-009',
    47,
    161,
    'Managed tab list.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-010',
    48,
    162,
    'Proven active tab.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-011',
    49,
    163,
    'Fresh exact URL.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-012',
    50,
    164,
    'Fresh page title.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-013',
    51,
    165,
    'Fresh download metadata.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-014',
    52,
    166,
    'Browser policy event.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-015',
    53,
    167,
    'Browser extension event.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-016',
    54,
    168,
    'CDP event.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-017',
    55,
    169,
    'OS app-control event.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-018',
    56,
    170,
    'Local AI classification with evidence refs.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-evidence-requirement',
    'Evidence Requirement',
    4,
    'browser-catalog-global-rule-dimensions-evidence-requirement-019',
    57,
    171,
    'Parent approval state.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-freshness-requirement',
    'Freshness Requirement',
    5,
    'browser-catalog-global-rule-dimensions-freshness-requirement-001',
    58,
    175,
    'Real-time only.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-freshness-requirement',
    'Freshness Requirement',
    5,
    'browser-catalog-global-rule-dimensions-freshness-requirement-002',
    59,
    176,
    'Fresh within seconds.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-freshness-requirement',
    'Freshness Requirement',
    5,
    'browser-catalog-global-rule-dimensions-freshness-requirement-003',
    60,
    177,
    'Fresh within minutes.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-freshness-requirement',
    'Freshness Requirement',
    5,
    'browser-catalog-global-rule-dimensions-freshness-requirement-004',
    61,
    178,
    'Stale allowed for reports only.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-freshness-requirement',
    'Freshness Requirement',
    5,
    'browser-catalog-global-rule-dimensions-freshness-requirement-005',
    62,
    179,
    'Stale allowed for dry-run only.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-freshness-requirement',
    'Freshness Requirement',
    5,
    'browser-catalog-global-rule-dimensions-freshness-requirement-006',
    63,
    180,
    'Degraded evidence allowed.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-freshness-requirement',
    'Freshness Requirement',
    5,
    'browser-catalog-global-rule-dimensions-freshness-requirement-007',
    64,
    181,
    'Unavailable means ask parent.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-freshness-requirement',
    'Freshness Requirement',
    5,
    'browser-catalog-global-rule-dimensions-freshness-requirement-008',
    65,
    182,
    'Unavailable means allow.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-freshness-requirement',
    'Freshness Requirement',
    5,
    'browser-catalog-global-rule-dimensions-freshness-requirement-009',
    66,
    183,
    'Unavailable means block.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-001',
    67,
    187,
    'Block wins.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-002',
    68,
    188,
    'Limit wins.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-003',
    69,
    189,
    'Ask wins.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-004',
    70,
    190,
    'Warn wins.',
  ],
  [
    'browser-catalog-global-rule-dimensions',
    'Global Rule Dimensions',
    1,
    'browser-catalog-global-rule-dimensions-rule-priority',
    'Rule Priority',
    6,
    'browser-catalog-global-rule-dimensions-rule-priority-005',
    71,
    191,
    'Allow wins.',
  ],
];
