import {
  BrowserSocialRouteSchemaVersion as GeneratedBrowserSocialRouteSchemaVersion,
  BrowserSocialRouteEvidenceIdSchema as GeneratedBrowserSocialRouteEvidenceIdSchema,
  BrowserSocialPlatformSchema as GeneratedBrowserSocialPlatformSchema,
  BrowserSocialRouteKindSchema as GeneratedBrowserSocialRouteKindSchema,
  BrowserSocialRouteSourceKindSchema as GeneratedBrowserSocialRouteSourceKindSchema,
  BrowserSocialRouteProofStateSchema as GeneratedBrowserSocialRouteProofStateSchema,
  BrowserSocialRouteEvidenceSchema as GeneratedBrowserSocialRouteEvidenceSchema,
  decodeBrowserSocialRouteEvidence as GenerateddecodeBrowserSocialRouteEvidence,
} from './generated-browser-social-platform-route-schemas';
import type {
  BrowserSocialPlatform as GeneratedBrowserSocialPlatform,
  BrowserSocialRouteEvidence as GeneratedBrowserSocialRouteEvidence,
  BrowserSocialRouteEvidenceId as GeneratedBrowserSocialRouteEvidenceId,
  BrowserSocialRouteKind as GeneratedBrowserSocialRouteKind,
  BrowserSocialRouteProofState as GeneratedBrowserSocialRouteProofState,
  BrowserSocialRouteSourceKind as GeneratedBrowserSocialRouteSourceKind,
} from './generated-browser-social-platform-route-schemas';

export const BrowserSocialRouteSchemaVersion = GeneratedBrowserSocialRouteSchemaVersion;
export const BrowserSocialRouteEvidenceIdSchema = GeneratedBrowserSocialRouteEvidenceIdSchema;
export const BrowserSocialPlatformSchema = GeneratedBrowserSocialPlatformSchema;
export const BrowserSocialRouteKindSchema = GeneratedBrowserSocialRouteKindSchema;
export const BrowserSocialRouteSourceKindSchema = GeneratedBrowserSocialRouteSourceKindSchema;
export const BrowserSocialRouteProofStateSchema = GeneratedBrowserSocialRouteProofStateSchema;
export const BrowserSocialRouteEvidenceSchema = GeneratedBrowserSocialRouteEvidenceSchema;
export const decodeBrowserSocialRouteEvidence = GenerateddecodeBrowserSocialRouteEvidence;
export type BrowserSocialPlatform = GeneratedBrowserSocialPlatform;
export type BrowserSocialRouteEvidence = GeneratedBrowserSocialRouteEvidence;
export type BrowserSocialRouteEvidenceId = GeneratedBrowserSocialRouteEvidenceId;
export type BrowserSocialRouteKind = GeneratedBrowserSocialRouteKind;
export type BrowserSocialRouteProofState = GeneratedBrowserSocialRouteProofState;
export type BrowserSocialRouteSourceKind = GeneratedBrowserSocialRouteSourceKind;
