import type { BrowserControlFullCatalogSettingSeed } from './browser-control-full-catalog-schema';
export const BrowserControlFullCatalogData2: readonly BrowserControlFullCatalogSettingSeed[] = [
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-004',
    425,
    606,
    'Enable exact site daily quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-005',
    426,
    607,
    'Enable domain daily quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-006',
    427,
    608,
    'Enable category daily quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-007',
    428,
    609,
    'Enable video platform quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-008',
    429,
    610,
    'Enable search engine quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-009',
    430,
    611,
    'Enable unmanaged browser quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-010',
    431,
    612,
    'Enable managed browser quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-011',
    432,
    613,
    'Count only foreground browser time.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-012',
    433,
    614,
    'Count background browser time.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-013',
    434,
    615,
    'Count active tab time.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-014',
    435,
    616,
    'Count tab-list-only time.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-015',
    436,
    617,
    'Count unmanaged browser time as unknown web time.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-016',
    437,
    618,
    'Count blocked/paused time against quota.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-017',
    438,
    619,
    'Do not count parent-approved school sites.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-018',
    439,
    620,
    'Do not count allowlisted domains.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-019',
    440,
    621,
    'Do not count parent-approved session extension.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-020',
    441,
    622,
    'Grace minutes before block.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-021',
    442,
    623,
    'Warning threshold before budget ends.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-022',
    443,
    624,
    'Ask parent when budget ends.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-023',
    444,
    625,
    'Block when budget ends.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-024',
    445,
    626,
    'Switch to allowlist when budget ends.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-025',
    446,
    627,
    'Reset quota daily.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-026',
    447,
    628,
    'Reset quota weekly.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-027',
    448,
    629,
    'Carry over unused minutes.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-028',
    449,
    630,
    'Do not carry over unused minutes.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-029',
    450,
    631,
    'Parent can extend once.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-030',
    451,
    632,
    'Parent can extend for session.',
  ],
  [
    'browser-catalog-time-budget-settings',
    'Time Budget Settings',
    13,
    'browser-catalog-time-budget-settings-time-budget-settings',
    'Time Budget Settings',
    18,
    'browser-catalog-time-budget-settings-time-budget-settings-031',
    452,
    633,
    'Parent can extend until time.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-001',
    453,
    639,
    'Require approval for blocked site.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-002',
    454,
    640,
    'Require approval for new domain.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-003',
    455,
    641,
    'Require approval for unknown category.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-004',
    456,
    642,
    'Require approval for unmanaged browser.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-005',
    457,
    643,
    'Require approval for unsupported browser.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-006',
    458,
    644,
    'Require approval for private/incognito attempt.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-007',
    459,
    645,
    'Require approval for download.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-008',
    460,
    646,
    'Require approval for executable download.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-009',
    461,
    647,
    'Require approval for archive download.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-010',
    462,
    648,
    'Require approval for time extension.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-011',
    463,
    649,
    'Require approval for managed browser setup repair.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-012',
    464,
    650,
    'Require approval for browser extension permission.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-013',
    465,
    651,
    'Require approval for new browser install.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-014',
    466,
    652,
    'Require approval for browser policy change.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-015',
    467,
    653,
    'Require approval for clearing managed profile.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-016',
    468,
    654,
    'Require approval for disabling bridge.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-017',
    469,
    655,
    'Require approval for LAN-visible browser data.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-018',
    470,
    656,
    'Allow child to request site access.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-019',
    471,
    657,
    'Allow child to request category access.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-020',
    472,
    658,
    'Allow child to request unmanaged browser access.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-021',
    473,
    659,
    'Allow child to request download approval.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-022',
    474,
    660,
    'Allow child to request extra time.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-023',
    475,
    661,
    'Allow child to include note.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-024',
    476,
    662,
    'Allow parent to approve once.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-025',
    477,
    663,
    'Allow parent to approve this session.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-026',
    478,
    664,
    'Allow parent to approve until a time.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-027',
    479,
    665,
    'Allow parent to approve always.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-028',
    480,
    666,
    'Allow parent to deny once.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-029',
    481,
    667,
    'Allow parent to deny always.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-030',
    482,
    668,
    'Expire unanswered approval after N minutes.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-031',
    483,
    669,
    'Default unanswered approval to deny.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-032',
    484,
    670,
    'Default unanswered approval to allow temporarily.',
  ],
  [
    'browser-catalog-parent-approval-settings',
    'Parent Approval Settings',
    14,
    'browser-catalog-parent-approval-settings-parent-approval-settings',
    'Parent Approval Settings',
    19,
    'browser-catalog-parent-approval-settings-parent-approval-settings-033',
    485,
    671,
    'Default unanswered approval to continue observe only.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-001',
    486,
    677,
    'Approve once.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-002',
    487,
    678,
    'Approve for current tab.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-003',
    488,
    679,
    'Approve for current domain.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-004',
    489,
    680,
    'Approve for current category.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-005',
    490,
    681,
    'Approve for current browser session.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-006',
    491,
    682,
    'Approve until time.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-007',
    492,
    683,
    'Approve for today.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-008',
    493,
    684,
    'Approve for school schedule.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-009',
    494,
    685,
    'Approve permanently.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-010',
    495,
    686,
    'Deny once.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-011',
    496,
    687,
    'Deny for session.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-012',
    497,
    688,
    'Deny until time.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-013',
    498,
    689,
    'Deny permanently.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-014',
    499,
    690,
    'Extend time by minutes.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-015',
    500,
    691,
    "Reset today's time budget.",
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-016',
    501,
    692,
    'Cancel active block.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-017',
    502,
    693,
    'Cancel pending ask.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-018',
    503,
    694,
    'Cancel download.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-019',
    504,
    695,
    'Allow download once.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-020',
    505,
    696,
    'Trust this download source.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-021',
    506,
    697,
    'Trust this browser executable.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-022',
    507,
    698,
    'Trust this managed profile repair.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-023',
    508,
    699,
    'Revoke previous override.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-024',
    509,
    700,
    'Auto-expire override.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-025',
    510,
    701,
    'Require override reason.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-026',
    511,
    702,
    'Hide override details from child.',
  ],
  [
    'browser-catalog-override-settings',
    'Override Settings',
    15,
    'browser-catalog-override-settings-override-settings',
    'Override Settings',
    20,
    'browser-catalog-override-settings-override-settings-027',
    512,
    703,
    'Show override reason to child.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-001',
    513,
    709,
    'Enable download monitoring.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-002',
    514,
    710,
    'Enable managed browser download metadata.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-003',
    515,
    711,
    'Enable unmanaged download file observation.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-004',
    516,
    712,
    'Ask parent before all downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-005',
    517,
    713,
    'Ask parent before executable downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-006',
    518,
    714,
    'Ask parent before archive downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-007',
    519,
    715,
    'Ask parent before unknown file types.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-008',
    520,
    716,
    'Ask parent before large downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-009',
    521,
    717,
    'Allow document downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-010',
    522,
    718,
    'Allow image downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-011',
    523,
    719,
    'Allow school file downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-012',
    524,
    720,
    'Allow media downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-013',
    525,
    721,
    'Block executable downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-014',
    526,
    722,
    'Block script downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-015',
    527,
    723,
    'Block archive downloads.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-016',
    528,
    724,
    'Block unknown file extensions.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-017',
    529,
    725,
    'Block downloads from blocked domains.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-018',
    530,
    726,
    'Block downloads from unknown domains.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-019',
    531,
    727,
    'Block downloads from unmanaged browsers.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-020',
    532,
    728,
    'Cancel managed browser download.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-021',
    533,
    729,
    'Quarantine completed download.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-022',
    534,
    730,
    'Delete blocked download.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-023',
    535,
    731,
    'Keep blocked file metadata only.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-024',
    536,
    732,
    'Show download URL when managed evidence exists.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-025',
    537,
    733,
    'Hide source URL for unmanaged download.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-026',
    538,
    734,
    'Show filename.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-027',
    539,
    735,
    'Show MIME type.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-028',
    540,
    736,
    'Show file size.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-029',
    541,
    737,
    'Show browser danger status.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-030',
    542,
    738,
    'Show interruption reason.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-031',
    543,
    739,
    'Show download completion status.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-032',
    544,
    740,
    'Scan downloaded file hash against local policy if a later adapter supports it.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-033',
    545,
    741,
    'Notify parent at download start.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-034',
    546,
    742,
    'Notify parent at download completion.',
  ],
  [
    'browser-catalog-downloads-settings',
    'Downloads Settings',
    16,
    'browser-catalog-downloads-settings-downloads-settings',
    'Downloads Settings',
    21,
    'browser-catalog-downloads-settings-downloads-settings-035',
    547,
    743,
    'Notify parent only on risky download.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-001',
    548,
    750,
    'Enable search engine detection.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-002',
    549,
    751,
    'Disable search term collection.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-003',
    550,
    752,
    'Redact search terms.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-004',
    551,
    753,
    'Allow search term rules.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-005',
    552,
    754,
    'Allow search category rules.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-006',
    553,
    755,
    'Allow safe-search enforcement where browser/search provider supports it.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-007',
    554,
    756,
    'Require managed browser for search term rules.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-008',
    555,
    757,
    'Use domain-only search evidence.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-009',
    556,
    758,
    'Store search terms only for policy decisions.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-010',
    557,
    759,
    'Store search terms only in local child journal.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-011',
    558,
    760,
    'Show search terms in parent report.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-012',
    559,
    761,
    'Hide search terms unless parent reveals.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-013',
    560,
    762,
    'Block search queries by keyword.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-014',
    561,
    763,
    'Warn on search queries by keyword.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-015',
    562,
    764,
    'Ask parent on unknown/risky search.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-016',
    563,
    765,
    'Treat network-only search domain as insufficient for search terms.',
  ],
  [
    'browser-catalog-search-settings',
    'Search Settings',
    17,
    'browser-catalog-search-settings-search-settings',
    'Search Settings',
    22,
    'browser-catalog-search-settings-search-settings-017',
    564,
    766,
    'Apply school-search allowlist.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-001',
    565,
    772,
    'Enable video platform detection.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-002',
    566,
    773,
    'Enable video channel rules.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-003',
    567,
    774,
    'Enable video URL rules.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-004',
    568,
    775,
    'Enable video category rules.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-005',
    569,
    776,
    'Enable video time budgets.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-006',
    570,
    777,
    'Enable video title matching.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-007',
    571,
    778,
    'Require managed browser for video rules.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-008',
    572,
    779,
    'Allow video rules from network/domain only.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-009',
    573,
    780,
    'Treat network/domain video evidence as weak.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-010',
    574,
    781,
    'Ask parent for unknown video channel.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-011',
    575,
    782,
    'Block specific video channels.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-012',
    576,
    783,
    'Allow specific video channels.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-013',
    577,
    784,
    'Limit video platform time.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-014',
    578,
    785,
    'Limit video category time.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-015',
    579,
    786,
    'Exclude school video domains from entertainment budget.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-016',
    580,
    787,
    'Record video evidence id.',
  ],
  [
    'browser-catalog-video-and-channel-settings',
    'Video And Channel Settings',
    18,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings',
    'Video And Channel Settings',
    23,
    'browser-catalog-video-and-channel-settings-video-and-channel-settings-017',
    581,
    788,
    'Avoid page body or transcript collection unless a later milestone approves it.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-001',
    582,
    794,
    'Block private/incognito windows in managed browser where supported.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-002',
    583,
    795,
    'Allow private/incognito but mark evidence unavailable.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-003',
    584,
    796,
    'Warn when private/incognito is attempted.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-004',
    585,
    797,
    'Ask parent for private/incognito.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-005',
    586,
    798,
    'Block Tor Browser.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-006',
    587,
    799,
    'Monitor Tor Browser.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-007',
    588,
    800,
    'Block VPN browser extensions.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-008',
    589,
    801,
    'Block proxy browser extensions.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-009',
    590,
    802,
    'Block browser profile switching.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-010',
    591,
    803,
    'Block unmanaged extension installs.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-011',
    592,
    804,
    'Block clearing managed browser history.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-012',
    593,
    805,
    'Block deleting managed browser profile.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-013',
    594,
    806,
    'Detect managed bridge closed unexpectedly.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-014',
    595,
    807,
    'Detect managed extension disabled.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-015',
    596,
    808,
    'Detect native host missing.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-016',
    597,
    809,
    'Detect browser policy removed.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-017',
    598,
    810,
    'Detect browser process launched outside Ocentra.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-018',
    599,
    811,
    'Detect browser executable copy/rename.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-019',
    600,
    812,
    'Detect new portable browser.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-020',
    601,
    813,
    'Detect unknown browser network activity.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-021',
    602,
    814,
    'Escalate repeated bypass attempts.',
  ],
  [
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    19,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings',
    'Private, Incognito, Tor, And Anti-Bypass Settings',
    24,
    'browser-catalog-private-incognito-tor-and-anti-bypass-settings-private-incognito-tor-and-anti-bypass-settings-022',
    603,
    815,
    'Lock to managed browser until parent resolves.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-001',
    604,
    821,
    'Enable network/domain observation.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-002',
    605,
    822,
    'Disable network/domain observation.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-003',
    606,
    823,
    'Enable DNS observation.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-004',
    607,
    824,
    'Enable process-attributed network observation.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-005',
    608,
    825,
    'Enable domain blocking.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-006',
    609,
    826,
    'Enable DNS filtering.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-007',
    610,
    827,
    'Enable proxy filtering.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-008',
    611,
    828,
    'Enable VPN filtering.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-009',
    612,
    829,
    'Enable Windows Filtering Platform adapter.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-010',
    613,
    830,
    'Enable firewall adapter.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-011',
    614,
    831,
    'Enable Android always-on VPN adapter.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-012',
    615,
    832,
    'Enable iOS web domain shielding where available.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-013',
    616,
    833,
    'Block domain for all browsers.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-014',
    617,
    834,
    'Block domain only for unmanaged browsers.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-015',
    618,
    835,
    'Block domain only outside managed browser.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-016',
    619,
    836,
    'Block browser network unless managed.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-017',
    620,
    837,
    'Allow local network domains.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-018',
    621,
    838,
    'Allow school domains.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-019',
    622,
    839,
    'Allow update/service domains.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-020',
    623,
    840,
    'Ignore CDN domains in parent summary.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-021',
    624,
    841,
    'Show CDN domains only in diagnostics.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-022',
    625,
    842,
    'Treat network-only evidence as domain-level.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-023',
    626,
    843,
    'Never treat network-only evidence as exact URL.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-024',
    627,
    844,
    'Use network evidence for local AI context.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-025',
    628,
    845,
    'Use network evidence for dry-run only.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-026',
    629,
    846,
    'Use network evidence for enforcement.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-027',
    630,
    847,
    'Fallback to network block when browser bridge fails.',
  ],
  [
    'browser-catalog-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    20,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings',
    'Network And Domain Fallback Settings',
    25,
    'browser-catalog-network-and-domain-fallback-settings-network-and-domain-fallback-settings-028',
    631,
    848,
    'Fallback to ask when network confidence is low.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-001',
    632,
    854,
    'Time-limit browser app use.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-002',
    633,
    855,
    'Time-limit unmanaged browser app use.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-003',
    634,
    856,
    'Time-limit managed browser app use.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-004',
    635,
    857,
    'Block browser executable.',
  ],
  [
    'browser-catalog-browser-app-and-process-settings',
    'Browser App And Process Settings',
    21,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings',
    'Browser App And Process Settings',
    26,
    'browser-catalog-browser-app-and-process-settings-browser-app-and-process-settings-005',
    636,
    858,
    'Allow browser executable.',
  ],
];
