import {
  BrowserUrlShapeSchemaVersion as GeneratedBrowserUrlShapeSchemaVersion,
  BrowserUrlIntelligenceMemorySchemaVersion as GeneratedBrowserUrlIntelligenceMemorySchemaVersion,
  BrowserUrlShapeClassificationIdSchema as GeneratedBrowserUrlShapeClassificationIdSchema,
  BrowserUrlIntelligenceMemoryHitIdSchema as GeneratedBrowserUrlIntelligenceMemoryHitIdSchema,
  BrowserUrlShapeSourceKindSchema as GeneratedBrowserUrlShapeSourceKindSchema,
  BrowserUrlShapeTargetKindSchema as GeneratedBrowserUrlShapeTargetKindSchema,
  BrowserUrlShapePlatformSchema as GeneratedBrowserUrlShapePlatformSchema,
  BrowserUrlShapeConfidenceSchema as GeneratedBrowserUrlShapeConfidenceSchema,
  BrowserUrlShapeReasonCodeSchema as GeneratedBrowserUrlShapeReasonCodeSchema,
  BrowserUrlIntelligenceMemoryKeyKindSchema as GeneratedBrowserUrlIntelligenceMemoryKeyKindSchema,
  BrowserUrlIntelligenceMemoryHitStateSchema as GeneratedBrowserUrlIntelligenceMemoryHitStateSchema,
  BrowserUrlIntelligenceMemoryDecisionKindSchema as GeneratedBrowserUrlIntelligenceMemoryDecisionKindSchema,
  BrowserUrlIntelligenceMemoryStaleReasonSchema as GeneratedBrowserUrlIntelligenceMemoryStaleReasonSchema,
  BrowserUrlShapePlatformIdsSchema as GeneratedBrowserUrlShapePlatformIdsSchema,
  BrowserUrlIntelligenceMemoryKeySchema as GeneratedBrowserUrlIntelligenceMemoryKeySchema,
  BrowserUrlShapeClassificationResultSchema as GeneratedBrowserUrlShapeClassificationResultSchema,
  decodeBrowserUrlShapeClassificationResult as GenerateddecodeBrowserUrlShapeClassificationResult,
  BrowserUrlIntelligenceMemoryHitSchema as GeneratedBrowserUrlIntelligenceMemoryHitSchema,
  decodeBrowserUrlIntelligenceMemoryHit as GenerateddecodeBrowserUrlIntelligenceMemoryHit,
} from './generated-browser-url-intelligence-schemas';
import type {
  BrowserUrlIntelligenceMemoryHitId as GeneratedBrowserUrlIntelligenceMemoryHitId,
  BrowserUrlShapeClassificationId as GeneratedBrowserUrlShapeClassificationId,
  BrowserUrlShapeSourceKind as GeneratedBrowserUrlShapeSourceKind,
  BrowserUrlShapeTargetKind as GeneratedBrowserUrlShapeTargetKind,
  BrowserUrlShapePlatform as GeneratedBrowserUrlShapePlatform,
  BrowserUrlShapeConfidence as GeneratedBrowserUrlShapeConfidence,
  BrowserUrlShapeReasonCode as GeneratedBrowserUrlShapeReasonCode,
  BrowserUrlShapePlatformIds as GeneratedBrowserUrlShapePlatformIds,
  BrowserUrlShapeClassificationResult as GeneratedBrowserUrlShapeClassificationResult,
  BrowserUrlIntelligenceMemoryKeyKind as GeneratedBrowserUrlIntelligenceMemoryKeyKind,
  BrowserUrlIntelligenceMemoryHitState as GeneratedBrowserUrlIntelligenceMemoryHitState,
  BrowserUrlIntelligenceMemoryDecisionKind as GeneratedBrowserUrlIntelligenceMemoryDecisionKind,
  BrowserUrlIntelligenceMemoryStaleReason as GeneratedBrowserUrlIntelligenceMemoryStaleReason,
  BrowserUrlIntelligenceMemoryKey as GeneratedBrowserUrlIntelligenceMemoryKey,
  BrowserUrlIntelligenceMemoryHit as GeneratedBrowserUrlIntelligenceMemoryHit,
} from './generated-browser-url-intelligence-schemas';

export const BrowserUrlShapeSchemaVersion = GeneratedBrowserUrlShapeSchemaVersion;
export const BrowserUrlIntelligenceMemorySchemaVersion = GeneratedBrowserUrlIntelligenceMemorySchemaVersion;
export const BrowserUrlShapeClassificationIdSchema = GeneratedBrowserUrlShapeClassificationIdSchema;
export const BrowserUrlIntelligenceMemoryHitIdSchema = GeneratedBrowserUrlIntelligenceMemoryHitIdSchema;
export const BrowserUrlShapeSourceKindSchema = GeneratedBrowserUrlShapeSourceKindSchema;
export const BrowserUrlShapeTargetKindSchema = GeneratedBrowserUrlShapeTargetKindSchema;
export const BrowserUrlShapePlatformSchema = GeneratedBrowserUrlShapePlatformSchema;
export const BrowserUrlShapeConfidenceSchema = GeneratedBrowserUrlShapeConfidenceSchema;
export const BrowserUrlShapeReasonCodeSchema = GeneratedBrowserUrlShapeReasonCodeSchema;
export const BrowserUrlIntelligenceMemoryKeyKindSchema = GeneratedBrowserUrlIntelligenceMemoryKeyKindSchema;
export const BrowserUrlIntelligenceMemoryHitStateSchema = GeneratedBrowserUrlIntelligenceMemoryHitStateSchema;
export const BrowserUrlIntelligenceMemoryDecisionKindSchema = GeneratedBrowserUrlIntelligenceMemoryDecisionKindSchema;
export const BrowserUrlIntelligenceMemoryStaleReasonSchema = GeneratedBrowserUrlIntelligenceMemoryStaleReasonSchema;
export const BrowserUrlShapePlatformIdsSchema = GeneratedBrowserUrlShapePlatformIdsSchema;
export const BrowserUrlIntelligenceMemoryKeySchema = GeneratedBrowserUrlIntelligenceMemoryKeySchema;
export const BrowserUrlShapeClassificationResultSchema = GeneratedBrowserUrlShapeClassificationResultSchema;
export const decodeBrowserUrlShapeClassificationResult = GenerateddecodeBrowserUrlShapeClassificationResult;
export const BrowserUrlIntelligenceMemoryHitSchema = GeneratedBrowserUrlIntelligenceMemoryHitSchema;
export const decodeBrowserUrlIntelligenceMemoryHit = GenerateddecodeBrowserUrlIntelligenceMemoryHit;
export type BrowserUrlIntelligenceMemoryHitId = GeneratedBrowserUrlIntelligenceMemoryHitId;
export type BrowserUrlShapeClassificationId = GeneratedBrowserUrlShapeClassificationId;
export type BrowserUrlShapeSourceKind = GeneratedBrowserUrlShapeSourceKind;
export type BrowserUrlShapeTargetKind = GeneratedBrowserUrlShapeTargetKind;
export type BrowserUrlShapePlatform = GeneratedBrowserUrlShapePlatform;
export type BrowserUrlShapeConfidence = GeneratedBrowserUrlShapeConfidence;
export type BrowserUrlShapeReasonCode = GeneratedBrowserUrlShapeReasonCode;
export type BrowserUrlShapePlatformIds = GeneratedBrowserUrlShapePlatformIds;
export type BrowserUrlShapeClassificationResult = GeneratedBrowserUrlShapeClassificationResult;
export type BrowserUrlIntelligenceMemoryKeyKind = GeneratedBrowserUrlIntelligenceMemoryKeyKind;
export type BrowserUrlIntelligenceMemoryHitState = GeneratedBrowserUrlIntelligenceMemoryHitState;
export type BrowserUrlIntelligenceMemoryDecisionKind = GeneratedBrowserUrlIntelligenceMemoryDecisionKind;
export type BrowserUrlIntelligenceMemoryStaleReason = GeneratedBrowserUrlIntelligenceMemoryStaleReason;
export type BrowserUrlIntelligenceMemoryKey = GeneratedBrowserUrlIntelligenceMemoryKey;
export type BrowserUrlIntelligenceMemoryHit = GeneratedBrowserUrlIntelligenceMemoryHit;
