import type { BrowserControlFullCatalogSettingSeed } from './browser-control-full-catalog-schema';
export const BrowserControlFullCatalogData1A: readonly BrowserControlFullCatalogSettingSeed[] = [
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-011',
    213,
    359,
    'Disable unmanaged profile switching.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-012',
    214,
    360,
    'Disable private/incognito mode where supported.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-013',
    215,
    361,
    'Disable guest mode where supported.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-014',
    216,
    362,
    'Disable extension installs by child.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-015',
    217,
    363,
    'Allow approved extensions only.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-016',
    218,
    364,
    'Block developer tools in managed browser where supported.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-017',
    219,
    365,
    'Block browser settings page where supported.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-018',
    220,
    366,
    'Block clearing browser history where supported.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-019',
    221,
    367,
    'Block changing managed search engine where supported.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-020',
    222,
    368,
    'Block changing default download folder where supported.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-021',
    223,
    369,
    'Enable safe browsing or browser-native protection where supported.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-022',
    224,
    370,
    'Keep managed session visible to parent reports.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-023',
    225,
    371,
    'Allow child to request managed setup repair.',
  ],
  [
    'browser-catalog-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    6,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings',
    'Managed Browser Operation Settings',
    11,
    'browser-catalog-managed-browser-operation-settings-managed-browser-operation-settings-024',
    226,
    372,
    'Notify parent if managed browser cannot launch.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-001',
    227,
    378,
    'Allow unmanaged browsers.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-002',
    228,
    379,
    'Disallow unmanaged browsers.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-003',
    229,
    380,
    'Monitor unmanaged browsers.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-004',
    230,
    381,
    'Warn child on unmanaged browser.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-005',
    231,
    382,
    'Notify parent on unmanaged browser.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-006',
    232,
    383,
    'Ask parent before unmanaged browser continues.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-007',
    233,
    384,
    'Apply grace period before action.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-008',
    234,
    385,
    'Close unmanaged browser.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-009',
    235,
    386,
    'Close unmanaged browser and launch managed browser.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-010',
    236,
    387,
    'Block unmanaged browser launch.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-011',
    237,
    388,
    'Block browser-like unknown processes.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-012',
    238,
    389,
    'Block portable browsers.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-013',
    239,
    390,
    'Block renamed browsers.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-014',
    240,
    391,
    'Block unsupported browsers.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-015',
    241,
    392,
    'Block Tor/private browsers.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-016',
    242,
    393,
    'Allow Edge unmanaged.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-017',
    243,
    394,
    'Allow Chrome unmanaged.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-018',
    244,
    395,
    'Allow Firefox unmanaged.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-019',
    245,
    396,
    'Allow Brave/Opera unmanaged.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-020',
    246,
    397,
    'Allow specific unmanaged executable path.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-021',
    247,
    398,
    'Allow specific unmanaged executable signature.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-022',
    248,
    399,
    'Allow specific unmanaged browser during schedule.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-023',
    249,
    400,
    'Allow unmanaged browser only in observe mode.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-024',
    250,
    401,
    'Allow unmanaged browser only for adult/admin child profile.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-025',
    251,
    402,
    'Allow unmanaged browser only with parent PIN.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-026',
    252,
    403,
    'Record unmanaged browser as bypass evidence.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-027',
    253,
    404,
    'Escalate after repeated unmanaged launches.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-028',
    254,
    405,
    'Escalate after repeated relaunch attempts.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-029',
    255,
    406,
    'Escalate if child kills managed browser.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-030',
    256,
    407,
    'Escalate if bridge disappears during session.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-031',
    257,
    408,
    'Do not terminate if unsaved-data warning is possible.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-032',
    258,
    409,
    'Terminate immediately in strict mode.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-033',
    259,
    410,
    'Relaunch captured URL in managed browser when available.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-034',
    260,
    411,
    'Relaunch managed browser without URL when target is unknown.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-035',
    261,
    412,
    'Keep unmanaged browser open but block network.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-036',
    262,
    413,
    'Keep unmanaged browser open but hide exact URL controls.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-037',
    263,
    414,
    'Treat unmanaged browser time as browser app time.',
  ],
  [
    'browser-catalog-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    7,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings',
    'Unmanaged Browser Handling Settings',
    12,
    'browser-catalog-unmanaged-browser-handling-settings-unmanaged-browser-handling-settings-038',
    264,
    415,
    'Treat unmanaged browser time as unknown web time.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-001',
    265,
    421,
    'Allow managed URL inspection.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-002',
    266,
    422,
    'Disable exact URL inspection.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-003',
    267,
    423,
    'Collect full URL.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-004',
    268,
    424,
    'Collect domain/origin only.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-005',
    269,
    425,
    'Collect page title.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-006',
    270,
    426,
    'Collect active tab state.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-007',
    271,
    427,
    'Collect tab list.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-008',
    272,
    428,
    'Collect window id.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-009',
    273,
    429,
    'Collect tab id.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-010',
    274,
    430,
    'Collect target id.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-011',
    275,
    431,
    'Collect active/inactive state.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-012',
    276,
    432,
    'Collect navigation events.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-013',
    277,
    433,
    'Collect redirect chain.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-014',
    278,
    434,
    'Collect request URL for main frame.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-015',
    279,
    435,
    'Collect request URL for subresources.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-016',
    280,
    436,
    'Ignore subresource URLs.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-017',
    281,
    437,
    'Collect favicon URL.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-018',
    282,
    438,
    'Disable favicon collection.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-019',
    283,
    439,
    'Collect only when rule matches.',
  ],
];
