import type { BrowserControlFullCatalogSettingSeed } from './browser-control-full-catalog-schema';
export const BrowserControlFullCatalogData1B: readonly BrowserControlFullCatalogSettingSeed[] = [
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-020',
    284,
    440,
    'Collect only when active tab is proven.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-021',
    285,
    441,
    'Collect only while managed browser is foreground.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-022',
    286,
    442,
    'Collect while managed browser is background.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-023',
    287,
    443,
    'Collect only during configured schedules.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-024',
    288,
    444,
    'Redact query string by default.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-025',
    289,
    445,
    'Allow query string for exact rules.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-026',
    290,
    446,
    'Redact sensitive query parameters.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-027',
    291,
    447,
    'Redact search terms by default.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-028',
    292,
    448,
    'Store search terms only when parent enables search rules.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-029',
    293,
    449,
    'Store exact URL only for blocked or asked decisions.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-030',
    294,
    450,
    'Store exact URL only in local child journal.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-031',
    295,
    451,
    'Show exact URL only after parent reveal action.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-032',
    296,
    452,
    'Mark tab-list-only state distinctly.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-033',
    297,
    453,
    'Mark unknown-active state distinctly.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-034',
    298,
    454,
    'Mark stale evidence distinctly.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-035',
    299,
    455,
    'Ignore stale URL evidence for enforcement.',
  ],
  [
    'browser-catalog-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    8,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings',
    'URL And Tab Evidence Settings',
    13,
    'browser-catalog-url-and-tab-evidence-settings-url-and-tab-evidence-settings-036',
    300,
    456,
    'Allow stale URL evidence for report history.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-001',
    301,
    462,
    'Exact URL.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-002',
    302,
    463,
    'URL prefix.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-003',
    303,
    464,
    'URL pattern.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-004',
    304,
    465,
    'Domain.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-005',
    305,
    466,
    'Origin.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-006',
    306,
    467,
    'Site.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-007',
    307,
    468,
    'Site category.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-008',
    308,
    469,
    'Unknown category.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-009',
    309,
    470,
    'Search engine.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-010',
    310,
    471,
    'Search term.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-011',
    311,
    472,
    'Video platform.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-012',
    312,
    473,
    'Video channel.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-013',
    313,
    474,
    'Video id.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-014',
    314,
    475,
    'Page title keyword.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-015',
    315,
    476,
    'Browser family.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-016',
    316,
    477,
    'Browser version.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-017',
    317,
    478,
    'Browser channel.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-018',
    318,
    479,
    'Managed state.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-019',
    319,
    480,
    'Unmanaged state.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-020',
    320,
    481,
    'Browser session.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-021',
    321,
    482,
    'Browser process.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-022',
    322,
    483,
    'Browser executable path.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-023',
    323,
    484,
    'Browser signature/hash reference.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-024',
    324,
    485,
    'Capability state.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-025',
    325,
    486,
    'Active tab certainty.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-026',
    326,
    487,
    'Evidence freshness.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-027',
    327,
    488,
    'Source/custody label.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-028',
    328,
    489,
    'Download source URL.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-029',
    329,
    490,
    'Download filename.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-030',
    330,
    491,
    'Download extension.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-031',
    331,
    492,
    'Download MIME type.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-032',
    332,
    493,
    'Download size.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-033',
    333,
    494,
    'Browser network domain.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-034',
    334,
    495,
    'Browser network destination.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-035',
    335,
    496,
    'Time of day.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-036',
    336,
    497,
    'Schedule window.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-037',
    337,
    498,
    'Device location/profile context if a later milestone supports it.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-038',
    338,
    499,
    'Parent approval state.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-039',
    339,
    500,
    'Local AI classification.',
  ],
  [
    'browser-catalog-rule-target-settings',
    'Rule Target Settings',
    9,
    'browser-catalog-rule-target-settings-rule-target-settings',
    'Rule Target Settings',
    14,
    'browser-catalog-rule-target-settings-rule-target-settings-040',
    340,
    501,
    'Local AI confidence/reason.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-001',
    341,
    507,
    'Allow.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-002',
    342,
    508,
    'Monitor.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-003',
    343,
    509,
    'Log only.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-004',
    344,
    510,
    'Warn child.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-005',
    345,
    511,
    'Notify parent.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-006',
    346,
    512,
    'Ask parent.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-007',
    347,
    513,
    'Ask parent and pause.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-008',
    348,
    514,
    'Ask parent and allow temporarily.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-009',
    349,
    515,
    'Time-limit.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-010',
    350,
    516,
    'Reduce remaining budget.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-011',
    351,
    517,
    'Start session timer.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-012',
    352,
    518,
    'End session timer.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-013',
    353,
    519,
    'Block page.',
  ],
  [
    'browser-catalog-rule-action-settings',
    'Rule Action Settings',
    10,
    'browser-catalog-rule-action-settings-rule-action-settings',
    'Rule Action Settings',
    15,
    'browser-catalog-rule-action-settings-rule-action-settings-014',
    354,
    520,
    'Close tab.',
  ],
];
