import {
  BrowserSocialFeedVideoRouteGateInputSchema as GeneratedBrowserSocialFeedVideoRouteGateInputSchema,
  BrowserSocialFeedVideoRouteGatePlanSchema as GeneratedBrowserSocialFeedVideoRouteGatePlanSchema,
  decodeBrowserSocialFeedVideoRouteGatePlan as GenerateddecodeBrowserSocialFeedVideoRouteGatePlan,
  planBrowserSocialFeedVideoRouteGate as GeneratedplanBrowserSocialFeedVideoRouteGate,
} from './generated-browser-social-feed-video-route-gate';
import type {
  BrowserSocialFeedVideoRouteGateInput as GeneratedBrowserSocialFeedVideoRouteGateInput,
  BrowserSocialFeedVideoRouteGatePlan as GeneratedBrowserSocialFeedVideoRouteGatePlan,
} from './generated-browser-social-feed-video-route-gate';

export const BrowserSocialFeedVideoRouteGateInputSchema = GeneratedBrowserSocialFeedVideoRouteGateInputSchema;
export const BrowserSocialFeedVideoRouteGatePlanSchema = GeneratedBrowserSocialFeedVideoRouteGatePlanSchema;
export const decodeBrowserSocialFeedVideoRouteGatePlan = GenerateddecodeBrowserSocialFeedVideoRouteGatePlan;
export const planBrowserSocialFeedVideoRouteGate = GeneratedplanBrowserSocialFeedVideoRouteGate;
export type BrowserSocialFeedVideoRouteGateInput = GeneratedBrowserSocialFeedVideoRouteGateInput;
export type BrowserSocialFeedVideoRouteGatePlan = GeneratedBrowserSocialFeedVideoRouteGatePlan;
