/* generated from crates/schema/src/billing_entitlement_runtime_proof_ts.rs */

export const GeneratedBillingEntitlementRuntimeProofReadModel = {
  schemaVersion: 'billing-entitlement-runtime-proof',
  snapshotConsumptions: [
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-snapshot-active',
      operation: 'account-entitlement-snapshot-consumption',
      runtimeState: 'snapshot-active',
      source: 'signed-local-snapshot',
      entitlementSnapshot: {
        schemaVersion: 'billing-entitlement-contract-proof',
        snapshotId: 'entitlement-snapshot-family-1-active',
        family: {
          familyId: 'family-billing-entitlement-proof-1',
        },
        parentAccount: {
          parentAccountId: 'parent-account-billing-entitlement-proof-1',
        },
        planId: 'family-plus-monthly',
        subscriptionStatus: 'active',
        source: 'signed-local-snapshot',
        signatureState: 'schema-valid-local',
        generatedAt: '2026-06-03T09:57:32.000Z',
        expiresAt: '2026-06-11T23:34:57.000Z',
        deviceLimit: 5,
        baseChildDeviceLimit: 1,
        activeReferralCredits: 2,
        paidExtraChildDeviceSeats: 2,
        effectiveChildDeviceLimit: 5,
        featureDecisions: [
          {
            featureCode: 'multi-device-sync',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'advanced-reports',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'cloud-relay',
            decision: 'grace',
            reasonCode: 'snapshot-stale',
            safetyCritical: false,
            localSafetyBehavior: 'grace-with-local-safety',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'local-evidence-capture',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'evidence-export-access',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
        ],
        failureState: null,
      },
      localSafetyBehavior: 'unchanged',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      failureState: null,
      auditReference: 'audit-runtime-snapshot-active',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-snapshot-stale',
      operation: 'account-entitlement-snapshot-consumption',
      runtimeState: 'snapshot-stale',
      source: 'signed-local-snapshot',
      entitlementSnapshot: {
        schemaVersion: 'billing-entitlement-contract-proof',
        snapshotId: 'entitlement-runtime-expired',
        family: {
          familyId: 'family-billing-entitlement-proof-1',
        },
        parentAccount: {
          parentAccountId: 'parent-account-billing-entitlement-proof-1',
        },
        planId: 'family-plus-monthly',
        subscriptionStatus: 'expired',
        source: 'signed-local-snapshot',
        signatureState: 'schema-valid-local',
        generatedAt: '2026-06-03T09:57:32.000Z',
        expiresAt: '2026-06-11T23:34:57.000Z',
        deviceLimit: 5,
        baseChildDeviceLimit: 1,
        activeReferralCredits: 2,
        paidExtraChildDeviceSeats: 2,
        effectiveChildDeviceLimit: 5,
        featureDecisions: [
          {
            featureCode: 'multi-device-sync',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'advanced-reports',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'cloud-relay',
            decision: 'grace',
            reasonCode: 'snapshot-stale',
            safetyCritical: false,
            localSafetyBehavior: 'grace-with-local-safety',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'local-evidence-capture',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'evidence-export-access',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
        ],
        failureState: {
          failureKind: 'stale-snapshot',
          parentVisibleState: 'stale',
          localSafetyBehavior: 'grace-with-local-safety',
          retainEvidenceExportAccess: true,
          existingLocalSafetyContinues: true,
          parentResolution: 'wait-for-provider',
          retryAllowed: true,
          retryAfter: '2026-06-05T00:34:57.000Z',
        },
      },
      localSafetyBehavior: 'grace-with-local-safety',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      failureState: {
        failureKind: 'stale-snapshot',
        parentVisibleState: 'stale',
        localSafetyBehavior: 'grace-with-local-safety',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'wait-for-provider',
        retryAllowed: true,
        retryAfter: '2026-06-05T00:34:57.000Z',
      },
      auditReference: 'audit-runtime-snapshot-stale',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-snapshot-payment-required',
      operation: 'account-entitlement-snapshot-consumption',
      runtimeState: 'payment-required',
      source: 'signed-local-snapshot',
      entitlementSnapshot: {
        schemaVersion: 'billing-entitlement-contract-proof',
        snapshotId: 'entitlement-runtime-past-due',
        family: {
          familyId: 'family-billing-entitlement-proof-1',
        },
        parentAccount: {
          parentAccountId: 'parent-account-billing-entitlement-proof-1',
        },
        planId: 'family-plus-monthly',
        subscriptionStatus: 'past-due',
        source: 'signed-local-snapshot',
        signatureState: 'schema-valid-local',
        generatedAt: '2026-06-03T09:57:32.000Z',
        expiresAt: '2026-06-11T23:34:57.000Z',
        deviceLimit: 5,
        baseChildDeviceLimit: 1,
        activeReferralCredits: 2,
        paidExtraChildDeviceSeats: 2,
        effectiveChildDeviceLimit: 5,
        featureDecisions: [
          {
            featureCode: 'multi-device-sync',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'advanced-reports',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'cloud-relay',
            decision: 'grace',
            reasonCode: 'snapshot-stale',
            safetyCritical: false,
            localSafetyBehavior: 'grace-with-local-safety',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'local-evidence-capture',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'evidence-export-access',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
        ],
        failureState: {
          failureKind: 'payment-required',
          parentVisibleState: 'past-due',
          localSafetyBehavior: 'grace-with-local-safety',
          retainEvidenceExportAccess: true,
          existingLocalSafetyContinues: true,
          parentResolution: 'payment-update',
          retryAllowed: true,
          retryAfter: null,
        },
      },
      localSafetyBehavior: 'grace-with-local-safety',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      failureState: {
        failureKind: 'payment-required',
        parentVisibleState: 'past-due',
        localSafetyBehavior: 'grace-with-local-safety',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'payment-update',
        retryAllowed: true,
        retryAfter: null,
      },
      auditReference: 'audit-runtime-snapshot-payment-required',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-snapshot-provider-unavailable',
      operation: 'account-entitlement-snapshot-consumption',
      runtimeState: 'provider-unavailable',
      source: 'unavailable',
      entitlementSnapshot: {
        schemaVersion: 'billing-entitlement-contract-proof',
        snapshotId: 'entitlement-runtime-unavailable',
        family: {
          familyId: 'family-billing-entitlement-proof-1',
        },
        parentAccount: {
          parentAccountId: 'parent-account-billing-entitlement-proof-1',
        },
        planId: 'family-plus-monthly',
        subscriptionStatus: 'unavailable',
        source: 'unavailable',
        signatureState: 'unavailable',
        generatedAt: '2026-06-03T09:57:32.000Z',
        expiresAt: '2026-06-11T23:34:57.000Z',
        deviceLimit: 5,
        baseChildDeviceLimit: 1,
        activeReferralCredits: 2,
        paidExtraChildDeviceSeats: 2,
        effectiveChildDeviceLimit: 5,
        featureDecisions: [
          {
            featureCode: 'multi-device-sync',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'advanced-reports',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'cloud-relay',
            decision: 'grace',
            reasonCode: 'snapshot-stale',
            safetyCritical: false,
            localSafetyBehavior: 'grace-with-local-safety',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'local-evidence-capture',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'evidence-export-access',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
        ],
        failureState: {
          failureKind: 'provider-unavailable',
          parentVisibleState: 'unavailable',
          localSafetyBehavior: 'local-only',
          retainEvidenceExportAccess: true,
          existingLocalSafetyContinues: true,
          parentResolution: 'wait-for-provider',
          retryAllowed: true,
          retryAfter: '2026-06-05T00:34:57.000Z',
        },
      },
      localSafetyBehavior: 'local-only',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      failureState: {
        failureKind: 'provider-unavailable',
        parentVisibleState: 'unavailable',
        localSafetyBehavior: 'local-only',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'wait-for-provider',
        retryAllowed: true,
        retryAfter: '2026-06-05T00:34:57.000Z',
      },
      auditReference: 'audit-runtime-snapshot-provider-unavailable',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-snapshot-manual-review',
      operation: 'account-entitlement-snapshot-consumption',
      runtimeState: 'manual-review',
      source: 'manual-support-review',
      entitlementSnapshot: {
        schemaVersion: 'billing-entitlement-contract-proof',
        snapshotId: 'entitlement-runtime-manual-review',
        family: {
          familyId: 'family-billing-entitlement-proof-1',
        },
        parentAccount: {
          parentAccountId: 'parent-account-billing-entitlement-proof-1',
        },
        planId: 'family-plus-monthly',
        subscriptionStatus: 'unknown',
        source: 'manual-admin-review',
        signatureState: 'manual-required',
        generatedAt: '2026-06-03T09:57:32.000Z',
        expiresAt: '2026-06-11T23:34:57.000Z',
        deviceLimit: 5,
        baseChildDeviceLimit: 1,
        activeReferralCredits: 2,
        paidExtraChildDeviceSeats: 2,
        effectiveChildDeviceLimit: 5,
        featureDecisions: [
          {
            featureCode: 'multi-device-sync',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'advanced-reports',
            decision: 'available',
            reasonCode: 'within-plan',
            safetyCritical: false,
            localSafetyBehavior: 'unchanged',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'cloud-relay',
            decision: 'grace',
            reasonCode: 'snapshot-stale',
            safetyCritical: false,
            localSafetyBehavior: 'grace-with-local-safety',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'local-evidence-capture',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
          {
            featureCode: 'evidence-export-access',
            decision: 'local-only',
            reasonCode: 'within-plan',
            safetyCritical: true,
            localSafetyBehavior: 'local-only',
            evidenceExportAccess: 'retained',
            childActivityCustody: 'not-included',
          },
        ],
        failureState: {
          failureKind: 'validation-failed',
          parentVisibleState: 'manual-review',
          localSafetyBehavior: 'manual-review-with-local-safety',
          retainEvidenceExportAccess: true,
          existingLocalSafetyContinues: true,
          parentResolution: 'manual-support-review',
          retryAllowed: false,
          retryAfter: null,
        },
      },
      localSafetyBehavior: 'manual-review-with-local-safety',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      failureState: {
        failureKind: 'validation-failed',
        parentVisibleState: 'manual-review',
        localSafetyBehavior: 'manual-review-with-local-safety',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'manual-support-review',
        retryAllowed: false,
        retryAfter: null,
      },
      auditReference: 'audit-runtime-snapshot-manual-review',
    },
  ],
  deviceLimitConsumptions: [
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-device-allowed',
      operation: 'device-limit-decision-consumption',
      deviceLimitDecision: {
        schemaVersion: 'billing-entitlement-contract-proof',
        decisionId: 'device-limit-allowed-1',
        requestedDevice: {
          deviceId: 'windows-child-device-1',
          childProfileId: 'child-billing-entitlement-proof-1',
          label: 'windows-child-device-1 activation',
          platform: 'windows',
        },
        entitlementSnapshotId: 'entitlement-snapshot-family-1-active',
        activeDeviceCount: 4,
        planDeviceLimit: 5,
        requestedDeviceAlreadyTrusted: false,
        decision: 'allowed',
        reasonCode: 'within-plan',
        deviceActivationBehavior: 'allow-new-device',
        auditReference: 'audit-device-limit-allowed-1',
        existingLocalSafetyBehavior: 'unchanged',
      },
      consumptionState: 'accepted-local',
      localSafetyBehavior: 'unchanged',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      failureState: null,
      auditReference: 'audit-runtime-device-allowed',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-device-denied',
      operation: 'device-limit-decision-consumption',
      deviceLimitDecision: {
        schemaVersion: 'billing-entitlement-contract-proof',
        decisionId: 'device-limit-denied-1',
        requestedDevice: {
          deviceId: 'android-child-device-6',
          childProfileId: 'child-billing-entitlement-proof-1',
          label: 'android-child-device-6 activation',
          platform: 'android',
        },
        entitlementSnapshotId: 'entitlement-snapshot-family-1-active',
        activeDeviceCount: 5,
        planDeviceLimit: 5,
        requestedDeviceAlreadyTrusted: false,
        decision: 'denied',
        reasonCode: 'limit-exceeded',
        deviceActivationBehavior: 'deny-new-device',
        auditReference: 'audit-device-limit-denied-1',
        existingLocalSafetyBehavior: 'grace-with-local-safety',
      },
      consumptionState: 'blocked-new-device',
      localSafetyBehavior: 'grace-with-local-safety',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      failureState: {
        failureKind: 'payment-required',
        parentVisibleState: 'past-due',
        localSafetyBehavior: 'grace-with-local-safety',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'payment-update',
        retryAllowed: true,
        retryAfter: null,
      },
      auditReference: 'audit-runtime-device-denied',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-device-grace',
      operation: 'device-limit-decision-consumption',
      deviceLimitDecision: {
        schemaVersion: 'billing-entitlement-contract-proof',
        decisionId: 'device-limit-grace-1',
        requestedDevice: {
          deviceId: 'ios-child-device-2',
          childProfileId: 'child-billing-entitlement-proof-1',
          label: 'ios-child-device-2 activation',
          platform: 'ios',
        },
        entitlementSnapshotId: 'entitlement-snapshot-family-1-active',
        activeDeviceCount: 5,
        planDeviceLimit: 5,
        requestedDeviceAlreadyTrusted: false,
        decision: 'grace',
        reasonCode: 'snapshot-stale',
        deviceActivationBehavior: 'grace-existing-devices',
        auditReference: 'audit-device-limit-grace-1',
        existingLocalSafetyBehavior: 'grace-with-local-safety',
      },
      consumptionState: 'accepted-grace',
      localSafetyBehavior: 'grace-with-local-safety',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      failureState: {
        failureKind: 'stale-snapshot',
        parentVisibleState: 'stale',
        localSafetyBehavior: 'grace-with-local-safety',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'wait-for-provider',
        retryAllowed: true,
        retryAfter: '2026-06-05T00:34:57.000Z',
      },
      auditReference: 'audit-runtime-device-grace',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-device-manual',
      operation: 'device-limit-decision-consumption',
      deviceLimitDecision: {
        schemaVersion: 'billing-entitlement-contract-proof',
        decisionId: 'device-limit-manual-1',
        requestedDevice: {
          deviceId: 'android-child-device-7',
          childProfileId: 'child-billing-entitlement-proof-1',
          label: 'android-child-device-7 activation',
          platform: 'android',
        },
        entitlementSnapshotId: 'entitlement-snapshot-family-1-active',
        activeDeviceCount: 5,
        planDeviceLimit: 5,
        requestedDeviceAlreadyTrusted: false,
        decision: 'manual-review',
        reasonCode: 'manual-review',
        deviceActivationBehavior: 'manual-review-required',
        auditReference: 'audit-device-limit-manual-1',
        existingLocalSafetyBehavior: 'grace-with-local-safety',
      },
      consumptionState: 'manual-required',
      localSafetyBehavior: 'manual-review-with-local-safety',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      failureState: {
        failureKind: 'validation-failed',
        parentVisibleState: 'manual-review',
        localSafetyBehavior: 'manual-review-with-local-safety',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'manual-support-review',
        retryAllowed: false,
        retryAfter: null,
      },
      auditReference: 'audit-runtime-device-manual',
    },
  ],
  failureConsumptions: [
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-failure-provider-unavailable',
      operation: 'billing-failure-state-consumption',
      failureState: {
        failureKind: 'provider-unavailable',
        parentVisibleState: 'unavailable',
        localSafetyBehavior: 'local-only',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'wait-for-provider',
        retryAllowed: true,
        retryAfter: '2026-06-05T00:34:57.000Z',
      },
      consumedFor: ['account-entitlement-snapshot-consumption', 'billing-failure-state-consumption'],
      localSafetyBehavior: 'local-only',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      consumptionState: 'unavailable-local-safety',
      auditReference: 'audit-runtime-failure-provider-unavailable',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-failure-stale-snapshot',
      operation: 'billing-failure-state-consumption',
      failureState: {
        failureKind: 'stale-snapshot',
        parentVisibleState: 'stale',
        localSafetyBehavior: 'grace-with-local-safety',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'wait-for-provider',
        retryAllowed: true,
        retryAfter: '2026-06-05T00:34:57.000Z',
      },
      consumedFor: ['account-entitlement-snapshot-consumption', 'device-limit-decision-consumption'],
      localSafetyBehavior: 'grace-with-local-safety',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      consumptionState: 'accepted-grace',
      auditReference: 'audit-runtime-failure-stale-snapshot',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-failure-payment-required',
      operation: 'billing-failure-state-consumption',
      failureState: {
        failureKind: 'payment-required',
        parentVisibleState: 'past-due',
        localSafetyBehavior: 'grace-with-local-safety',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'payment-update',
        retryAllowed: true,
        retryAfter: null,
      },
      consumedFor: ['account-entitlement-snapshot-consumption', 'device-limit-decision-consumption'],
      localSafetyBehavior: 'grace-with-local-safety',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      consumptionState: 'blocked-new-device',
      auditReference: 'audit-runtime-failure-payment-required',
    },
    {
      schemaVersion: 'billing-entitlement-runtime-proof',
      boundaryId: 'runtime-failure-validation-failed',
      operation: 'billing-failure-state-consumption',
      failureState: {
        failureKind: 'validation-failed',
        parentVisibleState: 'manual-review',
        localSafetyBehavior: 'manual-review-with-local-safety',
        retainEvidenceExportAccess: true,
        existingLocalSafetyContinues: true,
        parentResolution: 'manual-support-review',
        retryAllowed: false,
        retryAfter: null,
      },
      consumedFor: ['billing-failure-state-consumption'],
      localSafetyBehavior: 'manual-review-with-local-safety',
      evidenceExportAccess: 'retained',
      childActivityCustody: 'not-included',
      consumptionState: 'manual-required',
      auditReference: 'audit-runtime-failure-validation-failed',
    },
  ],
  nonClaims: [
    'no-stripe-sdk',
    'no-live-provider-execution',
    'no-provider-contact',
    'no-refund-credit-runtime',
    'no-child-activity-custody',
    'no-production-billing-claim',
    'no-portal-ui',
  ],
  stripeSdkClaim: 'not-included',
  providerExecutionClaim: 'not-implemented',
  providerContactClaim: 'manual-required',
  refundCreditClaim: 'manual-required',
  productionBillingClaim: 'not-claimed',
  portalUiClaim: 'not-implemented',
  childCustodyClaim: 'signed-snapshot-consumption-contract',
  childActivityCustodyClaim: 'not-included',
  updatedAt: '2026-06-04T23:34:57.000Z',
} as const;
