import { type Infer, NonEmptyStringSchema, Schema, withParser } from './effect';

const NetworkRemoteDeliveryCount = Schema.Number.pipe(Schema.nonNegative(), Schema.int());

export const AgentNetworkRemoteDeliveryRow10tRefs = {
  StatusRef: 'network.remote-delivery.external-cross-process-transport-status.10t',
  ExternalCrossProcessTransportRef: 'network.remote-delivery.external-cross-process-transport.10t',
  ExternalCrossProcessTransportEnvelopeRef: 'network.remote-delivery.external-cross-process-transport-envelope.10t',
  ExternalCrossProcessTransportAckRef: 'network.remote-delivery.external-cross-process-transport-ack.10t',
} as const;

export const AgentNetworkRemoteDeliveryStatusStateSchema = withParser(
  Schema.Literal('fixture-requirements-recorded-but-not-implemented', 'manual-required')
);
export const AgentNetworkRemoteDeliveryTransportDispatchStateSchema = withParser(
  Schema.Literal('manual-required-blocked')
);
export const AgentNetworkRemoteDeliveryProviderChildReadinessStateSchema = withParser(
  Schema.Literal('manual-required-unavailable')
);
export const AgentNetworkRemoteDeliveryCrossProcessCustodyReadinessStateSchema = withParser(
  Schema.Literal('manual-required-unavailable')
);
export const AgentNetworkRemoteDeliveryExternalCrossProcessTransportStateSchema = withParser(
  Schema.Literal('deterministic-envelope-ack-recorded')
);

export const AgentNetworkRemoteDeliveryStatusSchema = withParser(
  Schema.Struct({
    statusRef: NonEmptyStringSchema,
    brokerStatus: AgentNetworkRemoteDeliveryStatusStateSchema,
    familyHubStatus: AgentNetworkRemoteDeliveryStatusStateSchema,
    custodyProofRef: NonEmptyStringSchema,
    publisherAuthRef: NonEmptyStringSchema,
    subscriberAuthRef: NonEmptyStringSchema,
    encryptionRef: NonEmptyStringSchema,
    retentionPolicyRef: NonEmptyStringSchema,
    replayPlanRef: NonEmptyStringSchema,
    deletionPlanRef: NonEmptyStringSchema,
    offsetPolicyRef: NonEmptyStringSchema,
    dedupePolicyRef: NonEmptyStringSchema,
    transportConfigRef: NonEmptyStringSchema,
    relayIdentityRef: NonEmptyStringSchema,
    relayPolicyRef: NonEmptyStringSchema,
    brokerMissingArtifactCount: NetworkRemoteDeliveryCount,
    familyHubMissingArtifactCount: NetworkRemoteDeliveryCount,
    acceptedEventTypeCount: NetworkRemoteDeliveryCount,
    localIdempotencyQueueProved: Schema.Boolean,
    droppedEventDeadLetterCount: NetworkRemoteDeliveryCount,
    queuedDuplicateRejected: Schema.Boolean,
    completedDuplicateRejected: Schema.Boolean,
    eventChainJournalRef: NonEmptyStringSchema,
    receiptLedgerRef: NonEmptyStringSchema,
    localReceiptAckRef: NonEmptyStringSchema,
    durableEnvelopeRef: NonEmptyStringSchema,
    durableStoreRef: NonEmptyStringSchema,
    durableReplayRef: NonEmptyStringSchema,
    durableDeleteExportRef: NonEmptyStringSchema,
    durableSupportStatusRef: NonEmptyStringSchema,
    durableEnvelopeReady: Schema.Boolean,
    durableEnvelopeMissingArtifactCount: NetworkRemoteDeliveryCount,
    outboxRef: NonEmptyStringSchema,
    outboxHandoffRef: NonEmptyStringSchema,
    outboxReplayRef: NonEmptyStringSchema,
    outboxSupportStatusRef: NonEmptyStringSchema,
    transportDispatchStateRef: NonEmptyStringSchema,
    blockedDispatchRef: NonEmptyStringSchema,
    futureTransportSeamRef: NonEmptyStringSchema,
    fixtureTransportRef: NonEmptyStringSchema,
    fixtureDispatchAttemptRef: NonEmptyStringSchema,
    fixtureAckRef: NonEmptyStringSchema,
    deleteExportPropagationRef: NonEmptyStringSchema,
    remoteDeleteReadinessRef: NonEmptyStringSchema,
    remoteExportReadinessRef: NonEmptyStringSchema,
    providerRouteRef: NonEmptyStringSchema,
    childDeviceRouteRef: NonEmptyStringSchema,
    providerDeliveryReadinessRef: NonEmptyStringSchema,
    childDeviceDeliveryReadinessRef: NonEmptyStringSchema,
    crossProcessCustodyStatusRef: NonEmptyStringSchema,
    crossProcessReplayReadinessRef: NonEmptyStringSchema,
    remoteRetentionReadinessRef: NonEmptyStringSchema,
    remoteDeleteCustodyReadinessRef: NonEmptyStringSchema,
    remoteExportCustodyReadinessRef: NonEmptyStringSchema,
    crossProcessReplayRef: NonEmptyStringSchema,
    crossProcessReplayStoreRef: NonEmptyStringSchema,
    crossProcessReplayCursorRef: NonEmptyStringSchema,
    externalCrossProcessTransportRef: NonEmptyStringSchema,
    externalCrossProcessTransportEnvelopeRef: NonEmptyStringSchema,
    externalCrossProcessTransportAckRef: NonEmptyStringSchema,
    transportDispatchState: AgentNetworkRemoteDeliveryTransportDispatchStateSchema,
    providerDeliveryReadinessState: AgentNetworkRemoteDeliveryProviderChildReadinessStateSchema,
    childDeviceDeliveryReadinessState: AgentNetworkRemoteDeliveryProviderChildReadinessStateSchema,
    crossProcessCustodyReadinessState: AgentNetworkRemoteDeliveryCrossProcessCustodyReadinessStateSchema,
    externalCrossProcessTransportState: AgentNetworkRemoteDeliveryExternalCrossProcessTransportStateSchema,
    outboxCandidateCount: NetworkRemoteDeliveryCount,
    sourceOutboxCandidateCount: NetworkRemoteDeliveryCount,
    preparedNotDispatchedCount: NetworkRemoteDeliveryCount,
    blockedDispatchRecordCount: NetworkRemoteDeliveryCount,
    blockedDispatchRecordsMatchOutboxCandidates: Schema.Boolean,
    fixtureSourceOutboxCandidateCount: NetworkRemoteDeliveryCount,
    fixtureDispatchAttemptCount: NetworkRemoteDeliveryCount,
    fixtureRemoteAckCount: NetworkRemoteDeliveryCount,
    fixtureRecordsMatchOutboxCandidates: Schema.Boolean,
    deleteExportReadinessRecordCount: NetworkRemoteDeliveryCount,
    remoteDeleteReadyCount: NetworkRemoteDeliveryCount,
    remoteExportReadyCount: NetworkRemoteDeliveryCount,
    deleteExportRecordsMatchFixtureAcks: Schema.Boolean,
    providerDeliveryReadinessRecordCount: NetworkRemoteDeliveryCount,
    childDeviceDeliveryReadinessRecordCount: NetworkRemoteDeliveryCount,
    providerDeliveryArtifactCount: Schema.Literal(0),
    childDeviceDeliveryArtifactCount: Schema.Literal(0),
    providerDeliveryRecordsMatchFixtureAcks: Schema.Boolean,
    childDeviceDeliveryRecordsMatchFixtureAcks: Schema.Boolean,
    crossProcessReplayReadinessRecordCount: NetworkRemoteDeliveryCount,
    remoteRetentionReadinessRecordCount: NetworkRemoteDeliveryCount,
    remoteDeleteCustodyReadinessRecordCount: NetworkRemoteDeliveryCount,
    remoteExportCustodyReadinessRecordCount: NetworkRemoteDeliveryCount,
    crossProcessCustodyRecordsMatchProviderChildReadiness: Schema.Boolean,
    crossProcessReplayArtifactCount: Schema.Literal(0),
    remoteRetentionArtifactCount: Schema.Literal(0),
    remoteDeleteCustodyArtifactCount: Schema.Literal(0),
    remoteExportCustodyArtifactCount: Schema.Literal(0),
    crossProcessReplayRecordCount: NetworkRemoteDeliveryCount,
    crossProcessReplayStoreWriteCount: NetworkRemoteDeliveryCount,
    crossProcessReplayCursorNextSequence: NetworkRemoteDeliveryCount,
    crossProcessReplayRecordsMatchDurableEnvelopes: Schema.Boolean,
    crossProcessReplayRecordsMatchCustodyReadiness: Schema.Boolean,
    externalCrossProcessTransportRecordCount: NetworkRemoteDeliveryCount,
    externalCrossProcessTransportEnvelopeCount: NetworkRemoteDeliveryCount,
    externalCrossProcessTransportAckCount: NetworkRemoteDeliveryCount,
    externalCrossProcessTransportRecordsMatchReplayRecords: Schema.Boolean,
    externalCrossProcessTransportAckRecordsMatchEnvelopes: Schema.Boolean,
    dispatchReadyCandidateCount: Schema.Literal(0),
    dispatchAttemptCount: Schema.Literal(0),
    remoteAckCount: Schema.Literal(0),
    duplicateDurableEnvelopeRejected: Schema.Boolean,
    outboxCandidatesMatchDurableEnvelopes: Schema.Boolean,
    outboxCandidatesMatchReceipts: Schema.Boolean,
    sequenceGapCount: Schema.Literal(0),
    eventIdMismatchCount: Schema.Literal(0),
    eventTypeMismatchCount: Schema.Literal(0),
    correlationMismatchCount: Schema.Literal(0),
    brokerDeliveryImplemented: Schema.Literal(false),
    familyHubDeliveryImplemented: Schema.Literal(false),
    remoteDeliveryAckImplemented: Schema.Literal(false),
    providerDeliveryImplemented: Schema.Literal(false),
    childDeviceDeliveryImplemented: Schema.Literal(false),
    crossProcessReplayImplemented: Schema.Literal(true),
    externalCrossProcessTransportImplemented: Schema.Literal(true),
    remoteDeleteExportPropagationImplemented: Schema.Literal(false),
    productReadyRemoteDelivery: Schema.Literal(false),
    policyAuthority: Schema.Literal(false),
    sideEffectAuthority: Schema.Literal(false),
    hostFilteringClaimed: Schema.Literal(false),
    enforcementCommandEventCount: Schema.Literal(0),
    adapterActionExecutedCount: Schema.Literal(0),
    rawPcapAvailableCount: Schema.Literal(0),
    exactUrlAvailableCount: Schema.Literal(0),
    decryptedPayloadAvailableCount: Schema.Literal(0),
    pageContentAvailableCount: Schema.Literal(0),
    videoContentAvailableCount: Schema.Literal(0),
    privateMessageContentAvailableCount: Schema.Literal(0),
    searchQueryAvailableCount: Schema.Literal(0),
  })
);

export type AgentNetworkRemoteDeliveryStatus = Infer<typeof AgentNetworkRemoteDeliveryStatusSchema>;
