/* thin adapter over Rust-owned generated notification local outbox contracts */

import * as Generated from './generated-notification-local-outbox';

export const RequiredNotificationLocalOutboxStates = Generated.GeneratedRequiredNotificationLocalOutboxStates;
export const RequiredNotificationLocalOutboxNonClaims = Generated.GeneratedRequiredNotificationLocalOutboxNonClaims;
export const NotificationLocalOutboxForbiddenDetailFragments =
  Generated.GeneratedNotificationLocalOutboxForbiddenDetailFragments;
export const NotificationLocalOutboxKnownGaps = Generated.GeneratedNotificationLocalOutboxKnownGaps;
export const NotificationLocalOutboxProviderChannels = Generated.GeneratedNotificationLocalOutboxProviderChannels;
export const NotificationLocalOutboxProofTimestamp = Generated.GeneratedNotificationLocalOutboxProofTimestamp;
export const NotificationLocalOutboxProofFamily = Generated.GeneratedNotificationLocalOutboxProofFamily;
export const NotificationLocalOutboxProofDevice = Generated.GeneratedNotificationLocalOutboxProofDevice;
export const NotificationLocalOutboxProofParentAction = Generated.GeneratedNotificationLocalOutboxProofParentAction;
export const NotificationLocalOutboxProofEvidenceRef = Generated.GeneratedNotificationLocalOutboxProofEvidenceRef;
export const NotificationLocalOutboxProofRows = Generated.GeneratedNotificationLocalOutboxProofRows;

export const RequiredNotificationLocalOutboxSchedulerStates =
  Generated.GeneratedRequiredNotificationLocalOutboxSchedulerStates;
export const RequiredNotificationLocalOutboxSchedulerNonClaims =
  Generated.GeneratedRequiredNotificationLocalOutboxSchedulerNonClaims;
export const NotificationLocalOutboxSchedulerProofTimestamp =
  Generated.GeneratedNotificationLocalOutboxSchedulerProofTimestamp;
export const NotificationLocalOutboxSchedulerProofNow = Generated.GeneratedNotificationLocalOutboxSchedulerProofNow;
export const NotificationLocalOutboxSchedulerArtifactRef =
  Generated.GeneratedNotificationLocalOutboxSchedulerArtifactRef;
export const NotificationLocalOutboxSchedulerKnownGaps = Generated.GeneratedNotificationLocalOutboxSchedulerKnownGaps;
export const NotificationLocalOutboxSchedulerProofRows = Generated.GeneratedNotificationLocalOutboxSchedulerProofRows;
