import * as contracts from './setup-registration-entry-contracts';
import * as evaluation from './setup-registration-entry-evaluation';

export const RegistrationEntryRouteLiteral = contracts.RegistrationEntryRouteLiteral;
export const RegistrationRecoveryMethodLiteral = contracts.RegistrationRecoveryMethodLiteral;
export const RegistrationIdentityProviderStateLiteral = contracts.RegistrationIdentityProviderStateLiteral;
export const RegistrationSetupStateLiteral = contracts.RegistrationSetupStateLiteral;
export const RegistrationEntryRejectionReasonLiteral = contracts.RegistrationEntryRejectionReasonLiteral;
export const RegistrationEntryFailureStateLiteral = contracts.RegistrationEntryFailureStateLiteral;
export const RegistrationHandoffFieldLiteral = contracts.RegistrationHandoffFieldLiteral;
export const RegistrationForbiddenCollectionLiteral = contracts.RegistrationForbiddenCollectionLiteral;

export const RegistrationEntryRouteSchema = contracts.RegistrationEntryRouteSchema;
export const RegistrationRecoveryMethodSchema = contracts.RegistrationRecoveryMethodSchema;
export const RegistrationIdentityProviderStateSchema = contracts.RegistrationIdentityProviderStateSchema;
export const RegistrationSetupStateSchema = contracts.RegistrationSetupStateSchema;
export const RegistrationEntryRejectionReasonSchema = contracts.RegistrationEntryRejectionReasonSchema;
export const RegistrationEntryFailureStateSchema = contracts.RegistrationEntryFailureStateSchema;
export const RegistrationHandoffFieldSchema = contracts.RegistrationHandoffFieldSchema;
export const RegistrationForbiddenCollectionSchema = contracts.RegistrationForbiddenCollectionSchema;
export const RegistrationEntryRouteContractSchema = contracts.RegistrationEntryRouteContractSchema;
export const RegistrationStateMatrixRowSchema = contracts.RegistrationStateMatrixRowSchema;
export const RegistrationIdentityHandoffSchema = contracts.RegistrationIdentityHandoffSchema;
export const RegistrationEntryDecisionSchema = contracts.RegistrationEntryDecisionSchema;

export type RegistrationEntryRoute = contracts.RegistrationEntryRoute;
export type RegistrationRecoveryMethod = contracts.RegistrationRecoveryMethod;
export type RegistrationIdentityProviderState = contracts.RegistrationIdentityProviderState;
export type RegistrationSetupState = contracts.RegistrationSetupState;
export type RegistrationEntryRejectionReason = contracts.RegistrationEntryRejectionReason;
export type RegistrationEntryFailureState = contracts.RegistrationEntryFailureState;
export type RegistrationHandoffField = contracts.RegistrationHandoffField;
export type RegistrationForbiddenCollection = contracts.RegistrationForbiddenCollection;
export type RegistrationEntryRouteContract = contracts.RegistrationEntryRouteContract;
export type RegistrationStateMatrixRow = contracts.RegistrationStateMatrixRow;
export type RegistrationIdentityHandoff = contracts.RegistrationIdentityHandoff;
export type RegistrationEntryDecision = contracts.RegistrationEntryDecision;

export const RegistrationEntryRoute = contracts.RegistrationEntryRoute;
export const RegistrationRecoveryMethod = contracts.RegistrationRecoveryMethod;
export const RegistrationIdentityProviderState = contracts.RegistrationIdentityProviderState;
export const RegistrationSetupState = contracts.RegistrationSetupState;
export const RegistrationEntryRejectionReason = contracts.RegistrationEntryRejectionReason;
export const RegistrationEntryFailureState = contracts.RegistrationEntryFailureState;

export const RegistrationEntryRouteContracts = contracts.RegistrationEntryRouteContracts;
export const RegistrationStateMatrix = contracts.RegistrationStateMatrix;

export const registrationEntryRouteContract = evaluation.registrationEntryRouteContract;
export const registrationStateMatrixRow = evaluation.registrationStateMatrixRow;
export const deriveRegistrationSetupState = evaluation.deriveRegistrationSetupState;
export const evaluateRegistrationIdentityHandoff = evaluation.evaluateRegistrationIdentityHandoff;
