/* thin adapter over Rust-owned generated v0.8 notification provider status boundary contracts */

import * as Generated from './generated-v0-8-notification-provider-status-boundary';

export const V08NotificationProviderStatusBoundaryReadModelIdSchema =
  Generated.V08NotificationProviderStatusBoundaryReadModelIdSchema;
export const V08NotificationProviderStatusBoundaryEntryIdSchema =
  Generated.V08NotificationProviderStatusBoundaryEntryIdSchema;
export const V08NotificationProviderStatusBoundaryReferenceSchema =
  Generated.V08NotificationProviderStatusBoundaryReferenceSchema;
export const V08NotificationProviderStatusBoundaryRequirementSchema =
  Generated.V08NotificationProviderStatusBoundaryRequirementSchema;
export const V08NotificationProviderStatusBoundaryTextSchema =
  Generated.V08NotificationProviderStatusBoundaryTextSchema;

export const V08NotificationProviderStatusSchema = Generated.V08NotificationProviderStatusSchema;
export const V08NotificationProviderStatusProofStateSchema = Generated.V08NotificationProviderStatusProofStateSchema;
export const V08NotificationQuietHoursReadinessSchema = Generated.V08NotificationQuietHoursReadinessSchema;
export const V08NotificationEscalationReadinessSchema = Generated.V08NotificationEscalationReadinessSchema;
export const V08NotificationProviderDeliveryClaimSchema = Generated.V08NotificationProviderDeliveryClaimSchema;

export const V08NotificationProviderStatusBoundaryEntrySchema =
  Generated.V08NotificationProviderStatusBoundaryEntrySchema;
export const V08NotificationProviderStatusBoundaryReadModelSchema =
  Generated.V08NotificationProviderStatusBoundaryReadModelSchema;

export type V08NotificationProviderStatusBoundaryReadModelId =
  Generated.V08NotificationProviderStatusBoundaryReadModelId;
export type V08NotificationProviderStatusBoundaryEntryId = Generated.V08NotificationProviderStatusBoundaryEntryId;
export type V08NotificationProviderStatusBoundaryReference = Generated.V08NotificationProviderStatusBoundaryReference;
export type V08NotificationProviderStatusBoundaryRequirement =
  Generated.V08NotificationProviderStatusBoundaryRequirement;
export type V08NotificationProviderStatusBoundaryText = Generated.V08NotificationProviderStatusBoundaryText;
export type V08NotificationProviderStatus = Generated.V08NotificationProviderStatus;
export type V08NotificationProviderStatusProofState = Generated.V08NotificationProviderStatusProofState;
export type V08NotificationQuietHoursReadiness = Generated.V08NotificationQuietHoursReadiness;
export type V08NotificationEscalationReadiness = Generated.V08NotificationEscalationReadiness;
export type V08NotificationProviderDeliveryClaim = Generated.V08NotificationProviderDeliveryClaim;
export type V08NotificationProviderStatusBoundaryEntry = Generated.V08NotificationProviderStatusBoundaryEntry;
export type V08NotificationProviderStatusBoundaryReadModel = Generated.V08NotificationProviderStatusBoundaryReadModel;

export const V08NotificationProviderStatusBoundaryReadModel = Generated.V08NotificationProviderStatusBoundaryReadModel;
export const decodeV08NotificationProviderStatusBoundaryEntry =
  Generated.decodeV08NotificationProviderStatusBoundaryEntry;
export const decodeV08NotificationProviderStatusBoundaryReadModel =
  Generated.decodeV08NotificationProviderStatusBoundaryReadModel;
