[package]
name = "ocentra-app-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ocentra-eventing = { path = "../ocentra-eventing" }
ocentra-parent-agent-protocol = { path = "../agent-protocol" }
serde = { version = "1.0.228", features = ["derive"] }
