use super::activity_surface_app_game_boundary_fixtures::{evidence_claim, identity_row};
use super::activity_surface_common_fixtures::{
    evidence_ref, TEST_FIRST_OBSERVED_AT, TEST_SECOND_OBSERVED_AT, TEST_THIRD_OBSERVED_AT,
    TEST_TIMESTAMP,
};
use ocentra_parent_agent_protocol::app_game::{
    AppGameForegroundEvidenceRow, AppGameInventoryEvidenceRow, AppGameLauncherEvidenceRow,
    AppGameRuntimeEvidenceRow, AppGameServiceReadModel, AppGameSessionDailyRollup,
    APP_GAME_CAPABILITY_STATUS_AVAILABLE, APP_GAME_CAPABILITY_STATUS_PERMISSION_LIMITED,
    APP_GAME_CATALOG_NOT_LOADED, APP_GAME_CATALOG_READY, APP_GAME_CLASSIFICATION_KNOWN_APP,
    APP_GAME_CLASSIFICATION_KNOWN_GAME, APP_GAME_CLASSIFICATION_KNOWN_LAUNCHER,
    APP_GAME_CONTENT_KNOWLEDGE_NOT_CLAIMED, APP_GAME_FOREGROUND_FOREGROUND,
    APP_GAME_FOREGROUND_NOT_CLAIMED, APP_GAME_INVENTORY_CUSTODY_LOCAL_AGENT,
    APP_GAME_INVENTORY_SOURCE_OS_INSTALLED_RECORD, APP_GAME_INVENTORY_SOURCE_STORE_PACKAGE,
    APP_GAME_INVENTORY_STATE_INSTALLED, APP_GAME_JOURNAL_CUSTODY_LOCAL_SQLITE,
    APP_GAME_JOURNAL_REPLAY_STATE_REPLAYED, APP_GAME_OBSERVATION_MODE_FOREGROUND_WINDOW,
    APP_GAME_OBSERVATION_MODE_PROCESS_SNAPSHOT, APP_GAME_PRODUCT_NATIVE_APP,
    APP_GAME_PRODUCT_NATIVE_GAME, APP_GAME_RUNTIME_NOT_CLAIMED, APP_GAME_RUNTIME_RUNNING,
    APP_GAME_SCHEMA_VERSION,
};

pub(crate) fn app_game_service_model() -> AppGameServiceReadModel {
    let runtime_evidence = evidence_ref("game-runtime-evidence-1", None);
    AppGameServiceReadModel {
        schema_version: APP_GAME_SCHEMA_VERSION,
        generated_at: TEST_TIMESTAMP.to_string(),
        limit: 10,
        custody_label: APP_GAME_JOURNAL_CUSTODY_LOCAL_SQLITE.to_string(),
        replay_state: APP_GAME_JOURNAL_REPLAY_STATE_REPLAYED.to_string(),
        capability_status: APP_GAME_CAPABILITY_STATUS_PERMISSION_LIMITED.to_string(),
        inventory_returned: 2,
        running_now_returned: 2,
        foreground_now_returned: 2,
        launcher_returned: 1,
        daily_rollup_returned: 2,
        evidence_claim_returned: 1,
        identity_returned: 1,
        approval_authority_returned: 0,
        approval_action_result_returned: 0,
        platform_authority_matrix_returned: 0,
        ai_classifier_result_returned: 0,
        inventory_rows: vec![app_inventory_row(), game_inventory_row()],
        running_now_rows: vec![app_runtime_row(), game_runtime_row()],
        foreground_now_rows: vec![app_foreground_row(), game_foreground_row()],
        launcher_rows: vec![game_launcher_row()],
        daily_rollups: vec![app_rollup(), game_rollup()],
        evidence_claim_rows: vec![evidence_claim(runtime_evidence)],
        identity_rows: vec![identity_row(evidence_ref("app-identity-1", None))],
        approval_authority_rows: Vec::new(),
        approval_action_result_rows: Vec::new(),
        platform_authority_matrices: Vec::new(),
        ai_classifier_result_rows: Vec::new(),
    }
}

fn app_inventory_row() -> AppGameInventoryEvidenceRow {
    AppGameInventoryEvidenceRow {
        schema_version: APP_GAME_SCHEMA_VERSION,
        inventory_entry_id: "app-inventory-1".to_string(),
        observed_at: TEST_FIRST_OBSERVED_AT.to_string(),
        source_kind: APP_GAME_INVENTORY_SOURCE_OS_INSTALLED_RECORD.to_string(),
        source_ref: "registry:app-1".to_string(),
        custody_state: APP_GAME_INVENTORY_CUSTODY_LOCAL_AGENT.to_string(),
        product_kind: APP_GAME_PRODUCT_NATIVE_APP.to_string(),
        display_label: "Ocentra Parent App".to_string(),
        identity_id: Some("app-identity-1".to_string()),
        package_id: None,
        bundle_id: None,
        app_user_model_id: None,
        desktop_entry_id: None,
        executable_path_ref: Some("path:app".to_string()),
        launcher_ref: None,
        launcher_app_id: None,
        launcher_manifest_id: None,
        store_id: None,
        catalog_ref: Some("catalog-app-1".to_string()),
        inventory_state: APP_GAME_INVENTORY_STATE_INSTALLED.to_string(),
        classification_state: APP_GAME_CLASSIFICATION_KNOWN_APP.to_string(),
        catalog_ready_state: APP_GAME_CATALOG_READY.to_string(),
        capability_status: APP_GAME_CAPABILITY_STATUS_AVAILABLE.to_string(),
        confidence: 0.88,
        category_candidates: Vec::new(),
        runtime_state: APP_GAME_RUNTIME_NOT_CLAIMED.to_string(),
        foreground_state: APP_GAME_FOREGROUND_NOT_CLAIMED.to_string(),
        running_duration_ms: 0,
        foreground_duration_ms: 0,
        evidence: vec![evidence_ref("app-inventory-evidence-1", None)],
    }
}

fn game_inventory_row() -> AppGameInventoryEvidenceRow {
    AppGameInventoryEvidenceRow {
        schema_version: APP_GAME_SCHEMA_VERSION,
        inventory_entry_id: "game-inventory-1".to_string(),
        observed_at: TEST_SECOND_OBSERVED_AT.to_string(),
        source_kind: APP_GAME_INVENTORY_SOURCE_STORE_PACKAGE.to_string(),
        source_ref: "store:game-1".to_string(),
        custody_state: APP_GAME_INVENTORY_CUSTODY_LOCAL_AGENT.to_string(),
        product_kind: APP_GAME_PRODUCT_NATIVE_GAME.to_string(),
        display_label: "Ocentra Game".to_string(),
        identity_id: Some("game-identity-1".to_string()),
        package_id: None,
        bundle_id: None,
        app_user_model_id: None,
        desktop_entry_id: None,
        executable_path_ref: Some("path:game".to_string()),
        launcher_ref: Some("steam".to_string()),
        launcher_app_id: None,
        launcher_manifest_id: None,
        store_id: None,
        catalog_ref: Some("catalog-game-1".to_string()),
        inventory_state: APP_GAME_INVENTORY_STATE_INSTALLED.to_string(),
        classification_state: APP_GAME_CLASSIFICATION_KNOWN_GAME.to_string(),
        catalog_ready_state: APP_GAME_CATALOG_READY.to_string(),
        capability_status: APP_GAME_CAPABILITY_STATUS_AVAILABLE.to_string(),
        confidence: 0.91,
        category_candidates: Vec::new(),
        runtime_state: APP_GAME_RUNTIME_NOT_CLAIMED.to_string(),
        foreground_state: APP_GAME_FOREGROUND_NOT_CLAIMED.to_string(),
        running_duration_ms: 0,
        foreground_duration_ms: 0,
        evidence: vec![evidence_ref("game-inventory-evidence-1", None)],
    }
}

fn app_runtime_row() -> AppGameRuntimeEvidenceRow {
    AppGameRuntimeEvidenceRow {
        schema_version: APP_GAME_SCHEMA_VERSION,
        runtime_evidence_id: "app-runtime-1".to_string(),
        observed_at: TEST_SECOND_OBSERVED_AT.to_string(),
        process_identity: "proc-app-1".to_string(),
        process_id: 101,
        parent_process_id: None,
        process_name: "app.exe".to_string(),
        executable_path_ref: Some("path:app".to_string()),
        publisher_signature_ref: None,
        file_hash_ref: None,
        inventory_entry_id: Some("app-inventory-1".to_string()),
        launcher_ref: None,
        catalog_ref: Some("catalog-app-1".to_string()),
        started_at: Some(TEST_FIRST_OBSERVED_AT.to_string()),
        exited_at: None,
        running_duration_ms: 900,
        runtime_state: APP_GAME_RUNTIME_RUNNING.to_string(),
        foreground_state: APP_GAME_FOREGROUND_NOT_CLAIMED.to_string(),
        observation_mode: APP_GAME_OBSERVATION_MODE_PROCESS_SNAPSHOT.to_string(),
        classification_state: APP_GAME_CLASSIFICATION_KNOWN_APP.to_string(),
        catalog_ready_state: APP_GAME_CATALOG_READY.to_string(),
        capability_status: APP_GAME_CAPABILITY_STATUS_AVAILABLE.to_string(),
        confidence: 0.8,
        evidence: vec![evidence_ref("app-runtime-evidence-1", None)],
    }
}

fn game_runtime_row() -> AppGameRuntimeEvidenceRow {
    AppGameRuntimeEvidenceRow {
        schema_version: APP_GAME_SCHEMA_VERSION,
        runtime_evidence_id: "game-runtime-1".to_string(),
        observed_at: TEST_THIRD_OBSERVED_AT.to_string(),
        process_identity: "proc-game-1".to_string(),
        process_id: 202,
        parent_process_id: None,
        process_name: "game.exe".to_string(),
        executable_path_ref: Some("path:game".to_string()),
        publisher_signature_ref: None,
        file_hash_ref: None,
        inventory_entry_id: Some("game-inventory-1".to_string()),
        launcher_ref: Some("steam".to_string()),
        catalog_ref: Some("catalog-game-1".to_string()),
        started_at: Some(TEST_SECOND_OBSERVED_AT.to_string()),
        exited_at: None,
        running_duration_ms: 1500,
        runtime_state: APP_GAME_RUNTIME_RUNNING.to_string(),
        foreground_state: APP_GAME_FOREGROUND_NOT_CLAIMED.to_string(),
        observation_mode: APP_GAME_OBSERVATION_MODE_PROCESS_SNAPSHOT.to_string(),
        classification_state: APP_GAME_CLASSIFICATION_KNOWN_GAME.to_string(),
        catalog_ready_state: APP_GAME_CATALOG_READY.to_string(),
        capability_status: APP_GAME_CAPABILITY_STATUS_AVAILABLE.to_string(),
        confidence: 0.93,
        evidence: vec![evidence_ref("game-runtime-evidence-1", None)],
    }
}

fn app_foreground_row() -> AppGameForegroundEvidenceRow {
    AppGameForegroundEvidenceRow {
        schema_version: APP_GAME_SCHEMA_VERSION,
        foreground_evidence_id: "app-foreground-1".to_string(),
        observed_at: TEST_THIRD_OBSERVED_AT.to_string(),
        process_identity: "proc-app-1".to_string(),
        process_id: 101,
        process_name: "app.exe".to_string(),
        inventory_entry_id: Some("app-inventory-1".to_string()),
        launcher_ref: None,
        catalog_ref: Some("catalog-app-1".to_string()),
        window_ref: Some("window-app-1".to_string()),
        window_title_ref: Some("App Window".to_string()),
        title_capture_state: "captured".to_string(),
        foreground_started_at: Some(TEST_SECOND_OBSERVED_AT.to_string()),
        foreground_ended_at: None,
        foreground_duration_ms: 700,
        runtime_state: APP_GAME_RUNTIME_RUNNING.to_string(),
        foreground_state: APP_GAME_FOREGROUND_FOREGROUND.to_string(),
        observation_mode: APP_GAME_OBSERVATION_MODE_FOREGROUND_WINDOW.to_string(),
        classification_state: APP_GAME_CLASSIFICATION_KNOWN_APP.to_string(),
        catalog_ready_state: APP_GAME_CATALOG_READY.to_string(),
        capability_status: APP_GAME_CAPABILITY_STATUS_AVAILABLE.to_string(),
        content_knowledge_state: APP_GAME_CONTENT_KNOWLEDGE_NOT_CLAIMED.to_string(),
        confidence: 0.84,
        evidence: vec![evidence_ref("app-foreground-evidence-1", None)],
    }
}

fn game_foreground_row() -> AppGameForegroundEvidenceRow {
    AppGameForegroundEvidenceRow {
        schema_version: APP_GAME_SCHEMA_VERSION,
        foreground_evidence_id: "game-foreground-1".to_string(),
        observed_at: TEST_THIRD_OBSERVED_AT.to_string(),
        process_identity: "proc-game-1".to_string(),
        process_id: 202,
        process_name: "game.exe".to_string(),
        inventory_entry_id: Some("game-inventory-1".to_string()),
        launcher_ref: Some("steam".to_string()),
        catalog_ref: Some("catalog-game-1".to_string()),
        window_ref: Some("window-game-1".to_string()),
        window_title_ref: Some("Game Window".to_string()),
        title_capture_state: "captured".to_string(),
        foreground_started_at: Some(TEST_THIRD_OBSERVED_AT.to_string()),
        foreground_ended_at: None,
        foreground_duration_ms: 1100,
        runtime_state: APP_GAME_RUNTIME_RUNNING.to_string(),
        foreground_state: APP_GAME_FOREGROUND_FOREGROUND.to_string(),
        observation_mode: APP_GAME_OBSERVATION_MODE_FOREGROUND_WINDOW.to_string(),
        classification_state: APP_GAME_CLASSIFICATION_KNOWN_GAME.to_string(),
        catalog_ready_state: APP_GAME_CATALOG_READY.to_string(),
        capability_status: APP_GAME_CAPABILITY_STATUS_AVAILABLE.to_string(),
        content_knowledge_state: APP_GAME_CONTENT_KNOWLEDGE_NOT_CLAIMED.to_string(),
        confidence: 0.95,
        evidence: vec![evidence_ref("game-foreground-evidence-1", None)],
    }
}

fn game_launcher_row() -> AppGameLauncherEvidenceRow {
    AppGameLauncherEvidenceRow {
        schema_version: APP_GAME_SCHEMA_VERSION,
        launcher_evidence_id: "game-launcher-evidence-1".to_string(),
        observed_at: TEST_THIRD_OBSERVED_AT.to_string(),
        launcher_kind: "steam".to_string(),
        launcher_ref: "steam".to_string(),
        launcher_inventory_entry_id: None,
        launcher_manifest_id: None,
        launcher_app_id: None,
        launcher_process_identity: Some("proc-steam-1".to_string()),
        launcher_process_id: Some(303),
        launcher_process_name: Some("steam.exe".to_string()),
        child_process_identity: Some("proc-game-1".to_string()),
        child_inventory_entry_id: Some("game-inventory-1".to_string()),
        child_game_evidence_claim_id: Some("app-evidence-claim-1".to_string()),
        catalog_ref: Some("catalog-game-1".to_string()),
        runtime_state: APP_GAME_RUNTIME_RUNNING.to_string(),
        foreground_state: APP_GAME_FOREGROUND_NOT_CLAIMED.to_string(),
        observation_mode: "launcher-manifest".to_string(),
        classification_state: APP_GAME_CLASSIFICATION_KNOWN_LAUNCHER.to_string(),
        catalog_ready_state: APP_GAME_CATALOG_NOT_LOADED.to_string(),
        capability_status: APP_GAME_CAPABILITY_STATUS_AVAILABLE.to_string(),
        game_proof_state: "launcher-only".to_string(),
        confidence: 0.78,
        evidence: vec![evidence_ref("game-launcher-evidence-1", None)],
    }
}

fn app_rollup() -> AppGameSessionDailyRollup {
    AppGameSessionDailyRollup {
        schema_version: APP_GAME_SCHEMA_VERSION,
        rollup_date: TEST_FIRST_OBSERVED_AT.to_string(),
        classification_state: APP_GAME_CLASSIFICATION_KNOWN_APP.to_string(),
        session_count: 5,
        running_duration_ms: 1200,
        foreground_duration_ms: 700,
        background_duration_ms: 500,
        evidence_count: 1,
        session_ids: vec!["app-session-1".to_string()],
        evidence: vec![evidence_ref("app-rollup-evidence-1", None)],
    }
}

fn game_rollup() -> AppGameSessionDailyRollup {
    AppGameSessionDailyRollup {
        schema_version: APP_GAME_SCHEMA_VERSION,
        rollup_date: TEST_FIRST_OBSERVED_AT.to_string(),
        classification_state: APP_GAME_CLASSIFICATION_KNOWN_GAME.to_string(),
        session_count: 2,
        running_duration_ms: 4200,
        foreground_duration_ms: 1100,
        background_duration_ms: 3100,
        evidence_count: 1,
        session_ids: vec!["game-session-1".to_string()],
        evidence: vec![evidence_ref("game-rollup-evidence-1", None)],
    }
}
