use super::protocol_lookup;
use crate::{constants, BrowserInterventionTargetType};

impl BrowserInterventionTargetType {
    pub fn from_protocol_str(value: &str) -> Option<Self> {
        protocol_lookup(
            value,
            [
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_SITE,
                    Self::Site,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_DOMAIN,
                    Self::Domain,
                ),
                (constants::browser::INTERVENTION_TARGET_TYPE_URL, Self::Url),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_VIDEO,
                    Self::Video,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_SOCIAL_ACCOUNT_CREATION,
                    Self::SocialAccountCreation,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_SOCIAL_FEED,
                    Self::SocialFeed,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_SOCIAL_SHORT_VIDEO_FEED,
                    Self::SocialShortVideoFeed,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_SOCIAL_MESSAGING,
                    Self::SocialMessaging,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_SOCIAL_UPLOAD_POST,
                    Self::SocialUploadPost,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_SOCIAL_LIVESTREAM,
                    Self::SocialLivestream,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_UNKNOWN_SOCIAL_SITE,
                    Self::UnknownSocialSite,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_BROWSER_GAME,
                    Self::BrowserGame,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_GAME_ACCOUNT,
                    Self::GameAccount,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_GAME_PURCHASE,
                    Self::GamePurchase,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_CLOUD_GAMING,
                    Self::CloudGaming,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_UNKNOWN_GAME,
                    Self::UnknownGame,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_UNBLOCKED_GAME_SITE,
                    Self::UnblockedGameSite,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_BROWSER_PROCESS,
                    Self::BrowserProcess,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_BROWSER_SESSION,
                    Self::BrowserSession,
                ),
                (
                    constants::browser::INTERVENTION_TARGET_TYPE_UNKNOWN,
                    Self::Unknown,
                ),
            ],
        )
    }
}
