use super::protocol_lookup;
use crate::{constants, BrowserUnmanagedEnforcementState};

impl BrowserUnmanagedEnforcementState {
    pub fn from_protocol_str(value: &str) -> Option<Self> {
        protocol_lookup(
            value,
            [
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_REPORT_ONLY,
                    Self::ReportOnly,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_WARN_CHILD,
                    Self::WarnChild,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_ASK_PARENT,
                    Self::AskParent,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_TERMINATE_PROCESS,
                    Self::TerminateProcess,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_RELAUNCH_MANAGED_BROWSER,
                    Self::RelaunchManagedBrowser,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_OS_BLOCK_CONFIGURED,
                    Self::OsBlockConfigured,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_OS_BLOCK_MANUAL_REQUIRED,
                    Self::OsBlockManualRequired,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_ALLOWED_UNMANAGED_EXCEPTION,
                    Self::AllowedUnmanagedException,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_DEGRADED,
                    Self::Degraded,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_UNAVAILABLE,
                    Self::Unavailable,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_MONITOR_ONLY,
                    Self::MonitorOnly,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_REQUIRES_OS_APP_CONTROL,
                    Self::RequiresOsAppControl,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_READY_TO_BLOCK,
                    Self::ReadyToBlock,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_BLOCKED_AND_RELAUNCHED_MANAGED,
                    Self::BlockedAndRelaunchedManaged,
                ),
                (
                    constants::browser::UNMANAGED_ENFORCEMENT_UNSUPPORTED,
                    Self::Unsupported,
                ),
            ],
        )
    }
}
