#![forbid(unsafe_code)]

pub mod activity_store;
pub mod activity_store_app_game;
mod activity_store_app_game_observation;
pub mod activity_store_app_game_rows;
mod activity_store_browser;
mod activity_store_browser_intervention;
mod activity_store_connection;
mod activity_store_enforcement_audit;
pub mod activity_store_error;
mod activity_store_memory_graph;
mod activity_store_memory_graph_builder;
mod activity_store_memory_graph_index;
pub mod activity_store_memory_graph_index_persist;
mod activity_store_memory_graph_index_query;
mod activity_store_memory_graph_nodes;
mod activity_store_memory_graph_rows;
mod activity_store_network_flow;
mod activity_store_network_flow_rows;
mod activity_store_parent_rule_context;
mod activity_store_policy_preview;
mod activity_store_policy_preview_parent_rules;
mod activity_store_policy_preview_rows;
mod activity_store_policy_preview_targets;
mod activity_store_rows;
mod activity_store_screen_evidence;
pub mod authenticated_delivery_execution;
pub mod authenticated_delivery_grant;
pub mod browser_bridge_event;
mod browser_bridge_fields;
mod browser_bridge_http;
mod browser_bridge_ids;
pub mod browser_bridge_native_host;
pub mod browser_bridge_poll;
pub mod browser_event_runtime;
mod browser_event_runtime_refs;
pub mod browser_intervention_event;
pub mod browser_managed_discovery;
pub mod browser_managed_session;
pub mod browser_windows_inventory;
pub mod browser_windows_inventory_paths;
pub mod browser_windows_inventory_source;
pub mod browser_windows_package_inventory;
pub mod browser_windows_package_source;
pub mod browser_windows_shortcut_source;
pub mod enforcement_adapter;
pub mod enforcement_app_time_limit;
pub mod enforcement_boundary;
pub mod enforcement_policy_dispatch;
pub mod enforcement_readiness;
pub mod enforcement_timer_state;
pub mod household_ai_provider_route;
mod household_ai_provider_route_labels;
pub mod household_ai_provider_route_state;
pub mod household_mesh_bridge_runtime;
mod household_mesh_bridge_runtime_message;
mod household_mesh_bridge_runtime_payload;
mod household_mesh_bridge_runtime_refs;
mod household_mesh_bridge_runtime_rejection;
mod household_mesh_bridge_runtime_source;
mod household_mesh_bridge_runtime_spine;
mod household_mesh_bridge_runtime_state;
mod household_mesh_bridge_runtime_validation;
pub mod household_mesh_event_bridge;
mod household_mesh_event_bridge_lookup;
mod household_mesh_event_bridge_rejection;
pub mod journal;
pub mod journal_crypto;
pub mod journal_error;
mod journal_rotation;
pub mod network_capture;
mod network_capture_adapter;
pub mod network_capture_event;
mod network_capture_event_fields;
#[cfg(windows)]
pub mod network_capture_netstat;
pub mod network_event_runtime;
mod network_event_runtime_state;
pub mod parent_child_event_runtime;
pub mod policy_dry_run_evaluator;
pub mod process_capture;
pub mod screen_event_runtime;
pub mod screen_event_runtime_input;
mod screen_event_runtime_metadata;
mod screen_event_runtime_refs;
mod screen_event_runtime_state;
pub mod screen_evidence_queue;
pub mod screen_household_mesh_runtime;
mod screen_household_mesh_runtime_refs;
mod screen_household_mesh_runtime_state;
pub mod tracking;
pub mod trusted_device_registry;
mod trusted_device_registry_selection;
pub mod window_capture;
pub mod window_capture_event;

use activity_store::ActivityStore;
use activity_store_error::ActivityStoreError;
use browser_bridge_event::{browser_tab_observation_event, BrowserBridgeTargetObservation};
use browser_windows_package_inventory::BrowserWindowsPackageIdentity;
use household_mesh_event_bridge::HouseholdMeshLocalEventKind;
use journal::ActivityJournal;
use journal_error::JournalError;
use network_capture::NetworkObservation;
use trusted_device_registry::TrustedDeviceRegistry;

pub fn crate_name() -> &'static str {
    env!("CARGO_PKG_NAME")
}

pub mod activity_store_memory_graph_index_maintenance;
