import { type Infer, Schema } from '@ocentra-parent/schema-domain/effect';
export declare const V08EnforcementIntegrityRuntimeAuditReadModelIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReadModelId">;
export declare const V08EnforcementIntegrityRuntimeAuditEntryIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditEntryId">;
export declare const V08EnforcementIntegrityRuntimeAuditReferenceSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">;
export declare const V08EnforcementIntegrityRuntimeAuditRequirementSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditRequirement">;
export declare const V08EnforcementIntegrityRuntimeAuditBoundarySchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditBoundary">;
export declare const V08EnforcementIntegrityRuntimeAuditSurfaceSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["app-game-time-limit", "managed-browser-session", "unmanaged-browser-process-fallback", "network-domain-observe-only", "host-network-domain-filter", "notification-delivery", "integrity-heartbeat", "tamper-uninstall-signal", "mobile-child-control"]>>;
export declare const V08EnforcementIntegrityRuntimeAuditResultSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["succeeded", "failed", "unavailable", "expired", "rolled-back", "superseded", "no-op", "manual-required", "unsupported", "observe-only"]>>;
export declare const V08EnforcementIntegrityRuntimeAuditExecutionSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["executed-supported-boundary", "dry-run-no-adapter-execution", "rejected-before-adapter", "manual-required-no-execution", "observe-only-no-execution", "unavailable-no-execution", "unsupported-no-execution", "recovery-needed-no-execution"]>>;
export declare const V08EnforcementIntegrityRuntimeAuditIntentStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["validated", "observe-only", "rejected-invalid", "rejected-stale", "rejected-wrong-device", "rejected-unsupported"]>>;
export declare const V08EnforcementIntegrityRuntimeAuditTimerStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["active-timer-backed", "expired-backed", "cancelled-backed", "rollback-backed", "recovery-needed", "not-applicable", "unavailable"]>>;
export declare const V08EnforcementIntegrityRuntimeAuditRollbackStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["not-needed", "rollback-token-backed", "rollback-completed", "rollback-required", "manual-required", "unavailable"]>>;
export declare const V08EnforcementIntegrityRuntimeAuditChildStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["status-ref-backed", "reason-ref-backed", "approval-intent-backed", "manual-required", "unsupported", "not-claimed"]>>;
export declare const V08EnforcementIntegrityRuntimeAuditIntegrityStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["running", "permission-missing", "adapter-unavailable", "stale-heartbeat", "service-stopped", "uninstall-detection-manual-required", "tamper-signal-manual-required", "anti-tamper-not-claimed", "not-applicable"]>>;
export declare const V08EnforcementIntegrityRuntimeAuditAuditStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-backed", "audit-required", "manual-required", "unavailable", "not-claimed"]>>;
export declare const V08EnforcementIntegrityRuntimeAuditEntrySchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
    schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
    auditEntryId: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditEntryId">;
    surface: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["app-game-time-limit", "managed-browser-session", "unmanaged-browser-process-fallback", "network-domain-observe-only", "host-network-domain-filter", "notification-delivery", "integrity-heartbeat", "tamper-uninstall-signal", "mobile-child-control"]>>;
    platform: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["windows", "linux", "macos", "android", "ios"]>>;
    result: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["succeeded", "failed", "unavailable", "expired", "rolled-back", "superseded", "no-op", "manual-required", "unsupported", "observe-only"]>>;
    execution: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["executed-supported-boundary", "dry-run-no-adapter-execution", "rejected-before-adapter", "manual-required-no-execution", "observe-only-no-execution", "unavailable-no-execution", "unsupported-no-execution", "recovery-needed-no-execution"]>>;
    intentState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["validated", "observe-only", "rejected-invalid", "rejected-stale", "rejected-wrong-device", "rejected-unsupported"]>>;
    timerState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["active-timer-backed", "expired-backed", "cancelled-backed", "rollback-backed", "recovery-needed", "not-applicable", "unavailable"]>>;
    rollbackState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["not-needed", "rollback-token-backed", "rollback-completed", "rollback-required", "manual-required", "unavailable"]>>;
    childState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["status-ref-backed", "reason-ref-backed", "approval-intent-backed", "manual-required", "unsupported", "not-claimed"]>>;
    integrityState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["running", "permission-missing", "adapter-unavailable", "stale-heartbeat", "service-stopped", "uninstall-detection-manual-required", "tamper-signal-manual-required", "anti-tamper-not-claimed", "not-applicable"]>>;
    auditState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-backed", "audit-required", "manual-required", "unavailable", "not-claimed"]>>;
    policyDecisionRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    evidenceRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    adapterOutcomeRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    auditRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    rollbackRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    timerRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    childStatusRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    integrityRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    parentIntentRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    manualProofRequirements: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditRequirement">>;
    boundary: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditBoundary">;
    broadInstalledAppBlockingClaimed: typeof Schema.Boolean;
    hostNetworkDomainBlockingClaimed: typeof Schema.Boolean;
    exactActiveTabEnforcementClaimed: typeof Schema.Boolean;
    notificationDeliveryClaimed: typeof Schema.Boolean;
    tamperHardeningClaimed: typeof Schema.Boolean;
    mobilePrivilegeClaimed: typeof Schema.Boolean;
    stealthPersistenceClaimed: typeof Schema.Boolean;
    privilegeEscalationClaimed: typeof Schema.Boolean;
    lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
}>>>;
export declare const V08EnforcementIntegrityRuntimeAuditReadModelSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
    schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
    readModelId: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReadModelId">;
    generatedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
    sourceReadModelIds: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
    entries: Schema.Array$<import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
        schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
        auditEntryId: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditEntryId">;
        surface: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["app-game-time-limit", "managed-browser-session", "unmanaged-browser-process-fallback", "network-domain-observe-only", "host-network-domain-filter", "notification-delivery", "integrity-heartbeat", "tamper-uninstall-signal", "mobile-child-control"]>>;
        platform: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["windows", "linux", "macos", "android", "ios"]>>;
        result: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["succeeded", "failed", "unavailable", "expired", "rolled-back", "superseded", "no-op", "manual-required", "unsupported", "observe-only"]>>;
        execution: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["executed-supported-boundary", "dry-run-no-adapter-execution", "rejected-before-adapter", "manual-required-no-execution", "observe-only-no-execution", "unavailable-no-execution", "unsupported-no-execution", "recovery-needed-no-execution"]>>;
        intentState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["validated", "observe-only", "rejected-invalid", "rejected-stale", "rejected-wrong-device", "rejected-unsupported"]>>;
        timerState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["active-timer-backed", "expired-backed", "cancelled-backed", "rollback-backed", "recovery-needed", "not-applicable", "unavailable"]>>;
        rollbackState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["not-needed", "rollback-token-backed", "rollback-completed", "rollback-required", "manual-required", "unavailable"]>>;
        childState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["status-ref-backed", "reason-ref-backed", "approval-intent-backed", "manual-required", "unsupported", "not-claimed"]>>;
        integrityState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["running", "permission-missing", "adapter-unavailable", "stale-heartbeat", "service-stopped", "uninstall-detection-manual-required", "tamper-signal-manual-required", "anti-tamper-not-claimed", "not-applicable"]>>;
        auditState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-backed", "audit-required", "manual-required", "unavailable", "not-claimed"]>>;
        policyDecisionRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
        evidenceRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
        adapterOutcomeRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
        auditRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
        rollbackRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
        timerRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
        childStatusRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
        integrityRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
        parentIntentRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditReference">>;
        manualProofRequirements: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditRequirement">>;
        boundary: Schema.brand<Schema.filter<typeof Schema.String>, "V08EnforcementIntegrityRuntimeAuditBoundary">;
        broadInstalledAppBlockingClaimed: typeof Schema.Boolean;
        hostNetworkDomainBlockingClaimed: typeof Schema.Boolean;
        exactActiveTabEnforcementClaimed: typeof Schema.Boolean;
        notificationDeliveryClaimed: typeof Schema.Boolean;
        tamperHardeningClaimed: typeof Schema.Boolean;
        mobilePrivilegeClaimed: typeof Schema.Boolean;
        stealthPersistenceClaimed: typeof Schema.Boolean;
        privilegeEscalationClaimed: typeof Schema.Boolean;
        lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
    }>>>>;
    integrityAlertStatusBridge: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.filter<Schema.Struct<{
        schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
        readModelId: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReadModelId">;
        generatedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
        sourceReadModelIds: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
        entries: Schema.Array$<import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
            schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
            bridgeEntryId: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeEntryId">;
            integrityAlertState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["permission-loss", "stale-heartbeat", "stopped-or-removed", "tamper-manual-required"]>>;
            parentVisibleStatus: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["permission-action-required", "agent-heartbeat-stale", "agent-stopped-or-removed", "tamper-review-required"]>>;
            notificationIntentState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["intent-created", "manual-review-required"]>>;
            deliveryState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["not-delivered-provider-not-configured"]>>;
            auditState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-ref-backed", "manual-required"]>>;
            reasonCodeRef: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">;
            statusRef: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">;
            notificationIntentRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
            notificationStatusRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
            auditRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
            integrityRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
            drillInRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
            manualProofRequirements: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeRequirement">>;
            boundary: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeBoundary">;
            providerDeliveryClaimed: typeof Schema.Boolean;
            broadBlockingClaimed: typeof Schema.Boolean;
            tamperResistanceClaimed: typeof Schema.Boolean;
            mobileEnforcementClaimed: typeof Schema.Boolean;
            stealthPersistenceClaimed: typeof Schema.Boolean;
            privilegeEscalationClaimed: typeof Schema.Boolean;
            lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
        }>>>>;
    }>>>>;
    notificationProviderStatusBoundary: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.filter<Schema.filter<Schema.Struct<{
        schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
        readModelId: Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryReadModelId">;
        generatedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
        sourceReadModelIds: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryReference">>;
        entries: Schema.Array$<import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
            schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
            statusEntryId: Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryEntryId">;
            providerStatus: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["queued", "delivered", "failed", "unavailable", "manual-required"]>>;
            statusProofState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["queued-contract-only", "delivery-receipt-required", "failure-contract-only", "provider-unavailable-contract", "manual-action-required"]>>;
            quietHoursReadiness: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["ready", "defer-noncritical", "manual-required", "unavailable"]>>;
            escalationReadiness: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["ready", "waiting-window", "manual-required", "unavailable"]>>;
            deliveryClaimState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["not-implemented", "not-observed", "receipt-required"]>>;
            notificationIntentRef: Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryReference">;
            notificationStatusRef: Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryReference">;
            providerAttemptRef: Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryReference">;
            auditRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryReference">>;
            preferenceRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryReference">>;
            readinessRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryReference">>;
            providerReceiptRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryReference">>;
            manualProofRequirements: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryRequirement">>;
            minimalPayloadBoundary: Schema.brand<Schema.filter<typeof Schema.String>, "V08NotificationProviderStatusBoundaryText">;
            providerDeliveryImplemented: typeof Schema.Boolean;
            providerDeliveryObserved: typeof Schema.Boolean;
            deliveredNotificationClaimed: typeof Schema.Boolean;
            sensitiveProviderPayloadClaimed: typeof Schema.Boolean;
            providerStoresChildEvidenceClaimed: typeof Schema.Boolean;
            lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
        }>>>>;
    }>>>>>;
}>>>;
export type V08EnforcementIntegrityRuntimeAuditReadModelId = typeof V08EnforcementIntegrityRuntimeAuditReadModelIdSchema.Type;
export type V08EnforcementIntegrityRuntimeAuditEntryId = typeof V08EnforcementIntegrityRuntimeAuditEntryIdSchema.Type;
export type V08EnforcementIntegrityRuntimeAuditReference = typeof V08EnforcementIntegrityRuntimeAuditReferenceSchema.Type;
export type V08EnforcementIntegrityRuntimeAuditRequirement = typeof V08EnforcementIntegrityRuntimeAuditRequirementSchema.Type;
export type V08EnforcementIntegrityRuntimeAuditBoundary = typeof V08EnforcementIntegrityRuntimeAuditBoundarySchema.Type;
export type V08EnforcementIntegrityRuntimeAuditSurface = Infer<typeof V08EnforcementIntegrityRuntimeAuditSurfaceSchema>;
export type V08EnforcementIntegrityRuntimeAuditResult = Infer<typeof V08EnforcementIntegrityRuntimeAuditResultSchema>;
export type V08EnforcementIntegrityRuntimeAuditExecution = Infer<typeof V08EnforcementIntegrityRuntimeAuditExecutionSchema>;
export type V08EnforcementIntegrityRuntimeAuditIntentState = Infer<typeof V08EnforcementIntegrityRuntimeAuditIntentStateSchema>;
export type V08EnforcementIntegrityRuntimeAuditTimerState = Infer<typeof V08EnforcementIntegrityRuntimeAuditTimerStateSchema>;
export type V08EnforcementIntegrityRuntimeAuditRollbackState = Infer<typeof V08EnforcementIntegrityRuntimeAuditRollbackStateSchema>;
export type V08EnforcementIntegrityRuntimeAuditChildState = Infer<typeof V08EnforcementIntegrityRuntimeAuditChildStateSchema>;
export type V08EnforcementIntegrityRuntimeAuditIntegrityState = Infer<typeof V08EnforcementIntegrityRuntimeAuditIntegrityStateSchema>;
export type V08EnforcementIntegrityRuntimeAuditAuditState = Infer<typeof V08EnforcementIntegrityRuntimeAuditAuditStateSchema>;
export type V08EnforcementIntegrityRuntimeAuditEntry = Infer<typeof V08EnforcementIntegrityRuntimeAuditEntrySchema>;
export type V08EnforcementIntegrityRuntimeAuditReadModel = Infer<typeof V08EnforcementIntegrityRuntimeAuditReadModelSchema>;
export declare const V08EnforcementIntegrityRuntimeAuditReadModel: {
    readonly entries: readonly {
        readonly schemaVersion: "v0.6";
        readonly auditState: "manual-required" | "unavailable" | "not-claimed" | "audit-backed" | "audit-required";
        readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly integrityRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditRequirement">)[];
        readonly boundary: string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditBoundary">;
        readonly stealthPersistenceClaimed: boolean;
        readonly privilegeEscalationClaimed: boolean;
        readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        readonly platform: "windows" | "linux" | "macos" | "android" | "ios";
        readonly evidenceRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly broadInstalledAppBlockingClaimed: boolean;
        readonly exactActiveTabEnforcementClaimed: boolean;
        readonly notificationDeliveryClaimed: boolean;
        readonly tamperHardeningClaimed: boolean;
        readonly auditEntryId: string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditEntryId">;
        readonly surface: "app-game-time-limit" | "managed-browser-session" | "unmanaged-browser-process-fallback" | "network-domain-observe-only" | "host-network-domain-filter" | "notification-delivery" | "integrity-heartbeat" | "tamper-uninstall-signal" | "mobile-child-control";
        readonly result: "manual-required" | "unavailable" | "unsupported" | "succeeded" | "failed" | "expired" | "rolled-back" | "superseded" | "no-op" | "observe-only";
        readonly execution: "executed-supported-boundary" | "dry-run-no-adapter-execution" | "rejected-before-adapter" | "manual-required-no-execution" | "observe-only-no-execution" | "unavailable-no-execution" | "unsupported-no-execution" | "recovery-needed-no-execution";
        readonly intentState: "observe-only" | "validated" | "rejected-invalid" | "rejected-stale" | "rejected-wrong-device" | "rejected-unsupported";
        readonly timerState: "unavailable" | "not-applicable" | "active-timer-backed" | "expired-backed" | "cancelled-backed" | "rollback-backed" | "recovery-needed";
        readonly rollbackState: "manual-required" | "unavailable" | "not-needed" | "rollback-token-backed" | "rollback-completed" | "rollback-required";
        readonly childState: "manual-required" | "not-claimed" | "unsupported" | "status-ref-backed" | "reason-ref-backed" | "approval-intent-backed";
        readonly integrityState: "stale-heartbeat" | "not-applicable" | "running" | "permission-missing" | "adapter-unavailable" | "service-stopped" | "uninstall-detection-manual-required" | "tamper-signal-manual-required" | "anti-tamper-not-claimed";
        readonly policyDecisionRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly adapterOutcomeRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly rollbackRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly timerRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly childStatusRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly parentIntentRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly hostNetworkDomainBlockingClaimed: boolean;
        readonly mobilePrivilegeClaimed: boolean;
    }[];
    readonly schemaVersion: "v0.6";
    readonly readModelId: string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReadModelId">;
    readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly integrityAlertStatusBridge: {
        readonly entries: readonly {
            readonly schemaVersion: "v0.6";
            readonly bridgeEntryId: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeEntryId">;
            readonly integrityAlertState: "permission-loss" | "stale-heartbeat" | "stopped-or-removed" | "tamper-manual-required";
            readonly parentVisibleStatus: "permission-action-required" | "agent-heartbeat-stale" | "agent-stopped-or-removed" | "tamper-review-required";
            readonly notificationIntentState: "intent-created" | "manual-review-required";
            readonly deliveryState: "not-delivered-provider-not-configured";
            readonly auditState: "audit-ref-backed" | "manual-required";
            readonly reasonCodeRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
            readonly statusRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
            readonly notificationIntentRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly notificationStatusRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly integrityRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly drillInRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeRequirement">)[];
            readonly boundary: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeBoundary">;
            readonly providerDeliveryClaimed: boolean;
            readonly broadBlockingClaimed: boolean;
            readonly tamperResistanceClaimed: boolean;
            readonly mobileEnforcementClaimed: boolean;
            readonly stealthPersistenceClaimed: boolean;
            readonly privilegeEscalationClaimed: boolean;
            readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        }[];
        readonly schemaVersion: "v0.6";
        readonly readModelId: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReadModelId">;
        readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
    };
    readonly notificationProviderStatusBoundary: {
        readonly entries: readonly {
            readonly schemaVersion: "v0.6";
            readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
            readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryRequirement">)[];
            readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
            readonly statusEntryId: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryEntryId">;
            readonly providerStatus: "manual-required" | "unavailable" | "failed" | "queued" | "delivered";
            readonly statusProofState: "queued-contract-only" | "delivery-receipt-required" | "failure-contract-only" | "provider-unavailable-contract" | "manual-action-required";
            readonly quietHoursReadiness: "manual-required" | "unavailable" | "ready" | "defer-noncritical";
            readonly escalationReadiness: "manual-required" | "unavailable" | "ready" | "waiting-window";
            readonly deliveryClaimState: "not-implemented" | "not-observed" | "receipt-required";
            readonly notificationIntentRef: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">;
            readonly notificationStatusRef: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">;
            readonly providerAttemptRef: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">;
            readonly preferenceRefs: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
            readonly readinessRefs: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
            readonly providerReceiptRefs: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
            readonly minimalPayloadBoundary: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryText">;
            readonly providerDeliveryImplemented: boolean;
            readonly providerDeliveryObserved: boolean;
            readonly deliveredNotificationClaimed: boolean;
            readonly sensitiveProviderPayloadClaimed: boolean;
            readonly providerStoresChildEvidenceClaimed: boolean;
        }[];
        readonly schemaVersion: "v0.6";
        readonly readModelId: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReadModelId">;
        readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
    };
};
export declare const decodeV08EnforcementIntegrityRuntimeAuditEntry: (u: unknown, overrideOptions?: import("effect/SchemaAST").ParseOptions) => {
    readonly schemaVersion: "v0.6";
    readonly auditState: "manual-required" | "unavailable" | "not-claimed" | "audit-backed" | "audit-required";
    readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly integrityRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditRequirement">)[];
    readonly boundary: string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditBoundary">;
    readonly stealthPersistenceClaimed: boolean;
    readonly privilegeEscalationClaimed: boolean;
    readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    readonly platform: "windows" | "linux" | "macos" | "android" | "ios";
    readonly evidenceRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly broadInstalledAppBlockingClaimed: boolean;
    readonly exactActiveTabEnforcementClaimed: boolean;
    readonly notificationDeliveryClaimed: boolean;
    readonly tamperHardeningClaimed: boolean;
    readonly auditEntryId: string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditEntryId">;
    readonly surface: "app-game-time-limit" | "managed-browser-session" | "unmanaged-browser-process-fallback" | "network-domain-observe-only" | "host-network-domain-filter" | "notification-delivery" | "integrity-heartbeat" | "tamper-uninstall-signal" | "mobile-child-control";
    readonly result: "manual-required" | "unavailable" | "unsupported" | "succeeded" | "failed" | "expired" | "rolled-back" | "superseded" | "no-op" | "observe-only";
    readonly execution: "executed-supported-boundary" | "dry-run-no-adapter-execution" | "rejected-before-adapter" | "manual-required-no-execution" | "observe-only-no-execution" | "unavailable-no-execution" | "unsupported-no-execution" | "recovery-needed-no-execution";
    readonly intentState: "observe-only" | "validated" | "rejected-invalid" | "rejected-stale" | "rejected-wrong-device" | "rejected-unsupported";
    readonly timerState: "unavailable" | "not-applicable" | "active-timer-backed" | "expired-backed" | "cancelled-backed" | "rollback-backed" | "recovery-needed";
    readonly rollbackState: "manual-required" | "unavailable" | "not-needed" | "rollback-token-backed" | "rollback-completed" | "rollback-required";
    readonly childState: "manual-required" | "not-claimed" | "unsupported" | "status-ref-backed" | "reason-ref-backed" | "approval-intent-backed";
    readonly integrityState: "stale-heartbeat" | "not-applicable" | "running" | "permission-missing" | "adapter-unavailable" | "service-stopped" | "uninstall-detection-manual-required" | "tamper-signal-manual-required" | "anti-tamper-not-claimed";
    readonly policyDecisionRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly adapterOutcomeRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly rollbackRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly timerRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly childStatusRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly parentIntentRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly hostNetworkDomainBlockingClaimed: boolean;
    readonly mobilePrivilegeClaimed: boolean;
};
export declare const decodeV08EnforcementIntegrityRuntimeAuditReadModel: (u: unknown, overrideOptions?: import("effect/SchemaAST").ParseOptions) => {
    readonly entries: readonly {
        readonly schemaVersion: "v0.6";
        readonly auditState: "manual-required" | "unavailable" | "not-claimed" | "audit-backed" | "audit-required";
        readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly integrityRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditRequirement">)[];
        readonly boundary: string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditBoundary">;
        readonly stealthPersistenceClaimed: boolean;
        readonly privilegeEscalationClaimed: boolean;
        readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        readonly platform: "windows" | "linux" | "macos" | "android" | "ios";
        readonly evidenceRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly broadInstalledAppBlockingClaimed: boolean;
        readonly exactActiveTabEnforcementClaimed: boolean;
        readonly notificationDeliveryClaimed: boolean;
        readonly tamperHardeningClaimed: boolean;
        readonly auditEntryId: string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditEntryId">;
        readonly surface: "app-game-time-limit" | "managed-browser-session" | "unmanaged-browser-process-fallback" | "network-domain-observe-only" | "host-network-domain-filter" | "notification-delivery" | "integrity-heartbeat" | "tamper-uninstall-signal" | "mobile-child-control";
        readonly result: "manual-required" | "unavailable" | "unsupported" | "succeeded" | "failed" | "expired" | "rolled-back" | "superseded" | "no-op" | "observe-only";
        readonly execution: "executed-supported-boundary" | "dry-run-no-adapter-execution" | "rejected-before-adapter" | "manual-required-no-execution" | "observe-only-no-execution" | "unavailable-no-execution" | "unsupported-no-execution" | "recovery-needed-no-execution";
        readonly intentState: "observe-only" | "validated" | "rejected-invalid" | "rejected-stale" | "rejected-wrong-device" | "rejected-unsupported";
        readonly timerState: "unavailable" | "not-applicable" | "active-timer-backed" | "expired-backed" | "cancelled-backed" | "rollback-backed" | "recovery-needed";
        readonly rollbackState: "manual-required" | "unavailable" | "not-needed" | "rollback-token-backed" | "rollback-completed" | "rollback-required";
        readonly childState: "manual-required" | "not-claimed" | "unsupported" | "status-ref-backed" | "reason-ref-backed" | "approval-intent-backed";
        readonly integrityState: "stale-heartbeat" | "not-applicable" | "running" | "permission-missing" | "adapter-unavailable" | "service-stopped" | "uninstall-detection-manual-required" | "tamper-signal-manual-required" | "anti-tamper-not-claimed";
        readonly policyDecisionRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly adapterOutcomeRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly rollbackRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly timerRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly childStatusRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly parentIntentRefs: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
        readonly hostNetworkDomainBlockingClaimed: boolean;
        readonly mobilePrivilegeClaimed: boolean;
    }[];
    readonly schemaVersion: "v0.6";
    readonly readModelId: string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReadModelId">;
    readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08EnforcementIntegrityRuntimeAuditReference">)[];
    readonly integrityAlertStatusBridge: {
        readonly entries: readonly {
            readonly schemaVersion: "v0.6";
            readonly bridgeEntryId: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeEntryId">;
            readonly integrityAlertState: "permission-loss" | "stale-heartbeat" | "stopped-or-removed" | "tamper-manual-required";
            readonly parentVisibleStatus: "permission-action-required" | "agent-heartbeat-stale" | "agent-stopped-or-removed" | "tamper-review-required";
            readonly notificationIntentState: "intent-created" | "manual-review-required";
            readonly deliveryState: "not-delivered-provider-not-configured";
            readonly auditState: "audit-ref-backed" | "manual-required";
            readonly reasonCodeRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
            readonly statusRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
            readonly notificationIntentRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly notificationStatusRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly integrityRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly drillInRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
            readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeRequirement">)[];
            readonly boundary: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeBoundary">;
            readonly providerDeliveryClaimed: boolean;
            readonly broadBlockingClaimed: boolean;
            readonly tamperResistanceClaimed: boolean;
            readonly mobileEnforcementClaimed: boolean;
            readonly stealthPersistenceClaimed: boolean;
            readonly privilegeEscalationClaimed: boolean;
            readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        }[];
        readonly schemaVersion: "v0.6";
        readonly readModelId: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReadModelId">;
        readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
    };
    readonly notificationProviderStatusBoundary: {
        readonly entries: readonly {
            readonly schemaVersion: "v0.6";
            readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
            readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryRequirement">)[];
            readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
            readonly statusEntryId: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryEntryId">;
            readonly providerStatus: "manual-required" | "unavailable" | "failed" | "queued" | "delivered";
            readonly statusProofState: "queued-contract-only" | "delivery-receipt-required" | "failure-contract-only" | "provider-unavailable-contract" | "manual-action-required";
            readonly quietHoursReadiness: "manual-required" | "unavailable" | "ready" | "defer-noncritical";
            readonly escalationReadiness: "manual-required" | "unavailable" | "ready" | "waiting-window";
            readonly deliveryClaimState: "not-implemented" | "not-observed" | "receipt-required";
            readonly notificationIntentRef: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">;
            readonly notificationStatusRef: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">;
            readonly providerAttemptRef: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">;
            readonly preferenceRefs: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
            readonly readinessRefs: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
            readonly providerReceiptRefs: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
            readonly minimalPayloadBoundary: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryText">;
            readonly providerDeliveryImplemented: boolean;
            readonly providerDeliveryObserved: boolean;
            readonly deliveredNotificationClaimed: boolean;
            readonly sensitiveProviderPayloadClaimed: boolean;
            readonly providerStoresChildEvidenceClaimed: boolean;
        }[];
        readonly schemaVersion: "v0.6";
        readonly readModelId: string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReadModelId">;
        readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08NotificationProviderStatusBoundaryReference">)[];
    };
};
//# sourceMappingURL=v0-8-enforcement-integrity-runtime-audit.d.ts.map