import { type Infer, Schema } from '@ocentra-parent/schema-domain/effect';
export declare const V08IntegrityAlertStatusBridgeReadModelIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReadModelId">;
export declare const V08IntegrityAlertStatusBridgeEntryIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeEntryId">;
export declare const V08IntegrityAlertStatusBridgeReferenceSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">;
export declare const V08IntegrityAlertStatusBridgeRequirementSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeRequirement">;
export declare const V08IntegrityAlertStatusBridgeBoundarySchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeBoundary">;
export declare const V08IntegrityAlertStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["permission-loss", "stale-heartbeat", "stopped-or-removed", "tamper-manual-required"]>>;
export declare const V08IntegrityAlertParentVisibleStatusSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["permission-action-required", "agent-heartbeat-stale", "agent-stopped-or-removed", "tamper-review-required"]>>;
export declare const V08IntegrityAlertNotificationIntentStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["intent-created", "manual-review-required"]>>;
export declare const V08IntegrityAlertDeliveryStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["not-delivered-provider-not-configured"]>>;
export declare const V08IntegrityAlertAuditStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-ref-backed", "manual-required"]>>;
export declare const V08IntegrityAlertStatusBridgeEntrySchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
    schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
    bridgeEntryId: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeEntryId">;
    integrityAlertState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["permission-loss", "stale-heartbeat", "stopped-or-removed", "tamper-manual-required"]>>;
    parentVisibleStatus: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["permission-action-required", "agent-heartbeat-stale", "agent-stopped-or-removed", "tamper-review-required"]>>;
    notificationIntentState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["intent-created", "manual-review-required"]>>;
    deliveryState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["not-delivered-provider-not-configured"]>>;
    auditState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-ref-backed", "manual-required"]>>;
    reasonCodeRef: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">;
    statusRef: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">;
    notificationIntentRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
    notificationStatusRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
    auditRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
    integrityRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
    drillInRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
    manualProofRequirements: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeRequirement">>;
    boundary: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeBoundary">;
    providerDeliveryClaimed: typeof Schema.Boolean;
    broadBlockingClaimed: typeof Schema.Boolean;
    tamperResistanceClaimed: typeof Schema.Boolean;
    mobileEnforcementClaimed: typeof Schema.Boolean;
    stealthPersistenceClaimed: typeof Schema.Boolean;
    privilegeEscalationClaimed: typeof Schema.Boolean;
    lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
}>>>;
export declare const V08IntegrityAlertStatusBridgeReadModelSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.filter<Schema.Struct<{
    schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
    readModelId: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReadModelId">;
    generatedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
    sourceReadModelIds: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
    entries: Schema.Array$<import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
        schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
        bridgeEntryId: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeEntryId">;
        integrityAlertState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["permission-loss", "stale-heartbeat", "stopped-or-removed", "tamper-manual-required"]>>;
        parentVisibleStatus: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["permission-action-required", "agent-heartbeat-stale", "agent-stopped-or-removed", "tamper-review-required"]>>;
        notificationIntentState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["intent-created", "manual-review-required"]>>;
        deliveryState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["not-delivered-provider-not-configured"]>>;
        auditState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-ref-backed", "manual-required"]>>;
        reasonCodeRef: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">;
        statusRef: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">;
        notificationIntentRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
        notificationStatusRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
        auditRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
        integrityRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
        drillInRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeReference">>;
        manualProofRequirements: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeRequirement">>;
        boundary: Schema.brand<Schema.filter<typeof Schema.String>, "V08IntegrityAlertStatusBridgeBoundary">;
        providerDeliveryClaimed: typeof Schema.Boolean;
        broadBlockingClaimed: typeof Schema.Boolean;
        tamperResistanceClaimed: typeof Schema.Boolean;
        mobileEnforcementClaimed: typeof Schema.Boolean;
        stealthPersistenceClaimed: typeof Schema.Boolean;
        privilegeEscalationClaimed: typeof Schema.Boolean;
        lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
    }>>>>;
}>>>>;
export type V08IntegrityAlertStatusBridgeReadModelId = typeof V08IntegrityAlertStatusBridgeReadModelIdSchema.Type;
export type V08IntegrityAlertStatusBridgeEntryId = typeof V08IntegrityAlertStatusBridgeEntryIdSchema.Type;
export type V08IntegrityAlertStatusBridgeReference = typeof V08IntegrityAlertStatusBridgeReferenceSchema.Type;
export type V08IntegrityAlertStatusBridgeRequirement = typeof V08IntegrityAlertStatusBridgeRequirementSchema.Type;
export type V08IntegrityAlertStatusBridgeBoundary = typeof V08IntegrityAlertStatusBridgeBoundarySchema.Type;
export type V08IntegrityAlertState = Infer<typeof V08IntegrityAlertStateSchema>;
export type V08IntegrityAlertParentVisibleStatus = Infer<typeof V08IntegrityAlertParentVisibleStatusSchema>;
export type V08IntegrityAlertNotificationIntentState = Infer<typeof V08IntegrityAlertNotificationIntentStateSchema>;
export type V08IntegrityAlertDeliveryState = Infer<typeof V08IntegrityAlertDeliveryStateSchema>;
export type V08IntegrityAlertAuditState = Infer<typeof V08IntegrityAlertAuditStateSchema>;
export type V08IntegrityAlertStatusBridgeEntry = Infer<typeof V08IntegrityAlertStatusBridgeEntrySchema>;
export type V08IntegrityAlertStatusBridgeReadModel = Infer<typeof V08IntegrityAlertStatusBridgeReadModelSchema>;
export declare const V08IntegrityAlertStatusBridgeReadModel: {
    readonly entries: readonly {
        readonly schemaVersion: "v0.6";
        readonly bridgeEntryId: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeEntryId">;
        readonly integrityAlertState: "permission-loss" | "stale-heartbeat" | "stopped-or-removed" | "tamper-manual-required";
        readonly parentVisibleStatus: "permission-action-required" | "agent-heartbeat-stale" | "agent-stopped-or-removed" | "tamper-review-required";
        readonly notificationIntentState: "intent-created" | "manual-review-required";
        readonly deliveryState: "not-delivered-provider-not-configured";
        readonly auditState: "audit-ref-backed" | "manual-required";
        readonly reasonCodeRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
        readonly statusRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
        readonly notificationIntentRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly notificationStatusRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly integrityRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly drillInRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeRequirement">)[];
        readonly boundary: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeBoundary">;
        readonly providerDeliveryClaimed: boolean;
        readonly broadBlockingClaimed: boolean;
        readonly tamperResistanceClaimed: boolean;
        readonly mobileEnforcementClaimed: boolean;
        readonly stealthPersistenceClaimed: boolean;
        readonly privilegeEscalationClaimed: boolean;
        readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    }[];
    readonly schemaVersion: "v0.6";
    readonly readModelId: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReadModelId">;
    readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
};
export declare const decodeV08IntegrityAlertStatusBridgeEntry: (u: unknown, overrideOptions?: import("effect/SchemaAST").ParseOptions) => {
    readonly schemaVersion: "v0.6";
    readonly bridgeEntryId: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeEntryId">;
    readonly integrityAlertState: "permission-loss" | "stale-heartbeat" | "stopped-or-removed" | "tamper-manual-required";
    readonly parentVisibleStatus: "permission-action-required" | "agent-heartbeat-stale" | "agent-stopped-or-removed" | "tamper-review-required";
    readonly notificationIntentState: "intent-created" | "manual-review-required";
    readonly deliveryState: "not-delivered-provider-not-configured";
    readonly auditState: "audit-ref-backed" | "manual-required";
    readonly reasonCodeRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
    readonly statusRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
    readonly notificationIntentRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
    readonly notificationStatusRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
    readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
    readonly integrityRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
    readonly drillInRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
    readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeRequirement">)[];
    readonly boundary: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeBoundary">;
    readonly providerDeliveryClaimed: boolean;
    readonly broadBlockingClaimed: boolean;
    readonly tamperResistanceClaimed: boolean;
    readonly mobileEnforcementClaimed: boolean;
    readonly stealthPersistenceClaimed: boolean;
    readonly privilegeEscalationClaimed: boolean;
    readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
};
export declare const decodeV08IntegrityAlertStatusBridgeReadModel: (u: unknown, overrideOptions?: import("effect/SchemaAST").ParseOptions) => {
    readonly entries: readonly {
        readonly schemaVersion: "v0.6";
        readonly bridgeEntryId: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeEntryId">;
        readonly integrityAlertState: "permission-loss" | "stale-heartbeat" | "stopped-or-removed" | "tamper-manual-required";
        readonly parentVisibleStatus: "permission-action-required" | "agent-heartbeat-stale" | "agent-stopped-or-removed" | "tamper-review-required";
        readonly notificationIntentState: "intent-created" | "manual-review-required";
        readonly deliveryState: "not-delivered-provider-not-configured";
        readonly auditState: "audit-ref-backed" | "manual-required";
        readonly reasonCodeRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
        readonly statusRef: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">;
        readonly notificationIntentRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly notificationStatusRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly auditRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly integrityRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly drillInRefs: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
        readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeRequirement">)[];
        readonly boundary: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeBoundary">;
        readonly providerDeliveryClaimed: boolean;
        readonly broadBlockingClaimed: boolean;
        readonly tamperResistanceClaimed: boolean;
        readonly mobileEnforcementClaimed: boolean;
        readonly stealthPersistenceClaimed: boolean;
        readonly privilegeEscalationClaimed: boolean;
        readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    }[];
    readonly schemaVersion: "v0.6";
    readonly readModelId: string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReadModelId">;
    readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08IntegrityAlertStatusBridgeReference">)[];
};
//# sourceMappingURL=v0-8-integrity-alert-status-bridge.d.ts.map