import { type Infer, Schema } from '@ocentra-parent/schema-domain/effect';
import { V08IntegrityAlertStatusBridgeReadModel as ImportedV08IntegrityAlertStatusBridgeReadModel, V08IntegrityAlertStatusBridgeReadModelSchema, decodeV08IntegrityAlertStatusBridgeReadModel } from './v0-8-integrity-alert-status-bridge';
import type { V08IntegrityAlertStatusBridgeReadModel as V08IntegrityAlertStatusBridgeReadModelType } from './v0-8-integrity-alert-status-bridge';
import { V08NotificationProviderStatusBoundaryReadModel as ImportedV08NotificationProviderStatusBoundaryReadModel, V08NotificationProviderStatusBoundaryReadModelSchema, decodeV08NotificationProviderStatusBoundaryReadModel } from '@ocentra-parent/notification-domain/v0-8-notification-provider-status-boundary';
import type { V08NotificationProviderStatusBoundaryReadModel as V08NotificationProviderStatusBoundaryReadModelType } from '@ocentra-parent/notification-domain/v0-8-notification-provider-status-boundary';
import { V08EnforcementIntegrityRuntimeAuditReadModel as ImportedV08EnforcementIntegrityRuntimeAuditReadModel, V08EnforcementIntegrityRuntimeAuditReadModelSchema, decodeV08EnforcementIntegrityRuntimeAuditReadModel } from './v0-8-enforcement-integrity-runtime-audit';
import type { V08EnforcementIntegrityRuntimeAuditReadModel as V08EnforcementIntegrityRuntimeAuditReadModelType } from './v0-8-enforcement-integrity-runtime-audit';
export { V08IntegrityAlertStatusBridgeReadModelSchema, decodeV08IntegrityAlertStatusBridgeReadModel, V08NotificationProviderStatusBoundaryReadModelSchema, decodeV08NotificationProviderStatusBoundaryReadModel, V08EnforcementIntegrityRuntimeAuditReadModelSchema, decodeV08EnforcementIntegrityRuntimeAuditReadModel };
export declare const V08IntegrityAlertStatusBridgeReadModel: typeof ImportedV08IntegrityAlertStatusBridgeReadModel;
export type V08IntegrityAlertStatusBridgeReadModel = V08IntegrityAlertStatusBridgeReadModelType;
export declare const V08NotificationProviderStatusBoundaryReadModel: typeof ImportedV08NotificationProviderStatusBoundaryReadModel;
export type V08NotificationProviderStatusBoundaryReadModel = V08NotificationProviderStatusBoundaryReadModelType;
export declare const V08EnforcementIntegrityRuntimeAuditReadModel: typeof ImportedV08EnforcementIntegrityRuntimeAuditReadModel;
export type V08EnforcementIntegrityRuntimeAuditReadModel = V08EnforcementIntegrityRuntimeAuditReadModelType;
export declare const V08SupportedAdapterRuntimeProofReadModelIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReadModelId">;
export declare const V08SupportedAdapterRuntimeProofEntryIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofEntryId">;
export declare const V08SupportedAdapterRuntimeProofReferenceSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReference">;
export declare const V08SupportedAdapterRuntimeProofRequirementSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofRequirement">;
export declare const V08SupportedAdapterRuntimeProofBoundarySchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofBoundary">;
export declare const V08SupportedAdapterRuntimeProofFallbackSchema: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofFallback">;
export declare const V08SupportedAdapterRuntimeBoundarySchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["windows-app-game-owned-process-time-limit", "windows-network-flow-observe-policy-handoff", "windows-broad-installed-app-blocking-manual-gate", "windows-host-network-domain-blocking-manual-gate", "windows-broad-installed-app-artifact-status", "windows-host-network-domain-artifact-status", "windows-managed-browser-artifact-status", "windows-managed-exact-active-tab-not-claimed", "windows-adapter-permission-dependency-degraded", "linux-host-adapter-unavailable", "macos-host-adapter-unsupported", "android-mobile-control-manual-gate", "ios-mobile-control-manual-gate"]>>;
export declare const V08SupportedAdapterCapabilitySchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["app-game-owned-process-time-limit", "network-flow-observe-policy-handoff", "broad-installed-app-blocking", "host-network-domain-blocking", "broad-installed-app-artifact-status", "host-network-domain-artifact-status", "managed-browser-artifact-status", "managed-exact-active-tab-enforcement", "adapter-permission-dependency", "desktop-host-platform-adapter", "mobile-child-control-adapter"]>>;
export declare const V08SupportedAdapterRuntimeStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["implemented-boundary", "manual-required", "unavailable", "not-claimed", "unsupported", "degraded"]>>;
export declare const V08SupportedAdapterResultSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["supported-boundary-proved", "manual-proof-required", "target-unavailable", "not-claimed", "unsupported-platform", "degraded-permission-or-dependency"]>>;
export declare const V08SupportedAdapterPlatformSupportStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["supported-on-windows", "manual-required", "unavailable-on-target", "unsupported-platform", "degraded"]>>;
export declare const V08SupportedAdapterTargetIdentityStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["process-session-evidence-backed", "network-flow-evidence-backed", "insufficient-for-broad-target", "not-applicable", "unsupported-platform-target"]>>;
export declare const V08SupportedAdapterRollbackReferenceStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["timer-recovery-backed", "observe-only-not-needed", "manual-required", "unavailable", "not-claimed"]>>;
export declare const V08SupportedAdapterAuditReferenceStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-reference-backed", "manual-required", "unavailable", "not-claimed"]>>;
export declare const V08SupportedAdapterRefusalReasonSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["none", "manual-artifact-required", "target-unavailable", "not-claimed-boundary", "unsupported-platform", "permission-or-dependency-degraded"]>>;
export declare const V08SupportedAdapterRuntimeProofEntrySchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
    schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
    proofEntryId: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofEntryId">;
    runtimeBoundary: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["windows-app-game-owned-process-time-limit", "windows-network-flow-observe-policy-handoff", "windows-broad-installed-app-blocking-manual-gate", "windows-host-network-domain-blocking-manual-gate", "windows-broad-installed-app-artifact-status", "windows-host-network-domain-artifact-status", "windows-managed-browser-artifact-status", "windows-managed-exact-active-tab-not-claimed", "windows-adapter-permission-dependency-degraded", "linux-host-adapter-unavailable", "macos-host-adapter-unsupported", "android-mobile-control-manual-gate", "ios-mobile-control-manual-gate"]>>;
    platform: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["windows", "linux", "macos", "android", "ios"]>>;
    adapterCapability: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["app-game-owned-process-time-limit", "network-flow-observe-policy-handoff", "broad-installed-app-blocking", "host-network-domain-blocking", "broad-installed-app-artifact-status", "host-network-domain-artifact-status", "managed-browser-artifact-status", "managed-exact-active-tab-enforcement", "adapter-permission-dependency", "desktop-host-platform-adapter", "mobile-child-control-adapter"]>>;
    runtimeState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["implemented-boundary", "manual-required", "unavailable", "not-claimed", "unsupported", "degraded"]>>;
    adapterResult: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["supported-boundary-proved", "manual-proof-required", "target-unavailable", "not-claimed", "unsupported-platform", "degraded-permission-or-dependency"]>>;
    platformSupportState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["supported-on-windows", "manual-required", "unavailable-on-target", "unsupported-platform", "degraded"]>>;
    targetIdentityState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["process-session-evidence-backed", "network-flow-evidence-backed", "insufficient-for-broad-target", "not-applicable", "unsupported-platform-target"]>>;
    rollbackReferenceState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["timer-recovery-backed", "observe-only-not-needed", "manual-required", "unavailable", "not-claimed"]>>;
    auditReferenceState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-reference-backed", "manual-required", "unavailable", "not-claimed"]>>;
    refusalReason: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["none", "manual-artifact-required", "target-unavailable", "not-claimed-boundary", "unsupported-platform", "permission-or-dependency-degraded"]>>;
    evidenceRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReference">>;
    linkedProofCommands: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReference">>;
    linkedProofArtifacts: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReference">>;
    manualProofRequirements: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofRequirement">>;
    claimBoundary: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofBoundary">;
    fallbackBehavior: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofFallback">;
    broadInstalledAppBlockingClaimed: typeof Schema.Boolean;
    networkDomainBlockingClaimed: typeof Schema.Boolean;
    exactActiveTabEnforcementClaimed: typeof Schema.Boolean;
    notificationDeliveryClaimed: typeof Schema.Boolean;
    tamperHardeningClaimed: typeof Schema.Boolean;
    mobileControlClaimed: typeof Schema.Boolean;
    unsupportedPlatformBehaviorClaimed: typeof Schema.Boolean;
    lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
}>>>;
export declare const V08SupportedAdapterRuntimeProofReadModelSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
    schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
    readModelId: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReadModelId">;
    generatedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
    sourceReadModelIds: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReference">>;
    entries: Schema.Array$<import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
        schemaVersion: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["v0.6"]>>;
        proofEntryId: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofEntryId">;
        runtimeBoundary: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["windows-app-game-owned-process-time-limit", "windows-network-flow-observe-policy-handoff", "windows-broad-installed-app-blocking-manual-gate", "windows-host-network-domain-blocking-manual-gate", "windows-broad-installed-app-artifact-status", "windows-host-network-domain-artifact-status", "windows-managed-browser-artifact-status", "windows-managed-exact-active-tab-not-claimed", "windows-adapter-permission-dependency-degraded", "linux-host-adapter-unavailable", "macos-host-adapter-unsupported", "android-mobile-control-manual-gate", "ios-mobile-control-manual-gate"]>>;
        platform: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["windows", "linux", "macos", "android", "ios"]>>;
        adapterCapability: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["app-game-owned-process-time-limit", "network-flow-observe-policy-handoff", "broad-installed-app-blocking", "host-network-domain-blocking", "broad-installed-app-artifact-status", "host-network-domain-artifact-status", "managed-browser-artifact-status", "managed-exact-active-tab-enforcement", "adapter-permission-dependency", "desktop-host-platform-adapter", "mobile-child-control-adapter"]>>;
        runtimeState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["implemented-boundary", "manual-required", "unavailable", "not-claimed", "unsupported", "degraded"]>>;
        adapterResult: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["supported-boundary-proved", "manual-proof-required", "target-unavailable", "not-claimed", "unsupported-platform", "degraded-permission-or-dependency"]>>;
        platformSupportState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["supported-on-windows", "manual-required", "unavailable-on-target", "unsupported-platform", "degraded"]>>;
        targetIdentityState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["process-session-evidence-backed", "network-flow-evidence-backed", "insufficient-for-broad-target", "not-applicable", "unsupported-platform-target"]>>;
        rollbackReferenceState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["timer-recovery-backed", "observe-only-not-needed", "manual-required", "unavailable", "not-claimed"]>>;
        auditReferenceState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["audit-reference-backed", "manual-required", "unavailable", "not-claimed"]>>;
        refusalReason: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["none", "manual-artifact-required", "target-unavailable", "not-claimed-boundary", "unsupported-platform", "permission-or-dependency-degraded"]>>;
        evidenceRefs: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReference">>;
        linkedProofCommands: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReference">>;
        linkedProofArtifacts: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofReference">>;
        manualProofRequirements: Schema.Array$<Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofRequirement">>;
        claimBoundary: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofBoundary">;
        fallbackBehavior: Schema.brand<Schema.filter<typeof Schema.String>, "V08SupportedAdapterRuntimeProofFallback">;
        broadInstalledAppBlockingClaimed: typeof Schema.Boolean;
        networkDomainBlockingClaimed: typeof Schema.Boolean;
        exactActiveTabEnforcementClaimed: typeof Schema.Boolean;
        notificationDeliveryClaimed: typeof Schema.Boolean;
        tamperHardeningClaimed: typeof Schema.Boolean;
        mobileControlClaimed: typeof Schema.Boolean;
        unsupportedPlatformBehaviorClaimed: typeof Schema.Boolean;
        lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "ParentTimestamp">;
    }>>>>;
}>>>;
export type V08SupportedAdapterRuntimeProofReadModelId = typeof V08SupportedAdapterRuntimeProofReadModelIdSchema.Type;
export type V08SupportedAdapterRuntimeProofEntryId = typeof V08SupportedAdapterRuntimeProofEntryIdSchema.Type;
export type V08SupportedAdapterRuntimeProofReference = typeof V08SupportedAdapterRuntimeProofReferenceSchema.Type;
export type V08SupportedAdapterRuntimeProofRequirement = typeof V08SupportedAdapterRuntimeProofRequirementSchema.Type;
export type V08SupportedAdapterRuntimeProofBoundary = typeof V08SupportedAdapterRuntimeProofBoundarySchema.Type;
export type V08SupportedAdapterRuntimeProofFallback = typeof V08SupportedAdapterRuntimeProofFallbackSchema.Type;
export type V08SupportedAdapterRuntimeBoundary = Infer<typeof V08SupportedAdapterRuntimeBoundarySchema>;
export type V08SupportedAdapterCapability = Infer<typeof V08SupportedAdapterCapabilitySchema>;
export type V08SupportedAdapterRuntimeState = Infer<typeof V08SupportedAdapterRuntimeStateSchema>;
export type V08SupportedAdapterResult = Infer<typeof V08SupportedAdapterResultSchema>;
export type V08SupportedAdapterPlatformSupportState = Infer<typeof V08SupportedAdapterPlatformSupportStateSchema>;
export type V08SupportedAdapterTargetIdentityState = Infer<typeof V08SupportedAdapterTargetIdentityStateSchema>;
export type V08SupportedAdapterRollbackReferenceState = Infer<typeof V08SupportedAdapterRollbackReferenceStateSchema>;
export type V08SupportedAdapterAuditReferenceState = Infer<typeof V08SupportedAdapterAuditReferenceStateSchema>;
export type V08SupportedAdapterRefusalReason = Infer<typeof V08SupportedAdapterRefusalReasonSchema>;
export type V08SupportedAdapterRuntimeProofEntry = Infer<typeof V08SupportedAdapterRuntimeProofEntrySchema>;
export type V08SupportedAdapterRuntimeProofReadModel = Infer<typeof V08SupportedAdapterRuntimeProofReadModelSchema>;
export declare const V08SupportedAdapterRuntimeBoundary: {
    readonly WindowsAppGameOwnedProcessTimeLimit: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly WindowsNetworkFlowObservePolicyHandoff: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly WindowsBroadInstalledAppBlockingManualGate: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly WindowsHostNetworkDomainBlockingManualGate: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly WindowsBroadInstalledAppArtifactStatus: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly WindowsHostNetworkDomainArtifactStatus: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly WindowsManagedBrowserArtifactStatus: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly WindowsManagedExactActiveTabNotClaimed: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly WindowsAdapterPermissionDependencyDegraded: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly LinuxHostAdapterUnavailable: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly MacosHostAdapterUnsupported: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly AndroidMobileControlManualGate: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly IosMobileControlManualGate: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
};
export declare const V08SupportedAdapterRuntimeProofReadModel: {
    readonly entries: readonly {
        readonly schemaVersion: "v0.6";
        readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofRequirement">)[];
        readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        readonly proofEntryId: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofEntryId">;
        readonly runtimeBoundary: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
        readonly platform: "windows" | "linux" | "macos" | "android" | "ios";
        readonly adapterCapability: "app-game-owned-process-time-limit" | "network-flow-observe-policy-handoff" | "broad-installed-app-blocking" | "host-network-domain-blocking" | "broad-installed-app-artifact-status" | "host-network-domain-artifact-status" | "managed-browser-artifact-status" | "managed-exact-active-tab-enforcement" | "adapter-permission-dependency" | "desktop-host-platform-adapter" | "mobile-child-control-adapter";
        readonly runtimeState: "manual-required" | "implemented-boundary" | "unavailable" | "not-claimed" | "unsupported" | "degraded";
        readonly adapterResult: "not-claimed" | "supported-boundary-proved" | "manual-proof-required" | "target-unavailable" | "unsupported-platform" | "degraded-permission-or-dependency";
        readonly platformSupportState: "manual-required" | "degraded" | "unsupported-platform" | "supported-on-windows" | "unavailable-on-target";
        readonly targetIdentityState: "process-session-evidence-backed" | "network-flow-evidence-backed" | "insufficient-for-broad-target" | "not-applicable" | "unsupported-platform-target";
        readonly rollbackReferenceState: "manual-required" | "unavailable" | "not-claimed" | "timer-recovery-backed" | "observe-only-not-needed";
        readonly auditReferenceState: "manual-required" | "unavailable" | "not-claimed" | "audit-reference-backed";
        readonly refusalReason: "target-unavailable" | "unsupported-platform" | "none" | "manual-artifact-required" | "not-claimed-boundary" | "permission-or-dependency-degraded";
        readonly evidenceRefs: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
        readonly linkedProofCommands: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
        readonly linkedProofArtifacts: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
        readonly claimBoundary: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofBoundary">;
        readonly fallbackBehavior: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofFallback">;
        readonly broadInstalledAppBlockingClaimed: boolean;
        readonly networkDomainBlockingClaimed: boolean;
        readonly exactActiveTabEnforcementClaimed: boolean;
        readonly notificationDeliveryClaimed: boolean;
        readonly tamperHardeningClaimed: boolean;
        readonly mobileControlClaimed: boolean;
        readonly unsupportedPlatformBehaviorClaimed: boolean;
    }[];
    readonly schemaVersion: "v0.6";
    readonly readModelId: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReadModelId">;
    readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
};
export declare const decodeV08SupportedAdapterRuntimeProofEntry: (u: unknown, overrideOptions?: import("effect/SchemaAST").ParseOptions) => {
    readonly schemaVersion: "v0.6";
    readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofRequirement">)[];
    readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    readonly proofEntryId: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofEntryId">;
    readonly runtimeBoundary: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
    readonly platform: "windows" | "linux" | "macos" | "android" | "ios";
    readonly adapterCapability: "app-game-owned-process-time-limit" | "network-flow-observe-policy-handoff" | "broad-installed-app-blocking" | "host-network-domain-blocking" | "broad-installed-app-artifact-status" | "host-network-domain-artifact-status" | "managed-browser-artifact-status" | "managed-exact-active-tab-enforcement" | "adapter-permission-dependency" | "desktop-host-platform-adapter" | "mobile-child-control-adapter";
    readonly runtimeState: "manual-required" | "implemented-boundary" | "unavailable" | "not-claimed" | "unsupported" | "degraded";
    readonly adapterResult: "not-claimed" | "supported-boundary-proved" | "manual-proof-required" | "target-unavailable" | "unsupported-platform" | "degraded-permission-or-dependency";
    readonly platformSupportState: "manual-required" | "degraded" | "unsupported-platform" | "supported-on-windows" | "unavailable-on-target";
    readonly targetIdentityState: "process-session-evidence-backed" | "network-flow-evidence-backed" | "insufficient-for-broad-target" | "not-applicable" | "unsupported-platform-target";
    readonly rollbackReferenceState: "manual-required" | "unavailable" | "not-claimed" | "timer-recovery-backed" | "observe-only-not-needed";
    readonly auditReferenceState: "manual-required" | "unavailable" | "not-claimed" | "audit-reference-backed";
    readonly refusalReason: "target-unavailable" | "unsupported-platform" | "none" | "manual-artifact-required" | "not-claimed-boundary" | "permission-or-dependency-degraded";
    readonly evidenceRefs: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
    readonly linkedProofCommands: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
    readonly linkedProofArtifacts: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
    readonly claimBoundary: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofBoundary">;
    readonly fallbackBehavior: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofFallback">;
    readonly broadInstalledAppBlockingClaimed: boolean;
    readonly networkDomainBlockingClaimed: boolean;
    readonly exactActiveTabEnforcementClaimed: boolean;
    readonly notificationDeliveryClaimed: boolean;
    readonly tamperHardeningClaimed: boolean;
    readonly mobileControlClaimed: boolean;
    readonly unsupportedPlatformBehaviorClaimed: boolean;
};
export declare const decodeV08SupportedAdapterRuntimeProofReadModel: (u: unknown, overrideOptions?: import("effect/SchemaAST").ParseOptions) => {
    readonly entries: readonly {
        readonly schemaVersion: "v0.6";
        readonly manualProofRequirements: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofRequirement">)[];
        readonly lastCheckedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
        readonly proofEntryId: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofEntryId">;
        readonly runtimeBoundary: "windows-app-game-owned-process-time-limit" | "windows-network-flow-observe-policy-handoff" | "windows-broad-installed-app-blocking-manual-gate" | "windows-host-network-domain-blocking-manual-gate" | "windows-broad-installed-app-artifact-status" | "windows-host-network-domain-artifact-status" | "windows-managed-browser-artifact-status" | "windows-managed-exact-active-tab-not-claimed" | "windows-adapter-permission-dependency-degraded" | "linux-host-adapter-unavailable" | "macos-host-adapter-unsupported" | "android-mobile-control-manual-gate" | "ios-mobile-control-manual-gate";
        readonly platform: "windows" | "linux" | "macos" | "android" | "ios";
        readonly adapterCapability: "app-game-owned-process-time-limit" | "network-flow-observe-policy-handoff" | "broad-installed-app-blocking" | "host-network-domain-blocking" | "broad-installed-app-artifact-status" | "host-network-domain-artifact-status" | "managed-browser-artifact-status" | "managed-exact-active-tab-enforcement" | "adapter-permission-dependency" | "desktop-host-platform-adapter" | "mobile-child-control-adapter";
        readonly runtimeState: "manual-required" | "implemented-boundary" | "unavailable" | "not-claimed" | "unsupported" | "degraded";
        readonly adapterResult: "not-claimed" | "supported-boundary-proved" | "manual-proof-required" | "target-unavailable" | "unsupported-platform" | "degraded-permission-or-dependency";
        readonly platformSupportState: "manual-required" | "degraded" | "unsupported-platform" | "supported-on-windows" | "unavailable-on-target";
        readonly targetIdentityState: "process-session-evidence-backed" | "network-flow-evidence-backed" | "insufficient-for-broad-target" | "not-applicable" | "unsupported-platform-target";
        readonly rollbackReferenceState: "manual-required" | "unavailable" | "not-claimed" | "timer-recovery-backed" | "observe-only-not-needed";
        readonly auditReferenceState: "manual-required" | "unavailable" | "not-claimed" | "audit-reference-backed";
        readonly refusalReason: "target-unavailable" | "unsupported-platform" | "none" | "manual-artifact-required" | "not-claimed-boundary" | "permission-or-dependency-degraded";
        readonly evidenceRefs: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
        readonly linkedProofCommands: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
        readonly linkedProofArtifacts: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
        readonly claimBoundary: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofBoundary">;
        readonly fallbackBehavior: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofFallback">;
        readonly broadInstalledAppBlockingClaimed: boolean;
        readonly networkDomainBlockingClaimed: boolean;
        readonly exactActiveTabEnforcementClaimed: boolean;
        readonly notificationDeliveryClaimed: boolean;
        readonly tamperHardeningClaimed: boolean;
        readonly mobileControlClaimed: boolean;
        readonly unsupportedPlatformBehaviorClaimed: boolean;
    }[];
    readonly schemaVersion: "v0.6";
    readonly readModelId: string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReadModelId">;
    readonly generatedAt: string & import("effect/Brand").Brand<"ParentTimestamp">;
    readonly sourceReadModelIds: readonly (string & import("effect/Brand").Brand<"V08SupportedAdapterRuntimeProofReference">)[];
};
//# sourceMappingURL=v0-8-supported-adapter-runtime-proof.d.ts.map
