import { type Infer, Schema } from '@ocentra-parent/schema-domain/effect';
export declare const LocalAiContextNonNegativeCountSchema: Schema.filter<Schema.filter<typeof Schema.Number>>;
export declare const LocalAiEvidenceContextIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiEvidenceContextId">;
export declare const LocalAiEvidenceContextRefIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiEvidenceContextRefId">;
export declare const LocalAiParentRuleContextRefIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiParentRuleContextRefId">;
export declare const LocalAiEvidenceSourceIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiEvidenceSourceId">;
export declare const LocalAiEvidenceAdapterIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiEvidenceAdapterId">;
export declare const LocalAiEvidenceContextSummarySchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiEvidenceContextSummary">;
export declare const LocalAiRejectedFieldSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiRejectedField">;
export declare const LocalAiRequestedEvaluationKindSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["page", "url", "video", "app", "game", "domain", "network-digest", "screen-summary", "recent-activity", "mixed-context"]>>;
export declare const LocalAiEvidenceContextKindSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["browser", "app-game", "network-flow", "screen-summary", "policy-decision", "parent-action", "recent-activity"]>>;
export declare const LocalAiEvidenceCustodySchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["live-local-child-agent", "live-lan-child-agent", "child-device-journal", "child-device-query-store", "parent-device-cache", "parent-owned-export", "ocentra-hosted-non-activity", "unavailable"]>>;
export declare const LocalAiEvidenceRetentionStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["local", "temporary", "deleted-source", "export-copy", "parent-owned-copy", "unavailable"]>>;
export declare const LocalAiConfidenceKindSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["observation", "correlation", "classifier", "model", "memory-match", "graph-edge", "rule-match"]>>;
export declare const LocalAiContextCapabilityStatusSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["available", "unsupported", "permission-limited", "stale", "degraded", "adapter-error", "disabled-by-parent", "unavailable"]>>;
export declare const LocalAiContextReasonCodeSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["missing-evidence", "stale-evidence", "source-conflict", "unsupported-source", "permission-limited", "adapter-error", "capability-disabled-by-parent", "custody-unavailable", "forbidden-remote-source", "invalid-confidence", "invalid-ai-output", "model-unavailable", "model-overloaded", "model-output-unparseable", "memory-ungrounded", "graph-ungrounded", "parent-rule-missing", "parent-rule-conflict", "schedule-unresolved", "protected-surface", "screen-image-deleted", "screen-deletion-unconfirmed", "network-encrypted-content-unavailable", "browser-active-tab-unknown", "app-duration-incomplete"]>>;
export declare const LocalAiContextBuildStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["ready", "partial", "insufficient", "unavailable", "rejected"]>>;
export type LocalAiEvidenceContextId = typeof LocalAiEvidenceContextIdSchema.Type;
export type LocalAiEvidenceContextRefId = typeof LocalAiEvidenceContextRefIdSchema.Type;
export type LocalAiParentRuleContextRefId = typeof LocalAiParentRuleContextRefIdSchema.Type;
export type LocalAiEvidenceSourceId = typeof LocalAiEvidenceSourceIdSchema.Type;
export type LocalAiEvidenceAdapterId = typeof LocalAiEvidenceAdapterIdSchema.Type;
export type LocalAiEvidenceContextSummary = typeof LocalAiEvidenceContextSummarySchema.Type;
export type LocalAiRejectedField = typeof LocalAiRejectedFieldSchema.Type;
export type LocalAiRequestedEvaluationKind = Infer<typeof LocalAiRequestedEvaluationKindSchema>;
export type LocalAiEvidenceContextKind = Infer<typeof LocalAiEvidenceContextKindSchema>;
export type LocalAiEvidenceCustody = Infer<typeof LocalAiEvidenceCustodySchema>;
export type LocalAiEvidenceRetentionState = Infer<typeof LocalAiEvidenceRetentionStateSchema>;
export type LocalAiConfidenceKind = Infer<typeof LocalAiConfidenceKindSchema>;
export type LocalAiContextCapabilityStatus = Infer<typeof LocalAiContextCapabilityStatusSchema>;
export type LocalAiContextReasonCode = Infer<typeof LocalAiContextReasonCodeSchema>;
export type LocalAiContextBuildState = Infer<typeof LocalAiContextBuildStateSchema>;
//# sourceMappingURL=context-primitives.d.ts.map