import { type Infer, Schema } from '@ocentra-parent/schema-domain/effect';
export * from './local-ai-model-artifacts';
export declare const LocalAiProviderPrivacyModeSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["local-only"]>>;
export declare const LocalAiAdapterBoundarySchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["status-only", "local-adapter-unavailable", "local-adapter-ready"]>>;
export declare const LocalAiExecutionStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["disabled", "dry-run-ready", "running", "failed"]>>;
export declare const LocalAiProviderSourceSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["unavailable", "local-config", "local-model-cache", "os-capability-probe"]>>;
export declare const LocalAiAdapterProbeStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["probe-unavailable", "probe-ready", "probe-failed"]>>;
export declare const LocalAiProviderConfigurationStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["local-provider-unconfigured", "local-provider-configured", "local-provider-config-invalid"]>>;
export declare const LocalAiAdapterReadinessStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["adapter-not-ready", "adapter-ready", "adapter-readiness-invalid"]>>;
export declare const LocalModelRuntimeStatusSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Struct<{
    runtimeReferenceId: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiRuntimeReferenceId">;
    providerId: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiProviderId">;
    modelId: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiModelId">;
    modelReference: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiModelReference">;
    privacyMode: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["local-only"]>>;
    adapterBoundary: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["status-only", "local-adapter-unavailable", "local-adapter-ready"]>>;
    executionState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["disabled", "dry-run-ready", "running", "failed"]>>;
    providerSource: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["unavailable", "local-config", "local-model-cache", "os-capability-probe"]>>;
    loadState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["unavailable", "loading", "loaded", "degraded", "failed"]>>;
    capabilityFlags: Schema.Array$<import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["classification", "summarization", "embedding", "safety-decision", "chat-completion"]>>>;
    resourceClass: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["cpu", "gpu", "npu", "remote-unavailable"]>>;
    degradedState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["none", "provider-unavailable", "model-load-failed", "overloaded", "invalid-output"]>>;
    lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "AiTimestamp">;
    unavailableReason: Schema.Union<[Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiUnavailableReason">, typeof Schema.Null]>;
}>>;
export declare const LocalProviderAdapterProbeSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.filter<Schema.Struct<{
    providerId: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiProviderId">;
    privacyMode: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["local-only"]>>;
    adapterBoundary: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["status-only", "local-adapter-unavailable", "local-adapter-ready"]>>;
    executionState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["disabled", "dry-run-ready", "running", "failed"]>>;
    providerSource: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["unavailable", "local-config", "local-model-cache", "os-capability-probe"]>>;
    probeState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["probe-unavailable", "probe-ready", "probe-failed"]>>;
    configurationState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["local-provider-unconfigured", "local-provider-configured", "local-provider-config-invalid"]>>;
    readinessState: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["adapter-not-ready", "adapter-ready", "adapter-readiness-invalid"]>>;
    executionAllowed: typeof Schema.Boolean;
    lastCheckedAt: Schema.brand<Schema.filter<typeof Schema.String>, "AiTimestamp">;
    unavailableReason: Schema.Union<[Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiUnavailableReason">, typeof Schema.Null]>;
}>>>;
export declare const LocalProviderCapabilitySchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Struct<{
    providerId: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiProviderId">;
    supportedTasks: Schema.Array$<import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["classification", "summarization", "embedding", "safety-decision", "chat-completion"]>>>;
    resourceClass: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["cpu", "gpu", "npu", "remote-unavailable"]>>;
    privacyMode: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["local-only"]>>;
    fallbackOrder: typeof Schema.Number;
}>>;
export declare const LocalAiModelRequestMetadataSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Struct<{
    providerId: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiProviderId">;
    modelId: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiModelId">;
    promptVersion: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiPromptVersion">;
}>>;
export type LocalModelRuntimeStatus = Infer<typeof LocalModelRuntimeStatusSchema>;
export type LocalProviderAdapterProbe = Infer<typeof LocalProviderAdapterProbeSchema>;
export type LocalProviderCapability = Infer<typeof LocalProviderCapabilitySchema>;
export type LocalAiModelRequestMetadata = Infer<typeof LocalAiModelRequestMetadataSchema>;
export type LocalAiProviderPrivacyMode = Infer<typeof LocalAiProviderPrivacyModeSchema>;
export type LocalAiAdapterBoundary = Infer<typeof LocalAiAdapterBoundarySchema>;
export type LocalAiExecutionState = Infer<typeof LocalAiExecutionStateSchema>;
export type LocalAiProviderSource = Infer<typeof LocalAiProviderSourceSchema>;
export type LocalAiAdapterProbeState = Infer<typeof LocalAiAdapterProbeStateSchema>;
export type LocalAiProviderConfigurationState = Infer<typeof LocalAiProviderConfigurationStateSchema>;
export type LocalAiAdapterReadinessState = Infer<typeof LocalAiAdapterReadinessStateSchema>;
//# sourceMappingURL=local-ai-runtime.d.ts.map