import { type Infer, Schema } from '@ocentra-parent/schema-domain/effect';
export declare const LocalAiEvaluationRequestIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiEvaluationRequestId">;
export declare const LocalAiResultIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiResultId">;
export declare const LocalAiPromptVersionSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiPromptVersion">;
export declare const LocalAiModelIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiModelId">;
export declare const LocalAiProviderIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiProviderId">;
export declare const LocalAiModelReferenceSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiModelReference">;
export declare const LocalAiExplanationReferenceSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiExplanationReference">;
export declare const LocalAiMemoryReferenceIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiMemoryReferenceId">;
export declare const LocalAiGraphReferenceIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiGraphReferenceId">;
export declare const LocalAiRuntimeReferenceIdSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiRuntimeReferenceId">;
export declare const LocalAiTimestampSchema: Schema.brand<Schema.filter<typeof Schema.String>, "AiTimestamp">;
export declare const LocalAiDerivedIndexVersionSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiDerivedIndexVersion">;
export declare const LocalAiUnavailableReasonSchema: Schema.brand<Schema.filter<typeof Schema.String>, "LocalAiUnavailableReason">;
export declare const LocalAiConfidenceSchema: Schema.filter<typeof Schema.Number>;
export declare const LocalAiContextKindSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["app", "process", "window", "url", "page", "video", "domain", "network", "recent-activity"]>>;
export declare const LocalAiModelLoadStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["unavailable", "loading", "loaded", "degraded", "failed"]>>;
export declare const LocalAiCapabilityFlagSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["classification", "summarization", "embedding", "safety-decision", "chat-completion"]>>;
export declare const LocalAiResourceClassSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["cpu", "gpu", "npu", "remote-unavailable"]>>;
export declare const LocalAiDegradedStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["none", "provider-unavailable", "model-load-failed", "overloaded", "invalid-output"]>>;
export declare const LocalAiUnknownStateSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["none", "missing-evidence", "low-confidence", "model-unavailable", "policy-conflict"]>>;
export declare const LocalAiMemoryReferenceKindSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["evidence-memory", "recent-activity", "policy-memory", "semantic-memory"]>>;
export declare const LocalAiGraphReferenceKindSchema: import("@ocentra-parent/schema-domain/effect").ParsedSchema<Schema.Literal<["graph-entity", "graph-edge"]>>;
export type LocalAiEvaluationRequestId = typeof LocalAiEvaluationRequestIdSchema.Type;
export type LocalAiResultId = typeof LocalAiResultIdSchema.Type;
export type LocalAiPromptVersion = typeof LocalAiPromptVersionSchema.Type;
export type LocalAiModelId = typeof LocalAiModelIdSchema.Type;
export type LocalAiProviderId = typeof LocalAiProviderIdSchema.Type;
export type LocalAiModelReference = typeof LocalAiModelReferenceSchema.Type;
export type LocalAiExplanationReference = typeof LocalAiExplanationReferenceSchema.Type;
export type LocalAiMemoryReferenceId = typeof LocalAiMemoryReferenceIdSchema.Type;
export type LocalAiGraphReferenceId = typeof LocalAiGraphReferenceIdSchema.Type;
export type LocalAiRuntimeReferenceId = typeof LocalAiRuntimeReferenceIdSchema.Type;
export type LocalAiConfidence = typeof LocalAiConfidenceSchema.Type;
export type LocalAiContextKind = Infer<typeof LocalAiContextKindSchema>;
export type LocalAiModelLoadState = Infer<typeof LocalAiModelLoadStateSchema>;
export type LocalAiCapabilityFlag = Infer<typeof LocalAiCapabilityFlagSchema>;
export type LocalAiResourceClass = Infer<typeof LocalAiResourceClassSchema>;
export type LocalAiDegradedState = Infer<typeof LocalAiDegradedStateSchema>;
export type LocalAiUnknownState = Infer<typeof LocalAiUnknownStateSchema>;
export type LocalAiMemoryReferenceKind = Infer<typeof LocalAiMemoryReferenceKindSchema>;
export type LocalAiGraphReferenceKind = Infer<typeof LocalAiGraphReferenceKindSchema>;
export declare const LocalAiDegradedState: {
    readonly None: "none" | "provider-unavailable" | "model-load-failed" | "overloaded" | "invalid-output";
    readonly ProviderUnavailable: "none" | "provider-unavailable" | "model-load-failed" | "overloaded" | "invalid-output";
    readonly ModelLoadFailed: "none" | "provider-unavailable" | "model-load-failed" | "overloaded" | "invalid-output";
    readonly Overloaded: "none" | "provider-unavailable" | "model-load-failed" | "overloaded" | "invalid-output";
    readonly InvalidOutput: "none" | "provider-unavailable" | "model-load-failed" | "overloaded" | "invalid-output";
};
export declare const LocalAiUnknownState: {
    readonly None: "none" | "missing-evidence" | "low-confidence" | "model-unavailable" | "policy-conflict";
    readonly MissingEvidence: "none" | "missing-evidence" | "low-confidence" | "model-unavailable" | "policy-conflict";
    readonly LowConfidence: "none" | "missing-evidence" | "low-confidence" | "model-unavailable" | "policy-conflict";
    readonly ModelUnavailable: "none" | "missing-evidence" | "low-confidence" | "model-unavailable" | "policy-conflict";
    readonly PolicyConflict: "none" | "missing-evidence" | "low-confidence" | "model-unavailable" | "policy-conflict";
};
//# sourceMappingURL=primitives.d.ts.map