import type { AppControlGuideCatalogSettingSeed } from '@ocentra-parent/schema-domain/app-control-catalog-data';

// Generated from docs/app-control-capability-guide.md. Tests parse the source doc and prove parity.
export const AppControlGuideCatalogData3: readonly AppControlGuideCatalogSettingSeed[] = [
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-004',
    193,
    524,
    'Running and foreground sessionization.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-005',
    194,
    525,
    'Owned-process launch and termination.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-006',
    195,
    526,
    'Narrow target process termination after typed policy decisions.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-007',
    196,
    527,
    'Broad app control through AppLocker, WDAC/App Control for Business, managed installer policy, or equivalent only after explicit host proof.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-008',
    197,
    529,
    'Package lifecycle actions through installer/package mechanisms where product setup owns the package.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-009',
    198,
    534,
    'AppLocker/WDAC behavior depends on Windows edition, policy deployment, signing, administrator rights, audit/enforce mode, and reboot or refresh behavior.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-010',
    199,
    536,
    'Microsoft Store package identity and Win32 executable identity are different evidence families.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-011',
    200,
    538,
    'Blocking by path alone can be bypassed by copy/rename unless hash, signer, or managed installer proof is used.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-012',
    201,
    540,
    'The current roadmap distinguishes owned-process terminate and app time-limit proof from broad app blocking. Do not claim broad blocking until the adapter is proven.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-001',
    202,
    551,
    'Application bundle inventory.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-002',
    203,
    552,
    'Running process and window/frontmost app observation with the required permissions.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-003',
    204,
    554,
    'Launch Services, bundle identifiers, code signing, and app metadata.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-004',
    205,
    555,
    'MDM managed app distribution and restrictions where enrolled.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-005',
    206,
    556,
    'System Extensions, Endpoint Security, or Network Extension paths where entitled and deployed.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-006',
    207,
    558,
    'Managed browser/app controls through configuration profiles where supported.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-007',
    208,
    562,
    'Accessibility, Screen Recording, Full Disk Access, Endpoint Security, Network Extension, and MDM posture change what is possible.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-008',
    209,
    564,
    'Some controls require supervised or managed devices.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-macos',
    'macOS',
    2,
    'app-guide-platform-capability-notes-macos-009',
    210,
    565,
    'Do not assume Windows process control maps directly to macOS.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-001',
    211,
    575,
    'Desktop entries and menu categories.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-002',
    212,
    576,
    'Package manager inventory.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-003',
    213,
    577,
    'Flatpak, Snap, AppImage, or custom install metadata.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-004',
    214,
    578,
    'Process observation through OS process tables.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-005',
    215,
    579,
    'Foreground-window observation through X11, Wayland compositor protocols, or desktop-specific APIs where available.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-006',
    216,
    581,
    'Process termination where permission permits.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-007',
    217,
    582,
    'Policy controls through service, user session, package, desktop, firewall, or container mechanisms where proven.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-008',
    218,
    587,
    'Wayland commonly restricts global window inspection compared with X11.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-009',
    219,
    588,
    'Desktop entry category metadata is useful but not a complete app ontology.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-010',
    220,
    589,
    'Package managers differ by distro.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-linux',
    'Linux',
    3,
    'app-guide-platform-capability-notes-linux-011',
    221,
    590,
    'Broad app blocking should be treated as manual-required until a concrete adapter is proven on the target distro and desktop.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-001',
    222,
    600,
    'Package inventory through PackageManager subject to package visibility rules.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-002',
    223,
    601,
    'Usage events/statistics when the user grants Usage Access or the app has the required privileged context.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-003',
    224,
    603,
    'Foreground visibility through UsageStatsManager or Accessibility where approved and enabled.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-004',
    225,
    605,
    'DevicePolicyManager package hiding, suspension, permission policy, managed configuration, and package lifecycle control for device owner/profile owner contexts.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-005',
    226,
    608,
    'Managed Play or MDM package installation/removal where deployed.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-006',
    227,
    609,
    'Always-on VPN with lockdown for network mediation, separate from app foreground proof.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-007',
    228,
    614,
    'A normal Android app cannot generally control all other apps.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-008',
    229,
    615,
    'Package visibility rules can hide installed apps from inventory queries.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-009',
    230,
    616,
    'Usage access is permission-gated and can be revoked.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-010',
    231,
    617,
    'Accessibility is sensitive and must not be used as a stealth content capture path.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-011',
    232,
    619,
    'Device owner/profile owner changes the capability class and setup burden.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-android',
    'Android',
    4,
    'app-guide-platform-capability-notes-android-012',
    233,
    620,
    'The roadmap currently treats Android package lifecycle proof as manual-required until real device artifacts exist.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-001',
    234,
    629,
    'Screen Time frameworks: Family Controls, Managed Settings, Device Activity.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-002',
    235,
    630,
    'Opaque selections for applications, categories, and web domains.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-003',
    236,
    631,
    'App/category shielding through Managed Settings.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-004',
    237,
    632,
    'Threshold/event monitoring through Device Activity.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-005',
    238,
    633,
    'MDM managed app install/removal and restrictions for enrolled devices.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-006',
    239,
    634,
    'Supervised-device restrictions where applicable.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-007',
    240,
    638,
    'Third-party apps do not get a general raw list of every installed app for parental control.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-008',
    241,
    640,
    'Screen Time APIs are privacy-preserving and token-based; tokens can be voided if authorization is revoked.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-009',
    242,
    642,
    'App shielding is not the same as process termination or raw app telemetry.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-010',
    243,
    643,
    'MDM and supervision determine app install/removal and restriction scope.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-011',
    244,
    644,
    'Family Controls entitlements, App Store review, TestFlight, and runtime authorization are separate proof requirements.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-ios-and-ipados',
    'iOS And iPadOS',
    5,
    'app-guide-platform-capability-notes-ios-and-ipados-012',
    245,
    646,
    'The roadmap separates iOS signing/entitlements from TestFlight and runtime API entitlements; do not claim iOS control until each is proven.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-001',
    246,
    658,
    'Detect installed or launchable apps where available.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-002',
    247,
    659,
    'Show running and foreground state.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-003',
    248,
    660,
    'Build running and foreground session durations.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-004',
    249,
    661,
    'Show unknown, unsupported, stale, and permission-limited states.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-005',
    250,
    662,
    'Produce reports without changing device behavior.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-006',
    251,
    666,
    'App blocking.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-007',
    252,
    667,
    'Mobile device-owner/supervised setup.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-008',
    253,
    668,
    'Broad application control.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-009',
    254,
    672,
    'Guaranteed launch blocking.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-010',
    255,
    673,
    'Install/uninstall control.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use',
    'Observe App Use',
    1,
    'app-guide-policy-modes-to-represent-later-in-ui-observe-app-use-011',
    256,
    674,
    'App-internal content knowledge.',
  ],
];
