import type { AppControlGuideCatalogSettingSeed } from '@ocentra-parent/schema-domain/app-control-catalog-data';

// Generated from docs/app-control-capability-guide.md. Tests parse the source doc and prove parity.
export const AppControlGuideCatalogData4: readonly AppControlGuideCatalogSettingSeed[] = [
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use',
    'Warn Or Ask On App Use',
    2,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use-001',
    257,
    680,
    'Matching app activity remains allowed temporarily.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use',
    'Warn Or Ask On App Use',
    2,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use-002',
    258,
    681,
    'The child sees a warning or ask-parent state.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use',
    'Warn Or Ask On App Use',
    2,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use-003',
    259,
    682,
    'The parent sees the app/session evidence and can approve, deny, or extend.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use',
    'Warn Or Ask On App Use',
    2,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use-004',
    260,
    686,
    'App/session evidence.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use',
    'Warn Or Ask On App Use',
    2,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use-005',
    261,
    687,
    'Child-facing local UI or notification/shield path.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use',
    'Warn Or Ask On App Use',
    2,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use-006',
    262,
    688,
    'Parent approval contract.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use',
    'Warn Or Ask On App Use',
    2,
    'app-guide-policy-modes-to-represent-later-in-ui-warn-or-ask-on-app-use-007',
    263,
    689,
    'Expiry and audit.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps',
    'Time-Limit Apps',
    3,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps-001',
    264,
    695,
    'Running or foreground time is counted against a parent budget.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps',
    'Time-Limit Apps',
    3,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps-002',
    265,
    696,
    'Warning and grace rules apply.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps',
    'Time-Limit Apps',
    3,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps-003',
    266,
    697,
    'When the budget expires, the configured action runs if the adapter supports it.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps',
    'Time-Limit Apps',
    3,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps-004',
    267,
    702,
    'Sessionization from stored evidence.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps',
    'Time-Limit Apps',
    3,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps-005',
    268,
    703,
    'Timer recovery after restart.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps',
    'Time-Limit Apps',
    3,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps-006',
    269,
    704,
    'Policy decision and enforcement audit.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps',
    'Time-Limit Apps',
    3,
    'app-guide-policy-modes-to-represent-later-in-ui-time-limit-apps-007',
    270,
    705,
    'Fallback when enforcement is unavailable.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-001',
    271,
    711,
    'Parent rules prevent or interrupt app access.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-002',
    272,
    712,
    'On desktop this may mean launch block or process termination.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-003',
    273,
    713,
    'On mobile this may mean shield/hide/suspend through approved platform APIs.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-004',
    274,
    717,
    'Platform-specific control proof.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-005',
    275,
    718,
    'Parent exceptions.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-006',
    276,
    719,
    'Rollback path.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-007',
    277,
    720,
    'Audit for every strict action.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-008',
    278,
    724,
    'App deletion.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-009',
    279,
    725,
    'Exact in-app activity knowledge.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps',
    'Block Or Shield Apps',
    4,
    'app-guide-policy-modes-to-represent-later-in-ui-block-or-shield-apps-010',
    280,
    726,
    'Parity across platforms.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle',
    'Managed App Lifecycle',
    5,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle-001',
    281,
    732,
    'Install, update, uninstall, hide, or remove managed apps through a platform management boundary.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle',
    'Managed App Lifecycle',
    5,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle-002',
    282,
    737,
    'Managed-device or package-management setup.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle',
    'Managed App Lifecycle',
    5,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle-003',
    283,
    738,
    'Signing/store/MDM or installer proof.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle',
    'Managed App Lifecycle',
    5,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle-004',
    284,
    739,
    'Custody model for personal vs managed apps.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle',
    'Managed App Lifecycle',
    5,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle-005',
    285,
    740,
    'Explicit parent-visible state and audit.',
  ],
  [
    'app-guide-policy-modes-to-represent-later-in-ui',
    'Policy Modes To Represent Later In UI',
    10,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle',
    'Managed App Lifecycle',
    5,
    'app-guide-policy-modes-to-represent-later-in-ui-managed-app-lifecycle-006',
    286,
    744,
    'Personal device and family device expectations differ. The product should not imply corporate MDM behavior unless the device is actually managed that way.',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-001',
    287,
    751,
    'App/game evidence contracts use stored local evidence and query/read models.',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-002',
    288,
    752,
    'Process/window evidence can support native app sessions, running time, and foreground time.',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-003',
    289,
    754,
    'Local AI can consume evidence references or structured digests; it does not scan the OS.',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-004',
    290,
    756,
    'Policy decisions must reference evidence and remain deterministic.',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-005',
    291,
    757,
    'V0.8 enforcement work has typed contracts, capability status, timer/recovery, and audit scaffolding.',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-006',
    292,
    759,
    'Windows has proof direction for owned-process terminate and app time-limit behavior, but broad app blocking remains manual-required until a real adapter proves it.',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-007',
    293,
    762,
    'Android package lifecycle and iOS Screen Time/entitlement behavior are manual-required until real device/platform proof exists.',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-008',
    294,
    764,
    'Parent portal is an authoring and visibility surface. It does not run app inventory, timers, policy evaluation, or enforcement.',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-009',
    295,
    769,
    '[`docs/architecture/app-game-evidence-sessions.md`](architecture/app-game-evidence-sessions.md)',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-010',
    296,
    770,
    '[`docs/expectations/app-game-evidence.md`](expectations/app-game-evidence.md)',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-011',
    297,
    771,
    '[`docs/expectations/policy.md`](expectations/policy.md)',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-012',
    298,
    772,
    '[`docs/expectations/enforcement.md`](expectations/enforcement.md)',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-013',
    299,
    773,
    '[`docs/product-roadmap.md`](product-roadmap.md)',
  ],
  [
    'app-guide-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    11,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture',
    'Current Ocentra Parent Posture',
    1,
    'app-guide-current-ocentra-parent-posture-current-ocentra-parent-posture-014',
    300,
    774,
    '[`docs/managed-unmanaged-browser.md`](managed-unmanaged-browser.md)',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-001',
    301,
    780,
    'Show inventory, running, foreground, time-limit, install, uninstall, shield, suspend, block, and terminate as separate capability rows.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-002',
    302,
    782,
    'Show the evidence source next to every app claim.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-003',
    303,
    783,
    'Show exact package/process identity only when proof exists and retention allows it.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-004',
    304,
    785,
    'Show unknown apps as unknown, not as risky by default.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-005',
    305,
    786,
    'Show app category as a label with source/confidence, not as an automatic decision.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-006',
    306,
    788,
    'Show app time limits only when duration evidence exists or when the rule is clearly marked as pending proof.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-007',
    307,
    790,
    'Show strict actions as ready, unsupported, permission-required, manual-required, degraded, dry-run-only, adapter-error, or blocked-by-setup.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-008',
    308,
    792,
    'Keep managed-device setup state close to mobile actions.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-009',
    309,
    793,
    'Keep child-facing messages separate from parent diagnostics.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-010',
    310,
    794,
    'Every strict action should have an audit path: evidence, parent rule, compiled policy, adapter mechanism, outcome, timestamp, and rollback/unavailable state.',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-011',
    311,
    799,
    'observe only;',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-012',
    312,
    800,
    'warn on app use;',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-013',
    313,
    801,
    'ask parent on app use;',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-014',
    314,
    802,
    'set app/category/unknown-app time budgets;',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-015',
    315,
    803,
    'close or terminate selected apps after a timer;',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-016',
    316,
    804,
    'shield, suspend, or block apps where the platform supports it;',
  ],
  [
    'app-guide-future-ui-rules',
    'Future UI Rules',
    12,
    'app-guide-future-ui-rules-future-ui-rules',
    'Future UI Rules',
    1,
    'app-guide-future-ui-rules-future-ui-rules-017',
    317,
    805,
    'manage app installs/uninstalls only inside a platform-approved custody model.',
  ],
];
