import type { AppControlGuideCatalogSettingSeed } from '@ocentra-parent/schema-domain/app-control-catalog-data';

// Generated from docs/app-control-capability-guide.md. Tests parse the source doc and prove parity.
export const AppControlGuideCatalogData2: readonly AppControlGuideCatalogSettingSeed[] = [
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-005',
    129,
    368,
    'Parent approval or extension state.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-006',
    130,
    369,
    'Enforcement fallback for unsupported action.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-007',
    131,
    370,
    'Audit event for warning, timeout, action, failure, extension, and rollback.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-008',
    132,
    374,
    'A timer without action is report-only.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-009',
    133,
    375,
    'Foreground time and running time should be separate settings.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-010',
    134,
    376,
    'Cross-device time budgets need sync/custody rules.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-011',
    135,
    377,
    'Mobile time-limit enforcement depends on platform-specific APIs.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-001',
    136,
    386,
    'Windows MSI/MSIX/package manager or managed installer.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-002',
    137,
    387,
    'macOS installer/package/MDM managed app or declarative package management.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-003',
    138,
    388,
    'Linux package manager, Flatpak, Snap, AppImage-managed wrapper, or desktop entry.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-004',
    139,
    390,
    'Android package installer, device owner/profile owner, managed Play, or MDM.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-005',
    140,
    391,
    'iOS/iPadOS MDM managed app distribution and managed app removal.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-006',
    141,
    395,
    'Ocentra must not remove personal apps unless a platform-approved managed path and parent/child custody model explicitly allow it.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-007',
    142,
    397,
    'Store policies, signing, entitlements, user consent, device enrollment, and uninstall rights vary sharply.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall',
    'Install And Uninstall',
    5,
    'app-guide-app-control-what-is-possible-install-and-uninstall-008',
    143,
    399,
    'Install/uninstall actions must be audited separately from normal app observation.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-001',
    144,
    408,
    'Known identity from package/bundle/app token.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-002',
    145,
    409,
    'Known policy source.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-003',
    146,
    410,
    'Install or update provenance.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-004',
    147,
    411,
    'Known allowed/blocked/shielded state.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps',
    'Managed Apps',
    1,
    'app-guide-managed-unmanaged-and-unknown-apps-managed-apps-005',
    148,
    412,
    'Stronger app lifecycle action where the platform supports it.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-001',
    149,
    421,
    'Running and foreground observation.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-002',
    150,
    422,
    'Session duration.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-003',
    151,
    423,
    'Category candidate.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-004',
    152,
    424,
    'Ask-parent or warning events.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-005',
    153,
    425,
    'Terminate where allowed.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps',
    'Unmanaged Apps',
    2,
    'app-guide-managed-unmanaged-and-unknown-apps-unmanaged-apps-006',
    154,
    426,
    'Report-only unknown or bypass state.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-001',
    155,
    435,
    'Observe only.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-002',
    156,
    436,
    'Ask parent on first run.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-003',
    157,
    437,
    'Warn child.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-004',
    158,
    438,
    'Count time under unknown-app budget.',
  ],
  [
    'app-guide-managed-unmanaged-and-unknown-apps',
    'Managed, Unmanaged, And Unknown Apps',
    6,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps',
    'Unknown Apps',
    3,
    'app-guide-managed-unmanaged-and-unknown-apps-unknown-apps-005',
    159,
    439,
    'Block or terminate only when the parent selected that posture and the platform adapter can prove the action.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-001',
    160,
    450,
    'Warn before time limit.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-002',
    161,
    451,
    'Show time remaining.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-003',
    162,
    452,
    'Show that parent approval is needed.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-004',
    163,
    453,
    'Show whether an app is paused, shielded, blocked, or closed by parent policy.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-005',
    164,
    454,
    'Offer ask-parent, request more time, or use allowed alternative where policy supports it.',
  ],
  [
    'app-guide-child-facing-actions',
    'Child-Facing Actions',
    7,
    'app-guide-child-facing-actions-child-facing-actions',
    'Child-Facing Actions',
    1,
    'app-guide-child-facing-actions-child-facing-actions-006',
    165,
    456,
    'Hide parent diagnostics, evidence ids, adapter errors, hashes, and internal policy fields from the child surface.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-001',
    166,
    475,
    'Installed/detectable app inventory.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-002',
    167,
    476,
    'Running now.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-003',
    168,
    477,
    'Foreground now.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-004',
    169,
    478,
    'Recent sessions.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-005',
    170,
    479,
    'Daily app/category rollups.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-006',
    171,
    480,
    'Time budgets and remaining time.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-007',
    172,
    481,
    'Unknown and permission-limited apps.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-008',
    173,
    482,
    'Policy decisions.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-009',
    174,
    483,
    'Enforcement actions and failures.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-010',
    175,
    484,
    'Approval requests and parent responses.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-011',
    176,
    488,
    'Evidence ids.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-012',
    177,
    489,
    'Source adapter.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-013',
    178,
    490,
    'Capability state.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-014',
    179,
    491,
    'Custody label.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-015',
    180,
    492,
    'Collection scope.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-016',
    181,
    493,
    'Retention policy.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-017',
    182,
    494,
    'Redaction status.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-018',
    183,
    495,
    'Policy version and decision id when policy contributed.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-019',
    184,
    496,
    'Adapter result id when enforcement contributed.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-020',
    185,
    500,
    'Raw process/window evidence should be retained for the shortest useful local audit window.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-021',
    186,
    502,
    'Daily rollups can be retained longer than raw observations if they are redacted.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-022',
    187,
    504,
    'Exact executable paths and window titles may be sensitive and should have narrower retention and reveal controls.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-023',
    188,
    506,
    'Ocentra-hosted storage is not the default child-activity store.',
  ],
  [
    'app-guide-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    8,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit',
    'Reports, Custody, Retention, And Audit',
    1,
    'app-guide-reports-custody-retention-and-audit-reports-custody-retention-and-audit-024',
    189,
    507,
    'Parent export and deletion must preserve audit integrity while respecting retention settings.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-001',
    190,
    519,
    'Installed-app inventory from uninstall records, Start Menu shortcuts, Microsoft Store packages, known install paths, package query APIs, and executable metadata.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-002',
    191,
    522,
    'Process enumeration and process metadata.',
  ],
  [
    'app-guide-platform-capability-notes',
    'Platform Capability Notes',
    9,
    'app-guide-platform-capability-notes-windows',
    'Windows',
    1,
    'app-guide-platform-capability-notes-windows-003',
    192,
    523,
    'Foreground-window observation.',
  ],
];
