import { AppGamePerformanceHealthMatrixSchema } from './app-game-performance-health';

const evidence = (evidenceReferenceId: string, observedAt: string) => ({
  evidenceReferenceId,
  kind: 'query-store-summary',
  observedAt,
});

const proofPackRefs = [
  'output/app-game-plan-proof/27-performance-and-service-health',
  'output/app-plan-proof/26-performance-and-service-health',
];

const commonNoClaimBoundaries = [
  'fixture-scale-not-live-load-test',
  'no-platform-adapter-execution',
  'not-product-complete-performance-claim',
] as const;

const AppGamePerformanceHealthProofMatrixCandidate = {
  schemaVersion: 'v0.6',
  matrixId: 'app-game-performance-health-proof',
  generatedAt: '2026-06-03T12:38:00.000Z',
  rows: [
    {
      schemaVersion: 'app-game-performance-health-proof',
      healthCheckId: 'inventory-scan-1000-budget',
      productSlice: 'shared-app-game',
      surface: 'inventory-scan-bounds',
      measurementMode: 'generated-scale-smoke',
      minimumEntityCount: 1000,
      warningThresholdMs: 750,
      budgetMs: 1500,
      serviceHealthState: 'healthy',
      capabilityState: 'observe-only',
      degradedTriggers: [],
      evidenceReferences: [evidence('evidence:inventory-scale-fixture-1000', '2026-06-03T12:30:00.000Z')],
      parentVisibleState: 'Large inventory proof stays evidence-only and cannot be displayed as app or game use.',
      noClaimBoundaries: [...commonNoClaimBoundaries, 'inventory-is-not-use', 'raw-private-paths-not-exposed'],
      proofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      livePlatformClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:30:00.000Z',
    },
    {
      schemaVersion: 'app-game-performance-health-proof',
      healthCheckId: 'runtime-polling-500-budget',
      productSlice: 'shared-app-game',
      surface: 'runtime-polling-bounds',
      measurementMode: 'generated-scale-smoke',
      minimumEntityCount: 500,
      warningThresholdMs: 500,
      budgetMs: 1000,
      serviceHealthState: 'healthy',
      capabilityState: 'observe-only',
      degradedTriggers: [],
      evidenceReferences: [evidence('evidence:runtime-scale-fixture-500', '2026-06-03T12:31:00.000Z')],
      parentVisibleState: 'Runtime snapshot scale proof remains running-state evidence and not foreground proof.',
      noClaimBoundaries: [...commonNoClaimBoundaries, 'runtime-is-not-foreground', 'raw-private-paths-not-exposed'],
      proofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      livePlatformClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:31:00.000Z',
    },
    {
      schemaVersion: 'app-game-performance-health-proof',
      healthCheckId: 'foreground-debounce-500-budget',
      productSlice: 'shared-app-game',
      surface: 'foreground-debounce-bounds',
      measurementMode: 'generated-scale-smoke',
      minimumEntityCount: 500,
      warningThresholdMs: 400,
      budgetMs: 900,
      serviceHealthState: 'healthy',
      capabilityState: 'observe-only',
      degradedTriggers: [],
      evidenceReferences: [evidence('evidence:foreground-scale-fixture-500', '2026-06-03T12:32:00.000Z')],
      parentVisibleState: 'Foreground debounce proof keeps focus separate from app or game content knowledge.',
      noClaimBoundaries: [...commonNoClaimBoundaries, 'foreground-is-not-content'],
      proofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      livePlatformClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:32:00.000Z',
    },
    {
      schemaVersion: 'app-game-performance-health-proof',
      healthCheckId: 'journal-write-10000-budget',
      productSlice: 'shared-app-game',
      surface: 'journal-write-volume',
      measurementMode: 'generated-scale-smoke',
      minimumEntityCount: 10000,
      warningThresholdMs: 1200,
      budgetMs: 2500,
      serviceHealthState: 'healthy',
      capabilityState: 'observe-only',
      degradedTriggers: [],
      evidenceReferences: [evidence('evidence:journal-scale-fixture-10000', '2026-06-03T12:33:00.000Z')],
      parentVisibleState:
        'Journal write-volume proof is generated fixture scale, not live encrypted storage throughput.',
      noClaimBoundaries: [...commonNoClaimBoundaries, 'raw-private-paths-not-exposed'],
      proofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      livePlatformClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:33:00.000Z',
    },
    {
      schemaVersion: 'app-game-performance-health-proof',
      healthCheckId: 'session-replay-100000-budget',
      productSlice: 'shared-app-game',
      surface: 'session-replay-cost',
      measurementMode: 'generated-scale-smoke',
      minimumEntityCount: 100000,
      warningThresholdMs: 2500,
      budgetMs: 5000,
      serviceHealthState: 'healthy',
      capabilityState: 'observe-only',
      degradedTriggers: [],
      evidenceReferences: [evidence('evidence:session-replay-fixture-100000', '2026-06-03T12:34:00.000Z')],
      parentVisibleState: 'Replay scale proof preserves deterministic session duration and stale-gap boundaries.',
      noClaimBoundaries: [...commonNoClaimBoundaries, 'runtime-is-not-foreground', 'foreground-is-not-content'],
      proofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      livePlatformClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:34:00.000Z',
    },
    {
      schemaVersion: 'app-game-performance-health-proof',
      healthCheckId: 'policy-compile-1000-budget',
      productSlice: 'shared-app-game',
      surface: 'policy-compile-cost',
      measurementMode: 'generated-scale-smoke',
      minimumEntityCount: 1000,
      warningThresholdMs: 1500,
      budgetMs: 3000,
      serviceHealthState: 'healthy',
      capabilityState: 'dry-run',
      degradedTriggers: [],
      evidenceReferences: [evidence('evidence:policy-compile-fixture-1000', '2026-06-03T12:35:00.000Z')],
      parentVisibleState: 'Policy compile scale proof remains dry-run and does not dispatch adapters.',
      noClaimBoundaries: [...commonNoClaimBoundaries, 'manual-required-cannot-execute'],
      proofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      livePlatformClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:35:00.000Z',
    },
    {
      schemaVersion: 'app-game-performance-health-proof',
      healthCheckId: 'portal-intent-500-row-budget',
      productSlice: 'shared-app-game',
      surface: 'portal-render-bounds',
      measurementMode: 'existing-portal-intent-smoke',
      minimumEntityCount: 500,
      warningThresholdMs: 1000,
      budgetMs: 2500,
      serviceHealthState: 'healthy',
      capabilityState: 'observe-only',
      degradedTriggers: [],
      evidenceReferences: [evidence('evidence:portal-intent-fixture-500', '2026-06-03T12:36:00.000Z')],
      parentVisibleState: 'Existing app/game dashboard intent can summarize 500 service rows without new portal edits.',
      noClaimBoundaries: [
        ...commonNoClaimBoundaries,
        'portal-intent-not-browser-dom-render-proof',
        'inventory-is-not-use',
        'runtime-is-not-foreground',
        'foreground-is-not-content',
        'launcher-is-not-game',
      ],
      proofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      livePlatformClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:36:00.000Z',
    },
    {
      schemaVersion: 'app-game-performance-health-proof',
      healthCheckId: 'adapter-health-degraded-visible-state',
      productSlice: 'shared-app-game',
      surface: 'adapter-health-degraded-state',
      measurementMode: 'degraded-state-contract',
      minimumEntityCount: 1,
      warningThresholdMs: 1,
      budgetMs: 1,
      serviceHealthState: 'degraded',
      capabilityState: 'degraded',
      degradedTriggers: ['adapter-error', 'stale-evidence', 'live-source-not-claimed'],
      evidenceReferences: [evidence('evidence:adapter-degraded-visible-state', '2026-06-03T12:37:00.000Z')],
      parentVisibleState: 'Adapter error and stale evidence must remain parent-visible degraded states.',
      noClaimBoundaries: [...commonNoClaimBoundaries, 'manual-required-cannot-execute'],
      proofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      livePlatformClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:37:00.000Z',
    },
  ],
} as const;

export const AppGamePerformanceHealthProofMatrix = AppGamePerformanceHealthMatrixSchema.parse(
  AppGamePerformanceHealthProofMatrixCandidate
);
