import type { AppControlGuideCatalogSettingSeed } from '@ocentra-parent/schema-domain/app-control-catalog-data';

// Generated from docs/app-control-capability-guide.md. Tests parse the source doc and prove parity.
export const AppControlGuideCatalogData1: readonly AppControlGuideCatalogSettingSeed[] = [
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-008',
    65,
    216,
    'It can miss portable apps, per-user installs, wrapped apps, web apps, and apps hidden by platform privacy.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-009',
    66,
    218,
    'It can report apps that are installed but never used.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-010',
    67,
    219,
    'Mobile app lists can be package-visibility-limited, tokenized, supervised-only, or MDM-only.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory',
    'Installed App Inventory',
    1,
    'app-guide-app-evidence-what-is-possible-installed-app-inventory-011',
    68,
    221,
    'Inventory should never be used as proof of activity without runtime evidence.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-001',
    69,
    227,
    'Process id, parent process id, executable path, process name, command-line handling status, user/session reference, and launch time where available.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-002',
    70,
    229,
    'Publisher/signature/hash metadata where safe.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-003',
    71,
    230,
    'Window id, title, active/foreground state, minimized/background state, and last foreground timestamp where available.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-004',
    72,
    232,
    'Sessionization into running and foreground durations.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-005',
    73,
    233,
    'Unknown, permission-limited, stale, unsupported, and adapter-error states.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-006',
    74,
    237,
    'Process names can be renamed.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-007',
    75,
    238,
    'Helper processes may not represent user-facing apps.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-008',
    76,
    239,
    'Foreground window title may contain sensitive text and may be stale or misleading.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-009',
    77,
    241,
    'Foreground proof does not reveal what happened inside the app.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-010',
    78,
    242,
    'Background process duration is not the same as child attention.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence',
    'Process And Window Evidence',
    2,
    'app-guide-app-evidence-what-is-possible-process-and-window-evidence-011',
    79,
    243,
    'Elevated, protected, sandboxed, or cross-user processes can be unreadable or uncontrollable.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration',
    'Foreground Use And Duration',
    3,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration-001',
    80,
    250,
    'Which app is active now?',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration',
    'Foreground Use And Duration',
    3,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration-002',
    81,
    251,
    'How long was this app in foreground today?',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration',
    'Foreground Use And Duration',
    3,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration-003',
    82,
    252,
    'Did the time budget run out?',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration',
    'Foreground Use And Duration',
    3,
    'app-guide-app-evidence-what-is-possible-foreground-use-and-duration-004',
    83,
    253,
    'Which evidence ids prove the count?',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-001',
    84,
    269,
    'Education.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-002',
    85,
    270,
    'Productivity.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-003',
    86,
    271,
    'Communication.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-004',
    87,
    272,
    'Entertainment.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-005',
    88,
    273,
    'Social.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-006',
    89,
    274,
    'Browser.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-007',
    90,
    275,
    'Game.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-008',
    91,
    276,
    'Creative.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-009',
    92,
    277,
    'System.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-010',
    93,
    278,
    'Unknown.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-011',
    94,
    285,
    'Category is not content.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-012',
    95,
    286,
    'Category confidence must be recorded.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-013',
    96,
    287,
    'Parent rules decide actions. Category labels alone should not block.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-014',
    97,
    288,
    'Some platforms expose categories as opaque tokens rather than raw identifiers.',
  ],
  [
    'app-guide-app-evidence-what-is-possible',
    'App Evidence: What Is Possible',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories',
    'App Categories',
    4,
    'app-guide-app-evidence-what-is-possible-app-categories-015',
    98,
    289,
    'Unknown or ambiguous categories should degrade to observe, ask, or parent review according to explicit policy.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-001',
    99,
    301,
    'Open an approved app.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-002',
    100,
    302,
    'Relaunch a blocked/closed app later after a time budget resets.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-003',
    101,
    303,
    'Open an app as part of an ask-parent approval.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-004',
    102,
    304,
    'Prefer a managed app path or managed browser path for certain tasks.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-005',
    103,
    308,
    'Launching an app does not guarantee it stays foreground.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-006',
    104,
    309,
    'Launching an unmanaged app can move outside Ocentra control.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-launch',
    'Launch',
    1,
    'app-guide-app-control-what-is-possible-launch-007',
    105,
    310,
    'Mobile launch behavior depends on platform foreground and intent rules.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-001',
    106,
    316,
    'Stop an app after a block or time-limit decision.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-002',
    107,
    317,
    'Stop an owned child process.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-003',
    108,
    318,
    'Stop a target process when identity still matches the policy target.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-004',
    109,
    319,
    'Record already-exited, target-changed, permission-limited, failed, or succeeded results.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-005',
    110,
    324,
    'Termination can lose unsaved work.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-006',
    111,
    325,
    'Target processes can exit and relaunch between detection and action.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-007',
    112,
    326,
    'Parent/child UX should support grace periods, warnings, and ask-parent flows.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-008',
    113,
    327,
    'Some platforms do not allow third-party apps to kill other apps.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-terminate',
    'Terminate',
    2,
    'app-guide-app-control-what-is-possible-terminate-009',
    114,
    328,
    'Protected, elevated, system, or different-user processes may be unavailable.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-001',
    115,
    337,
    'Windows application control policy, AppLocker, WDAC/App Control for Business, or a narrower service adapter where proven.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-002',
    116,
    339,
    'macOS MDM profile, system extension, endpoint/security tooling, or managed app restriction where entitled and deployed.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-003',
    117,
    341,
    'Linux policy, desktop/session integration, package-manager restriction, or service-level control where proven.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-004',
    118,
    343,
    'Android DevicePolicyManager package hide/suspend, device owner/profile owner, managed configuration, or accessibility/VPN-adjacent UX where approved.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-005',
    119,
    345,
    'iOS/iPadOS Screen Time Family Controls, Managed Settings shields, Device Activity thresholds, or MDM restrictions where entitled/supervised.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-006',
    120,
    350,
    'Broad app blocking is a privileged OS capability, not a normal UI toggle.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-007',
    121,
    351,
    'Policy setup can require admin rights, device-owner enrollment, MDM, supervision, entitlements, app review, signing, or store distribution.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-008',
    122,
    353,
    'Some systems support shielding/visibility restrictions rather than process termination.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-009',
    123,
    355,
    'Platform APIs may expose opaque identifiers for privacy.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block',
    'Suspend, Hide, Shield, Or Block',
    3,
    'app-guide-app-control-what-is-possible-suspend-hide-shield-or-block-010',
    124,
    356,
    'Rollback and uninstall paths must be documented before strict policies ship.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-001',
    125,
    364,
    'App/session identity.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-002',
    126,
    365,
    'Running or foreground duration proof.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-003',
    127,
    366,
    'Schedule and budget state.',
  ],
  [
    'app-guide-app-control-what-is-possible',
    'App Control: What Is Possible',
    5,
    'app-guide-app-control-what-is-possible-time-limits',
    'Time Limits',
    4,
    'app-guide-app-control-what-is-possible-time-limits-004',
    128,
    367,
    'Warning threshold and grace state.',
  ],
];
