import type { GameControlCatalogSettingSeed } from './game-control-catalog-schema';

export const GameControlCatalogSourceDocuments = [
  'docs/game-control-capability-guide.md',
  'docs/game-control-schema-proposal.md',
] as const;

export const GameControlCatalogSettingSeeds = [
  {
    sectionId: 'game-management',
    sectionTitle: 'Game management',
    sectionPurpose: 'Top-level game policy switch and default posture.',
    sectionOrder: 1,
    groupId: 'game-management',
    groupTitle: 'Game management',
    groupOrder: 1,
    settingId: 'game.enabled',
    settingOrder: 1,
    controlType: 'boolean',
    writesTo: '/gamePolicy/enabled',
    question: 'Enable game management?',
    defaultValue: false,
    options: [],
  },
  {
    sectionId: 'game-management',
    sectionTitle: 'Game management',
    sectionPurpose: 'Top-level game policy switch and default posture.',
    sectionOrder: 1,
    groupId: 'game-management',
    groupTitle: 'Game management',
    groupOrder: 1,
    settingId: 'game.defaultPosture',
    settingOrder: 2,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/defaultPosture',
    question: 'What should happen to game activity?',
    defaultValue: 'observe',
    options: [
      ['allow', 'Allow', 'Game activity is allowed unless a more specific rule changes it.'],
      [
        'observe',
        'Observe',
        'Game activity is allowed, evidence is collected according to data scope, and decisions are report-only.',
      ],
      [
        'warn',
        'Warn',
        'Game activity is allowed, but matching activity warns the child and records parent-visible events.',
      ],
      ['ask', 'Ask', 'Game activity needs parent approval unless an allow rule or override applies.'],
      ['limit', 'Limit', 'Game activity is allowed inside configured schedules and budgets.'],
      [
        'block',
        'Block',
        'Game activity is blocked by default unless an explicit exception or parent override allows it.',
      ],
    ],
  },
  {
    sectionId: 'game-management',
    sectionTitle: 'Game management',
    sectionPurpose: 'Top-level game policy switch and default posture.',
    sectionOrder: 1,
    groupId: 'game-management',
    groupTitle: 'Game management',
    groupOrder: 1,
    settingId: 'game.managementMode',
    settingOrder: 3,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/managementMode',
    question: 'How should game management run on this device?',
    defaultValue: 'local-child-agent',
    options: [
      ['local-child-agent', 'Child device local', null],
      ['lan-live', 'LAN live', null],
      ['platform-family-controls', 'Platform family controls', null],
      ['authoring-only', 'Authoring only', null],
      ['unavailable', 'Unavailable', null],
    ],
  },
  {
    sectionId: 'inventory',
    sectionTitle: 'Game inventory',
    sectionPurpose:
      'Configure which installed/detectable games, launchers, stores, and unknown candidates may be shown or used.',
    sectionOrder: 2,
    groupId: 'inventory',
    groupTitle: 'Game inventory',
    groupOrder: 2,
    settingId: 'inventory.mode',
    settingOrder: 1,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/inventory/mode',
    question: 'Which game inventory should be used?',
    defaultValue: 'local-installed-and-running',
    options: [
      ['off', 'off', null],
      ['running-only', 'running-only', null],
      ['local-installed-and-running', 'local-installed-and-running', null],
      ['launcher-backed', 'launcher-backed', null],
      ['platform-family-controls', 'platform-family-controls', null],
      ['manual-list-only', 'manual-list-only', null],
    ],
  },
  {
    sectionId: 'inventory',
    sectionTitle: 'Game inventory',
    sectionPurpose:
      'Configure which installed/detectable games, launchers, stores, and unknown candidates may be shown or used.',
    sectionOrder: 2,
    groupId: 'inventory',
    groupTitle: 'Game inventory',
    groupOrder: 2,
    settingId: 'inventory.sources',
    settingOrder: 2,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/inventory/sources',
    question: 'Which inventory sources may contribute game evidence?',
    defaultValue: [
      'process-snapshot',
      'foreground-window',
      'installed-app-records',
      'store-packages',
      'launcher-manifests',
    ],
    options: [
      ['process-snapshot', 'process-snapshot', null],
      ['foreground-window', 'foreground-window', null],
      ['installed-app-records', 'installed-app-records', null],
      ['start-menu-shortcuts', 'start-menu-shortcuts', null],
      ['store-packages', 'store-packages', null],
      ['launcher-manifests', 'launcher-manifests', null],
      ['manual-parent-catalog', 'manual-parent-catalog', null],
      ['platform-family-controls', 'platform-family-controls', null],
      ['browser-managed-url', 'browser-managed-url', null],
      ['network-service-hint', 'network-service-hint', null],
    ],
  },
  {
    sectionId: 'inventory',
    sectionTitle: 'Game inventory',
    sectionPurpose:
      'Configure which installed/detectable games, launchers, stores, and unknown candidates may be shown or used.',
    sectionOrder: 2,
    groupId: 'inventory',
    groupTitle: 'Game inventory',
    groupOrder: 2,
    settingId: 'inventory.classificationStates',
    settingOrder: 3,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/inventory/classificationStates',
    question: 'Which game classifications should appear in rules?',
    defaultValue: ['known-game', 'known-launcher', 'launcher-game-candidate', 'possibly-game', 'unknown-process'],
    options: [
      ['known-game', 'known-game', null],
      ['known-app', 'known-app', null],
      ['known-launcher', 'known-launcher', null],
      ['launcher-game-candidate', 'launcher-game-candidate', null],
      ['possibly-game', 'possibly-game', null],
      ['unknown-process', 'unknown-process', null],
      ['permission-limited', 'permission-limited', null],
      ['unsupported-platform', 'unsupported-platform', null],
      ['stale', 'stale', null],
      ['adapter-error', 'adapter-error', null],
    ],
  },
  {
    sectionId: 'inventory',
    sectionTitle: 'Game inventory',
    sectionPurpose:
      'Configure which installed/detectable games, launchers, stores, and unknown candidates may be shown or used.',
    sectionOrder: 2,
    groupId: 'inventory',
    groupTitle: 'Game inventory',
    groupOrder: 2,
    settingId: 'inventory.ratingSources',
    settingOrder: 4,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/inventory/ratingSources',
    question: 'Which rating or category sources may be used?',
    defaultValue: ['store-metadata', 'parent-catalog', 'rating-authority'],
    options: [
      ['store-metadata', 'store-metadata', null],
      ['launcher-metadata', 'launcher-metadata', null],
      ['parent-catalog', 'parent-catalog', null],
      ['rating-authority', 'rating-authority', null],
      ['local-classifier-digest', 'local-classifier-digest', null],
      ['unknown', 'unknown', null],
    ],
  },
  {
    sectionId: 'session-evidence',
    sectionTitle: 'Game session evidence',
    sectionPurpose: 'Choose which proof is enough to count game time or support strict game rules.',
    sectionOrder: 3,
    groupId: 'session-evidence',
    groupTitle: 'Game session evidence',
    groupOrder: 3,
    settingId: 'evidence.requiredProof',
    settingOrder: 1,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/evidence/requiredProof',
    question: 'What proof is enough for game rules?',
    defaultValue: 'foreground-known-game-session',
    options: [
      ['process-running', 'process-running', null],
      ['foreground-window', 'foreground-window', null],
      ['foreground-known-game-session', 'foreground-known-game-session', null],
      ['launcher-attributed-session', 'launcher-attributed-session', null],
      ['package-identity-session', 'package-identity-session', null],
      ['managed-browser-game-url', 'managed-browser-game-url', null],
      ['platform-family-activity', 'platform-family-activity', null],
      ['manual-parent-catalog', 'manual-parent-catalog', null],
    ],
  },
  {
    sectionId: 'session-evidence',
    sectionTitle: 'Game session evidence',
    sectionPurpose: 'Choose which proof is enough to count game time or support strict game rules.',
    sectionOrder: 3,
    groupId: 'session-evidence',
    groupTitle: 'Game session evidence',
    groupOrder: 3,
    settingId: 'evidence.durationCountingMode',
    settingOrder: 2,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/evidence/durationCountingMode',
    question: 'Which time should count toward game budgets?',
    defaultValue: 'foreground-game-time',
    options: [
      ['foreground-game-time', 'foreground-game-time', null],
      ['running-game-process-time', 'running-game-process-time', null],
      ['launcher-child-game-time', 'launcher-child-game-time', null],
      ['known-game-only-time', 'known-game-only-time', null],
      ['known-and-possible-game-time', 'known-and-possible-game-time', null],
      ['browser-managed-game-time', 'browser-managed-game-time', null],
      ['cloud-client-foreground-time', 'cloud-client-foreground-time', null],
      ['platform-reported-game-time', 'platform-reported-game-time', null],
    ],
  },
  {
    sectionId: 'session-evidence',
    sectionTitle: 'Game session evidence',
    sectionPurpose: 'Choose which proof is enough to count game time or support strict game rules.',
    sectionOrder: 3,
    groupId: 'session-evidence',
    groupTitle: 'Game session evidence',
    groupOrder: 3,
    settingId: 'evidence.whenProofUnavailable',
    settingOrder: 3,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/evidence/whenProofUnavailable',
    question: 'What if game proof is unavailable?',
    defaultValue: 'ask',
    options: [
      ['allow', 'allow', null],
      ['observe', 'observe', null],
      ['warn', 'warn', null],
      ['ask', 'ask', null],
      ['block-until-ready', 'block-until-ready', null],
      ['mark-unavailable', 'mark-unavailable', null],
    ],
  },
  {
    sectionId: 'session-evidence',
    sectionTitle: 'Game session evidence',
    sectionPurpose: 'Choose which proof is enough to count game time or support strict game rules.',
    sectionOrder: 3,
    groupId: 'session-evidence',
    groupTitle: 'Game session evidence',
    groupOrder: 3,
    settingId: 'evidence.neverCollect',
    settingOrder: 4,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/evidence/neverCollect',
    question: 'What must game rules never collect?',
    defaultValue: [
      'screenshots',
      'keystrokes',
      'chat-content',
      'voice-content',
      'game-memory',
      'decrypted-network-payload',
      'launcher-credentials',
      'private-social-graph',
      'raw-anti-cheat-data',
    ],
    options: [
      ['screenshots', 'screenshots', null],
      ['keystrokes', 'keystrokes', null],
      ['chat-content', 'chat-content', null],
      ['voice-content', 'voice-content', null],
      ['game-memory', 'game-memory', null],
      ['decrypted-network-payload', 'decrypted-network-payload', null],
      ['launcher-credentials', 'launcher-credentials', null],
      ['private-social-graph', 'private-social-graph', null],
      ['raw-anti-cheat-data', 'raw-anti-cheat-data', null],
      ['purchase-history', 'purchase-history', null],
      ['cloud-save-content', 'cloud-save-content', null],
    ],
  },
  {
    sectionId: 'native-games',
    sectionTitle: 'Native games',
    sectionPurpose: 'Configure desktop/native executable and package controls.',
    sectionOrder: 4,
    groupId: 'native-games',
    groupTitle: 'Native games',
    groupOrder: 4,
    settingId: 'nativeGames.mode',
    settingOrder: 1,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/nativeGames/mode',
    question: 'How should native games be handled?',
    defaultValue: 'observe-and-limit',
    options: [
      ['off', 'off', null],
      ['observe', 'observe', null],
      ['warn', 'warn', null],
      ['ask', 'ask', null],
      ['observe-and-limit', 'observe-and-limit', null],
      ['block-when-proven', 'block-when-proven', null],
    ],
  },
  {
    sectionId: 'native-games',
    sectionTitle: 'Native games',
    sectionPurpose: 'Configure desktop/native executable and package controls.',
    sectionOrder: 4,
    groupId: 'native-games',
    groupTitle: 'Native games',
    groupOrder: 4,
    settingId: 'nativeGames.allowedIdentityTypes',
    settingOrder: 2,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/nativeGames/allowedIdentityTypes',
    question: 'Which native game identities may rules target?',
    defaultValue: ['package-id', 'executable-hash', 'publisher-signature', 'launcher-app-id', 'game-title'],
    options: [
      ['package-id', 'package-id', null],
      ['executable-path', 'executable-path', null],
      ['executable-hash', 'executable-hash', null],
      ['publisher-signature', 'publisher-signature', null],
      ['launcher-app-id', 'launcher-app-id', null],
      ['game-title', 'game-title', null],
      ['game-category', 'game-category', null],
      ['rating-threshold', 'rating-threshold', null],
      ['unknown-candidate', 'unknown-candidate', null],
    ],
  },
  {
    sectionId: 'native-games',
    sectionTitle: 'Native games',
    sectionPurpose: 'Configure desktop/native executable and package controls.',
    sectionOrder: 4,
    groupId: 'native-games',
    groupTitle: 'Native games',
    groupOrder: 4,
    settingId: 'nativeGames.strictActions',
    settingOrder: 3,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/nativeGames/strictActions',
    question: 'Which strict native game actions may be used?',
    defaultValue: ['ask', 'time-limit', 'terminate-accessible-process'],
    options: [
      ['ask', 'ask', null],
      ['time-limit', 'time-limit', null],
      ['terminate-accessible-process', 'terminate-accessible-process', null],
      ['block-launch', 'block-launch', null],
      ['temporary-block', 'temporary-block', null],
      ['repair-required', 'repair-required', null],
      ['observe-only', 'observe-only', null],
    ],
  },
  {
    sectionId: 'launcher-games',
    sectionTitle: 'Launchers and stores',
    sectionPurpose:
      'Configure launcher-backed attribution and limits without treating launcher activity as guaranteed gameplay.',
    sectionOrder: 5,
    groupId: 'launcher-games',
    groupTitle: 'Launchers and stores',
    groupOrder: 5,
    settingId: 'launchers.supportedKinds',
    settingOrder: 1,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/launchers/supportedKinds',
    question: 'Which launchers or stores should be considered?',
    defaultValue: ['steam', 'xbox-app', 'microsoft-store', 'epic-games', 'roblox', 'minecraft-launcher'],
    options: [
      ['steam', 'steam', null],
      ['epic-games', 'epic-games', null],
      ['xbox-app', 'xbox-app', null],
      ['microsoft-store', 'microsoft-store', null],
      ['riot-client', 'riot-client', null],
      ['battle-net', 'battle-net', null],
      ['ea-app', 'ea-app', null],
      ['ubisoft-connect', 'ubisoft-connect', null],
      ['gog-galaxy', 'gog-galaxy', null],
      ['roblox', 'roblox', null],
      ['minecraft-launcher', 'minecraft-launcher', null],
      ['unknown-launcher', 'unknown-launcher', null],
    ],
  },
  {
    sectionId: 'launcher-games',
    sectionTitle: 'Launchers and stores',
    sectionPurpose:
      'Configure launcher-backed attribution and limits without treating launcher activity as guaranteed gameplay.',
    sectionOrder: 5,
    groupId: 'launcher-games',
    groupTitle: 'Launchers and stores',
    groupOrder: 5,
    settingId: 'launchers.launcherOnlyHandling',
    settingOrder: 2,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/launchers/launcherOnlyHandling',
    question: 'How should launcher-only time be handled?',
    defaultValue: 'report-separately',
    options: [
      ['ignore', 'ignore', null],
      ['report-separately', 'report-separately', null],
      ['count-as-possible-game', 'count-as-possible-game', null],
      ['ask-after-threshold', 'ask-after-threshold', null],
      ['block', 'block', null],
    ],
  },
  {
    sectionId: 'launcher-games',
    sectionTitle: 'Launchers and stores',
    sectionPurpose:
      'Configure launcher-backed attribution and limits without treating launcher activity as guaranteed gameplay.',
    sectionOrder: 5,
    groupId: 'launcher-games',
    groupTitle: 'Launchers and stores',
    groupOrder: 5,
    settingId: 'launchers.whenManifestUnavailable',
    settingOrder: 3,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/launchers/whenManifestUnavailable',
    question: 'What if launcher manifests cannot be read?',
    defaultValue: 'use-process-evidence-only',
    options: [
      ['use-process-evidence-only', 'use-process-evidence-only', null],
      ['mark-unavailable', 'mark-unavailable', null],
      ['ask', 'ask', null],
      ['manual-parent-catalog', 'manual-parent-catalog', null],
    ],
  },
  {
    sectionId: 'browser-cloud-games',
    sectionTitle: 'Browser and cloud games',
    sectionPurpose: 'Configure browser-game and cloud-game handling using the correct evidence boundary.',
    sectionOrder: 6,
    groupId: 'browser-cloud-games',
    groupTitle: 'Browser and cloud games',
    groupOrder: 6,
    settingId: 'browserCloud.mode',
    settingOrder: 1,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/browserCloud/mode',
    question: 'How should browser and cloud games be counted?',
    defaultValue: 'managed-proof-only',
    options: [
      ['off', 'off', null],
      ['report-only', 'report-only', null],
      ['managed-proof-only', 'managed-proof-only', null],
      ['domain-service-hint', 'domain-service-hint', null],
      ['count-cloud-client', 'count-cloud-client', null],
      ['ask', 'ask', null],
    ],
  },
  {
    sectionId: 'browser-cloud-games',
    sectionTitle: 'Browser and cloud games',
    sectionPurpose: 'Configure browser-game and cloud-game handling using the correct evidence boundary.',
    sectionOrder: 6,
    groupId: 'browser-cloud-games',
    groupTitle: 'Browser and cloud games',
    groupOrder: 6,
    settingId: 'browserCloud.allowedEvidence',
    settingOrder: 2,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/browserCloud/allowedEvidence',
    question: 'Which evidence may classify browser or cloud game use?',
    defaultValue: ['managed-browser-url', 'cloud-client-process', 'parent-catalog'],
    options: [
      ['managed-browser-url', 'managed-browser-url', null],
      ['managed-browser-title', 'managed-browser-title', null],
      ['domain-service-hint', 'domain-service-hint', null],
      ['cloud-client-process', 'cloud-client-process', null],
      ['network-flow-service-hint', 'network-flow-service-hint', null],
      ['platform-family-activity', 'platform-family-activity', null],
      ['parent-catalog', 'parent-catalog', null],
    ],
  },
  {
    sectionId: 'game-rules',
    sectionTitle: 'Game rules',
    sectionPurpose:
      'Rules for games, launchers, categories, ratings, unknown candidates, sessions, and capability states.',
    sectionOrder: 7,
    groupId: 'game-rules',
    groupTitle: 'Game rules',
    groupOrder: 7,
    settingId: 'rules.allowedTargetTypes',
    settingOrder: 1,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/rules/allowedTargetTypes',
    question: 'What game targets should rules match?',
    defaultValue: ['known-game', 'game-category', 'launcher-kind', 'game-session', 'possibly-game', 'capability-state'],
    options: [
      ['known-game', 'known-game', null],
      ['game-title', 'game-title', null],
      ['game-category', 'game-category', null],
      ['rating-threshold', 'rating-threshold', null],
      ['launcher-kind', 'launcher-kind', null],
      ['launcher-app-id', 'launcher-app-id', null],
      ['executable-identity', 'executable-identity', null],
      ['package-id', 'package-id', null],
      ['game-session', 'game-session', null],
      ['possibly-game', 'possibly-game', null],
      ['unknown-process', 'unknown-process', null],
      ['browser-game-site', 'browser-game-site', null],
      ['cloud-game-service', 'cloud-game-service', null],
      ['capability-state', 'capability-state', null],
    ],
  },
  {
    sectionId: 'game-rules',
    sectionTitle: 'Game rules',
    sectionPurpose:
      'Rules for games, launchers, categories, ratings, unknown candidates, sessions, and capability states.',
    sectionOrder: 7,
    groupId: 'game-rules',
    groupTitle: 'Game rules',
    groupOrder: 7,
    settingId: 'rules.allowedActions',
    settingOrder: 2,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/rules/allowedActions',
    question: 'What actions may game rules use?',
    defaultValue: ['allow', 'monitor', 'warn', 'ask', 'limit', 'terminate'],
    options: [
      ['allow', 'allow', null],
      ['monitor', 'monitor', null],
      ['warn', 'warn', null],
      ['ask', 'ask', null],
      ['limit', 'limit', null],
      ['terminate', 'terminate', null],
      ['block-launch', 'block-launch', null],
      ['temporary-block', 'temporary-block', null],
      ['platform-shield', 'platform-shield', null],
      ['manual-required', 'manual-required', null],
    ],
  },
  {
    sectionId: 'game-rules',
    sectionTitle: 'Game rules',
    sectionPurpose:
      'Rules for games, launchers, categories, ratings, unknown candidates, sessions, and capability states.',
    sectionOrder: 7,
    groupId: 'game-rules',
    groupTitle: 'Game rules',
    groupOrder: 7,
    settingId: 'rules.items',
    settingOrder: 3,
    controlType: 'rule-list',
    writesTo: '/gamePolicy/rules/items',
    question: 'Which game rules should apply?',
    defaultValue: [],
    options: [],
  },
  {
    sectionId: 'budgets',
    sectionTitle: 'Game time budgets',
    sectionPurpose: 'Budgets and schedules used when posture or a rule limits game activity.',
    sectionOrder: 8,
    groupId: 'budgets',
    groupTitle: 'Game time budgets',
    groupOrder: 8,
    settingId: 'budgets.enabled',
    settingOrder: 1,
    controlType: 'boolean',
    writesTo: '/gamePolicy/budgets/enabled',
    question: 'Use game time budgets?',
    defaultValue: true,
    options: [],
  },
  {
    sectionId: 'budgets',
    sectionTitle: 'Game time budgets',
    sectionPurpose: 'Budgets and schedules used when posture or a rule limits game activity.',
    sectionOrder: 8,
    groupId: 'budgets',
    groupTitle: 'Game time budgets',
    groupOrder: 8,
    settingId: 'budgets.defaultDailyMinutes',
    settingOrder: 2,
    controlType: 'number',
    writesTo: '/gamePolicy/budgets/defaultDailyMinutes',
    question: 'How many game minutes are allowed per day?',
    defaultValue: 60,
    options: [],
  },
  {
    sectionId: 'budgets',
    sectionTitle: 'Game time budgets',
    sectionPurpose: 'Budgets and schedules used when posture or a rule limits game activity.',
    sectionOrder: 8,
    groupId: 'budgets',
    groupTitle: 'Game time budgets',
    groupOrder: 8,
    settingId: 'budgets.warningThresholdMinutes',
    settingOrder: 3,
    controlType: 'number',
    writesTo: '/gamePolicy/budgets/warningThresholdMinutes',
    question: 'How many minutes before a limit should the child be warned?',
    defaultValue: 10,
    options: [],
  },
  {
    sectionId: 'budgets',
    sectionTitle: 'Game time budgets',
    sectionPurpose: 'Budgets and schedules used when posture or a rule limits game activity.',
    sectionOrder: 8,
    groupId: 'budgets',
    groupTitle: 'Game time budgets',
    groupOrder: 8,
    settingId: 'budgets.graceMinutes',
    settingOrder: 4,
    controlType: 'number',
    writesTo: '/gamePolicy/budgets/graceMinutes',
    question: 'How many grace minutes are allowed before strict action?',
    defaultValue: 5,
    options: [],
  },
  {
    sectionId: 'approvals',
    sectionTitle: 'Parent approvals',
    sectionPurpose: 'Events that need parent approval and how approvals expire.',
    sectionOrder: 9,
    groupId: 'approvals',
    groupTitle: 'Parent approvals',
    groupOrder: 9,
    settingId: 'approvals.requiredFor',
    settingOrder: 1,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/approvals/requiredFor',
    question: 'What should need parent approval?',
    defaultValue: ['blocked-game', 'new-game', 'unknown-game', 'time-extension'],
    options: [
      ['blocked-game', 'blocked-game', null],
      ['new-game', 'new-game', null],
      ['unknown-game', 'unknown-game', null],
      ['possibly-game', 'possibly-game', null],
      ['launcher-game-candidate', 'launcher-game-candidate', null],
      ['time-extension', 'time-extension', null],
      ['rating-threshold', 'rating-threshold', null],
      ['multiplayer-capable-game', 'multiplayer-capable-game', null],
      ['platform-setup', 'platform-setup', null],
    ],
  },
  {
    sectionId: 'approvals',
    sectionTitle: 'Parent approvals',
    sectionPurpose: 'Events that need parent approval and how approvals expire.',
    sectionOrder: 9,
    groupId: 'approvals',
    groupTitle: 'Parent approvals',
    groupOrder: 9,
    settingId: 'approvals.unansweredDefault',
    settingOrder: 2,
    controlType: 'single-choice',
    writesTo: '/gamePolicy/approvals/unansweredDefault',
    question: 'What happens if parent does not answer?',
    defaultValue: 'deny',
    options: [
      ['deny', 'deny', null],
      ['allow-temporarily', 'allow-temporarily', null],
      ['continue-observe-only', 'continue-observe-only', null],
      ['keep-waiting', 'keep-waiting', null],
    ],
  },
  {
    sectionId: 'approvals',
    sectionTitle: 'Parent approvals',
    sectionPurpose: 'Events that need parent approval and how approvals expire.',
    sectionOrder: 9,
    groupId: 'approvals',
    groupTitle: 'Parent approvals',
    groupOrder: 9,
    settingId: 'approvals.allowedParentResponses',
    settingOrder: 3,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/approvals/allowedParentResponses',
    question: 'Which parent responses are allowed?',
    defaultValue: ['approve-once', 'approve-session', 'approve-until-time', 'deny', 'extend-time', 'cancel'],
    options: [
      ['approve-once', 'approve-once', null],
      ['approve-session', 'approve-session', null],
      ['approve-until-time', 'approve-until-time', null],
      ['approve-for-schedule', 'approve-for-schedule', null],
      ['deny', 'deny', null],
      ['extend-time', 'extend-time', null],
      ['cancel', 'cancel', null],
    ],
  },
  {
    sectionId: 'reports',
    sectionTitle: 'Reports and retention',
    sectionPurpose: 'What parents see and how long data stays available.',
    sectionOrder: 10,
    groupId: 'reports',
    groupTitle: 'Reports and retention',
    groupOrder: 10,
    settingId: 'reports.visibleFields',
    settingOrder: 1,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/reports/visibleFields',
    question: 'What should parents see in game reports?',
    defaultValue: [
      'inventory-status',
      'running-now',
      'foreground-now',
      'recent-sessions',
      'time-budget',
      'policy-decisions',
      'source-capability',
    ],
    options: [
      ['inventory-status', 'inventory-status', null],
      ['running-now', 'running-now', null],
      ['foreground-now', 'foreground-now', null],
      ['recent-sessions', 'recent-sessions', null],
      ['daily-rollups', 'daily-rollups', null],
      ['unknown-candidates', 'unknown-candidates', null],
      ['launcher-status', 'launcher-status', null],
      ['rating-category', 'rating-category', null],
      ['approval-events', 'approval-events', null],
      ['block-results', 'block-results', null],
      ['time-budget', 'time-budget', null],
      ['policy-decisions', 'policy-decisions', null],
      ['source-capability', 'source-capability', null],
    ],
  },
  {
    sectionId: 'reports',
    sectionTitle: 'Reports and retention',
    sectionPurpose: 'What parents see and how long data stays available.',
    sectionOrder: 10,
    groupId: 'reports',
    groupTitle: 'Reports and retention',
    groupOrder: 10,
    settingId: 'retention.rawEvidence',
    settingOrder: 2,
    controlType: 'retention',
    writesTo: '/gamePolicy/retention/rawEvidence',
    question: 'How long should raw process/window game evidence be kept?',
    defaultValue: '7-days',
    options: [
      ['fresh-only', 'fresh-only', null],
      ['24-hours', '24-hours', null],
      ['7-days', '7-days', null],
      ['30-days', '30-days', null],
      ['until-reset', 'until-reset', null],
      ['delete-expired', 'delete-expired', null],
    ],
  },
  {
    sectionId: 'reports',
    sectionTitle: 'Reports and retention',
    sectionPurpose: 'What parents see and how long data stays available.',
    sectionOrder: 10,
    groupId: 'reports',
    groupTitle: 'Reports and retention',
    groupOrder: 10,
    settingId: 'custody.allowedUses',
    settingOrder: 3,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/custody/allowedUses',
    question: 'Where may game data be used?',
    defaultValue: ['child-local', 'lan-live', 'parent-cache', 'parent-report'],
    options: [
      ['child-local', 'child-local', null],
      ['lan-live', 'lan-live', null],
      ['parent-cache', 'parent-cache', null],
      ['parent-export', 'parent-export', null],
      ['parent-report', 'parent-report', null],
      ['unavailable', 'unavailable', null],
    ],
  },
  {
    sectionId: 'audit',
    sectionTitle: 'Audit',
    sectionPurpose: 'Audit requirements for strict game actions.',
    sectionOrder: 11,
    groupId: 'audit',
    groupTitle: 'Audit',
    groupOrder: 11,
    settingId: 'audit.requiredFields',
    settingOrder: 1,
    controlType: 'multi-choice',
    writesTo: '/gamePolicy/audit/requiredFields',
    question: 'What should game actions audit?',
    defaultValue: [
      'policy-decision',
      'evidence-ref',
      'adapter-result',
      'timer-state',
      'parent-override',
      'rollback',
      'policy-version',
      'capability-state',
    ],
    options: [
      ['policy-decision', 'policy-decision', null],
      ['evidence-ref', 'evidence-ref', null],
      ['ai-ref', 'ai-ref', null],
      ['adapter-result', 'adapter-result', null],
      ['timer-state', 'timer-state', null],
      ['parent-override', 'parent-override', null],
      ['rollback', 'rollback', null],
      ['policy-version', 'policy-version', null],
      ['capability-state', 'capability-state', null],
      ['custody-label', 'custody-label', null],
      ['protected-process-status', 'protected-process-status', null],
      ['target-recheck', 'target-recheck', null],
    ],
  },
] as const satisfies readonly GameControlCatalogSettingSeed[];

export const GameControlCapabilitySeeds = [
  {
    capabilityId: 'windows-process-observation',
    state: 'available',
    proofRequirement: 'runtime-read-model-required',
    affectsSettingIds: ['inventory.sources', 'evidence.requiredProof', 'rules.allowedTargetTypes'],
  },
  {
    capabilityId: 'windows-foreground-window-observation',
    state: 'available',
    proofRequirement: 'runtime-read-model-required',
    affectsSettingIds: ['evidence.requiredProof', 'evidence.durationCountingMode', 'budgets.enabled'],
  },
  {
    capabilityId: 'windows-installed-app-inventory',
    state: 'available',
    proofRequirement: 'runtime-read-model-required',
    affectsSettingIds: ['inventory.mode', 'inventory.sources', 'nativeGames.allowedIdentityTypes'],
  },
  {
    capabilityId: 'launcher-manifest-reader',
    state: 'manual-required',
    proofRequirement: 'not-yet-proven-for-each-launcher',
    affectsSettingIds: ['launchers.supportedKinds', 'inventory.sources', 'rules.allowedTargetTypes'],
  },
  {
    capabilityId: 'owned-process-termination',
    state: 'available',
    proofRequirement: 'runtime-adapter-proof-required',
    affectsSettingIds: ['nativeGames.strictActions', 'rules.allowedActions'],
  },
  {
    capabilityId: 'broad-app-control-blocking',
    state: 'manual-required',
    proofRequirement: 'not-yet-proven',
    affectsSettingIds: ['nativeGames.strictActions', 'rules.allowedActions', 'game.defaultPosture'],
  },
  {
    capabilityId: 'anti-cheat-protected-process-handling',
    state: 'degraded',
    proofRequirement: 'must-not-bypass-record-limits-only',
    affectsSettingIds: ['nativeGames.strictActions', 'audit.requiredFields'],
  },
  {
    capabilityId: 'managed-browser-game-proof',
    state: 'manual-required',
    proofRequirement: 'browser-control-boundary-required',
    affectsSettingIds: ['browserCloud.mode', 'browserCloud.allowedEvidence', 'rules.allowedTargetTypes'],
  },
  {
    capabilityId: 'platform-family-controls',
    state: 'manual-required',
    proofRequirement: 'platform-integration-required',
    affectsSettingIds: ['game.managementMode', 'browserCloud.allowedEvidence', 'rules.allowedActions'],
  },
] as const;

export const GameControlCapabilityTruthSeeds = [
  {
    truthId: 'game-truth-launcher-not-gameplay',
    sourceHeadingPath: ['Launcher Or Store'],
    originalSourceText: 'Launcher evidence is useful, but it is not automatically game evidence.',
    appliesToSettingIds: ['launchers.supportedKinds', 'launchers.launcherOnlyHandling'],
    capabilityState: 'manual-required',
  },
  {
    truthId: 'game-truth-browser-game-boundary',
    sourceHeadingPath: ['Browser Game'],
    originalSourceText:
      'Exact browser-game proof requires managed browser URL/tab evidence or another explicit browser boundary.',
    appliesToSettingIds: ['browserCloud.mode', 'browserCloud.allowedEvidence'],
    capabilityState: 'manual-required',
  },
  {
    truthId: 'game-truth-network-not-title-proof',
    sourceHeadingPath: ['Cloud Game'],
    originalSourceText: 'Network-only evidence can suggest a service or domain but usually cannot prove exact title.',
    appliesToSettingIds: ['browserCloud.allowedEvidence', 'rules.allowedTargetTypes'],
    capabilityState: 'degraded',
  },
  {
    truthId: 'game-truth-foreground-duration-proof',
    sourceHeadingPath: ['Foreground Game Session', 'Duration Proof'],
    originalSourceText:
      'Foreground time and duration proof must come from child-device process/window observations and evidence refs.',
    appliesToSettingIds: ['evidence.requiredProof', 'evidence.durationCountingMode', 'budgets.enabled'],
    capabilityState: 'available',
  },
  {
    truthId: 'game-truth-unknown-stays-unknown',
    sourceHeadingPath: ['Game Categories And Age Ratings'],
    originalSourceText:
      'Unknown and possible-game states must remain visible instead of being silently promoted to known games.',
    appliesToSettingIds: ['inventory.classificationStates', 'rules.allowedTargetTypes'],
    capabilityState: 'degraded',
  },
  {
    truthId: 'game-truth-anti-cheat-no-bypass',
    sourceHeadingPath: ['Protected Or Anti-Cheat Process'],
    originalSourceText: 'Ocentra must not try to bypass protected or anti-cheat process controls.',
    appliesToSettingIds: ['nativeGames.strictActions', 'audit.requiredFields'],
    capabilityState: 'degraded',
  },
  {
    truthId: 'game-truth-terminate-recheck-audit',
    sourceHeadingPath: ['Enforcement Actions', 'Terminate'],
    originalSourceText: 'Termination requires target recheck, adapter result, timer/approval state, and evidence refs.',
    appliesToSettingIds: ['nativeGames.strictActions', 'rules.allowedActions', 'audit.requiredFields'],
    capabilityState: 'protected',
  },
  {
    truthId: 'game-truth-parent-approval-agent-owned',
    sourceHeadingPath: ['Parent Approval'],
    originalSourceText:
      'Parent approval is a typed policy path; unanswered requests follow deterministic child-agent fallback.',
    appliesToSettingIds: ['approvals.requiredFor', 'approvals.unansweredDefault', 'approvals.allowedParentResponses'],
    capabilityState: 'available',
  },
  {
    truthId: 'game-truth-local-custody-default',
    sourceHeadingPath: ['Reports, Custody, Retention, And Audit'],
    originalSourceText: 'Ocentra-hosted services must not become the default store for raw game activity evidence.',
    appliesToSettingIds: ['reports.visibleFields', 'retention.rawEvidence', 'custody.allowedUses'],
    capabilityState: 'available',
  },
  {
    truthId: 'game-truth-mobile-manual-required',
    sourceHeadingPath: ['Platform Capability Notes', 'Android', 'iOS And iPadOS'],
    originalSourceText:
      'Mobile game control is platform-dependent and manual-required until device-owner or platform entitlement proof exists.',
    appliesToSettingIds: ['game.managementMode', 'browserCloud.allowedEvidence'],
    capabilityState: 'manual-required',
  },
  {
    truthId: 'game-truth-console-platform-only',
    sourceHeadingPath: ['Platform Capability Notes', 'Consoles'],
    originalSourceText:
      'Console play is external platform family-control state unless Ocentra later builds an approved integration.',
    appliesToSettingIds: ['game.managementMode', 'rules.allowedActions'],
    capabilityState: 'manual-required',
  },
] as const;

export const GameControlUpdateCommandSeeds = [
  ['game-policy.get.requested', 'Portal asks the child agent for current policy value and revision.'],
  ['game-policy.preview.requested', 'Portal asks whether proposed changes validate and what effective policy results.'],
  ['game-policy.patch.requested', 'Portal sends a small settings change with an expected revision.'],
  ['game-policy.replace.requested', 'Portal sends a full policy replacement for setup, import, reset, or wizard save.'],
  ['game-policy.acknowledge.requested', 'Portal acknowledges an accepted game policy update event.'],
  ['game-policy.reject.requested', 'Portal records that a proposed game policy update was rejected.'],
  ['game-policy.rollback.requested', 'Parent asks child agent to roll back to a previous valid revision.'],
  ['game-policy.capability-refresh.requested', 'Portal asks the child agent to refresh game capability states.'],
] as const;
