use super::identifiers::{proof_ref, replay_ref, row_id, tombstone_ref};
use super::*;

pub(super) fn sample_retention_delete_rows(
    request: &RetentionDeleteRequest,
) -> Vec<RetentionDeleteRow> {
    let mut rows = sample_retention_delete_rows_primary(request);
    rows.extend(sample_retention_delete_rows_secondary(request));
    rows.extend(sample_retention_delete_rows_tertiary(request));
    rows
}

fn sample_retention_delete_rows_primary(
    request: &RetentionDeleteRequest,
) -> Vec<RetentionDeleteRow> {
    vec![
        sample_row(SampleRowInput {
            request,
            data_class: RetentionDeleteDataClass::EvidenceJournal,
            state: RetentionDeleteState::DeleteRequested,
            retention_class: RetentionDeleteRetentionClass::DeleteRequested,
            tombstone_ref: None,
            replay_ref: None,
            tombstone_written: false,
            local_payload_present: true,
            local_payload_redacted: false,
            propagation_pending: false,
            propagated: false,
            replay_blocked: false,
            restore_revival_blocked: false,
            minimal_audit_ref_retained: false,
            report_export_leak_blocked: true,
            assistant_leak_blocked: true,
            notification_leak_blocked: true,
            hard_deleted: false,
        }),
        sample_row(SampleRowInput {
            request,
            data_class: RetentionDeleteDataClass::PolicyHistory,
            state: RetentionDeleteState::DeleteValidated,
            retention_class: RetentionDeleteRetentionClass::DeleteRequested,
            tombstone_ref: None,
            replay_ref: None,
            tombstone_written: false,
            local_payload_present: true,
            local_payload_redacted: false,
            propagation_pending: false,
            propagated: false,
            replay_blocked: false,
            restore_revival_blocked: false,
            minimal_audit_ref_retained: false,
            report_export_leak_blocked: true,
            assistant_leak_blocked: true,
            notification_leak_blocked: true,
            hard_deleted: false,
        }),
        sample_row(SampleRowInput {
            request,
            data_class: RetentionDeleteDataClass::EvidenceJournal,
            state: RetentionDeleteState::TombstoneWritten,
            retention_class: RetentionDeleteRetentionClass::DeleteConfirmed,
            tombstone_ref: Some(tombstone_ref(RETENTION_DELETE_SAMPLE_TOMBSTONE_REF_ONE)),
            replay_ref: None,
            tombstone_written: true,
            local_payload_present: true,
            local_payload_redacted: false,
            propagation_pending: false,
            propagated: false,
            replay_blocked: false,
            restore_revival_blocked: false,
            minimal_audit_ref_retained: false,
            report_export_leak_blocked: true,
            assistant_leak_blocked: true,
            notification_leak_blocked: true,
            hard_deleted: false,
        }),
    ]
}

fn sample_retention_delete_rows_secondary(
    request: &RetentionDeleteRequest,
) -> Vec<RetentionDeleteRow> {
    vec![
        sample_row(SampleRowInput {
            request,
            data_class: RetentionDeleteDataClass::Screenshots,
            state: RetentionDeleteState::LocalRedacted,
            retention_class: RetentionDeleteRetentionClass::DeleteConfirmed,
            tombstone_ref: Some(tombstone_ref(RETENTION_DELETE_SAMPLE_TOMBSTONE_REF_TWO)),
            replay_ref: None,
            tombstone_written: true,
            local_payload_present: false,
            local_payload_redacted: true,
            propagation_pending: false,
            propagated: false,
            replay_blocked: false,
            restore_revival_blocked: false,
            minimal_audit_ref_retained: false,
            report_export_leak_blocked: true,
            assistant_leak_blocked: true,
            notification_leak_blocked: true,
            hard_deleted: false,
        }),
        sample_row(SampleRowInput {
            request,
            data_class: RetentionDeleteDataClass::NetworkArtifacts,
            state: RetentionDeleteState::PropagationPending,
            retention_class: RetentionDeleteRetentionClass::DeleteConfirmed,
            tombstone_ref: Some(tombstone_ref(RETENTION_DELETE_SAMPLE_TOMBSTONE_REF_THREE)),
            replay_ref: None,
            tombstone_written: true,
            local_payload_present: false,
            local_payload_redacted: true,
            propagation_pending: true,
            propagated: false,
            replay_blocked: false,
            restore_revival_blocked: false,
            minimal_audit_ref_retained: false,
            report_export_leak_blocked: true,
            assistant_leak_blocked: true,
            notification_leak_blocked: true,
            hard_deleted: false,
        }),
        sample_row(SampleRowInput {
            request,
            data_class: RetentionDeleteDataClass::Reports,
            state: RetentionDeleteState::Propagated,
            retention_class: RetentionDeleteRetentionClass::DeleteConfirmed,
            tombstone_ref: Some(tombstone_ref(RETENTION_DELETE_SAMPLE_TOMBSTONE_REF_FOUR)),
            replay_ref: None,
            tombstone_written: true,
            local_payload_present: false,
            local_payload_redacted: true,
            propagation_pending: false,
            propagated: true,
            replay_blocked: false,
            restore_revival_blocked: false,
            minimal_audit_ref_retained: false,
            report_export_leak_blocked: true,
            assistant_leak_blocked: true,
            notification_leak_blocked: true,
            hard_deleted: false,
        }),
    ]
}

fn sample_retention_delete_rows_tertiary(
    request: &RetentionDeleteRequest,
) -> Vec<RetentionDeleteRow> {
    vec![
        sample_row(SampleRowInput {
            request,
            data_class: RetentionDeleteDataClass::AiOutputs,
            state: RetentionDeleteState::ReplayProtected,
            retention_class: RetentionDeleteRetentionClass::DeleteConfirmed,
            tombstone_ref: Some(tombstone_ref(RETENTION_DELETE_SAMPLE_TOMBSTONE_REF_FIVE)),
            replay_ref: Some(replay_ref(RETENTION_DELETE_SAMPLE_REPLAY_REF_ONE)),
            tombstone_written: true,
            local_payload_present: false,
            local_payload_redacted: true,
            propagation_pending: false,
            propagated: true,
            replay_blocked: true,
            restore_revival_blocked: false,
            minimal_audit_ref_retained: false,
            report_export_leak_blocked: true,
            assistant_leak_blocked: true,
            notification_leak_blocked: true,
            hard_deleted: false,
        }),
        sample_row(SampleRowInput {
            request,
            data_class: RetentionDeleteDataClass::Notifications,
            state: RetentionDeleteState::AuditRetained,
            retention_class: RetentionDeleteRetentionClass::AuditMinimal,
            tombstone_ref: Some(tombstone_ref(RETENTION_DELETE_SAMPLE_TOMBSTONE_REF_SIX)),
            replay_ref: Some(replay_ref(RETENTION_DELETE_SAMPLE_REPLAY_REF_TWO)),
            tombstone_written: true,
            local_payload_present: false,
            local_payload_redacted: true,
            propagation_pending: false,
            propagated: true,
            replay_blocked: true,
            restore_revival_blocked: true,
            minimal_audit_ref_retained: true,
            report_export_leak_blocked: true,
            assistant_leak_blocked: true,
            notification_leak_blocked: true,
            hard_deleted: false,
        }),
        sample_row(SampleRowInput {
            request,
            data_class: RetentionDeleteDataClass::Logs,
            state: RetentionDeleteState::HardDeleted,
            retention_class: RetentionDeleteRetentionClass::HardDeleted,
            tombstone_ref: Some(tombstone_ref(RETENTION_DELETE_SAMPLE_TOMBSTONE_REF_SEVEN)),
            replay_ref: Some(replay_ref(RETENTION_DELETE_SAMPLE_REPLAY_REF_THREE)),
            tombstone_written: true,
            local_payload_present: false,
            local_payload_redacted: true,
            propagation_pending: false,
            propagated: true,
            replay_blocked: true,
            restore_revival_blocked: true,
            minimal_audit_ref_retained: true,
            report_export_leak_blocked: true,
            assistant_leak_blocked: true,
            notification_leak_blocked: true,
            hard_deleted: true,
        }),
    ]
}

struct SampleRowInput<'a> {
    request: &'a RetentionDeleteRequest,
    data_class: RetentionDeleteDataClass,
    state: RetentionDeleteState,
    retention_class: RetentionDeleteRetentionClass,
    tombstone_ref: Option<RetentionDeleteTombstoneRef>,
    replay_ref: Option<RetentionDeleteReplayRef>,
    tombstone_written: bool,
    local_payload_present: bool,
    local_payload_redacted: bool,
    propagation_pending: bool,
    propagated: bool,
    replay_blocked: bool,
    restore_revival_blocked: bool,
    minimal_audit_ref_retained: bool,
    report_export_leak_blocked: bool,
    assistant_leak_blocked: bool,
    notification_leak_blocked: bool,
    hard_deleted: bool,
}

fn sample_row(input: SampleRowInput<'_>) -> RetentionDeleteRow {
    let SampleRowInput {
        request,
        data_class,
        state,
        retention_class,
        tombstone_ref,
        replay_ref,
        tombstone_written,
        local_payload_present,
        local_payload_redacted,
        propagation_pending,
        propagated,
        replay_blocked,
        restore_revival_blocked,
        minimal_audit_ref_retained,
        report_export_leak_blocked,
        assistant_leak_blocked,
        notification_leak_blocked,
        hard_deleted,
    } = input;

    RetentionDeleteRow {
        row_id: row_id(format!("retention-delete-row-{}", state.as_str())),
        request_id: request.request_id.clone(),
        data_class,
        state,
        retention_class,
        tombstone_ref,
        replay_ref,
        proof_ref: proof_ref(format!("proof-ref-{}", state.as_str())),
        request_expired: false,
        parent_authorized: request.parent_authorized,
        tombstone_written,
        local_payload_present,
        local_payload_redacted,
        propagation_pending,
        propagated,
        replay_blocked,
        restore_revival_blocked,
        minimal_audit_ref_retained,
        audit_payload_redacted: minimal_audit_ref_retained,
        report_export_leak_blocked,
        assistant_leak_blocked,
        notification_leak_blocked,
        hard_deleted,
        claim_safe: true,
    }
}
