import { AppGamePolicyPreviewStatus, AppGamePolicyPreviewTargetDomain } from '../../src/app-game-policy-preview-handoff';
import {
  AppGameSourceFreshnessPolicyReadinessState,
  AppGameSourceFreshnessRequirementState,
} from '../../src/app-game-source-freshness-policy-consumption-values';
import {
  AppGameSourceFreshnessPreviewGateState,
  AppGameSourceFreshnessPreviewGateStatus,
} from '../../src/app-game-source-freshness-preview-gate';
import {
  AppGameSourceGatedPolicyPreviewReadModelProjectionState,
  AppGameSourceGatedPolicyPreviewReadModelSensitiveBoundary,
} from '../../src/app-game-source-gated-policy-preview-read-model';
import { ParentContractSchemaVersion } from '../../src/family-reference-primitives';

export const appGameTimerGeneratedAt = '2026-06-29T06:00:00.000Z';

export const timerSourceGatedReadModel = {
  schemaVersion: ParentContractSchemaVersion.V0_6,
  readModelId: 'source-gated-read-model-1',
  sourceGateId: 'gate-1',
  generatedAt: appGameTimerGeneratedAt,
  sourceContractRefs: ['contract-preview'],
  sourceGateContractRefs: ['contract-gate'],
  rows: [
    {
      schemaVersion: ParentContractSchemaVersion.V0_6,
      rowId: 'source-gated-row-1',
      sourceGateRowId: 'gate-row-1',
      sourceGateId: 'gate-1',
      targetDomain: AppGamePolicyPreviewTargetDomain.NativeApp,
      sourceReadinessId: 'readiness-app-1',
      sourcePolicyRequestId: 'request-app-1',
      sourceReadinessState: AppGameSourceFreshnessPolicyReadinessState.PolicyReady,
      sourceRequirementStates: [AppGameSourceFreshnessRequirementState.Satisfied],
      sourcePolicyCompileAllowed: true,
      sourceEvidenceRefs: ['evidence-app-ready'],
      gateState: AppGameSourceFreshnessPreviewGateState.SourceFresh,
      projectionState: AppGameSourceGatedPolicyPreviewReadModelProjectionState.PreviewReadyVisible,
      previewStatus: AppGameSourceFreshnessPreviewGateStatus.PreviewReady,
      previewDecisionRef: 'preview-decision-app-1',
      previewCompilerStatus: AppGamePolicyPreviewStatus.PreviewReady,
      sensitiveDetailBoundary:
        AppGameSourceGatedPolicyPreviewReadModelSensitiveBoundary.RedactedEvidenceRefsOnly,
      serviceRuntimeEventClaimed: false,
      portalUiRendered: false,
      policyEvaluatorRuntimeClaimed: false,
      timerRuntimeClaimed: false,
      adapterDispatchClaimed: false,
      childDeliveryClaimed: false,
      platformEnforcementClaimed: false,
      rawPrivateSourceRowsIncluded: false,
      generatedAt: appGameTimerGeneratedAt,
    },
    {
      schemaVersion: ParentContractSchemaVersion.V0_6,
      rowId: 'source-gated-row-2',
      sourceGateRowId: 'gate-row-2',
      sourceGateId: 'gate-1',
      targetDomain: AppGamePolicyPreviewTargetDomain.NativeGame,
      sourceReadinessId: 'readiness-game-1',
      sourcePolicyRequestId: 'request-game-1',
      sourceReadinessState: AppGameSourceFreshnessPolicyReadinessState.ManualRequired,
      sourceRequirementStates: [AppGameSourceFreshnessRequirementState.Stale],
      sourcePolicyCompileAllowed: false,
      sourceEvidenceRefs: ['evidence-game-stale'],
      gateState: AppGameSourceFreshnessPreviewGateState.SourceManualRequired,
      projectionState: AppGameSourceGatedPolicyPreviewReadModelProjectionState.SourceManualRequiredVisible,
      previewStatus: AppGameSourceFreshnessPreviewGateStatus.ManualRequired,
      previewDecisionRef: null,
      previewCompilerStatus: null,
      sensitiveDetailBoundary:
        AppGameSourceGatedPolicyPreviewReadModelSensitiveBoundary.RedactedEvidenceRefsOnly,
      serviceRuntimeEventClaimed: false,
      portalUiRendered: false,
      policyEvaluatorRuntimeClaimed: false,
      timerRuntimeClaimed: false,
      adapterDispatchClaimed: false,
      childDeliveryClaimed: false,
      platformEnforcementClaimed: false,
      rawPrivateSourceRowsIncluded: false,
      generatedAt: appGameTimerGeneratedAt,
    },
  ],
  nativeAppRowCount: 1,
  nativeGameRowCount: 1,
  previewReadyVisibleCount: 1,
  sourceManualRequiredVisibleCount: 1,
  compilerManualRequiredVisibleCount: 0,
  readModelNonClaims: [
    'no-service-runtime-event',
    'no-portal-ui-rendered',
    'no-policy-evaluator-runtime',
    'no-timer-runtime',
    'no-adapter-dispatch',
    'no-child-delivery',
    'no-platform-enforcement',
    'no-raw-private-source-rows',
  ],
  serviceRuntimeEventClaimed: false,
  portalUiRendered: false,
  policyEvaluatorRuntimeClaimed: false,
  timerRuntimeClaimed: false,
  adapterDispatchClaimed: false,
  childDeliveryClaimed: false,
  platformEnforcementClaimed: false,
  rawPrivateSourceRowsIncluded: false,
} as const;

export const timerHandoffMetadata = {
  schemaVersion: ParentContractSchemaVersion.V0_6,
  handoffId: 'timer-handoff-1',
  generatedAt: appGameTimerGeneratedAt,
  sourceContractRefs: ['contract-preview'],
} as const;

export const timerStatusMetadata = {
  schemaVersion: ParentContractSchemaVersion.V0_6,
  statusId: 'timer-status-1',
  generatedAt: appGameTimerGeneratedAt,
  sourceContractRefs: ['contract-timer-status'],
  timerRuntimeProofRef: 'proof-timer-runtime',
  sourceFreshnessProofRef: 'proof-source-freshness',
  compilerDecisionProofRef: 'proof-compiler-decision',
} as const;

export const timerRuntimeReadinessMetadata = {
  schemaVersion: ParentContractSchemaVersion.V0_6,
  readinessId: 'timer-runtime-readiness-1',
  generatedAt: appGameTimerGeneratedAt,
  sourceContractRefs: ['contract-runtime-readiness'],
  timerRuntimeProofRef: 'proof-timer-runtime',
  schedulerPersistenceProofRef: 'proof-scheduler-persistence',
  auditProofRef: 'proof-audit',
  rollbackProofRef: 'proof-rollback',
} as const;

export const timerSchedulerPersistenceMetadata = {
  schemaVersion: ParentContractSchemaVersion.V0_6,
  persistenceId: 'timer-scheduler-persistence-1',
  generatedAt: appGameTimerGeneratedAt,
  sourceContractRefs: ['contract-scheduler-persistence'],
  serviceTimerRuntimeProofRef: 'proof-service-timer-runtime',
  schedulerPersistenceProofRef: 'proof-scheduler-persistence',
  schedulerStateStoreProofRef: 'proof-scheduler-store',
  auditProofRef: 'proof-audit',
  rollbackProofRef: 'proof-rollback',
} as const;

export const serviceReadinessHandoff = {
  schemaVersion: ParentContractSchemaVersion.V0_6,
  handoffId: 'service-readiness-handoff-1',
  sourceParentSurfaceIntentId: 'parent-surface-intent-1',
  generatedAt: appGameTimerGeneratedAt,
  sourceContractRefs: ['contract-service-readiness-handoff'],
  rows: [
    {
      schemaVersion: ParentContractSchemaVersion.V0_6,
      rowId: 'service-readiness-row-1',
      sourceParentSurfaceIntentRowId: 'parent-surface-row-1',
      sourceAuditRollbackReadModelRowId: 'audit-read-model-row-1',
      sourceAuditRollbackHandoffRowId: 'audit-handoff-row-1',
      sourceSchedulerPersistenceRowId: 'scheduler-persistence-row-1',
      targetDomain: AppGamePolicyPreviewTargetDomain.NativeApp,
      serviceReadinessHandoffState: 'service-read-api-proof-required',
      parentSurfaceProofRequired: true,
      serviceReadinessProofRequired: true,
      serviceReadApiProofRequired: true,
      requiredProofRefs: [
        'proof-service-timer-runtime',
        'proof-scheduler-persistence',
        'proof-scheduler-store',
        'proof-audit',
        'proof-rollback',
        'proof-service-readiness',
        'proof-service-read-api',
      ],
      sourceEvidenceRefs: ['evidence-app-ready'],
      serviceReadApiRef: 'service-read-api-app',
      serviceRuntimeEventClaimed: false,
      serviceReadApiImplemented: false,
      portalUiRendered: false,
      policyEvaluatorRuntimeClaimed: false,
      timerRuntimeClaimed: false,
      timerScheduled: false,
      schedulerPersistenceRuntimeClaimed: false,
      durableSchedulerStorageClaimed: false,
      auditRuntimeClaimed: false,
      durableAuditLogClaimed: false,
      rollbackRuntimeClaimed: false,
      rollbackExecutionClaimed: false,
      adapterDispatchClaimed: false,
      childDeliveryClaimed: false,
      platformEnforcementClaimed: false,
      rawPrivateSourceRowsIncluded: false,
      generatedAt: appGameTimerGeneratedAt,
    },
    {
      schemaVersion: ParentContractSchemaVersion.V0_6,
      rowId: 'service-readiness-row-2',
      sourceParentSurfaceIntentRowId: 'parent-surface-row-2',
      sourceAuditRollbackReadModelRowId: 'audit-read-model-row-2',
      sourceAuditRollbackHandoffRowId: 'audit-handoff-row-2',
      sourceSchedulerPersistenceRowId: 'scheduler-persistence-row-2',
      targetDomain: AppGamePolicyPreviewTargetDomain.NativeGame,
      serviceReadinessHandoffState: 'blocked-by-source-freshness',
      parentSurfaceProofRequired: false,
      serviceReadinessProofRequired: false,
      serviceReadApiProofRequired: false,
      requiredProofRefs: ['proof-source-freshness'],
      sourceEvidenceRefs: ['evidence-game-stale'],
      serviceReadApiRef: 'service-read-api-game',
      serviceRuntimeEventClaimed: false,
      serviceReadApiImplemented: false,
      portalUiRendered: false,
      policyEvaluatorRuntimeClaimed: false,
      timerRuntimeClaimed: false,
      timerScheduled: false,
      schedulerPersistenceRuntimeClaimed: false,
      durableSchedulerStorageClaimed: false,
      auditRuntimeClaimed: false,
      durableAuditLogClaimed: false,
      rollbackRuntimeClaimed: false,
      rollbackExecutionClaimed: false,
      adapterDispatchClaimed: false,
      childDeliveryClaimed: false,
      platformEnforcementClaimed: false,
      rawPrivateSourceRowsIncluded: false,
      generatedAt: appGameTimerGeneratedAt,
    },
  ],
  nativeAppRowCount: 1,
  nativeGameRowCount: 1,
  serviceReadApiProofRequiredCount: 1,
  blockedBySourceFreshnessCount: 1,
  blockedByCompilerDecisionCount: 0,
  serviceReadinessHandoffNonClaims: [
    'no-service-runtime-event',
    'no-service-read-api-implemented',
    'no-portal-ui-rendered',
    'no-policy-evaluator-runtime',
    'no-timer-runtime',
    'no-timer-scheduled',
    'no-scheduler-persistence-runtime',
    'no-durable-scheduler-storage',
    'no-audit-runtime',
    'no-durable-audit-log',
    'no-rollback-runtime',
    'no-rollback-execution',
    'no-adapter-dispatch',
    'no-child-delivery',
    'no-platform-enforcement',
    'no-raw-private-source-rows',
  ],
  serviceRuntimeEventClaimed: false,
  serviceReadApiImplemented: false,
  portalUiRendered: false,
  policyEvaluatorRuntimeClaimed: false,
  timerRuntimeClaimed: false,
  timerScheduled: false,
  schedulerPersistenceRuntimeClaimed: false,
  durableSchedulerStorageClaimed: false,
  auditRuntimeClaimed: false,
  durableAuditLogClaimed: false,
  rollbackRuntimeClaimed: false,
  rollbackExecutionClaimed: false,
  adapterDispatchClaimed: false,
  childDeliveryClaimed: false,
  platformEnforcementClaimed: false,
  rawPrivateSourceRowsIncluded: false,
} as const;

export const serviceReadinessReadModelMetadata = {
  schemaVersion: ParentContractSchemaVersion.V0_6,
  readModelId: 'service-readiness-read-model-1',
  generatedAt: appGameTimerGeneratedAt,
  sourceContractRefs: ['contract-service-readiness-read-model'],
  serviceReadinessSummaryRef: 'service-readiness-summary-1',
} as const;

export const serviceReadinessProtocolHandoffMetadata = {
  schemaVersion: ParentContractSchemaVersion.V0_6,
  handoffId: 'protocol-handoff-1',
  generatedAt: appGameTimerGeneratedAt,
  sourceContractRefs: ['contract-protocol-handoff'],
  protocolCommandContractProofRef: 'proof-protocol-command',
  protocolEventContractProofRef: 'proof-protocol-event',
  rustProtocolMirrorProofRef: 'proof-rust-protocol-mirror',
  serviceHandlerProofRef: 'proof-service-handler',
} as const;

export const serviceReadinessProtocolReadModelMetadata = {
  schemaVersion: ParentContractSchemaVersion.V0_6,
  readModelId: 'protocol-read-model-1',
  generatedAt: appGameTimerGeneratedAt,
  sourceContractRefs: ['contract-protocol-read-model'],
  protocolSummaryRef: 'protocol-summary-1',
} as const;
