import { ParentPlatform as ParentPlatformValue } from './reference-primitives';
import { route } from './app-game-platform-extension-routing-data-support';

export const IosPlatformExtensionRows = [
  route({
    rowId: 'IOS-01',
    platform: ParentPlatformValue.Ios,
    title: 'FamilyControls authorization UX',
    actionScope: 'policy-handoff',
    authorityTier: 'user-approved-helper',
    setupState: 'permission-required',
    proofGate: 'Entitlement and runtime authorization proof',
    parentVisibleLabel: 'iOS FamilyControls requires entitlement and runtime authorization proof.',
    appGameDifference: 'Game apps use tokens and DeviceActivity data, not raw process inventory.',
    manualTags: ['@requires-familycontrols', '@requires-store-signing'],
    requiredProofKinds: ['permission-setup-proof', 'store-signing-entitlement-proof'],
    storeSigningEntitlementRequired: true,
  }),
  route({
    rowId: 'IOS-02',
    platform: ParentPlatformValue.Ios,
    title: 'FamilyActivityPicker token selection',
    actionScope: 'identity',
    authorityTier: 'user-approved-helper',
    setupState: 'permission-required',
    proofGate: 'Token selection and privacy proof',
    parentVisibleLabel: 'iOS token selection needs privacy proof and cannot reveal raw app inventory.',
    appGameDifference: 'Game identity is token-based and cannot be treated as process evidence.',
    manualTags: ['@requires-familycontrols'],
    requiredProofKinds: ['permission-setup-proof', 'manual-platform-proof'],
  }),
  route({
    rowId: 'IOS-03',
    platform: ParentPlatformValue.Ios,
    title: 'DeviceActivity schedule/threshold monitor',
    actionScope: 'time-budget',
    authorityTier: 'supervised-device',
    setupState: 'supervision-required',
    proofGate: 'DeviceActivity callback proof',
    parentVisibleLabel: 'DeviceActivity budgets need callback proof and supervised or authorized setup.',
    appGameDifference: 'Game budget proof uses app/category tokens, not running-process duration.',
    manualTags: ['@requires-familycontrols'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'IOS-04',
    platform: ParentPlatformValue.Ios,
    title: 'ManagedSettings app/category shield adapter',
    actionScope: 'shield-app',
    authorityTier: 'supervised-device',
    setupState: 'supervision-required',
    proofGate: 'Shield action proof',
    parentVisibleLabel: 'ManagedSettings shield claims need authorization, shield action, rollback, and audit proof.',
    appGameDifference: 'Game app shielding needs game token/category proof plus parent-visible exception state.',
    manualTags: ['@requires-familycontrols', '@requires-managedsettings'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'IOS-05',
    platform: ParentPlatformValue.Ios,
    title: 'Shield UI and child request flow',
    actionScope: 'warn-ask',
    authorityTier: 'supervised-device',
    setupState: 'supervision-required',
    proofGate: 'Screenshot and approval proof',
    parentVisibleLabel: 'iOS shield UI needs screenshot, approval, expiry, and audit proof.',
    appGameDifference: 'Game request copy must stay evidence-backed and avoid content claims.',
    manualTags: ['@requires-familycontrols', '@requires-managedsettings'],
    requiredProofKinds: ['ui-proof', 'manual-platform-proof', 'permission-setup-proof'],
  }),
  route({
    rowId: 'IOS-06',
    platform: ParentPlatformValue.Ios,
    title: 'Token-based app identity model',
    actionScope: 'identity',
    authorityTier: 'observe-only',
    setupState: 'permission-required',
    proofGate: 'No raw app inventory proof',
    parentVisibleLabel: 'iOS app identity is token-based and must prove no raw inventory leakage.',
    appGameDifference: 'Game tokens need separate game/category explanation from native app identity.',
    manualTags: ['@requires-familycontrols'],
    requiredProofKinds: ['security-negative-proof', 'permission-setup-proof'],
  }),
  route({
    rowId: 'IOS-07',
    platform: ParentPlatformValue.Ios,
    title: 'iOS MDM installed-app query mode',
    actionScope: 'inventory',
    authorityTier: 'mdm-enrolled',
    setupState: 'mdm-required',
    proofGate: 'MDM query artifact',
    parentVisibleLabel: 'iOS installed-app query is managed-device-only and needs MDM query proof.',
    appGameDifference: 'MDM game inventory is not usage or content proof.',
    manualTags: ['@requires-mdm'],
    requiredProofKinds: ['authority-tier-proof', 'runtime-evidence-proof'],
  }),
  route({
    rowId: 'IOS-08',
    platform: ParentPlatformValue.Ios,
    title: 'Supervised-device restriction matrix',
    actionScope: 'policy-handoff',
    authorityTier: 'supervised-device',
    setupState: 'supervision-required',
    proofGate: 'Supervision/MDM proof',
    parentVisibleLabel: 'Supervised-device restrictions need supervision or MDM proof before product claims.',
    appGameDifference: 'Restrictions can route game categories only when token/category proof exists.',
    manualTags: ['@requires-mdm'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof'],
  }),
  route({
    rowId: 'IOS-09',
    platform: ParentPlatformValue.Ios,
    title: 'App Lock / Single App Mode proof',
    actionScope: 'single-app-mode',
    authorityTier: 'kiosk-or-single-app',
    setupState: 'kiosk-required',
    proofGate: 'App Lock payload proof',
    parentVisibleLabel: 'App Lock and Single App Mode need kiosk payload, setup, rollback, and audit proof.',
    appGameDifference: 'Single-app mode is device state, not a per-game gameplay classifier.',
    manualTags: ['@requires-kiosk', '@requires-mdm'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'IOS-10',
    platform: ParentPlatformValue.Ios,
    title: 'iOS exception/approval flow',
    actionScope: 'warn-ask',
    authorityTier: 'supervised-device',
    setupState: 'supervision-required',
    proofGate: 'Approval expiry and audit proof',
    parentVisibleLabel: 'iOS approval exceptions need expiry, audit, shield state, and parent response proof.',
    appGameDifference: 'Game exceptions must cite token/category and budget evidence refs.',
    manualTags: ['@requires-familycontrols', '@requires-managedsettings'],
    requiredProofKinds: ['manual-platform-proof', 'policy-action-proof', 'ui-proof'],
  }),
  route({
    rowId: 'IOS-11',
    platform: ParentPlatformValue.Ios,
    title: 'iOS manual-required fallback labels',
    actionScope: 'policy-handoff',
    authorityTier: 'manual-required',
    setupState: 'manual-required',
    proofGate: 'UI proof for unavailable states',
    parentVisibleLabel: 'iOS unavailable states must show permission, supervision, MDM, or not-claimed labels.',
    appGameDifference: 'Game UI must keep shield unavailable separate from unknown-game evidence.',
    requiredProofKinds: ['ui-proof', 'manual-platform-proof'],
  }),
  route({
    rowId: 'IOS-12',
    platform: ParentPlatformValue.Ios,
    title: 'iOS store/signing/entitlement proof',
    actionScope: 'store-signing',
    authorityTier: 'manual-required',
    setupState: 'manual-required',
    proofGate: 'TestFlight/device/App Store proof',
    parentVisibleLabel: 'iOS capability claims need signing, entitlement, TestFlight/device, or store proof.',
    appGameDifference: 'Game shielding and approval claims cannot move up without the same entitlement proof.',
    manualTags: ['@requires-store-signing'],
    requiredProofKinds: ['store-signing-entitlement-proof', 'manual-platform-proof'],
    storeSigningEntitlementRequired: true,
  }),
] as const;
