import { ParentPlatform as ParentPlatformValue } from './reference-primitives';
import { route } from './app-game-platform-extension-routing-data-support';

export const MacosPlatformExtensionRows = [
  route({
    rowId: 'MAC-01',
    platform: ParentPlatformValue.Macos,
    title: 'App bundle inventory adapter',
    actionScope: 'inventory',
    authorityTier: 'observe-only',
    setupState: 'not-required',
    proofGate: 'Fixture and manual host proof',
    parentVisibleLabel: 'macOS bundle inventory is observe-only until fixture and host proof are attached.',
    appGameDifference: 'Native games use the same bundle evidence but still need launcher-child-game proof.',
  }),
  route({
    rowId: 'MAC-02',
    platform: ParentPlatformValue.Macos,
    title: 'LaunchServices/Spotlight inventory adapter',
    actionScope: 'inventory',
    authorityTier: 'observe-only',
    setupState: 'permission-required',
    proofGate: 'Metadata fixture and privacy proof',
    parentVisibleLabel: 'LaunchServices and Spotlight metadata need privacy proof before product inventory claims.',
    appGameDifference: 'Launcher metadata cannot promote installed launchers into played-game evidence.',
  }),
  route({
    rowId: 'MAC-03',
    platform: ParentPlatformValue.Macos,
    title: 'NSWorkspace running app adapter',
    actionScope: 'runtime',
    authorityTier: 'user-approved-helper',
    setupState: 'helper-required',
    proofGate: 'Real macOS host proof',
    parentVisibleLabel: 'Running app evidence requires a user-approved helper and real macOS host proof.',
    appGameDifference: 'Running game-like processes stay runtime evidence, not content or known-game proof.',
  }),
  route({
    rowId: 'MAC-04',
    platform: ParentPlatformValue.Macos,
    title: 'Accessibility foreground/window adapter',
    actionScope: 'foreground',
    authorityTier: 'accessibility-assisted',
    setupState: 'permission-required',
    proofGate: 'Permission prompt and foreground proof',
    parentVisibleLabel: 'Foreground evidence requires explicit Accessibility permission proof.',
    appGameDifference: 'Foreground launcher windows do not prove child-game content.',
    manualTags: ['@requires-accessibility'],
    requiredProofKinds: ['permission-setup-proof', 'runtime-evidence-proof'],
  }),
  route({
    rowId: 'MAC-05',
    platform: ParentPlatformValue.Macos,
    title: 'Code signature/team-id identity adapter',
    actionScope: 'identity',
    authorityTier: 'observe-only',
    setupState: 'not-required',
    proofGate: 'Signature fixture and invalid-state proof',
    parentVisibleLabel: 'Signature identity is a candidate identity signal until invalid-state proof is attached.',
    appGameDifference: 'Game publisher/team ids remain category evidence, not policy authority.',
  }),
  route({
    rowId: 'MAC-06',
    platform: ParentPlatformValue.Macos,
    title: 'LaunchAgent/LaunchDaemon service model',
    actionScope: 'runtime',
    authorityTier: 'root-or-admin-service',
    setupState: 'admin-or-root-required',
    proofGate: 'Service install/restart proof',
    parentVisibleLabel: 'macOS service persistence needs admin setup, restart, audit, and rollback proof.',
    appGameDifference: 'Service persistence cannot add hard game blocking without separate platform proof.',
    manualTags: ['@requires-admin-root'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'MAC-07',
    platform: ParentPlatformValue.Macos,
    title: 'PPPC profile for Accessibility/Automation permissions',
    actionScope: 'policy-handoff',
    authorityTier: 'mdm-enrolled',
    setupState: 'mdm-required',
    proofGate: 'Profile payload/manual proof',
    parentVisibleLabel: 'PPPC permission routing requires MDM profile payload and manual host proof.',
    appGameDifference: 'Game control uses the same permission route but still needs app/game evidence refs.',
    manualTags: ['@requires-mdm'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof'],
  }),
  route({
    rowId: 'MAC-08',
    platform: ParentPlatformValue.Macos,
    title: 'MDM installed-app query proof',
    actionScope: 'inventory',
    authorityTier: 'mdm-enrolled',
    setupState: 'mdm-required',
    proofGate: 'MDM query artifact',
    parentVisibleLabel: 'MDM installed-app query claims need enrollment and MDM query artifacts.',
    appGameDifference: 'MDM app inventory cannot imply game play or foreground duration.',
    manualTags: ['@requires-mdm'],
    requiredProofKinds: ['authority-tier-proof', 'runtime-evidence-proof'],
  }),
  route({
    rowId: 'MAC-09',
    platform: ParentPlatformValue.Macos,
    title: 'Parental Controls payload proof',
    actionScope: 'block-launch',
    authorityTier: 'mdm-enrolled',
    setupState: 'mdm-required',
    proofGate: 'Managed Mac payload artifact',
    parentVisibleLabel: 'Managed Mac payload control needs enrollment, action, rollback, and audit proof.',
    appGameDifference: 'Native game blocking through payloads must still cite game identity and rollback proof.',
    manualTags: ['@requires-mdm'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'MAC-10',
    platform: ParentPlatformValue.Macos,
    title: 'Endpoint Security feasibility/proof',
    actionScope: 'block-launch',
    authorityTier: 'system-extension',
    setupState: 'system-extension-required',
    proofGate: 'Entitlement/signing/system-extension proof',
    parentVisibleLabel:
      'Endpoint Security hard control needs entitlement, signing, system extension, and rollback proof.',
    appGameDifference: 'Endpoint Security cannot classify game content; it can only route proved executable control.',
    manualTags: ['@requires-system-extension', '@requires-store-signing'],
    requiredProofKinds: [
      'authority-tier-proof',
      'permission-setup-proof',
      'rollback-proof',
      'store-signing-entitlement-proof',
    ],
    storeSigningEntitlementRequired: true,
  }),
  route({
    rowId: 'MAC-11',
    platform: ParentPlatformValue.Macos,
    title: 'macOS terminate/quit adapter',
    actionScope: 'terminate-process',
    authorityTier: 'user-approved-helper',
    setupState: 'helper-required',
    proofGate: 'Target recheck and rollback proof',
    parentVisibleLabel: 'macOS quit/terminate needs target recheck, action, rollback, and audit proof.',
    appGameDifference: 'Game termination needs current owned process proof, not just bundle inventory.',
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
  route({
    rowId: 'MAC-12',
    platform: ParentPlatformValue.Macos,
    title: 'macOS hard-block manual proof gate',
    actionScope: 'block-launch',
    authorityTier: 'system-extension',
    setupState: 'system-extension-required',
    proofGate: 'Explicit no-claim until real proof',
    parentVisibleLabel:
      'macOS hard block remains manual-required until MDM, Endpoint Security, or System Extension proof exists.',
    appGameDifference: 'Hard game block needs the same authority plus game identity, rollback, and audit proof.',
    manualTags: ['@requires-system-extension'],
    requiredProofKinds: ['authority-tier-proof', 'permission-setup-proof', 'rollback-proof'],
  }),
] as const;
