import { AppGameInstallStoreHandoffMatrixSchema } from './app-game-install-store-handoff';

const evidence = (evidenceReferenceId: string, observedAt: string) => ({
  evidenceReferenceId,
  kind: 'journal-event',
  observedAt,
});

const commonProofPackRefs = [
  'output/app-game-plan-proof/26-install-uninstall-purchase-store-handoffs',
  'output/app-plan-proof/25-install-and-uninstall-approval-handoff',
];

const AppGameInstallStoreHandoffProofMatrixCandidate = {
  schemaVersion: 'v0.6',
  matrixId: 'app-game-install-store-handoff-proof',
  generatedAt: '2026-06-03T12:11:00.000Z',
  rows: [
    {
      schemaVersion: 'app-game-install-store-handoff-proof',
      handoffId: 'new-app-inventory-review-handoff',
      productSlice: 'native-app',
      signalKind: 'new-inventory-detected',
      platform: 'windows',
      storeSurface: 'parent-manual-entry',
      decisionAuthority: 'approval-feature-handoff',
      storeSignalUse: 'not-store-signal',
      approvalSupportState: 'manual-required',
      capabilityState: 'observe-only',
      approvalRequestRef: 'approval-request:new-app-inventory-review',
      evidenceReferences: [evidence('evidence:new-app-inventory-delta', '2026-06-03T12:00:00.000Z')],
      destinationFeatureDocs: ['docs/features/app-game-control.md', 'docs/features/app-install-purchase-approval.md'],
      expectationDocRefs: [
        'docs/expectations/app-game-evidence.md',
        'docs/expectations/app-install-purchase-approval.md',
      ],
      manualRequirement: 'parent approval UI and platform source proof are still required',
      parentVisibleManualState: 'New app is review-needed with source evidence, not blocked automatically.',
      noClaimBoundaries: [
        'inventory-is-not-use',
        'not-generic-app-blocking',
        'no-store-interception',
        'no-platform-adapter-execution',
      ],
      proofPackRefs: commonProofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      policyDecisionClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:00:00.000Z',
    },
    {
      schemaVersion: 'app-game-install-store-handoff-proof',
      handoffId: 'installer-updater-process-review-handoff',
      productSlice: 'shared-app-game',
      signalKind: 'installer-updater-process',
      platform: 'windows',
      storeSurface: 'unknown-store',
      decisionAuthority: 'approval-feature-handoff',
      storeSignalUse: 'not-store-signal',
      approvalSupportState: 'manual-required',
      capabilityState: 'observe-only',
      approvalRequestRef: 'approval-request:installer-updater-process',
      evidenceReferences: [evidence('evidence:installer-updater-process', '2026-06-03T12:01:00.000Z')],
      destinationFeatureDocs: ['docs/features/app-game-control.md', 'docs/features/app-install-purchase-approval.md'],
      expectationDocRefs: [
        'docs/expectations/app-game-evidence.md',
        'docs/expectations/app-install-purchase-approval.md',
      ],
      manualRequirement: 'installer process evidence needs source verification before approval or enforcement',
      parentVisibleManualState: 'Installer or updater detected; parent review is required before any claim.',
      noClaimBoundaries: [
        'inventory-is-not-use',
        'not-generic-app-blocking',
        'no-store-interception',
        'no-platform-adapter-execution',
      ],
      proofPackRefs: commonProofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      policyDecisionClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:01:00.000Z',
    },
    {
      schemaVersion: 'app-game-install-store-handoff-proof',
      handoffId: 'store-package-install-context-handoff',
      productSlice: 'native-app',
      signalKind: 'store-package-install',
      platform: 'windows',
      storeSurface: 'microsoft-store',
      decisionAuthority: 'approval-feature-handoff',
      storeSignalUse: 'context-only-not-decision',
      approvalSupportState: 'manual-required',
      capabilityState: 'manual-required',
      approvalRequestRef: 'approval-request:store-package-install',
      evidenceReferences: [evidence('evidence:microsoft-store-package-row', '2026-06-03T12:02:00.000Z')],
      destinationFeatureDocs: ['docs/features/app-game-control.md', 'docs/features/app-install-purchase-approval.md'],
      expectationDocRefs: [
        'docs/expectations/app-game-evidence.md',
        'docs/expectations/app-install-purchase-approval.md',
      ],
      manualRequirement: 'Microsoft Store API or approved source proof is required before interception claims',
      parentVisibleManualState: 'Store package signal is context for review, not an automatic safety decision.',
      noClaimBoundaries: [
        'inventory-is-not-use',
        'store-signal-not-safety-decision',
        'not-generic-app-blocking',
        'no-store-interception',
        'no-platform-adapter-execution',
      ],
      proofPackRefs: commonProofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      policyDecisionClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:02:00.000Z',
    },
    {
      schemaVersion: 'app-game-install-store-handoff-proof',
      handoffId: 'native-game-purchase-signal-handoff',
      productSlice: 'native-game',
      signalKind: 'game-purchase-signal',
      platform: 'windows',
      storeSurface: 'unknown-store',
      decisionAuthority: 'approval-feature-handoff',
      storeSignalUse: 'context-only-not-decision',
      approvalSupportState: 'manual-required',
      capabilityState: 'manual-required',
      approvalRequestRef: 'approval-request:native-game-purchase-signal',
      evidenceReferences: [evidence('evidence:native-game-purchase-capability', '2026-06-03T12:03:00.000Z')],
      destinationFeatureDocs: ['docs/features/app-game-control.md', 'docs/features/app-install-purchase-approval.md'],
      expectationDocRefs: [
        'docs/expectations/app-game-evidence.md',
        'docs/expectations/app-install-purchase-approval.md',
      ],
      manualRequirement: 'purchase signals need store metadata and approval proof before parent decisions',
      parentVisibleManualState: 'Game purchase signal is advisory context and stays outside billing entitlement logic.',
      noClaimBoundaries: [
        'store-signal-not-safety-decision',
        'not-generic-app-blocking',
        'no-store-interception',
        'no-platform-adapter-execution',
        'no-billing-entitlement-logic',
      ],
      proofPackRefs: commonProofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      policyDecisionClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:03:00.000Z',
    },
    {
      schemaVersion: 'app-game-install-store-handoff-proof',
      handoffId: 'uninstall-detected-tamper-handoff',
      productSlice: 'native-app',
      signalKind: 'uninstall-detected',
      platform: 'windows',
      storeSurface: 'parent-manual-entry',
      decisionAuthority: 'tamper-uninstall-feature-handoff',
      storeSignalUse: 'not-store-signal',
      approvalSupportState: 'manual-required',
      capabilityState: 'manual-required',
      approvalRequestRef: null,
      evidenceReferences: [evidence('evidence:stale-inventory-uninstall-delta', '2026-06-03T12:04:00.000Z')],
      destinationFeatureDocs: ['docs/features/app-game-control.md', 'docs/features/enforcement-integrity-tamper.md'],
      expectationDocRefs: [
        'docs/expectations/app-game-evidence.md',
        'docs/expectations/tamper-uninstall-protection.md',
      ],
      manualRequirement: 'uninstall detection requires tamper artifact proof before protection claims',
      parentVisibleManualState:
        'App disappeared from inventory; route to integrity review without child-intent claims.',
      noClaimBoundaries: ['inventory-is-not-use', 'no-platform-adapter-execution', 'no-tamper-blocking'],
      proofPackRefs: commonProofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      policyDecisionClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:04:00.000Z',
    },
    {
      schemaVersion: 'app-game-install-store-handoff-proof',
      handoffId: 'tamper-uninstall-candidate-manual-handoff',
      productSlice: 'shared-app-game',
      signalKind: 'tamper-uninstall-candidate',
      platform: 'android',
      storeSurface: 'google-play',
      decisionAuthority: 'tamper-uninstall-feature-handoff',
      storeSignalUse: 'not-store-signal',
      approvalSupportState: 'manual-required',
      capabilityState: 'manual-required',
      approvalRequestRef: null,
      evidenceReferences: [evidence('evidence:android-package-artifact-gap', '2026-06-03T12:05:00.000Z')],
      destinationFeatureDocs: ['docs/features/app-game-control.md', 'docs/features/enforcement-integrity-tamper.md'],
      expectationDocRefs: [
        'docs/expectations/app-game-evidence.md',
        'docs/expectations/tamper-uninstall-protection.md',
        'docs/expectations/enforcement.md',
      ],
      manualRequirement: 'Device Owner/Profile Owner proof is required before uninstall-block claims',
      parentVisibleManualState: 'Tamper or uninstall candidate is manual-required until platform artifacts are proved.',
      noClaimBoundaries: ['inventory-is-not-use', 'no-platform-adapter-execution', 'no-tamper-blocking'],
      proofPackRefs: commonProofPackRefs,
      adapterExecutionClaim: 'not-claimed',
      policyDecisionClaim: 'not-claimed',
      recordedAt: '2026-06-03T12:05:00.000Z',
    },
  ],
} as const;

export const AppGameInstallStoreHandoffProofMatrix = AppGameInstallStoreHandoffMatrixSchema.parse(
  AppGameInstallStoreHandoffProofMatrixCandidate
);
