export type AppControlCatalogSettingSeed = readonly [
  sectionId: string,
  sectionTitle: string,
  policyLane: string,
  groupId: string,
  groupTitle: string,
  settingId: string,
  controlKind: string,
  uiQuestionText: string,
  writesTo: string,
  effectStatus: string,
  runtimeOwner: string,
  capabilityState: string,
  capabilityRequirement: string | null,
  proofRequirement: string | null,
  unsafeOrUnsupportedFallback: string | null,
  options: readonly AppControlCatalogOptionSeed[],
  defaultValue: AppControlCatalogDefaultValue,
];

export type AppControlGuideCatalogSettingSeed = readonly [
  sectionId: string,
  sectionTitle: string,
  sectionOrder: number,
  groupId: string,
  groupTitle: string,
  groupOrder: number,
  settingId: string,
  sourceOrder: number,
  sourceLine: number,
  sourceText: string,
];

export type AppControlCatalogOptionSeed =
  | string
  | {
      readonly value: string;
      readonly label: string;
      readonly meaning?: string;
    };

export type AppControlCatalogDefaultValue = string | number | boolean | readonly string[] | null;

export type AppControlCapabilitySeed = readonly [
  capabilityId: string,
  state: string,
  proof: string,
  source: string,
  affectsSettings: readonly string[],
];

export const AppControlCatalogSourceDocuments = [
  'docs/app-control-capability-guide.md',
  'docs/app-control-schema-proposal.md',
] as const;

export const AppControlTargetScopeSeeds = ['family', 'per-child', 'per-device', 'per-platform', 'per-app'] as const;

export const AppControlEffectModeSeeds = [
  'off',
  'observe',
  'dry-run',
  'warn',
  'notify',
  'ask',
  'limit',
  'block',
  'enforce',
  'audit-only',
] as const;

export const AppControlCatalogSettingSeeds: readonly AppControlCatalogSettingSeed[] = [
  [
    'app-management',
    'App management',
    'rules',
    'app-management-defaults',
    'Default posture',
    'app.enabled',
    'toggle',
    'Enable app management?',
    '/appPolicy/enabled',
    'already-represented',
    'parent-domain',
    'available',
    null,
    null,
    'Native app controls stay disabled until a parent enables this policy document.',
    [],
    false,
  ],
  [
    'app-management',
    'App management',
    'rules',
    'app-management-defaults',
    'Default posture',
    'app.defaultPosture',
    'single-choice',
    'What should happen to app activity?',
    '/appPolicy/defaultPosture',
    'proof-required',
    'child-agent',
    'protected',
    'runtime app evidence plus strict-action capability proof',
    'Blocking is product-true only when the target platform adapter proves it.',
    'Degrade block posture to ask, warn, or unavailable reporting when broad app blocking is not proven.',
    [
      { value: 'allow', label: 'Allow', meaning: 'App activity is allowed unless a more specific rule changes it.' },
      {
        value: 'observe',
        label: 'Observe',
        meaning: 'App activity is allowed and decisions are report-only.',
      },
      { value: 'warn', label: 'Warn', meaning: 'Matching app activity warns the child and records events.' },
      { value: 'ask', label: 'Ask', meaning: 'Matching app activity needs parent approval.' },
      { value: 'limit', label: 'Limit', meaning: 'App activity is allowed inside configured schedules and budgets.' },
      {
        value: 'block',
        label: 'Block',
        meaning: 'Blocking applies only when platform capability proof exists.',
      },
    ],
    'observe',
  ],
  [
    'app-management',
    'App management',
    'rules',
    'app-management-defaults',
    'Default posture',
    'app.managementMode',
    'single-choice',
    'How should app management run on this device?',
    '/appPolicy/managementMode',
    'already-represented',
    'child-agent',
    'available',
    'local child-agent or LAN service route',
    'Portal authoring alone must not claim runtime enforcement.',
    'Show authoring-only or unavailable when no child-agent route exists.',
    ['local-child-agent', 'lan-live', 'authoring-only', 'unavailable'],
    'local-child-agent',
  ],
  [
    'inventory',
    'Installed apps',
    'evidence',
    'inventory-sources',
    'Inventory sources',
    'inventory.mode',
    'single-choice',
    'How should installed app inventory be used?',
    '/appPolicy/inventory/mode',
    'needs-effect-wiring',
    'child-agent',
    'permission-limited',
    'installed app inventory adapter',
    'Inventory is not proof of current use.',
    'Keep app activity unknown when inventory is missing or stale.',
    ['disabled', 'reports-only', 'use-for-matching-and-reports', 'required-for-strict-rules'],
    'use-for-matching-and-reports',
  ],
  [
    'inventory',
    'Installed apps',
    'evidence',
    'inventory-sources',
    'Inventory sources',
    'inventory.sources',
    'multi-choice',
    'Which app inventory sources are allowed?',
    '/appPolicy/inventory/sources',
    'permission-limited',
    'os-adapter',
    'permission-limited',
    'platform inventory source visibility',
    'Portable, privacy-hidden, and mobile-tokenized apps may be absent.',
    'Do not infer unlisted apps are absent or safe.',
    [
      'os-installed-apps',
      'desktop-shortcuts',
      'store-packages',
      'package-manager',
      'managed-device-apps',
      'screen-time-tokens',
      'executable-metadata',
      'parent-catalog',
    ],
    ['os-installed-apps', 'desktop-shortcuts', 'store-packages', 'executable-metadata', 'parent-catalog'],
  ],
  [
    'inventory',
    'Installed apps',
    'evidence',
    'inventory-identity',
    'Identity strategy',
    'inventory.identityFields',
    'multi-choice',
    'Which identity fields may app rules use?',
    '/appPolicy/inventory/identityFields',
    'proof-required',
    'child-agent',
    'protected',
    'typed app identity evidence',
    'No single identity field proves an app on every platform.',
    'Keep unknown identity state when deterministic proof is unavailable.',
    [
      'package-id',
      'bundle-id',
      'app-user-model-id',
      'desktop-entry-id',
      'application-token',
      'executable-path',
      'publisher-signature',
      'file-hash',
      'display-name',
      'parent-label',
    ],
    ['package-id', 'bundle-id', 'app-user-model-id', 'executable-path', 'publisher-signature', 'file-hash'],
  ],
  [
    'inventory',
    'Installed apps',
    'rules',
    'inventory-identity',
    'Identity strategy',
    'inventory.unknownHandling',
    'single-choice',
    'What should happen when an app cannot be identified?',
    '/appPolicy/inventory/unknownHandling',
    'already-represented',
    'parent-domain',
    'available',
    'unknown app policy state',
    'Unknown apps must remain labeled unknown.',
    'Never promote unknown apps to known, risky, blocked, or game without proof.',
    ['allow', 'observe', 'warn', 'ask', 'count-under-unknown-budget', 'block-if-supported'],
    'observe',
  ],
  [
    'runtime-evidence',
    'Runtime evidence',
    'evidence',
    'runtime-sources',
    'Runtime sources',
    'evidence.runtimeSources',
    'multi-choice',
    'Which runtime evidence sources may be used?',
    '/appPolicy/evidence/runtimeSources',
    'permission-required',
    'os-adapter',
    'permission-required',
    'process, foreground, usage, or managed-device adapter permissions',
    'Foreground evidence and mobile usage visibility are platform-permission dependent.',
    'Report unavailable instead of counting portal polling as child activity.',
    [
      'process-snapshot',
      'process-start-exit',
      'foreground-window',
      'usage-stats',
      'device-activity',
      'managed-device-state',
      'accessibility-approved-state',
      'app-session-summary',
    ],
    ['process-snapshot', 'process-start-exit', 'foreground-window', 'app-session-summary'],
  ],
  [
    'runtime-evidence',
    'Runtime evidence',
    'evidence',
    'runtime-proof',
    'Runtime proof',
    'evidence.requiredProof',
    'single-choice',
    'What proof is enough for app rules?',
    '/appPolicy/evidence/requiredProof',
    'proof-required',
    'child-agent',
    'protected',
    'fresh app evidence reference',
    'Inventory-only proof cannot justify strict runtime action.',
    'Degrade strict actions until fresh runtime or managed-device proof exists.',
    [
      'inventory-only',
      'process-running',
      'foreground-window',
      'fresh-app-session',
      'platform-usage-event',
      'managed-device-state',
    ],
    'fresh-app-session',
  ],
  [
    'runtime-evidence',
    'Runtime evidence',
    'schedule',
    'duration-proof',
    'Duration proof',
    'evidence.durationMode',
    'single-choice',
    'Which duration should time budgets count?',
    '/appPolicy/evidence/durationMode',
    'proof-required',
    'child-agent',
    'protected',
    'ordered runtime or foreground app-session evidence',
    'Portal refresh cadence must not count as child activity.',
    'Treat observation gaps and restarts as gaps unless replay or platform events prove continuity.',
    ['running-time', 'foreground-time', 'platform-usage-time', 'manual-review-only'],
    'foreground-time',
  ],
  [
    'runtime-evidence',
    'Runtime evidence',
    'evidence',
    'runtime-proof',
    'Runtime proof',
    'evidence.whenProofUnavailable',
    'single-choice',
    'What if app proof is unavailable?',
    '/appPolicy/evidence/whenProofUnavailable',
    'already-represented',
    'parent-domain',
    'available',
    'fallback policy state',
    'Unavailable proof is a parent-visible state, not a hidden allow or block.',
    'Mark unavailable when proof cannot support the selected strict action.',
    ['allow', 'observe', 'warn', 'ask', 'block-until-ready', 'mark-unavailable'],
    'mark-unavailable',
  ],
  [
    'runtime-evidence',
    'Runtime evidence',
    'audit',
    'data-minimization',
    'Data minimization',
    'evidence.neverCollect',
    'multi-choice',
    'What must app controls never collect?',
    '/appPolicy/evidence/neverCollect',
    'already-represented',
    'parent-domain',
    'protected',
    'privacy and redaction boundary',
    'App evidence does not prove content, keystrokes, screenshots, or chat text.',
    'Exclude raw sensitive fields and keep reports evidence-reference based.',
    [
      'screen-contents',
      'screenshots',
      'keystrokes',
      'chat-content',
      'voice-content',
      'app-internal-documents',
      'launcher-credentials',
      'decrypted-network-payload',
      'raw-command-line-with-secrets',
    ],
    [
      'screen-contents',
      'screenshots',
      'keystrokes',
      'chat-content',
      'voice-content',
      'app-internal-documents',
      'launcher-credentials',
      'decrypted-network-payload',
    ],
  ],
  [
    'app-rules',
    'App rules',
    'rules',
    'rule-targets',
    'Rule targets',
    'rules.allowedTargetTypes',
    'multi-choice',
    'What app targets should rules match?',
    '/appPolicy/rules/allowedTargetTypes',
    'proof-required',
    'child-agent',
    'protected',
    'typed app identity and category match strategy',
    'Unknown, helper, wrapper, and renamed apps require honest confidence state.',
    'Keep exact app control disabled when targets cannot be matched deterministically.',
    [
      'app-ref',
      'app-category',
      'package-id',
      'bundle-id',
      'application-token',
      'executable-identity',
      'publisher-signature',
      'unknown-app',
      'managed-app-state',
      'app-session',
      'capability-state',
    ],
    ['app-ref', 'app-category', 'executable-identity', 'unknown-app', 'app-session', 'capability-state'],
  ],
  [
    'app-rules',
    'App rules',
    'rules',
    'unknown-apps',
    'Unknown apps',
    'rules.defaultUnknownRule',
    'single-choice',
    'Default rule for unknown apps?',
    '/appPolicy/rules/defaultUnknownRule',
    'proof-required',
    'child-agent',
    'protected',
    'unknown app fallback policy',
    'Unknown remains unknown until adapter evidence maps it confidently.',
    'Use ask, warn, or limit fallback before unsupported broad blocking.',
    ['allow', 'observe', 'warn', 'ask-first-run', 'limit', 'block-if-supported'],
    'ask-first-run',
  ],
  [
    'app-rules',
    'App rules',
    'rules',
    'rule-targets',
    'Rule targets',
    'rules.matchConfidenceRequired',
    'single-choice',
    'How strong must an app match be before strict action?',
    '/appPolicy/rules/matchConfidenceRequired',
    'already-represented',
    'parent-domain',
    'available',
    'app identity confidence threshold',
    'Strict action requires deterministic or approved app identity proof.',
    'Fall back to parent approval when confidence is below threshold.',
    ['any-candidate', 'catalog-confidence-high', 'deterministic-or-parent-approved', 'managed-device-proof'],
    'deterministic-or-parent-approved',
  ],
  [
    'budgets',
    'App time limits',
    'schedule',
    'time-budgets',
    'Time budgets',
    'budgets.enabled',
    'toggle',
    'Enable app time budgets?',
    '/appPolicy/budgets/enabled',
    'already-represented',
    'child-agent',
    'available',
    'local timer state and app-session evidence',
    'Budgets need child-agent timer state, not portal-rendered time.',
    'Disable app budgets when no runtime evidence source is available.',
    [],
    true,
  ],
  [
    'budgets',
    'App time limits',
    'schedule',
    'time-budgets',
    'Time budgets',
    'budgets.defaultDailyMinutes',
    'number',
    'Default daily app time limit in minutes?',
    '/appPolicy/budgets/defaultDailyMinutes',
    'needs-effect-wiring',
    'child-agent',
    'available',
    'daily app budget policy value',
    'Timer recovery and audit are child-agent responsibilities.',
    'Reject non-positive or non-finite budget values.',
    [],
    60,
  ],
  [
    'budgets',
    'App time limits',
    'schedule',
    'time-budgets',
    'Time budgets',
    'budgets.whenExhausted',
    'single-choice',
    'What happens when app time runs out?',
    '/appPolicy/budgets/whenExhausted',
    'proof-required',
    'child-agent',
    'protected',
    'time-limit action adapter result',
    'Terminate, shield, or block after budget requires platform proof.',
    'Use ask or warn fallback when the strict action is unsupported.',
    ['observe', 'warn', 'ask', 'terminate-if-supported', 'shield-if-supported', 'block-if-supported'],
    'ask',
  ],
  [
    'enforcement',
    'App enforcement',
    'enforcement',
    'strict-actions',
    'Strict actions',
    'enforcement.allowedActions',
    'multi-choice',
    'Which app enforcement actions may run?',
    '/appPolicy/enforcement/allowedActions',
    'manual-required',
    'os-adapter',
    'manual-required',
    'per-platform enforcement adapter capability',
    'Broad app blocking remains manual-required until a real adapter proves it.',
    'Allow only warn, ask, owned-process terminate, and time-limit paths until stricter proof exists.',
    [
      'warn',
      'ask-parent',
      'owned-process-terminate',
      'target-process-terminate',
      'block-launch',
      'shield-app',
      'suspend-package',
      'hide-package',
      'time-limit',
      'managed-install',
      'managed-uninstall',
    ],
    ['warn', 'ask-parent', 'owned-process-terminate', 'time-limit'],
  ],
  [
    'enforcement',
    'App enforcement',
    'enforcement',
    'strict-actions',
    'Strict actions',
    'enforcement.strictActionFallback',
    'single-choice',
    'What if a strict app action is unsupported?',
    '/appPolicy/enforcement/strictActionFallback',
    'already-represented',
    'parent-domain',
    'available',
    'strict action fallback policy',
    'Unsupported strict actions must surface as unavailable or parent-visible fallback.',
    'Never silently claim enforcement when adapter proof is missing.',
    [
      'allow-and-report-unavailable',
      'observe-and-report-unavailable',
      'warn-and-report-unavailable',
      'parent-request-report-unavailable',
      'block-until-ready',
    ],
    'parent-request-report-unavailable',
  ],
  [
    'enforcement',
    'App enforcement',
    'enforcement',
    'strict-actions',
    'Strict actions',
    'enforcement.graceSeconds',
    'number',
    'How long should the child get before strict action applies?',
    '/appPolicy/enforcement/graceSeconds',
    'needs-effect-wiring',
    'child-agent',
    'available',
    'child-agent strict action timer',
    'Grace timers need local runtime and audit state.',
    'Reject negative grace periods and record unavailable when timers cannot run.',
    [],
    15,
  ],
  [
    'enforcement',
    'App enforcement',
    'enforcement',
    'strict-actions',
    'Strict actions',
    'enforcement.requireRollbackPlan',
    'toggle',
    'Require rollback state for strict actions?',
    '/appPolicy/enforcement/requireRollbackPlan',
    'already-represented',
    'rust-service',
    'available',
    'adapter rollback or unavailable state',
    'Strict actions need rollback or explicit unavailable outcome.',
    'Reject strict action plans without audit and rollback/unavailable state.',
    [],
    true,
  ],
  [
    'app-lifecycle',
    'Managed app lifecycle',
    'setup',
    'managed-lifecycle',
    'Managed lifecycle',
    'lifecycle.mode',
    'single-choice',
    'How should app install and uninstall controls be handled?',
    '/appPolicy/lifecycle/mode',
    'manual-required',
    'os-adapter',
    'manual-required',
    'managed device, device-owner, MDM, or approved package lifecycle proof',
    'Personal app install or removal often is not available.',
    'Keep lifecycle controls disabled unless managed-device proof exists.',
    ['disabled', 'report-managed-state', 'managed-apps-only', 'device-owner-or-mdm-only'],
    'disabled',
  ],
  [
    'app-lifecycle',
    'Managed app lifecycle',
    'setup',
    'managed-lifecycle',
    'Managed lifecycle',
    'lifecycle.allowedOperations',
    'multi-choice',
    'Which managed app lifecycle operations are allowed?',
    '/appPolicy/lifecycle/allowedOperations',
    'manual-required',
    'os-adapter',
    'manual-required',
    'managed package lifecycle adapter',
    'Install, uninstall, hide, and suspend depend on platform custody and policy.',
    'Report managed lifecycle as unavailable when the device is not supervised or managed.',
    [
      'install-managed-app',
      'uninstall-managed-app',
      'hide-managed-app',
      'suspend-managed-app',
      'remove-user-installed-app-if-platform-approved',
      'prevent-uninstall-if-platform-approved',
    ],
    [],
  ],
  [
    'approvals',
    'Approvals',
    'approvals',
    'approval-events',
    'Approval events',
    'approvals.requiredFor',
    'multi-choice',
    'Which app events require parent approval?',
    '/appPolicy/approvals/requiredFor',
    'needs-effect-wiring',
    'child-agent',
    'available',
    'parent approval request and audit flow',
    'Approval state is policy data; child-agent still owns local action results.',
    'Queue or deny according to unanswered-default when parent is unavailable.',
    [
      'unknown-app',
      'new-app',
      'blocked-app',
      'time-extension',
      'managed-install',
      'managed-uninstall',
      'strict-action-unavailable',
      'category-override',
    ],
    ['unknown-app', 'time-extension', 'strict-action-unavailable'],
  ],
  [
    'approvals',
    'Approvals',
    'approvals',
    'approval-events',
    'Approval events',
    'approvals.unansweredDefault',
    'single-choice',
    'What happens if the parent does not answer?',
    '/appPolicy/approvals/unansweredDefault',
    'already-represented',
    'parent-domain',
    'available',
    'approval fallback policy',
    'Unanswered approvals must be deterministic and auditable.',
    'Use the configured fallback rather than silently allowing strict action.',
    ['allow', 'deny', 'keep-pending', 'use-rule-fallback'],
    'deny',
  ],
  [
    'reports',
    'Reports',
    'reports',
    'report-fields',
    'Report fields',
    'reports.visibleFields',
    'multi-choice',
    'Which app report fields should be visible?',
    '/appPolicy/reports/visibleFields',
    'already-represented',
    'parent-owned-storage',
    'available',
    'stored evidence references and report read models',
    'Reports must distinguish raw evidence from redacted rollups.',
    'Hide fields whose source capability is unavailable.',
    [
      'installed-apps',
      'running-now',
      'foreground-now',
      'session-rollups',
      'unknown-apps',
      'category-rollups',
      'time-budget',
      'policy-decisions',
      'enforcement-results',
      'approval-events',
      'managed-lifecycle-events',
      'source-capability',
    ],
    [
      'installed-apps',
      'running-now',
      'foreground-now',
      'session-rollups',
      'policy-decisions',
      'enforcement-results',
      'source-capability',
    ],
  ],
  [
    'reports',
    'Reports',
    'audit',
    'retention',
    'Retention',
    'retention.rawObservation',
    'retention',
    'How long should raw app observations be kept?',
    '/appPolicy/retention/rawObservation',
    'already-represented',
    'parent-owned-storage',
    'available',
    'local-first evidence retention policy',
    'Raw app observations should be short-lived and redacted where possible.',
    'Default to local retention and do not upload raw app observations to Ocentra-hosted storage.',
    [],
    '7-days',
  ],
  [
    'reports',
    'Reports',
    'audit',
    'retention',
    'Retention',
    'retention.rollups',
    'retention',
    'How long should app rollups be kept?',
    '/appPolicy/retention/rollups',
    'already-represented',
    'parent-owned-storage',
    'available',
    'local-first report rollup retention policy',
    'Rollups must preserve custody and evidence-reference boundaries.',
    'Delete or export according to parent-owned retention settings.',
    [],
    '30-days',
  ],
] as const;

export const AppControlCapabilitySeeds: readonly AppControlCapabilitySeed[] = [
  [
    'windows-app-inventory',
    'available',
    'runtime-read-model-required',
    'os-installed-apps-and-package-query',
    ['inventory.mode', 'inventory.sources', 'reports.visibleFields'],
  ],
  [
    'windows-process-observation',
    'available',
    'runtime-adapter-proof-required',
    'process-snapshot-and-process-events',
    ['evidence.runtimeSources', 'rules.allowedTargetTypes'],
  ],
  [
    'windows-foreground-window',
    'available',
    'runtime-adapter-proof-required',
    'foreground-window-observation',
    ['evidence.durationMode', 'budgets.enabled', 'budgets.defaultDailyMinutes'],
  ],
  [
    'windows-owned-process-terminate',
    'available',
    'service-proof-required-before-product-claim',
    'owned-process-termination-adapter',
    ['enforcement.allowedActions', 'budgets.whenExhausted'],
  ],
  [
    'windows-target-process-terminate',
    'manual-required',
    'real-host-adapter-proof-required',
    'target-process-termination-adapter',
    ['enforcement.allowedActions', 'rules.defaultUnknownRule'],
  ],
  [
    'windows-broad-app-blocking',
    'manual-required',
    'applocker-wdac-or-equivalent-proof-required',
    'application-control-policy',
    ['app.defaultPosture', 'enforcement.allowedActions'],
  ],
  [
    'android-package-lifecycle',
    'manual-required',
    'device-owner-profile-owner-or-mdm-proof-required',
    'device-policy-manager',
    ['lifecycle.mode', 'lifecycle.allowedOperations', 'enforcement.allowedActions'],
  ],
  [
    'ios-screen-time-shielding',
    'manual-required',
    'family-controls-managed-settings-device-activity-entitlement-proof-required',
    'screen-time-frameworks',
    ['enforcement.allowedActions', 'budgets.whenExhausted', 'rules.allowedTargetTypes'],
  ],
  [
    'macos-managed-app-control',
    'manual-required',
    'mdm-system-extension-or-approved-api-proof-required',
    'macos-managed-device-boundary',
    ['lifecycle.mode', 'enforcement.allowedActions'],
  ],
  [
    'linux-desktop-app-control',
    'manual-required',
    'target-distro-desktop-adapter-proof-required',
    'desktop-entry-package-process-policy',
    ['inventory.sources', 'enforcement.allowedActions'],
  ],
] as const;
