import { type AppGameAiClassifierResult, AppGameAiClassifierResultSchema } from './app-game-ai-classifier-boundary';
import {
  AppGameAiClassifierCandidateKind as CandidateKind,
  AppGameAiClassifierFallbackState as FallbackState,
  AppGameAiClassifierPolicyHandoff as PolicyHandoff,
  AppGameAiClassifierProductKind as ProductKind,
  AppGameAiClassifierSchemaVersion,
  AppGameAiClassifierSourceDigestKind as SourceDigestKind,
  AppGameAiClassifierState as ClassifierState,
} from './app-game-ai-classifier-boundary-values';

const GeneratedAt = '2026-06-03T11:10:00Z';

export const AppGameAiClassifierBoundaryProofMatrix = {
  schemaVersion: AppGameAiClassifierSchemaVersion,
  matrixId: 'app-game-ai-classifier-boundary-proof',
  results: [
    AppGameAiClassifierResultSchema.parse({
      schemaVersion: AppGameAiClassifierSchemaVersion,
      classifierRunId: 'classifier-run-native-app-unknown-1',
      productKind: ProductKind.UnknownApp,
      digestRef: 'ai-digest-native-app-unknown-1',
      sourceDigestKind: SourceDigestKind.InventoryEvidence,
      sourceEvidenceRefs: ['evidence-inventory-unknown-vpn-tool'],
      sourceSessionRefs: [],
      candidateKind: CandidateKind.SafetyCandidate,
      candidateLabel: 'VPN or proxy candidate',
      classifierState: ClassifierState.LowConfidenceCandidate,
      confidence: 0.44,
      uncertaintyReasonCodes: ['weak-name-match', 'unknown-publisher'],
      modelRuntimeRef: 'local-runtime-small-classifier-v1',
      promptTemplateRef: 'prompt-template-app-game-classifier-v1',
      promptVersion: 'prompt-version-2026-06-03',
      fallbackState: FallbackState.LowConfidence,
      policyHandoff: PolicyHandoff.ManualReview,
      generatedAt: GeneratedAt,
      directActionRequested: false,
      rawScanIncluded: false,
      contentClaimIncluded: false,
    }),
    AppGameAiClassifierResultSchema.parse({
      schemaVersion: AppGameAiClassifierSchemaVersion,
      classifierRunId: 'classifier-run-native-game-launcher-1',
      productKind: ProductKind.UnknownGame,
      digestRef: 'ai-digest-native-game-launcher-1',
      sourceDigestKind: SourceDigestKind.LauncherEvidence,
      sourceEvidenceRefs: ['evidence-launcher-candidate-steam-child-game'],
      sourceSessionRefs: ['session-launcher-child-game-1'],
      candidateKind: CandidateKind.GameContextCandidate,
      candidateLabel: 'Launcher child-game candidate',
      classifierState: ClassifierState.Candidate,
      confidence: 0.71,
      uncertaintyReasonCodes: ['launcher-child-process-unverified'],
      modelRuntimeRef: 'local-runtime-small-classifier-v1',
      promptTemplateRef: 'prompt-template-app-game-classifier-v1',
      promptVersion: 'prompt-version-2026-06-03',
      fallbackState: FallbackState.NotNeeded,
      policyHandoff: PolicyHandoff.PolicyPreviewOnly,
      generatedAt: GeneratedAt,
      directActionRequested: false,
      rawScanIncluded: false,
      contentClaimIncluded: false,
    }),
    AppGameAiClassifierResultSchema.parse({
      schemaVersion: AppGameAiClassifierSchemaVersion,
      classifierRunId: 'classifier-run-provider-unavailable-1',
      productKind: ProductKind.NativeApp,
      digestRef: 'ai-digest-provider-unavailable-1',
      sourceDigestKind: SourceDigestKind.SessionSummary,
      sourceEvidenceRefs: ['evidence-session-summary-native-app-1'],
      sourceSessionRefs: ['session-native-app-1'],
      candidateKind: CandidateKind.PolicyEvidenceCandidate,
      candidateLabel: 'Provider unavailable candidate',
      classifierState: ClassifierState.ProviderUnavailable,
      confidence: 0,
      uncertaintyReasonCodes: ['local-model-unavailable'],
      modelRuntimeRef: 'local-runtime-unavailable',
      promptTemplateRef: 'prompt-template-app-game-classifier-v1',
      promptVersion: 'prompt-version-2026-06-03',
      fallbackState: FallbackState.LocalModelUnavailable,
      policyHandoff: PolicyHandoff.ParentReview,
      generatedAt: GeneratedAt,
      directActionRequested: false,
      rawScanIncluded: false,
      contentClaimIncluded: false,
    }),
  ] satisfies readonly AppGameAiClassifierResult[],
} as const;
