import * as Domain from '@ocentra-parent/billing-domain/billing-account-runtime-boundary';
import * as DomainValues from '@ocentra-parent/billing-domain/billing-account-runtime-boundary-values';

export const BillingAccountRuntimeSchemaVersionSchema =
  DomainValues.BillingAccountRuntimeSchemaVersionSchema;
export const BillingAccountRuntimeStatusSchema =
  DomainValues.BillingAccountRuntimeStatusSchema;
export const BillingAccountRuntimeSourceSchema =
  DomainValues.BillingAccountRuntimeSourceSchema;
export const BillingAccountBackendRuntimeStateSchema =
  DomainValues.BillingAccountBackendRuntimeStateSchema;
export const BillingAccountRuntimeOperationSchema =
  DomainValues.BillingAccountRuntimeOperationSchema;
export const BillingAccountRuntimeParentVisibleStateSchema =
  DomainValues.BillingAccountRuntimeParentVisibleStateSchema;
export const BillingAccountRuntimeProviderBoundarySchema =
  DomainValues.BillingAccountRuntimeProviderBoundarySchema;
export const BillingAccountRuntimeProviderSecretCustodySchema =
  DomainValues.BillingAccountRuntimeProviderSecretCustodySchema;
export const BillingAccountRuntimeChildDeviceConsumptionSchema =
  DomainValues.BillingAccountRuntimeChildDeviceConsumptionSchema;
export const BillingAccountRuntimeEntitlementSigningStateSchema =
  DomainValues.BillingAccountRuntimeEntitlementSigningStateSchema;
export const BillingAccountRuntimeNonClaimSchema =
  DomainValues.BillingAccountRuntimeNonClaimSchema;
export const BillingAccountRuntimeStripeSdkClaimSchema =
  DomainValues.BillingAccountRuntimeStripeSdkClaimSchema;
export const BillingAccountRuntimeProviderSecretClaimSchema =
  DomainValues.BillingAccountRuntimeProviderSecretClaimSchema;
export const BillingAccountRuntimeBackendClaimSchema =
  DomainValues.BillingAccountRuntimeBackendClaimSchema;
export const BillingAccountRuntimePortalUiClaimSchema =
  DomainValues.BillingAccountRuntimePortalUiClaimSchema;
export const BillingAccountRuntimeChildDeviceConsumptionClaimSchema =
  DomainValues.BillingAccountRuntimeChildDeviceConsumptionClaimSchema;
export const BillingAccountRuntimeChildActivityCustodyClaimSchema =
  DomainValues.BillingAccountRuntimeChildActivityCustodyClaimSchema;
export const BillingAccountRuntimeBoundaryIdSchema =
  DomainValues.BillingAccountRuntimeBoundaryIdSchema;
export const BillingAccountRuntimeAuditReferenceSchema =
  DomainValues.BillingAccountRuntimeAuditReferenceSchema;
export const BillingAccountRuntimeFailureStateSchema =
  Domain.BillingAccountRuntimeFailureStateSchema;
export const BillingAccountRuntimeStatusRowSchema =
  Domain.BillingAccountRuntimeStatusRowSchema;
export const BillingAccountRuntimeOperationRowSchema =
  Domain.BillingAccountRuntimeOperationRowSchema;
export const BillingAccountRuntimeEntitlementSigningBoundarySchema =
  Domain.BillingAccountRuntimeEntitlementSigningBoundarySchema;
export const BillingAccountRuntimeBoundaryProofSchema =
  Domain.BillingAccountRuntimeBoundaryProofSchema;

export type BillingAccountRuntimeStatus = DomainValues.BillingAccountRuntimeStatus;
export type BillingAccountRuntimeOperation = DomainValues.BillingAccountRuntimeOperation;
export type BillingAccountBackendRuntimeState =
  DomainValues.BillingAccountBackendRuntimeState;
export type BillingAccountRuntimeNonClaim = DomainValues.BillingAccountRuntimeNonClaim;
export type BillingAccountRuntimeStatusRow =
  Domain.BillingAccountRuntimeStatusRow;
export type BillingAccountRuntimeOperationRow =
  Domain.BillingAccountRuntimeOperationRow;
export type BillingAccountRuntimeFailureState =
  Domain.BillingAccountRuntimeFailureState;
export type BillingAccountRuntimeEntitlementSigningBoundary =
  Domain.BillingAccountRuntimeEntitlementSigningBoundary;
export type BillingAccountRuntimeBoundaryProof =
  Domain.BillingAccountRuntimeBoundaryProof;

export const decodeBillingAccountRuntimeBoundaryProof =
  Domain.decodeBillingAccountRuntimeBoundaryProof;
export const summarizeBillingAccountRuntimeStatuses =
  DomainValues.summarizeBillingAccountRuntimeStatuses;
export const summarizeBillingAccountRuntimeOperations =
  DomainValues.summarizeBillingAccountRuntimeOperations;
