import * as Domain from '@ocentra-parent/billing-domain/billing-account-runtime-boundary-values';

export const BillingAccountRuntimeSchemaVersionSchema =
  Domain.BillingAccountRuntimeSchemaVersionSchema;
export const BillingAccountRuntimeStatusSchema =
  Domain.BillingAccountRuntimeStatusSchema;
export const BillingAccountRuntimeSourceSchema =
  Domain.BillingAccountRuntimeSourceSchema;
export const BillingAccountBackendRuntimeStateSchema =
  Domain.BillingAccountBackendRuntimeStateSchema;
export const BillingAccountRuntimeOperationSchema =
  Domain.BillingAccountRuntimeOperationSchema;
export const BillingAccountRuntimeParentVisibleStateSchema =
  Domain.BillingAccountRuntimeParentVisibleStateSchema;
export const BillingAccountRuntimeProviderBoundarySchema =
  Domain.BillingAccountRuntimeProviderBoundarySchema;
export const BillingAccountRuntimeProviderSecretCustodySchema =
  Domain.BillingAccountRuntimeProviderSecretCustodySchema;
export const BillingAccountRuntimeChildDeviceConsumptionSchema =
  Domain.BillingAccountRuntimeChildDeviceConsumptionSchema;
export const BillingAccountRuntimeEntitlementSigningStateSchema =
  Domain.BillingAccountRuntimeEntitlementSigningStateSchema;
export const BillingAccountRuntimeNonClaimSchema =
  Domain.BillingAccountRuntimeNonClaimSchema;
export const BillingAccountRuntimeStripeSdkClaimSchema =
  Domain.BillingAccountRuntimeStripeSdkClaimSchema;
export const BillingAccountRuntimeProviderSecretClaimSchema =
  Domain.BillingAccountRuntimeProviderSecretClaimSchema;
export const BillingAccountRuntimeBackendClaimSchema =
  Domain.BillingAccountRuntimeBackendClaimSchema;
export const BillingAccountRuntimePortalUiClaimSchema =
  Domain.BillingAccountRuntimePortalUiClaimSchema;
export const BillingAccountRuntimeChildDeviceConsumptionClaimSchema =
  Domain.BillingAccountRuntimeChildDeviceConsumptionClaimSchema;
export const BillingAccountRuntimeChildActivityCustodyClaimSchema =
  Domain.BillingAccountRuntimeChildActivityCustodyClaimSchema;
export const BillingAccountRuntimeBoundaryIdSchema =
  Domain.BillingAccountRuntimeBoundaryIdSchema;
export const BillingAccountRuntimeAuditReferenceSchema =
  Domain.BillingAccountRuntimeAuditReferenceSchema;

export type BillingAccountRuntimeStatus = Domain.BillingAccountRuntimeStatus;
export type BillingAccountRuntimeOperation = Domain.BillingAccountRuntimeOperation;
export type BillingAccountBackendRuntimeState =
  Domain.BillingAccountBackendRuntimeState;
export type BillingAccountRuntimeNonClaim = Domain.BillingAccountRuntimeNonClaim;

export const summarizeBillingAccountRuntimeStatuses =
  Domain.summarizeBillingAccountRuntimeStatuses;
export const summarizeBillingAccountRuntimeOperations =
  Domain.summarizeBillingAccountRuntimeOperations;
