import * as Domain from '@ocentra-parent/billing-domain/billing-support-admin-status-values';

export const BillingSupportAdminStatusSchemaVersionSchema =
  Domain.BillingSupportAdminStatusSchemaVersionSchema;
export const BillingSupportAdminStatusRowSchema =
  Domain.BillingSupportAdminStatusRowSchema;
export const BillingSupportAdminStatusRuntimeStateSchema =
  Domain.BillingSupportAdminStatusRuntimeStateSchema;
export const BillingSupportAdminStatusDataClassSchema =
  Domain.BillingSupportAdminStatusDataClassSchema;
export const BillingSupportAdminStatusNonClaimSchema =
  Domain.BillingSupportAdminStatusNonClaimSchema;
export const BillingSupportAdminStatusProofRefSchema =
  Domain.BillingSupportAdminStatusProofRefSchema;
export const BillingSupportAdminStatusEvidenceExportAccessSchema =
  Domain.BillingSupportAdminStatusEvidenceExportAccessSchema;
export const BillingSupportAdminStatusLocalSafetyClaimSchema =
  Domain.BillingSupportAdminStatusLocalSafetyClaimSchema;
export const BillingSupportAdminStatusProviderClaimSchema =
  Domain.BillingSupportAdminStatusProviderClaimSchema;
export const BillingSupportAdminStatusPortalClaimSchema =
  Domain.BillingSupportAdminStatusPortalClaimSchema;
export const BillingSupportAdminStatusChildActivityCustodyClaimSchema =
  Domain.BillingSupportAdminStatusChildActivityCustodyClaimSchema;
export const BillingSupportAdminStatusIdSchema =
  Domain.BillingSupportAdminStatusIdSchema;
export const BillingSupportAdminStatusAuditReferenceSchema =
  Domain.BillingSupportAdminStatusAuditReferenceSchema;

export type BillingSupportAdminStatusRow = Domain.BillingSupportAdminStatusRow;
export type BillingSupportAdminStatusRuntimeState =
  Domain.BillingSupportAdminStatusRuntimeState;
export type BillingSupportAdminStatusDataClass =
  Domain.BillingSupportAdminStatusDataClass;
export type BillingSupportAdminStatusNonClaim =
  Domain.BillingSupportAdminStatusNonClaim;
export type BillingSupportAdminStatusProofRef =
  Domain.BillingSupportAdminStatusProofRef;

export const summarizeBillingSupportAdminStatusRows =
  Domain.summarizeBillingSupportAdminStatusRows;
export const summarizeBillingSupportAdminStatusRuntimeStates =
  Domain.summarizeBillingSupportAdminStatusRuntimeStates;
