import {
  BillingEntitlementRuntimeDeviceLimitConsumptionSchema as DomainBillingEntitlementRuntimeDeviceLimitConsumptionSchema,
  BillingEntitlementRuntimeFailureConsumptionSchema as DomainBillingEntitlementRuntimeFailureConsumptionSchema,
  BillingEntitlementRuntimeKnownGaps as DomainBillingEntitlementRuntimeKnownGaps,
  BillingEntitlementRuntimeProof as DomainBillingEntitlementRuntimeProof,
  BillingEntitlementRuntimeProofReadModel as DomainBillingEntitlementRuntimeProofReadModel,
  BillingEntitlementRuntimeProofSchema as DomainBillingEntitlementRuntimeProofSchema,
  BillingEntitlementRuntimeSnapshotConsumptionSchema as DomainBillingEntitlementRuntimeSnapshotConsumptionSchema,
  decodeBillingEntitlementRuntimeProof as decodeDomainBillingEntitlementRuntimeProof,
  summarizeBillingEntitlementRuntimeConsumptionStates as summarizeDomainBillingEntitlementRuntimeConsumptionStates,
  summarizeBillingEntitlementRuntimeSnapshotStates as summarizeDomainBillingEntitlementRuntimeSnapshotStates,
  type BillingEntitlementRuntimeDeviceLimitConsumption as DomainBillingEntitlementRuntimeDeviceLimitConsumption,
  type BillingEntitlementRuntimeFailureConsumption as DomainBillingEntitlementRuntimeFailureConsumption,
  type BillingEntitlementRuntimeProof as DomainBillingEntitlementRuntimeProofType,
  type BillingEntitlementRuntimeSnapshotConsumption as DomainBillingEntitlementRuntimeSnapshotConsumption,
} from '@ocentra-parent/billing-domain/billing-entitlement-runtime-proof';

export const BillingEntitlementRuntimeSnapshotConsumptionSchema =
  DomainBillingEntitlementRuntimeSnapshotConsumptionSchema;
export const BillingEntitlementRuntimeDeviceLimitConsumptionSchema =
  DomainBillingEntitlementRuntimeDeviceLimitConsumptionSchema;
export const BillingEntitlementRuntimeFailureConsumptionSchema =
  DomainBillingEntitlementRuntimeFailureConsumptionSchema;
export const BillingEntitlementRuntimeProofSchema =
  DomainBillingEntitlementRuntimeProofSchema;

export type BillingEntitlementRuntimeSnapshotConsumption =
  DomainBillingEntitlementRuntimeSnapshotConsumption;
export type BillingEntitlementRuntimeDeviceLimitConsumption =
  DomainBillingEntitlementRuntimeDeviceLimitConsumption;
export type BillingEntitlementRuntimeFailureConsumption =
  DomainBillingEntitlementRuntimeFailureConsumption;
export type BillingEntitlementRuntimeProof =
  DomainBillingEntitlementRuntimeProofType;

export const decodeBillingEntitlementRuntimeProof =
  decodeDomainBillingEntitlementRuntimeProof;
export const BillingEntitlementRuntimeProofReadModel =
  DomainBillingEntitlementRuntimeProofReadModel;
export const BillingEntitlementRuntimeProof =
  DomainBillingEntitlementRuntimeProof;
export const BillingEntitlementRuntimeKnownGaps =
  DomainBillingEntitlementRuntimeKnownGaps;
export const summarizeBillingEntitlementRuntimeConsumptionStates =
  summarizeDomainBillingEntitlementRuntimeConsumptionStates;
export const summarizeBillingEntitlementRuntimeSnapshotStates =
  summarizeDomainBillingEntitlementRuntimeSnapshotStates;
