import * as Domain from '@ocentra-parent/billing-domain/billing-support-admin-status-proof';
import * as DomainValues from '@ocentra-parent/billing-domain/billing-support-admin-status-values';

export const BillingSupportAdminStatusSchemaVersionSchema =
  DomainValues.BillingSupportAdminStatusSchemaVersionSchema;
export const BillingSupportAdminStatusRowSchema =
  DomainValues.BillingSupportAdminStatusRowSchema;
export const BillingSupportAdminStatusRuntimeStateSchema =
  DomainValues.BillingSupportAdminStatusRuntimeStateSchema;
export const BillingSupportAdminStatusDataClassSchema =
  DomainValues.BillingSupportAdminStatusDataClassSchema;
export const BillingSupportAdminStatusNonClaimSchema =
  DomainValues.BillingSupportAdminStatusNonClaimSchema;
export const BillingSupportAdminStatusProofRefSchema =
  DomainValues.BillingSupportAdminStatusProofRefSchema;
export const BillingSupportAdminStatusEvidenceExportAccessSchema =
  DomainValues.BillingSupportAdminStatusEvidenceExportAccessSchema;
export const BillingSupportAdminStatusLocalSafetyClaimSchema =
  DomainValues.BillingSupportAdminStatusLocalSafetyClaimSchema;
export const BillingSupportAdminStatusProviderClaimSchema =
  DomainValues.BillingSupportAdminStatusProviderClaimSchema;
export const BillingSupportAdminStatusPortalClaimSchema =
  DomainValues.BillingSupportAdminStatusPortalClaimSchema;
export const BillingSupportAdminStatusChildActivityCustodyClaimSchema =
  DomainValues.BillingSupportAdminStatusChildActivityCustodyClaimSchema;
export const BillingSupportAdminStatusIdSchema =
  DomainValues.BillingSupportAdminStatusIdSchema;
export const BillingSupportAdminStatusAuditReferenceSchema =
  DomainValues.BillingSupportAdminStatusAuditReferenceSchema;
export const BillingSupportAdminStatusProofRowSchema =
  Domain.BillingSupportAdminStatusProofRowSchema;
export const BillingSupportAdminStatusProofSchema =
  Domain.BillingSupportAdminStatusProofSchema;

export type BillingSupportAdminStatusRow = DomainValues.BillingSupportAdminStatusRow;
export type BillingSupportAdminStatusRuntimeState =
  DomainValues.BillingSupportAdminStatusRuntimeState;
export type BillingSupportAdminStatusDataClass =
  DomainValues.BillingSupportAdminStatusDataClass;
export type BillingSupportAdminStatusNonClaim =
  DomainValues.BillingSupportAdminStatusNonClaim;
export type BillingSupportAdminStatusProofRef =
  DomainValues.BillingSupportAdminStatusProofRef;
export type BillingSupportAdminStatusProofRow =
  Domain.BillingSupportAdminStatusProofRow;
export type BillingSupportAdminStatusProof = Domain.BillingSupportAdminStatusProof;

export const decodeBillingSupportAdminStatusProof =
  Domain.decodeBillingSupportAdminStatusProof;
export const BillingSupportAdminStatusProofReadModel =
  Domain.BillingSupportAdminStatusProofReadModel;
export const BillingSupportAdminStatusProof =
  Domain.BillingSupportAdminStatusProof;
export const BillingSupportAdminStatusKnownGaps =
  Domain.BillingSupportAdminStatusKnownGaps;
export const BillingSupportAdminStatusBoundaryProof =
  Domain.BillingSupportAdminStatusBoundaryProof;
export const summarizeBillingSupportAdminStatusRows =
  DomainValues.summarizeBillingSupportAdminStatusRows;
export const summarizeBillingSupportAdminStatusRuntimeStates =
  DomainValues.summarizeBillingSupportAdminStatusRuntimeStates;
