import {
  BrowserGamePolicyCompilerInputSchema as BrowserGamePolicyCompilerInputSchemaFromBrowser,
  BrowserGamePolicyDecisionCandidateSchema as BrowserGamePolicyDecisionCandidateSchemaFromBrowser,
  compileBrowserGamePolicyCandidate as compileBrowserGamePolicyCandidateFromBrowser,
  decodeBrowserGamePolicyCompilerInput as decodeBrowserGamePolicyCompilerInputFromBrowser,
  decodeBrowserGamePolicyDecisionCandidate as decodeBrowserGamePolicyDecisionCandidateFromBrowser,
} from '@ocentra-parent/browser-domain/browser-game-policy-compiler';
import type {
  BrowserGamePolicyCompilerInput as BrowserGamePolicyCompilerInputFromBrowser,
  BrowserGamePolicyDecisionCandidate as BrowserGamePolicyDecisionCandidateFromBrowser,
} from '@ocentra-parent/browser-domain/browser-game-policy-compiler';

export const BrowserGamePolicyCompilerInputSchema = BrowserGamePolicyCompilerInputSchemaFromBrowser;
export const BrowserGamePolicyDecisionCandidateSchema = BrowserGamePolicyDecisionCandidateSchemaFromBrowser;
export const decodeBrowserGamePolicyCompilerInput = decodeBrowserGamePolicyCompilerInputFromBrowser;
export const decodeBrowserGamePolicyDecisionCandidate = decodeBrowserGamePolicyDecisionCandidateFromBrowser;
export type BrowserGamePolicyCompilerInput = BrowserGamePolicyCompilerInputFromBrowser;
export type BrowserGamePolicyDecisionCandidate = BrowserGamePolicyDecisionCandidateFromBrowser;
export const compileBrowserGamePolicyCandidate = compileBrowserGamePolicyCandidateFromBrowser;
