import * as BrowserGamePolicyCompilerValues from '@ocentra-parent/browser-domain/browser-game-policy-compiler-values';

export const BrowserGamePolicyEvidenceRefsSchema =
  BrowserGamePolicyCompilerValues.BrowserGamePolicyEvidenceRefsSchema;
export const BrowserGamePolicyAnalysisRefsSchema =
  BrowserGamePolicyCompilerValues.BrowserGamePolicyAnalysisRefsSchema;
export const BrowserGamePolicyMobileCapabilityRefsSchema =
  BrowserGamePolicyCompilerValues.BrowserGamePolicyMobileCapabilityRefsSchema;
export const BrowserGamePolicyParentRuleRefsSchema =
  BrowserGamePolicyCompilerValues.BrowserGamePolicyParentRuleRefsSchema;
export const BrowserGamePolicyScheduleRefsSchema =
  BrowserGamePolicyCompilerValues.BrowserGamePolicyScheduleRefsSchema;
export const BrowserGamePolicyCompileRequestIdSchema =
  BrowserGamePolicyCompilerValues.BrowserGamePolicyCompileRequestIdSchema;
export const BrowserGamePolicyDecisionCandidateIdSchema =
  BrowserGamePolicyCompilerValues.BrowserGamePolicyDecisionCandidateIdSchema;
export const BrowserGamePolicyTargetKindSchema = BrowserGamePolicyCompilerValues.BrowserGamePolicyTargetKindSchema;
export const BrowserGamePolicyActionCandidateSchema =
  BrowserGamePolicyCompilerValues.BrowserGamePolicyActionCandidateSchema;
export const BrowserGamePolicyReasonCodeSchema = BrowserGamePolicyCompilerValues.BrowserGamePolicyReasonCodeSchema;
export const BrowserGamePolicyCompilerModeSchema = BrowserGamePolicyCompilerValues.BrowserGamePolicyCompilerModeSchema;
export const BrowserGamePolicyConfidenceSchema = BrowserGamePolicyCompilerValues.BrowserGamePolicyConfidenceSchema;
export const BrowserGamePolicyReasonCodesSchema = BrowserGamePolicyCompilerValues.BrowserGamePolicyReasonCodesSchema;
