import {
  ActivityNetworkActivityClassificationKindSchema,
  ActivityNetworkActivityClassificationSchema,
  ActivityNetworkAdapterCapabilitySchema,
  ActivityNetworkAdapterCapabilityStateSchema,
  ActivityNetworkClaimScopeSchema,
  ActivityNetworkContractSchemaVersion,
  ActivityNetworkDomainEvidenceSchema,
  ActivityNetworkDomainEvidenceSourceSchema,
  ActivityNetworkEvidenceGradeSchema,
  ActivityNetworkFlowEvidenceSchema,
  ActivityNetworkPolicyActionKindSchema,
  ActivityNetworkPolicyActionModeSchema,
  ActivityNetworkPolicyActionSchema,
  ActivityNetworkUnsupportedClaimSchema,
} from '@ocentra-parent/network-domain/network-contracts';
import type {
  ActivityNetworkActivityClassification as UpstreamActivityNetworkActivityClassification,
  ActivityNetworkActivityClassificationKind as UpstreamActivityNetworkActivityClassificationKind,
  ActivityNetworkAdapterCapability as UpstreamActivityNetworkAdapterCapability,
  ActivityNetworkAdapterCapabilityState as UpstreamActivityNetworkAdapterCapabilityState,
  ActivityNetworkClaimScope as UpstreamActivityNetworkClaimScope,
  ActivityNetworkDomainEvidence as UpstreamActivityNetworkDomainEvidence,
  ActivityNetworkDomainEvidenceSource as UpstreamActivityNetworkDomainEvidenceSource,
  ActivityNetworkEvidenceGrade as UpstreamActivityNetworkEvidenceGrade,
  ActivityNetworkFlowEvidence as UpstreamActivityNetworkFlowEvidence,
  ActivityNetworkPolicyAction as UpstreamActivityNetworkPolicyAction,
  ActivityNetworkPolicyActionKind as UpstreamActivityNetworkPolicyActionKind,
  ActivityNetworkPolicyActionMode as UpstreamActivityNetworkPolicyActionMode,
  ActivityNetworkUnsupportedClaim as UpstreamActivityNetworkUnsupportedClaim,
} from '@ocentra-parent/network-domain/network-contracts';

export {
  ActivityNetworkContractSchemaVersion,
  ActivityNetworkClaimScopeSchema,
  ActivityNetworkUnsupportedClaimSchema,
  ActivityNetworkEvidenceGradeSchema,
  ActivityNetworkDomainEvidenceSourceSchema,
  ActivityNetworkActivityClassificationKindSchema,
  ActivityNetworkAdapterCapabilityStateSchema,
  ActivityNetworkPolicyActionModeSchema,
  ActivityNetworkPolicyActionKindSchema,
  ActivityNetworkFlowEvidenceSchema,
  ActivityNetworkDomainEvidenceSchema,
  ActivityNetworkActivityClassificationSchema,
  ActivityNetworkAdapterCapabilitySchema,
  ActivityNetworkPolicyActionSchema,
};

export type ActivityNetworkClaimScope = UpstreamActivityNetworkClaimScope;
export type ActivityNetworkUnsupportedClaim = UpstreamActivityNetworkUnsupportedClaim;
export type ActivityNetworkEvidenceGrade = UpstreamActivityNetworkEvidenceGrade;
export type ActivityNetworkDomainEvidenceSource = UpstreamActivityNetworkDomainEvidenceSource;
export type ActivityNetworkActivityClassificationKind = UpstreamActivityNetworkActivityClassificationKind;
export type ActivityNetworkAdapterCapabilityState = UpstreamActivityNetworkAdapterCapabilityState;
export type ActivityNetworkPolicyActionMode = UpstreamActivityNetworkPolicyActionMode;
export type ActivityNetworkPolicyActionKind = UpstreamActivityNetworkPolicyActionKind;
export type ActivityNetworkFlowEvidence = UpstreamActivityNetworkFlowEvidence;
export type ActivityNetworkDomainEvidence = UpstreamActivityNetworkDomainEvidence;
export type ActivityNetworkActivityClassification = UpstreamActivityNetworkActivityClassification;
export type ActivityNetworkAdapterCapability = UpstreamActivityNetworkAdapterCapability;
export type ActivityNetworkPolicyAction = UpstreamActivityNetworkPolicyAction;
