import * as ParentMobileRuntimeDomain from '@ocentra-parent/lan-domain/parent-mobile-runtime';

export const ParentMobilePlatformSchema = ParentMobileRuntimeDomain.ParentMobilePlatformSchema;
export const ParentMobilePackageStateSchema = ParentMobileRuntimeDomain.ParentMobilePackageStateSchema;
export const ParentMobilePackageLifecycleStateSchema = ParentMobileRuntimeDomain.ParentMobilePackageLifecycleStateSchema;
export const ParentMobileSigningStateSchema = ParentMobileRuntimeDomain.ParentMobileSigningStateSchema;
export const ParentMobileStoreDistributionStateSchema = ParentMobileRuntimeDomain.ParentMobileStoreDistributionStateSchema;
export const ParentMobileControllerStateSchema = ParentMobileRuntimeDomain.ParentMobileControllerStateSchema;
export const ParentMobileCommandAuthorityStateSchema = ParentMobileRuntimeDomain.ParentMobileCommandAuthorityStateSchema;
export const ParentMobileControllerRequestBoundarySchema =
  ParentMobileRuntimeDomain.ParentMobileControllerRequestBoundarySchema;
export const ParentMobileServiceAvailabilityStateSchema =
  ParentMobileRuntimeDomain.ParentMobileServiceAvailabilityStateSchema;
export const ParentMobileServiceRouteKindSchema = ParentMobileRuntimeDomain.ParentMobileServiceRouteKindSchema;
export const ParentMobileServiceRouteCustodySchema = ParentMobileRuntimeDomain.ParentMobileServiceRouteCustodySchema;
export const ParentMobileAssistantJobRouteSchema = ParentMobileRuntimeDomain.ParentMobileAssistantJobRouteSchema;
export const ParentMobileAssistantJobStateSchema = ParentMobileRuntimeDomain.ParentMobileAssistantJobStateSchema;
export const ParentMobileLocalModelExecutionStateSchema =
  ParentMobileRuntimeDomain.ParentMobileLocalModelExecutionStateSchema;
export const ParentMobileChildAgentBehaviorClaimSchema =
  ParentMobileRuntimeDomain.ParentMobileChildAgentBehaviorClaimSchema;
export const ParentMobilePackageProofSchema = ParentMobileRuntimeDomain.ParentMobilePackageProofSchema;
export const ParentMobileCapabilityProofSchema = ParentMobileRuntimeDomain.ParentMobileCapabilityProofSchema;
export const ParentMobileServiceRouteStatusSchema = ParentMobileRuntimeDomain.ParentMobileServiceRouteStatusSchema;
export const ParentMobileServiceAvailabilitySchema = ParentMobileRuntimeDomain.ParentMobileServiceAvailabilitySchema;
export const ParentMobileControllerProofSchema = ParentMobileRuntimeDomain.ParentMobileControllerProofSchema;
export const ParentMobileAssistantJobProofSchema = ParentMobileRuntimeDomain.ParentMobileAssistantJobProofSchema;
export const ParentMobileRuntimeReadModelSchema = ParentMobileRuntimeDomain.ParentMobileRuntimeReadModelSchema;

export type ParentMobilePlatform = ParentMobileRuntimeDomain.ParentMobilePlatform;
export type ParentMobilePackageState = ParentMobileRuntimeDomain.ParentMobilePackageState;
export type ParentMobilePackageLifecycleState = ParentMobileRuntimeDomain.ParentMobilePackageLifecycleState;
export type ParentMobileSigningState = ParentMobileRuntimeDomain.ParentMobileSigningState;
export type ParentMobileStoreDistributionState = ParentMobileRuntimeDomain.ParentMobileStoreDistributionState;
export type ParentMobileControllerState = ParentMobileRuntimeDomain.ParentMobileControllerState;
export type ParentMobileCommandAuthorityState = ParentMobileRuntimeDomain.ParentMobileCommandAuthorityState;
export type ParentMobileControllerRequestBoundary = ParentMobileRuntimeDomain.ParentMobileControllerRequestBoundary;
export type ParentMobileServiceAvailabilityState = ParentMobileRuntimeDomain.ParentMobileServiceAvailabilityState;
export type ParentMobileServiceRouteKind = ParentMobileRuntimeDomain.ParentMobileServiceRouteKind;
export type ParentMobileServiceRouteCustody = ParentMobileRuntimeDomain.ParentMobileServiceRouteCustody;
export type ParentMobileAssistantJobRoute = ParentMobileRuntimeDomain.ParentMobileAssistantJobRoute;
export type ParentMobileAssistantJobState = ParentMobileRuntimeDomain.ParentMobileAssistantJobState;
export type ParentMobileLocalModelExecutionState = ParentMobileRuntimeDomain.ParentMobileLocalModelExecutionState;
export type ParentMobileChildAgentBehaviorClaim = ParentMobileRuntimeDomain.ParentMobileChildAgentBehaviorClaim;
export type ParentMobilePackageProof = ParentMobileRuntimeDomain.ParentMobilePackageProof;
export type ParentMobileServiceRouteStatus = ParentMobileRuntimeDomain.ParentMobileServiceRouteStatus;
export type ParentMobileServiceAvailability = ParentMobileRuntimeDomain.ParentMobileServiceAvailability;
export type ParentMobileControllerProof = ParentMobileRuntimeDomain.ParentMobileControllerProof;
export type ParentMobileAssistantJobProof = ParentMobileRuntimeDomain.ParentMobileAssistantJobProof;
export type ParentMobileCapabilityProof = ParentMobileRuntimeDomain.ParentMobileCapabilityProof;
export type ParentMobileRuntimeReadModel = ParentMobileRuntimeDomain.ParentMobileRuntimeReadModel;
