import {
  SocialParentPolicyCompilerInputSchema as SocialParentPolicyCompilerInputSchemaFromBrowser,
  SocialParentPolicyDecisionCandidateSchema as SocialParentPolicyDecisionCandidateSchemaFromBrowser,
  compileSocialParentPolicyCandidate as compileSocialParentPolicyCandidateFromBrowser,
  decodeSocialParentPolicyCompilerInput as decodeSocialParentPolicyCompilerInputFromBrowser,
  decodeSocialParentPolicyDecisionCandidate as decodeSocialParentPolicyDecisionCandidateFromBrowser,
} from '@ocentra-parent/browser-domain/social-policy-compiler';
import type {
  SocialParentPolicyCompilerInput as SocialParentPolicyCompilerInputFromBrowser,
  SocialParentPolicyDecisionCandidate as SocialParentPolicyDecisionCandidateFromBrowser,
} from '@ocentra-parent/browser-domain/social-policy-compiler';

export const SocialParentPolicyCompilerInputSchema = SocialParentPolicyCompilerInputSchemaFromBrowser;
export const SocialParentPolicyDecisionCandidateSchema = SocialParentPolicyDecisionCandidateSchemaFromBrowser;
export const decodeSocialParentPolicyCompilerInput = decodeSocialParentPolicyCompilerInputFromBrowser;
export const decodeSocialParentPolicyDecisionCandidate = decodeSocialParentPolicyDecisionCandidateFromBrowser;
export type SocialParentPolicyCompilerInput = SocialParentPolicyCompilerInputFromBrowser;
export type SocialParentPolicyDecisionCandidate = SocialParentPolicyDecisionCandidateFromBrowser;
export const compileSocialParentPolicyCandidate = compileSocialParentPolicyCandidateFromBrowser;
