import * as SocialPolicyCompilerValues from '@ocentra-parent/browser-domain/social-policy-compiler-values';

export const SocialPolicyEvidenceRefsSchema = SocialPolicyCompilerValues.SocialPolicyEvidenceRefsSchema;
export const SocialPolicySignalSetRefsSchema = SocialPolicyCompilerValues.SocialPolicySignalSetRefsSchema;
export const SocialPolicyParentRuleRefsSchema = SocialPolicyCompilerValues.SocialPolicyParentRuleRefsSchema;
export const SocialPolicyScheduleRefsSchema = SocialPolicyCompilerValues.SocialPolicyScheduleRefsSchema;
export const SocialPolicyTimeBudgetRefsSchema = SocialPolicyCompilerValues.SocialPolicyTimeBudgetRefsSchema;
export const SocialParentPolicyCompileRequestIdSchema =
  SocialPolicyCompilerValues.SocialParentPolicyCompileRequestIdSchema;
export const SocialParentPolicyDecisionCandidateIdSchema =
  SocialPolicyCompilerValues.SocialParentPolicyDecisionCandidateIdSchema;
export const SocialParentPolicyTargetKindSchema = SocialPolicyCompilerValues.SocialParentPolicyTargetKindSchema;
export const SocialParentPolicyActionCandidateSchema =
  SocialPolicyCompilerValues.SocialParentPolicyActionCandidateSchema;
export const SocialParentPolicyReasonCodeSchema = SocialPolicyCompilerValues.SocialParentPolicyReasonCodeSchema;
export const SocialParentPolicyCompilerModeSchema = SocialPolicyCompilerValues.SocialParentPolicyCompilerModeSchema;
export const SocialParentPolicyConfidenceSchema = SocialPolicyCompilerValues.SocialParentPolicyConfidenceSchema;
export const SocialParentPolicyScheduleStateSchema = SocialPolicyCompilerValues.SocialParentPolicyScheduleStateSchema;
export const SocialParentPolicyTimeBudgetStateSchema =
  SocialPolicyCompilerValues.SocialParentPolicyTimeBudgetStateSchema;
export const SocialParentPolicyReasonCodesSchema = SocialPolicyCompilerValues.SocialParentPolicyReasonCodesSchema;
