import {
  TrackingPolicyCompilerRuntimeProofRequestIdSchema as TrackingPolicyCompilerRuntimeProofRequestIdSchemaFromTracking,
  TrackingPolicyCompilerRuntimeProofModeSchema as TrackingPolicyCompilerRuntimeProofModeSchemaFromTracking,
  TrackingPolicyCompilerRequestedActionSchema as TrackingPolicyCompilerRequestedActionSchemaFromTracking,
  TrackingPolicyCompilerFinalActionSourceSchema as TrackingPolicyCompilerFinalActionSourceSchemaFromTracking,
  TrackingPolicyCompilerRuntimeProofRequestSchema as TrackingPolicyCompilerRuntimeProofRequestSchemaFromTracking,
  TrackingPolicyCompilerRuntimeProofResultSchema as TrackingPolicyCompilerRuntimeProofResultSchemaFromTracking,
  compileTrackingPolicyRuntimeProofDecision as compileTrackingPolicyRuntimeProofDecisionFromTracking,
  trackingPolicyCompilerActionNeedsAlert as trackingPolicyCompilerActionNeedsAlertFromTracking,
} from '@ocentra-parent/tracking-domain/tracking-policy-compiler-runtime-proof';
import type {
  TrackingPolicyCompilerRuntimeProofRequest as TrackingPolicyCompilerRuntimeProofRequestFromTracking,
  TrackingPolicyCompilerRuntimeProofResult as TrackingPolicyCompilerRuntimeProofResultFromTracking,
} from '@ocentra-parent/tracking-domain/tracking-policy-compiler-runtime-proof';

export const TrackingPolicyCompilerRuntimeProofRequestIdSchema =
  TrackingPolicyCompilerRuntimeProofRequestIdSchemaFromTracking;
export const TrackingPolicyCompilerRuntimeProofModeSchema = TrackingPolicyCompilerRuntimeProofModeSchemaFromTracking;
export const TrackingPolicyCompilerRequestedActionSchema =
  TrackingPolicyCompilerRequestedActionSchemaFromTracking;
export const TrackingPolicyCompilerFinalActionSourceSchema =
  TrackingPolicyCompilerFinalActionSourceSchemaFromTracking;
export const TrackingPolicyCompilerRuntimeProofRequestSchema =
  TrackingPolicyCompilerRuntimeProofRequestSchemaFromTracking;
export const TrackingPolicyCompilerRuntimeProofResultSchema =
  TrackingPolicyCompilerRuntimeProofResultSchemaFromTracking;
export type TrackingPolicyCompilerRuntimeProofRequest = TrackingPolicyCompilerRuntimeProofRequestFromTracking;
export type TrackingPolicyCompilerRuntimeProofResult = TrackingPolicyCompilerRuntimeProofResultFromTracking;
export const compileTrackingPolicyRuntimeProofDecision = compileTrackingPolicyRuntimeProofDecisionFromTracking;
export const trackingPolicyCompilerActionNeedsAlert = trackingPolicyCompilerActionNeedsAlertFromTracking;
