#![forbid(unsafe_code)]

pub mod activity;
pub mod activity_capture;
mod activity_conversions;
pub mod activity_memory_graph;
pub mod activity_query;
pub mod activity_surface;
pub mod ai_contracts;
pub mod app_game;
pub mod app_game_adapter_dispatch_preflight;
pub mod app_game_adapter_dispatch_result;
pub mod app_game_adapter_execution_readiness;
pub mod app_game_authority_classifier;
pub mod app_game_boundary_read_model;
pub mod app_game_child_runtime_transport_receipt;
pub mod app_game_notification_parent_surface_intent;
pub mod app_game_notification_readiness;
pub mod app_game_notification_status;
pub mod app_game_platform_proof_status;
pub mod app_game_policy_readiness;
pub mod app_game_timer_parent_preference_setup_request;
pub mod app_game_timer_parent_surface_read_model;
pub mod authenticated_delivery_grant;
pub mod browser;
pub mod browser_intervention;
mod browser_intervention_parse;
pub mod browser_intervention_values;
pub mod browser_inventory;
pub mod browser_managed;
pub mod browser_policy;
pub mod browser_policy_catalog_values;
pub mod browser_policy_model;
pub mod browser_policy_sections;
mod browser_policy_update_request;
pub mod browser_policy_values;
pub mod browser_read_model;
pub mod browser_unmanaged_enforcement;
mod browser_values;
pub mod child_agent;
pub mod child_domain_runtime;
pub mod constants;
pub mod enforcement;
pub mod enforcement_broad_adapter_proof;
pub mod enforcement_browser_domain_adapter_proof;
pub mod enforcement_cross_platform_capability_proof;
pub mod enforcement_integrity_runtime_audit;
pub mod enforcement_os_adapter_product_proof;
pub mod enforcement_policy_dispatch;
pub mod enforcement_product_control_spine;
pub mod enforcement_readiness;
pub mod enforcement_supported_adapter_runtime_proof;
pub mod host_identity;
pub mod household_mesh;
pub mod integrity_alert_status_bridge;
pub mod journal;
pub mod lan_pairing;
pub mod lan_pairing_authority;
pub mod lan_pairing_browser_add_device_state;
pub mod lan_pairing_browser_runtime;
pub mod lan_pairing_provider_selection;
pub mod lan_pairing_support;
pub mod local_ai_runtime;
pub mod local_ai_runtime_boundary;
pub mod local_ai_runtime_provider_proof;
pub mod logging;
pub mod network_android_vpn_service_gate_status;
pub mod network_apple_network_extension_gate_status;
pub mod network_flow;
pub mod network_linux_nftables_lab_status;
pub mod network_windows_firewall_lab_status;
pub mod network_windows_wfp_gate_status;
pub mod notification_provider_status_boundary;
pub mod parent_assistant;
pub mod parent_controller_events;
#[path = "constants/policy.rs"]
pub mod policy_constants;
pub mod schema_domain_ai_wire;
pub mod schema_domain_mirrors;
pub mod screen_child_disclosure;
pub mod screen_evidence;
pub mod screen_settings;
pub mod social_alert_report_parent_surface_read_model;
pub mod social_alert_report_read_model;
mod social_audit_explanation_read_model;
mod social_dashboard_read_model;
pub mod social_parent_notification_delivery_read_model;
mod social_source_custody_mutation;
pub mod tracking;
pub mod transport;
pub mod windows_adapter_artifact_gate;
pub mod windows_adapter_artifact_ingestion;
pub mod windows_adapter_capability;
include!("root_compat.rs");

pub const CRATE_NAME: &str = "ocentra-parent-agent-protocol";
pub const LOG_SCHEMA_VERSION: u16 = 1;
pub const AGENT_PROTOCOL_SCHEMA_VERSION: u16 = 1;
pub const ACTIVITY_SCHEMA_VERSION: u16 = 1;
pub const ACTIVITY_JOURNAL_SCHEMA_VERSION: u16 = 1;
pub const ACTIVITY_QUERY_SCHEMA_VERSION: u16 = 1;
pub const ACTIVITY_MEMORY_GRAPH_SCHEMA_VERSION: u16 = 1;
pub const ACTIVITY_SURFACE_SCHEMA_VERSION: u16 = 1;
pub const BROWSER_EVIDENCE_SCHEMA_VERSION: u16 = 1;
pub const BROWSER_INTERVENTION_SCHEMA_VERSION: u16 = 1;
pub const NETWORK_FLOW_SCHEMA_VERSION: u16 = 1;
pub const LAN_PAIRING_SCHEMA_VERSION: u16 = 1;
pub const SCREEN_EVIDENCE_SCHEMA_VERSION: u16 = 1;
pub const ENFORCEMENT_SCHEMA_VERSION: u16 = 1;

pub fn crate_name() -> &'static str {
    CRATE_NAME
}
