import {
  AgentLogSnapshotSchema,
  LogFieldsSchema,
  LogLevelSchema,
  type AgentLogSnapshot,
  type LogFields,
  type LogLevel,
} from '@ocentra-parent/logging-domain/contracts';
import { type Infer, Schema, withParser } from '@ocentra-parent/schema-domain/effect';
import {
  AgentCorrelationIdSchema,
  AgentDeviceIdSchema,
  AgentEventIdSchema,
  AgentMessageIdSchema,
  AgentMessageTargetSchema,
  AgentPeerSchema,
  AgentProtocolSchemaVersion,
  AgentTimestampSchema,
  AgentWebSocketUrlSchema,
  SerializedAgentMessageSchema,
} from './primitives';
export { AgentProtocolDefaults } from './defaults';

export {
  AgentCorrelationIdSchema,
  AgentDeviceIdSchema,
  AgentEventIdSchema,
  AgentMessageIdSchema,
  AgentMessageTargetSchema,
  AgentPeerIdSchema,
  AgentPeerRoleSchema,
  AgentPeerSchema,
  AgentPlatformSchema,
  AgentProtocolSchemaVersion,
  AgentRouteSchema,
  AgentTimestampSchema,
  AgentWebSocketUrlSchema,
  SerializedAgentMessageSchema,
  type AgentCorrelationId,
  type AgentDeviceId,
  type AgentEventId,
  type AgentMessageId,
  type AgentMessageTarget,
  type AgentPeer,
  type AgentPeerId,
  type AgentPeerRole,
  type AgentPlatform,
  type AgentRoute,
  type AgentTimestamp,
  type AgentWebSocketUrl,
  type SerializedAgentMessage,
} from './primitives';
export {
  AgentLanBrowserAddDeviceDiscoveryDeviceSchema,
  AgentLanBrowserAddDevicePairingRequestSchema,
  AgentLanBrowserAddDeviceReadModelSchema,
  AgentLanBrowserAddDeviceScanSummarySchema,
  AgentLanCanonicalHouseholdDeviceSchema,
  AgentLanHouseholdDeviceActionKindSchema,
  AgentLanPairingDiscoverySourceSchema,
  AgentLanSelectedDeviceReadinessSchema,
  AgentLanTrustedDeviceRegistryEntrySchema,
  type AgentLanBrowserAddDeviceDiscoveryDevice,
  type AgentLanBrowserAddDevicePairingRequest,
  type AgentLanBrowserAddDeviceReadModel,
  type AgentLanBrowserAddDeviceScanSummary,
  type AgentLanCanonicalHouseholdDevice,
  type AgentLanHouseholdDeviceActionKind,
  type AgentLanPairingDiscoverySource,
  type AgentLanSelectedDeviceReadiness,
  type AgentLanTrustedDeviceRegistryEntry,
} from './lan-pairing-browser-add-device-state';
export {
  AgentLanSignedDiscoveryRelayAdapterKindSchema,
  AgentLanSignedDiscoveryRelayAdapterRowSchema,
  AgentLanSignedDiscoveryRelayCacheCheckSchema,
  AgentLanSignedDiscoveryRelayCacheRowSchema,
  AgentLanSignedDiscoveryRelayCustodyLabelSchema,
  AgentLanSignedDiscoveryRelayDecisionStateSchema,
  AgentLanSignedDiscoveryRelayProofStateSchema,
  AgentLanSignedDiscoveryRelayRuntimeOwnerSchema,
  AgentLanSignedDiscoveryRelayRouteSafetyCheckSchema,
  AgentLanSignedDiscoveryRelayRouteSafetyRowSchema,
  AgentLanSignedDiscoveryRelaySignedProofCheckSchema,
  AgentLanSignedDiscoveryRelaySignedProofRowSchema,
  AgentLanSignedDiscoveryRelaySourceConfidenceSchema,
  AgentLanSignedDiscoveryRelaySpineSchema,
  type AgentLanSignedDiscoveryRelayAdapterKind,
  type AgentLanSignedDiscoveryRelayAdapterRow,
  type AgentLanSignedDiscoveryRelayCacheCheck,
  type AgentLanSignedDiscoveryRelayCacheRow,
  type AgentLanSignedDiscoveryRelayCustodyLabel,
  type AgentLanSignedDiscoveryRelayDecisionState,
  type AgentLanSignedDiscoveryRelayProofState,
  type AgentLanSignedDiscoveryRelayRuntimeOwner,
  type AgentLanSignedDiscoveryRelayRouteSafetyCheck,
  type AgentLanSignedDiscoveryRelayRouteSafetyRow,
  type AgentLanSignedDiscoveryRelaySignedProofCheck,
  type AgentLanSignedDiscoveryRelaySignedProofRow,
  type AgentLanSignedDiscoveryRelaySourceConfidence,
  type AgentLanSignedDiscoveryRelaySpine,
} from './lan-signed-discovery-relay-spine';
export {
  AgentLanDiscoverySourceAuthoritySchema,
  AgentLanDiscoverySourceKindSchema,
  AgentLanDiscoverySourceMatrixSchema,
  AgentLanDiscoverySourceProofStateSchema,
  AgentLanDiscoverySourceRowSchema,
  AgentLanDiscoverySourceRuntimeOwnerSchema,
  AgentLanDiscoverySourceRuntimePathSchema,
  AgentLanDiscoverySourceStatusSchema,
  AgentLanDiscoverySourceUiSurfaceSchema,
  AgentLanPlanWorkpackIdSchema,
  AgentLanPlanWorkpackStatusRowSchema,
  type AgentLanDiscoverySourceAuthority,
  type AgentLanDiscoverySourceKind,
  type AgentLanDiscoverySourceMatrix,
  type AgentLanDiscoverySourceProofState,
  type AgentLanDiscoverySourceRow,
  type AgentLanDiscoverySourceRuntimeOwner,
  type AgentLanDiscoverySourceRuntimePath,
  type AgentLanDiscoverySourceStatus,
  type AgentLanDiscoverySourceUiSurface,
  type AgentLanPlanWorkpackId,
  type AgentLanPlanWorkpackStatusRow,
} from './lan-discovery-source-matrix';
export {
  AgentLanBrowserAddDeviceRequestSchema,
  AgentLanBrowserDiscoveryScanRequestSchema,
  AgentLanBrowserRuntimeCommandSchema,
  AgentLanBrowserRuntimeEventSchema,
  type AgentLanBrowserAddDeviceRequest,
  type AgentLanBrowserDiscoveryScanRequest,
  type AgentLanBrowserRuntimeCommand,
  type AgentLanBrowserRuntimeEvent,
} from './lan-pairing-browser-runtime';
export {
  AgentLanPairingAddressRefSchema,
  AgentLanPairingAuditEventSchema,
  AgentLanPairingChallengeIdSchema,
  AgentLanPairingChallengeSchema,
  AgentLanChildAgentResponseSchema,
  AgentLanPairingDeviceRefSchema,
  AgentLanPairingDiscoveryDeviceSchema,
  AgentLanPairingIntentIdSchema,
  AgentLanPairingIntentKindSchema,
  AgentLanPairingNetworkModeSchema,
  AgentLanPairingParentAuthoritySchema,
  AgentLanPairingProductionDiscoveryStateSchema,
  AgentLanParentIntentEnvelopeSchema,
  AgentLanPairingProofDigestSchema,
  AgentLanPairingProofPreviewSchema,
  AgentLanPairingRejectionReasonSchema,
  AgentLanPairingResponseStateSchema,
  AgentLanPairingRouteIdSchema,
  AgentLanPairingRuntimeSupportStatusSchema,
  AgentLanAiProviderRoutingStateSchema,
  AgentPairingIdSchema,
  AgentLanSelectedDeviceReachabilitySchema,
  AgentLanSelectedRouteTrustStateSchema,
  AgentPairingProofSchema,
  AgentPairingStateSchema,
  AgentPairingTokenHashSchema,
  AgentRouteSecurityPolicySchema,
  type AgentLanPairingAddressRef,
  type AgentLanPairingChallenge,
  type AgentLanPairingChallengeId,
  type AgentLanChildAgentResponse,
  type AgentLanPairingDeviceRef,
  type AgentLanPairingDiscoveryDevice,
  type AgentLanPairingIntentId,
  type AgentLanPairingIntentKind,
  type AgentLanPairingNetworkMode,
  type AgentLanPairingParentAuthority,
  type AgentLanPairingProductionDiscoveryState,
  type AgentLanParentIntentEnvelope,
  type AgentLanPairingProofDigest,
  type AgentLanPairingProofPreview,
  type AgentLanPairingRejectionReason,
  type AgentLanPairingResponseState,
  type AgentLanPairingRouteId,
  type AgentLanPairingRuntimeSupportStatus,
  type AgentLanAiProviderRoutingState,
  type AgentPairingId,
  type AgentLanSelectedDeviceReachability,
  type AgentLanSelectedRouteTrustState,
  type AgentPairingProof,
  type AgentPairingState,
  type AgentPairingTokenHash,
  type AgentRouteSecurityPolicy,
} from './security';

export const AgentCommandNameSchema = withParser(
  Schema.Literal(
    'agent.health.check',
    'agent.log.snapshot.get',
    'agent.dev.echo',
    'agent.watch.status.get',
    'agent.activity.ingest.status.get',
    'agent.activity.recent.summary.get',
    'agent.activity.memory-graph.get',
    'agent.activity.report.daily.generate',
    'agent.activity.report.weekly.generate',
    'agent.activity.report.monthly.generate',
    'agent.activity.report.save',
    'agent.activity.report.history.list',
    'agent.activity.screen.read-model.get',
    'agent.activity.app-use.read-model.get',
    'agent.activity.browser.read-model.get',
    'agent.activity.games.read-model.get',
    'agent.activity.app-game.boundary.read-model.get',
    'agent.activity.app-game.policy-readiness.read-model.get',
    'agent.activity.app-game.notification-readiness.read-model.get',
    'agent.browser.social-dashboard.read-model.get',
    'agent.browser.social-audit-explanation.read-model.get',
    'agent.browser.social-alert-report.read-model.get',
    'agent.browser.social-source-custody.mutation.apply',
    'agent.activity.network.read-model.get',
    'agent.activity.tracking.read-model.get',
    'agent.browser.inventory.read-model.get',
    'agent.browser.evidence.recent.get',
    'agent.browser.managed.bridge.poll',
    'agent.browser.intervention.read-model.get',
    'agent.network.flow.read-model.get',
    'agent.network.runtime.event-chain.stream.get',
    'agent.network.remote-delivery.status.get',
    'agent.network.live-capture.status.get',
    'agent.network.linux-nftables-lab.status.get',
    'agent.network.windows-firewall-lab.status.get',
    'agent.network.windows-wfp-gate.status.get',
    'agent.local-ai.runtime.status.get',
    'agent.local-ai.chat.generate',
    'agent.parent-assistant.answer.generate',
    'agent.policy.preview.read-model.get',
    'agent.browser-policy.get',
    'agent.browser-policy.preview',
    'agent.browser-policy.patch',
    'agent.browser-policy.replace',
    'agent.browser-policy.rollback',
    'agent.enforcement.execute',
    'agent.enforcement.timer.recover',
    'agent.enforcement.timer.expire',
    'agent.enforcement.override.cancel',
    'agent.enforcement.product-control-spine.get',
    'agent.enforcement.policy-dispatch.get',
    'agent.enforcement.broad-adapter-proof.get',
    'agent.enforcement.supported-adapter-runtime-proof.get',
    'agent.parent-assistant.thread.list',
    'agent.parent-assistant.thread.create',
    'agent.parent-assistant.thread.open',
    'agent.parent-assistant.thread.archive',
    'agent.parent-assistant.message.send',
    'agent.parent-assistant.run.cancel',
    'agent.parent-assistant.quick-action.start',
    'agent.parent-assistant.action.preview',
    'agent.parent-assistant.action.confirm',
    'agent.parent-assistant.provider.status.get',
    'agent.lan-pairing.proof.submit',
    'agent.lan-pairing.route.select',
    'agent.lan-pairing.route.revoke',
    'agent.lan-pairing.status.get',
    'agent.lan-pairing.browser-discovery.scan',
    'agent.lan-pairing.add-device.request',
    'agent.lan-pairing.controller-lease.renew',
    'agent.lan-pairing.controller-lease.release',
    'agent.lan-pairing.controller-lease.takeover',
    'agent.lan-ai.provider.status.get',
    'agent.lan-ai.job.submit'
  )
);

export const AgentEventNameSchema = withParser(
  Schema.Literal(
    'agent.connection.ready',
    'agent.command.rejected',
    'agent.health.reported',
    'agent.log.snapshot.reported',
    'agent.dev.echoed',
    'agent.watch.status.reported',
    'agent.activity.ingest.status.reported',
    'agent.activity.recent.summary.reported',
    'agent.activity.memory-graph.reported',
    'agent.activity.report.generated',
    'agent.activity.report.saved',
    'agent.activity.report.history.reported',
    'agent.activity.screen.read-model.reported',
    'agent.activity.app-use.read-model.reported',
    'agent.activity.browser.read-model.reported',
    'agent.activity.games.read-model.reported',
    'agent.activity.app-game.boundary.read-model.reported',
    'agent.activity.app-game.policy-readiness.read-model.reported',
    'agent.activity.app-game.notification-readiness.read-model.reported',
    'agent.browser.social-dashboard.read-model.reported',
    'agent.browser.social-audit-explanation.read-model.reported',
    'agent.browser.social-alert-report.read-model.reported',
    'agent.browser.social-source-custody.mutation.applied',
    'agent.activity.network.read-model.reported',
    'agent.activity.tracking.read-model.reported',
    'agent.browser.inventory.read-model.reported',
    'agent.browser.evidence.recent.reported',
    'agent.browser.managed.status.reported',
    'agent.browser.intervention.read-model.reported',
    'agent.network.flow.read-model.reported',
    'agent.network.runtime.event-chain.stream.reported',
    'agent.network.remote-delivery.status.reported',
    'agent.network.live-capture.status.reported',
    'agent.network.linux-nftables-lab.status.reported',
    'agent.network.windows-firewall-lab.status.reported',
    'agent.network.windows-wfp-gate.status.reported',
    'agent.local-ai.runtime.status.reported',
    'agent.local-ai.chat.generation.reported',
    'agent.parent-assistant.answer.reported',
    'agent.policy.preview.read-model.reported',
    'agent.browser-policy.reported',
    'agent.browser-policy.previewed',
    'agent.browser-policy.patch.accepted',
    'agent.browser-policy.patch.rejected',
    'agent.browser-policy.replace.accepted',
    'agent.browser-policy.replace.rejected',
    'agent.browser-policy.rollback.accepted',
    'agent.browser-policy.rollback.rejected',
    'agent.enforcement.audit.reported',
    'agent.enforcement.timer.reported',
    'agent.enforcement.product-control-spine.reported',
    'agent.enforcement.policy-dispatch.reported',
    'agent.enforcement.broad-adapter-proof.reported',
    'agent.enforcement.supported-adapter-runtime-proof.reported',
    'agent.parent-assistant.thread.updated',
    'agent.parent-assistant.message.accepted',
    'agent.parent-assistant.run.started',
    'agent.parent-assistant.message.delta',
    'agent.parent-assistant.message.completed',
    'agent.parent-assistant.action.previewed',
    'agent.parent-assistant.action.confirmed',
    'agent.parent-assistant.provider.degraded',
    'agent.parent-assistant.error.reported',
    'agent.lan-pairing.status.reported',
    'agent.lan-pairing.browser-discovery.reported',
    'agent.lan-pairing.add-device.reported',
    'agent.lan-pairing.audit.reported',
    'agent.lan-ai.job.reported'
  )
);

export const AgentCommandEnvelopeSchema = withParser(
  Schema.Struct({
    schemaVersion: Schema.Literal(AgentProtocolSchemaVersion),
    messageId: AgentMessageIdSchema,
    sentAt: AgentTimestampSchema,
    source: AgentPeerSchema,
    target: AgentMessageTargetSchema,
    command: AgentCommandNameSchema,
    payload: LogFieldsSchema,
  })
);

export const AgentEventEnvelopeSchema = withParser(
  Schema.Struct({
    schemaVersion: Schema.Literal(AgentProtocolSchemaVersion),
    eventId: AgentEventIdSchema,
    correlationId: AgentCorrelationIdSchema,
    sentAt: AgentTimestampSchema,
    source: AgentPeerSchema,
    target: AgentPeerSchema,
    event: AgentEventNameSchema,
    severity: LogLevelSchema,
    payload: LogFieldsSchema,
    snapshot: Schema.Union(AgentLogSnapshotSchema, Schema.Null),
  })
);

export type AgentCommandName = Infer<typeof AgentCommandNameSchema>;
export type AgentEventName = Infer<typeof AgentEventNameSchema>;
export type AgentCommandEnvelope = Infer<typeof AgentCommandEnvelopeSchema>;
export type AgentEventEnvelope = Infer<typeof AgentEventEnvelopeSchema>;
export type AgentProtocolLogFields = LogFields;
export type AgentProtocolLogLevel = LogLevel;
export type AgentProtocolSnapshot = AgentLogSnapshot;

export const decodeAgentDeviceId = Schema.decodeUnknownSync(AgentDeviceIdSchema);
export const decodeAgentMessageId = Schema.decodeUnknownSync(AgentMessageIdSchema);
export const decodeAgentTimestamp = Schema.decodeUnknownSync(AgentTimestampSchema);
export const decodeAgentWebSocketUrl = Schema.decodeUnknownSync(AgentWebSocketUrlSchema);
export const decodeSerializedAgentMessage = Schema.decodeUnknownSync(SerializedAgentMessageSchema);

export function isAgentProtocolLogText(value: unknown): value is string {
  return typeof value === 'string';
}

export {
  parseAgentSocialAlertReportReadModelEvent,
  SocialAlertReportReadModelSnapshotSchema,
  type AgentSocialAlertReportReadModelFailureReason,
  type AgentSocialAlertReportReadModelResult,
  type SocialAlertReportReadModelIntent,
  type SocialAlertReportReadModelSnapshot,
} from './social-alert-report-read-model';

export {
  parseAgentSocialSourceCustodyMutationEvent,
  SocialSourceCustodyMutationSnapshotSchema,
  type AgentSocialSourceCustodyMutationFailureReason,
  type AgentSocialSourceCustodyMutationResult,
  type SocialSourceCustodyMutationSettings,
  type SocialSourceCustodyMutationSnapshot,
} from './social-source-custody-mutation';

export const AgentCommand = {
  HealthCheck: AgentCommandNameSchema.parse('agent.health.check'),
  LogSnapshotGet: AgentCommandNameSchema.parse('agent.log.snapshot.get'),
  DevEcho: AgentCommandNameSchema.parse('agent.dev.echo'),
  WatchStatusGet: AgentCommandNameSchema.parse('agent.watch.status.get'),
  ActivityIngestStatusGet: AgentCommandNameSchema.parse('agent.activity.ingest.status.get'),
  ActivityRecentSummaryGet: AgentCommandNameSchema.parse('agent.activity.recent.summary.get'),
  ActivityMemoryGraphGet: AgentCommandNameSchema.parse('agent.activity.memory-graph.get'),
  ActivityReportDailyGenerate: AgentCommandNameSchema.parse('agent.activity.report.daily.generate'),
  ActivityReportWeeklyGenerate: AgentCommandNameSchema.parse('agent.activity.report.weekly.generate'),
  ActivityReportMonthlyGenerate: AgentCommandNameSchema.parse('agent.activity.report.monthly.generate'),
  ActivityReportSave: AgentCommandNameSchema.parse('agent.activity.report.save'),
  ActivityReportHistoryList: AgentCommandNameSchema.parse('agent.activity.report.history.list'),
  ActivityScreenReadModelGet: AgentCommandNameSchema.parse('agent.activity.screen.read-model.get'),
  ActivityAppUseReadModelGet: AgentCommandNameSchema.parse('agent.activity.app-use.read-model.get'),
  ActivityBrowserReadModelGet: AgentCommandNameSchema.parse('agent.activity.browser.read-model.get'),
  ActivityGamesReadModelGet: AgentCommandNameSchema.parse('agent.activity.games.read-model.get'),
  ActivityAppGameBoundaryReadModelGet: AgentCommandNameSchema.parse('agent.activity.app-game.boundary.read-model.get'),
  ActivityAppGamePolicyReadinessReadModelGet: AgentCommandNameSchema.parse(
    'agent.activity.app-game.policy-readiness.read-model.get'
  ),
  ActivityAppGameNotificationReadinessReadModelGet: AgentCommandNameSchema.parse(
    'agent.activity.app-game.notification-readiness.read-model.get'
  ),
  BrowserSocialDashboardReadModelGet: AgentCommandNameSchema.parse('agent.browser.social-dashboard.read-model.get'),
  BrowserSocialAuditExplanationReadModelGet: AgentCommandNameSchema.parse(
    'agent.browser.social-audit-explanation.read-model.get'
  ),
  BrowserSocialAlertReportReadModelGet: AgentCommandNameSchema.parse(
    'agent.browser.social-alert-report.read-model.get'
  ),
  BrowserSocialSourceCustodyMutationApply: AgentCommandNameSchema.parse(
    'agent.browser.social-source-custody.mutation.apply'
  ),
  ActivityNetworkReadModelGet: AgentCommandNameSchema.parse('agent.activity.network.read-model.get'),
  ActivityTrackingReadModelGet: AgentCommandNameSchema.parse('agent.activity.tracking.read-model.get'),
  BrowserInventoryReadModelGet: AgentCommandNameSchema.parse('agent.browser.inventory.read-model.get'),
  BrowserEvidenceRecentGet: AgentCommandNameSchema.parse('agent.browser.evidence.recent.get'),
  BrowserManagedBridgePoll: AgentCommandNameSchema.parse('agent.browser.managed.bridge.poll'),
  BrowserInterventionReadModelGet: AgentCommandNameSchema.parse('agent.browser.intervention.read-model.get'),
  NetworkFlowReadModelGet: AgentCommandNameSchema.parse('agent.network.flow.read-model.get'),
  NetworkRuntimeEventChainStreamGet: AgentCommandNameSchema.parse('agent.network.runtime.event-chain.stream.get'),
  NetworkRemoteDeliveryStatusGet: AgentCommandNameSchema.parse('agent.network.remote-delivery.status.get'),
  NetworkLiveCaptureStatusGet: AgentCommandNameSchema.parse('agent.network.live-capture.status.get'),
  NetworkLinuxNftablesLabStatusGet: AgentCommandNameSchema.parse('agent.network.linux-nftables-lab.status.get'),
  NetworkWindowsFirewallLabStatusGet: AgentCommandNameSchema.parse('agent.network.windows-firewall-lab.status.get'),
  NetworkWindowsWfpGateStatusGet: AgentCommandNameSchema.parse('agent.network.windows-wfp-gate.status.get'),
  LocalAiRuntimeStatusGet: AgentCommandNameSchema.parse('agent.local-ai.runtime.status.get'),
  LocalAiChatGenerate: AgentCommandNameSchema.parse('agent.local-ai.chat.generate'),
  ParentAssistantAnswerGenerate: AgentCommandNameSchema.parse('agent.parent-assistant.answer.generate'),
  PolicyPreviewReadModelGet: AgentCommandNameSchema.parse('agent.policy.preview.read-model.get'),
  BrowserPolicyGet: AgentCommandNameSchema.parse('agent.browser-policy.get'),
  BrowserPolicyPreview: AgentCommandNameSchema.parse('agent.browser-policy.preview'),
  BrowserPolicyPatch: AgentCommandNameSchema.parse('agent.browser-policy.patch'),
  BrowserPolicyReplace: AgentCommandNameSchema.parse('agent.browser-policy.replace'),
  BrowserPolicyRollback: AgentCommandNameSchema.parse('agent.browser-policy.rollback'),
  EnforcementExecute: AgentCommandNameSchema.parse('agent.enforcement.execute'),
  EnforcementTimerRecover: AgentCommandNameSchema.parse('agent.enforcement.timer.recover'),
  EnforcementTimerExpire: AgentCommandNameSchema.parse('agent.enforcement.timer.expire'),
  EnforcementOverrideCancel: AgentCommandNameSchema.parse('agent.enforcement.override.cancel'),
  EnforcementProductControlSpineGet: AgentCommandNameSchema.parse('agent.enforcement.product-control-spine.get'),
  EnforcementPolicyDispatchGet: AgentCommandNameSchema.parse('agent.enforcement.policy-dispatch.get'),
  EnforcementBroadAdapterProofGet: AgentCommandNameSchema.parse('agent.enforcement.broad-adapter-proof.get'),
  EnforcementSupportedAdapterRuntimeProofGet: AgentCommandNameSchema.parse(
    'agent.enforcement.supported-adapter-runtime-proof.get'
  ),
  ParentAssistantThreadList: AgentCommandNameSchema.parse('agent.parent-assistant.thread.list'),
  ParentAssistantThreadCreate: AgentCommandNameSchema.parse('agent.parent-assistant.thread.create'),
  ParentAssistantThreadOpen: AgentCommandNameSchema.parse('agent.parent-assistant.thread.open'),
  ParentAssistantThreadArchive: AgentCommandNameSchema.parse('agent.parent-assistant.thread.archive'),
  ParentAssistantMessageSend: AgentCommandNameSchema.parse('agent.parent-assistant.message.send'),
  ParentAssistantRunCancel: AgentCommandNameSchema.parse('agent.parent-assistant.run.cancel'),
  ParentAssistantQuickActionStart: AgentCommandNameSchema.parse('agent.parent-assistant.quick-action.start'),
  ParentAssistantActionPreview: AgentCommandNameSchema.parse('agent.parent-assistant.action.preview'),
  ParentAssistantActionConfirm: AgentCommandNameSchema.parse('agent.parent-assistant.action.confirm'),
  ParentAssistantProviderStatusGet: AgentCommandNameSchema.parse('agent.parent-assistant.provider.status.get'),
  LanPairingProofSubmit: AgentCommandNameSchema.parse('agent.lan-pairing.proof.submit'),
  LanPairingRouteSelect: AgentCommandNameSchema.parse('agent.lan-pairing.route.select'),
  LanPairingRouteRevoke: AgentCommandNameSchema.parse('agent.lan-pairing.route.revoke'),
  LanPairingStatusGet: AgentCommandNameSchema.parse('agent.lan-pairing.status.get'),
  LanPairingBrowserDiscoveryScan: AgentCommandNameSchema.parse('agent.lan-pairing.browser-discovery.scan'),
  LanPairingAddDeviceRequest: AgentCommandNameSchema.parse('agent.lan-pairing.add-device.request'),
  LanPairingControllerLeaseRenew: AgentCommandNameSchema.parse('agent.lan-pairing.controller-lease.renew'),
  LanPairingControllerLeaseRelease: AgentCommandNameSchema.parse('agent.lan-pairing.controller-lease.release'),
  LanPairingControllerLeaseTakeover: AgentCommandNameSchema.parse('agent.lan-pairing.controller-lease.takeover'),
  LanAiProviderStatusGet: AgentCommandNameSchema.parse('agent.lan-ai.provider.status.get'),
  LanAiJobSubmit: AgentCommandNameSchema.parse('agent.lan-ai.job.submit'),
} as const;

export const AgentLanPairingSupportedWebSocketCommand = {
  ProofSubmit: AgentCommand.LanPairingProofSubmit,
  RouteSelect: AgentCommand.LanPairingRouteSelect,
  RouteRevoke: AgentCommand.LanPairingRouteRevoke,
  StatusGet: AgentCommand.LanPairingStatusGet,
  BrowserDiscoveryScan: AgentCommand.LanPairingBrowserDiscoveryScan,
  AddDeviceRequest: AgentCommand.LanPairingAddDeviceRequest,
  ControllerLeaseRenew: AgentCommand.LanPairingControllerLeaseRenew,
  ControllerLeaseRelease: AgentCommand.LanPairingControllerLeaseRelease,
  ControllerLeaseTakeover: AgentCommand.LanPairingControllerLeaseTakeover,
  LanAiProviderStatusGet: AgentCommand.LanAiProviderStatusGet,
  LanAiJobSubmit: AgentCommand.LanAiJobSubmit,
} as const;

export const AgentEvent = {
  ConnectionReady: AgentEventNameSchema.parse('agent.connection.ready'),
  CommandRejected: AgentEventNameSchema.parse('agent.command.rejected'),
  HealthReported: AgentEventNameSchema.parse('agent.health.reported'),
  LogSnapshotReported: AgentEventNameSchema.parse('agent.log.snapshot.reported'),
  DevEchoed: AgentEventNameSchema.parse('agent.dev.echoed'),
  WatchStatusReported: AgentEventNameSchema.parse('agent.watch.status.reported'),
  ActivityIngestStatusReported: AgentEventNameSchema.parse('agent.activity.ingest.status.reported'),
  ActivityRecentSummaryReported: AgentEventNameSchema.parse('agent.activity.recent.summary.reported'),
  ActivityMemoryGraphReported: AgentEventNameSchema.parse('agent.activity.memory-graph.reported'),
  ActivityReportGenerated: AgentEventNameSchema.parse('agent.activity.report.generated'),
  ActivityReportSaved: AgentEventNameSchema.parse('agent.activity.report.saved'),
  ActivityReportHistoryReported: AgentEventNameSchema.parse('agent.activity.report.history.reported'),
  ActivityScreenReadModelReported: AgentEventNameSchema.parse('agent.activity.screen.read-model.reported'),
  ActivityAppUseReadModelReported: AgentEventNameSchema.parse('agent.activity.app-use.read-model.reported'),
  ActivityBrowserReadModelReported: AgentEventNameSchema.parse('agent.activity.browser.read-model.reported'),
  ActivityGamesReadModelReported: AgentEventNameSchema.parse('agent.activity.games.read-model.reported'),
  ActivityAppGameBoundaryReadModelReported: AgentEventNameSchema.parse(
    'agent.activity.app-game.boundary.read-model.reported'
  ),
  ActivityAppGamePolicyReadinessReadModelReported: AgentEventNameSchema.parse(
    'agent.activity.app-game.policy-readiness.read-model.reported'
  ),
  ActivityAppGameNotificationReadinessReadModelReported: AgentEventNameSchema.parse(
    'agent.activity.app-game.notification-readiness.read-model.reported'
  ),
  BrowserSocialDashboardReadModelReported: AgentEventNameSchema.parse(
    'agent.browser.social-dashboard.read-model.reported'
  ),
  BrowserSocialAuditExplanationReadModelReported: AgentEventNameSchema.parse(
    'agent.browser.social-audit-explanation.read-model.reported'
  ),
  BrowserSocialAlertReportReadModelReported: AgentEventNameSchema.parse(
    'agent.browser.social-alert-report.read-model.reported'
  ),
  BrowserSocialSourceCustodyMutationApplied: AgentEventNameSchema.parse(
    'agent.browser.social-source-custody.mutation.applied'
  ),
  ActivityNetworkReadModelReported: AgentEventNameSchema.parse('agent.activity.network.read-model.reported'),
  ActivityTrackingReadModelReported: AgentEventNameSchema.parse('agent.activity.tracking.read-model.reported'),
  BrowserInventoryReadModelReported: AgentEventNameSchema.parse('agent.browser.inventory.read-model.reported'),
  BrowserEvidenceRecentReported: AgentEventNameSchema.parse('agent.browser.evidence.recent.reported'),
  BrowserManagedStatusReported: AgentEventNameSchema.parse('agent.browser.managed.status.reported'),
  BrowserInterventionReadModelReported: AgentEventNameSchema.parse('agent.browser.intervention.read-model.reported'),
  NetworkFlowReadModelReported: AgentEventNameSchema.parse('agent.network.flow.read-model.reported'),
  NetworkRuntimeEventChainStreamReported: AgentEventNameSchema.parse(
    'agent.network.runtime.event-chain.stream.reported'
  ),
  NetworkRemoteDeliveryStatusReported: AgentEventNameSchema.parse('agent.network.remote-delivery.status.reported'),
  NetworkLiveCaptureStatusReported: AgentEventNameSchema.parse('agent.network.live-capture.status.reported'),
  NetworkLinuxNftablesLabStatusReported: AgentEventNameSchema.parse('agent.network.linux-nftables-lab.status.reported'),
  NetworkWindowsFirewallLabStatusReported: AgentEventNameSchema.parse(
    'agent.network.windows-firewall-lab.status.reported'
  ),
  NetworkWindowsWfpGateStatusReported: AgentEventNameSchema.parse('agent.network.windows-wfp-gate.status.reported'),
  LocalAiRuntimeStatusReported: AgentEventNameSchema.parse('agent.local-ai.runtime.status.reported'),
  LocalAiChatGenerationReported: AgentEventNameSchema.parse('agent.local-ai.chat.generation.reported'),
  ParentAssistantAnswerReported: AgentEventNameSchema.parse('agent.parent-assistant.answer.reported'),
  PolicyPreviewReadModelReported: AgentEventNameSchema.parse('agent.policy.preview.read-model.reported'),
  BrowserPolicyReported: AgentEventNameSchema.parse('agent.browser-policy.reported'),
  BrowserPolicyPreviewed: AgentEventNameSchema.parse('agent.browser-policy.previewed'),
  BrowserPolicyPatchAccepted: AgentEventNameSchema.parse('agent.browser-policy.patch.accepted'),
  BrowserPolicyPatchRejected: AgentEventNameSchema.parse('agent.browser-policy.patch.rejected'),
  BrowserPolicyReplaceAccepted: AgentEventNameSchema.parse('agent.browser-policy.replace.accepted'),
  BrowserPolicyReplaceRejected: AgentEventNameSchema.parse('agent.browser-policy.replace.rejected'),
  BrowserPolicyRollbackAccepted: AgentEventNameSchema.parse('agent.browser-policy.rollback.accepted'),
  BrowserPolicyRollbackRejected: AgentEventNameSchema.parse('agent.browser-policy.rollback.rejected'),
  EnforcementAuditReported: AgentEventNameSchema.parse('agent.enforcement.audit.reported'),
  EnforcementTimerReported: AgentEventNameSchema.parse('agent.enforcement.timer.reported'),
  EnforcementProductControlSpineReported: AgentEventNameSchema.parse(
    'agent.enforcement.product-control-spine.reported'
  ),
  EnforcementPolicyDispatchReported: AgentEventNameSchema.parse('agent.enforcement.policy-dispatch.reported'),
  EnforcementBroadAdapterProofReported: AgentEventNameSchema.parse('agent.enforcement.broad-adapter-proof.reported'),
  EnforcementSupportedAdapterRuntimeProofReported: AgentEventNameSchema.parse(
    'agent.enforcement.supported-adapter-runtime-proof.reported'
  ),
  ParentAssistantThreadUpdated: AgentEventNameSchema.parse('agent.parent-assistant.thread.updated'),
  ParentAssistantMessageAccepted: AgentEventNameSchema.parse('agent.parent-assistant.message.accepted'),
  ParentAssistantRunStarted: AgentEventNameSchema.parse('agent.parent-assistant.run.started'),
  ParentAssistantMessageDelta: AgentEventNameSchema.parse('agent.parent-assistant.message.delta'),
  ParentAssistantMessageCompleted: AgentEventNameSchema.parse('agent.parent-assistant.message.completed'),
  ParentAssistantActionPreviewed: AgentEventNameSchema.parse('agent.parent-assistant.action.previewed'),
  ParentAssistantActionConfirmed: AgentEventNameSchema.parse('agent.parent-assistant.action.confirmed'),
  ParentAssistantProviderDegraded: AgentEventNameSchema.parse('agent.parent-assistant.provider.degraded'),
  ParentAssistantErrorReported: AgentEventNameSchema.parse('agent.parent-assistant.error.reported'),
  LanPairingStatusReported: AgentEventNameSchema.parse('agent.lan-pairing.status.reported'),
  LanPairingBrowserDiscoveryReported: AgentEventNameSchema.parse('agent.lan-pairing.browser-discovery.reported'),
  LanPairingAddDeviceReported: AgentEventNameSchema.parse('agent.lan-pairing.add-device.reported'),
  LanPairingAuditReported: AgentEventNameSchema.parse('agent.lan-pairing.audit.reported'),
  LanAiJobReported: AgentEventNameSchema.parse('agent.lan-ai.job.reported'),
} as const;
