import { Schema } from '@ocentra-parent/schema-domain/effect';
import {
  AgentMessageTargetSchema,
  AgentPeerSchema,
  AgentProtocolSchemaVersion,
  AgentWebSocketUrlSchema,
} from './primitives';
import { AgentPairingStateSchema, AgentRouteSecurityPolicySchema } from './security';

const decodeAgentWebSocketUrl = Schema.decodeUnknownSync(AgentWebSocketUrlSchema);

export const AgentProtocolDefaults = {
  SchemaVersion: AgentProtocolSchemaVersion,
  WebSocketUrl: decodeAgentWebSocketUrl('ws://127.0.0.1:4477/api/dev/ws'),
  MessageIdPrefix: 'cmd-',
  Peer: {
    PortalDev: AgentPeerSchema.parse({
      peerId: 'portal-dev',
      role: 'portal',
    }),
  },
  Target: {
    LocalhostWindowsAgent: AgentMessageTargetSchema.parse({
      deviceId: 'local-dev-agent',
      platform: 'windows',
      route: 'localhost',
    }),
    LocalNetworkWindowsAgent: AgentMessageTargetSchema.parse({
      deviceId: 'local-dev-agent',
      platform: 'windows',
      route: 'local-network',
    }),
  },
  PairingState: {
    Unpaired: AgentPairingStateSchema.parse('unpaired'),
    Pairing: AgentPairingStateSchema.parse('pairing'),
    Paired: AgentPairingStateSchema.parse('paired'),
    Revoked: AgentPairingStateSchema.parse('revoked'),
  },
  RouteSecurity: {
    Localhost: AgentRouteSecurityPolicySchema.parse({
      route: 'localhost',
      requiresPairing: false,
      allowsAnonymousControl: true,
    }),
    LocalNetwork: AgentRouteSecurityPolicySchema.parse({
      route: 'local-network',
      requiresPairing: true,
      allowsAnonymousControl: false,
    }),
    CloudRelay: AgentRouteSecurityPolicySchema.parse({
      route: 'cloud-relay',
      requiresPairing: true,
      allowsAnonymousControl: false,
    }),
  },
  Host: {
    LoopbackIp: '127.0.0.1',
    LocalhostName: 'localhost',
  },
  Field: {
    Available: 'available',
    ActiveState: 'activeState',
    AdapterId: 'adapterId',
    BridgeEndpointRef: 'bridgeEndpointRef',
    BridgeKind: 'bridgeKind',
    BrowserEvidenceId: 'browserEvidenceId',
    BrowserChannel: 'browserChannel',
    BrowserFamily: 'browserFamily',
    BrowserVersion: 'browserVersion',
    BytesReceived: 'bytesReceived',
    BytesSent: 'bytesSent',
    CapabilityStatus: 'capabilityStatus',
    CheckedAt: 'checkedAt',
    ConnectionCount: 'connectionCount',
    Custody: 'custody',
    CustodyLabel: 'custodyLabel',
    DatabaseReady: 'databaseReady',
    DestinationDomain: 'destinationDomain',
    DestinationIp: 'destinationIp',
    DestinationPort: 'destinationPort',
    Domain: 'domain',
    DomainAttributionStatus: 'domainAttributionStatus',
    DuplicateEvents: 'duplicateEvents',
    Entries: 'entries',
    EventsIngested: 'eventsIngested',
    EventsStored: 'eventsStored',
    FirstObservedAt: 'firstObservedAt',
    FirstSeenAt: 'firstSeenAt',
    GeneratedAt: 'generatedAt',
    LastEventId: 'lastEventId',
    LastObservedAt: 'lastObservedAt',
    LastSeenAt: 'lastSeenAt',
    LatestEventId: 'latestEventId',
    LatestObservedAt: 'latestObservedAt',
    Limit: 'limit',
    LoadState: 'loadState',
    LocalIp: 'localIp',
    LocalPort: 'localPort',
    LocalAiRuntimeReferenceId: 'runtimeReferenceId',
    LocalAiProviderId: 'providerId',
    LocalAiModelId: 'modelId',
    LocalAiModelReference: 'modelReference',
    LocalAiCapabilityFlags: 'capabilityFlags',
    LocalAiResourceClass: 'resourceClass',
    LocalAiDegradedState: 'degradedState',
    LocalAiUnavailableReason: 'unavailableReason',
    LocalAiPrivacyMode: 'privacyMode',
    LocalAiAdapterBoundary: 'adapterBoundary',
    LocalAiExecutionState: 'executionState',
    LocalAiProviderSource: 'providerSource',
    LocalAiAdapterProbeState: 'probeState',
    LocalAiProviderConfigurationState: 'configurationState',
    LocalAiAdapterReadinessState: 'readinessState',
    LocalAiExecutionAllowed: 'executionAllowed',
    LocalAiResultId: 'localAiResultId',
    ManagedBrowserSessionId: 'managedBrowserSessionId',
    ManagedState: 'managedState',
    Message: 'message',
    MostRecentKind: 'mostRecentKind',
    MostRecentObserver: 'mostRecentObserver',
    MostRecentSubjectId: 'mostRecentSubjectId',
    MostRecentSubjectKind: 'mostRecentSubjectKind',
    MostRecentSubjectName: 'mostRecentSubjectName',
    NetworkProtocol: 'networkProtocol',
    Observer: 'observer',
    Online: 'online',
    Origin: 'origin',
    ProcessId: 'processId',
    PolicyAction: 'policyAction',
    PolicyDecisionId: 'policyDecisionId',
    PolicyDryRun: 'dryRun',
    PolicyEvidenceReferenceCount: 'evidenceReferenceCount',
    PolicyParentRuleContextReferenceCount: 'parentRuleContextReferenceCount',
    PolicyParentRuleContextRefIds: 'parentRuleContextRefIds',
    ProfileId: 'profileId',
    ProfilePathRef: 'profilePathRef',
    PolicyHandoffState: 'enforcementHandoffState',
    QueryVisibility: 'queryVisibility',
    ProcessAttributionStatus: 'processAttributionStatus',
    ProcessName: 'processName',
    PolicyPreviewId: 'policyPreviewId',
    PolicyReasonCodes: 'reasonCodes',
    PolicyRuleIds: 'ruleIds',
    PolicyTargetType: 'targetType',
    PolicyTargetValue: 'targetValue',
    Reason: 'reason',
    Returned: 'returned',
    SchemaVersion: 'schemaVersion',
    SourceId: 'sourceId',
    TargetId: 'targetId',
    TcpState: 'tcpState',
    Transport: 'transport',
    Title: 'title',
    Url: 'url',
    StartedAt: 'startedAt',
  },
  Primitive: {
    String: 'string',
  },
} as const;
