import { Schema } from '@ocentra-parent/schema-domain/effect';
import {
  AgentMessageTargetSchema,
  AgentPeerSchema,
  AgentProtocolSchemaVersion,
  AgentWebSocketUrlSchema,
} from './primitives';
import {
  AgentLanSelectedDeviceReachabilitySchema,
  AgentLanPairingRuntimeSupportStatusSchema,
  AgentPairingStateSchema,
  AgentRouteSecurityPolicySchema,
} from './security';

const decodeAgentWebSocketUrl = Schema.decodeUnknownSync(AgentWebSocketUrlSchema);

export const AgentProtocolDefaults = {
  SchemaVersion: AgentProtocolSchemaVersion,
  WebSocketUrl: decodeAgentWebSocketUrl('ws://127.0.0.1:4477/api/dev/ws'),
  MessageIdPrefix: 'cmd-',
  Peer: {
    PortalDev: AgentPeerSchema.parse({
      peerId: 'portal-dev',
      role: 'portal',
    }),
  },
  Target: {
    LocalhostWindowsAgent: AgentMessageTargetSchema.parse({
      deviceId: 'local-dev-agent',
      platform: 'windows',
      route: 'localhost',
    }),
    LocalNetworkWindowsAgent: AgentMessageTargetSchema.parse({
      deviceId: 'local-dev-agent',
      platform: 'windows',
      route: 'local-network',
    }),
  },
  PairingState: {
    Unauthenticated: AgentPairingStateSchema.parse('unauthenticated'),
    Unpaired: AgentPairingStateSchema.parse('unpaired'),
    Pairing: AgentPairingStateSchema.parse('pairing'),
    Paired: AgentPairingStateSchema.parse('paired'),
    Revoked: AgentPairingStateSchema.parse('revoked'),
  },
  LanSelectedDeviceReachability: {
    Online: AgentLanSelectedDeviceReachabilitySchema.parse('online'),
    Offline: AgentLanSelectedDeviceReachabilitySchema.parse('offline'),
    Stale: AgentLanSelectedDeviceReachabilitySchema.parse('stale'),
  },
  LanRuntimeSupportStatus: {
    PlannedUnsupported: AgentLanPairingRuntimeSupportStatusSchema.parse('planned-unsupported'),
  },
  RouteSecurity: {
    Localhost: AgentRouteSecurityPolicySchema.parse({
      route: 'localhost',
      requiresPairing: false,
      allowsAnonymousControl: true,
    }),
    LocalNetwork: AgentRouteSecurityPolicySchema.parse({
      route: 'local-network',
      requiresPairing: true,
      allowsAnonymousControl: false,
    }),
    CloudRelay: AgentRouteSecurityPolicySchema.parse({
      route: 'cloud-relay',
      requiresPairing: true,
      allowsAnonymousControl: false,
    }),
  },
  Host: {
    LoopbackIp: '127.0.0.1',
    LocalhostName: 'localhost',
  },
  Field: {
    Available: 'available',
    ActiveState: 'activeState',
    AdapterId: 'adapterId',
    ActivityDigest: 'activityDigest',
    BridgeEndpointRef: 'bridgeEndpointRef',
    BridgeKind: 'bridgeKind',
    BrowserEvidenceId: 'browserEvidenceId',
    BrowserChannel: 'browserChannel',
    BrowserFamily: 'browserFamily',
    BrowserInterventionId: 'browserInterventionId',
    BrowserVersion: 'browserVersion',
    BytesReceived: 'bytesReceived',
    BytesSent: 'bytesSent',
    CapabilityStatus: 'capabilityStatus',
    CheckedAt: 'checkedAt',
    ConnectionCount: 'connectionCount',
    Custody: 'custody',
    CustodyLabel: 'custodyLabel',
    DatabaseReady: 'databaseReady',
    DestinationDomain: 'destinationDomain',
    DestinationIp: 'destinationIp',
    DestinationPort: 'destinationPort',
    Domain: 'domain',
    DomainAttributionStatus: 'domainAttributionStatus',
    DuplicateEvents: 'duplicateEvents',
    DecisionSource: 'decisionSource',
    Entries: 'entries',
    EventsIngested: 'eventsIngested',
    EventsStored: 'eventsStored',
    FirstObservedAt: 'firstObservedAt',
    FirstSeenAt: 'firstSeenAt',
    FreshUntil: 'freshUntil',
    GeneratedAt: 'generatedAt',
    LastEventId: 'lastEventId',
    LastObservedAt: 'lastObservedAt',
    LastSeenAt: 'lastSeenAt',
    LatestEventId: 'latestEventId',
    LatestObservedAt: 'latestObservedAt',
    LanAuthenticationState: 'authenticationState',
    LanAddressRef: 'addressRef',
    LanAgentPeerId: 'agentPeerId',
    LanChallengeId: 'challengeId',
    LanChallengeStatus: 'challengeStatus',
    LanChildDeviceId: 'childDeviceId',
    LanControlState: 'controlState',
    LanDiscoveryStatus: 'discoveryStatus',
    LanIntentId: 'intentId',
    LanPairingId: 'pairingId',
    LanPairingState: 'pairingState',
    LanParentDeviceId: 'parentDeviceId',
    LanProofDigest: 'proofDigest',
    LanProofPreviewStatus: 'proofPreviewStatus',
    LanRejectionReason: 'rejectionReason',
    LanRevokedDeviceIds: 'revokedDeviceIds',
    LanRouteId: 'routeId',
    LanSelectedChildDeviceId: 'selectedChildDeviceId',
    LanSelectedDeviceReachability: 'selectedDeviceReachability',
    LanSelectedDeviceStaleAt: 'selectedDeviceStaleAt',
    LanSelectedRouteId: 'selectedRouteId',
    LanTrustedDeviceIds: 'trustedDeviceIds',
    LanTrustedDeviceCount: 'trustedDeviceCount',
    Limit: 'limit',
    LoadState: 'loadState',
    LocalIp: 'localIp',
    LocalPort: 'localPort',
    LocalAiRuntimeReferenceId: 'runtimeReferenceId',
    LocalAiProviderId: 'providerId',
    LocalAiModelId: 'modelId',
    LocalAiModelReference: 'modelReference',
    LocalAiModelArtifactRef: 'artifactRef',
    LocalAiModelManifestRef: 'manifestRef',
    LocalAiModelSourcePolicy: 'sourcePolicy',
    LocalAiModelCacheState: 'cacheState',
    LocalAiModelCacheHealth: 'cacheHealth',
    LocalAiModelManifestIntegrity: 'manifestIntegrity',
    LocalAiModelDownloadEnabled: 'downloadEnabled',
    LocalAiModelDownloadStatus: 'downloadStatus',
    LocalAiModelCacheByteSize: 'cacheByteSize',
    LocalAiModelCacheUnavailableReason: 'cacheUnavailableReason',
    LocalAiModelCacheStorageError: 'storageError',
    LocalAiModelCacheCorruptionReason: 'corruptionReason',
    LocalAiCapabilityFlags: 'capabilityFlags',
    LocalAiResourceClass: 'resourceClass',
    LocalAiDegradedState: 'degradedState',
    LocalAiUnavailableReason: 'unavailableReason',
    LocalAiPrivacyMode: 'privacyMode',
    LocalAiAdapterBoundary: 'adapterBoundary',
    LocalAiExecutionState: 'executionState',
    LocalAiProviderSource: 'providerSource',
    LocalAiAdapterProbeState: 'probeState',
    LocalAiProviderConfigurationState: 'configurationState',
    LocalAiAdapterReadinessState: 'readinessState',
    LocalAiExecutionAllowed: 'executionAllowed',
    LocalAiResultId: 'localAiResultId',
    LocalAiGenerationState: 'generationState',
    LocalAiOutputText: 'outputText',
    LocalAiPrompt: 'prompt',
    LocalAiPromptCharCount: 'promptCharCount',
    LocalAiMaxOutputTokens: 'maxOutputTokens',
    LocalAiTimeoutMs: 'timeoutMs',
    LocalAiDurationMs: 'durationMs',
    LocalAiExitCode: 'exitCode',
    LocalAiStderrByteSize: 'stderrByteSize',
    ManagedBrowserSessionId: 'managedBrowserSessionId',
    ManagedSessionInterventionCapability: 'managedSessionInterventionCapability',
    ManagedState: 'managedState',
    Message: 'message',
    MostRecentKind: 'mostRecentKind',
    MostRecentObserver: 'mostRecentObserver',
    MostRecentSubjectId: 'mostRecentSubjectId',
    MostRecentSubjectKind: 'mostRecentSubjectKind',
    MostRecentSubjectName: 'mostRecentSubjectName',
    NetworkProtocol: 'networkProtocol',
    Observer: 'observer',
    Online: 'online',
    Origin: 'origin',
    ObservedUrl: 'observedUrl',
    ProcessId: 'processId',
    PolicyAction: 'policyAction',
    PolicyDecisionId: 'policyDecisionId',
    PolicyDryRun: 'dryRun',
    PolicyEvidenceReferenceCount: 'evidenceReferenceCount',
    PolicyParentRuleContextReferenceCount: 'parentRuleContextReferenceCount',
    PolicyParentRuleContextRefIds: 'parentRuleContextRefIds',
    ProfileId: 'profileId',
    ProfilePathRef: 'profilePathRef',
    PolicyHandoffState: 'enforcementHandoffState',
    QueryVisibility: 'queryVisibility',
    ProcessAttributionStatus: 'processAttributionStatus',
    ProcessName: 'processName',
    PolicyPreviewId: 'policyPreviewId',
    PolicyReasonCodes: 'reasonCodes',
    PolicyRuleIds: 'ruleIds',
    PolicyTargetType: 'targetType',
    PolicyTargetValue: 'targetValue',
    Reason: 'reason',
    Returned: 'returned',
    RequestedUrl: 'requestedUrl',
    SchemaVersion: 'schemaVersion',
    SourceId: 'sourceId',
    StaleAt: 'staleAt',
    TargetId: 'targetId',
    InterventionAction: 'interventionAction',
    InterventionMechanism: 'interventionMechanism',
    InterventionOutcome: 'interventionOutcome',
    InterventionTargetType: 'interventionTargetType',
    InterventionTargetValue: 'interventionTargetValue',
    TabId: 'tabId',
    TcpState: 'tcpState',
    Transport: 'transport',
    Title: 'title',
    Url: 'url',
    UnmanagedBrowserEnforcement: 'unmanagedBrowserEnforcement',
    StartedAt: 'startedAt',
    WindowId: 'windowId',
  },
  Primitive: {
    String: 'string',
  },
} as const;
