import { Schema } from '@ocentra-parent/schema-domain/effect';
import {
  AgentMessageTargetSchema,
  AgentPeerSchema,
  AgentProtocolSchemaVersion,
  AgentWebSocketUrlSchema,
} from './primitives';
import {
  AgentLanPairingIntentKindSchema,
  AgentLanPairingProductionDiscoveryStateSchema,
  AgentLanSelectedDeviceReachabilitySchema,
  AgentLanSelectedRouteTrustStateSchema,
  AgentLanAiProviderRoutingStateSchema,
  AgentLanPairingRuntimeSupportStatusSchema,
  AgentLanPairingResponseStateSchema,
  AgentPairingStateSchema,
  AgentRouteSecurityPolicySchema,
} from './security';

const decodeAgentWebSocketUrl = Schema.decodeUnknownSync(AgentWebSocketUrlSchema);

export const AgentProtocolDefaults = {
  SchemaVersion: AgentProtocolSchemaVersion,
  WebSocketUrl: decodeAgentWebSocketUrl('ws://127.0.0.1:4477/api/dev/ws'),
  MessageIdPrefix: 'cmd-',
  Peer: {
    PortalDev: AgentPeerSchema.parse({
      peerId: 'portal-dev',
      role: 'portal',
    }),
  },
  Target: {
    LocalhostWindowsAgent: AgentMessageTargetSchema.parse({
      deviceId: 'local-dev-agent',
      platform: 'windows',
      route: 'localhost',
    }),
    LocalNetworkWindowsAgent: AgentMessageTargetSchema.parse({
      deviceId: 'local-dev-agent',
      platform: 'windows',
      route: 'local-network',
    }),
  },
  PairingState: {
    Unauthenticated: AgentPairingStateSchema.parse('unauthenticated'),
    Unpaired: AgentPairingStateSchema.parse('unpaired'),
    Pairing: AgentPairingStateSchema.parse('pairing'),
    Paired: AgentPairingStateSchema.parse('paired'),
    Revoked: AgentPairingStateSchema.parse('revoked'),
  },
  LanSelectedDeviceReachability: {
    Online: AgentLanSelectedDeviceReachabilitySchema.parse('online'),
    Offline: AgentLanSelectedDeviceReachabilitySchema.parse('offline'),
    Stale: AgentLanSelectedDeviceReachabilitySchema.parse('stale'),
  },
  LanSelectedRouteTrustState: {
    Unpaired: AgentLanSelectedRouteTrustStateSchema.parse('unpaired'),
    Paired: AgentLanSelectedRouteTrustStateSchema.parse('paired'),
    Revoked: AgentLanSelectedRouteTrustStateSchema.parse('revoked'),
    Expired: AgentLanSelectedRouteTrustStateSchema.parse('expired'),
  },
  LanProductionDiscoveryState: {
    Discovered: AgentLanPairingProductionDiscoveryStateSchema.parse('discovered'),
    Pending: AgentLanPairingProductionDiscoveryStateSchema.parse('pending'),
    Paired: AgentLanPairingProductionDiscoveryStateSchema.parse('paired'),
    Revoked: AgentLanPairingProductionDiscoveryStateSchema.parse('revoked'),
    Stale: AgentLanPairingProductionDiscoveryStateSchema.parse('stale'),
    Offline: AgentLanPairingProductionDiscoveryStateSchema.parse('offline'),
    Unavailable: AgentLanPairingProductionDiscoveryStateSchema.parse('unavailable'),
  },
  LanAiProviderRoutingState: {
    AuthorizedResult: AgentLanAiProviderRoutingStateSchema.parse('authorized-result'),
    Busy: AgentLanAiProviderRoutingStateSchema.parse('busy'),
    Degraded: AgentLanAiProviderRoutingStateSchema.parse('degraded'),
    Unavailable: AgentLanAiProviderRoutingStateSchema.parse('unavailable'),
    UnsupportedCapability: AgentLanAiProviderRoutingStateSchema.parse('unsupported-capability'),
  },
  LanRuntimeSupportStatus: {
    PlannedUnsupported: AgentLanPairingRuntimeSupportStatusSchema.parse('planned-unsupported'),
  },
  LanIntentKind: {
    HealthQuery: AgentLanPairingIntentKindSchema.parse('health-query'),
    RuleQuery: AgentLanPairingIntentKindSchema.parse('rule-query'),
    RuleUpdate: AgentLanPairingIntentKindSchema.parse('rule-update'),
    ApprovalDecision: AgentLanPairingIntentKindSchema.parse('approval-decision'),
    ConfigurationUpdate: AgentLanPairingIntentKindSchema.parse('configuration-update'),
    ControllerLeaseRenew: AgentLanPairingIntentKindSchema.parse('controller-lease-renew'),
    ControllerLeaseRelease: AgentLanPairingIntentKindSchema.parse('controller-lease-release'),
    ControllerLeaseTakeover: AgentLanPairingIntentKindSchema.parse('controller-lease-takeover'),
    LanAiProviderStatus: AgentLanPairingIntentKindSchema.parse('lan-ai-provider-status'),
    LanAiJobSubmit: AgentLanPairingIntentKindSchema.parse('lan-ai-job-submit'),
  },
  LanResponseState: {
    Accepted: AgentLanPairingResponseStateSchema.parse('accepted'),
    Rejected: AgentLanPairingResponseStateSchema.parse('rejected'),
    Queued: AgentLanPairingResponseStateSchema.parse('queued'),
    Completed: AgentLanPairingResponseStateSchema.parse('completed'),
    Degraded: AgentLanPairingResponseStateSchema.parse('degraded'),
  },
  RouteSecurity: {
    Localhost: AgentRouteSecurityPolicySchema.parse({
      route: 'localhost',
      requiresPairing: false,
      allowsAnonymousControl: true,
    }),
    LocalNetwork: AgentRouteSecurityPolicySchema.parse({
      route: 'local-network',
      requiresPairing: true,
      allowsAnonymousControl: false,
    }),
    CloudRelay: AgentRouteSecurityPolicySchema.parse({
      route: 'cloud-relay',
      requiresPairing: true,
      allowsAnonymousControl: false,
    }),
  },
  Host: {
    LoopbackIp: '127.0.0.1',
    LocalhostName: 'localhost',
  },
  Field: {
    Available: 'available',
    ActiveState: 'activeState',
    AdapterId: 'adapterId',
    ActivityDigest: 'activityDigest',
    ActivityReportDocument: 'activityReportDocument',
    ActivityReportFrequency: 'activityReportFrequency',
    ActivityReportId: 'activityReportId',
    ActivityReports: 'activityReports',
    ActivityFamilySources: 'activityFamilySources',
    ActivityReadModel: 'activityReadModel',
    ActivityReadModelKind: 'activityReadModelKind',
    ActivitySurfaceState: 'activitySurfaceState',
    BridgeEndpointRef: 'bridgeEndpointRef',
    BridgeKind: 'bridgeKind',
    BrowserEvidenceId: 'browserEvidenceId',
    BrowserChannel: 'browserChannel',
    BrowserFamily: 'browserFamily',
    BrowserInterventionId: 'browserInterventionId',
    BrowserPolicyRequest: 'browserPolicyRequest',
    BrowserPolicyResponse: 'browserPolicyResponse',
    BrowserPolicyUpdateKind: 'browserPolicyUpdateKind',
    BrowserPolicyRejectionReason: 'browserPolicyRejectionReason',
    BrowserPolicyEffectivePolicy: 'browserPolicyEffectivePolicy',
    BrowserPolicyCapabilityRegistry: 'browserPolicyCapabilityRegistry',
    BrowserVersion: 'browserVersion',
    BytesReceived: 'bytesReceived',
    BytesSent: 'bytesSent',
    CapabilityStatus: 'capabilityStatus',
    CheckedAt: 'checkedAt',
    ConnectionCount: 'connectionCount',
    Custody: 'custody',
    CustodyLabel: 'custodyLabel',
    DatabaseReady: 'databaseReady',
    DestinationDomain: 'destinationDomain',
    DestinationIp: 'destinationIp',
    DestinationPort: 'destinationPort',
    DeviceId: 'deviceId',
    Domain: 'domain',
    DomainAttributionStatus: 'domainAttributionStatus',
    DuplicateEvents: 'duplicateEvents',
    EnforcementAction: 'enforcementAction',
    EnforcementActionId: 'enforcementActionId',
    EnforcementAdapterResultCode: 'enforcementAdapterResultCode',
    EnforcementAuditEvent: 'enforcementAuditEvent',
    EnforcementAuditEventId: 'enforcementAuditEventId',
    EnforcementCapabilityState: 'enforcementCapabilityState',
    EnforcementIntentId: 'enforcementIntentId',
    EnforcementJournalEventId: 'enforcementJournalEventId',
    EnforcementResult: 'enforcementResult',
    EnforcementResultId: 'enforcementResultId',
    EnforcementRollbackState: 'enforcementRollbackState',
    EnforcementStatus: 'enforcementStatus',
    EnforcementTimerEvent: 'enforcementTimerEvent',
    EnforcementTimerEventId: 'enforcementTimerEventId',
    EnforcementTimerEventKind: 'enforcementTimerEventKind',
    EnforcementTimerState: 'enforcementTimerState',
    EnforcementTimerStateId: 'enforcementTimerStateId',
    DecisionSource: 'decisionSource',
    Entries: 'entries',
    EventsIngested: 'eventsIngested',
    EventsStored: 'eventsStored',
    EvidenceReferenceIds: 'evidenceReferenceIds',
    ExpiresAt: 'expiresAt',
    FirstObservedAt: 'firstObservedAt',
    FirstSeenAt: 'firstSeenAt',
    FreshUntil: 'freshUntil',
    FamilyId: 'familyId',
    GeneratedAt: 'generatedAt',
    LastEventId: 'lastEventId',
    LastObservedAt: 'lastObservedAt',
    LastSeenAt: 'lastSeenAt',
    LatestEventId: 'latestEventId',
    LatestObservedAt: 'latestObservedAt',
    LanAuthenticationState: 'authenticationState',
    LanAddressRef: 'addressRef',
    LanAgentPeerId: 'agentPeerId',
    LanChallengeId: 'challengeId',
    LanChallengeStatus: 'challengeStatus',
    LanChildDeviceId: 'childDeviceId',
    LanControlState: 'controlState',
    LanControllerDeviceId: 'controllerDeviceId',
    LanControllerLeaseExpiresAt: 'controllerLeaseExpiresAt',
    LanControllerLeaseId: 'controllerLeaseId',
    LanControllerLeaseIssuedAt: 'controllerLeaseIssuedAt',
    LanParentAuthority: 'parentAuthority',
    LanAiProviderStatus: 'lanAiProviderStatus',
    LanAiProviderCustodyLabel: 'lanAiProviderCustodyLabel',
    LanAiProviderRoutingState: 'lanAiProviderRoutingState',
    LanAiJobId: 'lanAiJobId',
    LanAiJobStatus: 'lanAiJobStatus',
    LanAiJobState: 'lanAiJobState',
    LanDiscoveryState: 'discoveryState',
    LanDiscoveryStatus: 'discoveryStatus',
    LanEvidenceReferenceCount: 'evidenceReferenceCount',
    LanEvidenceReferenceIds: 'evidenceReferenceIds',
    LanIntentId: 'intentId',
    LanIntentKind: 'intentKind',
    LanPairingId: 'pairingId',
    LanPairingState: 'pairingState',
    LanParentActorId: 'parentActorId',
    LanParentDeviceId: 'parentDeviceId',
    LanProofDigest: 'proofDigest',
    LanProofPreviewStatus: 'proofPreviewStatus',
    LanRejectionReason: 'rejectionReason',
    LanResponseState: 'state',
    LanRevokedDeviceIds: 'revokedDeviceIds',
    LanRouteId: 'routeId',
    LanSelectedChildDeviceId: 'selectedChildDeviceId',
    LanSelectedDeviceReachability: 'selectedDeviceReachability',
    LanSelectedDeviceStaleAt: 'selectedDeviceStaleAt',
    LanSelectedPairingId: 'selectedPairingId',
    LanSelectedRouteId: 'selectedRouteId',
    LanSelectedRouteOfflineAt: 'selectedRouteOfflineAt',
    LanSelectedRouteStaleAt: 'selectedRouteStaleAt',
    LanSelectedRouteTrustState: 'selectedRouteTrustState',
    LanRestartBehavior: 'restartBehavior',
    LanTrustedDeviceIds: 'trustedDeviceIds',
    LanTrustedDeviceCount: 'trustedDeviceCount',
    Limit: 'limit',
    LoadState: 'loadState',
    LocalIp: 'localIp',
    LocalPort: 'localPort',
    LocalAiRuntimeReferenceId: 'runtimeReferenceId',
    LocalAiProviderId: 'providerId',
    LocalAiModelId: 'modelId',
    LocalAiModelReference: 'modelReference',
    LocalAiModelArtifactRef: 'artifactRef',
    LocalAiModelManifestRef: 'manifestRef',
    LocalAiModelSourcePolicy: 'sourcePolicy',
    LocalAiModelCacheState: 'cacheState',
    LocalAiModelCacheHealth: 'cacheHealth',
    LocalAiModelManifestIntegrity: 'manifestIntegrity',
    LocalAiModelDownloadEnabled: 'downloadEnabled',
    LocalAiModelDownloadStatus: 'downloadStatus',
    LocalAiModelCacheByteSize: 'cacheByteSize',
    LocalAiModelCacheUnavailableReason: 'cacheUnavailableReason',
    LocalAiModelCacheStorageError: 'storageError',
    LocalAiModelCacheCorruptionReason: 'corruptionReason',
    LocalAiCapabilityFlags: 'capabilityFlags',
    LocalAiResourceClass: 'resourceClass',
    LocalAiDegradedState: 'degradedState',
    LocalAiUnavailableReason: 'unavailableReason',
    LocalAiPrivacyMode: 'privacyMode',
    LocalAiAdapterBoundary: 'adapterBoundary',
    LocalAiExecutionState: 'executionState',
    LocalAiProviderSource: 'providerSource',
    LocalAiAdapterProbeState: 'probeState',
    LocalAiProviderConfigurationState: 'configurationState',
    LocalAiAdapterReadinessState: 'readinessState',
    LocalAiExecutionAllowed: 'executionAllowed',
    LocalAiResultId: 'localAiResultId',
    LocalAiGenerationState: 'generationState',
    LocalAiOutputText: 'outputText',
    LocalAiPrompt: 'prompt',
    LocalAiPromptCharCount: 'promptCharCount',
    LocalAiMaxOutputTokens: 'maxOutputTokens',
    LocalAiTimeoutMs: 'timeoutMs',
    LocalAiDurationMs: 'durationMs',
    LocalAiExitCode: 'exitCode',
    LocalAiStderrByteSize: 'stderrByteSize',
    ManagedBrowserSessionId: 'managedBrowserSessionId',
    ManagedSessionInterventionCapability: 'managedSessionInterventionCapability',
    ManagedState: 'managedState',
    Message: 'message',
    MostRecentKind: 'mostRecentKind',
    MostRecentObserver: 'mostRecentObserver',
    MostRecentSubjectId: 'mostRecentSubjectId',
    MostRecentSubjectKind: 'mostRecentSubjectKind',
    MostRecentSubjectName: 'mostRecentSubjectName',
    NetworkProtocol: 'networkProtocol',
    Observer: 'observer',
    Online: 'online',
    Origin: 'origin',
    ObservedUrl: 'observedUrl',
    ProcessId: 'processId',
    PolicyAction: 'policyAction',
    PolicyDecisionId: 'policyDecisionId',
    PolicyDryRun: 'dryRun',
    PolicyEvidenceReferenceCount: 'evidenceReferenceCount',
    PolicyParentRuleContextReferenceCount: 'parentRuleContextReferenceCount',
    PolicyParentRuleContextRefIds: 'parentRuleContextRefIds',
    ProfileId: 'profileId',
    ProfilePathRef: 'profilePathRef',
    PolicyHandoffState: 'enforcementHandoffState',
    PolicyVersion: 'policyVersion',
    ParentActionReferenceId: 'parentActionReferenceId',
    ParentActionCreatedAt: 'parentActionCreatedAt',
    ParentActorId: 'parentActorId',
    ParentActorRole: 'parentActorRole',
    ParentAssistantActionPreview: 'parentAssistantActionPreview',
    ParentAssistantAnswer: 'parentAssistantAnswer',
    ParentAssistantAnswerState: 'parentAssistantAnswerState',
    ParentAssistantAnswerText: 'parentAssistantAnswerText',
    ParentAssistantApiProviderBoundary: 'parentAssistantApiProviderBoundary',
    ParentAssistantCitationCount: 'parentAssistantCitationCount',
    ParentAssistantEvidenceSummary: 'parentAssistantEvidenceSummary',
    ParentAssistantProviderState: 'parentAssistantProviderState',
    ParentAssistantQuestion: 'parentAssistantQuestion',
    ParentAssistantRequestId: 'parentAssistantRequestId',
    QueryVisibility: 'queryVisibility',
    ProcessAttributionStatus: 'processAttributionStatus',
    ProcessName: 'processName',
    PolicyPreviewId: 'policyPreviewId',
    PolicyReasonCodes: 'reasonCodes',
    PolicyRuleIds: 'ruleIds',
    PolicyTargetType: 'targetType',
    PolicyTargetValue: 'targetValue',
    ParentAssistantThreadId: 'assistantThreadId',
    ParentAssistantMessageId: 'assistantMessageId',
    ParentAssistantRunId: 'assistantRunId',
    ParentAssistantActionIntentId: 'assistantActionIntentId',
    ParentAssistantQuickActionId: 'quickActionId',
    ParentAssistantPromptTemplateId: 'promptTemplateId',
    ParentAssistantStarterCategory: 'starterCategory',
    ParentAssistantInputText: 'inputText',
    ParentAssistantInputSource: 'inputSource',
    ParentAssistantRequiredChildContracts: 'requiredChildContracts',
    ParentAssistantBackendState: 'assistantBackendState',
    Reason: 'reason',
    Returned: 'returned',
    RequestedUrl: 'requestedUrl',
    RequestedAt: 'requestedAt',
    RangeEnd: 'rangeEnd',
    RangeStart: 'rangeStart',
    RollbackToken: 'rollbackToken',
    SchemaVersion: 'schemaVersion',
    ScopeKind: 'scopeKind',
    SourceId: 'sourceId',
    StaleAt: 'staleAt',
    TargetId: 'targetId',
    InterventionAction: 'interventionAction',
    InterventionMechanism: 'interventionMechanism',
    InterventionOutcome: 'interventionOutcome',
    InterventionTargetType: 'interventionTargetType',
    InterventionTargetValue: 'interventionTargetValue',
    TabId: 'tabId',
    TcpState: 'tcpState',
    Transport: 'transport',
    Title: 'title',
    Url: 'url',
    UnmanagedBrowserEnforcement: 'unmanagedBrowserEnforcement',
    StartedAt: 'startedAt',
    WindowId: 'windowId',
  },
  Primitive: {
    String: 'string',
  },
} as const;
