import {
  LanSignedDiscoveryRelayAdapterKindSchema,
  LanSignedDiscoveryRelayAdapterRowSchema,
  LanSignedDiscoveryRelayCacheCheckSchema,
  LanSignedDiscoveryRelayCacheRowSchema,
  LanSignedDiscoveryRelayCustodyLabelSchema,
  LanSignedDiscoveryRelayDecisionStateSchema,
  LanSignedDiscoveryRelayProofStateSchema,
  LanSignedDiscoveryRelayRouteSafetyCheckSchema,
  LanSignedDiscoveryRelayRouteSafetyRowSchema,
  LanSignedDiscoveryRelaySignedProofCheckSchema,
  LanSignedDiscoveryRelaySignedProofRowSchema,
  LanSignedDiscoveryRelaySourceConfidenceSchema,
  LanSignedDiscoveryRelaySpineSchema,
  type LanSignedDiscoveryRelayAdapterKind,
  type LanSignedDiscoveryRelayAdapterRow,
  type LanSignedDiscoveryRelayCacheCheck,
  type LanSignedDiscoveryRelayCacheRow,
  type LanSignedDiscoveryRelayCustodyLabel,
  type LanSignedDiscoveryRelayDecisionState,
  type LanSignedDiscoveryRelayProofState,
  type LanSignedDiscoveryRelayRouteSafetyCheck,
  type LanSignedDiscoveryRelayRouteSafetyRow,
  type LanSignedDiscoveryRelaySignedProofCheck,
  type LanSignedDiscoveryRelaySignedProofRow,
  type LanSignedDiscoveryRelaySourceConfidence,
  type LanSignedDiscoveryRelaySpine,
} from '@ocentra-parent/lan-domain/lan-signed-discovery-relay-spine';
import {
  LanProductionHouseholdProofRuntimeOwnerSchema,
  type LanProductionHouseholdProofRuntimeOwner,
} from '@ocentra-parent/lan-domain/lan-production-household-proof';

export const AgentLanSignedDiscoveryRelayAdapterKindSchema = LanSignedDiscoveryRelayAdapterKindSchema;
export const AgentLanSignedDiscoveryRelaySourceConfidenceSchema = LanSignedDiscoveryRelaySourceConfidenceSchema;
export const AgentLanSignedDiscoveryRelayCustodyLabelSchema = LanSignedDiscoveryRelayCustodyLabelSchema;
export const AgentLanSignedDiscoveryRelayRuntimeOwnerSchema = LanProductionHouseholdProofRuntimeOwnerSchema;
export const AgentLanSignedDiscoveryRelayProofStateSchema = LanSignedDiscoveryRelayProofStateSchema;
export const AgentLanSignedDiscoveryRelaySignedProofCheckSchema = LanSignedDiscoveryRelaySignedProofCheckSchema;
export const AgentLanSignedDiscoveryRelayRouteSafetyCheckSchema = LanSignedDiscoveryRelayRouteSafetyCheckSchema;
export const AgentLanSignedDiscoveryRelayCacheCheckSchema = LanSignedDiscoveryRelayCacheCheckSchema;
export const AgentLanSignedDiscoveryRelayDecisionStateSchema = LanSignedDiscoveryRelayDecisionStateSchema;
export const AgentLanSignedDiscoveryRelayAdapterRowSchema = LanSignedDiscoveryRelayAdapterRowSchema;
export const AgentLanSignedDiscoveryRelaySignedProofRowSchema = LanSignedDiscoveryRelaySignedProofRowSchema;
export const AgentLanSignedDiscoveryRelayRouteSafetyRowSchema = LanSignedDiscoveryRelayRouteSafetyRowSchema;
export const AgentLanSignedDiscoveryRelayCacheRowSchema = LanSignedDiscoveryRelayCacheRowSchema;
export const AgentLanSignedDiscoveryRelaySpineSchema = LanSignedDiscoveryRelaySpineSchema;

export type AgentLanSignedDiscoveryRelayAdapterKind = LanSignedDiscoveryRelayAdapterKind;
export type AgentLanSignedDiscoveryRelaySourceConfidence = LanSignedDiscoveryRelaySourceConfidence;
export type AgentLanSignedDiscoveryRelayCustodyLabel = LanSignedDiscoveryRelayCustodyLabel;
export type AgentLanSignedDiscoveryRelayRuntimeOwner = LanProductionHouseholdProofRuntimeOwner;
export type AgentLanSignedDiscoveryRelayProofState = LanSignedDiscoveryRelayProofState;
export type AgentLanSignedDiscoveryRelaySignedProofCheck = LanSignedDiscoveryRelaySignedProofCheck;
export type AgentLanSignedDiscoveryRelayRouteSafetyCheck = LanSignedDiscoveryRelayRouteSafetyCheck;
export type AgentLanSignedDiscoveryRelayCacheCheck = LanSignedDiscoveryRelayCacheCheck;
export type AgentLanSignedDiscoveryRelayDecisionState = LanSignedDiscoveryRelayDecisionState;
export type AgentLanSignedDiscoveryRelayAdapterRow = LanSignedDiscoveryRelayAdapterRow;
export type AgentLanSignedDiscoveryRelaySignedProofRow = LanSignedDiscoveryRelaySignedProofRow;
export type AgentLanSignedDiscoveryRelayRouteSafetyRow = LanSignedDiscoveryRelayRouteSafetyRow;
export type AgentLanSignedDiscoveryRelayCacheRow = LanSignedDiscoveryRelayCacheRow;
export type AgentLanSignedDiscoveryRelaySpine = LanSignedDiscoveryRelaySpine;
