import {
  AgentCorrelationIdSchema,
  AgentDeviceIdSchema,
  AgentEventAcknowledgementSchema,
  AgentEventAcknowledgementState as AgentEventAcknowledgementStateValue,
  AgentEventAcknowledgementStateLiteral,
  AgentEventAcknowledgementStateSchema,
  AgentEventDeliveryMode as AgentEventDeliveryModeValue,
  AgentEventDeliveryModeLiteral,
  AgentEventDeliveryModeSchema,
  AgentEventEnvelopeSchema,
  AgentEventIdSchema,
  AgentEventNameSchema,
  AgentMessageIdSchema,
  AgentMessageTargetSchema,
  AgentPeerIdSchema,
  AgentPeerRoleLiteral,
  AgentPeerRoleSchema,
  AgentPeerSchema,
  AgentPlatformSchema,
  AgentProtocolSchemaVersion,
  AgentRouteLiteral,
  AgentRouteSchema,
  AgentTimestampSchema,
  SerializedAgentMessageSchema,
  type AgentCorrelationId,
  type AgentDeviceId,
  type AgentEventAcknowledgement,
  type AgentEventAcknowledgementState as AgentEventAcknowledgementStateType,
  type AgentEventDeliveryMode as AgentEventDeliveryModeType,
  type AgentEventEnvelope,
  type AgentEventId,
  type AgentEventName,
  type AgentMessageId,
  type AgentMessageTarget,
  type AgentPeer,
  type AgentPeerId,
  type AgentPeerRole,
  type AgentPlatform,
  type AgentRoute,
  type AgentTimestamp,
  type SerializedAgentMessage,
} from '@ocentra-parent/event-domain/primitives';

export const AgentEventAcknowledgementState = AgentEventAcknowledgementStateValue;
export const AgentEventDeliveryMode = AgentEventDeliveryModeValue;

export {
  AgentCorrelationIdSchema,
  AgentDeviceIdSchema,
  AgentEventAcknowledgementSchema,
  AgentEventAcknowledgementStateLiteral,
  AgentEventAcknowledgementStateSchema,
  AgentEventDeliveryModeLiteral,
  AgentEventDeliveryModeSchema,
  AgentEventEnvelopeSchema,
  AgentEventIdSchema,
  AgentEventNameSchema,
  AgentMessageIdSchema,
  AgentMessageTargetSchema,
  AgentPeerIdSchema,
  AgentPeerRoleLiteral,
  AgentPeerRoleSchema,
  AgentPeerSchema,
  AgentPlatformSchema,
  AgentProtocolSchemaVersion,
  AgentRouteLiteral,
  AgentRouteSchema,
  AgentTimestampSchema,
  SerializedAgentMessageSchema,
};

export type AgentEventAcknowledgementState = AgentEventAcknowledgementStateType;
export type AgentEventDeliveryMode = AgentEventDeliveryModeType;

export type {
  AgentCorrelationId,
  AgentDeviceId,
  AgentEventAcknowledgement,
  AgentEventEnvelope,
  AgentEventId,
  AgentEventName,
  AgentMessageId,
  AgentMessageTarget,
  AgentPeer,
  AgentPeerId,
  AgentPeerRole,
  AgentPlatform,
  AgentRoute,
  AgentTimestamp,
  SerializedAgentMessage,
};
